### ISSUE TITLE
('Connection aborted.', ConnectionResetError(10054, "Connessione in corso interrotta forzatamente dall'host remoto", None, 10054, None))

### ISSUE THREAD

**Issue by LODYZ** [eternnoir/pyTelegramBotAPI#1000]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
 3.7.3
2. What OS are you using?
Windows 10 & CentOS 8 on Virtual Box

3. What version of python are you using?
3.8.6

Hi everyone, I'm new to python and also to pytelegrambotapi.

I created a very simple bot that for about a month did not give me this problem.

This problem has appeared for about a week. I can handle it by exception, but I don't understand why it started appearing.

The bot is very simple:

I have about 400 messages to send on two channels, I send a message every 10 seconds and every 20 messages sleeps one minute.

After 3 hours, delete all messages and start over.

When the bot has to delete the first message, it fails and returns the error. Successive messages do not have problems.

Simplified structure:

`
API_TOKEN='..'
bot = telebot.TeleBot(API_TOKEN) 

function sendmessages():
--FOR LOOP 
----bot.send_photo('@channel1', img, caption=stampa_prodotto_da_stampare)
--FOR LOOP 
----bot.send_photo('@channel2', img, caption=stampa_prodotto_da_stampare)

function delmessages():
--for loop: (channel1)
---bot.delete_message(*id_messaggi_inviati[x])
--for loop: (channel2)
---bot.delete_message(*id_messaggi_inviati[x])

function spam():
--if messages>0:
----delmessages()
--sendmessages()
   

while True:
---spam()
  time.sleep(10800)

`

I hope I have been able to explain enough. Sorry but this is the first time I ask for suggestions

Sorry for my bad english. 

Thanks in advance.

**Comment by BLUE-DEVIL1134** [comment]
the bot must have admin rights and also the message and chat id chould be correct...

**Comment by LODYZ** [comment]
> the bot must have admin rights and also the message and chat id chould be correct...

The bot has permissions in telegram channels. All message ids are correct because when I send a message, I save the id inside a vector.


Only the first message I want to delete gives me an error. If I catch the exception and run the deletion of the same message again, it works without problems.

It is as if it is not good for the telegram API, that the bot waits 3 hours without exchange of communication

**Comment by Badiboy** [comment]
It seems that Telegram close the connection to bot. Just retry on fail.

**Comment by khumoyun2008** [comment]
Wifi problems
telegram issues

**Comment by LODYZ** [comment]
Thank you for the reply guys.

@Badiboy Yes i am doing that 

@khumoyun2008 I am connected with cable and not with wifi

**Comment by icecore2** [comment]
Same to me, the polling seems like limited in the telegrams side so I made a systemd with restart on fail, but some say that webhook solves this issue with the connectivity...

**Comment by icecore2** [comment]
@Badiboy why you closed it without any solution?
I'm following this issue because I have the same issue...

**Comment by Badiboy** [comment]
@icecore2 
The solution is given and the issue author confirms that it works.
![image](https://user-images.githubusercontent.com/5613421/99882965-1c065d00-2c35-11eb-9ffe-d503a5ed55bd.png)

**Comment by icecore2** [comment]
Sorry for keeping replying buy, there's no solution... He said thanks for the reply and confirmed the comments solution but no as reloved the problem or so, am I missing the solution somewhere?

**Comment by Badiboy** [comment]
@icecore2 
![image](https://user-images.githubusercontent.com/5613421/99883440-8e2c7100-2c38-11eb-8e25-a65c3300f248.png)

**Comment by khumoyun2008** [comment]
The exception is from requests package. Perhaps need to replace requests package.
There is a network problem between your server and telegram's api.

and:
Can you try adding this line before polling()? 


apihelper.RETRY_ON_ERROR = True
bot.polling()

if u r on ubuntu vps, use service files
