### ISSUE TITLE
How do I get the reply_markup object from a message?

### ISSUE THREAD

**Issue by todorov-png** [eternnoir/pyTelegramBotAPI#1003]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
new
2. What OS are you using?
windows 10
3. What version of python are you using?
3
How to add a button to a message that already has a button, but not to delete the previous button? Or how to hide (not delete) a button?

**Comment by Badiboy** [comment]
You cannot...

**Comment by alexmechanic** [comment]
>    How to add a button to a message that already has a button, but not to delete the previous button? Or how to hide (not delete) a button?

The only suggestion I can give is to initialise the InlineKeyboardMarkup object with some buttons in prior and then add/remove needed buttons when you should
