### ISSUE TITLE
How to schedule message?

### ISSUE THREAD

**Issue by Neykuratick** [eternnoir/pyTelegramBotAPI#1006]
I couldn't find an option to schedule a post to a channel using this library, is there any?

**Comment by Badiboy** [comment]
Seems that Bot API does not provide scheduling... I did not find anything for that...

**Comment by Neykuratick** [comment]
> Seems that Bot API does not provide scheduling... I did not find anything for that...

do you know a way how to schedule a message on telegram? The only thing I found uses Schedule and other python libraries, but it requires the script to run 24/7, I can't afford that

**Comment by khumoyun2008** [comment]
https://pypi.org/project/schedule/

**Comment by khumoyun2008** [comment]
use this

**Comment by Neykuratick** [comment]
> use this

thank you for the suggestion, but I need to send exactly scheduled messages to the channel because I want to run my script only once, not 24/7

**Comment by khumoyun2008** [comment]
there is answer

**Comment by khumoyun2008** [comment]
schedule.every().day.at("10:30").do(job)
then some code, see on pypi: https://pypi.org/project/schedule/

**Comment by Neykuratick** [comment]
oh, thank you!
