### ISSUE TITLE
How to use MTProto Proxy?

### ISSUE THREAD

**Issue by walkman99** [eternnoir/pyTelegramBotAPI#1007]
Hello!
I cannot find example how to use mtproto proxy with this API. Please, help.

**Comment by MasterGroosha** [comment]
Telegram Bot API doesn't support MTProxy. If you don't want to use SOCKS-proxy (supported by pyTelegramBotAPI) and really sure you need MTProxy, please take a look at Telegram Client API libraries like [Telethon](https://docs.telethon.dev/en/latest/)

MTProxy example for Telethon: https://docs.telethon.dev/en/latest/basic/signing-in.html#using-mtproto-proxies
