### ISSUE TITLE
How to use new method copyMessage?

### ISSUE THREAD

**Issue by 1byari** [eternnoir/pyTelegramBotAPI#1009]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.3

2. What OS are you using?
Linux Mint 20

3. What version of python are you using?
3.8.2
I'm trying to do something like this: bot.copy_message(@mychannel, chat_id, message_id), but an error appears in the terminal: AttributeError: 'TeleBot' object has no attribute 'copy_message'

**Comment by BLUE-DEVIL1134** [comment]
even if the bot api is 5.0 
pytelegrambotapi isnt updated yet

**Comment by Olegt0rr** [comment]
While you're waiting for `pyTelegramBotAPI` update, you can try all new API 5.0 methods via [aiogram](https://github.com/aiogram/aiogram/)

**Comment by khumoyun2008** [comment]
I have created a new pull request. I have added copy message. So wait some time, and i also have added exceptions, not all
after my pull request is verified u can use copy message

**Comment by khumoyun2008** [comment]
so now u can close this issue
