### ISSUE TITLE
Telegram API timeout parameter for long polling on getUpdates not used?

### ISSUE THREAD

**Issue by VersilPerihelion** [eternnoir/pyTelegramBotAPI#1010]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.3

2. What OS are you using?
Ubuntu 20.04.1

3. What version of python are you using?
3.8.5
---
Is it a deliberate change that getUpdates requests made by the bots no longer use Telegram API's timeout parameter for long polling?
In apihelper, in `_make_request`:
```python
    if params:
        if 'timeout' in params:
            read_timeout = params.pop('timeout') + 10
        if 'connect-timeout' in params:
            connect_timeout = params.pop('connect-timeout') + 10
```
`timeout` is removed from query string params,
```python
        result = _get_req_session().request(
            method, request_url, params=params, files=files,
            timeout=(connect_timeout, read_timeout), proxies=proxy)
```
and not restored in any way afterwards, calling getUpdates without it.

And as expected from the timeout parameter not sent to the API and the API docs saying it defaults to 0, I'm seeing empty responses arriving immediately, rather than only with no updates after the desired timeout.

Have not found any prior issue mentioning it, and traced the change to May, to PR #848 where accessing `timeout` from the `params` dict was replaced with calling `.pop` on it.

**Comment by Badiboy** [comment]
Telegram API has nothing about timeouts.
All timeouts are on the client side.
https://core.telegram.org/bots/api#getting-updates

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/commit/7a3fd30f6ac7c06e39673665f9ec2817ad64294c

**Comment by Badiboy** [comment]
**long_polling_timeout** parameter added to _polling / infininty_polling_ and correspondent internal functions.

**timeout** left for "connection timeout" for compatibility with old code and other functions.
