### ISSUE TITLE
How to make callback_query_handler forget things?

### ISSUE THREAD

**Issue by Chrysalida** [eternnoir/pyTelegramBotAPI#1015]
Hi guys,

I use callback_query_handler this way:
User sends any text message, bot asks if the user wants him to forward the message to admin, and shows buttons "Yes" and "No". If the answer is "yes", the message is forwarded to another user (admin).

I'm trying to make it work with every text message, but the handler remembers the first message in the session forever, and deliver to admin the first message every time, no matter what was the user's new text.

What I'm doing wrong? I've also tried to pass the message text to the function as an additional argument, but failed.

here is the sample code:

`@bot.message_handler(content_types=['text'])
  def get_text_messages(message):

    mess=""
    mess = message.text.lower()

    if mess =="hi"
        print('User wrote: ',mess)

    else:
        keyboard=types.InlineKeyboardMarkup();
        key_yes=types.InlineKeyboardButton(text="Y",callback_data='yes');
        key_no=types.InlineKeyboardButton(text="N",callback_data='no');
        keyboard.add(key_yes,key_no)
        bot.send_message(message.from_user.id,text='Forward to admin?", reply_markup=keyboard)

        @bot.callback_query_handler(func=lambda call: True)
        def forwarder(call):

            if call.data=='yes':   
                bot.send_message(<ADMIN's USER ID',mess)

            else:
                bot.send_message(message.from_user.id,"Ok, I won't")`

bot.polling(none_stop=True,interval=0)

Thank you in advance

**Comment by Badiboy** [comment]
Message is in query.message.

**Comment by Chrysalida** [comment]
> Message is in query.message.

I still can't reach it. Do you mean call.message.text?

**Comment by Badiboy** [comment]
CallbackQuery.message is the bot's message which comes along with the keyboard, but not the message that triggered the query_handler.

What is the difference between "message which comes along with the keyboard" and "message that triggered the query_handler"? Query handler is triggered by the inline button which is attached to the message which comes with the keyboard.

**Comment by Chrysalida** [comment]
> > CallbackQuery.message is the bot's message which comes along with the keyboard, but not the message that triggered the query_handler.
> 
> What is the difference between "message which comes along with the keyboard" and "message that triggered the query_handler"? Query handler is triggered by the inline button which is attached to the message which comes with the keyboard.

The difference is one message is being sent by user, and the other - by the bot :)

**Comment by Chrysalida** [comment]
Well,
I seem to have solved the issue: it was all about the wrong visibility level of the user variable that stores user's message text. 
As for the callback_query, as far as I can see, it doesn't store the user's message anywhere in its json.
