### ISSUE TITLE
integration with other library

### ISSUE THREAD

**Issue by nogaevskii** [eternnoir/pyTelegramBotAPI#1018]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 3.7.3
2. What OS are you using?
Ubuntu 20.04
3. What version of python are you using?
3.5

Hello! Creator, answer me please, how i can do integration this library with telethon by LonamiWebs?
all my try's have been error with this mistake
`raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.`

**Comment by Badiboy** [comment]
No description what you are doing.
