### ISSUE TITLE
Can't seem to get echo_bot.py working :(

### ISSUE THREAD

**Issue by aimanbaharum** [eternnoir/pyTelegramBotAPI#102]
Pls excuse my naive problem, but I'm trying to run `echo_bot.py` in command line but it does nothing. I already replace the token inside the file. Do I expect something to type after running it?

It stops at `bot.polling()` and it just stuck there, no input no nothing. Unless I ctrl+c

![nothing.jpg](http://i.imgur.com/hfsbQ6b.jpg)

Help me starting up with this. Thank you.

**Comment by analca3** [comment]
You need to send a message to your bot inside Telegram.

**Comment by aimanbaharum** [comment]
Ahh, that's how it works. Thanks!
