### ISSUE TITLE
A problem with send_photo method

### ISSUE THREAD

**Issue by ubiquitousVN** [eternnoir/pyTelegramBotAPI#1021]
There is a buggy issue with `send_photo()` when it is used in a byte-image way. Given an `open('photo', 'rb')` as a second argument, it raises an AttributeError _"module 'PIL' has no attribute Image"_. Which means that Python does an attribute lookup `PIL.Image` that is interpreted as incorrect due to Image being not an attribute. Actually, I looked in the apihelper.py which calls `is_pil_image(var)` from util.py and it has an `isinstance(var, PIL.Image.Image)` function call. This is what raises an Error. After I changed it to `from PIL import Image` and `isinstance(var, Image.Image)`, an AttributeError disappeared and the photo was possible to be sent.

1. pyTelegramBotAPI 3.7.3

2. Windows 10

3. Python 3.8.5

**Comment by Badiboy** [comment]
It was fixed here: https://github.com/eternnoir/pyTelegramBotAPI/commit/81100f249cbec7f89f07c0fd62e02b397399bb96

Wait for the next published version (should be done soon) or install the recent version from GIT.
