### ISSUE TITLE
Run on AWS EC2 and Webhook with Flask

### ISSUE THREAD

**Issue by barbax7** [eternnoir/pyTelegramBotAPI#1024]
Hi!
Not actually an issue, but a question.
I would like to use webhook for my telegram bot. It is on AWS EC2 machine, but I'm not able to use webhooks with Flask because I don't understand how to set host, port, webhook address, and similar.
Lately, I used ngrox, which provides a tunnel from a web address to localhost. It works but running ngrox spends CPU time. 
I need another solution, quite simple. Someone can explain to me how to set it?

I use Python 3 (3.8)
Version of pyTelegramBotAPI -- 3.7.1

**Comment by alexmechanic** [comment]
I use webhooks with Flask in my project, take a look: https://github.com/alexmechanic/DH5AssassinsGWBot/blob/117afe8ce2d53bb02a145284c6604ab9de79bd9d/bot.py#L811
Perhaps it can help you

**Comment by barbax7** [comment]
> I use webhooks with Flask in my project, take a look: https://github.com/alexmechanic/DH5AssassinsGWBot/blob/117afe8ce2d53bb02a145284c6604ab9de79bd9d/bot.py#L811
> Perhaps it can help you

Thanks for your help.
I don't know why, but in aws i can't set the host for flask app

`Traceback (most recent call last):
  File "testbarbax.py", line 51, in <module>
    app.run(host="0.0.0.0", port=int(os.environ.get('PORT', 80)),debug=True)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
PermissionError: [Errno 13] Permission denied`

**Comment by SteveImmanuel** [comment]
Do you perhaps haven't configured the SSL certificate in your EC2? Because Telegram won't send the messages via HTTP. They only accept HTTPS.
