### ISSUE TITLE
is there a middleware in this library that works AFTER all other handlers, not BEFORE!?

### ISSUE THREAD

**Issue by SeruiosBoss** [eternnoir/pyTelegramBotAPI#1027]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? newest one

2. What OS are you using? win 10

3. What version of python are you using? 3.8

is there a middleware in this library that works AFTER all other handlers, not BEFORE!?

**Comment by Badiboy** [comment]
Nope...
