### ISSUE TITLE
Problem with next step handlers 

### ISSUE THREAD

**Issue by elchami89** [eternnoir/pyTelegramBotAPI#1028]
Hi, I'm using pyTelegramBotAPI 3.7.4 with python 3.8 on Windows 10 (PyCharm 2020.2)

My problem is that I can't use the handlers in a separate module from the main module.

I implement the example [step_example](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/step_example.py) and it works perfectly. But when I take the methods [process_name_step(message)](https://github.com/eternnoir/pyTelegramBotAPI/blob/a4d0b685b57153167dbb87daf63a238f8318856b/examples/step_example.py#L33), [process_age_step(message)](https://github.com/eternnoir/pyTelegramBotAPI/blob/a4d0b685b57153167dbb87daf63a238f8318856b/examples/step_example.py#L45) and [process_sex_step(message)](https://github.com/eternnoir/pyTelegramBotAPI/blob/a4d0b685b57153167dbb87daf63a238f8318856b/examples/step_example.py#L63) to another module (for example another_module.py) and I change the call 
_bot.register_next_step_handler(msg, process_name_step)_ 
to 
_bot.register_next_step_handler(msg, another_module.process_name_step)_
and launched the program again, I get stuck on _process_name_step_ and the program doesn't handle the _process_age_step_.

Please, help me find out what I am doing wrong.

I attach a screenshot where my process finish
![image](https://user-images.githubusercontent.com/22843370/100853837-85ce0480-3488-11eb-9ea4-77ebeeefff10.png)

Thanks.

**Comment by Badiboy** [comment]
Cannot reproduce. Please, provide working code sample.
