### ISSUE TITLE
The unpin_chat_message and unpin_all_chat_messages methods do not work

### ISSUE THREAD

**Issue by todorov-png** [eternnoir/pyTelegramBotAPI#1030]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 3.7.4
2. What OS are you using?
Windows 10
3. What version of python are you using?
python 3.8
![photo_2020-12-03_00-44-34](https://user-images.githubusercontent.com/61319839/100947375-97f68400-3516-11eb-8035-406d1e1b6acd.jpg)
The unpin_chat_message and unpin_all_chat_messages methods do not work, you need to update them and add the message_id parameter as it was done in API 5.0

**Comment by Badiboy** [comment]
New unpin mode and unpin_all are not published yet.

Wait for the next published version or install the recent version directly from GIT.
