### ISSUE TITLE
Get FIRST messages in a chat

### ISSUE THREAD

**Issue by QuAzI** [eternnoir/pyTelegramBotAPI#1032]
I want to delete all messages older than 1 month. So how can I get first available message in chat and enumerate messages to remove. And how can I check if message with specific id present to prevent "Error code: 400. Description: Bad Request: message to delete not found"

**Comment by Badiboy** [comment]
Bot get messages only when new messages appear. You cannot get ANYTHING that was not sent by Telegram to your bot.
