### ISSUE TITLE
Troubles with disabling parse_mode after setting default to "Markdown"/"HTML"

### ISSUE THREAD

**Issue by Gleefre** [eternnoir/pyTelegramBotAPI#1034]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.7.3

2. What OS are you using? Ubuntu 20

3. What version of python are you using? 3.8.5

After setting default for `parse_mode` to "Markdown"/"HTML", to send a
message without "Markdown"/"HTML" you can't just use `parse_mode`
parameter in `send_message`.
```
bot = TeleBot("token", parse_mode="Markdown")
bot.send_message(chat_id, text, parse_mode=None)  # This will use Markdown"
```
As I understand, this happens because in `send_message` `parse_mode` equals `None` by
default, so setting it to `None` won't change anything.
So instead, I set `bot.parse_mode` to `None` before sending a message and set it back
to "Markdown" at the end.
```
bot.parse_mode = None
bot.send_message(chat_id, text)  # This won't use Markdown
bot.parse_mode = "Markdown"
```
But this is a weird solving, so, I want to:
```
bot.send_message(chat_id, text, parse_mode="plain_text")
```

**Comment by Badiboy** [comment]
Try to use 
`parse_mode = ""`
?

**Comment by Gleefre** [comment]
It doesn't help. I think it is because of the check in the `send_message`:
```
parse_mode = self.parse_mode if not parse_mode else parse_mode
```
And `""` is False.

Just to be sure that I understand you correctly:
```
def test(token, chat_id):
    from telebot import TeleBot
    bot = TeleBot(token, parse_mode="Markdown")
    bot.send_message(chat_id, '*bold*')
    bot.send_message(chat_id, '*bold*', parse_mode=None)
    bot.send_message(chat_id, '*bold*', parse_mode='')
```
All three messages were the same.

**Comment by BLUE-DEVIL1134** [comment]
> It doesn't help. I think it is because of the check in the `send_message`:
> 
> ```
> parse_mode = self.parse_mode if not parse_mode else parse_mode
> ```
> 
> And `""` is False.
> 
> Just to be sure that I understand you correctly:
> 
> ```
> def test(token, chat_id):
>     from telebot import TeleBot
>     bot = TeleBot(token, parse_mode="Markdown")
>     bot.send_message(chat_id, '*bold*')
>     bot.send_message(chat_id, '*bold*', parse_mode=None)
>     bot.send_message(chat_id, '*bold*', parse_mode='')
> ```
> 
> All three messages were the same.

seems you are doing wrong.
the following are the working codes
```python
from telebot import TeleBot


bot = TeleBot(token)

@bot.message_handlers(commands=['start','help'])
def send_message_for_start_and_help(message):
    bot.send_message(message.chat.id, '*bold*', parse_mode='md') # Markdown
    bot.send_message(chat_id, '*bold*') #Normal Text
    bot.send_message(chat_id, '<b>bold</b>', parse_mode='html') #Html
```

Note -> Sometimes Markdown Dosen't Works Properly, So Better To Use HTML

**Comment by Badiboy** [comment]
@Gleefre this is an easier way to fix. :)

I tested: Telegram accepts parse_mode = "" as "no parse mode". So now "None" and "" works different: None - default, "" - no parse.

You can try this: 
https://github.com/eternnoir/pyTelegramBotAPI/commit/65c3ca58da9a787084cfaecbdaee9f97b9b709df

**Comment by Gleefre** [comment]
Thanks, it works now.
