### ISSUE TITLE
get_updates high delay with 3.7.4

### ISSUE THREAD

**Issue by bestnaf** [eternnoir/pyTelegramBotAPI#1036]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.7.4

2. What OS are you using? Linux Ubuntu 20

3. What version of python are you using? 3.8

After update - Get_updates started to hang the code for almost 20 second with version 3.7.4.
If I rollback to 3.7.3 it takes less then a second to poll data.

code:
bot = telebot.TeleBot(TOKEN)
bot.process_new_updates(bot.get_updates(offset=(bot.last_update_id + 1), timeout=20))

Please advice what was changed - I see nothing related to this in commits

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/commit/03e1aef70e25d8ed5f218ff25c80eb57372d2eb9

timeout behaviour was aligned.

Previously parameter "timeout" in get_updates was used as long_polling_timeout. It did not allow to set connection timeout for this API call.

Now there are two different parameters in get_updates:

>         :param timeout: Integer. Request connection timeout
>         :param long_polling_timeout. Timeout in seconds for long polling.

So for your case you should use:
```
bot = telebot.TeleBot(TOKEN)
bot.process_new_updates(bot.get_updates(offset=(bot.last_update_id + 1), long_polling_timeout=20, timeout = None))
```
It should restore your previous behaviour. Later you can adjust timeout to the value you prefer.

Please, let me know if it will restore the behaviour.

**Comment by bestnaf** [comment]
Unfortunately same behaviour with new options:
long_polling_timeout=20, timeout = None
However setting long_polling_timeout to 1 returned previous behaviour, what is kinda odd

**Comment by Badiboy** [comment]
Hmm... May be like this. Could you please also try

```
bot = telebot.TeleBot(TOKEN)
bot.process_new_updates(bot.get_updates(offset=(bot.last_update_id + 1), long_polling_timeout=20, timeout = 1))
```

?
