### ISSUE TITLE
bot.get_chat does not work

### ISSUE THREAD

**Issue by todorov-png** [eternnoir/pyTelegramBotAPI#1038]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 3.7.4
2. What OS are you using?
Windows 10
3. What version of python are you using?
python 3.8

I use the asynchronous version of the library and bot.get_chat (chat_id = @username) .wait () does not work for me, if I work through an id, then everything works, but does not want to use a nickname, writes "ERROR - TeleBot:" A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: cha t not found "" What could be the problem? I need to find out a person's ID through his nickname, maybe there are other ways?

**Comment by Badiboy** [comment]
Bot have access only to chats to which bot was added. You cannot scan arbitrary chats / users by username.

**Comment by todorov-png** [comment]
> Боту доступны только те чаты, в которые был добавлен бот. Вы не можете сканировать произвольные чаты / пользователей по имени пользователя.


and then how to get the ID of a person in the chat where there is a bot by nickname?
