### ISSUE TITLE
Properly parsing mentions (both with usernames and without)

### ISSUE THREAD

**Issue by DefiDebauchery** [eternnoir/pyTelegramBotAPI#1039]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.4
2. What OS are you using?
macOS
3. What version of python are you using?
3.9
---

I'm trying to get the best handle on how to properly parse user mentions; I understand that there's an `entities` structure for each incoming message, but the behavior seems inconsistent.

I've set up a test bot with a very simple test:

```py
@bot.message_handler(commands=['test'])
def test_message(message):
    print(message.entities[1])
```

I have two users: One with a username (`@WithUsername`), and one without (`NoUsername`).
As `@WithUsername`, I send the command `/test NoUsername`, and I get exactly what I'd expect:

```{'type': 'text_mention', 'offset': 6, 'length': 10, 'url': None, 'user': {'id': 12345678, 'is_bot': False, 'first_name': 'NoUsername', 'username': None, 'last_name': '', 'language_code': 'en', 'can_join_groups': None, 'can_read_all_group_messages': None, 'supports_inline_queries': None}, 'language': None}```

However, in reverse, when `NoUsername` sends the message `/test @WithUsername`, I just get generic info:

```{'type': 'mention', 'offset': 6, 'length': 13, 'url': None, 'user': None, 'language': None}```

Interestingly, I also get this simple mention structure if I'm `NoUsername` and tag myself (e.g. `/test NoUsername`)

What is it that I need to do to ensure that I can get a User structure with any/every type of mention within a command?

**Comment by Badiboy** [comment]
I re-read your message. And see that everything is fine. 

Telegram does not report you any user information when you use simple @name mention.

**Comment by DefiDebauchery** [comment]
Hi. Just to clear any ambiguity, when you say `@name`, are you referring to the username or bare name (without username)? You would think you'd get user info with a `@username` mention moreso than a mention without one.

**Comment by Badiboy** [comment]
pyTBA is just a Telegram Bot API wrapper. It do nothing that Telegram Bot API do not provide.
