### ISSUE TITLE
Sending some images (gifs) is delayed until next image is requested

### ISSUE THREAD

**Issue by oleg-sh** [eternnoir/pyTelegramBotAPI#104]
Sometimes when I request an image (gif) from tg client nothing is sent back although "moving filename" is seen in ssh terminal. Once I request another image — 2 images are sent back (if 2nd is jpeg) or just the 1st one if 2nd is a gif too. 

It also works if I stop the bot after 1st request and request a 2nd image.
This is strange. Any ideas why this is happening?

My code:
```
def send_gif_or_image(fn,message):
    if os.path.exists(fn):
        ext = fn.split(".")[-1]
        if os.path.exists("sent." + ext): os.remove("sent." + ext)
        os.rename(fn, "sent." + ext)
        print('moving: ' + fn)
        if (ext == "gif"):
            doc = open("sent." + ext, 'rb')
            bot.send_document(message.chat.id, doc)
            return
        else:
            photo = open("sent." + ext, 'rb')
            bot.send_photo(message.chat.id, photo)
            return
```

**Comment by eternnoir** [comment]
Try to add doc.close() and photo.close() after bot send.

**Comment by oleg-sh** [comment]
Thanks. I've just tried it and it didn't help much but I've noticed that if I wait 45-75 seconds the gif appears in tg client.
The file is only 2MB and the bot account is only used by one code instance.
I am able to do the same on the same files without pyTelegramBotAPI and it only takes 1-2 seconds to arrive.

**Comment by oleg-sh** [comment]
Looks like this is server-side issue, so I'll close it.
The best workaround I've found so far is uploading the gif animations in advance and forwarding them once required.
