### ISSUE TITLE
unban_chat_member in AsyncTeleBot is down!

### ISSUE THREAD

**Issue by todorov-png** [eternnoir/pyTelegramBotAPI#1041]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
new
2. What OS are you using?
windows 10
3. What version of python are you using?
3.8
unban_chat_member in AsyncTeleBot does not work, it does not give an error, it just does not work, everything works in TeleBot.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1046

Try with this patch.
