### ISSUE TITLE
Problem with downloadind voice message

### ISSUE THREAD

**Issue by dannkunt** [eternnoir/pyTelegramBotAPI#1042]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.4 after issuse updated on latest git

2. What OS are you using?
Manjaro linux Kde

3. What version of python are you using?
3.9.0

I'm trying to download vioce message but lib just adds tread every amount of seconds on 44 line. File does not load btw

```

@bot.message_handler(content_types=["voice"])
def recognize_voice(message: types.Message) -> None:
    bot.send_chat_action(message.chat.id, "typing")

    if message.chat.id in pending:
        bot.send_message(message.chat, "Вы уже сканируете голосовое, дождитесь завершения")
        return

    with open(f_name := f'/temp/{message.chat.id}.ogg', 'wb') as file:
        file.write(bot.download_file(bot.get_file(message.voice.file_id).file_path))
    bot.send_message(message.chat.id, "File saved")
```

![изображение](https://user-images.githubusercontent.com/32395839/102123164-a10d1c80-3e57-11eb-8e03-aacd718a5843.png)

![изображение](https://user-images.githubusercontent.com/32395839/102123472-f0534d00-3e57-11eb-89ab-e6221b210e76.png)

**Comment by Badiboy** [comment]
> open(f_name := f'/temp/{message.chat.id}.ogg', 'wb')

1. What is "f_name :=" ?

2. Did you checked that writing to this file path is successfull? Could you try to write non-telegram data there?

**Comment by dannkunt** [comment]
1. Assignment Expression, they were added to python 3.8. [More](https://www.python.org/dev/peps/pep-0572/)

2. Not before creation Issuse. Now checked and it was unsucsesful. After creating temp dir and changind path to temp/name.ogg everything works. Thanks.

I thing there should be fix in telebot for threads and error output in this case.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1053

Could you please reproduce the file problem and check the behaviour with this patch?

**Comment by dannkunt** [comment]
This problem no longer occurs but telebot logger don't work. It could be due to [loguru](https://github.com/Delgan/loguru)

**Comment by Badiboy** [comment]
Logging is not in the scope of this issue. :)

Thank you, closing.
