### ISSUE TITLE
Problem bot.SendGame

### ISSUE THREAD

**Issue by korkinmask** [eternnoir/pyTelegramBotAPI#1044]
END VERSION

I don't understand how you can bind a link to a button (for example: Play a game)

I know what answer_callback_query is, but I don't understand how to do it correctly. I ask for help)))
Can I have a working example?)

RUS VERSION

Не понимаю как можно привязать ссылку к кнопке (например: Играть в игру)

знаю, что answer_callback_query, но не понимаю как это сделать правильно. Прошу помощи ))) 
Можно рабочий пример?)

**Comment by Badiboy** [comment]
Так "привязать ссылку" или "играть в игру"? Или к кнопке? Или sendGame?

**Comment by korkinmask** [comment]
> Так "привязать ссылку" или "играть в игру"? Или к кнопке? Или sendGame?

Изначально при send.Game кнопка пустая 
![Снимок экрана 2020-12-15 в 20 04 03](https://user-images.githubusercontent.com/76049284/102247376-ed686300-3f10-11eb-9266-52f65dfc8aff.png)

При нажатии на нее должен обрабатываться CallBack. 

Но я сделал такой код:
game = 'cyberxkurskay'
bot.sendGame(chat_id,game_short_name='game')
bot.answerCallbackQuery(callback_query_id='game',url='https://yandex.ru')


На просторах интернета я нашел следующий код:

bot.onText(/\/start/, function onPhotoText(msg) {
  bot.sendGame(msg.chat.id, gameName);
});

bot.on('callback_query', function onCallbackQuery(callbackQuery) {
  bot.answerCallbackQuery(callbackQuery.id, { url });
});


Что можно сделать чтобы кнопка имела под собой какой то смысл ))

**Comment by Badiboy** [comment]
Я продолжаю непонимать, при чем здесь игра.

Вы написали игру, совместимую с телеграммом?
Или вы просто хотите получить коллбэк?
Или вы хотите сделать просто кнопку, в ответ на кокторую почему-то посылаете в яндекс? 
Почему у вас на скрине текст "Play CyberX_Kurskaya", которого нет в коде?

Мы в шарады играем, да?

**Comment by korkinmask** [comment]
> Я продолжаю непонимать, при чем здесь игра.
> 
> Вы написали игру, совместимую с телеграммом?
> Или вы просто хотите получить коллбэк?
> Или вы хотите сделать просто кнопку, в ответ на кокторую почему-то посылаете в яндекс?
> Почему у вас на скрине текст "Play CyberX_Kurskaya", которого нет в коде?
> 
> Мы в шарады играем, да?

Нет, никаких шарад. 

По умолчанию когда создаёшь игру через @BotFather. И при отправке игры (т.е. Sendgame с идентификатор ом игры который мы указывали в BotFather.) Telegram автоматически добавляет в кнопку текст.
Но вот как обработать действие при нажатии этой кнопки. Я незнаю. В интернете в целом информации о создании игр в телеграм, не очень много. Поэтому решил обратиться к вам как к разработчику данной библиотеки. Может сможете помочь. 

По документации телеграмма, после нажатия на кнопку например (Play Lumberjack), происходит Callback с идентификатором game_short_name. Но вот как его обработать, я не понимаю.

**Comment by g0thb0iclique** [comment]
> По документации телеграмма, после нажатия на кнопку например (Play Lumberjack), происходит Callback с идентификатором game_short_name. Но вот как его обработать, я не понимаю.
`
@bot.message_handler(func=lambda message: True, commands=['start'])
def start(message):
	m= types.InlineKeyboardMarkup()
	m.add( types.InlineKeyboardButton(text='Играть', callback_game='game_short_name') )
	bot.send_game(message.from_user.id, 'game_short_name', reply_markup=m)
	
@bot.callback_query_handler(func=lambda call: True)
def returnGame(call):
	bot.answer_callback_query(call.id, url='https://URL_ИГРЫ/')`
