### ISSUE TITLE
webhook flask and schedule do not work

### ISSUE THREAD

**Issue by todorov-png** [eternnoir/pyTelegramBotAPI#1045]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
new
2. What OS are you using?
window 10
3. What version of python are you using?
3,8
I use Webhook flask and schedule, and so it doesn't work with the webhook, the timer doesn't work, everything worked fine on the poling, but not on the webhook ... how to fix it? the bot is on pythonanywhere
![image](https://user-images.githubusercontent.com/61319839/102280935-11429d80-3f3f-11eb-8123-8ad621ddb117.png)

**Comment by Badiboy** [comment]
I see no flask here.
