### ISSUE TITLE
'TeleBot' object has no attribute 'default_middleware_handlers'

### ISSUE THREAD

**Issue by ModischFabrications** [eternnoir/pyTelegramBotAPI#1047]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.7.4

2. What OS are you using? Win 10

3. What version of python are you using? 3.9

----------------------
Trying to register a middleware handler like

```
@bot.middleware_handler()
def print_channel_post_text(bot_instance, update):
    print(update.update_id)
```

throws an exception:

`'TeleBot' object has no attribute 'default_middleware_handlers'`

Looking through the test cases it seems like that implementation has no coverage either, might be broken?

**Comment by ModischFabrications** [comment]
Oh, I figured it out. I has to add `apihelper.ENABLE_MIDDLEWARE = True` before the initialization of TeleBot. 

Might want to catch this error with a more verbose error and add a hint to #middleware-handler?

I could try a pull request if wanted, shouldn't be too big a change.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1052
