### ISSUE TITLE
polling() blocks my script

### ISSUE THREAD

**Issue by matan20** [eternnoir/pyTelegramBotAPI#1048]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.4

2. What OS are you using?
Win 10 Pro

3. What version of python are you using?
3.9.1

Hello,

bot = telebot.TeleBot(token=...)
bot.polling() 

is blocking my script. I searched the web and documentation and it seems like it should be a seperate thread and not block my script. 

What do I do wrong?

Thanks in advance!

**Comment by Badiboy** [comment]
It is.

Use threads.

**Comment by matan20** [comment]
Like this?

x = threading.Thread(target=bot.polling)
x.start()
