### ISSUE TITLE
Trace bot with reward it possible with the api?

### ISSUE THREAD

**Issue by mikegrep** [eternnoir/pyTelegramBotAPI#1051]
Simple question I want to make a bot witch.Soon as you start send you a message with link witch the user need to send to 4 of his friend if they joint the chanel bot send reward picture.It can be made with pyTelegramBotAPI and what steps i need to follow.Thanx
Thats it a deep link bot or ?

**Comment by BLUE-DEVIL1134** [comment]
this can be made with any language
any library

but its not a question to be asked here
its your own work

`PyTelegeamBotAPI` Has its documentation and you can make the bot by reading that only..

Theese types Of Questions Are Asked On StackOverFlow And Not Here
u make issues here if you have any doubt documentation or bug or feature-request

So close this issue,
Its Completely **Invalid!**

**Comment by mikegrep** [comment]
What is the name of that kind of bot.Deep link bot or ?

**Comment by BLUE-DEVIL1134** [comment]
> What is the name of that kind of bot.Deep link bot or ?

**Telegram bots have a deep linking mechanism, that allows for passing additional parameters to the bot on startup. It could be a command that launches the bot — or an auth token to connect the user's Telegram account to their account on some external service.**
