### ISSUE TITLE
ConnectionResetError with long running bot instance

### ISSUE THREAD

**Issue by ModischFabrications** [eternnoir/pyTelegramBotAPI#1057]
1. What version of pyTelegramBotAPI are you using? 3.7.4

2. What OS are you using? probably Raspbian

3. What version of python are you using? 3.6.9

A user of a bot of mine has problems where a long running instance is crashing regularly (https://github.com/ModischFabrications/MineGramBot/issues/4). The issue seems to be in the session handling of pyTelegramBotAPI. I already looked at https://github.com/eternnoir/pyTelegramBotAPI/pull/483, but it does not seem to fix this problem. See the log attached to the issue for details. 

A easy fix would be to wrap my call to `bot.polling(none_stop=True)` in a while loop and restart on error, but this is hardly a solution.

**Comment by Badiboy** [comment]
Use
`bot.infinity_polling`

**Comment by ModischFabrications** [comment]
Thanks a lot, that looks like the hotfix I was trying to implement. Seems a bit like a hack to catch all exceptions and restart, but I guess it works. Closing this issue.

**Comment by ModischFabrications** [comment]
One last thing: Won't this suppress all "real" exceptions thrown by user code? Seems dangerous...

**Comment by Badiboy** [comment]
> Won't this suppress all "real" exceptions thrown by user code?

Unhandled - yes, it will. But they will be logged by logger.error, so you can see them.
Additionally you can use... **exception_handler** parameter of TeleBot constructor to route excetions to your own exception handler.
