### ISSUE TITLE
There is no Traceback in stdout in Django/webhook config

### ISSUE THREAD

**Issue by yankevych** [eternnoir/pyTelegramBotAPI#1059]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.7.4.

2. What OS are you using? Ubuntu 20.04.1 LTS

3. What version of python are you using? Python 3.8.5

There is no Traceback in stdout when I'm using Django as a framework and set_webhook method. I didn't see tracebacks (like AttributeError: '****' object has no attribute '***'  or 'ValueError' or similar) ONLY in functions that decorate with 'handler' decorators. In other - all is fine.
When the Interpreter finds an Error - the program stopped and nothing happened. 

When I deprecated ver to 3.7.3 this problem is gone in the same config and env.

**Comment by Badiboy** [comment]
I do not use Django, so I cannot reproduce the problem.

Could you please check the latest veriion? There were some improvements on error logging...

**Comment by yankevych** [comment]
I checked the latest ver. 3.7.5. The problem didn't gone.
