### ISSUE TITLE
register_next_step_handler not working well on groups

### ISSUE THREAD

**Issue by analca3** [eternnoir/pyTelegramBotAPI#106]
Hi! This function isn't working well on groups. Bot responds to any user, not the one who begins transaction.

![image](https://cloud.githubusercontent.com/assets/3939991/12390426/373df3bc-bde0-11e5-9d01-de6bf8f9605d.png)

Is it a bug? My problem, maybe? This is my code

https://github.com/analca3/LaTeX2IMGbot/blob/master/bot.py

Thank you!

EDIT: I have modified locally this and bot force reply all users from group. How can I avoid this?

```python
markup = types.ForceReply(selective=False)
new_msg = bot.reply_to(message, "Send me the LaTeX expression", reply_markup=markup)
bot.register_for_reply(new_msg, send_expression_callback)
```

**Comment by analca3** [comment]
Sorry! I've found the bug: selective parameter must be True for working well in groups :dancers:

**Comment by martinikolaev** [comment]
@29antonioac , can you give more info on how you solved it? I am running into the same issue.

**Comment by brucelourenco** [comment]
Please, does anyone knows how to fix this issue?
Same here.
Thank you
