### ISSUE TITLE
I cannot make the bot hear/respond to messages in chans, I've diabled privacy.

### ISSUE THREAD

**Issue by slid3r** [eternnoir/pyTelegramBotAPI#1063]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?  2.2.3

2. What OS are you using?  Debian Linux

3. What version of python are you using? 3.6

# Handle all other messages with content_type 'text' (content_types defaults to ['text'])
@bot.message_handler(func=lambda message: True, content_types=['text'])

**Comment by slid3r** [comment]
Also tried bot.send_message(message.chat.id, message.text)

I don't think it hears the messages

**Comment by slid3r** [comment]
OK, I got it to reply, but it will only reply to a CHAT, not a CHAN.  Can I make it reply to the CHAN?

@bot.message_handler(func=lambda message: True, content_types=['text'])
def channel_post_handler(channel_post):
    bot.send_message(channel_post.chat.id, 'Reply Message!')

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI#channel_post_handler

**Comment by shivsah** [comment]
Have you managed to solve it..? 

@slid3r
