### ISSUE TITLE
Which command should I use to temporarily mute a user?

### ISSUE THREAD

**Issue by must4f** [eternnoir/pyTelegramBotAPI#1068]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2. What OS are you using?

3. What version of python are you using?

**Comment by Badiboy** [comment]
restrict_chat_member

**Comment by must4f** [comment]
> restrict_chat_member

thanks but i want to do it temporarily. eg how does the bot mute the user for 30 seconds?

    bot.restrict_chat_member(message.chat.id, uid, can_send_messages=False, until_date = message.date + 31)

This is taking indefinitely :/

**Comment by Badiboy** [comment]
https://core.telegram.org/bots/api#restrictchatmember

![image](https://user-images.githubusercontent.com/5613421/104334391-5688c980-5503-11eb-89db-8987426b3155.png)

You add 31 second to the date of the message that was sent some time ago. So you get delta less then 30 seconds = forever.

**Comment by must4f** [comment]
> https://core.telegram.org/bots/api#restrictchatmember
> 
> ![image](https://user-images.githubusercontent.com/5613421/104334391-5688c980-5503-11eb-89db-8987426b3155.png)
> 
> You add 31 second to the date of the message that was sent some time ago. So you get delta less then 30 seconds = forever.

Thank you for your quick turnaround. Yes I know. I tried 31 seconds as it can be seen in the codes I threw, but it did not work. I tried it for 32 seconds, it didn't happen again

    uid = message.new_chat_members[-1].id
    bot.restrict_chat_member(message.chat.id, uid, can_send_messages=False, until_date = message.date + 32)

Then I tried the same codes for 45 seconds but still result: indefinitely mute

**Comment by Badiboy** [comment]
You did not read my message. Try again.

**Comment by must4f** [comment]
> You did not read my message. Try again.

no man i read it, but it doesn't work.

**Comment by Badiboy** [comment]
I re-checked what's up. Additionally to my comment there definitely was an error in temporary bans.

It's fixed in the recent version. Use the GIT version.
pip install -U git+https://github.com/eternnoir/pyTelegramBotAPI.git
Version should be 3.7.5.u2.

**Comment by Badiboy** [comment]
Released in 3.7.6
