### ISSUE TITLE
Hello my brothers , i m starting ,где то ошибся(

### ISSUE THREAD

**Issue by ruskeep** [eternnoir/pyTelegramBotAPI#1069]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
from pyowm import OWM
from pyowm.utils import config
from pyowm.utils import timestamps

import telebot

owm = OWM('4ecb689736c9cf7865ed3c3956b7c28d', Language = "ru")
bot = telebot.TeleBot("1469514623:AAHgML8ri5wSk6XalEsYPQVc3cHvXkznUPs")

@bot.message_handler(content_types=['text'])
def send_echo(message):
    observation = owm.weather_at_place( message.text )
    w = observation.get_weather()
    temp += w.temperature('celsius')["temp"]

    answer = " В городе " + message.text + " сейчас " + w.get_detailed_status() + "\n"
    answer += "Температура сейчас в районе " + str(temp) + "\n\n"

    if temp < 10:
        answer += "Сейчас ппц как холодно, одевайся как танк!"
    elif temp < 20:
        answer += "Сейчас холодно, оденься по теплее."
    else:
        answer += "Температура норм, одевай , что угодно. "

    bot.send_message(message.chat.id, answer)

bot.polling( none_stop = True )
2. What OS are you using?

3. What version of python are you using?

**Comment by ruskeep** [comment]
bot = telebot.TeleBot("1469514623:AAHgML8ri5wSk6XalEsYPQVc3cHvXkznUPs", parse_mode=None)
AttributeError: partially initialized module 'telebot' has no attribute 'TeleBot' (most likely due to a circular import)

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/104279516-7e543f00-54bb-11eb-933a-9461e911a4a1.png)

When entering the "New issue" form you see this. Why not to start from filling it?
