### ISSUE TITLE
Asyncio instead of threading

### ISSUE THREAD

**Issue by FalseDev** [eternnoir/pyTelegramBotAPI#1079]
My suggestion/improvement is to use async functions and asyncio instead of threading

Several popular discord bot libraries for various languages are based on async instead of threading.

[discord.py](https://github.com/Rapptz/discord.py) for example uses async, not threading.

This also solves the issue of race conditions while working with threads

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI#advanced-use-of-the-api

**Comment by FalseDev** [comment]
> https://github.com/eternnoir/pyTelegramBotAPI#asynchronous-delivery-of-messages

It's **threaded**, I meant using [aiohttp](https://docs.aiohttp.org/) or [httpx](https://github.com/encoder/httpx) along with `async` and `await` keywords

Asynchronous, but single threaded.
