### ISSUE TITLE
how to get all of a channel member user id ?

### ISSUE THREAD

**Issue by alins1r** [eternnoir/pyTelegramBotAPI#1085]
1. What version of pyTelegramBotAPI are you using?
IDK
2. What OS are you using?
ubuntu 20.4.1 LTS
3. What version of python are you using?
python3.9

i have got a question how can i restrict user to using bot till they join to a channel or how to get all of a channel member user id ???
really really thank you if you can help me 🙏🌹

**Comment by Badiboy** [comment]
Not possible: not provided by telegram.

**Comment by alins1r** [comment]
thank alot
