### ISSUE TITLE
How can i delete last message that sent by bot?

### ISSUE THREAD

**Issue by Ghonghito** [eternnoir/pyTelegramBotAPI#1087]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
latest
2. What OS are you using?
Windows 7 x86
3. What version of python are you using?
python 3.8.7

I have tried this:
mid = message.message_id
bot_last_massage = mid - 1

bot this code deletes user messages also.

Im thinking about store message id's that sent by bot in list but i don't know how to get bot message id's.
Like this:

if command is called and message is sent by bot then store this ID in list of this message and if command is called second time delete last message sent by bot.

anyone can help me ? thanks

**Comment by Badiboy** [comment]
The only way is to remember the last bot message ID for every chat. No other way.

**Comment by Adwaith-Rajesh** [comment]
the bot.send_message returns anAPI reply, it contains the message id
