### ISSUE TITLE
copyMessage method does not group photos in the album

### ISSUE THREAD

**Issue by AlExKrYt** [eternnoir/pyTelegramBotAPI#1088]
1. pyTelegramBotAPI version: 3.7.6 (from github)

2. OS: Linux

3. Python version: 3.7

If you try to copy a message that contains several photos in a message, they will be sent separately, each photo in a separate message.

**Comment by Badiboy** [comment]
Every message contains only ONE photo. Album is a set of SEPARATE messages with their own ID. So you definitely cannot use copyMessage to copy albym.

**Comment by AlExKrYt** [comment]
Understood thanks.

> Every message contains only ONE photo. Album is a set of SEPARATE messages with their own ID. So you definitely cannot use copyMessage to copy album.
