### ISSUE TITLE
add support for new html parse_mode

### ISSUE THREAD

**Issue by ticoti** [eternnoir/pyTelegramBotAPI#109]
https://core.telegram.org/bots/api#formatting-options

**Comment by analca3** [comment]
It works with the actual implementation. You only have to pass "HTML" to parse_mode argument.

```python
tb.send_message(message.chat.id,message.text+"\n<b>"+message.text+"</b>\n<i>"+message.text+"</i>",parse_mode="HTML")
```

![image](https://cloud.githubusercontent.com/assets/3939991/12515543/3c06d390-c129-11e5-84b5-1e12edf4b4fa.png)
