### ISSUE TITLE
Realtime update of the bot commands

### ISSUE THREAD

**Issue by afalahat** [eternnoir/pyTelegramBotAPI#1092]
I am using pyTelegramBotAPI version 0.3.2 in Windows 10 under Python 3.8. I can successfully update the commands in realtime based on the user input. However, the problem is the user has to exit the chat with the bot and then come back to the chat again to see the new commands (by typing /).

Is there any way that I can have the bot update the list of commands in realtime with the user still in the chat?

**Comment by Badiboy** [comment]
Commands list visible by "/" is provided by Telegram. So it needs some time to update it's cache or what it has for commands list.

**Comment by afalahat** [comment]
Makes sense and I assume there is no way to force update the cache.
