### ISSUE TITLE
Copy message release

### ISSUE THREAD

**Issue by jedctl** [eternnoir/pyTelegramBotAPI#1093]
Hi.

I see the **copy message** is not part of the v3.7.6 release but I see it is already implemented in master.

Will this functionality be included in the next release? And when is it going to happen?

===
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.6

2. What OS are you using?
Mac OS

3. What version of python are you using?
3.9

**Comment by Badiboy** [comment]
It will be included.

Release is not planned yet due to small amount of updates.

You can use the master branch, if you want to...
`pip install -U git+https://github.com/eternnoir/pyTelegramBotAPI.git
`
