### ISSUE TITLE
infinity_polling stops when it's not supposed to

### ISSUE THREAD

**Issue by DeMaximilianster** [eternnoir/pyTelegramBotAPI#1095]
So when the bot tries to edit the message to the same text and keyboard (ergo nothing to actually edit), it stops working. Even calling infinity_polling again does not help. It just stops working right after it's called. Only restarting the program helps

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
I don't know, how do I check?
2. What OS are you using?
Windows 8, 64-bit
3. What version of python are you using?
3.7.3

**Comment by dtalkachou** [comment]
There is no point in reusing `infinity_polling`. This method starts normal `polling` and if an error occurs there, then it restarts normal `polling`.

About your problem: the telegram itself gives an error if you try to "edit" the message without changing anything. Try not to do this. It is better to check the values programmatically than to make an extra request to the Telegram server.

Why doesn't `infinity_polling` solve the problem with the exception for you, although he is called to do so? Most likely, there are errors in the method itself.

**Comment by DeMaximilianster** [comment]
Alright, thank you

**Comment by Badiboy** [comment]
@DeMaximilianster How do you call infinity_polling?

You can also use logger_level parameter if infinity_polling and check what happens in log.
