### ISSUE TITLE
Stopping polling() and closing the bot 

### ISSUE THREAD

**Issue by przemmaj** [eternnoir/pyTelegramBotAPI#1098]
Not an issue but not sure where to ask. Is there a way to stop the bot, stop the polling()? Would find it useful if want to pack it into the class.

**Comment by Badiboy** [comment]
bot.stop_polling() 
:)

**Comment by przemmaj** [comment]
Thanks! should I call stop_bot() additionally? can I call it from the function handler? Seems to work after 2nd repetition of the command.

**Comment by Badiboy** [comment]
You should call it when you want to stop bot polling. Not earlier and not later.
