### ISSUE TITLE
SetNew bot on telegram

### ISSUE THREAD

**Issue by Omarj22** [eternnoir/pyTelegramBotAPI#1099]
Hi everyone! i'm trying for the first time to make a bot but the problem is that i'm not able to do that...
i'm there to ask you if someone can do the impostation for a bot that have to book me automatically every week at a website where every sunday i have to book for go to university. So if it isn't a prlbem someone can do this for me and expalin how to change descrption ?
shortly:
a auto-booking bot where i can choose when book me. thank you very much guys

**Comment by Badiboy** [comment]
Not a topic for the library issue.
