### ISSUE TITLE
Executes message_handler or does not respond to process_new_updates

### ISSUE THREAD

**Issue by QviNSteN** [eternnoir/pyTelegramBotAPI#1102]
Please answer these questions before submitting your issue. Thanks!

Hello!

There was a problem: I wrote a bot, everything is OK on the LAN and on some free hosting. Posted on VDS, the bot starts up, the Flask part (requests) are executed, but ... process_new_updates handles everything somehow crookedly ... and @ bot.message_handler does not react.

My code (example. Removed unnecessary):

```
@app.route('/{}'.format(TOKEN), methods=["POST"])
def webhook():
    json_string = request.get_data().decode('utf-8')
    update = telebot.types.Update.de_json(json_string)
    bot.process_new_updates([update])
    return ''
 
@bot.message_handler(commands=['start'])
def startCommand(message):
    bot_send_message(message.chat.id, textStart()) #bot_send_message is my function. everything is ok there. The problem is that the request to startCommand doesn't even arrive. I added print there and it just isn't displayed ... At the same time, everything is ok in the route
```

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/webhook_examples/webhook_flask_echo_bot.py

Could you please test with excho bot "as is" (with appropriate hook updates)? Will it work as designed?

**Comment by QviNSteN** [comment]
@Badiboy i use nginx and therefore do not use setwebhook and app.run in my bot.

Could it be because of this?

I assign webhock using a direct request (since a self-signed certificate, alas, does not work through setwebhook)

**Comment by Badiboy** [comment]
Nobody knows what you had prepared outside of these wto functions. Plese provide the full not-working example, may be I'll be able to help...
