### ISSUE TITLE
Bot sleeps after a few hours?

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [eternnoir/pyTelegramBotAPI#1103]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.1

2. What OS are you using?
Debian

3. What version of python are you using?
3.8

Hi guys, i have a question ...
I am running my bot using the `bot.polling()` in a tmux session ... Everyday i want to make a command and the bot makes a requests. This only works for the current day, in the next day the information that bot is showing is about the last day and not the current day.

So my question is, does the bot sleeps after a few hours of inactivity?

**Comment by Badiboy** [comment]
> Everyday i want to make a command and the bot makes a requests. This only works for the current day, in the next day the information that bot is showing is about the last day and not the current day.

No clue what it may mean... What request bot makes... What information it show...

**Comment by BrunoTeixeira1996** [comment]
> > Everyday i want to make a command and the bot makes a requests. This only works for the current day, in the next day the information that bot is showing is about the last day and not the current day.
> 
> No clue what it may mean... What request bot makes... What information it show...

Bot makes a request to an API and if i stop the bot and rerun it shows the right information.
Imagine yesterday i made a command, the bot will send me a message with some information about yesterday, but today there is new information in the API and for some reason the bot only shows information about yesterday

**Comment by BLUE-DEVIL1134** [comment]
Can you provide your price of code?

**Comment by BrunoTeixeira1996** [comment]
> Can you provide your price of code?

yes i can
check here -> https://github.com/BrunoTeixeira1996/random_bots/blob/main/telegram/bot.py

**Comment by BLUE-DEVIL1134** [comment]
It's Really strange...
Well there is a easy thing u can do and check.... 

Replace  `bot.polling()`  To `bot.polling(non_stop=true)`

**Comment by BrunoTeixeira1996** [comment]
> It's Really strange...
> Well there is a easy thing u can do and check....
> 
> Replace `bot.polling()` To `bot.polling(non_stop=true)`

well i will do that and i will wait to tomorrow and see if it solved.
Btw, can you show me where i can see the `bot.polling()` params available?

**Comment by Badiboy** [comment]
```
"""
        This function creates a new Thread that calls an internal __retrieve_updates function.
        This allows the bot to retrieve Updates automagically and notify listeners and message handlers accordingly.
        Warning: Do not call this function more than once!
        Always get updates.
        :param interval: Delay between two update retrivals
        :param none_stop: Do not stop polling when an ApiException occurs.
        :param timeout: Request connection timeout
        :param long_polling_timeout: Timeout in seconds for long polling (see API docs)
        :return:
        """
```

**Comment by BrunoTeixeira1996** [comment]
> ```
> """
>         This function creates a new Thread that calls an internal __retrieve_updates function.
>         This allows the bot to retrieve Updates automagically and notify listeners and message handlers accordingly.
>         Warning: Do not call this function more than once!
>         Always get updates.
>         :param interval: Delay between two update retrivals
>         :param none_stop: Do not stop polling when an ApiException occurs.
>         :param timeout: Request connection timeout
>         :param long_polling_timeout: Timeout in seconds for long polling (see API docs)
>         :return:
>         """
> ```

Well it looks like `none_stop` will not work then because i am not having any `ApiException` output ...
what do you guys recommend?

**Comment by BrunoTeixeira1996** [comment]
maybe its beacause i am calling a function from `modules` that does not has the datetime inside it and instead of calling the `program.py` its only calling that functions and thats why it does not updates the current time?
What i mean is, i am calling a function in bot from another `py` file and inside that file i have global vars that represent the `datetime` and since i am calling (inside `bot.py`) only the function maybe thats the reason the datetime does not update, could it be?

**Comment by Badiboy** [comment]
> This only works for the current day, in the next day the information that bot is showing is about the last day and not the current day.

You are talking about nonsense. Bot have no meaning about time. About yesterady and today, and tomorrow. The only thing that bot do - receive and send messages. Bot does not sleep or feel tired. I have no clue what you are talking about and what do you want from bot library developers.

**Comment by BrunoTeixeira1996** [comment]
> > This only works for the current day, in the next day the information that bot is showing is about the last day and not the current day.
> 
> You are talking about nonsense. Bot have no meaning about time. About yesterady and today, and tomorrow. The only thing that bot do - receive and send messages. Bot does not sleep or feel tired. I have no clue what you are talking about and what do you want from bot library developers.

lol ... i am not talking nonsense, you could just tell me that the bot does not sleep at all

**Comment by dasshit** [comment]
@BrunoTeixeira1996 problem is in module modules.covid

Do not use variable "now" outside of functions, while you defining it on module level - it defines only once - on import in bot module.

Define variable "now" inside functions that will be using it as a part urls for your requests. That will work just fine.
