### ISSUE TITLE
Bad Request: message can't be edited

### ISSUE THREAD

**Issue by barbax7** [eternnoir/pyTelegramBotAPI#1104]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.7.6

2. What OS are you using? windows 10 and vps based on ubuntu 20.04

3. What version of python are you using? 3.9

Hello, i'm running into this error:
`ERROR - TeleBot: "A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message can't be edited"`

My code is:
`msg = bot.send_message(message.chat.id, 'Starting', reply_markup = types.ReplyKeyboardRemove())`
`do something`
`bot.edit_message_text(text, chat_id = msg.chat.id, message_id = msg.message_id, parse_mode='Markdown', reply_markup=m_start())`

I can't undestand what's the matter.

**Comment by saniar-mf** [comment]
Hi,If You're using **AsyncTeleBot** for getting **msg** informations in first use :
`x = msg.wait()
x = x.message_id`

**Comment by barbax7** [comment]
Not Async

**Comment by saniar-mf** [comment]
I had this problem tonight too.
I realized something.You can't send message to other bot and cant' forward messages from other bots even your own bot.
but in here you send msg to message.chat.id bot you want to edit for bot=> `(chat_id = msg.chat.id)`
but you can Solve your problem with this:
`bot.edit_message_text("examble" , message.chat.id , msg.message_id ,....)`

**Comment by barbax7** [comment]
No, doesn't work

**Comment by BLUE-DEVIL1134** [comment]
Where was the message posted?

**Comment by barbax7** [comment]
Private chat with user.
Every other message could be edited after callback action, but this one no, i can't understand.

**Comment by barbax7** [comment]
I discovered that the problem is `reply_markup=types.ReplyKeyboardRemove()`. Without this one in first message, it could be edited.
So I'll use send method, then delete method and eventually another send method.
