### ISSUE TITLE
Entities

### ISSUE THREAD

**Issue by roaste** [eternnoir/pyTelegramBotAPI#1105]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
1.15.0
2. What OS are you using?
win10
3. What version of python are you using?
python3.8.5

The official api https://core.telegram.org/bots/api#sendmessage has an entities parameter, but when I pass it to telebot, it gives me an error:

TypeError: send_message() got an unexpected keyword argument 'entities'
How i can fix it?

**Comment by Badiboy** [comment]
Added in the very last Bot API update. Not supported yet.

**Comment by Badiboy** [comment]
Released.

**Comment by Practic1984** [comment]
До сих пор не поддерживается?

**Comment by Badiboy** [comment]
![image](https://github.com/user-attachments/assets/4e8246dc-7b86-40f5-984c-6e97e8fe0659)
