### ISSUE TITLE
How to use ApiException

### ISSUE THREAD

**Issue by barbax7** [eternnoir/pyTelegramBotAPI#1106]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.6

2. What OS are you using?
Windows 10 and Ubuntu 20.04

3. What version of python are you using?
3.9

How can I use `ApiException` to handle different types of errors? Like `bot was blocked by the user` and `user is deactivated`

**Comment by BLUE-DEVIL1134** [comment]
`try/except` ?

**Comment by barbax7** [comment]
Yes, of course

I mean, how to handle different types of errors for doing different actions with except and ApiException?

Andrea Barbagallo
andreabarbagallo.ab7@gmail.com

________________________________

**Comment by Badiboy** [comment]
By text of the exception message. Telegram does not provide list of its exceptions, so library does not identify them.

**Comment by barbax7** [comment]
Can you please send an example?

Andrea Barbagallo
andreabarbagallo.ab7@gmail.com

________________________________

**Comment by Badiboy** [comment]
```
try:
  ...
except ApiException as err:
  if "bot was blocked by the user" in str(err);
    print("Life is pain")
```

**Comment by barbax7** [comment]
Brilliant, thank you!
