### ISSUE TITLE
Readding all messages of a group (not only commands)

### ISSUE THREAD

**Issue by enboig** [eternnoir/pyTelegramBotAPI#1108]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2.22
2. What OS are you using?
ubuntu 20.04
3. What version of python are you using?
3.8

I have checked #857 but it doesn't work on my group. 
* chatting directly to bot:
  * `hello` --> works
* chatting in a group:
  * `/hello` --> works
  * `hello` --> does nothing

```
import telebot

API_TOKEN = <TOKEN>

bot = telebot.TeleBot(API_TOKEN)

#@bot.channel_post_handler(func=lambda message: True)
@bot.message_handler(func=lambda message: True)
def echo_all(message):
    print('Chanel {} message received: {}'.format(message.chat.title, message.text))
    bot.send_chat_action(message.chat.id, 'typing')
    bot.send_message(message.chat.id, 'message received')

bot.polling()
```

**Comment by Badiboy** [comment]
![Uploading image.png…]()

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/110927100-412ef080-8336-11eb-8093-7bec6bda1588.png)

**Comment by enboig** [comment]
The comment is because I tested both ways. None worked

**Comment by enboig** [comment]
```
import telebot

API_TOKEN = <TOKEN>

bot = telebot.TeleBot(API_TOKEN)

@bot.message_handler(func=lambda message: True)
def echo_all(message):
    print('Chanel {} message received: {}'.format(message.chat.title, message.text))
    bot.send_chat_action(message.chat.id, 'typing')
    bot.send_message(message.chat.id, 'message received')

@bot.channel_post_handler(func=lambda message: True)
def echo_all(message):
    print('Chanel {} message received: {}'.format(message.chat.title, message.text))
    bot.send_chat_action(message.chat.id, 'typing')
    bot.send_message(message.chat.id, 'message received')


bot.polling()
```

**Comment by enboig** [comment]
Can it be related to https://github.com/eternnoir/pyTelegramBotAPI/issues/639#issuecomment-488227292?

**Comment by Badiboy** [comment]
Your bot definitely should have access to group messages and have disabled privacy...

**Comment by enboig** [comment]
At group info it says "bot has no access to messages"; where may I change this config?

**Comment by enboig** [comment]
Just found it, at it works. Thanks a lot for your time
[stakoverflow link](https://stackoverflow.com/questions/50204633/allow-bot-to-access-telegram-group-messages)
