### ISSUE TITLE
How to add forever test conditions and implementation for bot?

### ISSUE THREAD

**Issue by vovawed** [eternnoir/pyTelegramBotAPI#111]
I want to bot sent a notification to the user. I would appreciate help.

**Comment by Pitasi** [comment]
I don't understand what you want to achieve.
Bots can send messages to users by the ID like this:
`YOURBOT.send_message(USERID, TEXT)`

Obviously you need to subtitute _YOURBOT_, _USERID_ and _TEXT_ as you need.
