### ISSUE TITLE
The absence of the "message.forward" flag if the user does not have a last name.

### ISSUE THREAD

**Issue by VovaVilla** [eternnoir/pyTelegramBotAPI#1110]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2.2.3
2. What OS are you using?
Windows 10
3. What version of python are you using?
3.7

Most likely this is not a library problem, but a telegram problem, but when I process a forwarded message in my bot, the "message.forward" flag and all its properties (first _name, last_name) are equal to None if the user from whom the message was forwarded is empty last_name.

**Comment by Badiboy** [comment]
> "message.forward" flag
No such "flag"

> and all its properties (first _name, last_name)
Flag cannot have properties.

**Comment by VovaVilla** [comment]
okey, not a flag.
field "forward_from" = None and fields "irst _name", "last_name" etc. = None, but in fact the message was forwarded.

This happens if the user does not have a last name in the telegram

**Comment by Badiboy** [comment]
It's better.

This happens not when "user does not have a last name" but when user enabled forward privacy in Telegram privacy settings.
