### ISSUE TITLE
Bot stops responding after some time

### ISSUE THREAD

**Issue by bizonmwk** [eternnoir/pyTelegramBotAPI#1118]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.6
2. What OS are you using?
win10 / linux
3. What version of python are you using?
3.7

My problem is that, after some (random i belive) time bot stops hearing commands from telegram. I don't know excatly what causes this problem but it's some times after few minutes, sometimes after 20-30minutes. I created simple bot which is updating with messages when we choose option start, but after some time it's look like freezed even if bot is still working - doesing responding. I can mix all the time /start /stop /status and bot will send me updates but after some time it will freeze and doesnt respond for any command. Please help :/ : 

Fragment of code of message handler etc:

```
@bot.message_handler(commands=['start'])
def command_start(message):
    global bot_status
    bot_status = True
    bot.send_message(message.chat.id, "Bede podrzucal ci najnowsze informacje o tym co sie dzieje w krypto.")

    while True:
        if bot_status == False:
            return
        try:
            event_message = run_with_news() //run with news returns list of news for users
            if event_message:
                for event in event_message:
                    bot.send_message(message.chat.id, event)
                    print(event)
            else:
                print('Slucham  ' + str(time.localtime()))
        except:
            print('Problem z pobraniem danych.')


@bot.message_handler(commands=['stop'])
def command_stop(message):
    bot.reply_to(message, " Subskrypcja newsow zatrzymana.")
    global  bot_status
    bot_status = False

@bot.message_handler(commands=['status'])
def command_status(message):
    if bot_status == False:
        bot.send_message(message.chat.id, " Jestem ale nie informuje.")
    else:
        bot.send_message(message.chat.id, " Jestem i dzialam.")

bot.polling()

```

**Comment by Badiboy** [comment]
Use
`infinity_polling`

**Comment by bizonmwk** [comment]
> Use
> `infinity_polling`

I tried infinity_pooling too. It didn;t changed nothing - after some time bot stops to respond. My internet connection is stable and i tried on boyth linux and win10.

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/112003713-33e1e500-8b32-11eb-9092-67ffd63ba8a8.png)

You use infinite loop in message processor. Your bot will stop working when all your bot threads will be occupied in this loop. By default there are 2 threads, so if you will call start twice your bot will be frozen forever. 

It's absolutely enromous message processing, so you should find further problems yourself in your code. infinity_polling should work well.

**Comment by bizonmwk** [comment]
> ![image](https://user-images.githubusercontent.com/5613421/112003713-33e1e500-8b32-11eb-9092-67ffd63ba8a8.png)
> 
> You use infinite loop in message processor. Your bot will stop working when all your bot threads will be occupied in this loop. By default there are 2 threads, so if you will call start twice your bot will be frozen forever.
> 
> It's absolutely enromous message processing, so you should find further problems yourself in your code. infinity_polling should work well.

LoL, i didn;t knew about that there are only 2 threads by default. Thanks a lot for that advice. It's simple - and basic test version but i though i could break easly this while with break even if this is not pretty. Thanks again man :)
