### ISSUE TITLE
Exception in set_chat_permissions

### ISSUE THREAD

**Issue by fourteekey** [eternnoir/pyTelegramBotAPI#1119]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI v3.7.6

2. What OS are you using?
Linux Mint 20 

3. What version of python are you using?
Python 3.7

Whe use method  _**set_chat_permissions**_ I accept Exception: 
```
'permissions': permissions.to_json(),
AttributeError: 'dict' object has no attribute 'to_json'
```
![2021-03-23_13-10](https://user-images.githubusercontent.com/25711812/112130531-a22db280-8bd9-11eb-90f0-ce2688f270fa.png)
Afther modify method all work. 
![afther_update](https://user-images.githubusercontent.com/25711812/112130626-bbcefa00-8bd9-11eb-9229-942d72296d67.png)

**Comment by Badiboy** [comment]
Permissions should be of type ChatPermissions.

**Comment by fourteekey** [comment]
When i can create object type ChatPermissions?

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/112146674-e6767e00-8bec-11eb-8023-6b5dc9242783.png)
