### ISSUE TITLE
Bad Request: AUDIO_TITLE_EMPTY

### ISSUE THREAD

**Issue by cnderton** [eternnoir/pyTelegramBotAPI#1120]
Before I begin: 
pyTelegramBotAPI version - 3.7.6
OS - Ubuntu 20.04.2
Python - 3.8.5

I'm having trouble with `InlineQueryResultCachedAudio`, when I try to: 

`r = types.InlineQueryResultCachedAudio( id = 1, audio_file_id = my_audio_file_id )`
`bot.answer_inline_query(inline_query.id, [r])`

I get: 
`A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: AUDIO_TITLE_EMPTY`

I've checked out [docs](https://core.telegram.org/bots/api#inlinequeryresultcachedaudio), and found that TITLE is not required for `InlineQueryResultCachedAudio`

full code if required:

```
@bot.inline_handler(lambda query: query.query == 'hi')
def query_photo(inline_query):
    try:
        
        r = types.InlineQueryResultCachedAudio( id = 1, audio_file_id = my_audio_file_id )

        bot.answer_inline_query(inline_query.id, [r])
    except Exception as e:
        print(e)
```

**Comment by Badiboy** [comment]
Seems that there is a mistake in docs.

**All** other inline methods have _title_ and it's required. Like this:

![image](https://user-images.githubusercontent.com/5613421/112877233-31056800-90cf-11eb-849a-1ad70dd9d3c7.png)

Could you please temporary try to edit InlineQueryResultCachedAudio code in installed library to:
```
class InlineQueryResultCachedAudio(BaseInlineQueryResultCached):
    def __init__(self, id, audio_file_id, title, caption=None, parse_mode=None, reply_markup=None, input_message_content=None):
        BaseInlineQueryResultCached.__init__(self)
        self.type = 'audio'
        self.id = id
        self.audio_file_id = audio_file_id
        self.title = title
        self.caption = caption
        self.reply_markup = reply_markup
        self.input_message_content = input_message_content
        self.parse_mode = parse_mode
        self.payload_dic['audio_file_id'] = audio_file_id
```
And try again with passing the title?

**Comment by cnderton** [comment]
I've tried your method but it still doesn't seem to work.I still get the same error. If I got it correctly, I should edit `types.py` at telebot, right?
I've also tried to use  `python-telegram-bot` and it showed same error.

**Comment by Badiboy** [comment]
1. You should edit types.py, right.
2. You should set title in your code when creating InlineQueryResultCachedAudio to something valuable.

As I said, I suppose that there is a mistake in documentation.

**Comment by cnderton** [comment]
I've done both of them, `types.InlineQueryResultCachedAudio( id = 1, audio_file_id = file_data  , title = 'sometext')`

**Comment by Badiboy** [comment]
Thank you. So seems the problem is deeper in Telegram Bot API

**Comment by cnderton** [comment]
Thanks for attempt to help, I appreciate it, hope they fix it
