### ISSUE TITLE
Missing voice_chat types

### ISSUE THREAD

**Issue by GabrielRF** [eternnoir/pyTelegramBotAPI#1122]
1. What version of pyTelegramBotAPI are you using?
3.7.7

2. What OS are you using?
Ubuntu 18.04.5 LTS

3. What version of python are you using?
Python 3.8.0

Missing types on [Message](https://core.telegram.org/bots/api#message)
`voice_chat_started`
`voice_chat_ended`
`voice_chat_participants_invited`

**Comment by Badiboy** [comment]
Released.
