### ISSUE TITLE
Running bot in the background (non-blocking polling?)

### ISSUE THREAD

**Issue by alexgorbachev** [eternnoir/pyTelegramBotAPI#1127]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.7

2. What OS are you using?
Linux/MacOS

3. What version of python are you using?
3.9.2

Perhaps, there is already a way to do it but I couldn't figure out...

I need to add a bot to another program - the bot is just a notifier and provides some control functionality. So I need the bot to run and handle messages as they come while my program actually does whatever it needs to. I was expecting it to just do that because of use of threading but apparently not.

Do I run call polling() in another thread for it or there are arguments that I can use to make it non-blocking?

I could also live with periodically checking for new messages for the bot like every few seconds - I.e. if the polling() could just trigger messages check and exits immediately. The description of its parameters is confusing so I don't know if I can use it already this way.

To simplify, if there was any way to make polling() non-blocking then it would solve my problem.

Alex

**Comment by Badiboy** [comment]
`Do I run call polling() in another thread for it or there are arguments that I can use to make it non-blocking?`
In thread. 

Or check messages yourself without polling (not recommended): see  __retrieve_updates code.
