### ISSUE TITLE
Forwarded messages with empty datas

### ISSUE THREAD

**Issue by barbax7** [eternnoir/pyTelegramBotAPI#1128]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.7
    
2. What OS are you using?
Windows 10

3. What version of python are you using?
3.9.0

Hello!
When I forward a message from a chat to another and print the forwarded message data, i get this parameters:
`'forward_from': None,
'forward_from_chat': None,
'forward_from_message_id': None,
'forward_signature': None,
'forward_sender_name': 'Andrea Barbagallo',
'forward_date': 1618049089`

As you can see, the messages is really forwarded, because we have `forward_sender_name` and `forward_date`. So in `forward_from` there should be User object of original sender.

Why is it missing?

**Comment by Badiboy** [comment]
User forbid forward in privacy settings.

**Comment by barbax7** [comment]
Oh... ok, nice.
Actually i activated this option in my privacy settings.

I'll find out a different way to develop a feedback function, maybe storing the original chatid in a variable.
If you have any suggestions it could be great, or simply close the issue.

Thank you again
