### ISSUE TITLE
Why i cant get the callback here or how i can get it

### ISSUE THREAD

**Issue by pedromaironi** [eternnoir/pyTelegramBotAPI#1130]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Current version
2. What OS are you using?
windows
3. What version of python are you using?
3.9.2

Why i cant get the callback here or how i can get it

```
@bot.callback_query_handler(func=lambda call: True)
def callback_query(call):
    print(call)

```

```

@bot.message_handler(commands=['shop'])
def message_handler(message):
    product = message.json['text']
    words = product
    name_of_product = words.replace('/shop ','')
    details = showDetailsProducts(name_of_product.strip())
    print(name_of_product)
    print(details)
    details_product = details['detail']
    price = details['price']
    url = details['image']
    categoria = details['category']
    keyboard=json.dumps({ "inline_keyboard": [ [ {"text": 'DOP' + details['price'], "callback_data": "x"} ] ] })
    print(keyboard)
    response_products = name_of_product + "\n" + details_product + "\n" + "Precio: $" + price + '\n'
    bot.send_photo(chat_id=message.json['chat']['id'], photo=url, caption=response_products, reply_markup=keyboard)


```

```
keyboard=json.dumps({ "inline_keyboard": [ [ {"text": 'DOP' + details['price'], "callback_data": "x"} ] ] })
```

**Comment by Badiboy** [comment]
> @bot.message_handler(commands=['shop'])
> def message_handler(message):
>     product = message.json['text']
>     words = product
>     name_of_product = words.replace('/shop ','')
>     details = showDetailsProducts(name_of_product.strip())
>     print(name_of_product)
>     print(details)
>     details_product = details['detail']
>     price = details['price']
>     url = details['image']
>     categoria = details['category']
>     keyboard=json.dumps({ "inline_keyboard": [ [ {"text": 'DOP' + details['price'], "callback_data": "x"} ] ] })
>     print(keyboard)
>     response_products = name_of_product + "\n" + details_product + "\n" + "Precio: $" + price + '\n'
>     bot.send_photo(chat_id=message.json['chat']['id'], photo=url, caption=response_products, reply_markup=keyboard)

This is not how this library should be used. Use narural way and may be someone be able to help you.

**Comment by pedromaironi** [comment]
I already solved my error and found the natural way to write that type of code, thanks BadBoy
