### ISSUE TITLE
Is there a call that consists of receiving the message sent by the bot

### ISSUE THREAD

**Issue by pedromaironi** [eternnoir/pyTelegramBotAPI#1131]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
current version
2. What OS are you using?
win 10
3. What version of python are you using?
3.9.2

Hello there
Is there a call that consists of receiving the message sent by the bot
Example: I would like to receive this message, in the sense of capturing it
![image](https://user-images.githubusercontent.com/43529059/114481320-9b0c2a00-9c04-11eb-8a24-41572a3582af.png)

**Comment by pedromaironi** [comment]
Or a suggestion they can make to create a quiz

**Comment by pedromaironi** [comment]
I just read about force reply, examples?

**Comment by BLUE-DEVIL1134** [comment]
> I just read about force reply, examples?

So @pedromaironi , Fore Reply Helps You In A Different Manner..
It Forces The User To Reply To The Specific Message But User Is Not Bound To Answer That Reply...

User Can Always Close The Reply Option...

For Examples -


------
<kbd>forceReplyExample.py</kbd>
```python
bot = TeleBot('myBotToken')
markup = types.ForceReply(selective=False)
bot.send_message(chat_id, "Send me another word:", reply_markup=markup)
```

------
<kbd>Image Example</kbd>
![image](https://user-images.githubusercontent.com/55914808/114495594-fa396100-9c3b-11eb-97f8-b1fb73e39c3e.png)

As You Can See In The **Above Example**, User Can Cancel The Force Reply...


**Note.** If You Want To Build A Quiz Bot Then You Will Need Continuous Work Flow With A Database To Make Things Work.

**Comment by Badiboy** [comment]
Is there a call that consists of **receiving** the message **sent by the bot**

What bot you are talking about? Bot is what you are creating.

**Comment by pedromaironi** [comment]
@Badiboy Hello brother, I meant to receive the messages from the bot itself, but last night I found a way, thanks @BLUE-DEVIL1134 for the explanation, that same method worked for me, thank u

**Comment by BLUE-DEVIL1134** [comment]
You are welcome @pedromaironi ,Now can this be closed ?

**Comment by pedromaironi** [comment]
YES BROTHA
