### ISSUE TITLE
send_message(timeout=...) does nothing

### ISSUE THREAD

**Issue by enboig** [eternnoir/pyTelegramBotAPI#1132]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.6
2. What OS are you using?
xUbuntu 20.04
3. What version of python are you using?
python3.7

I am using a reply_markup with some buttons in a chat group, but I want them to disappear after some time. I tried timeout but I thing I am misusing it because it does nothing. I tried 
```m=bot.send_message(chat_id, "Choose a game", reply_markup=games_choose_markup(),  timeout=10,disable_notification=True)```
but it don't expire after 10 seconds, I also tried adding
```bot.delete_message(m.chat.id, m.message_id,timeout=10)```
but then it disappear immediately.

How can I make a markup disappear after some time? thanks

(I read #1109 but I don't know if it related neither where to set READ_TIMEOUT)

**Comment by Badiboy** [comment]
Timeout deals with connection timeout.

Buttons will not disappear until you manualy delete them,

**Comment by enboig** [comment]
And how could I delete them after some time? of after some option is chosen?

**Comment by Badiboy** [comment]
Manually means MANUALLY. You in your bot take care about time, conditions etc.

**Comment by enboig** [comment]
ok, thanks
