### ISSUE TITLE
Commands with parameters

### ISSUE THREAD

**Issue by pedromaironi** [eternnoir/pyTelegramBotAPI#1133]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
current version
2. What OS are you using?
win 10
3. What version of python are you using?
3.9.,4

How can I make the user click on the command to also automatically take the product name parameter in the command?
![image](https://user-images.githubusercontent.com/43529059/114617609-a44ed280-9ca8-11eb-8f7f-be77b4da556f.png)

**Comment by Badiboy** [comment]
You cannot.

**Comment by pedromaironi** [comment]
Okay brotha, thanks
