### ISSUE TITLE
callback for ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [eternnoir/pyTelegramBotAPI#1136]
Hi,

How do I get the user reply after ReplyKeyboardMarkup? 

Cheers,

Francesco

**Comment by BLUE-DEVIL1134** [comment]
See,  Reply Keyboard Markups are different from as you think... 
Keyboard buttons don't have callbacks.. 
Callbacks are in InlineKeyboardMarkup...

**Comment by BLUE-DEVIL1134** [comment]
@Badiboy can this be closed now?
