### ISSUE TITLE
Converting get_updates to json

### ISSUE THREAD

**Issue by Xen-neX** [eternnoir/pyTelegramBotAPI#1139]
Hi ! I'm using get_updates but can't convert to json. I've tried taking the last message in the list I get, it is a string, it seems. If you try json.loads, you get an error. Is there a special method?

**Comment by Badiboy** [comment]
You should not use get_updates, use infinity_pollings.

If you still want to use get_updates manually - inspect polling code to see how to use it.

**Comment by BLUE-DEVIL1134** [comment]
@Badiboy , on the other note, I liked the idea of JSON..
Now a days most of things are json.
Why not convert things to json..
