### ISSUE TITLE
Invitation link with url parameters

### ISSUE THREAD

**Issue by dhervy** [eternnoir/pyTelegramBotAPI#1142]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.7

2. What OS are you using?
High Sierra

3. What version of python are you using?
3.9.1

Is it possible to recover a parameters provided in an invitation url?
I can’t catch the event when someone uses an invitation link.

thank you

**Comment by BLUE-DEVIL1134** [comment]
could you provide more information like an invitation link and what parameters you need?
