### ISSUE TITLE
I have a problem guys

### ISSUE THREAD

**Issue by 1728910096** [eternnoir/pyTelegramBotAPI#1143]
Hello, I created a robot in Telegram as an experiment through the bot dad, a bot that downloads social media for subscribers, I never know about the robot or programming but it is an experiment, my problem is when I send the robot it responds and works well, but when others send it it does not respond and does not  They answer what is the solution to this problem?

**Comment by BLUE-DEVIL1134** [comment]
ask to robot dad 🤣

**Comment by dostonru** [comment]
Problems with chat.I'd
