### ISSUE TITLE
my_chat_member and chat_member miss in Update class

### ISSUE THREAD

**Issue by barbax7** [eternnoir/pyTelegramBotAPI#1145]
Hello there, great work with this library!

I found out that API method GetUpdates returns more information than pyTelegramBotAPI catches.

I mean, as you can see [here](https://core.telegram.org/bots/api#update), the last two fields aren't catched from `process_new_updates` function ans `Update` [class](https://github.com/eternnoir/pyTelegramBotAPI/blob/c437b40d58b0dbb399894c1a9342163ffc464051/telebot/types.py#L91).

It could be useful to add this fields in pyTelegramBotAPI.

I attach also a [JSON](https://pastebin.com/y3WqC6gM) response from GetUpdates.

Thanks for your time.

**Comment by SwissCorePy** [comment]
@barbax7 I added it today. Hope it will me merged :)

**Comment by Badiboy** [comment]
Released.
