### ISSUE TITLE
No visible support for user attributes.

### ISSUE THREAD

**Issue by STInfinityXz** [eternnoir/pyTelegramBotAPI#1146]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
                       version 13.5
2. What OS are you using?
                       win10
3. What version of python are you using?
                       python 3.9.4

I've been trying to acquire user attributes, specifically the 'username' to be used in replies by the bot. However, there seems to be no such function that allows this to be possible, despite it being heavily linked to the telegram bot API.

**Comment by Badiboy** [comment]
I did not understand what you are asking about. Please, try to ask question clearly.

**Comment by STInfinityXz** [comment]
Basically, I am asking if there is a way to return user objects. There doesn't seem to be a well documented way of doing so.

**Comment by Badiboy** [comment]
> What version of pyTelegramBotAPI are you using?
> version 13.5

pyTelegramBotAPI has version 3.7.8.
Version 13.5 have python-telegram-bot library.
So seems that you went to the wrong place.
