### ISSUE TITLE
poll 

### ISSUE THREAD

**Issue by Brijeshkrishna** [eternnoir/pyTelegramBotAPI#1147]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 
   3.7.7

2. What OS are you using?
  win

3. What version of python are you using?
    3.8

[<telebot.types.PollOption object at 0x0000024E0E4DC640>, <telebot.types.PollOption object at 0x0000024E0E4DC730>]  how to convert to text

**Comment by Badiboy** [comment]
https://core.telegram.org/bots/api#polloption
