### ISSUE TITLE
How to send file using file id

### ISSUE THREAD

**Issue by technicalheist** [eternnoir/pyTelegramBotAPI#1156]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? : Latest 

2. What OS are you using? : Ubuntu

3. What version of python are you using? : Python 3.8.6

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/118298505-37696b00-b4e8-11eb-910f-1709bef263bf.png)


https://core.telegram.org/bots/api#senddocument
