### ISSUE TITLE
BOT API latest - 5.2 ?

### ISSUE THREAD

**Issue by abhi3700** [eternnoir/pyTelegramBotAPI#1164]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? latest

2. What OS are you using? Windows

3. What version of python are you using? 3.8.5

Is the BOT API not updated to latest - 5.2 ?

**Comment by Badiboy** [comment]
It is not.

**Comment by abhi3700** [comment]
Then which latest version does it support?

**Comment by SwissCorePy** [comment]
Bot API 4.4 is latest, Bot API 4.5 to be checked

**Comment by abhi3700** [comment]
Ok
