### ISSUE TITLE
Whenever i send message to my bot it gives me error

### ISSUE THREAD

**Issue by Vuqar05** [eternnoir/pyTelegramBotAPI#1169]
1. pyTelegramBotAPI 3.7.9

2. MacOs Catalina  10.15.5 (19F101)

3.Python 3.9.5

Hello! When i send my bot message my app gives me an error and stops and the next time i run it, it gives me the error again, although that i didn't text anything to bot. Although when i send a command it works just fine. In addition when i use echo bot script from official api before my commands it works, but i can't use commands, also when i use echo script after my commands it gives me the error
 How do I make my bot work even when it receives a message?

My code: https://pastebin.com/kcYshQh5
Error: https://pastebin.com/1i4wH3NL

**Comment by Vuqar05** [comment]
I tried using echo bot script after every command and saw that error was caused by markup

I still don't know why this happens

  @bot.message_handler(commands="menu")
    def menu(message):
        bot.send_message(message.chat.id,"Menu:",reply_markup=markup)
        print(str(message.chat.id) + " использовал команду /menu")

**Comment by Badiboy** [comment]
commands=["menu"]

**Comment by Badiboy** [comment]
But anyway I'll check what's that error :)

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/commit/2add34c70261949cfcd18df5b602a1a2f6eb4da4

Should be coverd, I hope...
