### ISSUE TITLE
how to send with filename

### ISSUE THREAD

**Issue by Brijeshkrishna** [eternnoir/pyTelegramBotAPI#1170]
1. pyTelegramBotAPI 3.7.9

2. windows 10 64bit

3. Python 3.9.5

how to send document with  filename

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/detailed_example/detailed_example.py

**Comment by Brijeshkrishna** [comment]
if i have a file name called " file.txt " . if i want to send with other name without renaming the file

**Comment by Badiboy** [comment]
You cannot
