### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 429: Too Many Requests Error

### ISSUE THREAD

**Issue by Pycomet** [eternnoir/pyTelegramBotAPI#1171]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? - 3.7.9

2. What OS are you using? - Linux (Ubuntu 18.04)

3. What version of python are you using?  - 3.6.9

```
from config import *
def start_menu(msg):
    keyboard = types.ReplyKeyboardMarkup(row_width=2)
    
    a = types.KeyboardButton(translator.translate("I Am A Passenger?", LANGUAGE))
    b = types.KeyboardButton(translator.translate("I Am A Bus Operator?", LANGUAGE))
    c = types.KeyboardButton(translator.translate("Referral Link", LANGUAGE))
    d = types.KeyboardButton(translator.translate("About Us", LANGUAGE))
    e = types.KeyboardButton(translator.translate("Rules & Regulations", LANGUAGE))
    f = types.KeyboardButton("Language Switcher")
    g = types.KeyboardButton("Contact Us")

    keyboard.add(a,b,c,d,e,f,g)
    return keyboard

@bot.message_handler(commands=['start'])
def startbot(msg):
    user.id = msg.from_user.id
    "Ignites the bot application to take action"
    response = str(translator.translate("Welcomkljmore.", LANGUAGE))
    bot.reply_to(
        msg,
        response,
        parse_mode='HTML',
        reply_markup=start_menu(msg)
    )

```

Everything I need is set up in the config. This structure has worked for me (a long time, till now). The errors seem to lie in the library plus there's blankly no response if I tried using the webhook method.

Can anyone help me out here?

**Comment by Badiboy** [comment]
Too many requests means that you got Temporary ban from Telegram for sending too many messages in small period of time.

**Comment by Pycomet** [comment]
Even so, that should not happen if I create a new bot and used the token on my script right?

**Comment by coder2020official** [comment]
Telegram limits sending messages - around 20 in channels/groups per second, and 30 messages per second for users.
For more read here: 
https://limits.tginfo.me/
