### ISSUE TITLE
Upload files more than 50MB

### ISSUE THREAD

**Issue by zwingify** [eternnoir/pyTelegramBotAPI#1180]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.9
2. What OS are you using?
Windows 10
3. What version of python are you using?
3.6

The telegram API limits bots to 50MB per upload. But when using a local API server https://core.telegram.org/bots/api#using-a-local-bot-api-server there is no limit. I was wondering if there was a way pyTelegramBotAPI can be used to send requests to a locally hosted telegram api to bypass the file size limit or if there is any other workaround.

**Comment by Badiboy** [comment]
Lib have no limits. If you use self hosted bot server - it will send larger files.

**Comment by zwingify** [comment]
> 
> 
> Lib have no limits. If you use self hosted bot server - it will send larger files.



> 
> 
> Lib have no limits. If you use self hosted bot server - it will send larger files.

My main problem is how to make pyTelegramBotAPI work with a locally self hosted bot server.

**Comment by Badiboy** [comment]
apihelper.API_URL
apihelper.FILE_URL

Both should be according to signature:
"https://api.telegram.org/bot{0}/{1}" (token, method_name)
"https://api.telegram.org/file/bot{0}/{1}" (token, file)
