### ISSUE TITLE
AttributeError: module 'telebot' has no attribute 'TeleBot' … pyTelegramBotAPI 3.7.9

### ISSUE THREAD

**Issue by itsDARKSAMA** [eternnoir/pyTelegramBotAPI#1185]
pyTelegramBotAPI Version: 3.7.9
OS : Manjaro 21.0.6 Ornara
Python Version :  3.9.5

when i try to run the code

```
import os
import telebot 
API_KEY = os.getenv('API_KEY') 
bot = telebot.TeleBot(API_KEY)

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
	bot.reply_to(message, "Howdy, how are you doing?")

bot.polling() 
```
it's always give me the same error message 
```
Traceback (most recent call last):
  File "/home/dark/Desktop/TelegramBot/main.py", line 4, in <module>
    bot = telebot.TeleBot(API_KEY)
AttributeError: module 'telebot' has no attribute 'TeleBot'
```
I tried this to fix the problem, but not fixed
```
pip uninstall telebot
pip install pyTelegramBotAPI
```

**Comment by Badiboy** [comment]
> I tried this to fix the problem, but not fixed

You should try better. This is the fix.

**Comment by itsDARKSAMA** [comment]
> > I tried this to fix the problem, but not fixed
> 
> You should try better. This is the fix.

What can I do more, I deleted the Package and reinstall it many times but the same problem, when i try to use the Replit , the module works well but in pc and vscode it's not
