### ISSUE TITLE
Bot doesn't recognize group commands?

### ISSUE THREAD

**Issue by Diogovski** [eternnoir/pyTelegramBotAPI#1188]
Hi, i am trying to create a bot to manage a community, where users would use the commands to get the information they need.I coded the part where he sends the message on the group after receiving the command, but he only does that if i send the command on a private message to him, how can i make him able to recognize group commands?

import os
import telebot

API_KEY = os.environ['TOKEN']
()
bot = telebot.TeleBot(API_KEY)
@bot.message_handler(commands=['info'])
def sendinfo(message):
    bot.send_message(-1001190057099,"Howdy, how are you doing?")

bot.polling()

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
 Last version3.7.9
2. What OS are you using?
 Windows
3. What version of python are you using?
 Pyhon 3

**Comment by Badiboy** [comment]
I suppose you did not disable Privacy in @bofather for your bot.

**Comment by Diogovski** [comment]
i disabled it

**Comment by Badiboy** [comment]
1. If you did it AFTER you added bot to group - remove bot from the group and add it again.
2. Bot should be admin.
3. Test on common text messages, not on command.

**Comment by Diogovski** [comment]
still doesnt work

**Comment by Diogovski** [comment]
okay solved it, i was using a channel instead of a group
