### ISSUE TITLE
how could I get all the users information that used my bot ?

### ISSUE THREAD

**Issue by Ro0kie** [eternnoir/pyTelegramBotAPI#1189]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
   latest

2. What OS are you using?
  ubuntu18.04

3. What version of python are you using?
  3.7

needs :
for example , one user uses my bot ,then one day later,he changes his first name,last name, username,
and never use my bot any more
but he does something bad with my bot, how can I find his  ,first name,last name, username,
the only information I get is his telegram user id

**Comment by Badiboy** [comment]
I suppose it's not possible.

**Comment by coder2020official** [comment]
If you have only his id, u may:
tg://user?id=yourid
Link to that person. Remember, it should be used only in parse mode. Telegram doesn't open, but if you send this message from bot by using parse mode, it ll work

**Comment by coder2020official** [comment]
Can't we close this issue?
