### ISSUE TITLE
Unable to get message length!

### ISSUE THREAD

**Issue by Diogovski** [eternnoir/pyTelegramBotAPI#1190]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
 Last version
2. What OS are you using?
 Windows
3. What version of python are you using?
4. Last

Hi i am trying to make a bot that deletes messages when having more than 600 characters to avoid spam in the group, but i seem unable to get the message length? Is there an alternative way to get it?

Error:
AttributeError: 'str' object has no attribute 'Length'

Code:

import os
import telebot

API_KEY = os.environ['TOKEN']
()
bot = telebot.TeleBot(API_KEY, False)
@bot.message_handler(commands=['shill'])
def sendinfo(message):
    bot.send_message(-1001269763792,"Howdy, this is the best shilling group!")

@bot.message_handler()
def echo_messages(*messages):
    """
    Getting Last Messages.
    """
    for m in messages:
        chatid = m.chat.id
        if m.content_type == 'text':
            text = m.text
            if text.Length > 600:
              bot.delete_message(chatid,text)
             

bot.polling()

**Comment by Badiboy** [comment]
You should start from learning Python.
