### ISSUE TITLE
Bots are unable to download received files/photos/videos

### ISSUE THREAD

**Issue by pevdh** [eternnoir/pyTelegramBotAPI#12]
When bots receive a file/photo/video/sticker, they are unable to download it from the Telegram servers.

As far as I know, this is a limitation of the Telegram Bot API. I really hope they add this feature anytime soon to their API.

**Comment by Kondra007** [comment]
Still an issue? 
Any solutions?

**Comment by pevdh** [comment]
Telegram hasn't added this feature to their api as of yet. I remember BotSupport told someone on reddit that this feature is almost guaranteed to be implemented at some point in the future, although I cannot find the source link right now.

--- Oorspronkelijk bericht ---

Van: "Kondra007" <notifications@github.com>
Verzonden: 22 juli 2015 21:38
Aan: "eternnoir/pyTelegramBotAPI" <pyTelegramBotAPI@noreply.github.com>
CC: "Pieter" <pevdh@live.nl>
Onderwerp: Re: [pyTelegramBotAPI] Bots are unable to download received files/photos/videos (#12)

Still an issue?
Any solutions?

---

**Comment by Kondra007** [comment]
I'm more concerned, that all pictures uploaded to Telegram have url like
`filesystem:https://web.telegram.org/temporary/5458many_numbers85848.jpg`
And these links (even without `filesystem`) lead to 404 :(

**Comment by pevdh** [comment]
There probably is a MTProto call for retrieving the files, but that protocol is way out of my area of expertise..

--- Oorspronkelijk bericht ---

Van: "Kondra007" <notifications@github.com>
Verzonden: 22 juli 2015 21:51
Aan: "eternnoir/pyTelegramBotAPI" <pyTelegramBotAPI@noreply.github.com>
CC: "Pieter" <pevdh@live.nl>
Onderwerp: Re: [pyTelegramBotAPI] Bots are unable to download received files/photos/videos (#12)

I'm more concerned, that all pictures uploaded to Telegram have url like
`filesystem:https://web.telegram.org/temporary/5458many_numbers85848.jpg`
And these links (even without `filesystem`) lead to 404 :(

---

**Comment by Kondra007** [comment]
Yes. Due to Pavel Durov's words, new updates coming late in August.
