### ISSUE TITLE
ForceReply and ReplyKeyboardMarkup need new keyword str: input_field_placeholder

### ISSUE THREAD

**Issue by AndydeCleyre** [eternnoir/pyTelegramBotAPI#1202]
This change just came today!

`input_field_placeholder`

- API doc for [ReplyKeyboardMarkup](https://core.telegram.org/bots/api#replykeyboardmarkup)
  - *Optional.* The placeholder to be shown in the input field when the keyboard is active; 1-64 characters
- API doc for [ForceReply](https://core.telegram.org/bots/api#forcereply)
  - *Optional.* The placeholder to be shown in the input field when the reply is active; 1-64 characters

1. What version of pyTelegramBotAPI are you using?

`3.7.9`

2. What OS are you using?

Arch Linux

3. What version of python are you using?

`3.9.5`

**Comment by Badiboy** [comment]
Implemented.
https://github.com/eternnoir/pyTelegramBotAPI/pull/1206

**Comment by AndydeCleyre** [comment]
Thank you!
