### ISSUE TITLE
Get message by id

### ISSUE THREAD

**Issue by pinguluk** [eternnoir/pyTelegramBotAPI#1213]
https://core.telegram.org/method/messages.getMessages
https://docs.pyrogram.org/api/methods/get_messages

I see there 's a method to get a message by id. I want to read a message by giving the bot the message id and the use it further in my custom functions.
I don't think that you currently have this implemented, right?

1. What version of pyTelegramBotAPI are you using?
Latest

2. What OS are you using?
Windows 10

3. What version of python are you using?
3.7

**Comment by Badiboy** [comment]
It's not a Bot API, it's Client API. Use https://github.com/LonamiWebs/Telethon to access these functions.

Bot functions are here: https://core.telegram.org/bots/api
