### ISSUE TITLE
How to make throughput test of a bot?

### ISSUE THREAD

**Issue by koren-v** [eternnoir/pyTelegramBotAPI#1218]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Version: 3.8.1
2. What OS are you using?
Mac OS
3. What version of python are you using?
Python 3.6.5

Hi, would like to ask you, does any way to simulate the workload on the bot to test the throughput?

**Comment by AndydeCleyre** [comment]
You might want to use a (non-bot) Telegram API wrapper like [Telethon](https://docs.telethon.dev/en/latest/) to automate your regular user.
