### ISSUE TITLE
bot ask for verification and make session on mobile devise (Samsung Galaxy)

### ISSUE THREAD

**Issue by OZOAR** [eternnoir/pyTelegramBotAPI#1227]
python 3.8 , Pytelegrambotapi 3.8.1. @coinexfaq_bot 

from time to time requires authentication and creates a session on the Samsung Galaxy
![image](https://user-images.githubusercontent.com/23193846/125430565-e1a00cfb-3b62-4ed4-921f-3b8f9d246aa7.png)
![image](https://user-images.githubusercontent.com/23193846/125430576-d5d549a3-86b6-4826-8be2-c757322a9b48.png)
![image](https://user-images.githubusercontent.com/23193846/125430589-f824ba57-d789-4652-9ea8-44261461c23c.png)

What could it be?

**Comment by BLUE-DEVIL1134** [comment]
firstly its off-topic
secondly, congratulations your telegram account got hacked by a bot.

**Comment by OZOAR** [comment]
by mine bot ?

**Comment by OZOAR** [comment]
@BLUE-DEVIL1134  my code from local server was hacked ?

**Comment by BLUE-DEVIL1134** [comment]
> @BLUE-DEVIL1134 my code from local server was hacked ?

no, you gave access of your telegram account to the bot backend codes, thus your account is probablly hacked
