### ISSUE TITLE
How to make a blacklist of words?

### ISSUE THREAD

**Issue by bluebudgiedev** [eternnoir/pyTelegramBotAPI#1233]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2. What OS are you using?
I’m using Windows 10 but the code is on the cloud.

3. What version of python are you using?
I’m using Python 3.7 version

How I can made a blacklist of words in a file for example “bad-words.txt”?

Thanks!

**Comment by Badiboy** [comment]
Not a subject of thelibrary.

**Comment by BLUE-DEVIL1134** [comment]
i know its not related but just wanna help so -
if you want to blacklist some specific words day ["hi", "bye", "ok"], then in your code you can do ->

```python
@bot.message_handler(commands=["start"])
def blackListedWords(message):
    for i in ["hi", "bye", "ok"]:
        if i in message.message: # I forgot what's the text reference is
            print("This Word Is Black Listed")
            bot.send_message(message.chat.id, "This is a black listed word...")
```

**Comment by bluebudgiedev** [comment]
Thank you @BLUE-DEVIL1134!
The code works.

**Comment by BLUE-DEVIL1134** [comment]
You are welcome...
