### ISSUE TITLE
How I can restrict/ban a user by user id

### ISSUE THREAD

**Issue by bluebudgiedev** [eternnoir/pyTelegramBotAPI#1234]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2. What OS are you using?
Windows 10 (but the code is on the cloud)

3. What version of python are you using?
Python 3.7

this code:

`
bot.restrict_chat_member(chat_id=*****)
`
Don’t work.
What I can do? Thanks!

**Comment by Badiboy** [comment]
Hmmm... Does Telegram should use telepaty to identify which user you want to restrict?

PS: looking on method signature and its description may give you lot of information about how to use it...
