### ISSUE TITLE
How I ban a user when joins a group?

### ISSUE THREAD

**Issue by bluebudgiedev** [eternnoir/pyTelegramBotAPI#1235]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2. What OS are you using?
Windows 10

3. What version of python are you using?
Python 3.7

How I can ban a user when joins a group and the user is in a blacklist?

Thanks!

**Comment by Badiboy** [comment]
https://core.telegram.org/bots/api#message
(see new_chat_members)

https://core.telegram.org/bots/api#restrictchatmember

**Comment by bluebudgiedev** [comment]
I used this code:
`
def UsersBlacklist(message):
     for i in [“userid1” , “userid2” , “userid3”]:
           if i in new_chat_members:
       bot.restrictchatmember(message.chat.id)

`

but it don’t work!

**Comment by Badiboy** [comment]
You should learn programming and reading.
