### ISSUE TITLE
how can I make the  \n  in the text of button  effective ?

### ISSUE THREAD

**Issue by Ro0kie** [eternnoir/pyTelegramBotAPI#1242]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?latest

2. What OS are you using?  docker 

3. What version of python are you using? 3.7
4.

sorry my english is not good , I will try to express my problem

this is the code
markup.add(types.InlineKeyboardButton(text='sfsdfsfsfsfgfefsdrrrrrrrrrrrrrr\nrrrrrrrrrrrrrrrrrrr',callback_data='add_one_thing'))

but  the \n    in  the  text    is not effective

when I use the bot, the text on the button is still one line , not two

**Comment by Badiboy** [comment]
I suppose that this is Telegram limitation that Inline buttons cannot be multiline. 
Did you ever seen multiline inline buttons?

**Comment by Ro0kie** [comment]
https://ftp.bmp.ovh/imgs/2021/07/1b09b2849bd70b9d.png

my friend  make a demo using  pyrogram and \n

**Comment by Badiboy** [comment]
**Test code**

```
import telebot
from telebot import types
telebot.logger.setLevel('DEBUG')
bot_token = "XXX"
chat = 'XXX'
bot = telebot.TeleBot(bot_token)
markup = types.InlineKeyboardMarkup()
markup.add(types.InlineKeyboardButton(text='123\n456\n789',callback_data='add_one_thing'))
bot.send_message(chat, "Button test", reply_markup=markup)
m2 = types.ReplyKeyboardMarkup(resize_keyboard=True)
m2.row('123\n456\n789')
bot.send_message(chat, "Button test", reply_markup=m2)
```

**Debug log**

> 2021-07-22 16:02:11,801 (apihelper.py:83 MainThread) DEBUG - TeleBot: "Request: method=post url=https://api.telegram.org/botXXX:{TOKEN}/sendMessage params={'chat_id': 'XXX', 'text': 'Button test', 'reply_markup': '{"inline_keyboard":[[{"text":"123\\n456\\n789","callback_data":"add_one_thing"}]]}'} files=None"
> 2021-07-22 16:02:11,999 (apihelper.py:141 MainThread) DEBUG - TeleBot: "The server returned: 'b'{"ok":true,"result":{"message_id":73780,"from":{"id":XXX,"is_bot":true,"first_name":"MB Test - Head","username":"BuildMenuTestBot"},"chat":{"id":XXX,"first_name":"A","last_name":"A","username":"Badiboy","type":"private"},"date":1626958931,"text":"Button test","reply_markup":{"inline_keyboard":[[{"text":"123\\n456\\n789","callback_data":"add_one_thing"}]]}}}''"
> 2021-07-22 16:02:11,999 (apihelper.py:83 MainThread) DEBUG - TeleBot: "Request: method=post url=https://api.telegram.org/botXXX:{TOKEN}/sendMessage params={'chat_id': 'XXX', 'text': 'Button test', 'reply_markup': '{"keyboard":[[{"text":"123\\n456\\n789"}]],"resize_keyboard":true}'} files=None"
> 2021-07-22 16:02:12,091 (apihelper.py:141 MainThread) DEBUG - TeleBot: "The server returned: 'b'{"ok":true,"result":{"message_id":73781,"from":{"id":XXX,"is_bot":true,"first_name":"MB Test - Head","username":"BuildMenuTestBot"},"chat":{"id":XXX,"first_name":"A","last_name":"A","username":"Badiboy","type":"private"},"date":1626958931,"text":"Button test"}}''"

You can see that both Inline and Reply buttons are sent in the same manner and returned (for inline) also in the same manner.

**Results**
Desktop
![image](https://user-images.githubusercontent.com/5613421/126643892-3da4eb86-4f76-4c66-85c2-6cbf293b3759.png)
Unigram
![image](https://user-images.githubusercontent.com/5613421/126644819-567385e4-cca3-4ced-9015-2c817efdedc9.png)
TelegramX
![image](https://user-images.githubusercontent.com/5613421/126644096-ac8064de-c0ca-4b40-a119-3ef8806d193e.png)

You can see that decision about word wrap is taken by client.

**Comment by Ro0kie** [comment]
thank you so much  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
