### ISSUE TITLE
how to getuserprofilephotos??

### ISSUE THREAD

**Issue by davi78** [eternnoir/pyTelegramBotAPI#1246]
@bot.message_handler(commands=['myprofile'])
def profile(message):
    myprofile= bot.get_user_profile_photos(message.from_user.id)
    print(myprofile)

Output:
{'total_count': 2, 'photos': [[<telebot.types.PhotoSize object at 0x000001F2281AA880>, <telebot.types.PhotoSize object at 0x000001F2281AA8E0>, <telebot.types.PhotoSize object at 0x000001F2281E6730>], [<telebot.types.PhotoSize object at 0x000001F2281E66D0>, <telebot.types.PhotoSize object at 0x000001F2281E6580>, <telebot.types.PhotoSize object at 0x000001F2281E6AC0>]]}

**Comment by coder2020official** [comment]
https://core.telegram.org/bots/api#photosize
Get the class itself by indexing[0] then try to get .file_id attribute.

**Comment by coder2020official** [comment]
You need to get PhotoSize class, that's all.

**Comment by davi78** [comment]
> myprofile.get('photos')[0][0] should get first class. If you need to loop every photo, use for loop and iterate through each photo. After u get the class, you just get .file_id parameter like shown in api

this code??

**Comment by davi78** [comment]
> myprofile.get('photos')[0][0] should get first class. If you need to loop every photo, use for loop and iterate through each photo. After u get the class, you just get .file_id parameter like shown in api

thanks for you
