### ISSUE TITLE
Send message with linked text.

### ISSUE THREAD

**Issue by Jzarecta** [eternnoir/pyTelegramBotAPI#125]
I want to return an rss news items hyperlinked to the individual post. I've tried using markup language [text](url) and regular html, but still get it unrendered.

**Comment by eternnoir** [comment]
Do you use `HTML`  parse_mode in send_message method? 

```
tb.send_message(CHAT_ID, htmlstring, parse_mode="HTML")
```

**Comment by Jzarecta** [comment]
Thanks, it worked :dancers:
