### ISSUE TITLE
new_chat_members isn't updating on big groups (100k users)

### ISSUE THREAD

**Issue by ballinger-guillaume** [eternnoir/pyTelegramBotAPI#1250]
pyTelegramBotAPI version: 3.8.2
OS: Windows 10
Python: 3.7

To get new updates when a user is joining I use the following function:

```py
@bot.message_handler(content_types=["new_chat_members"])
def blackList(message):
# some code to block certain names
```

The snippet works fine on smaller groups (20k users). What I have noticed is that on higher groups they are turning off the "user x has joined" notification/label. I supposed that this function relied on that message in the chat which would also be visible in the JSON when pooling the data from the server.

So in the meanwhile is there any other option that would show us the latest user that joined? I tried with `bot.chat(IDOfChat)` but the new_chat_members is equal to NONE.

Any help would be preciated.

**Comment by coder2020official** [comment]
Hi!

Recently, there was a warning in telegram bot api website. Read below:
Service messages about non-bot users joining the chat will be soon removed from large groups. We recommend using the “chat_member” update as a replacement.
So, you should use chatMember from now. Here are some useful things:
[Using new handlers](https://github.com/coder2020official/chatMember/blob/main/main.py)
More on new handlers:
We have my chat member handler, it is used when bot is added to group.
chat member handler is for any people entering the chat
When the status of a user changes, telegram gives update that his status has changed. Read more on [statuses](https://core.telegram.org/bots/api#chatmember)

**Comment by ballinger-guillaume** [comment]
Thank you I will try it out and report if it helped.

**Comment by ballinger-guillaume** [comment]
@coder2020official  thank you that worked. For future references make sure to use:

```py
bot.polling(allowed_updates=util.update_types)
```

Without it it won't work.

**Comment by MaGua-Bishop** [comment]
Thanks, this problem has been bothering me for three days, but my code is webhook, and I found that I only need to add 

`allowed_updates=util.update_types`
 parameter to set_webhook to receive member addition information
