### ISSUE TITLE
smart_split

### ISSUE THREAD

**Issue by mraihanfs** [eternnoir/pyTelegramBotAPI#1252]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.8.2

2. What OS are you using? Windows 10 

3. What version of python are you using? 3.9.5

Why i cant use telebot.util.smart_split function the error say : AttributeError: module 'telebot.util' has no attribute 'smart_split' 
and here my code 
`from telebot import util
f = open('command to open jupyter notebook in capstone project.txt','rb').read()
    
split_text = util.smart_split(f, 3000)

print(split_text)`

**Comment by ballinger-guillaume** [comment]
If you use pip install it will only give you the __init__ file which doesn't contain the util part.
If you wish to have the util part you will need to clone the repo and put the files in your library part of the project.

**Comment by Badiboy** [comment]
```
from telebot import util
split_text = util.smart_split("ololo", 3000)
print(split_text)
```

![image](https://user-images.githubusercontent.com/5613421/130236666-98af4435-125e-4538-8885-b4b292d7997a.png)

Works fine.  Try to re-install the package.

**Comment by mraihanfs** [comment]
Ok i'll try thank u before
