### ISSUE TITLE
runing one bot in several servers

### ISSUE THREAD

**Issue by saniar-mf** [eternnoir/pyTelegramBotAPI#1253]
Hi dears.
how we can ron one telegram bot in several servers?
there is a way to division messages to several servers?

**Comment by BLUE-DEVIL1134** [comment]
you cant run 1 but at 2 diff places, telegram limits...

**Comment by ballinger-guillaume** [comment]
concurrent run would be possible but parallel isn't.
You can only have 1 request to the API from one place with 1 token. So you would have to time the request in a way that one server would run it than the other one.

But this would be a lot of work to do where you could simply run it in one single instance.

**Comment by Badiboy** [comment]
You can run bot on multiple servers, but only one of them can RECIEVE messages with poll or webhooks. Other servers can send messages as they want to.

With webhooks you can use incomming proxy and route income requests to multiple servers. Something like load balancer - it will work.
