### ISSUE TITLE
How can I catch exception during polling?

### ISSUE THREAD

**Issue by Skywal** [eternnoir/pyTelegramBotAPI#1256]
1. pyTelegramBotAPI = 3.8.1

2. Windows 10

3. python=3.6+

Hello, is there some way to catch all ApiException outside of polling()? I know that inside there is already exception handling and logging but I need more control over this process.

**Comment by Badiboy** [comment]
Use
exception_handler
parameter of TeleBot constructor.

It should be the class instance inherited from ExceptionHandler.

**Comment by Skywal** [comment]
It worked, thanks!
