### ISSUE TITLE
Forgot to chage type for BotCommandScopeChatMember

### ISSUE THREAD

**Issue by netbriler** [eternnoir/pyTelegramBotAPI#1260]
https://github.com/eternnoir/pyTelegramBotAPI/blob/554b39a49aceccac02a7759affe897a43737255b/telebot/types.py#L1383

Change the type to `'chat_member'` instead of `'chat_administrators'`

**Comment by Badiboy** [comment]
Thanks.

Fixed: https://github.com/eternnoir/pyTelegramBotAPI/pull/1261
