### ISSUE TITLE
Getting live location from Users

### ISSUE THREAD

**Issue by igormcsouza** [eternnoir/pyTelegramBotAPI#1262]
Hello! This tool to work with telegram bot is very nice, congrats! I was using it those days and came across the issue of creating a system to get users live location!! Using the message handles watching for location I'm able to get the current user location! But I couldn't find on docs how to get the update of this location, so I can follow the users location over time!! How to do it with the bot!?

**Comment by Badiboy** [comment]
If the bot does not receive new "location" when user posts live location - then it's not possible.

**Comment by igormcsouza** [comment]
I don't get it @Badiboy ... You telling me it's not possible with **pyTelegramBotAPI**, or you saying I'm doing a mistake which turns live location unavailable?

**Comment by Ediii96** [comment]
Hello.
Has the situation with location broadcasting changed?

I tried to do it using the "python-telegram-bot" library and everything worked out there.
