### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in the telegrambot

### ISSUE THREAD

**Issue by davi78** [eternnoir/pyTelegramBotAPI#1267]
RecursionError: maximum recursion depth exceeded deploy in the heroku

**Comment by coder2020official** [comment]
Code?

**Comment by davi78** [comment]
> Code?

if the code is no problem, but if it is deployed on heroku there is a problem, namely at 2 am to 5 pm there is no problem on heroku, if it is 5 pm to 1 am the bot does not work, and raises RecursionError: maximum recursion depth exceeded

**Comment by Badiboy** [comment]
No code - no telepats here.
