### ISSUE TITLE
Error in urllib3

### ISSUE THREAD

**Issue by MonsterDeveloper** [eternnoir/pyTelegramBotAPI#127]
Hey. I am using this library with Python3.5 and sometimes i get this error:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botTOKEN/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcfe0c8ada0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Any ideas how to fix that? (I replaced my token with word TOKEN

**Comment by MonsterDeveloper** [comment]
I upgraded to Python3.5 yesterday and with Python3.4 this error doesn't appear

**Comment by MonsterDeveloper** [comment]
Well, its happening again(

**Comment by Tronikart** [comment]
Its also happening to me, using python 2.7.10

**Comment by gise88** [comment]
Same here! Seems that the telegram servers reject our connection.. I have temporarily worked around this problem as follows:

```
while True:
	try:
		bot.polling(none_stop=True)
	except requests.exceptions.ConnectionError as e:
		print >> sys.stderr, str(e)
		time.sleep(15)
```

**Comment by Tronikart** [comment]
Thats how I have it implemented, I will add the sleep(), it sometimes pops the error and doesnt load backup again, maybe with the sleep it will be more reliable
