### ISSUE TITLE
Impossible to modify reply_markup

### ISSUE THREAD

**Issue by DwaynGFX** [eternnoir/pyTelegramBotAPI#1271]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? : 3.8.3

2. What OS are you using? : Windows

3. What version of python are you using? : 3.8.5

It's seems impossible to edit the reply_markup of a bot message.. I get the following error: "Error code: 400. Description: Bad Request: message can't be edited"

This is my code:

```
order_markup = types.InlineKeyboardMarkup()
order_markup.add(types.InlineKeyboardButton(text='\U0001F44C Commander', callback_data='order_button_callback'))

start_msg = bot.send_message(message.chat.id, msgs.start, reply_markup=types.ReplyKeyboardRemove())
bot.edit_message_reply_markup(message.chat.id, message_id=start_msg.message_id, reply_markup=order_markup)
```

I don't understand why, I just try to edit the reply_markup of a bot message..

**Comment by Badiboy** [comment]
Try to make a delay of several seconds between post and edit.

**Comment by DwaynGFX** [comment]
doesn't work with time.sleep(5)

**Comment by Badiboy** [comment]
Frankly speaking, the problem is on the TG side.

```
reply_markup=types.ReplyKeyboardRemove()
reply_markup=order_markup
```

I suppose that it's not possible to ADD buttons to message where there was no buttons. 
This code works fine:
```

order_markup1 = types.InlineKeyboardMarkup()
order_markup1.add(types.InlineKeyboardButton(text='\U0001F44C Commander1', callback_data='order_button_callback'))

order_markup2 = types.InlineKeyboardMarkup()
order_markup2.add(types.InlineKeyboardButton(text='\U0001F44C Commander2', callback_data='order_button_callback'))

start_msg = bot.send_message(chat, "Ololo", reply_markup=order_markup1)
bot.edit_message_reply_markup(chat, message_id=start_msg.message_id, reply_markup=order_markup2)

```
