### ISSUE TITLE
What fix 3.7.4 version?

### ISSUE THREAD

**Issue by birkmanjon** [eternnoir/pyTelegramBotAPI#1279]
Hey! I have been using your library for a long time, together with python3 and it was fine with me. Now there is a need to update python to version 3.8, and then the library to version 3.8.3 and some of its behavior alarmed me. I started rolling back versions down to 3.7.3 and realized that my code works great on this version, but not as expected since 3.7.4. What could have changed in version 3.7.4, and how will it adapt to me? The problem is this: in the decorator, I print a deliberately non-existent variable and get an error in the terminal. Starting from version 3.7.4, the code in the decorator, as before, is executed to a bad line and does not output anything. It's a trifle, but it made me sweat to understand that the problem is in the version of the library. Thank you in advance!

**Comment by birkmanjon** [comment]
A simple and illustrative example above, let's modify it so that you can just copy it.

The answer to the command /ps:

`userlist =[YOU ID]`
`@bot.message_handler(func=lambda message: message.chat.id in userlist, commands=['ps'])`
`def otvet_ps(message):`
`   print('one str')`
`   print(kukaracha)`
`   print('two str')`

**Comment by Badiboy** [comment]
It's funny. If you do not need assistance - ok.

**Comment by birkmanjon** [comment]
A simple and illustrative example above, let's modify it so that you can just copy it.

The answer to the command /ps:

`userlist =[YOU ID]`
`@bot.message_handler(func=lambda message: message.chat.id in userlist, commands=['ps'])`
`def otvet_ps(message):`
`   print('one str')`
`   print(kukaracha)`
`   print('two str')`

**Comment by birkmanjon** [comment]
API_TOKEN = '#####

WEBHOOK_HOST = 'WHITE IP'
WEBHOOK_PORT = 88  
WEBHOOK_LISTEN = '127.0.0.1' 
WEBHOOK_URL_BASE = "https://%s:%s" % (WEBHOOK_HOST, WEBHOOK_PORT)
WEBHOOK_URL_PATH = "/%s/" % (API_TOKEN)

WEBHOOK_SSL_CERT = 'PATH SSL CRT'  
WEBHOOK_SSL_PRIV = 'PATH SSL PK''  

bot = telebot.TeleBot(API_TOKEN)

**Comment by Badiboy** [comment]
Thanks, I'll check as soon as I can.

**Comment by Badiboy** [comment]
I have no cherry, so I updated it to flask based in echo_flask example.
Here is the full code.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This is a simple echo bot using decorators and webhook with flask
# It echoes any incoming text messages and does not use the polling method.

import logging
import time

import flask

import telebot

WEBHOOK_URL_BASE = "https://h.hh"
WEBHOOK_URL_PATH = "/test/testflask"

logger = telebot.logger
telebot.logger.setLevel(logging.DEBUG)

bot = telebot.TeleBot("xxxxxxxx:xxxxxxxxxxxxxxxxxxxxx")

app = flask.Flask(__name__)


# Empty webserver index, return nothing, just http 200
@app.route('/', methods=['GET', 'HEAD'])
def index():
    return 'ROOT'


# Process webhook calls
@app.route(WEBHOOK_URL_PATH, methods=['POST'])
def webhook():
    if flask.request.headers.get('content-type') == 'application/json':
        json_string = flask.request.get_data().decode('utf-8')
        update = telebot.types.Update.de_json(json_string)
        bot.process_new_updates([update])
        return ''
    else:
        flask.abort(403)


# Handle '/start' and '/help'
@bot.message_handler(commands=['help', 'start'])
def send_welcome(message):
    bot.reply_to(message,
                 ("Hi there, I am EchoBot.\n"
                  "I am here to echo your kind words back to you."))

userlist = [111111111]
@bot.message_handler(func=lambda message: message.chat.id in userlist, commands=['ps'])
def otvet_ps(message):
	print('one str')
	print(kukaracha)
	print('two str')

# Handle all other messages
@bot.message_handler(func=lambda message: True, content_types=['text'])
def echo_message(message):
    bot.reply_to(message, message.text)


# Remove webhook, it fails sometimes the set if there is a previous webhook
bot.remove_webhook()

time.sleep(1)

# Set webhook
bot.set_webhook(url=WEBHOOK_URL_BASE + WEBHOOK_URL_PATH)

# Start flask server
app.run(host="10.0.0.4",
        port=88,
        debug=True)

```

Error reporting works fine for me.

![image](https://user-images.githubusercontent.com/5613421/132101724-825a94e3-767c-403c-8e29-b7a09f58b506.png)

The library version installed there is 3.8.2.

**Comment by birkmanjon** [comment]
Thanks! I will watch cherrypy.)
