### ISSUE TITLE
Send file with special characters in his name

### ISSUE THREAD

**Issue by Nideapum** [eternnoir/pyTelegramBotAPI#128]
Hello,

the problem is when i try to send a file with á, é, í, ó, ú, ñ ... etc

I have this code 
`@bot.message_handler(content_types=['text'])`
`def command_default(m):`
`    # chat_id = m.chat.id`
`    audio=open(path_audio+'á.mp3', 'rb')`
`    print audio`
`    bot.send_audio(chat_id, audio)`

its return: `<open file '\xc3\xa1.mp3', mode 'rb' at 0x76553cd8>`

* So.... **'bot.send_audio(chat_id, audio)'** don't find the file **'\xc3\xa1.mp3'** instead of **'á.mp3'**

* if the file don't have accent is work without problems

Some idea? Thanks

**Comment by Nideapum** [comment]
Nobody have any idea?

**Comment by pevdh** [comment]
Does `(path_audio+'á.mp3).decode('utf-8')` work?
