### ISSUE TITLE
Can't decorate step_handler with custom decorator

### ISSUE THREAD

**Issue by blackacornlabs** [eternnoir/pyTelegramBotAPI#1280]
pyTelegramBotAPI==3.7.4
Ubuntu 20.04.2 LTS
python 3.9.5

I'm trying to decorate step_handler with custom decorator like this:
```python
from functools import wraps

def check_text(err_message=None):
    """Decorator check that message has text"""
    def decorator(func):
        @wraps(func)
        def wrapper(message, *args, **kwargs):
            if not message.text:
                _err_message = err_message if err_message else "Could not get text from message."
                bot.reply_to(message, _err_message)
                bot.register_next_step_handler(message, func, *args, **kwargs)
                return
            return func(message, *args, **kwargs)
        return wrapper
    return decorator
    
@bot.message_handler(commands='new_invoice')
def new_invoice(message):
    bot.send_message(message.chat.id, "Insert invoice number")
    bot.register_next_step_handler(message, invoice_number_handler)
    
@check_text()
def invoice_number_handler(message):
    print(message.text)

```

...and getting this exception:

> Exception in thread Thread-15:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.9/threading.py", line 1266, in run
>     self.function(*self.args, **self.kwargs)
>   File ".../lib/python3.9/site-packages/telebot/handler_backends.py", line 76, in save_handlers
>     self.dump_handlers(self.handlers, self.filename)
>   File ".../lib/python3.9/site-packages/telebot/handler_backends.py", line 92, in dump_handlers
>     pickle.dump(handlers, file)
> _pickle.PicklingError: Can't pickle <function invoice_number_handler at 0x7fa023a16430>: it's not the same object as __main__.invoice_number_handler

How can I avoid this exception?

Edit: I found out that `register_next_step_handler` works well with decorator, but exception is still there.

**Comment by blackacornlabs** [comment]
I guess I understood everything correctly: I need to store handlers - because I use `register_next_step_handler`. But still, `register_next_step_handler` works in spite of this exception, so it is not clear for me - what do I need this storing for?

Alternatively, I read a bit of code and found out that I can use CUSTOM_SERIALIZER to handle storing. Can you please provide a code which initialize some new serializer for my bot?

Here's the code and condition with CUSTOM_SERIALIZER:

```python
    def dump_handlers(handlers, filename, file_mode="wb"):
        dirs = filename.rsplit('/', maxsplit=1)[0]
        os.makedirs(dirs, exist_ok=True)

        with open(filename + ".tmp", file_mode) as file:
            if (apihelper.CUSTOM_SERIALIZER is None):
                pickle.dump(handlers, file)
            else:
                apihelper.CUSTOM_SERIALIZER.dump(handlers, file)

        if os.path.isfile(filename):
            os.remove(filename)

        os.rename(filename + ".tmp", filename) 
```

**Comment by Badiboy** [comment]
As you can see:
![image](https://user-images.githubusercontent.com/5613421/131327567-8ab5db99-9fd0-4fad-928a-7a25c65197b2.png)
by default Memory backend is used. It does not use pickle and cannot lead to your problem.

You use File backend.  Either you mentioned it obviously in init, or you used
enable_save_next_step_handlers
from one of examples. If you do not need it - do not use it...

**Comment by egorgvo** [comment]
Yeah, that's true - I've used `enable_save_next_step_handlers`. Thank you for your explanation!
