### ISSUE TITLE
ImportError: No module named telebot

### ISSUE THREAD

**Issue by Lucifer25x** [eternnoir/pyTelegramBotAPI#1283]
1. What version of pyTelegramBotAPI are you using?
3.8.3

2. What OS are you using?
Windows 

3. What version of python are you using?
3.8.7

Error:
```sh
$ ImportError: No module named telebot
```

**Comment by Badiboy** [comment]
Reinstall pyTelegramBotAPI

**Comment by Lucifer25x** [comment]
I tried it 3-4 times.But it not worked.
