### ISSUE TITLE
Message handler doesn't handle the messages that are sent by a bot.

### ISSUE THREAD

**Issue by realmasonjam** [eternnoir/pyTelegramBotAPI#1286]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.7.9

2. What OS are you using? mac & windows

3. What version of python are you using? 3.9.2

I have set up the handler in the following way:

`MESSAGE_CONTENT_TYPES = ['text', 'audio', 'document', 'photo',
                         'sticker', 'video', 'video_note', 'voice', 'location', 'contact']
@bot.message_handler(content_types=MESSAGE_CONTENT_TYPES)
def handle_all_message(message):
`
It perfectly handles the messages that are coming from real users. But when a bot sends a message it doesn't handle it at all. Am I doing sth wrong or is that a bug? Thanks.

**Comment by Badiboy** [comment]
In Telegram bots do not see messages from bots. It's fundamental system limitation.
