### ISSUE TITLE
Telegram Bot API 2.0

### ISSUE THREAD

**Issue by sevazhidkov** [eternnoir/pyTelegramBotAPI#129]
What do you think?

https://core.telegram.org/bots/2-0-intro

Will pyTelegramBotAPI be adapted for new version of API?

**Comment by eternnoir** [comment]
Of course. But bot 2.0 has huge change. I create new branch for bot 2.0 development. https://github.com/eternnoir/pyTelegramBotAPI/tree/bot20

**Comment by MonsterDeveloper** [comment]
Does it support InlineKeyboardButton now?

**Comment by eternnoir** [comment]
Not yet.

**Comment by MonsterDeveloper** [comment]
Waiting for full 2.0 features support)

**Comment by MonsterDeveloper** [comment]
Sorry for that stupid question maybe, but how can i donate you? You library is really like emhhh...... amazing! I dont have lots of money, only 2 dollars( but i think that all money will help you)

**Comment by eternnoir** [comment]
Discussionabout bot2.0 move to https://github.com/eternnoir/pyTelegramBotAPI/issues/130
