### ISSUE TITLE
Adding Thumbnail to the video

### ISSUE THREAD

**Issue by RafayGhafoor** [eternnoir/pyTelegramBotAPI#1292]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

4.0.0

2. What OS are you using?

Arch Linux

3. What version of python are you using?

Python 3.9

---

Hi, I am unable to add a thumbnail to any video/animation. The code I am using is as follows

![image](https://user-images.githubusercontent.com/20343475/132398023-06c79774-7201-417e-aa2f-ffd7e873f7e6.png)

No error is shown. I have also tried with files > 10 MB and < 10 MB.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/detailed_example/detailed_example.py

Check here how to send files (see "send_photo").

**Comment by RafayGhafoor** [comment]
Doesn't work with this as well:

![image](https://user-images.githubusercontent.com/20343475/132406119-e9ab1c8b-d4f8-47de-97d6-e43e964bb32c.png)

**Comment by Badiboy** [comment]
Ah, sorry. Now I remeber. It's the old topic: you cannot assign NEW thumb to OLD file. You either should load both files or use file_id for both files.

**Comment by RafayGhafoor** [comment]
Thanks a lot for the quick reply. Trying it now.

How about if I would want to edit a thumbnail of an old video file, can I do it?

I am thinking of uploading a photo, and getting its file id, then using that file_id and video_id to update the media from the old message. Do you think that would work?

**Comment by Badiboy** [comment]
Frankly speaking I never tried both of operations, so I cannot say anything about it.
