### ISSUE TITLE
Heroku Deploy

### ISSUE THREAD

**Issue by Diogovski** [eternnoir/pyTelegramBotAPI#1294]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2. Latest

2. What OS are you using?
3. Windows

3. What version of python are you using?
4. 3.9 i think

This is more a heroku issue rather pyTelegramBotAPI!  Anyone knows what i am missing here? I get the following error when deploying on heroku( connected to git repository) and when is deploying it throws this error! Can anyone help me?

-----> Building on the Heroku-20 stack

-----> Using buildpack: heroku/python

-----> App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz

       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure

 !     Push failed

**Comment by BLUE-DEVIL1134** [comment]
its python buildpack error not the library...

**Comment by coder2020official** [comment]
The problem is with heroku, not library.
You have some incorrect option in procfile, or some other error
