### ISSUE TITLE
Updating lib

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#13]
Hello! I'm running Ubuntu 14.04 with pyTelegramBotAPI version about 0.1.5 or so
How can I update it? 
I've pulled the newest code from this repo, ran `sudo python2.7 setup.py install` and tried to use new functions (f.ex. `markup = types.ReplyKeyboardMarkup()`)
However, I get error `'module' object has no attribute 'ReplyKeyboardMarkup'`

**Comment by eternnoir** [comment]
Do you add `from telebot import types` in your source code?

**Comment by Kondra007** [comment]
My bad, I just wrote `import types` instead of `from telebot import types`
