### ISSUE TITLE
Inline keyboard with send_photo

### ISSUE THREAD

**Issue by UlugbekMuslitdinov** [eternnoir/pyTelegramBotAPI#1306]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.7.3

2. What OS are you using? Windows 10

3. What version of python are you using? 3.9

Hi! I cannot add the Inline Keyboard to the send_photo function. I have read the documentation but it didn't help. I am developing a bot connected to my Django application.
Here is the part of my code. 

```python
def dish_detail(m):
    dish_name = m.text
    try:
        dish = Dish.objects.get(name=str(dish_name))
    except Dish.DoesNotExist:
        tbot.reply_to(m, 'This dish name is incorrect. Choose it once more')
        tbot.register_next_step_handler(m, dish_detail)
    else:
        keyboard = types.InlineKeyboardMarkup()
        keyboard.row(
            types.InlineKeyboardButton(f"{dish.price}"),
        )
        tbot.send_photo(m.chat.id, dish.image, caption=f'{dish.price}', reply_markup=keyboard)
```

**Comment by coder2020official** [comment]
Any error u got?
Or it is not giving buttons?

**Comment by coder2020official** [comment]
Also, do not use too old version of pytelegambotapi.
The latest(currently) is 4.0.0

**Comment by UlugbekMuslitdinov** [comment]
> Any error u got?
> Or it is not giving buttons?

The errors are not logged because this is the part of views.py of my Django project. When I add code to display buttons, it doesn't work, but without buttons code, it works nice.

**Comment by coder2020official** [comment]
Instead of dish.price do
dish[0].get("price")

**Comment by Badiboy** [comment]
![Uploading image.png…]()
