### ISSUE TITLE
Issue with timeout

### ISSUE THREAD

**Issue by kartlife** [eternnoir/pyTelegramBotAPI#1319]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Last one

2. What OS are you using? Windows

3. What version of python are you using? 3.8

I make a python Bot with this API and it works fine, but if I left all the day active in some moment launchs this error, Any help?

```
HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)

During handling of the above exception, another exception occurred:

  File "<string>", line 3, in raise_from

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

  File "XXXXXXXXXXXXX\bot.py", line 265, in <module>
    bot.polling()
```

**Comment by Badiboy** [comment]
Sometime network or Telegram issues happen.

Handle excetions or use infinity_polling instead of polling.
