### ISSUE TITLE
many threads alive

### ISSUE THREAD

**Issue by sbongain** [eternnoir/pyTelegramBotAPI#132]
hi,
i'm having problems with the number of threads the bot creates when i send messages using "bot.send_message(cid, msg)", if i send, for example, 10 messages i have 20 threads alive and this threads doesn't stop. how can i stop or control the number of threads alive after send messages?
thx

edit1: i think i fixed it using bot.TeleBot(TOKEN,threaded=False), but... any other solution?

**Comment by SatoshiReport** [comment]
Same here

**Comment by SatoshiReport** [comment]
thanks sbongain for the edit/solution.
