### ISSUE TITLE
"one_time_keyboard=False" flag doesn't work in send_message method

### ISSUE THREAD

**Issue by almaz5000** [eternnoir/pyTelegramBotAPI#1321]
Hi all.

1. What version of pyTelegramBotAPI are you using?
pytelegrambotapi-4.1.0
2. What OS are you using?
Debian 10
3. What version of python are you using?
Python 3.7.3

I am trying to add keyboard with "one_time_keyboard=False" flag. Previosly it works good. After some time and some updates it doesn't work good. With flag False it shows one time keyboard, with flag True it shows one time keyboard too. What kind of problem it could be?

def main_menu():
    keys = types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=False)
    keys.row('butt1', 'butt2')
    return keys

bot.send_message(chat_id, text, reply_markup=keys)

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/135420663-21ddf84c-1924-496d-9405-9b8b09f3855b.png)

Oh my god... 

![image](https://user-images.githubusercontent.com/5613421/135420815-5b4ce183-654f-454b-9a9d-eef9bf2d6348.png)

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1322

Fixed.
