### ISSUE TITLE
Bot cannot reply in group only after I kicked it and added it back.

### ISSUE THREAD

**Issue by kevinyin9** [eternnoir/pyTelegramBotAPI#1327]
1. What version of pyTelegramBotAPI are you using?
4.0.1

2. What OS are you using?
macOS catalina 10.15.7

3. What version of python are you using?
3.8.5

```
@bot.message_handler(commands=['show_all'])
def show_all(message):
      bot.reply_to(message, 'show_all')
```
Hello, this problem confused me a while.
If I type /show_all in group, the bot won't reply.
If I dm the bot, it will reply.
If I kicked the bot, added it back in group, and typed the command, it will reply.
Why? 

Thank you.

**Comment by Badiboy** [comment]
95% that your bot had enabled "Privacy". Than you turned it off, but it will not affect the groups where bot was already added. When you remove and add it back it will affect.

**Comment by kevinyin9** [comment]
Thank you very much!
I solved it.
