### ISSUE TITLE
Help with multi command arguments

### ISSUE THREAD

**Issue by AnimusXCASH** [eternnoir/pyTelegramBotAPI#1328]
Hi, 

I have been going through examples and could not find the way how to make command with multiple arguments. 

for example 

`/register @username `

I would need to get the tagged users ID out of it. 

Thank you for your answer/assistance. 

Animus

**Comment by AnimusXCASH** [comment]
Any examples on how?

As i could not find it in examples part of github repo

thank you

**Comment by coder2020official** [comment]
![image](https://user-images.githubusercontent.com/63740404/136686967-dad38be5-b9b6-459f-b69b-ea43ab65f1b8.png)
Or, try this. Try passing the username of that person by splitting message.text.

**Comment by AnimusXCASH** [comment]
Thanks for answering
