### ISSUE TITLE
can't import telebot

### ISSUE THREAD

**Issue by mohamadyaserakbari** [eternnoir/pyTelegramBotAPI#1344]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.1.1
2. What OS are you using?
linux - ubuntu
3. What version of python are you using?
3.9.7
- - - - - - - - - - -- - - -- - - - - - -- - - - --  - - -- - -- - - -- - - - -- - - - 
hi, i can't import telebot in pyTelegramBotAPI and i get this error:
Traceback (most recent call last):
  File "/home/yaser/Desktop/pyhton codes/Insta-tel-bot/insta/telegram.py", line 2, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'

**Comment by abdualiabduraimov** [comment]
> pip3 install pyTelegramBotAPI

No module named 'telebot'
