### ISSUE TITLE
Stress testing and high load calculation

### ISSUE THREAD

**Issue by baterflyrity** [eternnoir/pyTelegramBotAPI#1348]
Hi! How can I test my bot for hight load?

_pyTelegramBotAPI 4.1.1, python 3.10, windows 10 x64_

My first approach was to replace bot methods but didn't help:
```python
bot.send_message = lambda *args,**kwargs: args
bot.process_new_updates([generate_fake_update() for _ in range(10**7)])
```

My second approach was to use dummy proxy but it failed to:
```python
apihelper.proxy = {'http': 'http://127.0.0.1:51123'}
Process(target=always_http_200_proxy, kwargs={'host':'127.0.0.1', 'port': 51123}, daemon=True).start()
bot.process_new_updates([generate_fake_update() for _ in range(10**7)])
```

All the time i receive 100500+ notifications in my real telegram.

**Please help in testing.** Ty.

**Comment by Badiboy** [comment]
What exactly you want/need? To suppress bot replies to your fake updates?

**Comment by baterflyrity** [comment]
> 
> 
> What exactly you want/need? To suppress bot replies to your fake updates? Or what?

Thanks for reply. I need to measure time it takes to process 1 000 000 updates in one time.

So i try to replace real telegram servers with my functions to avoid ban: fake_data_generator→bot.process_new_updates(...)→fake_data_receiver

All in all now i achieved firest two steps but cant prevent bot to send HTTP rewrests to real servers. Maybe custom proxy/adapter/connection can be used by bot?

**Comment by Badiboy** [comment]
Feature seems usefull. I'll check what can be done.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1350

Check this.

**Comment by baterflyrity** [comment]
> 
> 
> #1350
> 
> Check this.

Seems like exactly what is needed. Thanks. Waiting for release)

**Comment by Badiboy** [comment]
Will release today or tomorrow.
