### ISSUE TITLE
Something went wrong after the upgrade pyTelegramBotAPI-4.1.1  

### ISSUE THREAD

**Issue by congcong0806** [eternnoir/pyTelegramBotAPI#1351]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.1.1
2. What OS are you using?
Windows 10 专业版 21H1
3. What version of python are you using?
Python 3.9.2

![Snipaste_2021-11-04_11-01-58](https://user-images.githubusercontent.com/3024785/140251245-b5ed749f-fed9-4797-a5a3-fa816b50fa15.png)

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/140266102-f91c38b9-b689-4959-80e5-ff223e810f42.png)

Check params you used for infinity_polling.

**Comment by congcong0806** [comment]
> ![image](https://user-images.githubusercontent.com/5613421/140266102-f91c38b9-b689-4959-80e5-ff223e810f42.png)
> 
> Check params you used for infinity_polling.

Thanks
