### ISSUE TITLE
Problem with many bots using load_next_step_handlers

### ISSUE THREAD

**Issue by diegomedflo** [eternnoir/pyTelegramBotAPI#1352]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
v 3.7.5
2. What OS are you using?
Linux enviroment at Pythonanywhere
3. What version of python are you using?
Python 3.7

When I create 3 bots in a same main folder and all bots uses load_next_step_handlers; since the step_handlers are saved in the same route, it shows the error:
`AttributeError: Can't get attribute 'notificame_2' on <module 'main' from '/home/diegomedfloxx/bots_telegram/compras_dat/botdat.py'>`

This function 'notificame_2' is from a different bot that what is showing the error. It mixes step_handlers.

Is it possible to delete the step registered?

**Comment by coder2020official** [comment]
Hi!
I do not recommend you to create 2 bots in same folder.
You can delete folder .handler-saves(if I am not mistaken with name) and all states can be deleted.

**Comment by Badiboy** [comment]
After creating bot and calling **enable_save_next_step_handlers** set
`        bot.next_step_backend.filename`
to unique for every bot.

**Comment by diegomedflo** [comment]
Yeah @coder2020official I was consdering doing that too, but I thougt it wasn't a good practice. Thanks for your answer.
