### ISSUE TITLE
Will there be "cogs" in this library, as in the library for discord bots?

### ISSUE THREAD

**Issue by theroucken** [eternnoir/pyTelegramBotAPI#1354]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.1.1
2. What OS are you using? Windows
3. What version of python are you using? 3.8.9

Hello! I would like to ask if it will be possible in the future in a telebot to separate parts of the bot code into different files (cogs), as it is implemented for bots in discord.py

**Comment by coder2020official** [comment]
Hi!
You can separate handlers in other files.
Use register_XXX_handler, also, there is an example using this function.
You can split up the handlers in different files. Handlers should be just functions, and you should register those functions

Check more here:
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/register_handler.py

**Comment by theroucken** [comment]
Do I need to define a "bot" variable in order to register the function in another file? Because I did just that, and it seems to work.

**Comment by coder2020official** [comment]
you can create a bot variable in config file.
Then, import bot variable and use anywhere you need

**Comment by coder2020official** [comment]
Better to create bot variable in main file, and register all handlers over there.

**Comment by theroucken** [comment]
But I can still define a variable in the config, while importing this variable into all files, and registering handlers in the main one?

**Comment by coder2020official** [comment]
Try

**Comment by theroucken** [comment]
Yes, I can. Thank you! :)

**Comment by coder2020official** [comment]
Is this still valid?

**Comment by Oreofreakshake** [comment]
Here's something I made If you want something closely related to discord cogs
https://github.com/Oreofreakshake/Scintilla-public-bot
