### ISSUE TITLE
banChatMember

### ISSUE THREAD

**Issue by JasonBate0401** [eternnoir/pyTelegramBotAPI#1359]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI       4.1.1

2. What OS are you using?
VERSION="20.04.3 LTS (Focal Fossa)"

3. What version of python are you using?
Python 3.8.10

I want to use banChatMember,however I don't know how to achieve.
Could give me some examples?

**Comment by coder2020official** [comment]
```
bot.ban_chat_member(chat_id=chat_id, user_id=user_id)
```
also there are revoke_messages and until_date parameters.
check more here: 
https://core.telegram.org/bots/api#banchatmember

**Comment by coder2020official** [comment]
Is this still valid?
