### ISSUE TITLE
Delete history method

### ISSUE THREAD

**Issue by lapers** [eternnoir/pyTelegramBotAPI#1361]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.2.0
2. What OS are you using?
Arch Linux 5.15.2
3. What version of python are you using?
3.9.7

Could you please add nice method for clearing all chat messages?
Here link to official docs:
[https://core.telegram.org/method/messages.deleteHistory](https://core.telegram.org/method/messages.deleteHistory)

**Comment by coder2020official** [comment]
Hi!
Bot api does not allow clearing all messages in a chat. The link you gave is for userbots, which is not related to bot api.
You can switch to telethon or pyrogram, and use this method. However, telebot is a bot api wrapper library, while telethon and pyrogram are wrappers for tdlib
