### ISSUE TITLE
How to get label value of selected inline keyboard selection?

### ISSUE THREAD

**Issue by shubhank-saxena** [eternnoir/pyTelegramBotAPI#1362]
Thank you @eternnoir for this amazing library. I just had a quick doubt.

```
def visibility_markup():
    markup = InlineKeyboardMarkup()
    markup.row_width = 1
    markup.add(
        InlineKeyboardButton("Light Fog", callback_data="e1"),
        InlineKeyboardButton("Dense Fog", callback_data="e2"),
        InlineKeyboardButton("Smog/Air Pollution", callback_data="e3"),
        InlineKeyboardButton("Blowing Dust", callback_data="e4"),
        InlineKeyboardButton("Blowing Snow", callback_data="e5")
    )
    return markup
   ```
This is my keyboard layout. I am able to extract callback_data using:
```
@bot.callback_query_handler(func=lambda call: True)
def handle_query(call):
    print(call.data)
 ```
 How can I get the option label from this function (eg - Light Fog)
 
 Thanks in advance!

**Comment by Badiboy** [comment]
You cannot. You can identify clicked button by its "callback_data".

**Comment by shubhank-saxena** [comment]
@Badiboy I have got the callback_data value. But I really need to get the value as well :(

**Comment by Badiboy** [comment]
Inline buton callbacks work as they are designed in the Teegram.
