### ISSUE TITLE
A blueprint technique to plug-in message handlers?

### ISSUE THREAD

**Issue by dexpiper** [eternnoir/pyTelegramBotAPI#1363]
I am trying to refactor code of my Flask/pyTelegramBotAPI application and take out in a separate file all the bot message handlers.

The problem is that the telebot.TeleBot instance should be assigned before the message handlers, and I don't see a way how to import separate handlers file without a mess with declaration. Is there any technique to make a kind of "handlers blueprint" and then to plug it in (same as in Flask maybe)? Could it be resolved using the listener mechanism?

By the way, I've got two ways to start the bot: long-polling and flask+webhooking (in separate files), and it would also be nice not to copy-paste same code for handlers in both of the files.

Thanks in advance.

pyTelegramBotAPI 3.7.9, Ubuntu 21.10, Python 3.9.7

**Comment by coder2020official** [comment]
Hi!
Use register_xxx_handler to register a function as a message handler. see example:
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/register_handler.py

**Comment by coder2020official** [comment]
Also i would suggest using newer version of pyTelegramBotAPI ;)

**Comment by dexpiper** [comment]
Thanks a lot for your answer.
The problem is I cannot use this pattern to define handlers in other file.

**bot.py**
```
import telebot
from handlers import handlers

bot = telebot.TeleBot('some_token)
# here it seems to work well...
for handler in handlers:
    bot.register_message_handler(name, **kwargs)

bot.infinity_polling()

# but...
```

**handlers.py**
```
handlers = []
# some code here
 @some_custom_register_decorator(commands=['start'])
 def answer_start(message):
    # Here is the trouble: we cannot get TeleBot instance from bot.py.
    bot.send_message(
            message.chat.id,
            startmessage.startmsg(),
            parse_mode='HTML'
        )
```
And by the way if we put all the handlers in handlers.py inside a class as a methods, that also does not help. You just cannot pass them the _self_ argument normally: it would look nice and clean in code, but when called by pyTelegramBotAPI, such method would become just a callable with exactly one argument - message, and without class instance _self_.

Example:
**handlers.py** with a class

```
class BotHandlers:

    handlers = []
    # some code here...

    def __init__(self, bot):
        self.bot = bot
    
    # and...
    @some_custom_register_decorator(commands=['start'])
    def answer_start(self, message):
    bot.send_message(
            message.chat.id,
            startmessage.startmsg(),
            parse_mode='HTML'
        )

    # it look nice, but with bot.py running you issue /start command,
    # telebot would throw an exception:
    # TypeError: answer_start() missing 1 required positional argument: 'message'
```

If I got it right, telebot strips the method off its class and its instance.

Thank you in advance for your help and attention!

P.S. I have updated  pyTelegramBotAPI :)

**Comment by Badiboy** [comment]
> Thank you in advance for your help and attention!

https://github.com/eternnoir/pyTelegramBotAPI/issues/1363#issuecomment-968920635

**Comment by Badiboy** [comment]
```
    # and...
    @some_custom_register_decorator(commands=['start'])
    def answer_start(self, message):
```

Do not invent decorators. Just follow the given example.

https://github.com/eternnoir/pyTelegramBotAPI/issues/1363#issuecomment-968920635
