### ISSUE TITLE
`file_unique_id` parameter

### ISSUE THREAD

**Issue by TECH-SAVVY-GUY** [eternnoir/pyTelegramBotAPI#1365]
Hi, just wanted to know how we can use the `file_unique_id` parameter of a media with `pyTelegramBotAPI`.

As far as I know, the `file_id` parameter is unique to each bot and does not work with others.

However, the `file_unique_id` parameter sounds something that is unique to a media and should be same for every bot.

So, does anyone know how we can use this parameter?

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/142688331-34316f46-fb79-48bd-a18d-445f9b91bdeb.png)

**Comment by TECH-SAVVY-GUY** [comment]
So, why is this parameter even associated with these media? Just asking....
