### ISSUE TITLE
`Inline Mode URL`

### ISSUE THREAD

**Issue by TECH-SAVVY-GUY** [eternnoir/pyTelegramBotAPI#1367]
Can we use the `get_file_url()` method to set the url for a media in the Inline Mode?

![image](https://user-images.githubusercontent.com/83786816/142739316-2d822056-7936-4c8f-9d4b-1893ab5f0ff0.png)

Something like this? ☝🏻

**Comment by Badiboy** [comment]
get_file_url is not a function for internet crawling. It's a special function to retrive the downloadable url for telegram file.

**Comment by TECH-SAVVY-GUY** [comment]
@Badiboy How can I use `Inline Mode` with `file_ids` of media already stored on the Telegram servers?

**Comment by coder2020official** [comment]
https://core.telegram.org/bots/api#inlinequeryresultcachedphoto
Use cached classes

**Comment by TECH-SAVVY-GUY** [comment]
@coder2020official Thanks for the reply!

I used this method, however only the first option is being displayed by the bot.

**Comment by TECH-SAVVY-GUY** [comment]
> @coder2020official Thanks for the reply!
> 
> I used this method, however only the first option is being displayed by the bot.
> 
> ![image](https://user-images.githubusercontent.com/83786816/142757722-4e0e30c1-3260-4483-800f-27f34829c317.png)

Well, on further investigation ,it seems like there is a delay in updating the information to the bot. Like I was running the script several times but it displayed all the 4 images after several re-runs.
Again I deleted, one of the query from the `queries` list and it still shows me all 4 images instead of 3.
