### ISSUE TITLE
support: how to keep "standing" the bot?

### ISSUE THREAD

**Issue by aborruso** [eternnoir/pyTelegramBotAPI#137]
Dear all,
thank you for this great product, I was able to create a test bot in no time.

I have a stupid question. I keep alive my bot running via shell `python mybot.py`. I think I must run it as if it were a service. How to do it? What's the best way to do in production and not only for a test?

Best regards

**Comment by analca3** [comment]
I usually use screen for those purposes :). If you want to launch as a
service it depends on your GNU/Linux distribution.

**Comment by aborruso** [comment]
Hi @analca3,
then if the server goes down you have some "screen" task that runs when the server comes back up?

I have Ubuntu 12.04.5 LTS.

Thank you

**Comment by analca3** [comment]
No, I don't. I only have screen because I hate bot process depends on the current shell. With screen you can detach a process from the shell and keep running (like nohup, but they're not the same).

I don't have a system to recover the bot process from a system failure.
