### ISSUE TITLE
`InputPhotoMessageContent`

### ISSUE THREAD

**Issue by TECH-SAVVY-GUY** [eternnoir/pyTelegramBotAPI#1370]
Hi. I would like a new feature to be implemented regarding the `InputMessageContent` of the `Inline Mode`.

It says over [here](https://core.telegram.org/bots/api#inputmessagecontent) that Telegram only supports these 5 types:

![image](https://user-images.githubusercontent.com/83786816/143064543-76379f5c-a11a-409f-b611-da8c9884d682.png)

I was wondering if we can get a new type called the `InputPhotoMessageContent` which would represent the content of the photo to be sent as the result of an `Inline query`.

**Comment by coder2020official** [comment]
Telegram API development does not depend on us - this is a library-wrapper. Unfortunately, we are not devs in telegram ¯\_(ツ)_/¯

**Comment by TECH-SAVVY-GUY** [comment]
So, can you suggest an alternative way to do create a `Inline Query Handler` which displays the names of certain images:

For example:

- Sheet 1
- Sheet 2
- Sheet 3    and so on....

Now, when the user clicks on the one of these options, instead of the text the associated image is sent?

P.S. I tried using the `InlineQueryResultCachedPhoto` for the purpose, but it displays an annoying thumbnail of the image too.

I also tried using the `title` parameter for this method, but it doesn't seem to work :(

**Comment by coder2020official** [comment]
I think you cannot display name for a photo. You can add a caption to a photo, but it is not displayed

**Comment by Badiboy** [comment]
> I was wondering if we can get a new type called the `InputPhotoMessageContent` which would represent the content of the photo to be sent as the result of an `Inline query`.

You cannot use PHOTO as a SEARCH VALUE. You can send them as result, but not make "search by image". That's why there is no InputPhotoMessageContent. Use InputTextMessageContent for query and send photos as result.
