### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by aruznieto** [eternnoir/pyTelegramBotAPI#1372]
¿How can I that bot detect a location that I send? If I send my location bot works fine, but sending a restaurant location it doesn't work

**Comment by coder2020official** [comment]
Create a handler and with filter `content_types=['location']`
In defined function, just get `message.location`
And get values of .latitude and .longitude. Then, you can use external library(such as geopy) to get city, country, and other information

**Comment by aruznieto** [comment]
Yes, I know, the problem is that If I send my location it works

![Captura de pantalla 2021-11-27 100158](https://user-images.githubusercontent.com/40019177/143675107-4e91bb8d-fe75-4056-9f52-3644a58e69f6.png)

But If I send a place location not work

![Captura de pantalla 2021-11-27 100233](https://user-images.githubusercontent.com/40019177/143675123-edcb99ff-b16a-4f30-9058-806dbd03f765.png)

**Comment by Badiboy** [comment]
What means "not work"? May be you will give some details or we should continue playing quizz? Your handler? Handler code? Lgs?

**Comment by aruznieto** [comment]
I mean that @bot.message_handler(content_types=['location']) doesn´t detect it

**Comment by Badiboy** [comment]
Added this to echo_bot from examples.

```
# Handle location
@bot.message_handler(content_types=['location'])
def send_location(message):
    bot.reply_to(message, "Location: {}, {}".format(message.location.longitude, message.location.latitude))

```

Works absolutely fine.

![image](https://user-images.githubusercontent.com/5613421/143675995-63e31161-d9d8-4fff-bfaa-6fb3ab8f6ba5.png)

**Comment by Badiboy** [comment]
How you send "a place location"?

**Comment by aruznieto** [comment]
![photo_2021-11-27_10-38-32](https://user-images.githubusercontent.com/40019177/143676123-70fa2e8c-eff8-4b76-bcea-70aeabc73583.jpg)

In the 4 options that you can see in the imagen

**Comment by Badiboy** [comment]
It's "venue".
https://core.telegram.org/bots/api#venue

**Comment by aruznieto** [comment]
Ups, thanks you and sorry!
