### ISSUE TITLE
How to prevent the link from being deleted, on behalf of a supergroup?

### ISSUE THREAD

**Issue by dmitriy8720** [eternnoir/pyTelegramBotAPI#1381]
Tell me how to prevent the link from being deleted, on behalf of the supergroup.
`@bot.message_handler(func=lambda message: message.entities is not None and message.chat.id)
def delete_links(message):
    for entity in message.entities:
        if entity.type in ["url", "text_link"]:
            bot.delete_message(message.chat.id, message.message_id)
        else:
            return`

**Comment by coder2020official** [comment]
Hi, can you be more clear?

**Comment by dmitriy8720** [comment]
This code removes all links, even from the administrator, and it is necessary that you do not delete links as administrator.

**Comment by coder2020official** [comment]
check the status of a member.
https://core.telegram.org/bots/api#getchatmember

**Comment by coder2020official** [comment]
Check this example for admin-checkup too:
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/custom_filters/admin_filter_example.py

**Comment by dmitriy8720** [comment]
Nothing helped, tell me how to register member?
I did it like this, everything works ideally bot.delete_message (message.from_user.id, message.message_id) but there are errors in the console, (__ init__.py:690 MainThread)
ERROR - TeleBot: "A request to the Telegram API was unsuccessful.
Error code: 400. Description: Bad Request: message to delete not found ", but the squeak is not left, if this is the only working way, then tell me how to remove errors

**Comment by coder2020official** [comment]
Maybe message got already deleted.

**Comment by coder2020official** [comment]
Is this still valid?

**Comment by dmitriy8720** [comment]
Yes

**Comment by Badiboy** [comment]
"message to delete not found" means that message to delete not found. Handle this error and ignore it.
