### ISSUE TITLE
how to subscribe to queue?

### ISSUE THREAD

**Issue by Podidiving** [eternnoir/pyTelegramBotAPI#1382]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.8.2
2. What OS are you using?
MacOS
3. What version of python are you using? 
3.9

Hello everyone! 
I'm currently developing my telegram bot using pyTelegramBotAPI. The question is following. I have a program, which makes some calculations. After calculations are done it notifies rabbitmq. I want my bot to consume this queue infinitely and notify users, when job is done. Of course, this procedure shouldn't block my bot from interacting with users (so, consuming should be in other thread)

What is the best practice to do so? P.s. mb rabbitmq is not the best way of interacting with my bot and you can offer better solutions (for ex. interacting through redis)?

Thanks in advance!

**Comment by coder2020official** [comment]
Hi!
I would recommend switching to asynctelebot and use it. Create tasks and wait for their finish, then notify your library.
Read more here:
https://github.com/eternnoir/pyTelegramBotAPI#asynchronous-telebot

With synchronous version, I am not sure, however, threads block each other. So, I recommend to switch to asynchronous version.

Asynchronous version is not stable and supported only in version 4.2.1, so you should update your package.

**Comment by Podidiving** [comment]
@coder2020official, Thank you for reply!

Can you show minimal example, how to do it? In examples there is only events handlers and I want to do some job without any event

**Comment by coder2020official** [comment]
Read more here:
https://docs.python.org/3.8/library/asyncio-task.html

**Comment by coder2020official** [comment]
In this website, take a look at asyncio.create_task function. By this function, you can create a task by calling a function.

**Comment by Podidiving** [comment]
okay, thanks!

**Comment by Podidiving** [comment]
Sorry, but I don't quite understand: how to use `bot.polling` and `loop.run_forever` functions together. Can you explain?

**Comment by coder2020official** [comment]
Use create_task in your handler or whatever place you need. It won't affect on your code - it will run as a different task
