### ISSUE TITLE
`ERROR:root:Timeout context manager should be used inside a task`

### ISSUE THREAD

**Issue by ELWAER-M** [eternnoir/pyTelegramBotAPI#1388]
1. What version of pyTelegramBotAPI are you using?
4.2.2
2. What OS are you using?
android 11
3. What version of python are you using?
3.10.1

i'm getting this error when i try to make a rest request with other library
`ERROR:root:Timeout context manager should be used inside a task`

the part of my code the reasonable of this:
```python
@tbot.message_handler(func=lambda message: True)
async def telegram_message(message):
    await dbot.rest.create_message(902550780983275543, content=message.text)
```

what it means?, and what i have to do

**Comment by coder2020official** [comment]
Looks like the error is occuring with aiohttp. What exactly line is it?

**Comment by ELWAER-M** [comment]
i'm just getting this, it doesn't gives me a specific line

![Screenshot_20211212-080720_Termux](https://user-images.githubusercontent.com/71197008/145702309-554d0e31-14f6-43c3-910e-b1388b16d7b7.jpg)

**Comment by ELWAER-M** [comment]
i'm running it in a thread btw:

```python
import threading
from telebot.async_telebot import AsyncTeleBot
import hikari

tbot = AsyncTeleBot('')
dbot = hikari.GatewayBot(token="", banner=None, logs=None)

@tbot.message_handler(func=lambda message: True)
async def telegram_message(message):
    await dbot.rest.create_message(902550780983275543, content=message.text)

@dbot.listen()
async def ping(event: hikari.GuildMessageCreateEvent) -> None:
    if event.is_bot or not event.content:
        return
    await tbot.send_message("-1001779202357", text=str(event.message.content))

def tel():
    tbot.polling()

def dis():
    dbot.run(enable_signal_handlers=False)

t1 = threading.Thread(target=tel)
t1.start()

t2 = threading.Thread(target=dis)
t2.start()

while True:
    pass
```

**Comment by coder2020official** [comment]
Oh, do not run polling in thread!

**Comment by ELWAER-M** [comment]
so there is no solution to run it in a thread?

**Comment by coder2020official** [comment]
Instead, run in async task

**Comment by ELWAER-M** [comment]
._.

**Comment by coder2020official** [comment]
If you need to run polling in thread - switch to TeleBot, synchronous code can run in thread

**Comment by ELWAER-M** [comment]
i dont carr anymore .-.
