### ISSUE TITLE
support: how to solve "another webhook is active" problem?

### ISSUE THREAD

**Issue by aborruso** [eternnoir/pyTelegramBotAPI#139]
Hi,
I have written a simple hello world bot, and it works. Now I want to use it with another token but I have this error:

    Conflict: another webhook is active

Which pyTelegramBotAPI code do I must add in the below "hello world" code to solve this conflict and set a new webhook?

Thank you

```python
import telebot

TOKEN = "166104195:AAHK5KDyGaaaaaaaaaaaaaaaa"
bot = telebot.TeleBot(TOKEN)

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "Howdy, how are you doing?")


bot.polling()
```

**Comment by pevdh** [comment]
You probably once called `set_webhook` by accident. This will configure a [web hook](https://core.telegram.org/bots/api#setwebhook) for your bot. To delete the webhook, you can either call `bot.set_webhook()` (no arguments means that the webhook will be removed), or visit this url: `https://api.telegram.org/bot<YOUR_BOT_TOKEN>/setWebhook?url=`

Leaving the "url" argument empty will remove the webhook as well. `bot.set_webhook()` simply calls this URL for you :)

**Comment by aborruso** [comment]
@pevdh you are very kind. Thank you

**Comment by alimoval** [comment]
Just clear Webhook setting with
`curl -F "url=" https://api.telegram.org/bot<YOUR_TOKEN>/setWebhook`

**Comment by CalonDirektur** [comment]
> Just clear Webhook setting with
> `curl -F "url=" https://api.telegram.org/bot<YOUR_TOKEN>/setWebhook`

thanks for this tip..

**Comment by smartup10** [comment]
bot.deleteWebhook()

**Comment by antoniorb** [comment]
Dear Sir,

I've done a bot for telegram and it worked but some days ago it appears a problem.

"can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first"

I use the deleteWebhook but it doesn't work (with the python-telegram-bot). 
I use the Python 3.6.12 version

data = {"url": ""}
    bot = telegram.Bot('1126965009:AAFvWCs-Timzw3SDd4LcEIGXmY7cVQE_jOQ')

    if (normalize(update.message.text).upper() == 'HOLA'):
        #bot = telegram.Bot('1126965009:AAFvWCs-Timzw3SDd4LcEIGXmY7cVQE_jOQ')
        chat_id = update.message.chat_id
        bot.sendMessage(chat_id, 'HOLA')
      
        
        #pload = {'chat_id':chat_id,'message_id':'123'}
        #r = requests.get('https://api.telegram.org/bot1126965009:AAFvWCs-Timzw3SDd4LcEIGXmY7cVQE_jOQ/deleteWebhook')
        #r = requests.post('https://api.telegram.org/bot1126965009:AAFvWCs-Timzw3SDd4LcEIGXmY7cVQE_jOQ/deleteWebhook',data = pload)
        r = requests.post('https://api.telegram.org/bot1126965009:AAFvWCs-Timzw3SDd4LcEIGXmY7cVQE_jOQ/setWebhook',data = data)
        respuesta = bot.deleteWebhook()
        bot.sendMessage(chat_id, respuesta)
        respuesta = bot.deleteWebhook()
Could you tell me if there is a problem with that? How I can fix it?

Thank you

**Comment by doctorart666** [comment]
bot.remove_webhook()
    time.sleep(1)
    bot.set_webhook (url=WEB_HOOK_URL)
