### ISSUE TITLE
switch_inline_query_current_chat Not Working

### ISSUE THREAD

**Issue by gabking** [eternnoir/pyTelegramBotAPI#1391]
1. What version of pyTelegramBotAPI are you using? The newest

2. What OS are you using? Linux, Ubuntu

3. What version of python are you using? 3.9

I'm trying:
        markup = InlineKeyboardMarkup()
        markup.row_width = 2
        markup.add(
            InlineKeyboardButton("Test", callback_data="test", switch_inline_query_current_chat="Some thing")
        )

but it's not working, idk what is wrong

**Comment by gabking** [comment]
Solution:

> 1. What version of pyTelegramBotAPI are you using? The newest
> 2. What OS are you using? Linux, Ubuntu
> 3. What version of python are you using? 3.9
> 
> I'm trying: markup = InlineKeyboardMarkup() markup.row_width = 2 markup.add( InlineKeyboardButton("Test", callback_data="test", switch_inline_query_current_chat="Some thing") )
> 
> but it's not working, idk what is wrong

Solution: to use switch_inline_query_current_chat, you need to not include the callback_data param

**Comment by coder2020official** [comment]
Are you sure you are passing this markup to send message function?
