### ISSUE TITLE
How can I handle two bots in one class view?

### ISSUE THREAD

**Issue by AlexBreus** [eternnoir/pyTelegramBotAPI#1393]
ps: I have one dynamic URL for several bots: re_path('^bots/(?P<bot_id>\d +)/$', get_bot, name='bot'),

1. What version of pyTelegramBotAPI are you using?
- 4.2.2

2. What OS are you using?
- Macos

3. What version of python are you using?
- 3.10

**Comment by coder2020official** [comment]
I am not sure with django.
I've used fastapi, and handled post requests. And, I recommend to put bot token instead of bot id. But still, you can store bot ids somewhere(for example, in dict: {bot_id: token}), and then get token.
You need token for making requests.

**Comment by coder2020official** [comment]
Is this still valid?
