### ISSUE TITLE
asyncio _process_polling fails with blank error

### ISSUE THREAD

**Issue by Podidiving** [eternnoir/pyTelegramBotAPI#1395]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.2.1

2. What OS are you using? ubuntu

3. What version of python are you using? 3.9.9

Hello!
When polling, bot falls  into [this](https://github.com/eternnoir/pyTelegramBotAPI/blob/943396767c3f40c3dcee1679e0a37d5aa4e5369e/telebot/async_telebot.py#L328) exception, however error is blank, so `logger.error(str(e))` outputs `""`. What is the reason of this exception? Of course, I can just pass `non_stop` flag, and it will be ok, but I'm just curious

**Comment by coder2020official** [comment]
Hi, can you provide more information?

**Comment by coder2020official** [comment]
If you put non_stop=False, you will have an error raised

**Comment by Podidiving** [comment]
Unfortunately, I cannot share code, It's too big. I'm running bot in Docker, with `docker-compose` and sometimes see next errors:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/26285240/147204144-c13253d4-2db9-4fd1-9f00-ea9b40d49258.png">
if `non_stop=True` It just sleeps a little and starts polling again. The frequency of these errors depends on `interval` parameter.

**Comment by Podidiving** [comment]
Actually, I've looked into it and got, that it is `asyncio.exceptions.TimeoutError`

**Comment by Podidiving** [comment]
It's a little confusing because of blank error. Maybe it's worth adding extra `except asyncio.exceptions.TimeoutError`?

**Comment by coder2020official** [comment]
Hi. I think this is a bug. TimeoutError occurs when internet is unstable, aiohttp should throw it.
I will add retry function
Thanks for report

**Comment by coder2020official** [comment]
Fixed. Now RequestTimeout is raised.
Bot will continue working if non stop is set

**Comment by coder2020official** [comment]
Also added retry function

**Comment by Podidiving** [comment]
Cool, thx
