### ISSUE TITLE
send_document not sending?

### ISSUE THREAD

**Issue by GabrielMendesdc** [eternnoir/pyTelegramBotAPI#1396]
pyTelegramBotAPI 4.1.1
win10 pro 21h1
python 3.9.7

```
import telebot
import requests

chaveapi="2053709180:AAFLYVQ8I-7yijRLULw9PHObRo09bwPwxyk"

bot = telebot.TeleBot(chaveapi)

@bot.message_handler(commands=["dalbem"])
def notas(mensagem):
    mensagemID = mensagem.chat.id
    pic = open('C:/Users/pdv/Desktop/dalbem.pdf', 'rb')
    print('pic')
    bot.send_document(mensagemID,document = pic)
#bot.send_document(mensagemID, {},document = pic)

```

the print shows up but i get no message / pdf in telegram, helpme pls

**Comment by Badiboy** [comment]
99% that the file is not accessible by python.

Replace this:
`print('pic')`
with normal print and check what it will print.

**Comment by GabrielMendesdc** [comment]
Thanks a lot dude, i will test it tomorrow on job and i talk here if solved

**Comment by GabrielMendesdc** [comment]
<_io.BufferedReader name='C:/Users/pdv/Desktop/dalbem.pdf'>
this is what print printed, my pdf is ok?
Happy xmas eve.

**Comment by coder2020official** [comment]
It is not sending file? If there is no error, llease do the following;
-Turn on debugging
- Debug and show the output.

**Comment by Badiboy** [comment]
> bot.send_document(mensagemID,document = pic)

![image](https://user-images.githubusercontent.com/5613421/147384920-df41ec7b-295a-482d-8b11-b673b6dd5175.png)

"data", not "document"

**Comment by Badiboy** [comment]
BTW, it's mustyping in library method:

![image](https://user-images.githubusercontent.com/5613421/147384947-095fb167-045b-4c88-932c-8f625643882f.png)

I'll fix it.

**Comment by coder2020official** [comment]
Then just do the following:
```
bot.send_document(mensagemID, pic)
```

**Comment by GabrielMendesdc** [comment]
i try it, using the pdf's path in my computer and i try using the https link from internet, both return the same message: 2021-12-27 07:24:44,961 (__init__.py:667 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: failed to get HTTP URL content"

my solution was convert all pdf's pages into png, and the with a loop i could send the pics.

**Comment by Badiboy** [comment]
@GabrielMendesdc , you should use this:

> bot.send_document(mensagemID, pic)

**Comment by GabrielMendesdc** [comment]
i try it, but no return
