### ISSUE TITLE
Example request: Add FastApi webhook example

### ISSUE THREAD

**Issue by Sht97** [eternnoir/pyTelegramBotAPI#1398]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.2.2
2. What OS are you using?
Pop OS 21.10
3. What version of python are you using?
3.7 and 3.8

Hello everyone, I would like to know if you consider it acceptable to add a webhook example using FastApi https://fastapi.tiangolo.com/.
If so, I would be willing to do it and add the PR.

**Comment by coder2020official** [comment]
Hi. Yes, i would also like to add the example.
If you have time you can add, or wait for some time

**Comment by coder2020official** [comment]
Can this be closed?

**Comment by dasshit** [comment]
Please add disabling the swagger in the example, as a result, the bot token will be visible in it.

**Comment by coder2020official** [comment]
That's up to you.
