### ISSUE TITLE
getUpdates - update_id

### ISSUE THREAD

**Issue by GabrielRF** [eternnoir/pyTelegramBotAPI#14]
I've noticed that my bot is freezing.
After some investigation, it seems that the offset is not increasing correctly.
If I access via browser ```https://api.telegram.org/botTOKEN/getUpdates?offset=update_id+1``` the bot unfreezes and won't stop again until it reaches 100 updates.
It is also happening on commit ```924099d```.

**Comment by GabrielRF** [comment]
Maybe checking if ```https://api.telegram.org/botTOKEN/getUpdates?offset=last_update``` equals the last one read?

**Comment by eternnoir** [comment]
I think, maybe we should reset last_update_id after getUpdates with offset. 

In your case, freezing means no new messages notify or telebot doesn't visit  getUpdate api url ?

**Comment by pevdh** [comment]
Can you please provide some of your code?

**Comment by GabrielRF** [comment]
@eternnoir This is what I get on the log:
```2015-07-01 12:40:46,563 Setting read timeout to None```
```2015-07-01 12:40:46,644 "GET /botTOKEN/getUpdates HTTP/1.1" 200 298```
```2015-07-01 12:40:49,652 Starting new HTTPS connection (1): api.telegram.org```
```2015-07-01 12:40:49,932 Setting read timeout to None```
```2015-07-01 12:40:50,010 "GET /botTOKEN/getUpdates HTTP/1.1" 200 298```

@pevdh The code:
``` 
import telebot
import time
import datetime
import urllib
import logging
import logging.handlers

TOKEN = '<TOKEN>'

LOG_INFO_FILE = 'lmgtfy/lmgtfy.log'
LOG_DEBUG_FILE = '/var/log/lmgtfy.log'

logging.basicConfig(filename=LOG_DEBUG_FILE,level=logging.DEBUG,format='%(asctime)s %(message)s')
logging.debug('Start')

logger_info = logging.getLogger('InfoLogger')
logger_info.setLevel(logging.INFO)
handler_info = logging.handlers.RotatingFileHandler(LOG_INFO_FILE,maxBytes=10240,backupCount=5,)
logger_info.addHandler(handler_info)

print ('Start')

today = datetime.date.today()

print ('listening')

def listener(*messages):
    for m in messages:
        chatid = m.chat.id
        text = m.text
        firstname = m.fromUser.first_name
        username = m.fromUser.username
        logger_info.info(str(datetime.datetime.now())+' @'+username+' '+text)

        if "/start" in text:
            tb.send_message(chatid, "Welcome!\nText me what you want to search")
        elif "/lmgtfy" in text:
            args=text.split(' ',1)[1]
            tb.send_message(chatid, "http://lmgtfy.com/?q="+urllib.quote_plus(args))
        elif "/info" in text:
            tb.send_message(chatid,"Bot by @GabrielRF\nDo not hesitate do reach me")
        else:
            args=text
            tb.send_message(chatid, "http://lmgtfy.com/?q="+urllib.quote_plus(args))

tb = telebot.TeleBot(TOKEN)
tb.get_update()  # cache exist message
tb.set_update_listener(listener) #register listener
tb.polling(3)
while True:
    time.sleep(20)
```
The excess of log is because I was investigating what was happening.

**Comment by pevdh** [comment]
Hmm, I just ran your code and nothing seems wrong. What does the API give you when you open 'https://api.telegram.org/bot<TOKEN>/getUpdates' in your browser? It should return no new Updates, because the bot handled all of them.

**Comment by GabrielRF** [comment]
The problem starts after 100 messages, when it reaches the limit.
If you run the code and send only a few things everything will be ok.
When I open the url the updates are still there. I believe there should be only the "ok" message.

**Comment by pevdh** [comment]
I just noticed that in your log, it says 'GET /botTOKEN/getUpdates' where that should be 'GET /bot82565878:AAEBPQjeCPZgkCVrEVO7ewx4X7G7FV8JVRw/getUpdates?offset=12345'
Might be a stupid question, but did you do a git pull?
You can test if you have the right version by printing TeleBot#last_update_id. If that gives you an error, you have an outdated version.

**Comment by GabrielRF** [comment]
@pevdh Yes. I'm on the last version.
```
# git pull
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 10 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
From https://github.com/eternnoir/pyTelegramBotAPI
   77580e6..d9bd775  develop    -> origin/develop
Already up-to-date.
```
```print (tb.last_update_id)``` returns the value correctly.

**Comment by GabrielRF** [comment]
Is is possible that everything is now ok because I added ```tb.last_update_id)```?

**Comment by pevdh** [comment]
You mean the print statement? That shouldn't do anything to the object, of course. What version of python are you using by the way? 3?

**Comment by GabrielRF** [comment]
Python 2.7.6.
Everything seems ok now. I didn't get exactly how, but it seems solved.

**Comment by pevdh** [comment]
Though I am still curious as to what went wrong, I am happy the problem solved itself.

**Comment by GabrielRF** [comment]
Me too. It was visible that the updates were piling on 'https://api.telegram.org/botTOKEN/getUpdates' until they reach 100 of them and now they are not. All I get is ```{"ok":true,"result":[]}```

**Comment by eternnoir** [comment]
I am not sure where is the problem,too.
Is it possible the new message update_id less than offset return by getUpdate?

update_id would be reset by official api?

**Comment by GabrielRF** [comment]
I'll run some tests.
