### ISSUE TITLE
bot.process_new_updates(bot.get_updates()) construction question

### ISSUE THREAD

**Issue by bestnaf** [eternnoir/pyTelegramBotAPI#1401]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Currently using last one from pip

2. What OS are you using?
Ubuntu Linux

3. What version of python are you using?
3.7

I was not using telebot for quite some time and now using last version - this construction seem to not work anymore:
self.bot.process_new_updates(self.bot.get_updates(offset=(self.bot.last_update_id + 1), long_polling_timeout=0, timeout=None))
self.bot.get_updates itself does collect the data but process_new_updates are does nothing now.

Could you advice if it was depricated?

**Comment by bestnaf** [comment]
Update:
It is working, the problem now is I am using channel and had to replace the message_handler to channel_post_handler.
But now I cant make @self.bot.callback_query_handler(func=lambda call: True) to work in channel - please advice how it could be done?

**Comment by coder2020official** [comment]
Hi. Why are you using handler in class?(I mean it by seeing self argument)

**Comment by bestnaf** [comment]
I am using a separate module to use tg bot in different parts of the code. Let me post full module code here
`import logging
import telebot
from config import TG_TOKEN, TG_CHAT_ID, TG_INSTANCE_NAME
logger = logging.getLogger('minibot')

class TG_bot:
    instance = None
    def __new__(cls):
        if cls.instance is None:
            cls.instance = super().__new__(cls)
        return cls.instance

    def __init__(self):
        self.bot = telebot.TeleBot(TG_TOKEN)
        self.stats = False
        self.forceClose = False
        self.saveMode = False
        self.stopTrade = False


    def generate_bot(self):
        keyboard = telebot.types.InlineKeyboardMarkup()
        key_1 = telebot.types.InlineKeyboardButton(text='Stop/Start Trading', callback_data='stop_trade')
        keyboard.add(key_1)
        key_2 = telebot.types.InlineKeyboardButton(text='Enable/Disable Save Mode', callback_data='save_mode')
        keyboard.add(key_2)
        key_3 = telebot.types.InlineKeyboardButton(text='Show Current Stats', callback_data='stats')
        keyboard.add(key_3)
        self.bot.send_message(TG_CHAT_ID, 'Welcome', reply_markup=keyboard)

        @self.bot.callback_query_handler(func=lambda call: True)
        def callback_worker(call):
            print(call.data)
            if call.data == "stats":
                self.stats = True
            if call.data == "stop_trade":
                if not self.stopTrade:
                    self.stopTrade = True
                    self.bot.send_message(call.message.chat.id, f"Stop Trading Activated")
                if self.stopTrade:
                    self.stopTrade = False
                    self.bot.send_message(call.message.chat.id, f"Stop Trading Deactivated")
            if call.data == "save_mode":
                if not self.stopTrade:
                    self.saveMode = True
                    self.bot.send_message(call.message.chat.id, f"Save Mode Activated")
                if self.stopTrade:
                    self.saveMode = False
                    self.bot.send_message(call.message.chat.id, f"Save Mode Deactivated")
            
        @self.bot.channel_post_handler(commands=['start'])
        def start_message(message):
            self.bot.send_message(message.chat.id, 'Welcome toTG Controls', reply_markup=keyboard)

    def poll_data(self):
        logger.info("Polling TG data")
        try:
            self.bot.process_new_updates(self.bot.get_updates(offset=(self.bot.last_update_id + 1), long_polling_timeout=0, timeout=None))
        except Exception as ex:
            print(ex)
            logger.error("TG pool data error {}".format(ex))


    def sendTelegramMessage(self, message, instance_name=TG_INSTANCE_NAME):
        try:
            message_instanced = "Minibot *{}*\n{}".format(instance_name, message)
            self.bot.send_message(TG_CHAT_ID, message_instanced, parse_mode='Markdown')
        except Exception as ex:
            logger.error("TG Sending error {}".format(ex))`

**Comment by Badiboy** [comment]
> But now I cant make @self.bot.callback_query_handler(func=lambda call: True) to work in channel

Callback handler is chat type independent and work for private/group/channel.

```
API_TOKEN = 'xxx:xxx'
channel_id = -100xxxx

import telebot
from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton

bot = telebot.TeleBot(API_TOKEN)

# Handle '/start' and '/help'
@bot.message_handler(commands=['help', 'start'])
def send_welcome(message):
    bot.reply_to(message, """\
Hi there, I am EchoBot.
I am here to echo your kind words back to you. Just say anything nice and I'll say the exact same thing to you!\
""")

@bot.message_handler(commands=['test'])
def send_test(message):
    keyboard = telebot.types.InlineKeyboardMarkup()
    key_1 = telebot.types.InlineKeyboardButton(text='Stop/Start Trading', callback_data='stop_trade')
    keyboard.add(key_1)
    key_2 = telebot.types.InlineKeyboardButton(text='Enable/Disable Save Mode', callback_data='save_mode')
    keyboard.add(key_2)
    key_3 = telebot.types.InlineKeyboardButton(text='Show Current Stats', callback_data='stats')
    keyboard.add(key_3)
    bot.send_message(channel_id, 'Welcome', reply_markup=keyboard)

@bot.callback_query_handler(func=lambda call: True)
def process_callback_message_delete_confirm(call):
    print(call.data)

bot.infinity_polling()
```

This code works fine:

![image](https://user-images.githubusercontent.com/5613421/147791754-1a371882-84ae-41be-89b1-db00a158bf3b.png)

**Comment by bestnaf** [comment]
Hi @Badiboy,

I managed to make it work with infinite loop inside a separate thread, but initial construction I mention in a first post (I was running in cycle) now working.
Not sure it worth spending time to check this.
Thank you for your time and happy new year :)
