### ISSUE TITLE
dealing with loss of internet connection

### ISSUE THREAD

**Issue by HenRuw** [eternnoir/pyTelegramBotAPI#1403]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.2.0
2. What OS are you using?
Raspbian

3. What version of python are you using?
Python 3

Reproducing:
Happens after I start my script, within days to a few hours. I have a very unstable internet connection, but it sometimes does recover without problems after an outage.

Here are the logs, it crashed after the last log, but I don't know how much later, could be instantly to a few hours later.
[message.txt](https://github.com/eternnoir/pyTelegramBotAPI/files/7801805/message.txt)

This is the code for logging:

logging.basicConfig(filename='/home/pi/logging/hk.log', level=logging.ERROR, 
                    format='%(asctime)s %(levelname)s %(funcName)s %(lineno)d %(name)s %(message)s')
logger=logging.getLogger(__name__)

I dont know how to catch those exceptions and if they are what causes my program to crash.

Any help would be appreciated, thanks in advance!

**Comment by coder2020official** [comment]
Hello. Try this:

```
telebot.apihelper.RETRY_ON_ERROR = True
bot.polling()
```
This will make script run even if exception is thrown. So bot will continue running and trying to reach internet even if internet is down.

**Comment by HenRuw** [comment]
I use bot.infinity_polling() at the moment, should I change that or should I keep it?

**Comment by coder2020official** [comment]
Keep it

**Comment by Badiboy** [comment]
> Here are the logs, it crashed after the last log, but I don't know how much later, could be instantly to a few hours later.
> message.txt

> 2022-01-03 00:20:17,639 ERROR infinity_polling 617 TeleBot Infinity polling exception: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=25)
> 2022-01-03 00:20:17,661 ERROR infinity_polling 619 TeleBot Exception traceback:
> Traceback (most recent call last):

This error cannot lead to stop working: your bot should successfully proceed future updates. Given logs says nothing that something crashes and/or reasons of it.

Try to wrap "infinity_polling" with try/except and save traceback if some exceptions are handled there. There we should get more information for analysis.

**Comment by Badiboy** [comment]
PS: there is your bot token in logs. You should better hide it or renew token...

**Comment by coder2020official** [comment]
Can this be closed?
