### ISSUE TITLE
module 'telebot' has no attribute 'AsyncTeleBot'

### ISSUE THREAD

**Issue by PedroLuz89** [eternnoir/pyTelegramBotAPI#1406]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.3.0
2. What OS are you using?
Windows 10 PRO
3. What version of python are you using?
Python 3.9.9

Tried installing both from pip and from git, but the AsyncTeleBot object cannot be found anywhere ;(

![image](https://user-images.githubusercontent.com/1821054/148707756-a00b956a-c52e-4e78-bfec-9383ca9c8ae6.png)

**Comment by PedroLuz89** [comment]
found it on examples, good to go :)

**Comment by DuckyBlender** [comment]
How did you fix this? The examples doesn't work for me...
