### ISSUE TITLE
send_data() got an unexpected keyword argument 'protect_content'

### ISSUE THREAD

**Issue by o0HalfLife0o** [eternnoir/pyTelegramBotAPI#1407]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI-4.3.0
2. What OS are you using?
Ubuntu
  20.04.3
  LTS
3. What version of python are you using?
Python 3.8.10

[github actions](https://github.com/gedoor/legado/runs/4753827688?check_suite_focus=true) update to the latest pyTelegramBotAPI-4.3.0, and then run [tg_bot.py](https://github.com/gedoor/legado/blob/master/.github/scripts/tg_bot.py) it tips
` send_data() got an unexpected keyword argument 'protect_content'`
is it a bug?

**Comment by coder2020official** [comment]
Looks like a bug.

**Comment by Badiboy** [comment]
Version 4.3.1 released. You can update now.

**Comment by o0HalfLife0o** [comment]
@Badiboy update and success, thanks
