### ISSUE TITLE
Middleware Handler not working :(

### ISSUE THREAD

**Issue by TECH-SAVVY-GUY** [eternnoir/pyTelegramBotAPI#1413]
I tried the example provided [here](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/middleware/i18n.py).

However, it throws the following error 👇🏻

```python
self.typed_middleware_handlers[update_type].append(handler)
AttributeError: 'TeleBot' object has no attribute 'typed_middleware_handlers'. Did you mean: 'add_middleware_handler'?
```

Can anyone help?

**Comment by Badiboy** [comment]
> self.typed_middleware_handlers[update_type].append(handler)

Where you got this line? I do not see it in mentioned example.

**Comment by TECH-SAVVY-GUY** [comment]
> You should set **apihelper.ENABLE_MIDDLEWARE** to **True**

Even on doing that I am getting this error...

**Comment by Badiboy** [comment]
I took example "as is".

![image](https://user-images.githubusercontent.com/5613421/149538555-810350bf-ec29-4f4b-a38a-d3a12b36a877.png)

Works fine for me.

**Comment by Badiboy** [comment]
Try to enable middleware BEFORE creating Telebot instance.

**Comment by TECH-SAVVY-GUY** [comment]
> 

Ah this works! Thanks✌🏻

I think you should probably include this in the documentation...

**Comment by TECH-SAVVY-GUY** [comment]
> Try to enable middleware BEFORE creating Telebot instance.

Ah this works! Thanks✌🏻

I think you should probably include this in the documentation...
