### ISSUE TITLE
set_my_commands problem

### ISSUE THREAD

**Issue by joaodobread** [eternnoir/pyTelegramBotAPI#1414]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.3.1

2. What OS are you using?
Manjaro Linux

3. What version of python are you using?
Python 3.10.1

When using `set_my_commands` True is returned but not is defined. 
Possible fix: 
`apihelper.py` at line 1164 method: `set_my_commands`
just change the `_convert_list_json_serializable` func to a call of `json.dumps`

**Comment by Badiboy** [comment]
> When using set_my_commands True is returned but not is defined.

What can it mean?

**Comment by Badiboy** [comment]
2. Please, provide example: what you tried to do, what you get, what is wrong?

**Comment by joaodobread** [comment]
1.
I can't set my commands for the bot, when I type "/" on the chat the command for bot doesn't appear on the Telegram. [See](https://prnt.sc/26ehkrz)

2.
```
r = {'command': '123123', 'description': '123123'}
isinstance(r, types.JsonSerializable) {'command': '123123', 'description': '123123'} False
```

and `_convert_list_json_serializable` returns `[]`


``` python
response = bot.set_my_commands(
    commands=[{"command": "123123", "description": "123123"}])
print(response) # True
```
This is my code, for now, the response is True for every command I sent
`_convert_list_json_serializable(commands)` on line `1166` in the file `apihelper.py` return an empty array.


Very simple example:
``` python
import telebot
from telebot import types
from random import choice


BOT_API_KEY = 'apy:key'

bot = telebot.TeleBot(BOT_API_KEY)

response = bot.set_my_commands(
    commands=[{"command": "123123", "description": "123123"}])
print(response) # True, but the command sent for telegram API is []
```

**Comment by joaodobread** [comment]
Maybe if I use the code like in tests `tb.set_my_commands([telebot.types.BotCommand(command, description)], scope, lang)` this gonna work?

**Comment by joaodobread** [comment]
Oh, that's right, `response = bot.set_my_commands(
    commands=[types.BotCommand("asdfas",  "asdfasdf")])` works well. sorry

**Comment by joaodobread** [comment]
Can you add one example of this in the documentation?
Is really helpful

**Comment by Badiboy** [comment]
We definitely need example for that.

**Comment by artyl** [comment]
Add [#1418](https://github.com/eternnoir/pyTelegramBotAPI/pull/1418) with examples for this
