### ISSUE TITLE
Schedule timer events in pooling

### ISSUE THREAD

**Issue by artyl** [eternnoir/pyTelegramBotAPI#1415]
I liked the approach implemented in pyTelegramBotAPI much more than the python-telegram-bot.
But, as I understood, it is impossible to implement schedule events in pyTelegramBotAPI. 
In my case, it is necessary that the trigger of the event is not an incoming message, but a timer event 
See the example for the python telegram bot [timerbot.py ](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/timerbot.py )

**Comment by Badiboy** [comment]
Use external libraries. 
Like schedule. Or APScheduler, as in python-telegram-bot.
Run them in separate thread and do whatever you need.

**Comment by artyl** [comment]
Понятно, что так можно, но не хотелось бы нести мультитрединг только ради этого. Хотелось бы иметь возможность просто попасть в основной цикл poller
