### ISSUE TITLE
Cant use callback_data and url same time

### ISSUE THREAD

**Issue by Eikosa** [eternnoir/pyTelegramBotAPI#1426]
Please answer these questions before submitting your issue. Thanks!
![image](https://user-images.githubusercontent.com/20538090/151677485-27c31879-6069-4bde-9378-05a62ade07d5.png)
If I code a keyboard button as seen, when I click on that button, it goes to my bot's page but does not send the callback_data.

1. What version of pyTelegramBotAPI are you using?
3.7.9
2. What OS are you using?
Windows 10
3. What version of python are you using?
3.9.5

**Comment by Badiboy** [comment]
You cannot. Telegram Bot API limitation.
