### ISSUE TITLE
This may sound stupid but how do I make the bot to respond to messages that are not commands? I dont want to use the '/' whenever I want the bot to do something

### ISSUE THREAD

**Issue by fabianlanza** [eternnoir/pyTelegramBotAPI#1428]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
version 4.3.1

2. What OS are you using?
window 10

3. What version of python are you using?
Python 3.8.2

**Comment by Badiboy** [comment]
```
@bot.message_handler(func=lambda mess: mess.text == "Text to react", content_types=['text'])
def process_some_text(message):
    bot.reply_to(message, "Got text: " + message.text)
```

Or check custom filters:
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/custom_filters/text_filter_example.py

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/151709385-f8bdc2b8-fb1c-4ebb-b32c-d8bac71dd3fc.png)

It's funny. You are in so deep future...

**Comment by coder2020official** [comment]
Wow, a person came from the future xD

**Comment by fabianlanza** [comment]
> ```
> @bot.message_handler(func=lambda mess: mess.text == "Text to react", content_types=['text'])
> def process_some_text(message):
>     bot.reply_to(message, "Got text: " + message.text)
> ```
> 
> Or check custom filters: https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/custom_filters/text_filter_example.py

alright thx

**Comment by fabianlanza** [comment]
> ![image](https://user-images.githubusercontent.com/5613421/151709385-f8bdc2b8-fb1c-4ebb-b32c-d8bac71dd3fc.png)
> 
> It's funny. You are in so deep future...

Yeah my mistake

**Comment by coder2020official** [comment]
Still valid?
