### ISSUE TITLE
How to make indent message_handler() 

### ISSUE THREAD

**Issue by Joepython3** [eternnoir/pyTelegramBotAPI#1429]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 4.3.1

2. What OS are you using?
Windows 10

3. What version of python are you using?
Python 3.9.10

How to make indent message_handler() ?
To receive a message from the user the executes only under a certain message_handler
for example :

@bot.message_handler(regexp="🎛 Buttons Editor")
    def msg(message):
        for key , value in Buttons.items() :
            if value == message.text :
                Change1 = key
                Name1 = value 
                break
        bot.send_message(message.chat.id , "Please Select The Place You want to Put in..." , reply_markup = Markup )
        @bot.message_handler(content_types=["text"])
        def msg(message):
            for key , value in Buttons.items() :
                if value == message.text :
                    Change1 = key
                    Name1 = value               
                    
 I tried to make it under a function but it does not execute and tried it indented and the same issue

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/issues/1428#issuecomment-1025190596

**Comment by Joepython3** [comment]
It does not help bro, let me try to explain it more. I need to execute when it receives "🎛 Buttons Editor", The execution is to get another message from user and its content to get it as a value

**Comment by barbax7** [comment]
@Joepython3 you must not indent the message_handler
You should use bot.register_next_step_handler or states
See examples directory

**Comment by Joepython3** [comment]
@barbax7
Thanks I did not notice them at the beginning.. Thanks again <3
