### ISSUE TITLE
Exceptions not raised using webhooks

### ISSUE THREAD

**Issue by barbax7** [eternnoir/pyTelegramBotAPI#1431]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.4.0

2. What OS are you using?
Windows and ubuntu 20.04

3. What version of python are you using?
3.8

Hi, i'll try to be pretty clear.

```
@bot.message_handler(commands = ['start'])
def start(message):
    raise
```

This is a very simple code that should raise an exception every time a user sends `/start`.
Nice.
If we use `infinity_polling`, the exception is raised (and bot continues working, excellent)
That is the output:
```
2022-02-01 09:36:16,240 (__init__.py:615 MainThread) ERROR - TeleBot: "Infinity polling exception: No active exception to reraise"
2022-02-01 09:36:16,243 (__init__.py:617 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "c:\Users\andre\OneDrive\Desktop\pyTelegramBotAPI\telebot\__init__.py", line 611, in infinity_polling
    self.polling(none_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "c:\Users\andre\OneDrive\Desktop\pyTelegramBotAPI\telebot\__init__.py", line 658, in polling
    self.__threaded_polling(non_stop, interval, timeout, long_polling_timeout, allowed_updates)
  File "c:\Users\andre\OneDrive\Desktop\pyTelegramBotAPI\telebot\__init__.py", line 720, in __threaded_polling
    raise e
  File "c:\Users\andre\OneDrive\Desktop\pyTelegramBotAPI\telebot\__init__.py", line 680, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "c:\Users\andre\OneDrive\Desktop\pyTelegramBotAPI\telebot\util.py", line 135, in raise_exceptions
    raise self.exception_info
  File "c:\Users\andre\OneDrive\Desktop\pyTelegramBotAPI\telebot\util.py", line 87, in run
    task(*args, **kwargs)
  File "c:\Users\andre\OneDrive\Desktop\pyTelegramBotAPI\test.py", line 17, in start
    raise
RuntimeError: No active exception to reraise
"
```

while, if we use `webhook`, no exception is raised and bot doesn't crash.

This doesn't seem so much bad, but if we have:
```
@bot.message_handler(commands = ['start'])
def start(message):
    bot.send_message(message, 'welcome!')
    save_user_to_db(message.from_user.id)
```
there is an error (`bot.send_message` want `chat_id`, not `message `object) but there won't be any logs about the error. Even if we set the `exception handler` that exception isn't logged (while with `infinity_polling` `exception_handler` is very interesting)

why this? i studied how the library works for at least three hours, and saw the issue.
the `start` function defined under the message_handler is executed inside a try/except block in the WorkerThread
If any exception occures, that is catched by the except clause and stored in variable `bot.worker_pool.execption_info` while the Event `bot.worker_pool.exception_event` is set.

This is the `run` function of a `WorkerThread`:
```
            try:
                task, args, kwargs = self.queue.get(block=True, timeout=.5)
                self.continue_event.clear()
                self.received_task_event.clear()
                self.done_event.clear()
                self.exception_event.clear()
                logger.debug("Received task")
                self.received_task_event.set()

                task(*args, **kwargs)
                logger.debug("Task complete")
                self.done_event.set()
            except Queue.Empty:
                pass
            except Exception as e:
                logger.debug(type(e).__name__ + " occurred, args=" + str(e.args) + "\n" + traceback.format_exc())
                self.exception_info = e
                self.exception_event.set()
                if self.exception_callback:
                    self.exception_callback(self, self.exception_info)
                self.continue_event.wait()

```
as you can see, if any exception occures, we enter the block `except Exception as e` and the exception is stored in `exception_info`
`exception_callback` is by default the function `ThreadPool().on_exception` that brings the exception and stores it outside of the `WorkerThread `object, so in `worker_pool.exception_info` and set `worker_pool.exception_event`
Then it set `worker_thread.continue_event` in order to allow WorkerThread to continue his cicle.

Now, if we use `infinity_polling`, inside the `__threaded_polling`, after telling `PollingThread` to retrieve updates, it waits for an event and then it calls `self.worker_pool.raise_exceptions()` function. This function will raise any exception stored in `worker_pool.exception_info`
Thanks to this the exception is raised and cleared, and bot continues working
([refers to this try/except block, i don't copy the code](https://github.com/eternnoir/pyTelegramBotAPI/blob/723075d2dad68ee5f042276078c2c3e5bf7e23e0/telebot/__init__.py#L676))

But with webhook, when we use `process_new_updates`, it simply put the function `start` (in our example) inside the `worker_pool`, and doesn't raise any exception subsequently stored in `worker_thread.exception_info`.

I was working on this, and seems that the unique way to raise that exceptions and also avoid bot stops and responses to telegram, is to create a new Thread, that simply waits for `worker_pool.exception_event`, calls an exception_handler if set or just raises the error, clear the exception and goes on.

If you agree and assigne this issue to me, i'll continue working on this issue in this 2 weeks.

I hope i was clear, ask me anything

**Comment by coder2020official** [comment]
Hello. What about checking those exceptions in process_new_updates function? Or any other suggestions do you have? I think creating another thread is not a good idea. Btw, I will think about it.

**Comment by barbax7** [comment]
> What about checking those exceptions in process_new_updates function?

I also thought at this, was my first thought.
I defined a function `process_webhook` that wraps `process_new_updates` and add the waiting of any exception. But, in this way, if it waits WorkerThread finishing the task, the webapp will reply to Telegram after some time, and it isn't a good practice.

When telegram sends update to webhook, it waits for a 200 response code, and if it doesn't receive it in 60 seconds, it will resend update.

**Comment by Badiboy** [comment]
> while, if we use webhook, no exception is raised and bot doesn't crash.

I see the issue. I'll check what's there and what to do.

**Comment by Badiboy** [comment]
Okay, I got why I did not meet this problem.

It arises if you use "threaded" mode. process_new_updates don't run the task. It put them to queue, from which it is withdrawn by the pool of threads. Thus, when exception occurs, it is not binded to the calling thread, thus it cannot be catched with exception handler of the function who call process_new_updates.

**Comment by Badiboy** [comment]
The fast solution - disable the threaded mode. Frankly speaking, you do not need it: when you work with webhooks, you generally use some WSGI, at least flask. Flask has it's own threading, so you do not need to use Telebot threading.

But anyway it's not good, so I'll continue checking what can be done.

**Comment by barbax7** [comment]
> Okay, I got why I did not meet this problem.
> 
> It arises if you use "threaded" mode. process_new_updates don't run the task. It put them to queue, from which it is withdrawn by the pool of threads. Thus, when exception occurs, it is not binded to the calling thread, thus it cannot be catched with exception handler of the function who call process_new_updates.

Exactly that was the same i though

> The fast solution - disable the threaded mode. Frankly speaking, you do not need it: when you work with webhooks, you generally use some WSGI, at least flask. Flask has it's own threading, so you do not need to use Telebot threading

Well, yes, but if an error occures while executing process_new_updates, it won't reply to Telegram with response 200

```
@app.route('/webhook_path', methods = ['POST'])
def function():
    bot.process_new_updates(....)
    return '!', 200
```
it never goes to `return` clause, at lease we should wrap it inside try/except block

And also, if the execution requires a lot of time (due to bad practice of programmer, of course) the reply to telegram is sent only at the end
for example:

```
@bot.message_handler(commands = ['start'])
def start(message):
    time.sleep(61)
    bot.reply_to(message, 'hi')
```
with this code, telegram will receive the reply after his timeout, so it will send again the update to the flask app. infiite loop (i know because i encountered a similar issue due to an error in my code in handler of post requests)

**Comment by barbax7** [comment]
> If you hardly need to return before finish processing - run process_new_updates in thread. It's not so hard.

I though also this:
```
def process_webhook(self, updates):
    def threading_process_new_updates(up):
        try: self.process_new_updates(up)
        except Exception as e: .....
    Thread(target = threaded_process_new_updates, args = [updates]).start()

@app.route('/webhook_path', methods = ['POST'])
def function():
    bot.process_webhook(updates)
    return '!', 200
```
Just an idea, to do better

**Comment by Badiboy** [comment]
One of the ways.

**Comment by Badiboy** [comment]
@barbax7 You may know (I suppose you don't) that there is a parameter "exception_handler" in Telebot(). You can pass your own function (class) to be called if exception occurs.

I realise that it does not work for webhooks, only for pollings. I made and update: 
https://github.com/Badiboy/pyTelegramBotAPI/commit/ce56a035b5c8aabdbdf5116130f91abf7907e9e3
that should bring him to work both for polling and webhooks.

I suppose it should cover the issue with non-raising exceptions in webhooks, especially threaded.

**Comment by barbax7** [comment]
> @barbax7 You may know (I suppose you don't) that there is a parameter "exception_handler" in Telebot(). You can pass your own function (class) to be called if exception occurs.

Yes i know about that, as I referred in:
> Even if we set the exception handler that exception isn't logged (while with infinity_polling exception_handler is very interesting)

I looked at your commit, and seems could be good
Sorry if I haven't helped more...

**Comment by barbax7** [comment]
@Badiboy 
It seems that is working good

**Comment by Badiboy** [comment]
Thanks, merged.
