### ISSUE TITLE
How to reply to the original message in the chain?

### ISSUE THREAD

**Issue by jluizpjr** [eternnoir/pyTelegramBotAPI#1436]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.2.0

2. What OS are you using? Linux 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

3. What version of python are you using? 3.8.10

How to reply to the original message in chain?? For example, I receive the message "A" from an user, I type a command /x in and I'd like the boot to reply to the original message "A" instead of replying to my "/x" message. 

Best Regards and congrats for the project!!

**Comment by coder2020official** [comment]
Hello. You should use appropriate handlers to catch this update, and then answer. For example, check echo_bot example:

https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/echo_bot.py
