### ISSUE TITLE
Markdown/MarkdownV2 Code Block issues

### ISSUE THREAD

**Issue by chrisleunglkw** [eternnoir/pyTelegramBotAPI#1437]
Hi there, 

I tried both `Markdown` and `MarkdownV2` Parse Mode for code block, and the behaviour is kind of weird when using multi-lines syntax ``` if there is no escape (\n) on first line.

It might be a bit confusing, let me show the code:

---

```
    bot.reply_to(message, "```\nTest Test Test Test Test\n```", parse_mode = "MarkdownV2")
    bot.reply_to(message, "```Test Test Test Test Test```", parse_mode = "MarkdownV2")
    bot.reply_to(message, '<pre><code class="language-python">pre-formatted fixed-width code block written in the Python programming language</code></pre>', parse_mode = "html")
```
![image](https://user-images.githubusercontent.com/24679566/152382542-d3ee0329-08e0-414f-a38b-9290e5aff12e.png)
(Test result)

---

1. So here looking at the first line the `MardownV2` parse mode being used, 5 of the `Test` word will be displayed correctly. (Because there is an `\n`.

2. For the second line, all the words are keeping in same line without escape, the first `Test` word will be clipped off, which is displaying as `Test Test Test Test`.

3. Third line, as comparison I have tried HTML parse mode and the sample showing at [Telegram API page](https://core.telegram.org/bots/api#markdownv2-style). 

---

When comparing side-by-side, I found that possibly for `MarkdownV2` the first line (after ``` syntax) is to identify the language of the code block and it is not intended to show in message (just like the third line displaying in HTML parse mode).
![image](https://user-images.githubusercontent.com/24679566/152381970-97b1444d-3a19-4ede-a2a1-a111d1db3a2a.png)

---

However, when I tried to copy-and-paste the sample from [Telegram API page](https://core.telegram.org/bots/api#markdownv2-style) and enter directly from both Windows client and Android client, it shows differently. (check the screen capture below)

![image](https://user-images.githubusercontent.com/24679566/152381667-f82cf38c-b251-4d7c-9820-0a4ef3d5bb63.png)

I really do not have an idea whether this is an "issue" from the library or Telegram API, and which should be the correct behaviour.
It is quite interesting to see this accidentally.

Thank you for your time looking into the matter and please feel free to let me know if you want more information. 

Cheers,
Chris

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
`pyTelegramBotAPI==4.4.0`
2. What OS are you using?
3. What version of python are you using?
`Docker python:3.9-slim (debian:bullseye-slim)`

**Comment by coder2020official** [comment]
Interesting. I guess this is error with Bot API, i have tried to send get request manually, and i got the same response.

**Comment by coder2020official** [comment]
This is not a bug. It works exactly as documented. You can't check Markdown parsing through clients intended for users.
- Levlam(dev of tdlib)

**Comment by coder2020official** [comment]
https://t.me/tdlibchat/36206
Read more here.

**Comment by chrisleunglkw** [comment]
Thank you for the prompt response. @coder2020official 
I have read the original chat. That's an interesting one.
