### ISSUE TITLE
Message Handler with chat_id does not work

### ISSUE THREAD

**Issue by AntonWert** [eternnoir/pyTelegramBotAPI#1439]
1. What version of pyTelegramBotAPI are you using? 4.4.0
2. What OS are you using? Raspbian GNU/Linux 10 (buster)
3. What version of python are you using? Python 3.7.3

I wanted to use the "admin" function to hide some commands, so a simple bot:

```
import telebot
from telebot import types

bot = telebot.TeleBot("API Key", parse_mode=None) 

@bot.message_handler(chat_id=[123])
def echo_query(message):
	bot.reply_to(message.chat.id, "Hello Admin")

@bot.message_handler(func=lambda m: True)
def echo_all(message):
	bot.send_message(message.chat.id, "Any Reply")
	bot.send_message(message.chat.id, message.chat.id)

bot.send_message(123, 'startting.')

bot.infinity_polling()
```

Of yourse API Key is set.
And i do get the startting in my chat.
Also I get my id back when I sent any sting.

But I get never to "Hello Admin" 

Is this a bug? Or doing I'm wrong?

**Comment by Badiboy** [comment]
Why you decided it should work with chat_id?

![image](https://user-images.githubusercontent.com/5613421/152655426-6307ded9-1ede-43c0-aead-1a01048bd50a.png)

**Comment by Badiboy** [comment]
If you want to use chat_id (I suppose you saw it in examples of custom filters) - you should follow this example accurately:
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/custom_filters/id_filter_example.py

**Comment by AntonWert** [comment]
Oh sorry - I will directly try
I thought
You can check some built-in filters in source code Example of filtering by id 
is a built in filter

Give me some minutes - I will try and close if I'm succsessful

**Comment by AntonWert** [comment]
Well, it works :-)
Thank you.
The item with te register was not clear for me.
