### ISSUE TITLE
Change de default number of threads

### ISSUE THREAD

**Issue by dedezinholindo** [eternnoir/pyTelegramBotAPI#1442]
Hi!

I found this issue closed here: https://github.com/eternnoir/pyTelegramBotAPI/issues/1118 . It is saying that we have a default number of threads (2). How can I change that number?

Thanks,

André Ricardo

**Comment by coder2020official** [comment]
```
import telebot

bot = telebot.TeleBot('token', num_threads=10) # 10 for example
```

**Comment by dedezinholindo** [comment]
worked perfectly! thanks
