### ISSUE TITLE
Storing File_ids of a group photo message

### ISSUE THREAD

**Issue by alisaqi** [eternnoir/pyTelegramBotAPI#1445]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?  13.11

2. What OS are you using? windows

3. What version of python are you using? 3.9

Question: 

In my bot, I received a forwarded media group message which contained three different photos. Now I want to store all these three photos `file_id` and store them in an array to create a group message and send it to another chat. ( Hint:  all values in `message.photo.file_id` are representing the same photo in various resolutions, and when I store this `file_id` in a list to use it in the `media` section of `bot.send_media_group`, it makes a group of the same photo.

My question is, how can I store those three pictures' unique `file_id` to use it in the `media` section of `bot.send_media_group`

**Comment by Badiboy** [comment]
When GROUP of pictires is sent to bot - you will receive MULTIPLE messages, each one will contain SINGLE foto. So if you want to save GROUP - you should receave ALL messages and collect file_id from each of the message.

**Comment by alisaqi** [comment]
> 

Yes exactly, my question is how to store those file_ids?

**Comment by Badiboy** [comment]
file_ids = []
file_ids.append(message....file_id)

**Comment by alisaqi** [comment]
> file_ids = [] file_ids.append(message....file_id)

cmon man, that is not that easy you think.

**Comment by coder2020official** [comment]
The problem is that each photo comes as different update..

**Comment by alisaqi** [comment]
> The problem is that each photo comes as a different update.

yes, that's another problem as well. This is why I said that is not an easy task. @Badiboy @coder2020official 

@coder2020official Do you have any solution?

**Comment by coder2020official** [comment]
https://t.me/tdlibchat/21924

¯\_(ツ)_/¯ no way
