### ISSUE TITLE
Logger level settings

### ISSUE THREAD

**Issue by Troshchk** [eternnoir/pyTelegramBotAPI#1448]
Hi,

I would like to ask about the `logger.setLevel(logging.ERROR)` in [https://github.com/eternnoir/pyTelegramBotAPI/blob/a8af9120deb4be4ed286fcb7113289af4344867e/telebot/__init__.py#L29](url) .

With this setting, the warnings in [https://github.com/eternnoir/pyTelegramBotAPI/blob/a8af9120deb4be4ed286fcb7113289af4344867e/telebot/__init__.py#L2744](url) do not work.

Is there any particular reason for the logger level to be set on ERROR?

Thanks!

**Comment by Badiboy** [comment]
You can easily override it at any time in your program, what's the problem?

**Comment by Troshchk** [comment]
Having warnings turned on by default makes the API usage more user-friendly and simplifies troubleshooting. 

Less experienced people might not be aware of the logger setting and troubleshooting will be even harder for them while starting to work with this package.

The more experienced users usually know about this setting and can easily turn it off.

**Comment by Troshchk** [comment]
What about making troubleshooting in general easier by default for everyone despite the level?

**Comment by Badiboy** [comment]
The one especially with low level of competences may make their life **much easier** if the will start **everything they do** from reading basic manuals.
