### ISSUE TITLE
Receiving new messages of a public channel by pyTelegramBot

### ISSUE THREAD

**Issue by alisaqi** [eternnoir/pyTelegramBotAPI#1450]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?  13.11

2. What OS are you using? windows

3. What version of python are you using? 3.9

Question:

I want to know how I can program a bot by pyTelegramBot to receive every new message of a public channel; **in this case, my bot is not an admin of that public channel.**

**Comment by Badiboy** [comment]
_in this case, my bot is not an admin of that public channel._

Obviously you cannot.

**Comment by alisaqi** [comment]
> _in this case, my bot is not an admin of that public channel._
> 
> Obviously you cannot.

Isn't there any other solution?
