### ISSUE TITLE
In group chats bot reacts on other bot's command even if they mentioned directly

### ISSUE THREAD

**Issue by NEK-RA** [eternnoir/pyTelegramBotAPI#1451]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Version in  `pyproject.toml`: `pyTelegramBotAPI = "^4.3.1"`
Version in `poetry.lock`: `version = "4.4.0"`
Metadata for files in `poetry.lock`: `{file = "pyTelegramBotAPI-4.4.0.tar.gz", hash = "sha256:e6f22356abebffe0a893dcf72fe09a0c8bdedad6f498c55a30c3dd32ce488e6a"}`

2. What OS are you using?
OS: Ubuntu 20.04.3 LTS x86_64
Kernel: 5.4.0-97-generic

3. What version of python are you using?
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux

Description:
For example we have 2 bot's in the group chat. 
The first `@bot1` is just some bot from the Telegram, not our.
The second `@mybot` is my bot, written with pyTelegramBotAPI module.

I defined handler for the `start` and `help` commands by next code:

```py
@bot.message_handler(commands=["start","help"])
  def usage(msg):
    response = "Some help text"
    bot.reply_to(msg, response)
```

It works well.

When in group chat we call `/help` - it's expected behaviour to see that all bot's which have this command were triggered and replied somehow for that.

But when I call `/help@bot1`, I expect to see the `@bot1` help only, but finally `@mybot` also got triggered, however it shoudn't, just because with command I mentioned `@bot1` clearly.

The only way I see for now to fix this on the user's side is to check in each handler if message includes `@` and not includes `mybot` and just ignore such messages somehow, but I'm not sure it it's the "right way" to solve the problem.

**Comment by coder2020official** [comment]
You can use filters:

https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/custom_filters/text_filter_example.py

**Comment by NEK-RA** [comment]
But shouldn't it be filtered by default?

In example when you talking with friend somewhere at crowded place, when you talk directly to your friend, it's not ok, when random person answer to you instead of your friend.
