### ISSUE TITLE
No token in webhook update

### ISSUE THREAD

**Issue by prashantsengar** [eternnoir/pyTelegramBotAPI#1452]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.4.0

2. What OS are you using? Ubuntu 18.04.6 LT

3. What version of python are you using? python 3.6.9

I am using the [AIOHTTP example webhook script](https://github.com/eternnoir/pyTelegramBotAPI/tree/master/examples/webhook_examples) and was receiving the updates.

Suddenly after stopping and running it for a few times, it stopped receiving updates. On further investigation, I found out that the AIOHTTP request handler was receiving an update with the `token` set to `None`

```python
async def handle(request):
    print("yes")
    print(request.match_info.get("token"))
    if request.match_info.get("token") == bot.token:
        print("correct")
        request_body_dict = await request.json()
        update = telebot.types.Update.de_json(request_body_dict)
        bot.process_new_updates([update])
        return web.Response()
    else:
        print("wrong update")
        return web.Response(status=403)
```

It prints:
```
yes
None
wrong update
```

This means that it is not receiving the bot token in the request.

Here is my webhook_info:

```
{'url': 'my_ip:port/52XXXXX:AAHXYXZXYZYXZYXYZYXZYYZX/', 'has_custom_certificate': True, 'pending_update_count': 7, 'ip_address': 'my_ip', 'last_error_date': 1644752518, 'last_error_message': 'Connection refused', 'max_connections': 40, 'allowed_updates': None}
```

However, if I remove the check (if-else conditions) from the function, it starts receiving the updates.

Has there been any updates to the Telegram API which is not reflected in the examples yet? There also seems to be no mention of bot token in https://core.telegram.org/bots/api#update

**Comment by coder2020official** [comment]
So, you should get path:
ip:port/path_were_is_token

**Comment by prashantsengar** [comment]
But isn't this exactly what's being done in the [example](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/webhook_examples/webhook_aiohttp_echo_bot.py) given?

And it was actually receiving updates in the method until it stopped
