### ISSUE TITLE
Error when trying to use a custom filter

### ISSUE THREAD

**Issue by Lorg0n** [eternnoir/pyTelegramBotAPI#1463]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
- Latest (4.4.0)
2. What OS are you using?
- Windows 11
3. What version of python are you using?
- 3.10.2 (Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]

When I try to use the code from the example, an error is written to me:
`TypeError: 'in <string>' requires string as left operand, not list`
Code from [example](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/custom_filters.py) (in comments):
```
@bot.message_handler(text_contains=['account'])
def testM(message):
    bot.send_message(message.chat.id, f'Test')

bot.add_custom_filter(custom_filters.TextContainsFilter())
bot.infinity_polling(skip_pending=True)
```
This works if you change the list to a string, but it has stumped me. Most likely, this is a bug.

**Comment by coder2020official** [comment]
Try to install github version

**Comment by coder2020official** [comment]
So, have you tried installing git version?
