### ISSUE TITLE
i write a inline image searching bot , i want to add pyTelegramBotApi example 

### ISSUE THREAD

**Issue by Qiamast** [eternnoir/pyTelegramBotAPI#1464]
ImarchBot is an inline image search bot for telegram
I just want you to add my bot to the pyTelegramBotApi example
[imarchBot source code](https://github.com/Qiamast/ImarchBot)

1. What version of pyTelegramBotAPI are you using?  **pyTelegramBotAPI==4.4.0**

2. What OS are you using?  **Windows10**

3. What version of python are you using? **3.8 +**

**Comment by coder2020official** [comment]
Make a pull request
