### ISSUE TITLE
send_message

### ISSUE THREAD

**Issue by roaste** [eternnoir/pyTelegramBotAPI#1466]
What the timeout parameter in send_message doing? I can't search answer in Google.

**Comment by Badiboy** [comment]
Define a manual timeout for this call of send_message...

**Comment by roaste** [comment]
Does it work in simple chats or only in channels?
And what data should be submitted to the input

**Comment by coder2020official** [comment]
In any send_message.
Just ignore this parameter

**Comment by Badiboy** [comment]
bot.send_message(....., send_timeout = 60)
