### ISSUE TITLE
Get channel posts

### ISSUE THREAD

**Issue by roaste** [eternnoir/pyTelegramBotAPI#1471]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.4.0
2. What OS are you using?
win 10
3. What version of python are you using?
3.7

How i can get channel posts?
I want get all channel posts, it`s possible?

P.S. bot.get_chat dont return last posts

**Comment by Badiboy** [comment]
You cannot READ posts from channel with bot. No such API.
