### ISSUE TITLE
Information about link, that my bot generated for the Telegram channel,

### ISSUE THREAD

**Issue by kosavan** [eternnoir/pyTelegramBotAPI#1483]
Good afternoon! I have a problem that I have been working on for several days. I wrote a bot that generated links to the telegram channel. Now I want to find out if this link was used and which person was invited by it. It will be difficult to do this manually due to the large volume of links. Is there any way to do this via pytelegrambotapi?

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? - 4.4.0

2. What OS are you using? Windows

3. What version of python are you using? 3.6

**Comment by coder2020official** [comment]
Hello!
~ Sorry for late response.  You can use chat_member_handler to handle updates:

https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/chat_member_example.py

<img width="805" alt="image" src="https://user-images.githubusercontent.com/63740404/159111764-579b6e62-1834-49f0-823e-198f86bb0d25.png">

- You can get invite link in this update. But:

`The invite link. If the link was created by another chat administrator, then the second part of the link will be replaced with “…”.`

But, you can still see creator of link. Read more here:

https://core.telegram.org/bots/api#chatmemberupdated
