### ISSUE TITLE
register_next_step_handler

### ISSUE THREAD

**Issue by Eikosa** [eternnoir/pyTelegramBotAPI#1487]
How can i use bot.register_next_step_handler on AsyncTeleBot?

![image](https://user-images.githubusercontent.com/20538090/160249385-a6ef81ff-7063-4aa5-9705-b3835b94f094.png)

**Comment by coder2020official** [comment]
Hello. Unfortunately, Asynchronous implementation **does not** contain register_next_step_handler. For now, you can use states.

https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/asynchronous_telebot/custom_states.py

**Comment by coder2020official** [comment]
register_next_step_handler may be added in near future.

**Comment by Eikosa** [comment]
[> register_next_step_handler may be added in near future.](https://github.com/eternnoir/pyTelegramBotAPI/issues/1487#issuecomment-1079737917)

How can i add a kwords with states?
Like that:
`bot.register_next_step_handler(sent, write_word, location)`
(location is kwords)

**Comment by coder2020official** [comment]
Please take a look at example:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/63740404/160251607-e4961508-fcfb-4c73-aa08-104046fdd74f.png">

As you see, you can create a special dictionary which is unique for user. You can store data there.

**Comment by Eikosa** [comment]
> Please take a look at example:
> 
> <img alt="image" width="622" src="https://user-images.githubusercontent.com/63740404/160251607-e4961508-fcfb-4c73-aa08-104046fdd74f.png">
> 
> As you see, you can create a special dictionary which is unique for user. You can store data there.

I tried like this, but this time, other functions give the following error because there is no state :(

`TypeError: argument of type 'State' is not iterable
Task exception was never retrieved
future: <Task finished coro=<AsyncTeleBot.process_new_updates() done, defined at C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\telebot\async_telebot.py:398> exception=TypeError("argument of type 'State' is not iterable")>
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\telebot\async_telebot.py", line 463, in process_new_updates       
    await self.process_new_messages(new_messages)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\telebot\async_telebot.py", line 493, in process_new_messages      
    await self._process_updates(self.message_handlers, new_messages, 'message')
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\telebot\async_telebot.py", line 348, in _process_updates
    await asyncio.gather(*tasks)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\telebot\async_telebot.py", line 365, in _run_middlewares_and_handlers
    process_update = await self._test_message_handler(handler, message)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\telebot\async_telebot.py", line 557, in _test_message_handler     
    if not await self._test_filter(message_filter, filter_value, message):
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\telebot\async_telebot.py", line 616, in _check_filter
    return await filter_check.check(message, filter_value)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\telebot\asyncio_filters.py", line 167, in check
    elif group_state in text and type(text) is list:`

**Comment by coder2020official** [comment]
Can you provide **full code** so I could reproduce it?

**Comment by Eikosa** [comment]
> Can you provide **full code** so I could reproduce it?

I decided to keep it in a temporary variable until register_next_step_handler, it will edit when they send a text message, thank you very very much ✨
