### ISSUE TITLE
Eval Exec on Async

### ISSUE THREAD

**Issue by Eikosa** [eternnoir/pyTelegramBotAPI#1489]
![image](https://user-images.githubusercontent.com/20538090/160258926-405804cc-dad7-42ce-8dc1-e92bba7acb1e.png)

Before switching to async telebot, I wrote eval and exec commands, so I could manage the bot from telegram, but I can't use it after doing async, could you please help?

My eval & exec code

```
if msg.startswith("/eval "):
    command = msg.replace("/eval ","")
    Do = eval(command)
    if Do != None:
        bot.send_message(chat_id,str(Do))
        return
    elif msg.startswith("/exec "):
        command = msg.replace("/exec ","").strip()
        command = command.replace("bsm(", "bot.send_message(chat_id,")

        exec(command)
    return
```
Before async:
![image](https://user-images.githubusercontent.com/20538090/160259071-011fe294-b4c8-41bd-9b9e-662885195bbb.png)

After async:
![image](https://user-images.githubusercontent.com/20538090/160259040-c0af13c2-6064-46d6-b379-ccdf8bfc79d8.png)
(No answer)

**Comment by coder2020official** [comment]
Hi!
You should take a closer look at examples. AsyncTeleBot requires you to create asynchronous functions for handlers and you should also write await between api functions.

**Comment by Eikosa** [comment]
> Hi! You should take a closer look at examples. AsyncTeleBot requires you to create asynchronous functions for handlers and you should also write await between api functions.

Although I used many ways to solve it, unfortunately it does not work as well as before, I used to be able to run even long codes :/

**Comment by Eikosa** [comment]
Problem is not solved

**Comment by Badiboy** [comment]
You did not provide any update except "I used many ways to solve it".

**Comment by Eikosa** [comment]
> You did not provide any update except "I used many ways to solve it".

because i couldn't and i need help
