### ISSUE TITLE
new_chat_member and content_types

### ISSUE THREAD

**Issue by Otsoko** [eternnoir/pyTelegramBotAPI#149]
Telegram API has changed the field `new_chat_participant` to `new_chat_member`, as well as `left_chat_participant` to `left_chat_member`.

Also, `content_type` in this cases has changed to `None` from now on, so this example:

``` python
@bot.message_handler(func=lambda m: True, content_types=['new_chat_participant'])
def on_user_joins(message):
    if not is_api_group(message.chat.id):
        return
...
```

is not working anymore.
How can we detect new/left chat members? `add_message_handler` is converting`content_type` to `['text']` if it is `None`

Thank you so much in advance!

**Comment by Otsoko** [comment]
I did this as a workaround in order to make it work:

```python
def listener(messages):
	for m in messages:
		if m.content_type == 'text':
#		text stuff
		elif m.content_type is None:
			if hasattr(m.new_chat_member, 'id'):
				on_user_joins(m)
			elif hasattr(m.left_chat_member, 'id'):
				on_user_lefts(m)
```

**Comment by eternnoir** [comment]
Try this:

```
@bot.message_handler(func=lambda m: True, content_types=['new_chat_member'])
def on_user_joins(message):
    if not is_api_group(message.chat.id):
        return
...
```
