### ISSUE TITLE
Is there any way to start many process for one bot?

### ISSUE THREAD

**Issue by mikolaje** [eternnoir/pyTelegramBotAPI#1490]
Please answer these questions before submitting your issue. Thanks!
Due to there are many issues when running the AsyncTeleBot, it raised timeout error. But actually it's running normal without using AsyncTeleBot.  So, can I run multiple processes for one bot?

1. What version of pyTelegramBotAPI are you using?
4.4.0
2. What OS are you using?
Mac
3. What version of python are you using?
3.8

**Comment by coder2020official** [comment]
What?
AsyncTeleBot creates new tasks for running message handler. You can ignore timeouterror.

**Comment by mikolaje** [comment]
> What? AsyncTeleBot creates new tasks for running message handler. You can ignore timeouterror.

No, it doesn't work at all. I can't figure out the reason yet, but I believe there could be many issues while using asyncio, as the asyncio is confusing sometimes, and it's hard to find the cause. Thus, I think it's better to use multiple processes.

**Comment by coder2020official** [comment]
Then you should try synchronous telebot.
