### ISSUE TITLE
Is there any way to send scheduled messages?

### ISSUE THREAD

**Issue by Alex30NICK** [eternnoir/pyTelegramBotAPI#1493]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.4.0
2. What OS are you using?
Windows 11
3. What version of python are you using?
3.9

I've seen that Telegram API has methods to send schedulde messages but i can't find such things in pyTelegramBotAP.
https://core.telegram.org/api/scheduled-messages

**Comment by Badiboy** [comment]
It's CLIENT API. Bot API is here: https://core.telegram.org/bots/api
