### ISSUE TITLE
'telebot.types' has no attribute 'User' (most likely due to a circular import)

### ISSUE THREAD

**Issue by ThanosApollo** [eternnoir/pyTelegramBotAPI#1497]
I'm using Python 3.9.12, on a MacBook and Fedora PC.
I'm getting the following error in both : 
 Traceback (most recent call last):
  File "/Users/thanosraptis/Desktop/MUS-Bot/MUS-Robot.py", line 6, in <module>
    from telebot import types, TeleBot
  File "/opt/homebrew/lib/python3.9/site-packages/telebot/types.py", line 12, in <module>
    from telebot import util
  File "/opt/homebrew/lib/python3.9/site-packages/telebot/util.py", line 323, in <module>
    def user_link(user: types.User, include_id: bool=False) -> str:
AttributeError: partially initialized module 'telebot.types' has no attribute 'User' (most likely due to a circular import)

I also used the CallbackData example, as is in the repo, and I'm getting the same error. The telegram bot I had was working just fine a couple days ago. Thank you.

**Comment by Badiboy** [comment]
What version of ptb?

**Comment by ThanosApollo** [comment]
4.3.1

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/162737461-b0b4ad94-26d4-4093-bb0b-3417621e3664.png)

¯\_(ツ)_/¯

**Comment by Badiboy** [comment]
If the problem will still arise - let us know, we'll go deeper.

**Comment by ThanosApollo** [comment]
Its my bad, I apologize for any inconvenience caused. Just today I installed fedora and I guess I made some mistake when editing my telegram bot. Reinstalled fedora and remade the bot and have no issue as of now. Thank you for your patience, have a nice day
