### ISSUE TITLE
StateFilter incorrect list type check

### ISSUE THREAD

**Issue by feelgood-interface** [eternnoir/pyTelegramBotAPI#1498]
1. What version of pyTelegramBotAPI are you using?
4.4.0

2. What OS are you using?
Windows 10 64bit

3. What version of python are you using?
Python 3.9

Good day,
when checking the state of a message in a group chat, I am getting the following error:
`TypeError: argument of type 'State' is not iterable`
The current line is:
`elif group_state in text and type(text) is list:`
The list type check should occur first.

**Comment by coder2020official** [comment]
Make a PR.

**Comment by coder2020official** [comment]
Ok, I'll correct this issue by myself.
- Thanks for the report!

**Comment by coder2020official** [comment]
#1500 fixes it
