### ISSUE TITLE
Can't get message.forward_from_message_id

### ISSUE THREAD

**Issue by dannkunt** [eternnoir/pyTelegramBotAPI#1499]
![image](https://user-images.githubusercontent.com/32395839/163443704-b5d7eeac-365c-484f-9286-a7700b4b4623.png)

Can't get forwarded message id, no matter if user is hiding his id or not

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.4.0

2. What OS are you using?
Manjaro GNU/Linux

3. What version of python are you using?
3.10.2

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/163467046-d2930c7a-fcfe-4374-bbfb-40f1c53e7f3b.png)

It's optional and exists only for **channels**.

**Comment by dannkunt** [comment]
It's sad
