### ISSUE TITLE
How can I figure out what the user selected in a keyboard button? And ask questions and receive answers?

### ISSUE THREAD

**Issue by MarcoBuster** [eternnoir/pyTelegramBotAPI#150]
HI, I have created a keyboard (from the example in the guide):
```
@bot.message_handler(commands=['start', 'help', 'test'])
def send_welcome(message):  
    markup = types.ReplyKeyboardMarkup(row_width=2)
    itembtn1 = types.KeyboardButton('1')
    itembtn2 = types.KeyboardButton('2')
    itembtn3 = types.KeyboardButton('3')
    markup.add(itembtn1, itembtn2, itembtn3)
    bot.reply_to(message, "Choose one letter:", reply_markup=markup)
```
how can I figure out what the user selected ?
Ok, I fixxed this problem (thanks @thakryptex )
But, if I want (after pressing), ask the user a number and save it in a variable, how I can do?
Thanks,
Marco.
If you want, contact me: tlgrm.me/marcobuster

**Comment by thakryptex** [comment]
@MarcoBuster, hi.
**For simple reply keybord:**
when the user press the button (i.e. `types.KeyboardButton('1')` ), he will send the message to the bot with this text (here, he will send 1).
**So, you need to handle user messages with the text from your buttons:**
`@bot.message_handler(func=lambda message: message.text == '1' and message.content_type == 'text')` - to handle message with text == '1'
`@bot.message_handler(func=lambda message: True, content_types=['text'])` - to handle all text messages

**For inline keyboards it works different:**
[you can see example here](https://github.com/eternnoir/pyTelegramBotAPI/blob/bot20/examples/bot20-pass_generator-example.py)

**Comment by MarcoBuster** [comment]
@thakryptex 
Thanks! If I want (after pressing), ask the user a number and save it in a variable, how I can do?

**Comment by thakryptex** [comment]
@MarcoBuster, you mean user pressed a button (i.e. button is "Check order by ID"), then you send him message with text (like "Send ID of your order") and how to get his answer?
If so, you get his answer the same way as I described in a previous post, then save it in a variable or better database.

**Good way:**
These are different states for the user (finite state automata)
1 - main menu,
2 - menu of typing ID.
By pressing the buttons, users switching between these states. In each state he have to have limited options to do.

**Easier way:**
You can do it with commands.
Again, if we need his order ID, then we can set command like /id to do this.
And user have to write it like this `/id 1234`.
You handle this with `@bot.message_handler(commands=['id''])`, then do what you want.
This way you don't need states, but this is bad interface for the user.

**Comment by MarcoBuster** [comment]
I don't understand the Good way.
Yes, I want (for example) and ID.
1. Do /start
2. Press the button "ID"
3. The bot will ask me the ID, and the answer will be saved in a var
4. [Processing ID]
5. Send the informations

A little as the function "search" of @storebot

**Comment by thakryptex** [comment]
@MarcoBuster, read about [finite state automata](https://en.wikipedia.org/wiki/Finite-state_machine).
I draw a scheme of FSA for this ID example:
![fsa](https://cloud.githubusercontent.com/assets/12232787/14936281/b1af54f2-0ef2-11e6-8e29-f9db3aa13e83.png)

**These circles are states:**
- **main state** (which is initial state), where you have this "ID" button.
- **ID state**, where you have "back" button and user can type text (in our example is ID).

By pressing these two buttons, user switch between states.
You have to remember current state of each user (in SQLite, for example).

So, when user's state is ID and user sends some text, you handle it and check whether it's correct ID or it's wrong.
After user gets what he wanted, he can simply press "back" button and return to initial state.

**Comment by MarcoBuster** [comment]
@thakryptex Yes, now I learned the theory. But in pratice? Can you link me some example?
Thanks

**Comment by MarcoBuster** [comment]
@thakryptex Please reply.
Please

**Comment by thakryptex** [comment]
@MarcoBuster, all I can show you now is my previous version of bot - https://github.com/thakryptex/Telegram_Bots/tree/master/idoit_bot
But it is not so simple example for state automata.
As you can see there are lines with db.set_state, db.get_state. Try to understand logic, meaning and do your own bot with FSA. It will be clearer for yourself. Draw a scheme on a paper and then try to build it in code.

**Comment by Sheruan** [comment]
Hello. I have a question. What if I have button, which requesting contact data and after clicking no defined text is sent, so how can I save contact data to variables?

The issue is simple, user share contact, by clicking the button and bot have to save this contact.

**Comment by AndreiJirohHaliliDev2006** [comment]
> @MarcoBuster, hi.
> **For simple reply keybord:**
> when the user press the button (i.e. `types.KeyboardButton('1')` ), he will send the message to the bot with this text (here, he will send 1).
> **So, you need to handle user messages with the text from your buttons:**
> `@bot.message_handler(func=lambda message: message.text == '1' and message.content_type == 'text')` - to handle message with text == '1'
> `@bot.message_handler(func=lambda message: True, content_types=['text'])` - to handle all text messages
> 
> **For inline keyboards it works different:**
> [you can see example here](https://github.com/eternnoir/pyTelegramBotAPI/blob/bot20/examples/bot20-pass_generator-example.py)

@thakryptex It seems [the file you stated in your comment](https://github.com/eternnoir/pyTelegramBotAPI/blob/bot20/examples/bot20-pass_generator-example.py) was deleted. Where is it or is there is other places for that example?
