### ISSUE TITLE
Send_invoice currency error.

### ISSUE THREAD

**Issue by captainluzik** [eternnoir/pyTelegramBotAPI#1505]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI==4.4.1

3. What OS are you using?
Windows 11
4. What version of python are you using?
3.9

if send invoice from your example code handle this error (with ANY currency from currency list in telegram)
`ERROR - TeleBot: "A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: CURRENCY_INVALID"`

**Comment by captainluzik** [comment]
UPD: provider is **PayMaster Test**

**Comment by captainluzik** [comment]
Please tell, maybe is provider's trouble? And, what payment provaders is valid for this method?

**Comment by coder2020official** [comment]
Please show ur currency that you have passed to send_invoice.
Here is a list of currencies available:
https://core.telegram.org/bots/payments#supported-currencies

**Comment by Badiboy** [comment]
Seems there is an error in the example. First paramters are not named. Try this:

```
    bot.send_invoice(
                     message.chat.id,  #chat_id
                     'Working Time Machine', #title
                     ' Want to visit your great-great-great-grandparents? Make a fortune at the races? Shake hands with Hammurabi and take a stroll in the Hanging Gardens? Order our Working Time Machine today!', #description
                     'HAPPY FRIDAYS COUPON', #invoice_payload 
                     provider_token, #provider_token
                     'usd', #currency
                     prices, #prices
                     photo_url='http://erkelzaar.tsudao.com/models/perrotta/TIME_MACHINE.jpg',
                     photo_height=512,  # !=0/None or picture won't be shown
                     photo_width=512,
                     photo_size=512,
                     is_flexible=False,  # True If you need to set up Shipping Fee
                     start_parameter='time-machine-example')
```
