### ISSUE TITLE
AttributeError: module 'telebot' has no attribute 'telebot'

### ISSUE THREAD

**Issue by Miwa122op1** [eternnoir/pyTelegramBotAPI#1508]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.4.1
2. What OS are you using?
windows 10 64x
3. What version of python are you using?
python 3.9.12

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/issues/1033
