### ISSUE TITLE
How can i handle data transfer from webApp to bot? 

### ISSUE THREAD

**Issue by mihailgok** [eternnoir/pyTelegramBotAPI#1519]
There is no @bot.callback_webAppInfo_handler or smth like that so how can i get info from web app to my bot? 
<img width="492" alt="Снимок экрана 2022-04-24 в 17 19 02" src="https://user-images.githubusercontent.com/95829301/164980938-cc231049-4c12-4bd1-87ef-6c0108b422d2.png">

advance thanks

**Comment by Badiboy** [comment]
You should use message_handler and process web_app_data field in the Message.
https://core.telegram.org/bots/api#message

**Comment by Badiboy** [comment]
To handle especially WebApp responces set filter to content_type "web_app_data".

**Comment by mihailgok** [comment]
> To handle especially WebApp responces set filter to content_type "web_app_data".

Thank you so much!! 
I have one more question, how can i send data from webApp to bot if i start web app not from [Keyboard button](https://core.telegram.org/bots/webapps#keyboard-button-web-apps) so i cant use `sendData(data)` function as says API: 
<img width="818" alt="Снимок экрана 2022-04-25 в 00 44 41" src="https://user-images.githubusercontent.com/95829301/164997945-103cb81c-5b18-4ad9-b62d-1fae542539e9.png">

**Comment by Badiboy** [comment]
This question regards to WebApp behaviour and is out of the bot scope.

**Comment by mihailgok** [comment]
nevertheless, thank you
