### ISSUE TITLE
ReplyKeyboardMarkup - 'str' object has no attribute 'to_dic'

### ISSUE THREAD

**Issue by thakryptex** [eternnoir/pyTelegramBotAPI#152]
Earlier, code like this worked fine:
```
markup_main = types.ReplyKeyboardMarkup(resize_keyboard=True)
markup_main.row('Show')
markup_main.row('Tasks')
markup_main.row('Time, 'Help')
```

Now I get `AttributeError: 'str' object has no attribute 'to_dic'`.

I know how to make it work:
```
item_show = types.KeyboardButton('Show')
item_tasks = types.KeyboardButton('Tasks')
item_help = types.KeyboardButton('Help')
```
, but **this is redundant for simple ReplyKeyboardMarkup.**

Can you, please, make it simplier like it was earlier?
Now all of my bots with ReplyKeyboardMarkup can't start, because of this issue, and I have to rewrite them.

**It can be fixed** (In _types.py_, class _ReplyKeyboardMarkup_) **like this, for example:**
```
def row(self, *args):
    btn_array = []
    for button in args:
        if isinstance(button, str):
            btn_array.append({'text': button})
        else:
            btn_array.append(button.to_dic())
    self.keyboard.append(btn_array)
    return self
```

**Comment by MarcoBuster** [comment]
I have the same problem! Wow!

**Comment by thakryptex** [comment]
As I notice, this piece of code appears only in master branch.
In bot20 and develop braches "row" method is just:
```
def row(self, *args):
    self.keyboard.append(args)
    return self
```
I don't know if it's better, but I hope in the next update everything will be fine :)
Now I just change types.py in my local machine for proper work.

**Comment by ilteoood** [comment]
+1, same thing here!

**Comment by eternnoir** [comment]
@thakryptex Row method is fixed.

```
def row(self, *args):
    btn_array = []
    for button in args:
        if isinstance(button, str):
            btn_array.append({'text': button})
        else:
            btn_array.append(button.to_dic())
    self.keyboard.append(btn_array)
    return self
``` 

It's a good idea to let bot1.0's code support bot2.0's ReplyKeyboardMarkup. I'll add this feature in next update. Thanks for your suggestion.

**Comment by eternnoir** [comment]
Fixed. https://github.com/eternnoir/pyTelegramBotAPI/releases/tag/2.0.5
