### ISSUE TITLE
Reactions  in pyTelegramBotAPI

### ISSUE THREAD

**Issue by xsa-dev** [eternnoir/pyTelegramBotAPI#1523]
Telegram allows you to send [reactions](https://core.telegram.org/method/messages.getMessageReactionsList). Is it possible to read these reactions through the library?

**Comment by coder2020official** [comment]
Hi. Bots cannot react to messages yet.

**Comment by dzaytsev91** [comment]
Should we reopen this issue?
https://github.com/tdlib/telegram-bot-api/commit/0ec870fd77a97da9a532a8c80add073c1a56d2fd
