### ISSUE TITLE
Concurrency error related to storages

### ISSUE THREAD

**Issue by coder2020official** [eternnoir/pyTelegramBotAPI#1530]
Please answer these questions before submitting your issue. Thanks!
Tested 3 different storages: Pickle, Redis, Memory - only asynchronous ones.
Redis storage needs to be improved in order to support concurrency.

1. What version of pyTelegramBotAPI are you using?
4.5.0
2. What OS are you using?
MacOS
3. What version of python are you using?
4. 3.9.6

**Comment by 0x54726F79** [comment]
As far as I know, all storage don't support multithreading, only async.
You can inherit from storage class and add synchronization mechanisms such as mutexes.

**Comment by coder2020official** [comment]
Hello.
Yes, I am going to test threading/asyncio locks for sync and async.

**Comment by Badiboy** [comment]
@coder2020official close?

**Comment by coder2020official** [comment]
I wasn't able to reproduce it, let's close it for now
