### ISSUE TITLE
"takes 1 positional argument but 2 were given" when two identical handlers

### ISSUE THREAD

**Issue by WallaceWilliam** [eternnoir/pyTelegramBotAPI#1533]
i use two identical handlers
```
@bot.message_handler(func=lambda m: True)
def echo_all1(message):
        logger.info(f"echo1 \n{message}")

@bot.message_handler(func=lambda m: True)
def echo_all2(message):
        logger.info(f"echo3 \n{message}")
```
use_class_middlewares=True
and on the second handler I get an error
"**ERROR:root:echo_all2() takes 1 positional argument but 2 were given**"
I found out what's in the code
https://github.com/eternnoir/pyTelegramBotAPI/blob/146fd57b10bc1ae30412c30d515c3d4fdc54fd28/telebot/__init__.py#L3942-L3943
with each subsequent handler accumulates _params_
to fix this, I put before the start of the cycle
```
params =[]
for i in inspect.signature(handler['function']).parameters:
    params.append(i)
```

**Comment by coder2020official** [comment]
Using handlers with same filters is not allowed
