### ISSUE TITLE
Unknown error: TimeoutError

### ISSUE THREAD

**Issue by re3turn** [eternnoir/pyTelegramBotAPI#1543]
1. What version of pyTelegramBotAPI are you using?
4.5.1
2. What OS are you using?
debian([python:3.10](https://hub.docker.com/_/python))

3. What version of python are you using?
 3.10.4

I'm trying AsyncTeleBot sample from README - https://github.com/eternnoir/pyTelegramBotAPI#asynctelebot
Same error as  #1435 occurs.

```Python traceback
2022-05-11 21:47:19,791 (asyncio_helper.py:74 MainThread) ERROR - TeleBot: "Unknown error: TimeoutError"
2022-05-11 21:47:19,791 (async_telebot.py:234 MainThread) ERROR - TeleBot: "Request timeout. Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x7f89e3e249d0> files=None request_timeout=20"
```
If the message arrives within 20 seconds, the exception will not occur for a while.
However, after a while, exceptions occur.

**Comment by Badiboy** [comment]
What polling parameters do you use?

**Comment by re3turn** [comment]
No parameters are used

**Comment by coder2020official** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/issues/1435#issuecomment-1028121410

**Comment by re3turn** [comment]
I want to suppress the output of TimeoutError message.

**Comment by Badiboy** [comment]
Try to add timeout=30 parameter. Will it change the behaviour?

**Comment by re3turn** [comment]
Add `timeout=60` and `request_timeout = 60` has reduced the frequency of TimeoutError messages.

**Comment by Badiboy** [comment]
@re3turn Is what **you** did is what **I** asked to do?

**Comment by re3turn** [comment]
Not completely, but the frequency of messages has reduced, so I'm satisfied.
thanks

**Comment by Badiboy** [comment]
¯\_(ツ)_/¯

It's up to you...
