### ISSUE TITLE
A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message can't be deleted

### ISSUE THREAD

**Issue by paantya** [eternnoir/pyTelegramBotAPI#1544]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
-4.5.1

2. What OS are you using?
ubuntu 18,04

3. What version of python are you using?
pyhton3.6

Can you please tell me why messages in the channel can not be deleted using the bot?
The bot has rights to delete messages.
Could this be related to some kind of speed limit for deleting messages?

error text:
`A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message can't be deleted`

bot have flag in channel can_delete_messages == True

**Comment by paantya** [comment]
yes, the bot has access to delete messages, and he is in the admins of the public channel.

What other rules should be there?

**Comment by Badiboy** [comment]
May be you simply use wrong IDs to delete message(s)?

**Comment by paantya** [comment]
learned that the 48 hour rule is the most important(

**Comment by liergouzi88** [comment]
> 了解到 48 小时规则是最重要的（
拥有管理员权限 也删除不掉
