### ISSUE TITLE
Using local Bot API Sever but with local telebot.TeleBot instance

### ISSUE THREAD

**Issue by kostyakoz** [eternnoir/pyTelegramBotAPI#1546]
Hello! [Here you described](https://github.com/eternnoir/pyTelegramBotAPI#using-local-bot-api-sever) how to change API URL globally. Is there any way to change API URL specific for `telebot.TeleBot` instance without global replacement? Thanks.

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.5.1

2. What OS are you using? Ubuntu 18.04.5

3. What version of python are you using? 3.8

**Comment by Badiboy** [comment]
Why global one is not suitable? What usecase?

**Comment by kostyakoz** [comment]
[Badiboy](https://github.com/Badiboy) I'm using multiple bots in same project and they are initialising not simultaneously on different threads, I'm afraid that changing global API_URL during work can somehow negatively affect already initialised bots. I'm using own API server for uploading large files, so not every of my bots need this feature.

**Comment by coder2020official** [comment]
#1192 ig something similar to this is needed

**Comment by Badiboy** [comment]
@kostyakoz Looks reasonable. I'll take a look.

**Comment by Badiboy** [comment]
I checked. Not possible within current library architecture. Sorry.
