### ISSUE TITLE
ReplyKeyboardMarkup forces replying messages for groups, but not for bot himself

### ISSUE THREAD

**Issue by ksnow-be** [eternnoir/pyTelegramBotAPI#1559]
1. What version of pyTelegramBotAPI are you using? (4.4.0)
2. What OS are you using? (macOS Monterey)
3. What version of python are you using? (3.9.12)

So i have a bot who will manipulate 2 groups. 
The essence of the bot is to register people for an event by clicking on KeyboardButton of ReplyKeyboardMarkup.
Here is a simple init code for /start command:

    @bot.message_handler(commands=['start'])
    def start(message):
        bot.send_message(CHAT1_ID, 'CHAT1 START', reply_markup=service.createDefaultMarkup())
        bot.send_message(CHAT2_ID, 'CHAT2 START', reply_markup=service.createDefaultMarkup())

ReplyKeyboardMarkup creation method is something like:

    def createDefaultMarkup():
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
            markup.row(types.KeyboardButton('some text 1')
            markup.row(types.KeyboardButton('some text 2')
        return markup

Logic of bot is simple:
People can register on events by clicking on buttons IN BOTH groups and markup will change in BOTH groups for a person depending on a button he clicked.  (was: 'b1', 'b2' -> press 'b1' -> becomes: 'cancel b1', 'b2').

So when i launch my bot in those groups (as an admin in each), ReplyKeyboardMarkup forces to REPLY on that init message and keep doing it on every message comes after if person clicks button.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/42913607/169619759-21efcf29-774d-44d2-b62b-f173015e94fd.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/42913607/169619782-74fcce53-49d5-405b-a765-818d82bc0c59.png">

But if i will send init message not just in groups, but to a bot directly - this problem will not be shown ONLY IN BOT CHAT, NOT IN GROUP I WANT TO MANAGE.
      
      @bot.message_handler(commands=['start'])
          def start(message):
              bot.send_message(BOT_CHAT_ID, 'BOT CHAT START', reply_markup=service.createDefaultMarkup())
              bot.send_message(CHAT2_ID, 'CHAT2 START', reply_markup=service.createDefaultMarkup())

<img width="610" alt="image" src="https://user-images.githubusercontent.com/42913607/169620010-7906f84e-5afa-4a02-b2bc-32e1c8ed77fa.png">
<img width="618" alt="image" src="https://user-images.githubusercontent.com/42913607/169620049-ffca1d53-f798-4701-9bc8-2b019c38de00.png">

I need a behavior when users in groups will not reply to a message, just click the button -> logic proceeds -> info message sends to group.
And i have this behavior in bot chat directly.

Is this an issue? 
If not, how can i avoid it? 
I cant use InlineKeyboardMarkup, only ReplyKeyboardMarkup.

**Comment by Badiboy** [comment]
ReplyKeyboardMarkup is as stupid as a lug. The only thing it does when clicking a button - just send the message with button text. Nothing else. And the only way for your bot to proceed it - monitor all incomming messages and look for button texts there.

If you want 
click the button -> logic proceeds -> ...
InlineKeyboardMarkup is the only way.

**Comment by ksnow-be** [comment]
> If you want 
> 
> click the button -> logic proceeds -> ...
> 
> InlineKeyboardMarkup is the only way.

@Badiboy that's not a problem I am talking about. Look at the pics attached. The problem is that for some reason bot forces people to reply on a particular message, which he should not do. 
ReplyKeyboardMarkup in send_message method should just provide the buttons. But here I have reply_to behavior, but I never called it.

I know difference between inline/reply markups, I use prepared strings for a buttons texts and not handle those with 0 problems. 

Problem is it is ALWAYS "reply" to message bot sends with reply_markup property ONLY in groups.

**Comment by Qnetis** [comment]
Hi, I ran into the same error. The third day I'm looking for an answer. Please tell us how the problem was solved
