### ISSUE TITLE
Recent changes: May 6, 2016

### ISSUE THREAD

**Issue by ufuran** [eternnoir/pyTelegramBotAPI#156]
- Added the field emoji to the Sticker object. Your bot can now know the emoji a sticker corresponds to.
- Added the field forwarded_from_chat to the Message object for messages forwarded from channels.

When you add this?

**Comment by eternnoir** [comment]
Check https://github.com/eternnoir/pyTelegramBotAPI/pull/157 . Thanks @Kondra007
