### ISSUE TITLE
Send message from Inline Button Web Apps to bot

### ISSUE THREAD

**Issue by TSecretT** [eternnoir/pyTelegramBotAPI#1563]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.5.1

2. What OS are you using?
macOS

3. What version of python are you using?
3.10.2

Telegram docs mention that answerWebAppQuery method can be used to send messages on behalf of the user to the bot. Although Im not sure how exactly this method should be used. I get web_app_query_id from the telegram JS object, but where do I get InlineQueryResultBase? Ideally, I want my telegram bot to be acting like a backend and respond to messages sent from the web app. 

I assume answerWebAppQuery should be called from another instance (some JS telegram library, for example)?

**Comment by TECH-SAVVY-GUY** [comment]
Here's are some examples on how to implement Web Apps using this library. Hope it helps.

https://github.com/TECH-SAVVY-GUY/telegram-web-apps
