### ISSUE TITLE
Unable to use photo with Pillow without saving it.

### ISSUE THREAD

**Issue by tusharhero** [eternnoir/pyTelegramBotAPI#1572]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.5.1

2. What OS are you using? Garuda

3. What version of python are you using? 3.10.4

How to use the image with PIllow without saving it?

**Comment by Badiboy** [comment]
> Unable to use photo

> How to use

What is exactly the issue? **Unable** or **how**?

**Comment by tusharhero** [comment]
Nevermind fixed it.
