### ISSUE TITLE
Redis storage for data

### ISSUE THREAD

**Issue by BigDanTheOne** [eternnoir/pyTelegramBotAPI#1578]
Hello!
Why doesn't StateRedisStorage work with data, only with states? I'm using AsyncTeleBot and Heroku and such a feature would be very helpful to me.

**Comment by Badiboy** [comment]
Because it's created specially for states. Isn't it mentioned in its name?

https://github.com/eternnoir/pyTelegramBotAPI/discussions/1570

**Comment by BigDanTheOne** [comment]
Sorry for reopening the issue, but other types of async storages (StateMemoryStorage, StatePickleStorage) support storing data. Moreover, StateRedisStorage also has methods which are supposed to operate with data: get_data, set_data, get_interactive_data. 
I may continue in the discussion, but I think the topic of it is a little bit different.

**Comment by coder2020official** [comment]
You can save the data in any storage. But this classes are made not for storing data, they are actually made only for states. You shouldn't use them by default.

**Comment by Badiboy** [comment]
Okay, what exactly "doesn't StateRedisStorage work with data" means?

**Comment by BigDanTheOne** [comment]
1)In the description of the class it is written:
 "This class is for Redis storage.
    This will work only for states.
    To use it, just pass this class to:
    TeleBot(storage=StateRedisStorage())"
 2)When I try to use it for storing data like this:
```
storage = StateRedisStorage()
...
async with storage.get_interactive_data(chat_id, tg_id) as data:
        data["abc"] = "cde"
```
something goes wrong and it does not actually save data. 
But when I change `StateRedisStorage()` on `StatePickleStorage()` or `StateMemoryStorage()` (and nothing else) everything works correctly what means that the problem is connected with Redis storage only.

**Comment by coder2020official** [comment]
Please provide the code to reproduce it

**Comment by coder2020official** [comment]
Are you still struggling with it?
