### ISSUE TITLE
Doubt using InlineQueryResultPhoto

### ISSUE THREAD

**Issue by KingRotiv** [eternnoir/pyTelegramBotAPI#1579]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?  4.5.1

2. What OS are you using? Windows 10

3. What version of python are you using? 3.9.7

I'm using InlineQueryResultPhoto to show results that are fetched in my database, but when I try to show the title and description they don't appear anywhere, only the thumbnail and the image are shown. 

I expected that when defining the title and description, the InlineQueryResultPhoto would look like the InlineQueryResultArticle but its operation would remain the same, as I've seen it used this way in other projects. 

Is there any way to do this here?

**Current results:**
![Screenshot_20220612-192419](https://user-images.githubusercontent.com/12433702/173262545-536d41ad-01b4-4279-aa93-51206087cb13.png)

**Expected outcome:**
![Screenshot_20220612-002206](https://user-images.githubusercontent.com/12433702/173262551-1aee8039-9ca2-4eb8-bba3-3347507e3e29.png)

**Comment by coder2020official** [comment]
I think you should you should use [InlineQueryResultArticle](https://core.telegram.org/bots/api#inlinequeryresultarticle), by setting thumb_url. I am not sure, but let's try.

**Comment by KingRotiv** [comment]
> I think you should you should use [InlineQueryResultArticle](https://core.telegram.org/bots/api#inlinequeryresultarticle), by setting thumb_url. I am not sure, but let's try.

Doing it this way I got the expected result in the part that shows what the search returned, but as InlineQueryResultArticle works differently from InlineQueryResultPhoto it doesn't meet my need after that. 

I need that after I choose the result it sends an image with a caption and an inline menu, but I can only send an image using InlineQueryResultPhoto. 

I've seen this being used in a project, but I couldn't find anything about it either in the Telegram API or here. After I contacted the developer he told me that he uses pyrogram and that he has a specific parameter to make this possible in the answer_inline_query, just passing is_galerry=False. 

Would there be any possibility of this being added or is it outside the essence of the project functions not specified in the API?

**Comment by Badiboy** [comment]
> I'm using InlineQueryResultPhoto to show results that are fetched in my database, but when I try to show the title and description they don't appear anywhere, only the thumbnail and the image are shown.

Code example?

If you are doing all right - the result will depend on client behaviour.

**Comment by KingRotiv** [comment]
> > I'm using InlineQueryResultPhoto to show results that are fetched in my database, but when I try to show the title and description they don't appear anywhere, only the thumbnail and the image are shown.
> 
> Code example?
> 
> If you are doing all right - the result will depend on client behaviour.

# **pyTelegramBotApi**

```
import telebot
from telebot.types import (
	InlineKeyboardMarkup,
	InlineKeyboardButton,
	InlineQueryResultArticle,
	InlineQueryResultPhoto,
	InputTextMessageContent
)


bot = telebot.TeleBot(TOKEN)


def markup_search():
	markup = InlineKeyboardMarkup(
		[
			[
				InlineKeyboardButton(
					"Search",
					switch_inline_query_current_chat=""
				)
			]
		]
	)
	return markup
	

@bot.inline_handler(func=lambda query: query.query)
def return_search(query):
	
	title = "Wall-e"
	text = """<b>Filme:</b> Wall-e\n<b>Ano:</b> 2008
	\n<b>Gênero(s):</b> Animação\n\n<b>Sinopse:</b>
	 Aqui esgá escrito uma sinopse.
	 """
	img = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxYd3qWb7UlM_UBeis23ZV3SHzJpNy9-aBeScMnEzLHO1zc0wD"
	
	obj = [
		InlineQueryResultPhoto(
			"1",
			img,
			img,
			title=title,
			description=text,
			caption=text,
			parse_mode="html"
		)
	]
	bot.answer_inline_query(query.id, obj)

	
@bot.message_handler(func=lambda m: m.text)
def my_handler(message):
    bot.reply_to(
    	message,
    	"Welcome",
    	reply_markup=markup_search()
    )


bot.infinity_polling()
```

### Result: 

https://user-images.githubusercontent.com/12433702/173345034-31e2e0a7-44f5-47f0-a6fb-d60b1d58406f.mp4




# **pyrogram**

```
from pyrogram import Client
from pyrogram.types import (
	InlineKeyboardMarkup,
	InlineKeyboardButton,
	InlineQueryResultArticle,
	InlineQueryResultPhoto,
	InputTextMessageContent
)


app = Client(CONFIG)

	
def markup_search():
	markup = InlineKeyboardMarkup(
		[
			[
				InlineKeyboardButton(
					"Search",
					switch_inline_query_current_chat=""
				)
			]
		]
	)
	return markup
	

@app.on_inline_query()
def return_search(client, query):
	
	title = "Wall-e"
	text = """<b>Filme:</b> Wall-e\n<b>Ano:</b> 2008
	\n<b>Gênero(s):</b> Animação\n\n<b>Sinopse:</b>
	 Aqui esgá escrito uma sinopse.
	 """
	img = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxYd3qWb7UlM_UBeis23ZV3SHzJpNy9-aBeScMnEzLHO1zc0wD"
	
	obj = [
		InlineQueryResultPhoto(
			img,
			img,
			title=title,
			description=text,
			caption=text
		)
	]
	client.answer_inline_query(query.id, obj)

	
@app.on_message()
async def my_handler(client, message):
    await message.reply(
    	"Welcome",
    	reply_markup=markup_search()
    )


app.run()
```
### Result:

https://user-images.githubusercontent.com/12433702/173345333-2a6b2cf1-4b1e-4de6-8c98-7dd48e99fe84.mp4

**Comment by KingRotiv** [comment]
I thought it might be something outside the Telegram API. But thinking about it, it doesn't make sense to have the possibility to pass the title and description parameters in InlineQueryResultPhoto and it just doesn't show. Now it seems to me more of a problem in pyTelegramBotApi itself.

**Comment by coder2020official** [comment]
Looks interesting. I tested myself the code you provided for pyTelegramBotAPI. I will continue my investigations

**Comment by KingRotiv** [comment]
> Looks interesting. I tested myself the code you provided for pyTelegramBotAPI. I will continue my investigations  

I look forward to new information on the subject. Thanks.

**Comment by coder2020official** [comment]
Looks like this is not possible using bot api..

**Comment by coder2020official** [comment]
You can use InlineQueryResultArticle, it will give the same result, but as you said, it won't send the photo..

**Comment by KingRotiv** [comment]
The interesting thing is that the Telegram API itself demonstrates that it has the possibility of this by showing the parameters in the documentation. I realized that using in pyTelegramBotApi really the fields title and description are passed but there is no usage by the client side.

**Comment by emibonezzi** [comment]
Having the same problem... Using InlineQueryResultPhoto and passing these params:

`{
              type: 'photo',
              id: tweet.id_str,
              photo_url: `${tweet.entities.media[0].media_url_https}`,
              thumb_url: `${userProfilePic_small}`,
              title: `${user.name}`,
              caption: `\n[${user.name}] - [@${user.screen_name}]\n\n${tweet.full_text}`,
            }`

and it only shows the thumbnail without caption and title in the result. pretty annoying.

![0AFE5C61-01C9-468E-8DA7-F68E5010CF69_1_201_a](https://user-images.githubusercontent.com/111168037/205380241-0ce0e13e-029b-4752-8de5-c06313da4da1.jpeg)

**Comment by KingRotiv** [comment]
> Having the same problem... Using InlineQueryResultPhoto and it only shows the thumbnail without caption and title in the result. pretty annoying. Did anybody manage to solve this?
> 
> ![0AFE5C61-01C9-468E-8DA7-F68E5010CF69_1_201_a](https://user-images.githubusercontent.com/111168037/205380241-0ce0e13e-029b-4752-8de5-c06313da4da1.jpeg)



> Having the same problem... Using InlineQueryResultPhoto and it only shows the thumbnail without caption and title in the result. pretty annoying. Did anybody manage to solve this?
> 
> ![0AFE5C61-01C9-468E-8DA7-F68E5010CF69_1_201_a](https://user-images.githubusercontent.com/111168037/205380241-0ce0e13e-029b-4752-8de5-c06313da4da1.jpeg)

I haven't found a solution. I ended up using another function. If I remember correctly the data was sent but the client did not display it.
