### ISSUE TITLE
How to make the bot reply to a group of photos (MediaGroup) with one message?

### ISSUE THREAD

**Issue by tenshi911** [eternnoir/pyTelegramBotAPI#1581]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.5.1

2. What OS are you using? Windows 10 Pro 21H2

3. What version of python are you using? 3.10.4

```
import telebot


bot = telebot.TeleBot('API_TOKEN')

@bot.message_handler(content_types=['photo'])
def on_message(message):
    bot.send_message(message.chat.id, "test")

bot.infinity_polling()
```
    
when bot receives multiple photos (Mediagroup), it handles every photo alone. so if user send album with 3 photos for example, the bot will the send the message 3 times.
How to make it handle the Mediagroup message as one message and return only one message rather than a message for every photo.
preview:
https://i.imgur.com/4KEQyGb.png

**Comment by mrgetkit** [comment]
# you can solve this problem by a simple Boolean 

`
import telebot
import time

bot = telebot.TeleBot("API_TOKEN")

sending = False
@bot.message_handler(content_types=['photo'])
def on_message(message):
    global sending
    if sending == False :
        sending = True
        bot.send_message(message.chat.id,"hello")
        time.sleep(0.5)
        sending = False

bot.infinity_polling()
`

**Comment by tenshi911** [comment]
Problem solved, thank you very much!
