### ISSUE TITLE
Writing e2e tests

### ISSUE THREAD

**Issue by TSecretT** [eternnoir/pyTelegramBotAPI#1601]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.5.1

2. What OS are you using?
macos

3. What version of python are you using?
3.10.4

Hi, I would like to write some e2e tests with the bot logic that I have. To keep it simple, assume:

on /start command, bot checks if the user id is in the custom database (mongo) and depending on that sends the message "Authed" or "Not Authed"

I have checked the tests in the current repository but they are more for testing telegram API and not for function. Thank you for your help!

**Comment by coder2020official** [comment]
Hello.
Looks like you are new. Check out the examples folder for more.
You should create a handler with custom filter that checks your db, or instead of custom filter you should directly check the db in your handler.

**Comment by coder2020official** [comment]
Any news?

**Comment by Badiboy** [comment]
This is not an issue. Try in discussions if you want to.
