### ISSUE TITLE
Ban users

### ISSUE THREAD

**Issue by carasino007** [eternnoir/pyTelegramBotAPI#1609]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.6.0
2. What OS are you using?
windows 7
3. What version of python are you using?
3.8.10

The big question is: how add a user a the blacklist if this user never enter in my group?
or 
how ban a user if this user never enter in my group?
i try this: 
 _bot.ban_chat_member(chat_id='',user_id='')_
but return :  **('A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: PARTICIPANT_ID_INVALID',)**

**Comment by Badiboy** [comment]
This is not an issue. Try in discussions if you want to.

**Comment by Badiboy** [comment]
No way.

**Comment by carasino007** [comment]
> No way.

then what is the solution?

**Comment by Badiboy** [comment]
NO
WAY.

**Comment by carasino007** [comment]
I check for example hal9000 banned users and this users never enter in a group.

**Comment by carasino007** [comment]
> NO WAY.

I check for example hal9000 banned users and this users never enter in a group.

**Comment by EdwyReed** [comment]
Creating a variable with "blacklist" of users you don't want to join your group.
Creating a handler for checking every user that will join group in future. Check is new user in "blacklist". No? Nevermind, pass. Yes? Ban it.

**Comment by TECH-SAVVY-GUY** [comment]
Maybe this will help: https://gist.github.com/TECH-SAVVY-GUY/d6a2f1cbcd57aa4a5140cf95e110d9d2

**Comment by coder2020official** [comment]
@carasino007 I didn't get your question
@TECH-SAVVY-GUY no, it has nothing to do with this jssue.

**Comment by TECH-SAVVY-GUY** [comment]
> @TECH-SAVVY-GUY no, it has nothing to do with this issue.

I thought he's trying to block people from joining his group. Maybe he can use middleware handlers and check for new join updates and then directly ban them?

**Comment by carasino007** [comment]
> @carasino007no entendí tu pregunta @TECH-SAVVY-GUYno, no tiene nada que ver con este tema.

For example, you have a group in mode PUBLIC, but exist a scam with id user 123456 who writes to the users of the group to scam them, I want to prohibit that user from seeing the members of my group and not seeing the content of my group.
Since the scammer never joined my group, I can't ban him, the scammer doesn't have @user, he just has id:123456.
Then how ban this scammer?

**Comment by TECH-SAVVY-GUY** [comment]
@carasino007 

1. How does a user write in a group without joining it? 

2. You don't need the user name of the user. Just store his id, and store it somewhere. And whenever you see a message from that id, just delete it.

**Comment by carasino007** [comment]
> @carasino007
> 
>     1. ¿Cómo escribe un usuario en un grupo sin unirse a él?
> 
>     2. No necesita el nombre de usuario del usuario.  Solo guarda su identificación y guárdala en algún lugar.  Y cada vez que vea un mensaje de esa identificación, simplemente elimínelo

1.  I mean that it writes users to the private, it only checks who is in the group.

**Comment by TECH-SAVVY-GUY** [comment]
Oh, I see. So the scammer opens your group, sees your members and spams them directly in their private chats? 

Well, I don't think there's anything you can do about it apart from asking your members to report that account.

**Comment by carasino007** [comment]
> Ah, claro. Entonces, ¿el estafador abre su grupo, ve a sus miembros y los envía spam directamente en sus chats privados?
> 
> Bueno, no creo que haya nada que puedas hacer al respecto aparte de pedirles a tus miembros que denuncien esa cuenta.

yes it is the big problem, sometimes i ban this user of the group, but, theirs again write to the members in private and check new users in the group :(

**Comment by carasino007** [comment]
Another solution?
