### ISSUE TITLE
Bot doesn't answer after deploying app on Heroku

### ISSUE THREAD

**Issue by thebestmacone** [eternnoir/pyTelegramBotAPI#161]
I've created simple echo bot and it worked fine in terminal.
But after deploying it on Heroku bot doesn't answer on messages even simple /start and /help.
I'm using Flask app and index page opens ok with code 200, but bot is silent.
I've tried examples like webhook_flask_echo_bot.py from this repository, set webhooks manually
but nothing helps.
Can anybody help me?

**Comment by pevdh** [comment]
This might as well be an issue with Heroku. Are you sure you have configured the web hook properly, and are using HTTPS? Plain HTTP is not allowed.

**Comment by thebestmacone** [comment]
Of course I'm using https.

@app.route("/") 
def webhook():
	bot.remove_webhook()
	bot.set_webhook(url="https://mybotname.herokuapp.com/bot")
	return "!", 200

So, when I'm running command "heroku open" and app index page is loaded, web hook should be set?
How can I verify if it configured properly?

**Comment by pevdh** [comment]
Are you using a self-signed certificate? If that is the case, you must pass it as an argument:
`bot.set_webhook(url="...", certificate=open('my-certificate.pem'))`. See (here)[https://core.telegram.org/bots/self-signed] for a guide on how to create self-signed certificates. 

The "shitty" thing about webhooks is that they are so hard to debug, there is no "testWebhook" API call as of right now, unfortunately.

**Comment by thebestmacone** [comment]
Is it necessary to use self-signed certificate?

**Comment by pevdh** [comment]
No it is not necessary, but if you do have a signed certificate, you will have to upload the public key using the set_webhook call. That said, you could try creating a self signed certificate to check whether that would solve the issue.

**Comment by thebestmacone** [comment]
Thanks, I'll try.

**Comment by TommyJacket** [comment]
I know it's been almost a year now, but I ran into the same problem today. Did you solve it somehow?

**Comment by thebestmacone** [comment]
Sorry, but I've gave up with this issue. It was just unsuccessful experiment. I'm sure it's all about certificates. Please, let me know if you find out the answer. Thanks a lot and have a good luck.

**Comment by chekan-o** [comment]
At Heroku and AWS Lambda bot will not work with threading as it is not supported bu platform.
By default bot is starting with trading enabled. Once you disabled threading it works just fine:
`bot = telebot.TeleBot(bot_token, threaded=False)`

**Comment by alexzaitsev** [comment]
@chekan-o awesome! It helped me to make it working on the AWS. Thanks!
