### ISSUE TITLE
Issue with answer_inline_query

### ISSUE THREAD

**Issue by AlexandrErofeevsky** [eternnoir/pyTelegramBotAPI#1615]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.1

2. What OS are you using?
Windows 10 64

3. What version of python are you using?
Python 3.7.1

I'm trying to use bot.inline_handler, the answer is assembling about 20 sec, then I use answer_inline_query

According to documentation, cache_time is 5 minutes, and this is much more, than assembling time, nonetheless bot throws an error: 
A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: query is too old and response timeout expired or query ID is invalid

**Comment by coder2020official** [comment]
Hello!
You are answering to old query. As you said, it takes around 20 seconds to answer, and during those 20 seconds callback data id becomes invalid.

**Comment by AlexandrErofeevsky** [comment]
Thanks for your answer! Are there some ways to answer to the user after 20 sec waiting?

**Comment by coder2020official** [comment]
Probably no

**Comment by AlexandrErofeevsky** [comment]
And the last one. Don't you know the time window in which answer is not to old?

**Comment by coder2020official** [comment]
Probably around 5-10 seconds, I don't know the exact time.
