### ISSUE TITLE
Keyboards: "markup.add()" creates new row instead just adding 

### ISSUE THREAD

**Issue by denis-d** [eternnoir/pyTelegramBotAPI#1616]
Bug is back, using 4.6.0. it creates new row every time no matter what row_width is.

_Originally posted by @denis-d in https://github.com/eternnoir/pyTelegramBotAPI/issues/183#issuecomment-1179777833_

**Comment by Badiboy** [comment]
Why you suppose it should add a button to the last row?

**Comment by coder2020official** [comment]
Bug is not back, and it is not a bug. It is a proper behaviour of the buttons. Please read the answer written by pevdh.

**Comment by denis-d** [comment]
If you mean https://github.com/eternnoir/pyTelegramBotAPI/issues/183#issuecomment-224383386 it does not work as described.
It lists all buttons in one column.

**Comment by Badiboy** [comment]
@denis-d markup.add is working as it is working. If you need to add a key to the last (or any) row - get the appropriate row and add button to it.
`markup.keyboard[desired_row].add(your_button)`

**Comment by coder2020official** [comment]
We should add a function to do this ig

**Comment by denis-d** [comment]
Main problem is then you unable to predict how much buttons and rows wiil be.
As example i want to parse directories and list them as a buttons no more then 3 in a row.
I've tried workaround but in makes all in one row instead
`@bot.message_handler(commands=['list'])
def start(message):
    cwd = os.getcwd()
    row=[]
    with os.scandir(cwd) as it: 
        for entry in it:
            if not entry.name.startswith('.') and entry.is_dir():
                row.append(telebot.types.InlineKeyboardButton(entry.name, callback_data=entry.name))
        menu = telebot.types.InlineKeyboardMarkup([row], row_width=2)
        bot.send_message(message.chat.id, text=cwd, reply_markup=menu)`

**Comment by coder2020official** [comment]
Take a look at telebot.util.quick_markup:
`quick_markup({
        'Twitter': {'url': 'https://twitter.com'},
        'Facebook': {'url': 'https://facebook.com'},
        'Back': {'callback_data': 'whatever'}
    }, row_width=2):`

**Comment by Badiboy** [comment]
`menu = telebot.types.InlineKeyboardMarkup(*row, row_width=2)`

Be happy. :)

**Comment by Badiboy** [comment]
(updated)
