### ISSUE TITLE
Inline query always answers "default".

### ISSUE THREAD

**Issue by MrCheatEugene** [eternnoir/pyTelegramBotAPI#1625]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.6.0
2. What OS are you using?
Ubuntu 18.04 x86_64
3. What version of python are you using?
3.9.0

Hi. I have a problem. I am trying to write a inline bvot, that responds to command.
I've taken this(https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/inline_example.py) example, and modified it a little bit. 

That's what I got:
```
import logging
import sys
import time

import telebot
from telebot import types

API_TOKEN = 'TOKEN'

bot = telebot.TeleBot(API_TOKEN)
telebot.logger.setLevel(logging.DEBUG)


@bot.chosen_inline_handler(func=lambda chosen_inline_result: True)
def test_chosen(chosen_inline_result):
    # Process all chosen_inline_result.
    try:
        r = types.InlineQueryResultArticle('1', 'title of the result', types.InputTextMessageContent(message_text ='hello!'))
        print(r)
        bot.answer_inline_query(inline_query.id, [r])
    except Exception as e:
        print(e)

def main_loop():
    bot.infinity_polling()
    while 1:
        time.sleep(3)


if __name__ == '__main__':
    try:
        main_loop()
    except KeyboardInterrupt:
        print('\nExiting by user request.\n')
        sys.exit(0)
```
But, it always responds "default" to inline command "default."
Why does that happen? What I am doing wrong?

**Comment by Badiboy** [comment]
"inline_query" - what's that?

**Comment by MrCheatEugene** [comment]
> chosen_inline_handler - is the action when the user selected one of the given results. You should send message or like that.
> 
> Nothing to answer via answer_inline_query - it's when user ask inline question...

Ok, but how can I send message/reply to an inline command?

Can you give me some example?

**Comment by MrCheatEugene** [comment]
> > bot.answer_inline_query(inline_query.id, [r])
> 
> "inline_query" - what's that?

I was trying to get it working by try & error, and was not passing much attention to the parts that I was removing
Ooops:)
