### ISSUE TITLE
Just a question for getUpdates()

### ISSUE THREAD

**Issue by DullJZ** [eternnoir/pyTelegramBotAPI#1628]
In official docs, we should set a Webhook or use bot.getUpdates() to get the latest message manually to handle it. 

Thanks to your efforts, bot.polling() working with some 
decorators seems to solve the problem. And it's needless to set a keep-running program to get new messages, and call the handler function by myself, do I say right?

**Comment by Badiboy** [comment]
Just check examples. 

Not an issue, continue in discussions if you want to.
https://github.com/eternnoir/pyTelegramBotAPI/discussions
