### ISSUE TITLE
cannot add bot buttons with emoji as unicode...

### ISSUE THREAD

**Issue by Baylung** [eternnoir/pyTelegramBotAPI#164]
Before upgrading to pyTelegramBotAPI 2.1.1 my keyboard with emoji-buttons was working good:

```
all_lang_markup = types.ReplyKeyboardMarkup( resize_keyboard=True )
all_lang_markup.add( u'\U0001F1EC', u'\U0001F1F7')   # English and Russian Emoji Flags

```
After upgrating to pyTelegramBotAPI 2.1.1 (pip install pyTelegramBotAPI -U) bot cannot be launched with and followin error raised:

```
File "/usr/local/lib/python2.7/dist-packages/telebot/types.py", line 559, in add
    row.append(button.to_dic())
AttributeError: 'unicode' object has no attribute 'to_dic'
```

Please check..

How can i add keyboard button containing Emoji icons in  pyTelegramBotAPI 2.1.1 ?

PS. Thank you for pyTelegramBotAPI - the best library interface to Telegram bot API !

**Comment by pevdh** [comment]
[Line 577 in types.py](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/types.py#L577) should be `util.is_string(button)` instead of `isinstance(button, str)`. Will fix later, this day, thanks for the issue.

**Comment by sagosS** [comment]
t = b'\xF0\x9F\x98\x81'.decode('utf-8')
one = types.InlineQueryResultArticle('1', thunderstorm + 'default', types.InputTextMessageContent('one'))
