### ISSUE TITLE
Exception Handler error? 

### ISSUE THREAD

**Issue by f48al** [eternnoir/pyTelegramBotAPI#1641]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.10
2. What OS are you using?
Windows 10
3. What version of python are you using?
Python 3.10

![IMG_20220722_173525_573](https://user-images.githubusercontent.com/31438208/180421890-a030c6fe-133a-4a31-903e-c9696518c22d.jpg)

Hello i want to ask what happened with this exception_handler? since i updated version to the newest of PyTelegramApi it becomes error " can only concantenate list (not "int") to list " can u tell me what is wrong? thx

**Comment by coder2020official** [comment]
1. Is it github version?
2. Exactly at what stage are you getting this error?

**Comment by f48al** [comment]
> 1. Is it github version?
> 2. Exactly at what stage are you getting this error?

1. yes, is it github version
2. when i want to send message using Exception

**Comment by coder2020official** [comment]
Can you show your code?

**Comment by f48al** [comment]
> Can you show your code?

can i have ur personal account? like telegram account so i can show you my code

**Comment by coder2020official** [comment]
Just search me by my git username but without 'official' part.

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/180483959-867e4413-4dfe-4eb2-af84-28cc819b8d36.png)

The error is in your code. This file. Line 22.

**Comment by f48al** [comment]
> ![image](https://user-images.githubusercontent.com/5613421/180483959-867e4413-4dfe-4eb2-af84-28cc819b8d36.png)
> 
> The error is in your code. This file. Line 22.

nope dude, my line 22 is only handler code class like this

class (telebot.ExceptionHandler):
    def handle(self, exception):
        logger.error(exception)

**Comment by f48al** [comment]
solved
