### ISSUE TITLE
Troubles sending image in inline mode.

### ISSUE THREAD

**Issue by BigDanTheOne** [eternnoir/pyTelegramBotAPI#1642]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.6.0
2. What OS are you using?
Mac Os
3. What version of python are you using?
3.7.11

Hello, I'm using inline bot and trying to print a photo, which is already on a telegram server. But when I pass it's file id
`id = 'AgACAgIAAxkBAAIkc2LB6mYy0GnZBzKTXuxG_2qCaQAB2wACkr4xG8AuEEqrRCYAAUPEFEMBAAMCAANzAAMpBA'
`
to either `InlineQueryResultCachedPhoto`  like
```
types.InlineQueryResultCachedPhoto('2', photo_file_id=id, title='title', description='description', caption='caption')
```
or `InlineQueryResultPhoto` like
```
types.InlineQueryResultPhoto('2', photo_url=id, thumb_url=id, title='title', description='description', caption='caption')
```
I get "Untitled" instead of the description
<img width="329" alt="image" src="https://user-images.githubusercontent.com/45150310/180481104-c70a7c0d-5b99-4f6d-a8db-4b0836b4035e.png">

But when I pass a random url from the web everything works as expected:
<img width="227" alt="image" src="https://user-images.githubusercontent.com/45150310/180481722-9c64f20f-b269-4fa9-9db2-261b0c954480.png">
What should I do to fix this?

**Comment by coder2020official** [comment]
Can you please provide whole code to reproduce this issue?

**Comment by BigDanTheOne** [comment]
```
@tb.inline_handler(lambda query: query.query)
async def query_text(inline_query):
        r1 = types.InlineQueryResultArticle('1', 'Result', types.InputTextMessageContent('Result message.'))
        r2 = types.InlineQueryResultArticle('2', 'Result2', types.InputTextMessageContent('Result message2.'))
        id='AgACAgIAAxkBAAIkc2LB6mYy0GnZBzKTXuxG_2qCaQAB2wACkr4xG8AuEEqrRCYAAUPEFEMBAAMCAANzAAMpBA' 
        r3 = types.InlineQueryResultCachedPhoto('3', photo_file_id=id, 
                                          title='title', description='description', caption='caption')
        await tb.answer_inline_query(inline_query.id, [r1, r3, r2], cache_time=0)
   
```

**Comment by coder2020official** [comment]
You should pass a title for InlineQueryResultArticle objects.
https://core.telegram.org/bots/api#inlinequeryresultarticle

**Comment by BigDanTheOne** [comment]
@coder2020official 
But if I  pass a title to InlineQueryResultPhoto and a random url from the web everything works fine
```
@tb.inline_handler(lambda query: query.query)
async def query_text(inline_query):
        r1 = types.InlineQueryResultArticle('1', 'Result', types.InputTextMessageContent('Result message.'))
        r2 = types.InlineQueryResultArticle('2', 'Result2', types.InputTextMessageContent('Result message2.'))
        url = 'https://kudago.com/media/images/event/1a/f1/1af1f99cdcfe824ddd8e9ffb14afde8b.jpg'
        r3 = types.InlineQueryResultPhoto('3', photo_url=url, thumb_url=url,
                                          title='title', description='description', caption='caption')
        await tb.answer_inline_query(inline_query.id, [r1, r3, r2], cache_time=0)
```
<img width="355" alt="image" src="https://user-images.githubusercontent.com/45150310/180489911-4dc6631b-775e-4c23-b771-11f5bd71592f.png">

**Comment by coder2020official** [comment]
I didn't get your issue. You should always pass title cuz it is not optional.

**Comment by BigDanTheOne** [comment]
>You should always pass title cuz it is not optional.
Yes, sure.
>I didn't get your issue
Don't you have "Untitled" passing id of a photo stored on the Telegram servers (not a random url from the web) to InlineQueryResultCachedPhoto? Do you get your title?

**Comment by coder2020official** [comment]
So you are having untitled title for random image from internet?

**Comment by BigDanTheOne** [comment]
> So you are having untitled title for random image from internet?

No. For a  random image from internet everything is ok. I have untitled only for an image stored on the Telegram servers

**Comment by coder2020official** [comment]
![image](https://user-images.githubusercontent.com/63740404/181040282-d12b48ce-ef3f-4326-a52d-5c6854ebec74.png)
Here is the output when i run your code. The title isn't displayed, only image is displayed.

**Comment by coder2020official** [comment]
Still struggling?

**Comment by BigDanTheOne** [comment]
No, thanks a lot.

**Comment by PraryDogy** [comment]
> 
Solution?
