### ISSUE TITLE
How do I send a message to a group at a specific time?

### ISSUE THREAD

**Issue by victorodev** [eternnoir/pyTelegramBotAPI#1645]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? The most recent

2. What OS are you using? To develop is the windows, but i'm using heroku to deploy it to telegram

3. What version of python are you using? Python 3

**Comment by coder2020official** [comment]
Schedule using external schedulers, and pass your group id to send_message function.
For questions next time use 'discussions'.

**Comment by victorodev** [comment]
Ok, i'll try that, thanks!
