### ISSUE TITLE
Missing field message_auto_delete_timer_changed

### ISSUE THREAD

**Issue by 108ddy** [eternnoir/pyTelegramBotAPI#1647]
In my project I want to make that after sending a message it can be auto-deleted after some time. But if I'm not mistaken in `types.Message` is missing field: `message_auto_delete_timer_changed` in initialize.

PS: sorry if I misunderstood something and for my english

**Comment by coder2020official** [comment]
Confirmed

**Comment by coder2020official** [comment]
![image](https://user-images.githubusercontent.com/63740404/181242825-c06137b9-4e1a-42a4-8485-805368bd650c.png)
No, it has

**Comment by 108ddy** [comment]
Oh, sorry, I thought that it needed to be in `__init__` method too.
