### ISSUE TITLE
@bot.message_handler() not working properly with non-text message in group/channels

### ISSUE THREAD

**Issue by LoicRcp** [eternnoir/pyTelegramBotAPI#1648]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
          4.6.0 
2. What OS are you using?
           WINDOWS 10
3. What version of python are you using?
           Python 3.8.5

The `@bot.message_handler()` does not get update when anything other than text is sent to a group or channel.

The bot is admin in both group and channel. When a text-message in sent in those group/channel, the `@bot.message_handler(func=lambda m: True)` handler receive the message properly. 

But when it is a photo, a video, a document, anything else, nothing happen.

**Comment by coder2020official** [comment]
For channels, you should use channel_post_handler.
For groups, you should set content_types.
By default, if you don't set content_types, it will only handle text messages
