### ISSUE TITLE
message.html_text cannot return correct result

### ISSUE THREAD

**Issue by ImJoke** [eternnoir/pyTelegramBotAPI#1650]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.6.1
2. What OS are you using? Windows 10
3. What version of python are you using? Python 3.10.5

### So I typed qwertyuiop with bold, italic and underline formatting, but only bold came back

![image](https://user-images.githubusercontent.com/55929550/181996718-26458d8e-a38a-4dd8-90ce-708f044ab46c.png)
![image](https://user-images.githubusercontent.com/55929550/181996736-c6438db3-995a-415b-906f-e58912572701.png)

**Comment by Badiboy** [comment]
Only pure formatting (either bold, or italic, or etc...) supported. Nested formatting is not supported yet.

**Comment by coder2020official** [comment]
I will investigate

**Comment by coder2020official** [comment]
Btw, you can use [copy_message](https://pytba.readthedocs.io/en/latest/async_version/index.html#telebot.async_telebot.AsyncTeleBot.copy_message) for copying such messages

**Comment by rodrigobg** [comment]
bot = telebot.TeleBot(api_key, parse_mode=html) Error 400 Bad Request, parse mod dont work from Telegram api.
Your package ins conflict with telebot 0.0.4 python pip.

**Comment by Badiboy** [comment]
> parse_mode=html
parse_mode = "HTML"

> Your package ins conflict with telebot 0.0.4 python pip.
It is. And?
