### ISSUE TITLE
an error with AsyncTeleBot - Aiohttp ClientError: ServerDisconnectedError

### ISSUE THREAD

**Issue by nitrofoska-g** [eternnoir/pyTelegramBotAPI#1664]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 4.6.1

2. What OS are you using?
Ubuntu Server 16.0.4 LTS

3. What version of python are you using?
Python 3.8.1

Hi there, im having this issue in the lasted days:

`2022-08-12 10:45:37,075 (asyncio_helper.py:80 MainThread) ERROR - TeleBot: "Aiohttp ClientError: ServerDisconnectedError"
2022-08-12 10:45:37,075 (async_telebot.py:317 MainThread) ERROR - TeleBot: "Request timeout. Request: method=get url=getUpdates params=<aiohttp.formdata.FormData object at 0x7f60fcf77610> files=None request_timeout=None"
2022-08-12 10:45:37,076 (async_telebot.py:276 MainThread) ERROR - TeleBot: "Infinity polling: polling exited"
2022-08-12 10:45:37,076 (async_telebot.py:278 MainThread) ERROR - TeleBot: "Break infinity polling"`

The code works fine for a few hours and then that error appears shutting down the bot.
I have updated asyncio and aiohttp too.
I was researching about catching the exception aiohttp.ClientConnectionError which is a base class that ServerDisconnectedError but no success so far.

**Comment by coder2020official** [comment]
Hello.
These 2-3 days api had erros due to change in config of nginx. Server has disconnected due to 502 errors, so now this error shouldn't be raised.
If you want your bot to continue it's work, you should pass non_stop=True to infinity_polling.

**Comment by coder2020official** [comment]
I had the same issue yesterday - or the day before yesterday.

**Comment by nitrofoska-g** [comment]
Thanks! I'll try with non_stop flag.
