### ISSUE TITLE
parse_mode?

### ISSUE THREAD

**Issue by Antxj** [eternnoir/pyTelegramBotAPI#1687]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.7.0

4. What OS are you using?
Heroku, Linux, deploy.
Pycharm, Win11, coding.

6. What version of python are you using?
3.10

Code:

I don't know why, but parse_mode is not "active".

```
@bot.message_handler(commands=['start'])
def send_welcome(message):
    bot.send_message(message.chat.id, f"Bem-vindo(a) {message.from_user.username}!")
    bot.send_message(message.chat.id, text="<a href='https://www.google.com/'>Google</a>", parse_mode=HTML)
    bot.send_message(message.chat.id, text="[Google](https://www.google.com/)", parse_mode=markDown)
```
![image](https://user-images.githubusercontent.com/92764157/186697993-cceb0a2f-228e-4fbb-8999-eb73dd415dd5.png)

**Comment by Badiboy** [comment]
parse_mode="HTML"

**Comment by Antxj** [comment]
It worked. Thanks!

Sorry for my stupidity.
