### ISSUE TITLE
message.entities.user is always empty

### ISSUE THREAD

**Issue by LuGGuSS** [eternnoir/pyTelegramBotAPI#1698]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.7.0

2. What OS are you using?
win10

3. What version of python are you using?
3.9

Hello, I'm trying to get user id from mention (@user). But "user" field in mention entity is always empty.

**Comment by LuGGuSS** [comment]
Here are some screenshots:

![зображення](https://user-images.githubusercontent.com/90028497/188316857-b8a39a16-3c70-44bb-81b3-0089d7389b9c.png)
![зображення](https://user-images.githubusercontent.com/90028497/188316935-8dba77ad-adec-490e-8b4c-fb9b1cbe4458.png)

**Comment by coder2020official** [comment]
Hello! Thank you for report. Investigating it

**Comment by coder2020official** [comment]
![telegram-cloud-photo-size-2-5235956934081887926-x](https://user-images.githubusercontent.com/63740404/188317614-40652b14-2321-4ec9-a86f-dc5b1789b94a.jpg)
I got the result with user when I tagged a user with his id

**Comment by LuGGuSS** [comment]
That

> ![telegram-cloud-photo-size-2-5235956934081887926-x](https://user-images.githubusercontent.com/63740404/188317614-40652b14-2321-4ec9-a86f-dc5b1789b94a.jpg) I got the result with user when I tagged a user with his id

Strange. Mine is refusing to show up. Can it be due to privacy settings?

**Comment by coder2020official** [comment]
Maybe.

**Comment by byehack** [comment]
> Here are some screenshots:
> 
> ![зображення](https://user-images.githubusercontent.com/90028497/188316857-b8a39a16-3c70-44bb-81b3-0089d7389b9c.png) ![зображення](https://user-images.githubusercontent.com/90028497/188316935-8dba77ad-adec-490e-8b4c-fb9b1cbe4458.png)

Your `type` is `mention`.
`user` attribute only available if `type==text_mention`.

**Comment by sudoskys** [comment]
#1039 

`Telegram does not report you any user information when you use simple @name mention.`

**Comment by coder2020official** [comment]
Still struggling?

**Comment by LuGGuSS** [comment]
> Still struggling?


Hey, sorry, had no time to play with api. So, as I get it from sudosky's message - I don't receive user info due to tg api restrictions. Is there a way to get it without using tg core api? Because it'd make my project quite larger.
