### ISSUE TITLE
State not working on group

### ISSUE THREAD

**Issue by DovaSubs** [eternnoir/pyTelegramBotAPI#1699]
1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 4.7.0

2. What OS are you using?
Windows

3. What version of python are you using?
3.6.8

[custom_state](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/custom_states.py) works well on a private chat but it doesn't work in a group.

This is what happens when I run the code in a group:
![image](https://user-images.githubusercontent.com/88161251/188350158-dd86ae29-5c23-4f19-91f8-a15bee33e5d8.png)

I get no errors whatsoever. The bot keeps running normally, except the next step doesn't trigger.
Here's the same code running a private chat (expected behavior):
![image](https://user-images.githubusercontent.com/88161251/188350702-5b909c0f-e476-4bab-8e01-33566d0f0cab.png)

How can I run the code in a group?

**Comment by coder2020official** [comment]
Can you share your full code? i'll review it tomorrow

**Comment by coder2020official** [comment]
Ah yes, I forgot to tell that you should either make bot admin in the group, or turn off privacy in the group. That is the reason why bot is not working(not getting messages except commands)

**Comment by DovaSubs** [comment]
Hi @coder2020official thank you for your reply.
In fact the bot was not an admin and it didn't have access to messages. I gave it admin and now its status is "has access to messages" but [custom_states.py](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/custom_states.py) is still not working on my group. 
For now, I'm just running the sample code https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/custom_states.py because if the sample is not working on my group, my full code won't work either.

PS: I don't require to have a state for each user in the group, it's just a group of 3 people and it's fine if we all "share" state.

**Comment by magicarm22** [comment]
Got the same problem today. I have a group channel, and bot don't want to react to my messages. Bot has an access to read and write messages because I want to rewrite my code from `register_next_step_handler` to the states.

`@self.bot.message_handler(state='*')` works good, but `@self.bot.message_handler(state=CreateTaskStates.name)` doesn't work

**Comment by coder2020official** [comment]
I will think about this feature.

**Comment by coder2020official** [comment]
#1701 , everything was working before.
Btw, code for states need to be rewritten with more opportunity. I'll think about it

**Comment by coder2020official** [comment]
Try to install github version. I tested myself and got appropriate results. This issue should remain open
