### ISSUE TITLE
Escape characters for MarkdownV2

### ISSUE THREAD

**Issue by byehack** [eternnoir/pyTelegramBotAPI#1705]
![image](https://user-images.githubusercontent.com/26390254/189383447-5e671174-472d-4360-a7df-5246fd3426e6.png)

**Comment by coder2020official** [comment]
https://pytba.readthedocs.io/en/latest/formatting.html#telebot.formatting.escape_markdown

**Comment by coder2020official** [comment]
Next time please use discussions for suggestions
