### ISSUE TITLE
ModuleNotFoundError@examples

### ISSUE THREAD

**Issue by oeNrM** [eternnoir/pyTelegramBotAPI#1709]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
       4.7.0

3. What OS are you using?
       Linux Mint 20.3 x86_64

5. What version of python are you using?
       Python 3.8.10

**Error:**    `ModuleNotFoundError: No module named 'examples'`
at this example:
https://github.com/eternnoir/pyTelegramBotAPI/blob/4fd01e3ac81175411a46e0cb0b6be8962925c64a/examples/callback_data_examples/advanced_calendar_example/main.py#L9

![image](https://user-images.githubusercontent.com/33395636/189478029-7e363808-6978-4a4f-b886-daecc5bef0e4.png)

**Comment by coder2020official** [comment]
Just use from .keyboards import generate_calendar_days, \
This example was made for examples folder.
