### ISSUE TITLE
Register next step handler does not work on channels

### ISSUE THREAD

**Issue by hankertrix** [eternnoir/pyTelegramBotAPI#1712]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.7.0

2. What OS are you using?
Ubuntu 18.04.5 LTS (Bionic Beaver)

3. What version of python are you using?
3.7.10 and 3.8.12

<br>
<br>
<br>

Here is a snippet of the code that is being used to handle regular messages and channel posts
```
# Handles the /setversion command
@bot.channel_post_handler(commands=["setversion"])
@bot.message_handler(commands=["setversion"])
def handle_version(message: types.Message) -> None:

    # The content of the message behind the /setversion command
    msg_ctx = re.sub("/setversion ?", "", message.text.lower())

    # Checks if there is nothing behind the /setversion command
    if msg_ctx == "":

        # Sends the message to the user
        send_message(message.chat.id, "Please enter your bible version.")

        # Register the next step handler
        bot.register_next_step_handler(message, set_version)

    # If there is text written behind the /setversion command
    else:

        # Calls the set_version function
        set_version(message, msg_ctx)

# The function to read the user's message and save the new bible version given if it's accepted
def set_version(message: types.Message, ctx: str = "") -> None:

    # Checks if the context is not given
    if ctx == "":

        # Sets the version to the entire message given by the user
        version_given = message.text.upper().strip()

    # If the context is given
    else:

        # Sets the version to be the text behind the /setversion command
        version_given = ctx.upper().strip()

    # Gets the version from the version mapping
    version_given = version_map.get(version_given, version_given)

    # Gets the version list from the database
    version_list = db["chats_version"]
      
    # Checks if the bible version given is an accepted one
    if version_given in bible_version_set:
        
        # The list containing the chat id and the saved bible version
        saved_version = obtain_version(message.chat.id)

        # Removes the saved version if found
        version_list = [version for version in version_list if version != saved_version]

        # Checks if the version is not NIV
        if version_given != "NIV":

            # Saves the new version given to the database only when it's not NIV to save space
            version_list.append(f"{message.chat.id} {version_given}")

        # The message to notifiy the chat that the version has changed
        version_changed_msg = f"The current bible version has changed to {version_given}."

        # Sends the message
        send_message(message.chat.id, version_changed_msg)
 
    # If the bible version given is not in the list
    else:
        
        # The message to send to the chat
        invalid_msg = f"You have given me an invalid bible version. \n{get_version(message)} remains as the current bible version."
        
        # Sends the message
        reply_to(message, invalid_msg)

    # Finally, set the version list in the database to the updated one
    db["chats_version"] = list(dict.fromkeys(version_list))
```

<br>
<br>
<br>

While the code works perfectly fine for private chats and group chats, the bot fails the respond in channels.

<br>
<br>
<br>

## In a private chat:
<br>

![image](https://user-images.githubusercontent.com/91734413/189513208-28d377db-4135-4f67-8c96-1ed7290dc72a.png)

<br>
<br>
<br>

## In a group chat:
<br>

![image](https://user-images.githubusercontent.com/91734413/189513229-81916dd3-b051-43a7-a12a-1cff8460f506.png)

<br>
<br>
<br>

## In a channel:
<br>

![image](https://user-images.githubusercontent.com/91734413/189513213-b7b24892-20d6-4918-843f-678ad059b8e6.png)

**Comment by Badiboy** [comment]
```
# Handles the /setversion command
@bot.channel_post_handler(commands=["setversion"])
@bot.message_handler(commands=["setversion"])
def handle_version(message: types.Message) -> None:
```

I'm not sure that is suitable. Try to dedicate handlers:

```
@bot.channel_post_handler(commands=["setversion"])
def handle_version1(message: types.Message) -> None:
    handle_version(message)

@bot.message_handler(commands=["setversion"])
def handle_version2(message: types.Message) -> None:
    handle_version(message)
```

(

**Comment by coder2020official** [comment]
Confirmed. This happens because `process_new_channel_posts` does not process next step handlers.

**Comment by coder2020official** [comment]
@badiboy it is the same thing

> ```
> # Handles the /setversion command
> @bot.channel_post_handler(commands=["setversion"])
> @bot.message_handler(commands=["setversion"])
> def handle_version(message: types.Message) -> None:
> ```
> 
> I'm not sure that is suitable. Try to dedicate handlers:
> 
> ```
> @bot.channel_post_handler(commands=["setversion"])
> def handle_version1(message: types.Message) -> None:
>     handle_version(message)
> 
> @bot.message_handler(commands=["setversion"])
> def handle_version2(message: types.Message) -> None:
>     handle_version(message)
> ```
> 
> (

**Comment by coder2020official** [comment]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/63740404/189519545-ce73aec1-1855-47f7-adc0-19164a80e020.png">
The code worked after adding these lines of code to process step handlers. But i'm not sure whether it will be backward compatible or not.

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/189519889-5f9f45c2-73dd-49d6-abbe-624acd7ff2dd.png)

@coder2020official Current implementation of register_next_step_handler will not handle steps in groups correctly even if will be added.

Check the code: it is based in message.chat.id. It is fine for private chats, but for group chats it will always handle group chat id, so any of group users and there messages will pass to the next step. 

To implement steps for groups they should be extended to chat + user. I do not think it's reasonable, so I suppose @hankertrix should go to states and make custom implementation of anything he want to.

**Comment by coder2020official** [comment]
IK about it, so for groups I'd rather recommend states instead.
But for channels we can add implementation of steps.

**Comment by Badiboy** [comment]
Steps for channels are abolutely useless thing, because channels are not used for **interacition**.

**Comment by hankertrix** [comment]
I understand @Badiboy. A user of my bot wanted the ability for my bot to respond to his messages in his channel which is why I have this issue. I also told him that he should use the inline mode of the bot to send messages to a channel as it would be more appropriate. However, I don't think it'd be too much to ask to implement just a few more lines of code (if it is backwards compatible, of course) so that bot developers can use the register_next_step_handler function in channels as well. I believe that having the choice and the flexibility to use do so is great.

<br>
<br>
<br>
<br>

For anyone else who might run into the same issue, here is my solution to the problem:

<br>

`next_step_handler.py`

```
# The module to handle the next step of a command or conversation

from telebot import types

class NextStepHandler():
  """Class to handle the next step of a command or conversation"""

  def __init__(self, *, max_step: int) -> None:
    self.convos = {}
    self.max_step = max_step

  def register_next_step_handler(self, convo_name: str, message: types.Message) -> None:
    """Function to register the next step of a command or conversation"""

    # The name of the entry into the dictionary
    entry = f"{convo_name}_convo {message.from_user.id} {message.chat.id}"

    # Checks if the function name and chat id is not inside the dictionary or if the step is higher than the maximum number of steps
    if self.convos.get(entry) is None or self.convos.get(entry) > self.max_step:

      # Create the dictionary entry
      self.convos[entry] = 1

    # If the function name is already inside
    else:

      # Increment the number in the dictionary
      self.convos[entry] += 1

  def check_step(self, convo_name: str, message: types.Message, step: int) -> bool:
    """Function to check the step in the filters for the message handlers"""

    # Returns whether the step is inside the dictionary
    return self.convos.get(f"{convo_name}_convo {message.from_user.id} {message.chat.id}") == step

  def clear_step_handler(self, convo_name: str, message: types.Message) -> None:
    """Function to clear the step handler for a function and chat id. Must always be called at the end of a conversation"""

    # Removes the entry from the dictionary
    self.convos.pop(f"{convo_name}_convo {message.from_user.id} {message.chat.id}")
```

<br>
<br>
<br>

`main.py`

```

from next_step_handler import NextStepHandler

# The handler to handle the steps
handler = NextStepHandler(max_steps=1)

# Handles the /setversion command
@bot.channel_post_handler(commands=["setversion"])
@bot.message_handler(commands=["setversion"])
def handle_version(message: types.Message) -> None:

    # The content of the message behind the /setversion command
    msg_ctx = re.sub("/setversion ?", "", message.text.lower())

    # Checks if there is nothing behind the /setversion command
    if msg_ctx == "":

        # Sends the message to the user
        send_message(message.chat.id, "Please enter your bible version.")

        # Register the next step handler
        handler.register_next_step_handler("setversion", message)

    # If there is text written behind the /setversion command
    else:

        # Calls the set_version function
        set_version(message, msg_ctx)

# The function to read the user's message and save the new bible version given if it's accepted
@bot.channel_post_handler(func=lambda message: handler.check_step("setversion", message, 1))
@bot.message_handler(func=lambda message: handler.check_step("setversion", message, 1))
def set_version(message: types.Message, ctx: str = "") -> None:

    # Checks if the context is not given
    if ctx == "":

        # Sets the version to the entire message given by the user
        version_given = message.text.upper().strip()

    # If the context is given
    else:

        # Sets the version to be the text behind the /setversion command
        version_given = ctx.upper().strip()

    # Gets the version from the version mapping
    version_given = version_map.get(version_given, version_given)

    # Gets the version list from the database
    version_list = db["chats_version"]
      
    # Checks if the bible version given is an accepted one
    if version_given in bible_version_set:
        
        # The list containing the chat id and the saved bible version
        saved_version = obtain_version(message.chat.id)

        # Removes the saved version if found
        version_list = [version for version in version_list if version != saved_version]

        # Checks if the version is not NIV
        if version_given != "NIV":

            # Saves the new version given to the database only when it's not NIV to save space
            version_list.append(f"{message.chat.id} {version_given}")

        # The message to notifiy the chat that the version has changed
        version_changed_msg = f"The current bible version has changed to {version_given}."

        # Sends the message
        send_message(message.chat.id, version_changed_msg)
 
    # If the bible version given is not in the list
    else:
        
        # The message to send to the chat
        invalid_msg = f"You have given me an invalid bible version. \n{get_version(message)} remains as the current bible version.\nUse the /setversion command to try again."
        
        # Sends the message
        reply_to(message, invalid_msg)

    # Finally, set the version list in the database to the updated one
    db["chats_version"] = list(dict.fromkeys(version_list))

    # Removes the next step handler
    handler.clear_step_handler("setversion", message)
```

**Comment by Badiboy** [comment]
User that talk with bot in his personal dedicated channel is an extremely rare case. It can be said "Extraordinary case". I don't see a reason to change library for that case.

**Comment by hankertrix** [comment]
@Badiboy, indeed a user that talks to a bot in a channel can be considered an extremely rare case or an “extraordinary” case. But there are legitimately good use cases for interaction with bots within channels. The best example would be setting up a bot for use in a channel. Configuring a bot for use in a channel is probably best done within the channel in a series of steps, with the bot asking the user for their preferences and settings every step of the way. In the case of configuring the bot for the channel in a private chat, it would be pretty difficult to get the user to provide the channel ID that they want to configure the bot for, since it is something hidden by telegram and takes a bit of work to find and can be too much work for a lot of users, so much so that they won’t want to deal with the hassle of setting up the bot and just simply not use it. As for the settings, the alternative would be to provide a list of all the different settings that the user can change or configure, but it’ll likely be quite overwhelming for the user. Furthermore, the inputs wouldn’t be guided and it would either result in a lot of work on the developer’s side to parse a ton of different possible inputs or frustration on the end user because their inputs are not valid. A series of questions would make it such that the user only deals with one decision at a time and every input will be guided by providing a list of available options or providing a format for each (this guidance will likely be too much information when the user has to look through all the settings at once). 

I hope you see the usefulness of having a simple function to register the next step in a channel from this use case.

**Comment by Badiboy** [comment]
Use States. They are as flexible as your imagination can invent and can fulfil all your fantasies. ☺️

**Comment by coder2020official** [comment]
- I'm not sure about the states for channel. I didn't design them for channels

**Comment by hankertrix** [comment]
I see. But I honestly think that using states can be a little overkill for some simpler configurations that only take one or two steps. Introducing states just to configure a channel set up that only has one or two settings is a bit cumbersome. There is quite a bit of boilerplate that is needed to achieve the same functionality of the register_next_step_handler with states and I think for simpler use cases, it is fair to want to avoid the boilerplate to keep the code cleaner and more readable. For my situation, states is definitely a good solution as I need to deal with groups, private chats and channels, which is why my solution is pretty much a proprietary in-memory state management system. But for developers who want to create bots for channels (like daily update bots) and only need to configure one or two settings, the register_next_step_handler would be preferable to using states.

**Comment by Badiboy** [comment]
_User that talk with bot in his personal dedicated channel is an extremely rare case. It can be said "Extraordinary case". I don't see a reason to change library for that case._

**Comment by hankertrix** [comment]
I think you may have missed the point of my previous comment. I am not talking about a user interacting with a bot in a channel, but rather setting up and configuring a bot for a channel. Using states introduces too much boilerplate for a simple set up with one or two settings so the register_next_step_handler is preferable.
