### ISSUE TITLE
bot infinity polling can't handle errors or at least some of them

### ISSUE THREAD

**Issue by deamoncreator** [eternnoir/pyTelegramBotAPI#1730]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? last one

2. What OS are you using? Windows

4. What version of python are you using? 3.8.5

I was using bot infinity polling but it stops my script when an error come 

"telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400 Description: Bad Request: can't restrict self
"
2022-09-20 19:22:49,671 (__init__.py:455 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. Error code: 400 Description: Bad Request: can't restrict self""
(I tried to mute myself while being the chat owner)

Now I'm using this code and it doesnt give me any problems
"try:
    bot.polling(none_stop=True)
except Exception as e:
    time.sleep(15)"

**Comment by coder2020official** [comment]
Investigating it

**Comment by coder2020official** [comment]
Can you please set logging to DEBUG and send all the lines after the error?

**Comment by coder2020official** [comment]
And what is your 'last version' of pytba? 4.7.0?

**Comment by deamoncreator** [comment]
I confirm that I had an older version, my bad, sorry for taking your time.
