### ISSUE TITLE
  MypyBot = telebot.TeleBot('5476837851:AAFvobq4wpxzgqL_bfuj9NYSdqYP76dPrDo', parse_mode = None) TypeError: TeleBot.__init__() got an unexpected keyword argument 'parse_mode'

### ISSUE THREAD

**Issue by erickXzol** [eternnoir/pyTelegramBotAPI#1737]
MypyBot = telebot.TeleBot('5476837851:AAFvobq4wpxzgqL_bfuj9NYSdqYP76dPrDo', parse_mode = None)
TypeError: TeleBot.__init__() got an unexpected keyword argument 'parse_mode'

`import telebot

MypyBot = telebot.TeleBot('5476837851:AAFvobq4wpxzgqL_bfuj9NYSdqYP76dPrDo', parse_mode = None)

@MypyBot.message_handler(content_types = ['text'])
def replyer(message):
    MypyBot.reply_to(message, message.text)

MypyBot.polling()`

**Comment by Badiboy** [comment]
Default parameters like "parse_mode" are not released yet and are available only in githib version.

**Comment by coder2020official** [comment]
Parse mode should be available in older versions. Please upgrade your version to 4.7.0, it should have parse mode
@Badiboy last pull request wasn't about parse mode;
