### ISSUE TITLE
Threading: create_threads and num_threads - how to initiate

### ISSUE THREAD

**Issue by Baylung** [eternnoir/pyTelegramBotAPI#174]
Dear creators, 
please advise how to use documented parameters or TeleBot constructor: https://github.com/eternnoir/pyTelegramBotAPI#controlling-the-amount-of-threads-used-by-telebot

I'm initiating bot as following:
```
tb = telebot.TeleBot(token=TOKEN, create_threads=True, num_threads=8)
```
and get the following error:
```
tb = telebot.TeleBot(token=TOKEN, create_threads=True, num_threads=10)
TypeError: __init__() got an unexpected keyword argument 'create_threads'
```

pyTelegramBotAPI version: 2.1.1

**Comment by pevdh** [comment]
Unfortunately the docs are a bit out of date there - `create_threads` was removed from the constructor.
You can still get the same behaviour though.
```python

import telebot
from telebot import util

bot = telebot.TeleBot(TOKEN, threaded=True)
bot.worker_pool = util.ThreadPool(num_threads=8)
```
Although I would advise against using eight threads as the performance seems to drop after +/- 4 threads.

**Comment by Baylung** [comment]
Thank you !
