### ISSUE TITLE
How to get location object sent by user to the bot

### ISSUE THREAD

**Issue by Baylung** [eternnoir/pyTelegramBotAPI#175]
Please advise how I can catch and get/read the geo-location coordinates sent by user to the Bot ?

pyTelegramBotAPI version: 2.1.1

**Comment by pevdh** [comment]
```python
@bot.message_handler(content_types=['location'])
def handle_location(message):
    print("{0}, {1}".format(message.location.latitude, message.location.longitude))
```
[See the Telegram API docs](https://core.telegram.org/bots/api#message)

**Comment by Baylung** [comment]
Thank you !

**Comment by agentkingsman** [comment]
hola una pregunta espero no incomodar pero habrá alguna forma en c# como este ejemplo

**Comment by shivam-yoptima** [comment]
For me when I put in content_types it won't respond at all
