### ISSUE TITLE
Bot can't read bot messages.

### ISSUE THREAD

**Issue by RafayGhafoor** [eternnoir/pyTelegramBotAPI#1752]
Hi, I am using this message handler but I am unable to read messages in the group which are being posted by some bot. Is there something which I am doing wrong, the bot has permissions to read the messages in the group and is admin. Thanks.

```python
@bot.message_handler(
    func=lambda x:True,
    chat_types=["private", "group", "supergroup", "channel"],
    
)
def process(message): 
    print(message)
```

**Comment by Badiboy** [comment]
Bot can't read bot messages. It's Telegram limitation.

**Comment by RafayGhafoor** [comment]
Thank you!
