### ISSUE TITLE
Bug with entitities

### ISSUE THREAD

**Issue by roaste** [eternnoir/pyTelegramBotAPI#1753]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
latest
2. What OS are you using?
win10
3. What version of python are you using?
3.8

I have a code that prints the text and entities of the message, and I found a bug.
My code:
```
import telebot 


bot = telebot.TeleBot(token)


@bot.message_handler(content_types=['text'])
def messages(message):
	print('text: ')
	print(message.text) 
	print('len: ')
	print(len(message.text))
	print('entities: ')
	print(message.json['entities'])
bot.polling(none_stop = True, timeout=123)
```
Output:
```
text: 
😁
len: 
1
entities: 
[{'offset': 0, 'length': 2, 'type': 'text_link', 'url': 'https://github.com/eternnoir/pyTelegramBotAPI'}]
```

Why i have text len 1 and entitie length 2?

**Comment by Badiboy** [comment]
No bug.

Symbol "😁" is combinatorial Unicode character and in UTF-16 (in which message text is) consists of 2 symbols.

![image](https://user-images.githubusercontent.com/5613421/196259523-fe72fca8-dafd-43c9-9ce3-ea3df4b965d4.png)
