### ISSUE TITLE
Skip_pending does not work

### ISSUE THREAD

**Issue by Oleksandrigo** [eternnoir/pyTelegramBotAPI#1754]
1. 4.7.0
2. Windows 11
3. Python 3.10

Turn the bot off.
Send a message to the bot.
He does not respond.
Launch bot with skip_pending=True.
Bot reacts to the message, but in theory should not.

```
from telebot import TeleBot, types

import config

bot = TeleBot(config.BOT_TOKEN)


@bot.message_handler()
def echo(message: types.Message):
    bot.send_message(message.chat.id, message.text)


if __name__ == '__main__':
    bot.infinity_polling(skip_pending=True)
```

**Comment by coder2020official** [comment]
Just to remind that skip pending drops all updates except last one. Use delete_webhook with drop_pending_updates=True if you need to escape ALL updates

**Comment by Oleksandrigo** [comment]
@coder2020official  Thanks, its work =)
