### ISSUE TITLE
Bug with channel messages

### ISSUE THREAD

**Issue by Vamashi** [eternnoir/pyTelegramBotAPI#1760]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? latest

2. What OS are you using? windows 10

3. What version of python are you using? latest

I have problem, bot recieving messages from private chat, but not receiving messages from channel. He added to channel as admin, and have disabled privacy mode. He just not see messages from channel but see from private chat.

Code:
`import telebot

bot = telebot.TeleBot("tralalalalablalalatralalalalala")

@bot.message_handler()
def get_text_messages(message):
    print("nigga")
    bot.copy_message(481433297, message.from_user.id, message.id)
    print(bot.get_chat(message.from_user.id).username)
    
bot.polling(none_stop=True, interval=0)`

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI#channel-post-handler
