### ISSUE TITLE
`debug` removed from uvicorn

### ISSUE THREAD

**Issue by batmanscode** [eternnoir/pyTelegramBotAPI#1767]
Change in uvicorn: [Remove --debug flag #1640](https://github.com/encode/uvicorn/pull/1640)

---

`run_app()` https://github.com/eternnoir/pyTelegramBotAPI/blob/ebec3bf5c11cd685e1f3f031a422cfd831f7f428/telebot/ext/sync/webhooks.py#L107 and `run_webhooks()` https://github.com/eternnoir/pyTelegramBotAPI/blob/ebec3bf5c11cd685e1f3f031a422cfd831f7f428/telebot/__init__.py#L441 will need to be updated.

**Comment by coder2020official** [comment]
Can you do a PR?

**Comment by batmanscode** [comment]
Yes @coder2020official
