### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by popilanitu** [eternnoir/pyTelegramBotAPI#1777]
Please answer these questions before submitting your issue. Thanks!

1. I using 4.7.1

2. I using Windows 7

3. I using Python 3.6.0

My question is this. When I write "import telebot" at the beginning of the code and then run this code, it says "the telebot module does not exist"

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/issues/1033
