### ISSUE TITLE
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway

### ISSUE THREAD

**Issue by flllkis** [eternnoir/pyTelegramBotAPI#1780]
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 502. Description: Bad Gateway

**Comment by coder2020official** [comment]
Telegram problems. Use infinity polling, so your bot won't stop.

**Comment by flllkis** [comment]
Good thank you
