### ISSUE TITLE
Gifs/Sticker handler not works me

### ISSUE THREAD

**Issue by mashincode** [eternnoir/pyTelegramBotAPI#1793]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2dad99ad959741271a8ba1d114f2e3e5e65ff086 - from github

2. What OS are you using?
MacOs/Ubuntu Server

3. What version of python are you using?
 3.8 - 3.10

What ever i tried to do, those handlers can't detect gifs, i have no update if somebody send a gif or gif with caption
```

bot.message_handler(func=lambda message: True, content_types=['text', 'photo', 'video', 'document', 'sticker'])

bot.message_handler(func=lambda message: True)
```

Same for the stickers 

I tried to deep into your source code, but seems it require more time, that i was expected, so if possible, can you tell me where i need to look for to find a way to make it works, thank u :)

I also did check last 10 previous versions (cause before it works), but it did not help, seems like something changed on Telegram side or i did miss something else

**Comment by Badiboy** [comment]
GIFs are "animation".

**Comment by Badiboy** [comment]
Finding it is so

**Comment by mashincode** [comment]
> Найти это так

Thank you, don't know how i missed it
Have a good day
