### ISSUE TITLE
Broken URL in 'html_text' attribute of message with HTML markup

### ISSUE THREAD

**Issue by dbzix** [eternnoir/pyTelegramBotAPI#1804]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.7.1

2. What OS are you using?
GNU/Linux

3. What version of python are you using?
Python 3.10 / 3.11

**Steps to reproduce**:
1. Send message with HTML markup containing test word both in URL and in link's text:
`<b><a href="https://www.some.address.here.org/TEST_WORD">TEST_WORD</a></b>`

2. Read **html_text** attribute of sent message - it's broken:
`<a href="https://www.some.address.here.org/<b>TEST_WORD</b>"><b>TEST_WORD</b></a>`
instead of just:
`<a href="https://www.some.address.here.org/TEST_WORD"><b>TEST_WORD</b></a>`

3. Try to use updated at step 2 **html_text** for editing message or sending new message based on this content - you've got completely lost markup for this URL.

**Note**:
Problematic URL modification is part of processing nested entities in function `__html_text` of module `types.py`. Prior to version 4.7.1 there was no nested entities processing, so this issue relates to 4.7.1 only.

**Comment by coder2020official** [comment]
Thanks for the report. I'll investigate this issue ASAP

**Comment by coder2020official** [comment]
Check #1808. Try to install my git version and test. I tested a bit - everything looks fine.

**Comment by dbzix** [comment]
> Check #1808. Try to install my git version and test. I tested a bit - everything looks fine.

Thank you!
I've tested the change and it seems to be okay.
