### ISSUE TITLE
"Exception of type SSLError" when sending audio or document

### ISSUE THREAD

**Issue by kostyakoz** [eternnoir/pyTelegramBotAPI#182]
Hello everyone.

I'm just trying to send audio `.mp3` files with my bot (files size from 4mb to 15mb). My code is:
```python
with open(FILE_NAME, 'rb') as audio:
    # Getting meta-info from list (formed with json before)
    duration = int(item['audio']['duration']) # ex. '186'
    performer = str(item['audio']['performer'].encode('utf-8')) # ex. 'Sum 41'
    title = str(item['audio']['title'].encode('utf-8')) # ex. 'Pieces'
                 
    bot.send_audio(UID, audio, duration, performer, title, 
        disable_notification=True)
```
And so interesting thing: sometimes bot send my file successfully, but sometimes it gives me **SSLError** error.
```
ERROR - Exception of type SSLError in my_func(): ('The write operation timed out',)
```
Same with documents (gif files). I tried to rename file, meta-info, but everything without changes. It gives error again through time.

I run my bot locally on OS X, and this python-script executing only for sending files (without listeners or handlers, only DB with registered users ID's).

Any ideas how to fix it?

**UPD:** I think it's related with `requests` Python module, mine is v2.10
**UPD 2:** Solution is #173 (read my comment below)

**Comment by kostyakoz** [comment]
So, I've solved my problem. Solution is a pull request by @dmcelectrico: #173 
I've just added some time in `timeout` and now everything works fine.
Please, commit #173 to master branch.

**Comment by eternnoir** [comment]
Done.
