### ISSUE TITLE
Bug: register_next_step_handler_by_chat_id doesn't work with chat_id of type str

### ISSUE THREAD

**Issue by sch-mar** [eternnoir/pyTelegramBotAPI#1820]
After a lot of troubleshooting regarding ```bot.register_next_step_handler_by_chat_id``` I finally discovered that ```int(chat_id)``` works, but using ```str(chat_id)``` results in ignoring the (successfully) registered handler.

```python
...

# this works
bot.register_next_step_handler_by_chat_id(int(message.chat.id), some_handler)

# this doesn't
bot.register_next_step_handler_by_chat_id(str(message.chat.id), some_handler)
print(bot.next_step_backend.handlers) # returns {'12345679': [<telebot.Handler object at 0x0000012345689>]}
```

The documentation states both int and str should be valid:
```
:param chat_id: The chat for which we want to handle new message.
:type chat_id: int or str
```

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? - 4.7.1

2. What OS are you using? - Windows 10 Home 10.0.19045 Build 19045

3. What version of python are you using? - 3.9.2

**Comment by Badiboy** [comment]
Yes, you are right: register_next_step_handler_by_chat_id can handle only int chat_id.

Description is fixed: https://github.com/eternnoir/pyTelegramBotAPI/pull/1823

PS. You do not need "int(message.chat.id)": it is integer itself.
