### ISSUE TITLE
TypeError: __init__() unexpected keyword argument 'caption_entities' for types.InputMediaPhoto(..., caption_entities=ents)

### ISSUE THREAD

**Issue by pavel555ru** [eternnoir/pyTelegramBotAPI#1821]
Please answer these questions before submitting your issue. Thanks!
1. What version of pyTelegramBotAPI are you using? - 4.8.0
2. What OS are you using? - Linux
3. What version of python are you using? 3.8

When creating InputMediaPhoto with caption_entities:
`photo = telebot.types.InputMediaPhoto(my_file_id, caption=my_caption, caption_entities=my_entities)
`
getting the below error:
`TypeError: __init__() got an unexpected keyword argument 'caption_entities'`

If doing without caption_entities then works fine. Is caption_entities supported?

**Comment by Badiboy** [comment]
Bug... We'll fix.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1822
