### ISSUE TITLE
KeyboardButton type hint requires web_app

### ISSUE THREAD

**Issue by Goradii** [eternnoir/pyTelegramBotAPI#1825]
pyTelegramBotAPI = "^4.8.0"I are you using?

python 3.11

**Comment by Badiboy** [comment]
???

**Comment by Goradii** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/blame/master/telebot/types.py#L2196

**Comment by Badiboy** [comment]
Okay. When you learn how to write words and will be ready to open aprropriate and clear to understand issue - come back with your issue.
