### ISSUE TITLE
async StatePickleStorage does not require await in .read()

### ISSUE THREAD

**Issue by Wintreist** [eternnoir/pyTelegramBotAPI#1826]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
    4.8.0
2. What OS are you using?
   Windows 10
3. What version of python are you using?
   3.10

`storage = StatePickleStorage()`
this is probably just a small omission, however, I use all the storage methods together with await, and only for `storage.read()` this does not need to be done, although it is still asynchronous

**Comment by coder2020official** [comment]
I don't think using async and pickle is good idea. Afaik pickle does not support async and it is not safe to use it with async; I can implement locks though; But i wouldn't recommend using pickle for production

**Comment by Wintreist** [comment]
> I don't think using async and pickle is good idea. Afaik pickle does not support async and it is not safe to use it with async; I can implement locks though; But i wouldn't recommend using pickle for production

Which storage is better to use then?

**Comment by coder2020official** [comment]
Redis for prod
