### ISSUE TITLE
Keyboards: "markup.add()" creates new row instead just adding

### ISSUE THREAD

**Issue by kostyakoz** [eternnoir/pyTelegramBotAPI#183]
Hello. I need to add items to `markup` using `for` loop. When I use:
```python
markup.add(types.KeyboardButton('#1')) # it's inside `for` loop
```
it creates new row every time (same as using `markup.row`). So, what the difference between `markup.row` and `markup.add`, and how can I add new items to **same row** using `for` loop?

**Comment by pevdh** [comment]
The `row_width` passed to the constructor of a `ReplyKeyboardMarkup` or `InlineKeyboardMarkup` object determines how many buttons fit on a single row.
```python
markup = types.ReplyKeyboardMarkup(row_width=3)
for text in ['a', 'b', 'c', 'd', 'e']:
    markup.add(types.KeyboardButton(text))
```
should add 'a', 'b' and 'c' to the first row and push 'd' and 'e' to the next row.

**Comment by kostyakoz** [comment]
@pevdh thank you, it works for me 👍🏻

**Comment by AndydeCleyre** [comment]
It looks like this bug has returned, using `2.1.4`. Either leaving out `row_width` (should be `3`) or specifying `2` just acts as if I specified `1`. Oh, this is with `InlineKeyboardMarkup`.

Please re-open.

Thanks!

**Comment by denis-d** [comment]
Bug is back, using 4.6.0. it creates new row every time no matter what row_width is.
