### ISSUE TITLE
edit_message_reply_markup don't working with channel post with many photo or video

### ISSUE THREAD

**Issue by andrei-sharykau** [eternnoir/pyTelegramBotAPI#1830]
Hi, method "edit_message_reply_markup" don't working with channel post with many photo or video.
Method perfect working when post found single photo or video.

```
@bot.channel_post_handler(content_types=['photo', 'video'])
def edit_photo(message):
    bot.edit_message_reply_markup(chat_id=message.chat.id, message_id=message.message_id,  reply_markup=ch_keyboard)

```

**Comment by coder2020official** [comment]
What do you mean by not working? Use discussions instead next time

**Comment by Badiboy** [comment]
"Many photos" are many messages with 1 photo. So you should edit markup for one of those messages. I suppose with the first one (or last one) - should be checked. To which one your "message_id" relates - I don't know, check...

**Comment by andrei-sharykau** [comment]
Oh, I have this error 
`Error code: 400. Description: Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message`

**Comment by andrei-sharykau** [comment]
originally reply_markup is None, I change reply_markup to ch_keyboard

**Comment by Badiboy** [comment]
Check your "ch_keyboard"... If it really created. If it is not "ReplyKeyboardMarkup"... If it has buttons... 

The telegram answer is quite clear: it is not different.

**Comment by andrei-sharykau** [comment]
yes, "ch_keyboard" is correctly. Works with single photo or video

**Comment by coder2020official** [comment]
@andrei-sharykau did you solve the issue or you are still struggling?

**Comment by andrei-sharykau** [comment]
@coder2020official no, I haven't decided. It seems that telegram does not allow adding a button to a post containing several photos or videos.

**Comment by coder2020official** [comment]
Have u tried adding keyboard to first photo? What error/result did you get?

**Comment by andrei-sharykau** [comment]
@coder2020official When calling the edit_message_reply_markup method for any image in a post, I get an error:
`Error code: 400. Description: Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message`
When calling the edit_message_caption method - the caption changes, but if you add the reply_markup=ch_keyboard option to this method, the keyboard does not appear and no errors occur.

**Comment by Badiboy** [comment]
@andrei-sharykau I checked the code - it's fine. Looks like a behaviour/issue of the Telegram.
