### ISSUE TITLE
0A000086 SSL error in webhook

### ISSUE THREAD

**Issue by noname01t1** [eternnoir/pyTelegramBotAPI#1837]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.8.0
2. What OS are you using?
Ubuntu 22.04
3. What version of python are you using?
Python 3.10.6

I'm now starting webhook by using `bot.run_webhooks(listen=LISTEN,certificate=WEBHOOK_SSL_CERT,certificate_key=WEBHOOK_SSL_PRIV)`. However, after I starting it, telegram returns `SSL error {error:0A000086:SSL routines::certificate verify failed}`.

Google Chrome returns OK.
I'm now using Zerossl. The certificate is signed for an IP address. And the certificate file is full chain.

**Comment by coder2020official** [comment]
There're instructions on creating self-made certificate in example. Please follow it

**Comment by coder2020official** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/63740404/208251514-d0d4233a-4f30-48e1-aa39-06ae355dc545.png">
here is it

**Comment by noname01t1** [comment]
> 

Thanks and it works fine.
