### ISSUE TITLE
Add before dispatch function

### ISSUE THREAD

**Issue by SergiX44** [eternnoir/pyTelegramBotAPI#184]
It will be great if it possible to implement a function that it will be called before dispatch a message request to the right hook.
For example, Flask framework has this function that is called before calling the right route:

```
...
@app.before_request
def detect_user_language():
    connect_to_databaase()
    check_permissions()
    blahblah()
    ....

@app.route('/')
def index():
    return things('..')

...
```

I think that a function like this it can be useful for example to opening connection with a database, perform some checks on the message, etc

**Comment by pevdh** [comment]
Interesting idea, I will look into this for v3.
