### ISSUE TITLE
enable_save_next_step_handlers(delay=2) 报错 TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by stonegr** [eternnoir/pyTelegramBotAPI#1840]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.8.0
2. What OS are you using?
windows
3. What version of python are you using?
3.10.5

打开
bot.enable_save_next_step_handlers(delay=2)
bot.load_next_step_handlers()
这两项之后，报这个错

![截图_20221220105249](https://user-images.githubusercontent.com/74632994/208570734-c8a751ac-a4a6-4c33-bd5c-88aff71f8648.png)

感谢开发者的辛勤开发

**Comment by coder2020official** [comment]
I tried to use [this](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/step_example.py) example and reproduce the issue. I couldn't. Can you give more details?

**Comment by stonegr** [comment]
> I tried to use [this](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/step_example.py) example and reproduce the issue. I couldn't. Can you give more details?

thank you for your reply
I encountered this problem in this project, can you try to run?

https://github.com/stonegr/telebot-assistant

**Comment by coder2020official** [comment]
Can you create a small code with same problem instead?
