### ISSUE TITLE
Incorrect behaviour of escape_markdown

### ISSUE THREAD

**Issue by AsMaNick** [eternnoir/pyTelegramBotAPI#1843]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.8.0
2. What OS are you using?
Both Linux/Windows 10
3. What version of python are you using?
Python 3.9.0

Function `escape_markdown` from `telebot.formatting` doesn't escape symbols `{` and `}`, however according to the [core.telegram](https://core.telegram.org/bots/api#markdownv2-style) they must be escaped with the preceding character `\`.

It means that now sending messages using `parse_mode='MarkdownV2'` gives the following error when the message text contains symbols `{` and `}`: `A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Character '{' is reserved and must be escaped with the preceding '\'`.

**Comment by coder2020official** [comment]
Thx for bug report, I'll take a look

**Comment by coder2020official** [comment]
Can you install my git version containing fix and check? As you confirm that issue is fixed, I will re-test it again and merge.

```
pip uninstall pytelegrambotapi
pip install git+https://github.com/coder2020official/pyTelegramBotAPI.git
```

change to pip3 if necessary

**Comment by AsMaNick** [comment]
Thank you for such a fast fix, I've checked it, the issue is fixed now 👍
