### ISSUE TITLE
ForceReply appears without demand

### ISSUE THREAD

**Issue by DimaDDM** [eternnoir/pyTelegramBotAPI#1848]
Same problem like in #291 

1. API library 4.8.0 or <

2. Mac OS

3. Python 3.10 or <

I'm facing same issue when using `telet.ForceReply(selective=True)`. Problem can be reproduced on Telegram Lite for Mac OS (in private chats)

```
# Handle command
@self.bot.message_handler(commands=[Commands.COMMAND])
        def ai_command(message):
            self.cmd(message)


# Command handler
    def cmd(self, message):
        chat_id = message.chat.id

            if message.text:
                self.send_markup(chat_id, "Test", chat_id))


# Response
    def send_markup(self, cid, message_text: str):
        markup = telet.ForceReply(selective=True)
        self.bot.send_message(cid, message_text, reply_markup=markup, parse_mode=parse_mode,
                              disable_web_page_preview=disable_preview)

```

When you close app and open again force reply appears without any demand and even when the previous message does not contain a command. It's work no only Telegram Lite for Mac os, also for Telegram app for Mac OS too and sometimes on mobile devices.

**Comment by coder2020official** [comment]
Not a lib bug
