### ISSUE TITLE
Middleware enhancement

### ISSUE THREAD

**Issue by sevazhidkov** [eternnoir/pyTelegramBotAPI#185]
Hi!

In my projects i have a lot of code like:

``` python
def setup_user(user_data):
    # Load data from DB


@bot.message_handler(commands=['some_command'])
def a(message):
    user = setup_user(message.from_user)
    # ...


@bot.message_handler(func=lambda m: True)
def b(message):
    user = setup_user(message.from_user)
    # ...
```

Middlewares function can transform it to something like this:

```
@bot.middleware()
def setup_user(message):
    message.from_user.data = # load data from DB


@bot.message_handler(commands=['some_command'])
def a(message):
    # User DB data in the message.from_user.data 

@bot.message_handler(func=lambda m: True)
def b(message):
    # User DB data in the message.from_user.data
```

Getting data about user from DB isn't the only possible function of middlewares. For example, when user sends location, bot getting lat/long. In this case developer just can create new middleware that reverse-geocoding user's location.

**Comment by SergiX44** [comment]
See this https://github.com/eternnoir/pyTelegramBotAPI/issues/184
I have opened this some hours before XD, the idea is the same, it can be very useful
