### ISSUE TITLE
Circular import in types & util files

### ISSUE THREAD

**Issue by coder2020official** [eternnoir/pyTelegramBotAPI#1864]
Types file imports util:
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/types.py#L15
And util imports types:
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/util.py#L16

@Badiboy any ideas on properly fixing the issue?

**Comment by Badiboy** [comment]
There were no any **problems** with circular import before.
When the **problem** appears?

**Comment by coder2020official** [comment]
I've seen some reports before in chats, but they fixed it somehow.
Here's another screenshot of bugreport i got today:
![telegram-cloud-photo-size-2-5307926708923515092-y](https://user-images.githubusercontent.com/63740404/210575743-0f6d4564-ab74-44f7-b2ee-7374df2abeb6.jpg)
And the links in the issue description show the circular import. When one of the files import another file, it imports the file that it importing it. It is definitely a circular import issue

**Comment by Badiboy** [comment]
Thanks, I'll check.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1868
