### ISSUE TITLE
cannot start python app

### ISSUE THREAD

**Issue by kdh6429** [eternnoir/pyTelegramBotAPI#188]
> root@ubuntu:~/tg/bot/pyTelegramBotAPI/examples# python step_example.py
> Traceback (most recent call last):
>   File "step_example.py", line 78, in <module>
>     bot.polling()
>   File "build/bdist.linux-x86_64/egg/telebot/__init__.py", line 183, in polling
>   File "build/bdist.linux-x86_64/egg/telebot/__init__.py", line 206, in __threaded_polling
>   File "build/bdist.linux-x86_64/egg/telebot/util.py", line 73, in raise_exceptions
>   File "build/bdist.linux-x86_64/egg/telebot/util.py", line 54, in run
>   File "build/bdist.linux-x86_64/egg/telebot/__init__.py", line 121, in __retrieve_updates
>   File "build/bdist.linux-x86_64/egg/telebot/__init__.py", line 91, in get_updates
>   File "build/bdist.linux-x86_64/egg/telebot/apihelper.py", line 139, in get_updates
>   File "build/bdist.linux-x86_64/egg/telebot/apihelper.py", line 34, in _make_request
>   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 316, in send
>     timeout = TimeoutSauce(connect=timeout, read=timeout)
>   File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 116, in __init__
>     self._connect = self._validate_timeout(connect, 'connect')
>   File "/usr/lib/python2.7/dist-packages/urllib3/util.py", line 147, in _validate_timeout
>     "int or float." % (name, value))
> ValueError: Timeout value connect was (3.5, 30), but it must be an int or float.
> 

I just clone this git and here is result.
Am i doing something wrong?

**Comment by kdh6429** [comment]
Python version is 2.7.6

**Comment by eternnoir** [comment]
try `pip install -U requests`

**Comment by kdh6429** [comment]
still same error

**Comment by kdh6429** [comment]
after installing pip and request, re-make setup.py and all erros gone :)
