### ISSUE TITLE
Module telebot not found (IS INSTALLED and found this in same loc than before)

### ISSUE THREAD

**Issue by ZetZ1** [eternnoir/pyTelegramBotAPI#1887]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
latest
2. What OS are you using?
3. Ubuntu server
idont know version
4. What version of python are you using?
3.10

Yesterday i made a mistake with a bot, bot starting sending many many messages to Telegram, i erase the python script inmediately and reboot system. After reboot now i give the error  telebot module not installed, but i not make any changes in configuration...

Maybe a error of API due to many messages?

The same code with same telegram api works perfectly if i start code in local (another IP)

**Comment by Badiboy** [comment]
Just try re-install the library. 

API problems do not look like that )

**Comment by ZetZ1** [comment]
reinstalled and upgrade , is not the proble :/

 import telebot
ModuleNotFoundError: No module named 'telebot'
root@vps-88242f6b:~#


this error in all scripts. telebot installed. No changes in my VPS. in my pc code works fine, API problem discard.... IP?

**Comment by Badiboy** [comment]
> API problem discard.... IP?

The problem is in the istallation of the package. Something is wrong installed. For another user or somthing like that. Nothing is with API, because you are yet far away from any API :)

**Comment by Badiboy** [comment]
`pip list`
?

```
python3
import telebot
```
?

**Comment by ZetZ1** [comment]
telebot                0.0.4
TelegramBotAPI         0.3.2


in codes i import telebot. all is ok :(

**Comment by Badiboy** [comment]
> telebot 0.0.4

Come on, what's that?
Start from here: https://github.com/eternnoir/pyTelegramBotAPI#getting-started

**Comment by coder2020official** [comment]
Bruh
Delete telebot and update pytelegrambotapi

**Comment by ZetZ1** [comment]
now work work wiouth make any change after reboot (i reboot 638738787 times...  i dont understand what happened...

sorry and thanks
