### ISSUE TITLE
Ignore middleware

### ISSUE THREAD

**Issue by Blissbill** [eternnoir/pyTelegramBotAPI#1888]
Hey
I noticed that when using `register_next_step_handler`, the next call will ignore middleware. Is this done on purpose?
If so, is there a way to get around this limitation?

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pytelegrambotapi==4.9.0

2. What OS are you using?
Windows 11

3. What version of python are you using?
Python 3.9.10

**Comment by coder2020official** [comment]
Hi
I would recommend you to use states instead of steps. However, I'm gonna take a look at the issue ASAP and fix it if possible

**Comment by Blissbill** [comment]
@coder2020official Thanks for the quick response. Can you please tell me where to look about the implementation through states?

**Comment by Blissbill** [comment]
@coder2020official Thank you looks like exactly what I need
