### ISSUE TITLE
Problem on Ubuntu

### ISSUE THREAD

**Issue by Martin-Winter** [eternnoir/pyTelegramBotAPI#189]
I find problem with connecting to server:
![2016-06-03 15 04 03](https://cloud.githubusercontent.com/assets/18497630/15799290/75d0d6fc-2a79-11e6-908e-58f49d7b30bf.png)
I modify apihelper.py on string 32 to solve the problem:
`result = requests.request(method, request_url, params=params, files=files, timeout=(CONNECT_TIMEOUT, read_timeout))`
to
`result = requests.request(method, request_url, params=params, files=files, timeout=(read_timeout))`
This problem does not exist in Python 3 for Windows. Just in Python 3.4.3 on Ubuntu 14.04

**Comment by pevdh** [comment]
Please try `pip install -U requests`.

**Comment by Martin-Winter** [comment]
Yes, it solved the problem
