### ISSUE TITLE
get_state and retrieve_data always returns None in callback_query_handler

### ISSUE THREAD

**Issue by nz1848** [eternnoir/pyTelegramBotAPI#1895]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.9.0

2. What OS are you using?
Windows 10 x64

3. What version of python are you using?
3.8.10

**Issue:**
Calling TeleBot's `get_state `or `retrieve_data` methods inside functions decorated by `callback_query_handler` always returns `None`.

**An example** of code that reproduces the problem with `get_state`:
```
import telebot, logging
from telebot.custom_filters import StateFilter
from telebot.storage import StateMemoryStorage
from telebot.types import InlineKeyboardButton, InlineKeyboardMarkup, CallbackQuery, Message

logger = telebot.logger
telebot.logger.setLevel(logging.INFO)
state_storage = StateMemoryStorage()
bot = telebot.TeleBot(BOT_TOKEN, state_storage=state_storage)

@bot.message_handler(commands=["set_state"])
def set_state_command(m: Message):
    user_id, chat_id = m.from_user.id, m.chat.id
    markup = InlineKeyboardMarkup(
        [[InlineKeyboardButton('get_state', callback_data=f"get_state")]]
    )
    bot.set_state(user_id=user_id, chat_id=chat_id, state="some_state")
    bot.reply_to(message=m, text="set state to: 'some_state'", reply_markup=markup)
    print(f"\nfrom message_handler (set_state cmd):\nset state to: 'some_state'\n")

@bot.callback_query_handler(func=lambda q: q.data.startswith('get_state'), state='some_state')
def get_state_callback(cb: CallbackQuery):
    user_id, chat_id = cb.message.from_user.id, cb.message.chat.id
    state_str = bot.get_state(user_id=user_id, chat_id=chat_id)
    print(f"from callback_query_handler: \n{state_str = }\n")

@bot.message_handler(commands=["get_state"], state='some_state')
def set_state_command(m: Message):
    user_id, chat_id = m.from_user.id, m.chat.id
    state_str = bot.get_state(user_id=user_id, chat_id=chat_id)
    print(f"from message_handler (get_state cmd): \n{state_str = }\n")
    bot.reply_to(message=m, text=f"Get state: {state_str}")

if __name__ == '__main__':
    bot.add_custom_filter(StateFilter(bot))
    bot.infinity_polling()
```
After running this code, I sent /set_state to the bot, clicked on the 'get_state' button in replied message, sent /get_state and got this output in the console:
```
2023-01-28 20:13:07,387 (__init__.py:1057 MainThread) INFO - TeleBot: "Started polling."

from message_handler (set_state cmd):
set state to: 'some_state'

from callback_query_handler: 
state_str = None

from message_handler (get_state cmd): 
state_str = 'some_state'

```

Am I doing something wrong or is there no way to use `states` inside functions decorated by `callback_query_handler`?

**Comment by coder2020official** [comment]
I'll check, thanks for bugreport

**Comment by coder2020official** [comment]
A, i see. You are passing totally wrong user id.

Check ur callback query handler and replace this:
`user_id, chat_id = cb.message.from_user.id, cb.message.chat.id`
by:
`user_id, chat_id = cb.from_user.id, cb.message.chat.id`

**Comment by coder2020official** [comment]
callback.from_user returns user info. callback.message returns info about message - which is sent by bot. therefore, callback.message.from_user returns bot info, since message that is present is sent by bot

**Comment by nz1848** [comment]
@coder2020official Thanks for the quick response
