### ISSUE TITLE
Argument "allowed_updates" does not work in AsyncTeleBot

### ISSUE THREAD

**Issue by rustequal** [eternnoir/pyTelegramBotAPI#1896]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.9.0

2. What OS are you using?
Windows, Linux

3. What version of python are you using?
3.18

How to reproduce:
1. Create a new bot using BotFather
2. Add the bot to the group, make it an administrator
3. Run this code:

```
import asyncio
from telebot.async_telebot import AsyncTeleBot


TOKEN = '<BOT_TOKEN>'
bot = AsyncTeleBot(TOKEN, parse_mode='HTML')

@bot.chat_member_handler()
async def message_chat_member(message):
  print('chat_member_handler')

asyncio.run(bot.infinity_polling(allowed_updates=["chat_member"]))
```
4. Exit the group to trigger update "chat_member"
5. Find out that this code will not work

I seem to have found a bug. In the file "asyncio_helper.py" in function "get_updates" need to change this line:
`params['allowed_updates'] = allowed_updates`

to this line:
`params['allowed_updates'] = json.dumps(allowed_updates)`

After that, my code with the new bot started working

**Comment by coder2020official** [comment]
Thx, will fix tonight

**Comment by Badiboy** [comment]
Thank you.
https://github.com/eternnoir/pyTelegramBotAPI/pull/1898
