### ISSUE TITLE
Improve de_json

### ISSUE THREAD

**Issue by eternnoir** [eternnoir/pyTelegramBotAPI#19]
`opts['sticker'] = Sticker.de_json(json.dumps(obj['sticker']))`

to create sticker object bu de_json function need json string. But it has better way to create object without json_dumps.

**Comment by eternnoir** [comment]
@pevdh I found your develop branch has commit to improve de_json, it very helpful. Cloud you give me a pull request after you finish it? Thanks a lot.

**Comment by pevdh** [comment]
Alright, see #20
