### ISSUE TITLE
How to handle Image/ forwarded messages?

### ISSUE THREAD

**Issue by has12zen** [eternnoir/pyTelegramBotAPI#1903]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
 Name: pyTelegramBotAPI
Version: 4.9.0

2. What OS are you using?
Ubuntu 22.10

3. What version of python are you using?
3.9.12
I was going through the method provided in the documentation and testing them I copied the below function form docs and started the bot. It works as expected for text messages but when I send Image files to it it does not increment the counter. It also happens with forwarded messages I want it to work for for all messages is there any way? am I doing something wrong?

```py
@bot.message_handler(func=lambda m: True)
def echo_all(message):
    global counter
    with open(f'./logs/data_{counter}.json', "w") as file:
        json.dump(message.json, file)
    counter+=1
    print(counter)
    # bot.reply_to(message, message.text)

```

**Comment by coder2020official** [comment]
you have to set content_type to telebot.util.content_type_media in handler

**Comment by coder2020official** [comment]
If you don't specify content_type, text will only be received

**Comment by has12zen** [comment]
ohh ok Thanks
