### ISSUE TITLE
TypeError: 'ChatPermissions' object does not support item assignment

### ISSUE THREAD

**Issue by xvitaly** [eternnoir/pyTelegramBotAPI#1910]
pyTelegramBotAPI version: 4.10.0
OS: Microsoft Windows and Fedora Linux.
Python version: 3.10.10

Steps to reproduce:

```python
self._perm = telebot.types.ChatPermissions(can_send_messages=True, can_send_media_messages=False, can_send_audios=False, can_send_documents=False, can_send_photos=False, can_send_videos=False, can_send_video_notes=False, can_send_voice_notes=False, can_send_polls=False, can_send_other_messages=False, can_add_web_page_previews=False, can_change_info=False, can_invite_users=False, can_pin_messages=False, can_manage_topics=False)

@property
def join(self):
    return self._perm

self._bot.restrict_chat_member(message.chat.id, userid, until_date=mutetime, permissions=self.join, use_independent_chat_permissions=True)
```

Error:
```
Traceback (most recent call last):
  File "ecasbot\__init__.py", line 762, in __handle_join
  File "telebot\__init__.py", line 3001, in restrict_chat_member
  File "telebot\apihelper.py", line 977, in restrict_chat_member
TypeError: 'ChatPermissions' object does not support item assignment
```

**Comment by xvitaly** [comment]
`ChatPermissions` object can't be immutable (assigned with getter for example).

**Comment by xvitaly** [comment]
I think `use_independent_chat_permissions` should be moved to `ChatPermissions` constructor too.

**Comment by coder2020official** [comment]
I'll double check and make pr, thanks

**Comment by Badiboy** [comment]
restrict_chat_member provides the API method semantics.

https://core.telegram.org/bots/api#restrictchatmember

**Comment by Badiboy** [comment]
@coder2020official This is not a bug.

**Comment by coder2020official** [comment]
@badiboy there's a bug, look at apihelper

**Comment by coder2020official** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/63740404/217847244-342bfa95-cfa4-4f5c-93f5-eec78b517d04.png">
Here

**Comment by coder2020official** [comment]
so use_independent_chat_permissions should go to payload instead.

**Comment by Badiboy** [comment]
Lol, sorry. I'll fix.

**Comment by coder2020official** [comment]
Thanks

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1911

**Comment by xvitaly** [comment]
Great. LGTM now. Can you make a new bugfix release?

**Comment by coder2020official** [comment]
@Badiboy what do u think? it doesn't seem to be critical

**Comment by Badiboy** [comment]
Not critical, but a bug. Fix the other issue, let's release, why not.
