### ISSUE TITLE
async download_file issue

### ISSUE THREAD

**Issue by Badiboy** [eternnoir/pyTelegramBotAPI#1912]
Issue in 
`async download_file`

![image](https://user-images.githubusercontent.com/5613421/217848942-1ff6b432-2c69-4c78-b931-a00af3a05b58.png)

_result_ is used before assignment. I'm not sure how it should be, please, take a look.

**Comment by coder2020official** [comment]
uh shit, thanks, i'll check now

**Comment by Badiboy** [comment]
No hurry, it exists for long time. I just forgot to report...
