### ISSUE TITLE
colorful_logs parameter does not take effect

### ISSUE THREAD

**Issue by MaGua-Bishop** [eternnoir/pyTelegramBotAPI#1925]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.10
2. What OS are you using?
mac os 
3. What version of python are you using?
python3.8

**colorful_logs version:  15.0.1**

After this parameter is set, no log is generated 
The use of Internet links will be blocked, unable to receive telegraph messages
```
import logging

import telebot

telebot.logger.setLevel(logging.DEBUG)

bot = telebot.TeleBot("TOKEN",colorful_logs=True)

@bot.message_handler(commands=['start'], chat_types=['private'])
def private_user_message(message):
    print(message)


if __name__ == '__main__':
    bot.delete_webhook()
    bot.infinity_polling()
```

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/220542903-9accf33c-2ef7-451a-ae85-02230bcde7eb.png)

Works fine.
