### ISSUE TITLE
How to get any gif on server when i send it by phone

### ISSUE THREAD

**Issue by krifoElectron** [eternnoir/pyTelegramBotAPI#1957]
How to get any gif on server when i send it by phone

1. pyTelegramBotAPI==4.10.0

2. [Ubuntu Server 20.04 LTS](https://ubuntu.com/download/server)

3. Python 3.8.10

when i use all conent_types and send gif from phone or some of window computers:

@bot.message_handler(content_types=['text', 'audio', 'document', 'photo', 'sticker', 'video', 'video_note', 'voice', 'location', 'contact', 'new_chat_members', 'left_chat_member', 'new_chat_title', 'new_chat_photo', 'delete_chat_photo', 'group_chat_created', 'supergroup_chat_created', 'channel_chat_created', 'migrate_to_chat_id', 'migrate_from_chat_id', 'pinned_message', 'web_app_data'])
def get_text_messages(message):
    print('aaaa')

i don't see 'aaaa' in console

So, tell me, please, how can i get gif, which user send me? I think I'm missing something, but I don't understand what

**Comment by alex75311** [comment]
@bot.message_handler(content_types=['animation'])
