### ISSUE TITLE
 Field "language" must be of type String when clonning message entities with edit_message_text

### ISSUE THREAD

**Issue by nkhono** [eternnoir/pyTelegramBotAPI#1962]
**1)**`pyTelegramBotAPI 4.10.0`
**2)**`Windows//Ubuntu`
**3)**`3.11.2`

**Notice:** experienced it when there is 'pre' tag in entities

I have code that adds keyboard to message and to keep it formated I did it like so (using entities that were given by the API itself): 

```
@bot.channel_post_handler(content_types=['text'])
def adapt(message):

	#my code was here

	kyb = types.InlineKeyboardMarkup()
	bt = types.InlineKeyboardButton(text='text', url='https://example.com')
	kyb.add(bt)
	bot.edit_message_text(chat_id=message.chat.id, message_id=message.id, entities=message.entities, reply_markup=kyb, text=message.text)
```
But when executing I get error:
`telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse MessageEntity: Field "language" must be of type String`.

I fixed it by changing every 'language' in MessageEntity to 'text' (string) instead of None (nonetype)

**Comment by Istorn** [comment]
Hi @nkhono did you experienced the same issue on the following version as well (4.11.0)?

**Comment by coder2020official** [comment]
Can you send sample text please? Implementation of MessageEntity looks fine
