### ISSUE TITLE
No module named "telebot"

### ISSUE THREAD

**Issue by vahidsharifi** [eternnoir/pyTelegramBotAPI#1965]
pyTelegramBotAPI version: 4.10.0
OS: Mac OS 13.1  (M1)
Python version: 3.10.8

Hello, I installed my "pyTelegramBotAPI" with "pip install" in "venv". but when I import "telebot" I encounter the "ModuleNotFoundError: No module named 'telebot' " error. I uninstalled the "pyTelegramBotAPI" package and installed it again using pip. but it's not working. Also, when I check pip list, there is no telebot module in my packages list!!

**Comment by Badiboy** [comment]
You did something wrong with your venv. Not activated it when using or something like this. Learn how to use venv properly or do not use it.

> Also, when I check pip list, there is no telebot module in my packages list!!

It should not be there. pyTelegramBotAPI should be in this list.

**Comment by vahidsharifi** [comment]
> You did something wrong with your venv. Not activated it when using or something like this. Learn how to use venv properly or do not use it.
> 
> > Also, when I check pip list, there is no telebot module in my packages list!!
> 
> It should not be there. pyTelegramBotAPI should be in this list.

pyTelegramBotAPI is in the list as you mentioned. But when I want to import telebot, it seems it's not there! 
Also, I tried to different versions of pyTelegramBotAPI but it's not working! I've seen many other programmer in other communities had the same issues, but nobody came up with a solution for that!

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/232250051-0d38c71f-37e2-4ceb-92a4-b34c6e3cc7eb.png)

All these somehow solve that...
