### ISSUE TITLE
Next step handlers are not working with webhook

### ISSUE THREAD

**Issue by its0x4d** [eternnoir/pyTelegramBotAPI#1981]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 
2. 4.11.0

3. What OS are you using?
4. Arch Linux

5. What version of python are you using?
6. 3.11.0

![image](https://user-images.githubusercontent.com/58491910/235442978-47f9c484-7910-471d-b67b-e3e52d53dd15.png)

I have a handler like this it sends a message and the register a next step handler... i works fine with `polling` run method
but it doesn't work with set_webhook method why is that?

**Comment by Badiboy** [comment]
Depends on how you implemented webhooks. If you create new instance of Telebot on every incoming request - state will be lost between requests. If so - use one of next step handler saving modes.

**Comment by its0x4d** [comment]
> Depends on how you implemented webhooks. If you create new instance of Telebot on every incoming request - state will be lost between requests. If so - use one of next step handler saving modes.

![image](https://user-images.githubusercontent.com/58491910/235599456-41b7ddec-117d-4328-ac5f-e5f63c65c858.png)
this is my webhook api what do you suggest?

**Comment by its0x4d** [comment]
fixed it :) thanks

**Comment by guilemos** [comment]
@its0x4d  how you fixed it?
