### ISSUE TITLE
Issue With get_file() while using local bot api server

### ISSUE THREAD

**Issue by shoya0x00** [eternnoir/pyTelegramBotAPI#1986]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 4.11

2. What OS are you using?
Ubuntu 22.04

4. What version of python are you using?
Python 3.10

error i am getting
```
2023-05-15 19:04:14,389 - bot - ERROR - A request to the Telegram API was unsuccessful. The server returned HTTP 404 Not Found. Response body:
[b'{"ok":false,"error_code":404,"description":"Not Found"}']
```

**Comment by Badiboy** [comment]
Set 
apihelper.FILE_URL
