### ISSUE TITLE
Can't kill the echo bot example

### ISSUE THREAD

**Issue by grizmio** [eternnoir/pyTelegramBotAPI#2]
First, great work! It has been very useful and fun to me.
I copy/pasted the example, but can't be interrupted with the KeyboardInterrupt signal on Gentoo.
IMHO one possible fix could be change the main loop at the end:
try:
    while 1:
        time.sleep(20)
except KeyboardInterrupt:
    tb.stop_polling()

**Comment by eternnoir** [comment]
"Thank you for your suggestion. I will change telebot polling thread to daemon mode. In this way , you can kill echo bot by KeyboardInterrupt.
