### ISSUE TITLE
Block param in polling function

### ISSUE THREAD

**Issue by victor141516** [eternnoir/pyTelegramBotAPI#200]
I need the bot to not stop when polling() function is invoked. In the doc states that there is a param (block=False) that does the work but Python claims that param doen't exists as you can see in the code:

`def polling(self, none_stop=False, interval=0, timeout=20):`

**Comment by eternnoir** [comment]
block param had remove from polling method in new version. If you want polling method don't block thread, you need create new thread run polling method.

**Comment by wagnerluis1982** [comment]
This issue should be closed, isn't?
