### ISSUE TITLE
Telebot processing location

### ISSUE THREAD

**Issue by merkfrom** [eternnoir/pyTelegramBotAPI#2023]
1. What version of pyTelegramBotAPI are you using?
4.12.0
2. What OS are you using?
Windows 10
3. What version of python are you using?
3.9

I have user sharing live location with bot. I then want to save this location every 5 seconds. 

The thing is, the location message doesn't seem to be updating, even though the user moves, and the point is moving in telegram chat.

How do I retrieve the "live" location from live location message?

**Comment by gerswin** [comment]
Hello how you  retrieve the "live" location?
