### ISSUE TITLE
PhotoSize not deserialise. I can't get file_id

### ISSUE THREAD

**Issue by Deniallugo** [eternnoir/pyTelegramBotAPI#203]
I send photo like this:
 res = self.telebot_bot.send_photo(chat_id=chat_id,photo=open(bot_message.file, "rb"),
                                        caption=bot_message.text)

When I print res. I Have 

{'photo':` [ telebot.types.PhotoSize object at 0x7f7db23efc50 , telebot.types.PhotoSize object at 0x7f7db24068d0 ,  telebot.types.PhotoSize object at 0x7f7db2406a58], 

I think, that telebot.types.PhotoSize not deserialize

**Comment by Kondra007** [comment]
```
for item in res["photo"]:
    print(item.file_id)
```

Try this.
