### ISSUE TITLE
Ability to convert Message and other objects to JSON.

### ISSUE THREAD

**Issue by bmusin** [eternnoir/pyTelegramBotAPI#204]
Hi, eternnoir, thanks for your useful library.
I am currently working on integrating my bots with Botan(botan.io)
that requires messages to be JSON.

When I do json.dumps(message) I get
<telebot.types.Message object at 0x7f48036869e8> is not JSON serializable,
that is very inconvenient to create JSON manually, library can perform it without bothering the user.

I think a lot of people will benefit from it. Thanks.

**Comment by eternnoir** [comment]
If you only want to get message's data by json format not origin message json string from telegram bot api. I recommend use [jsonpickle](http://jsonpickle.github.io/) to serialize message to json format.

```python
import jsonpickle
print(jsonpickle.encode(message))
```

**Comment by moldabekov** [comment]
@bltnkl, I solved this task by enhancing `botan.py`. You may look at my [repo](https://github.com/moldabekov/sdk). I sent [pull request](https://github.com/botanio/sdk/pull/76) to the origin repo to merge the changes.

**Comment by Kondra007** [comment]
@moldabekov Botan has no connection to pyTelegramBotAPI. It's only up to you to edit botan.py to serve your purposes. Incorrect issue.

**Comment by user2020-py** [comment]
Hello

**Comment by user2020-py** [comment]
Follow me
