### ISSUE TITLE
Bot ignoring message handlers after some time of work

### ISSUE THREAD

**Issue by M1KTA-OFF** [eternnoir/pyTelegramBotAPI#2050]
What version of pyTelegramBotAPI are you using? - Latest
What OS are you using? - Ubuntu 23 (Server)
What version of python are you using? - 3.11

After some time bot ignoring any message handler, so it completely unresponsable.
BUT middleware handler handles all text from users.
This is very strange issue that appears twice or more per day.
Maybe someone know how to solve it.

**Comment by Badiboy** [comment]
Please, provide example how you handle messages. Both with middleware and ordinal handlers. Nothing can be said without example of your code.

**Comment by M1KTA-OFF** [comment]
`# Registering handlers
        self.bot.register_middleware_handler(self.middleware_handler, update_types=["message"])
        self.bot.register_message_handler(self.start_command, commands=["start"])
        self.bot.register_message_handler(self.register_command, commands=["register"])
        self.bot.register_message_handler(self.commands, content_types=["text", "photo"])
        self.bot.register_callback_query_handler(self.callbacks, func=lambda call: True)
        self.main_logger.info("Handlers registered")`
Handlers registered like that

**Comment by Badiboy** [comment]
Ok, no problem: if you do not need help - you will not get help.

**Comment by M1KTA-OFF** [comment]
> Ok, no problem: if you do not need help - you will not get help.

Sorry, but code is wrote for my client. And I can't post it to public. 
I found that bot ignoring or answers with very big delay, while it changes message for another user.
Maybe i miss some important parameters for bot?

`while True:
    try:
        bt.bot.infinity_polling(skip_pending=True)
    except Exception as e:
        bt.main_logger.critical(e)`

**Comment by M1KTA-OFF** [comment]
Hell no, bot just don't want to work properly. After sometime it just ignores updates.
Like it receives it, but do NOTHING.
Please somebody help, i can't find a solution for a month.
I attached piece of log as file.
[telebot.log](https://github.com/eternnoir/pyTelegramBotAPI/files/12713063/telebot.log)

**Comment by M1KTA-OFF** [comment]
@Badiboy Я очень прошу помочь, я предоставлю любую часть кода. Пожалуйста.

**Comment by demonlibra** [comment]
Т.е. проблема не связана с последним обновлением до 14.4.0 ?

**Comment by M1KTA-OFF** [comment]
> Т.е. проблема не связана с последним обновлением до 14.4.0 ?

Не уверен в этом. Но факт остается фактом, бот игнорирует апдейты.

**Comment by demonlibra** [comment]
Пользуюсь этим расширением год. Режим синхронный, метод опроса polling. Проблем в работе не замечал.
Попробуйте запустить бота на другом сервере или ПК из другой сети.

**Comment by Hamiiim** [comment]
Should not ignore the update, you check the log whether the connection timeout, it should be the telegram team at work caused by this time I often do

**Comment by demonlibra** [comment]
> > Т.е. проблема не связана с последним обновлением до 14.4.0 ?
> 
> Не уверен в этом. Но факт остается фактом, бот игнорирует апдейты.

3-й день после обновления на 4.14.0 Полёт нормальный.
Нашли проблему?

**Comment by coder2020official** [comment]
Привет.
Не думаю что проблема связана напрямую с библиотекой. Я бы порекомендовал попробовать изменить тайп апдейтов через поллинг:
bot.infinity_polling(allowed_updates=util.update_types)
Также рекомендую продебажить и посмотреть, действительно ли апдейты не прилетают. В readme написано, как дебажить.

**Comment by coder2020official** [comment]
If you are still receiving updates with a delay, please tell

**Comment by coder2020official** [comment]
No information
