### ISSUE TITLE
Library raising Request timeout in sendVideo before time is out

### ISSUE THREAD

**Issue by DimaDDM** [eternnoir/pyTelegramBotAPI#2057]
Hello. I talked about this bug a couple of days ago in https://github.com/eternnoir/pyTelegramBotAPI/discussions/2054

sometimes, when uploading medium-sized files, in the cases indicated by me in the previous task, the `sendVideo` function returns a RequestTimeout error, although the timeout time has not expired. In my case, i call function at `05.10.23 22:42:06`
with timeout = 10 minutes  and exception was at `2023-10-05 22:45:12`

**Comment by Badiboy** [comment]
One topic is enough.

**Comment by DimaDDM** [comment]
> One topic is enough.

It's not timeout parameter problem
