### ISSUE TITLE
@bot.message_handler decorator seems to timeout running process after some time

### ISSUE THREAD

**Issue by src203** [eternnoir/pyTelegramBotAPI#2058]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.14.0 (latest)
2. What OS are you using?
Ubuntu 22.04
3. What version of python are you using?
Python 3.10.12

I've created a telegram bot that let's users execute a python script from my server the script actually scrapes information from lots of websites and then display it back to user using`requests` library. This is my approach to do it
```python
import telebot
import requests

from functions.scrape import scrape

API_KEY = 'MY_KEY'

bot = telebot.TeleBot(API_KEY)

@bot.message_handler(commands=['start', 'help'])

def help(message):
	bot.send_message(message.chat.id, """
		ℹ️ **Command Menu** ℹ️
       /help - Displays the command menu
       /run - scrape information
""")

@bot.message_handler(commands=['run'])

def run(pm):
    values = scrape()
	bot.send_message(pm.chat.id, f"scraped values: {values}")

bot.polling()
```
The script works fine and does execute the `scrape` function however some requests from 
my script automatically fails (out of 300 only 170 requests succeed)

Note - I know the problem lies with telebot itself and not my script cause when i run the same script on my server directly it works flawless without any failed requests i wanted to know what possible reasons might be causing it and how can i fix it or if there any other alternative solutions.

**Comment by coder2020official** [comment]
use bot.infinity_polling

**Comment by coder2020official** [comment]
and the context is not enough. it might be your code's issue since you are using requests and sending requests to random websites.

**Comment by src203** [comment]
> use bot.infinity_polling

Sorry but how do using `bot.infinity_polling` will fix my use I guess they are completely unrelated and have different usage and yeah I do use it on actual server and it outputs the same error

**Comment by src203** [comment]
> and the context is not enough. it might be your code's issue since you are using requests and sending requests to random websites.

And no I am 100% sure the problem lies with the telebot itself executing my script directly works with no issue the problem is with this buggy module which am never gonna use cause it closes it's users issues without even looking at it

**Comment by Badiboy** [comment]
We are 100% sure that when executing YOUR script problem definitely lies with YOUR script. Because telebot do nothing with your script and your requests.
