### ISSUE TITLE
restrict_chat_member The result is asymmetrical

### ISSUE THREAD

**Issue by Hamiiim** [eternnoir/pyTelegramBotAPI#2059]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.13
2. What OS are you using?
ubuntu 22.04
3. What version of python are you using?
3.11.4

bot.restrict_chat_member(chat_id, user_id, can send messages=False)
I get this result when I can only disable people from talking:
Changed permissions of source listing - Xiaoliu (@Xiaoliu17): permanent

−Send Sticker GIF
−Link preview
−Initiate voting
−Change information
−Add members
− Pinned message
−Create topic
−Send pictures
−Send video
−Send video
−Send music
−Send voice
−Send files
−Send message

bot.restrict_chat_member(chat_id, user_id, can_send_messages=True)
What I get when I unban me:
Changed permissions of source listing - Xiaoliu (@Xiaoliu17): permanent

+Send message

These two results are not symmetrical

**Comment by Badiboy** [comment]
First of all:
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/5613421/d66644e2-ac16-49c0-a0b3-eecc18501ffd)

**Comment by Badiboy** [comment]
Secondly. 

If you do not pass value for any of permission (neither True or False) it is not passed to Telegram and thus restrict chat member works exactly as it is implemented in the Telegram. You can claim their support if you do not like the API function behaviour.
