### ISSUE TITLE
Timeout error causes app to crash, while bot.polling(non_stop=True)

### ISSUE THREAD

**Issue by grz667** [eternnoir/pyTelegramBotAPI#206]
Hi eternnoir, thanks for the library!

subject: I have, an timeout error while non_stop polling. This causing app to crash.
Is there a native way, to ignore such kind of errors and continue polling?
 
i use simple code example
```
if __name__ == '__main__':
        bot.polling(none_stop=True)

```
> Traceback (most recent call last):
>   File "C:\Users\anatoliy.piskunov\Desktop\PyTBot\bot.py", line 184, in <module>
>     bot.polling(none_stop=True) #constantly get messages from Telegram
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\telebot\__init__.py", line 192, in polling
>     self.__threaded_polling(none_stop, interval, timeout)
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\telebot\__init__.py", line 215, in __threaded_polling
>     polling_thread.raise_exceptions()
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\telebot\util.py", line 73, in raise_exceptions
>     six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\six.py", line 686, in reraise
>     raise value
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\telebot\util.py", line 54, in run
>     task(*args, **kwargs)
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\telebot\__init__.py", line 122, in __retrieve_updates
>     updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\telebot\__init__.py", line 92, in get_updates
>     json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\telebot\apihelper.py", line 139, in get_updates
>     return _make_request(token, method_url, params=payload)
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\telebot\apihelper.py", line 34, in _make_request
>     result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\requests\api.py", line 57, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\requests\sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\requests\sessions.py", line 585, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Program Files (x86)\Python35-32\lib\site-packages\requests\adapters.py", line 459, in send
>     raise ConnectTimeout(e, request=request)
> requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot<%bot_name%>:<%bot_token%>/getUpdates?timeout=20&offset=1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x03D83430>, 'Connection to api.telegram.org timed out. (connect timeout=3.5)'))

**Comment by eternnoir** [comment]
How about this?

```
if __name__ == '__main__':
    while True:
        try:
            bot.polling(none_stop=True)
        except Exception as ex:
            logger.error(ex)
```

**Comment by grz667** [comment]
@eternnoir Thanx for such a quicq reply!
I've solution you suggested firstly, but error stays the same. Process still crashes.
I've enlarged timeout to 60, and problem almost faced away.

testing now this construction:

```
def telegram_polling():
    try:
        bot.polling(none_stop=True, timeout=60) #constantly get messages from Telegram
    except:
        traceback_error_string=traceback.format_exc()
        with open("Error.Log", "a") as myfile:
            myfile.write("\r\n\r\n" + time.strftime("%c")+"\r\n<<ERROR polling>>\r\n"+ traceback_error_string + "\r\n<<ERROR polling>>")
        bot.stop_polling()
        time.sleep(10)
        telegram_polling()
        
if __name__ == '__main__':    
    telegram_polling()
```
and this is working fine for now.
i think, polling crashing because of constantly appearing identical errors in **requests** object.

**Comment by eternnoir** [comment]
Because polling method only catch telebot's ApiException. If exception cause by networking problem telebot polling will throw it.

**Comment by grz667** [comment]
@eternnoir Thank you a lot, for help with understanding this issue.
and for API of-course!
i think issue must be closed

**Comment by Said707** [comment]
> @eternnoir Thanx for such a quick reply!
> I've tried solution you suggested firstly, but error stays the same. Process still crashes.
> I've enlarged timeout to 60, and problem almost faced away.
> 
> testing now this construction:
> 
> ```
> def telegram_polling():
>     try:
>         bot.polling(none_stop=True, timeout=60) #constantly get messages from Telegram
>     except:
>         traceback_error_string=traceback.format_exc()
>         with open("Error.Log", "a") as myfile:
>             myfile.write("\r\n\r\n" + time.strftime("%c")+"\r\n<<ERROR polling>>\r\n"+ traceback_error_string + "\r\n<<ERROR polling>>")
>         bot.stop_polling()
>         time.sleep(10)
>         telegram_polling()
> 
> if __name__ == '__main__':    
>     telegram_polling()
> ```
> and this is working fine for now.
> i think, polling crashing because of constantly appearing identical errors in **requests** object, because i see in my errorlog
> `During handling of the above exception, another exception occurred:`

Why are you writing this thing in a file? Is there any reason for this? Can you please explain
Because I had the same problem and I would use your solution, that's way, I want to understand
Thank you in advance!

**Comment by aditya-dev201** [comment]
just use bot.infinity_polling(), its the best
