### ISSUE TITLE
There is no message_thread_id in json

### ISSUE THREAD

**Issue by Zapzatron** [eternnoir/pyTelegramBotAPI#2061]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.14.0
2. What OS are you using?
Windows
3. What version of python are you using?
3.10.9

There is no message_thread_id in json when writing from a topic in the telegram web A group, but when writing from a topic in the telegram desktop group, it is there.

**Comment by coder2020official** [comment]
Fixed?

**Comment by Zapzatron** [comment]
No, but as I understand it this is a telegram web bug, not pytelegrambotapi

**Comment by Zapzatron** [comment]
This happens because in telegram web, when you send a command in a topic, it is redirected to the main chat. But in the desktop version, it sends to the same chat from which the request was made.
So this is a bug in Telegram web, there is a chance that they will fix it someday.
