### ISSUE TITLE
I am Proud Of You. Chad

### ISSUE THREAD

**Issue by Jankovlski** [eternnoir/pyTelegramBotAPI#2063]
Regarding [this line](https://github.com/eternnoir/pyTelegramBotAPI/blob/9f887e72c4fcc318e645a82f8e6d0199d0b8febf/examples/step_example.py#L71C30-L71C37)

I am Proud Of You. 

![Developer](https://github.com/eternnoir/pyTelegramBotAPI/assets/66574700/f52d566f-e44b-494f-9819-4ffb5f1eac18)
Chad

**Comment by Jankovlski** [comment]
![Developer](https://media.tenor.com/epNMHGvRyHcAAAAC/gigachad-chad.gif)

**Comment by coder2020official** [comment]
Lol 😂
