### ISSUE TITLE
not enough rights to send text messages to the chat

### ISSUE THREAD

**Issue by enakhi** [eternnoir/pyTelegramBotAPI#2068]
My bot was working until last night. I added the bot to my channels, and it has admin privileges in the channels. However, when I try to send a message to my channels, I receive this error message.

File "/usr/local/lib/python3.9/site-packages/telebot/__init__.py", line 1549, in send_message
apihelper.send_message(
File "/usr/local/lib/python3.9/site-packages/telebot/apihelper.py", line 264, in send_message
return _make_request(token, method_url, params=payload, method='post')
File "/usr/local/lib/python3.9/site-packages/telebot/apihelper.py", line 162, in _make_request
 json_result = _check_result(method_name, result)
File "/usr/local/lib/python3.9/site-packages/telebot/apihelper.py", line 189, in _check_result raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: not enough rights to send text messages to the chat

pyhton 3.9
docker FROM python:3.9.1

latest version of pyTelegramBotAPI

**Comment by 94wogus-quantit** [comment]
same issue here

**Comment by icylian** [comment]
Same here
{"ok":false,"error_code":400,"description":"Bad Request: the message can't be copied"}

**Comment by keyiflerolsun** [comment]
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/57468649/b5f83b5a-218b-402f-944c-94e59f64e911)

**Comment by hekut146** [comment]
I have the same problem

**Comment by mohsenrahmani145** [comment]
I have this problem today
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/104733355/b01b1232-d807-44df-b8a2-9ded7a692f8e)

**Comment by matveybuk** [comment]
You're not alone. The first time I thought it was my mistake, but it's not. The problem is in the telegram api, there is a bug on their side.

**Comment by hekut146** [comment]
Now work for me

**Comment by Badiboy** [comment]
Today there are issues with Telegram bot API on Telegram side. 

Just wait, they will fix it.

**Comment by coder2020official** [comment]
Bot API experienced such issue for 4 hrs :(
