### ISSUE TITLE
The bot stopped processing callback_query_handler

### ISSUE THREAD

**Issue by mookor** [eternnoir/pyTelegramBotAPI#2069]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI   4.14.0

2. What OS are you using?
Windows 10

3. What version of python are you using?
3.10.11

I have a simple code to test
```
import telebot
from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton

bot = telebot.TeleBot("TOKEN")

@bot.callback_query_handler(func=lambda call: True)
def button(call):
    if call.data == 'button1':
        bot.send_message(call.message.chat.id, 'BUTTON1')
    elif call.data == 'button2':
        bot.send_message(call.message.chat.id, 'BUTTON2')

@bot.message_handler(commands=['start'])
def start(message):
    keyboard = InlineKeyboardMarkup()
    keyboard.row(InlineKeyboardButton('BUTTON1', callback_data='button1'))
    keyboard.row(InlineKeyboardButton('BUTTON2', callback_data='button2'))

    bot.send_message(message.chat.id, 'Привет, выберите кнопку:', reply_markup=keyboard)

bot.polling()
```

Everything used to work fine, but now nothing happens when you click on the buttons, I checked with a debugger, he never goes to callback_query_handler
maybe it has something to do with the latest telegram update?

**Comment by Badiboy** [comment]
Firstly use infinity_polling.

**Comment by mookor** [comment]
> Firstly use infinity_polling.

This does not solve the problem

Updating the bot token helped, while the token was valid and the rest of the functionality worked fine
