### ISSUE TITLE
Method `handle` in `ExceptionHandler` class is sync in async telebot

### ISSUE THREAD

**Issue by oalexandere** [eternnoir/pyTelegramBotAPI#2070]
1. What version of pyTelegramBotAPI are you using?
name = "pytelegrambotapi"
version = "4.12.0"

2. What OS are you using?
macOs

3. What version of python are you using?
python3.11

Class `ExceptionHandler` for async bot [has synchronous method](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/async_telebot.py#L55) def handle(exception).
It would be nice if method for that class also be async, i.e. `async def handle(exception)`.

Example usage and reason: I want to send notification message from my bot to me using telegram if some exception occurs. I have async telebot instance which can do that, but method `handle` is sync.

**Comment by Badiboy** [comment]
Could you please make update, test it and then pull?

**Comment by oalexandere** [comment]
@Badiboy hello, here it is, can you check it please? https://github.com/eternnoir/pyTelegramBotAPI/pull/2074
Thanks!
