### ISSUE TITLE
Cannot use markups in Iphones and desktop app

### ISSUE THREAD

**Issue by alienscientist** [eternnoir/pyTelegramBotAPI#2080]
hey, I developed a bot and used ReplyKeyboardMarkup function to get input from user. Somehow, the options can only seen in Android phones. Iphones and Telegram desktop cannot see the options when called /get_some_data method. Anyone encountered the same issue? How to solve? 

Here is my code:

`import telebot
from telebot import types

bot = telebot.TeleBot(token, parse_mode=None)

@bot.message_handler(commands=['get_some_data'])
def get_marketplace(message):
    chat_id = message.chat.id
    topic_id = message.message_thread_id
    
    markup = types.ReplyKeyboardMarkup(row_width=1, resize_keyboard=True, one_time_keyboard=True)
    for mp in ["somedata1", "somedata2", "somedata3"]:
        itembtn = types.KeyboardButton(mp)
        markup.add(itembtn)
    bot.send_message(chat_id, "Please select an option:", reply_markup=markup, reply_to_message_id=topic_id)

bot.infinity_polling(interval=0, timeout=25)`

**Comment by coder2020official** [comment]
Hmmm, sounds strange. Maybe try setting is_persistent=True

**Comment by alienscientist** [comment]
Yes, that works! Thanks.

**Comment by alienscientist** [comment]
> Hmmm, sounds strange. Maybe try setting is_persistent=True
Yes, that works!. Thanks.
