### ISSUE TITLE
Async API for the register_next_step_handler() method present in the non-async API ---> TeleBot.register_next_step_handler()

### ISSUE THREAD

**Issue by avadhut-00** [eternnoir/pyTelegramBotAPI#2086]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? : 4.14.0

3. What OS are you using? Windows 11 

4. What version of python are you using? 3.12.0

I need help in moving my non-async script to async one and I am using the TeleBot.register_next_step_handler() method in the my script. I am passing *args to the callback  function. As this method is not present in the async API of Telebot I am wondering how to go about it. The official examples in the repository: [pyTelegramAPI official examples](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/step_example.py) provides guidance for the non-async API. Please let me know a way to implement the same example with the async API of telebot.

**Comment by coder2020official** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/asynchronous_telebot/custom_states.py

**Comment by coder2020official** [comment]
States are a better and improved version of steps that are present for both versions. Try it out

**Comment by hiddify-com** [comment]
#2344
