### ISSUE TITLE
How do i stop the bot?

### ISSUE THREAD

**Issue by FoxFil** [eternnoir/pyTelegramBotAPI#2098]
I tried exit(), sys.exit(), sys.exit(0) but nothing seem to work. Would appreciate any help!

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.14.0

2. What OS are you using?
Windows

3. What version of python are you using?
3.11.0

**Comment by Badiboy** [comment]
stop_polling
