### ISSUE TITLE
deploying to heroku - ImportError: cannot import name 'logger'

### ISSUE THREAD

**Issue by ETarasenok** [eternnoir/pyTelegramBotAPI#212]
Hello, 
could you kindly help me. I'am trying to deploy my bot to the heroku but have import error:    

$ heroku run python3 bot.py
Running python3 bot.py on ⬢ fffmoex... up, run.7802
Traceback (most recent call last):
  File "bot.py", line 5, in <module>
    from telebot import types
  File "/app/.heroku/python/lib/python3.5/site-packages/telebot/types.py", line 6, in <module>
    from telebot import util
  File "/app/.heroku/python/lib/python3.5/site-packages/telebot/util.py", line 16, in <module>
    from telebot import logger
ImportError: cannot import name 'logger'

Bot working perfectly on the local console (mac os) and there is no "logger" in my code.  

pyTelegramBotAPI (2.1.5)
Python 3.5.1
Django 1.9.8
Heroku on linux

**Comment by talipomin** [comment]
are pyTelegramBotAPI and telebot are in your requirements.txt ?

**Comment by ETarasenok** [comment]
my requirements.txt

pyTelegramBotAPI==2.1.5
py==1.4.29
pytest==2.7.2
requests==2.7.0
six==1.9.0
wheel==0.24.0
Django==1.9.8
telebot==0.0.3
logger==1.4

**Comment by ETarasenok** [comment]
solved this problem by reinstalling pyTelegramBotAPI via pip

**Comment by honeypy** [comment]
Hello,
I have the same problem, could you help me?

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from telebot import types
  File "/app/.heroku/python/lib/python3.5/site-packages/telebot/types.py", line 10, in <module>
    from telebot import util
  File "/app/.heroku/python/lib/python3.5/site-packages/telebot/util.py", line 16, in <module>
    from telebot import logger
ImportError: cannot import name 'logger

reinstalling via pip doesn't help

my requirements file is:
PyTelegramBotAPI
requests
telebot
flask

**Comment by Breganov** [comment]
> Hello,
> I have the same problem, could you help me?
> 
> Traceback (most recent call last):
> File "main.py", line 4, in 
> from telebot import types
> File "/app/.heroku/python/lib/python3.5/site-packages/telebot/types.py", line 10, in 
> from telebot import util
> File "/app/.heroku/python/lib/python3.5/site-packages/telebot/util.py", line 16, in 
> from telebot import logger
> ImportError: cannot import name 'logger
> 
> reinstalling via pip doesn't help
> 
> my requirements file is:
> PyTelegramBotAPI
> requests
> telebot
> flask

Did you resolve your issue?
