### ISSUE TITLE
Issue with disable_web_page_preview

### ISSUE THREAD

**Issue by coder2020official** [eternnoir/pyTelegramBotAPI#2122]
LinkPreviewOptions has is_disabled parameter, and not disable_web_page_preview.
[See this](https://github.com/eternnoir/pyTelegramBotAPI/blob/956c2697a201e0ef03b16bc064a2367b73b2785f/telebot/__init__.py#L1661C17-L1661C17)
[And this](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/types.py#L8589)

@Badiboy, do you have time to fix all of that? If you don't, I will be able to complete all of this by Friday evening

**Comment by coder2020official** [comment]
And this is the reason I insisted on not hurrying with release :)

**Comment by coder2020official** [comment]
+ https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/__init__.py#L1664

**Comment by coder2020official** [comment]
And same thing happens with each method

**Comment by Badiboy** [comment]
> @Badiboy, do you have time to fix all of that? If you don't, I will be able to complete all of this by Friday evening

I'll check. Hope that I'll have.

**Comment by Badiboy** [comment]
> And this is the reason I insisted on not hurrying with release :)

I totally agreed with you then and agree now )

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/2123
