### ISSUE TITLE
!URGENT - InaccessibleMessage

### ISSUE THREAD

**Issue by Badiboy** [eternnoir/pyTelegramBotAPI#2130]
@coder2020official 

Due to new InaccessibleMessage returned for some cases I got a lot of troubles in project. Before I can access fields like 
message.from and check if they are filled:
```
if message.from_user:
   ...
```
and lot of other fields of message. They were always presented but None if not accessible.

Now all such code raises exceptions, because InaccessibleMessage **has no such fields**! 

For me personally I'll update the project, it's not so critical. **BUT. It will bring great backward incompatibility for thousands of users.**

I propose to inherit InaccessibleMessage from Message to keep compatibility.

**Comment by Badiboy** [comment]
Or at least make some stubs returning None with warnings in InaccessibleMessage to prevent such fails.

**Comment by coder2020official** [comment]
Yes, we didn't think of that..
What are the side effects of inheriting message in inaccessiblemessage?
It is a hard decision, because firstly, by inheriting message we will probably introduce more trouble.. secondly, I believe we cannot do anything against API change which breaks everything... So I guess maybe we could return warnings when trying to access non-existent fields in the class..

**Comment by Badiboy** [comment]
I also do not like that. But the situation is really VERY bad. Once again: not for me, but for users. I know what happend and will care about it).

Wait, i'll think about making some kind of universal stub for any Message field there. I'll let you know.

**Comment by Badiboy** [comment]
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/5613421/e9def844-1c3a-44b9-839f-cda78da20399)

Did not found better way, because fields of Message are dynamically constructed and this cannot be automated.

**Comment by Badiboy** [comment]
PS. This idea of adding InaccessibleMessage to Bot API is really shitty. 😔

**Comment by coder2020official** [comment]
why not use __getattr__?

**Comment by Badiboy** [comment]
> because fields of Message are dynamically constructed and this cannot be automated
👆

**Comment by Badiboy** [comment]
Or you mean override it?

**Comment by coder2020official** [comment]
"Called when an attribute lookup has not found the attribute in the usual places (i.e. it is not an instance attribute nor is it found in the class tree for self)."
Why not just create getattr function in inaccessiblemessage ?

**Comment by coder2020official** [comment]
and maybe remove inheriting from message to make it work

**Comment by Badiboy** [comment]
> Why not just create getattr function in inaccessiblemessage ?

I'll check, thanks.

**Comment by Badiboy** [comment]
> and maybe remove inheriting from message to make it work

No inheritance.

**Comment by Badiboy** [comment]
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/5613421/6fc17ea2-14ef-484f-9f4d-0b3eb219f25a)

Like this?

**Comment by coder2020official** [comment]
Yes

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/2131
