### ISSUE TITLE
Implement blacklist

### ISSUE THREAD

**Issue by Jzarecta** [eternnoir/pyTelegramBotAPI#214]
Is there a way I can programatically block users from the API?
I get users trying to DDoS the bot and want to implement some type of blocking mechanism for bad actors.

**Comment by selfus** [comment]
@Jzarecta I think you can add a blacklist on the bot side, and make the bot ignore(don't send a reply/take no action) messages from blacklisted users, but you would still need to process the received messages.
Would this help?
