### ISSUE TITLE
InlineKeyboardButton doesn't work last time

### ISSUE THREAD

**Issue by LazyPythonCoder** [eternnoir/pyTelegramBotAPI#2148]
Telebot 4.15.3/OS -WIN 10 64
Sо I have simple code, when I start program I can see meesage and button, but when pressed the button - nothing! In is very strange because this code worked some mounths ago!

import telebot
from telebot import types

bot = telebot.TeleBot('key')

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    button_text = "Press me"
    button_value = "button_pressed"
    button = types.InlineKeyboardButton(text=button_text, callback_data=button_value)
    message_text = "Press the button"
    reply_markup = types.InlineKeyboardMarkup(row_width=1)
    reply_markup.add(button)
    bot.send_message(message.from_user.id, text=message_text, reply_markup=reply_markup)

@bot.callback_query_handler(func=lambda call: True)
def handle_button_press(call):
    print(call.message)
    bot.send_message(call.message.chat.id, text='Button pressed')

bot.infinity_polling()

**Comment by Badiboy** [comment]
Telebot 4.15.3/OS -WIN 10 64

Works fine.
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/5613421/12d3ba28-b637-4ff5-98c0-6d8d00886da0)

**Comment by LazyPythonCoder** [comment]
Very strange. My code does not work at all. I press the button and nothihg..

**Comment by LazyPythonCoder** [comment]
I have done problem. I created new bot and that everythibg is OK. But I very surprized that I had not done any changes in old bot.
