### ISSUE TITLE
Forward messages without quoting

### ISSUE THREAD

**Issue by DarkEagle82** [eternnoir/pyTelegramBotAPI#215]
Is possible to forward a message with the command forward_message(to_chat_id, from_chat_id, message_id) without quoting ?

Thx in advance.

**Comment by selfus** [comment]
What do you mean?

Maybe I can help if you give further details.

**Comment by Kondra007** [comment]
Yes, that's possible. Check my [proxy-bot](https://bitbucket.org/master_groosha/telegram-proxy-bot) project for details. Oh, and it uses pyTelegramBotAPI under the hood.

**Comment by MonsterDeveloper** [comment]
Maybe you can try to just send message text like `message.text` and send it to another user using `send_message` method?
