### ISSUE TITLE
send standard msg

### ISSUE THREAD

**Issue by pietrondo** [eternnoir/pyTelegramBotAPI#216]
Hello, I'm newbie but I have a question:
how I can send a standard msg to the user when it start the bot?
In this msg I would say the default command.
thx

**Comment by kostyakoz** [comment]
Hello, what do u mean by “standard” message?

You can create handler for command `/start`:

```python
@bot.message_handler(commands=['start'])
def start(message):
     bot.send_message(message.chat.id, 'Commands is /one_command, /two_command, etc.')
