### ISSUE TITLE
unknown error(i dont have a screenshots sorry)

### ISSUE THREAD

**Issue by Sonys9** [eternnoir/pyTelegramBotAPI#2160]
2024-01-28 21:02:09,027 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): ChatBoost.init() missing 3 required positional arguments: 'boost_id', 'add_date', and 'expiration_date'"

**Comment by Sonys9** [comment]
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/137277008/22f9b5f9-2110-41ed-94d5-c7fe9b7a2a1f)

**Comment by coder2020official** [comment]
Version?

**Comment by Badiboy** [comment]
Try to install and use current GIT version:
pip install -U git+https://github.com/eternnoir/pyTelegramBotAPI.git
If will not be updated - run:
pip uninstall --yes pyTelegramBotAPI
before.

If you will see warnings - please, let us know.

**Comment by coder2020official** [comment]
I see this is boost-related? Will try to test it at some point myself

**Comment by Sonys9** [comment]
thank you

**Comment by Daloshka** [comment]
pip install -U git+https://github.com/eternnoir/pyTelegramBotAPI.git
Helped me
