### ISSUE TITLE
What should I do to make the telebot stop handling errors?

### ISSUE THREAD

**Issue by Zapzatron** [eternnoir/pyTelegramBotAPI#2161]
1. What version of pyTelegramBotAPI are you using?
4.15.3
2. What OS are you using?
Windows
3. What version of python are you using?
3.10.9

What should I do to make the telebot stop handling errors?
Because the telebot gives little information about the error.
I need to be able to handle the error myself.
I have `class ExceptionHandler(telebot.async_telebot.ExceptionHandler):`, but it doesn't always receive the error.

Example of small error information from telebot:
2024-02-08 17:17:14,295 (asyncio_helper.py:101 MainThread) ERROR - TeleBot: "Aiohttp ClientError: ClientConnectorError"

**Comment by Zapzatron** [comment]
Tried `telebot.logger.setLevel(logging.CRITICAL + 1)`, but it just stopped doing logging, but it won't let me handle the error myself.

**Comment by coder2020official** [comment]
Set to debug to get full information.

**Comment by Zapzatron** [comment]
I have my own exception handler and I catch and handle errors in it. `telebot.async_telebot.ExceptionHandler` is sometimes called and sometimes not.

**Comment by coder2020official** [comment]
you can't handle connection errors with exception handler afaik

**Comment by Badiboy** [comment]
> 2024-02-08 17:17:14,295 (asyncio_helper.py:101 MainThread) ERROR - TeleBot: "Aiohttp ClientError: ClientConnectorError"

This error is raised when doing requests to Telegram. In two cases:
1. When you make a request (like send_message). In this case you can handle it yourself when calling the function
2. When update_requests are called. Here you can use ExceptionHandler to handle the errir.
Note, that it is re-raised as asyncio_helper.RequestTimeout exception, not Aiohttp ClientError. And the error logging will be done anyway.
