### ISSUE TITLE
GiveawayCreated de_json raises NotImplemented error when the bot starts

### ISSUE THREAD

**Issue by YouRockGarnov** [eternnoir/pyTelegramBotAPI#2169]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.15.4
2. What OS are you using?
Linux (Ubuntu)
3. What version of python are you using?
3.11

bot  | 2024-02-16 11:42:53,156 (__init__.py:1023 MainThread) ERROR - TeleBot: "Exception traceback:
bot  | Traceback (most recent call last):
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 1016, in infinity_polling
bot  |     self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 1104, in polling
bot  |     self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 1179, in __threaded_polling
bot  |     raise e
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 1140, in __threaded_polling
bot  |     polling_thread.raise_exceptions()
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/util.py", line 110, in raise_exceptions
bot  |     raise self.exception_info
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/util.py", line 92, in run
bot  |     task(*args, **kwargs)
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 661, in __retrieve_updates
bot  |     updates = self.get_updates(offset=(self.last_update_id + 1),
bot  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 636, in get_updates
bot  |     return [types.Update.de_json(ju) for ju in json_updates]
bot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/__init__.py", line 636, in <listcomp>
bot  |     return [types.Update.de_json(ju) for ju in json_updates]
bot  |             ^^^^^^^^^^^^^^^^^^^^^^^^
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/types.py", line 190, in de_json
bot  |     message = Message.de_json(obj.get('message'))
bot  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/types.py", line 1265, in de_json
bot  |     opts['giveaway_created'] = GiveawayCreated.de_json(obj['giveaway_created'])
bot  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bot  |   File "/usr/local/lib/python3.11/site-packages/telebot/types.py", line 76, in de_json
bot  |     raise NotImplementedError
bot  | NotImplementedError

**Comment by Badiboy** [comment]
Update from pypi, this bug fix is uploaded now.
