### ISSUE TITLE
How can I "iterate" an Exception?

### ISSUE THREAD

**Issue by surik00** [eternnoir/pyTelegramBotAPI#217]
1. I'm using the latest version of API
2. I'm using mixed Ubuntu and OS X
3. I'm using python 3.4 and higher

When I catch an Exception using _try / except as e_ and then _print(e)_ I get something like this 
_A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[b'{"ok":false,"error_code":403,"description":"Bot was blocked by the user"}']_
So I want to fetch **description** 
So then I can work with this error. In this example bot will understand that it's blocked and do some action
I tried to iterate it using [], tried _e.description_ etc but it always returns an error _invalid syntax_ or not _iterable_
Of course I can convert error to string and then fetch data using regular expressions but maybe there is a way to catch an error and determine what type of error it is
Best regards

**Comment by kostyakoz** [comment]
Interested in this feature too, tried to use string, but it isn't works nice.

**Comment by eternnoir** [comment]
If you except `ApiException` you can use `ApiException.result` to get telegram bot api response message.
