### ISSUE TITLE
What happens to messages that don't enable a bot reaction?

### ISSUE THREAD

**Issue by selfus** [eternnoir/pyTelegramBotAPI#218]
What will happen to the messages that have a command that the bot is not ready to take an action?

Will they bounce between the bot and server forever?

**Comment by kostyakoz** [comment]
@selfus messages that bot can't handle now, just ignoring (any messages type, commands etc.)

**Comment by selfus** [comment]
But, are they ignored and marked as read, or someday, when I start to support more commands, those messages may arrive?

**Comment by kostyakoz** [comment]
@selfus yes, they are ignored and marked as read (if your bot working and received all messages with `polling` or `webhooks`). Nothing will happens when you start to support more commands.

**Comment by bvanrijn** [comment]
Messages to bots are only stored on Telegram's servers for 24 hours. After that, they are gone.
