### ISSUE TITLE
Build using setup.py isn't possible anymore

### ISSUE THREAD

**Issue by helioloureiro** [eternnoir/pyTelegramBotAPI#2180]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

I'm trying to build from sources 4.16.0.

2. What OS are you using?

Archlinux

3. What version of python are you using?
3.11.7

README.md has wrong information right now.

![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/6479951/25b92a69-34db-4c03-aaab-dda9235cfaea)

setup.py was removed on commit 0d2b886ab70d51ea8eecb8a54443c5eaaa9bacb7

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/2181
