### ISSUE TITLE
MenuButton implementation

### ISSUE THREAD

**Issue by KingRotiv** [eternnoir/pyTelegramBotAPI#2182]
When using the specific menu button, shouldn't it already fill in the type? I don't understand why even passing the specific class I need to pass the type.

https://github.com/eternnoir/pyTelegramBotAPI/blob/db4899a6b92b690ecb26ca28219de64eeac7deae/telebot/types.py#L7321-L7430

**Comment by Badiboy** [comment]
Loks reasonable...
