### ISSUE TITLE
Telebot constructor - num_threads argument doesn't exist

### ISSUE THREAD

**Issue by fastchatter** [eternnoir/pyTelegramBotAPI#220]
"The TeleBot constructor takes the following optional arguments:

threaded: True/False (default True). A flag to indicate whether TeleBot should execute message handlers on it's polling Thread.
num_threads: integer (default 4). Controls the amount of WorkerThreads created for the internal thread pool that TeleBot uses to execute message handlers. Is not used when threaded is False."

Why there is no such argument - "num_threads"? I found it in ThreadPool constructor but not in Telebot, so what's going on?

pyTelegramBotAPI 2.1.5
windows
python 3.5

**Comment by eternnoir** [comment]
It's document error. This argument was removed in previous version.
