### ISSUE TITLE
crash when trying to execute dropbox uploader bash script

### ISSUE THREAD

**Issue by journey6** [eternnoir/pyTelegramBotAPI#221]
Please answer these questions before submitting your issue. Thanks!
1. What version of pyTelegramBotAPI are you using?
   2.1.5
2. What OS are you using?
   Raspian jessie (Raspberry Pi OS)
3. What version of python are you using?
   python 2.7

I am trying to execute dropbox uploader to upload an image when a command is handled. everything works well except this.
Can you tell me the solution.
`filename = datetime.datetime.now().strftime("%Y-%-m-%-d_%-I:%M:%S")+".jpg";`
`os.system('sudo /var/www/html/scripts/dropbox_uploader.sh upload /var/www/html/gallery/'+
                      filename+ ' /remotetv/' + filename);`

![bot](https://cloud.githubusercontent.com/assets/21089053/17795089/f36e2612-65bd-11e6-9678-6f88a336c20a.png)

error message
`2016-08-19 03:24:15,423 (__init__.py:220 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[{"ok":false,"error_code":400,"description":"Bad Request: Message text must be encoded in utf-8"}]"`

**Comment by journey6** [comment]
I used asynchrounous bot and it worked
`bot = telebot.AsyncTeleBot(API_TOKEN)`

is this a good solution or there is any better solution?

**Comment by Kondra007** [comment]
Don't you read the error? `Message text must be encoded in utf-8`
