### ISSUE TITLE
Globally set parse_mode doesn't apply to InputMedia class

### ISSUE THREAD

**Issue by baatochan** [eternnoir/pyTelegramBotAPI#2232]
1. What version of pyTelegramBotAPI are you using?
 4.16.1
2. What OS are you using?
Manjaro Linux
3. What version of python are you using?
3.11.8

I have set the parse mode for a bot globally using `bot.parse_mode = "MarkdownV2"`. It is applied to every message I send using `send_photo()`, `send_video()` or `send_animation()`. However when I use `send_media_group()` with a list of `InputMediaPhoto` or `InputMediaVideo` I have to manually specify the parse_mode for every `InputMedia` object. Is it an expected behavior?

**Comment by Badiboy** [comment]
Looks reasonable.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/2235
