### ISSUE TITLE
Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by 46ef882ff3a47d** [eternnoir/pyTelegramBotAPI#2237]
When I run the code, I get the Enable tracemalloc to get the object allocation traceback error
Complete error report:
bot.py:20: RuntimeWarning: coroutine 'AsyncTeleBot.infinity_polling' was never awaited
bot.infinity_polling(stop=False)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
![photo_2024-04-22_22-28-58](https://github.com/eternnoir/pyTelegramBotAPI/assets/132568160/c257dcaa-ccdd-413d-ad76-5f5e24e1aea1)

**Comment by Badiboy** [comment]
If you do not know how to work with async - use Telebot.
