### ISSUE TITLE
inline_example

### ISSUE THREAD

**Issue by DevMykola** [eternnoir/pyTelegramBotAPI#2238]
1. What version of pyTelegramBotAPI are you using?
Last
3. What OS are you using?
Android 12, one ui
4. What version of python are you using?
Last

Example "inline_example.py" doesn't work.
```python
@bot.inline_handler(lambda query: query.query == 'text')
def query_text(inline_query):
```
query_text does not start

**Comment by Badiboy** [comment]
Any details?

**Comment by DevMykola** [comment]
I added details by editing

**Comment by Badiboy** [comment]
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/5613421/f2a026c9-7877-47ce-9a73-ccbb58c93fda)

Enabled?

**Comment by DevMykola** [comment]
Yes. When i wrote "@<mybot> ",  "@<mybot> text", "@<mybot> photo1"  the input field was loading and nothing. In logs at this time: received 0 new updates

**Comment by coder2020official** [comment]
You have to play with allowed_updates in infinity_polling if you are sure that you are not getting the updates.

**Comment by Badiboy** [comment]
@coder2020official Fast check shown that something is not obvious there. I'll check deeper later.

**Comment by DevMykola** [comment]
With allowed_updates in infinity_polling works as it should
