### ISSUE TITLE
Bot API update 7.3

### ISSUE THREAD

**Issue by coder2020official** [eternnoir/pyTelegramBotAPI#2255]
@Badiboy do you have time for this

**Comment by Badiboy** [comment]
I'll take a look.

**Comment by coder2020official** [comment]
Cool, thanks

**Comment by Badiboy** [comment]
Stalled in tasks yet, sorry (((

**Comment by Badiboy** [comment]
Push release now? Or wait some days?

**Comment by coder2020official** [comment]
I'd wait. U sure that ChatInfo thingy won't fail?
