### ISSUE TITLE
How to enable markdown?

### ISSUE THREAD

**Issue by barreeeiroo** [eternnoir/pyTelegramBotAPI#227]
**1. What version of pyTelegramBotAPI are you using?** IDK, the latest one, y use it importing it in my file
**2. What OS are you using?** Ubuntu 15
**3. What version of python are you using?** Python 2.7.10

Is possible to enable markdown mode using latest version of pyTelegramBot? Because I send a message using Telegram's default markdown mode ( `**, __, ´´, []()` ) but the bot sends it as normal text.

**Comment by xi4** [comment]
bot.send_message(parse_mode="markdown")

**Comment by barreeeiroo** [comment]
Thanks

**Comment by Kondra007** [comment]
@barreeeiroo Consider closing the issue if your problem is solved.

**Comment by barreeeiroo** [comment]
Sorry @Kondra007 
And thanks @xi4

**Comment by AndreiJirohHaliliDev2006** [comment]
How about if I want to reply from my bot to the `/start` command using Markdown? Is it same?

**Comment by MasterGroosha** [comment]
@AndreiJirohHaliliDev2006 Sure.

**Comment by AndreiJirohHaliliDev2006** [comment]
> @AndreiJirohHaliliDev2006 Sure.

How? I'm getting an error when I do this:

```py
@bot.message_handler(commands=['start'])
def send_welcome(message):
	bot.reply_to(message, parse_mode="markdown", "*Howdy, welcome to Recap Time bot!*" + "\n" + 
               "\n" +
              "To")
```

**Comment by MasterGroosha** [comment]
@AndreiJirohHaliliDev2006 What error are you getting?

**Comment by AndreiJirohHaliliDev2006** [comment]
> @AndreiJirohHaliliDev2006 What error are you getting?

```
File "telegram-bot.py", line 31

    bot.reply_to(message, parse_mode="markdown", "*Howdy, welcome to Recap Time bot!*" + "\n" + 
                                                 ^
SyntaxError: positional argument follows keyword argument
```

**Comment by MasterGroosha** [comment]
Just swap second and third arguments.
`parse_mode="markdown"` is a keyword argument
`"*Howdy..."` is a positional argument, since you don't reference it by name.

P.S. You don't need to concatenate separate "\n", just leave them in string like:
"*Howdy, welcome to Recap Time bot!*\n\nTo"

**Comment by AndreiJirohHaliliDev2006** [comment]
> ```python
> @bot.message_handler(commands=['start'])
> def send_welcome(message):
> 	bot.reply_to(message,"*Howdy, welcome to Recap Time bot!*\n\nTo", parse_mode="markdown")
> ```

Thanks!
