### ISSUE TITLE
Issue with not defined type

### ISSUE THREAD

**Issue by coder2020official** [eternnoir/pyTelegramBotAPI#2274]
https://github.com/eternnoir/pyTelegramBotAPI/blob/1931e3dc331c8b2968a621816d52c04edb595273/telebot/async_telebot.py#L6480
Should be types.InputPollWhatever
Bug in the new version @Badiboy 
How come tests do not fail?

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/2275

Fixed. Release?

**Comment by coder2020official** [comment]
Idk, what about tests

**Comment by Badiboy** [comment]
No clue about tests ) May be async not covered at all?
