### ISSUE TITLE
Add catch exception method for bot being blocked

### ISSUE THREAD

**Issue by ranjitsingha** [eternnoir/pyTelegramBotAPI#2277]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Latest

2. What OS are you using? Ubuntu

3. What version of python are you using? Latest

Add a exception method by which we can use it to know if bot was blocked by user.

**Comment by Badiboy** [comment]
Telegram has thousands of API exceptions and they eternaly changes. Catch API exception and check it by text.
