### ISSUE TITLE
Prevent spams, anti flood

### ISSUE THREAD

**Issue by mohamamdreza1000** [eternnoir/pyTelegramBotAPI#228]
Please answer these questions before submitting your issue. Thanks!
1. What version of pyTelegramBotAPI are you using?
   2.1.6 (latest)
2. What OS are you using?
   linux (ubuntu)
3. What version of python are you using?
   2.7

Hello,
Thank you for your effort which is really helpful for me ... The only problem that I have (or better say solution that I need)  is a way for me to stop incoming flood or spams from users. Because I may have many users and I have a connection to mysql which can't be so secure if I leave it as it is ...

And another question non-related to topic if I may have, How many chat_id can I have opened by the bot ? Are they permanet by telegram or they may change by time ? I want to keep my followers and contact them for a long duration ... [Sorry for last question I know it is not so related, but I have searched the telegram related link and couldn't find anything if you don't know perhaps I should ask the telegram bot developers.]

Regards.

**Comment by eternnoir** [comment]
First question.  You need Implement anti-spam for your bot yourself, for example you can save spam id to skip message from them. If your bot in chat, you can use `kick_chat_member` method to kick who you think spammer.

`How many chat_id can I have opened by the bot ?` 
I do not really understand this question, can you explain it more?
