### ISSUE TITLE
MessageEntity.user is optional, need to check if field is not None before serialization

### ISSUE THREAD

**Issue by miniusercoder** [eternnoir/pyTelegramBotAPI#2289]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
GitHub version commit [#139d35f](https://github.com/eternnoir/pyTelegramBotAPI/commit/139d35fe8e308c744facc0e20c2234dca6e74a96)

3. What OS are you using?
Windows

4. What version of python are you using?
3.12

If MessageEntity type is not text_mention, so "user" field would be None, so calling to_dict() method on it will raise AttributeError: 'NoneType' object has no attribute 'to_dict'

**Comment by Badiboy** [comment]
My bad, sorry.

https://github.com/eternnoir/pyTelegramBotAPI/pull/2290
