### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Telebot'

### ISSUE THREAD

**Issue by parrotchute** [eternnoir/pyTelegramBotAPI#229]
I'm using the latest version of pyTelegramBotAPI installed via pip on pythonanywhere, python version 3.4.3, but I'm getting this error on their Bash console.

```AttributeError: 'module' object has no attribute 'Telebot'```

I'm using the echo bot example and I don't see where I've made a mistake. Is this an incompatibility issue with pythonanywhere?

```
(telegramvenv) 06:09 ~ $ pip install pyTelegramBotAPI
Collecting pyTelegramBotAPI
  Downloading pyTelegramBotAPI-2.1.7.tar.gz
Collecting requests (from pyTelegramBotAPI)
  Downloading requests-2.11.1-py2.py3-none-any.whl (514kB)
    100% |████████████████████████████████| 522kB 864kB/s 
Collecting six (from pyTelegramBotAPI)
Building wheels for collected packages: pyTelegramBotAPI
  Running setup.py bdist_wheel for pyTelegramBotAPI ... done
  Stored in directory: /home/kudan/.cache/pip/wheels/34/69/1b/04f3ef48e7d7e8772d0e267f11f33fd993c6d8521c6fe36b8f
Successfully built pyTelegramBotAPI
Installing collected packages: requests, six, pyTelegramBotAPI
Successfully installed pyTelegramBotAPI-2.1.7 requests-2.11.1 six-1.10.0
(telegramvenv) 06:09 ~ $ python echo_bot.py
Traceback (most recent call last):
  File "echo_bot.py", line 5, in <module>
    bot = telebot.Telebot(key)
AttributeError: 'module' object has no attribute 'Telebot'
```

I even tried ```from telebot import Telebot``` but all I got was this error:

```
Traceback (most recent call last):
  File "echo_bot.py", line 1, in <module>
    from telebot import Telebot
ImportError: cannot import name 'Telebot'
```

**Comment by TiberiumPY** [comment]
there's not "Telebot", there's "Tele**B**ot"

**Comment by TiberiumPY** [comment]
E.g : 
`>>>> from telebot import TeleBot
>>>> dir(TeleBot)
['_TeleBot__non_threaded_polling', '_TeleBot__notify_update', '_TeleBot__retrieve_updates', '_TeleBot__skip_updates', '_TeleBot__threaded_polling', '__doc__', '__init__', '__module__', '_append_pre_next_step_handler', '_build_handler_dict', '_exec_task', '_notify_command_handlers', '_notify_message_next_handler', '_notify_message_subscribers', '_test_filter', '_test_message_handler', 'add_callback_query_handler', 'add_chosen_inline_handler', 'add_edited_message_handler', 'add_inline_handler', 'add_message_handler', 'answer_callback_query', 'answer_inline_query', 'callback_query_handler', 'chosen_inline_handler', 'download_file', 'edit_message_caption', 'edit_message_reply_markup', 'edit_message_text', 'edited_message_handler', 'forward_message', 'get_chat', 'get_chat_administrators', 'get_chat_member', 'get_chat_members_count', 'get_file', 'get_me', 'get_updates', 'get_user_profile_photos', 'inline_handler', 'kick_chat_member', 'leave_chat', 'message_handler', 'polling', 'process_new_callback_query', 'process_new_chosen_inline_query', 'process_new_edited_messages', 'process_new_inline_query', 'process_new_messages', 'process_new_updates', 'register_for_reply', 'register_next_step_handler', 'remove_webhook', 'reply_to', 'send_audio', 'send_chat_action', 'send_contact', 'send_document', 'send_location', 'send_message', 'send_photo', 'send_sticker', 'send_venue', 'send_video', 'send_voice', 'set_update_listener', 'set_webhook', 'stop_polling', **'unban_chat_member']`**

**Comment by parrotchute** [comment]
Doh, how did I miss that? So sorry and thanks for the clearing that up!

**Comment by HamidulloRahmonberdiyev** [comment]
Hi. I've get error "
ModuleNotFoundError: No module named 'telebot" in consol. Please, Help me.

**Comment by coder2020official** [comment]
Install it with `pip install pytelegrambotapi`
