### ISSUE TITLE
"ValueError: json_type should be a json dict or string." for user_shared message

### ISSUE THREAD

**Issue by its0x4d** [eternnoir/pyTelegramBotAPI#2292]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI==4.18.1

2. What OS are you using?
Ubuntu
3. What version of python are you using?
Python 3.11.3

Please fix user_shared message

![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/58491910/2da65da0-496a-434f-a1b9-4b4c3627d068)

**Comment by Badiboy** [comment]
No user_shared any more. 

![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/5613421/1e2c5881-ebd0-448e-bfa1-68f80fd4e317)
