### ISSUE TITLE
Error with copyMessage

### ISSUE THREAD

**Issue by iiAmeer** [eternnoir/pyTelegramBotAPI#2296]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.19

3. What OS are you using? Ubuntu 22

4. What version of python are you using? Python3

The error i get: copy_message() got an unexpected keyword argument 'show_caption_above_media'

**Comment by coder2020official** [comment]
Sorry for this. You will need to install GitHub version as it contains a fix

**Comment by Badiboy** [comment]
@coder2020official Is it in repo? We can push a fix release.

**Comment by coder2020official** [comment]
These bugfix releases are becoming more and more common(((
We urgently need to implement tests. 
Can you check the #2294 and fully make sure there's nothing I overlooked? Then you can push a release

**Comment by Badiboy** [comment]
Згырувю
