### ISSUE TITLE
users_shared still broken

### ISSUE THREAD

**Issue by its0x4d** [eternnoir/pyTelegramBotAPI#2298]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI==4.19.1
2. What OS are you using?
Ubuntu
3. What version of python are you using?

Why this still BROKEN!!??

![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/58491910/c8429ed8-6710-45e7-adfd-e054960e319d)

I can't use it 

![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/58491910/1c562a8e-6159-40bb-9383-73231176c6c1)

I edited the UsersShared class to this and the problem solved

![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/58491910/5a1b0e9e-3182-4561-a175-b20344c4f2f2)

**Comment by Badiboy** [comment]
> Added the class SharedUser and replaced the field user_ids in the class [UsersShared](https://core.telegram.org/bots/api#usersshared) with the field users.

Missed this update in March update...

**Comment by Badiboy** [comment]
@its0x4d Try this branch please: https://github.com/eternnoir/pyTelegramBotAPI/pull/2299

**Comment by its0x4d** [comment]
> @its0x4d Try this branch please: https://github.com/eternnoir/pyTelegramBotAPI/pull/2299

Worked

**Comment by Badiboy** [comment]
+
