### ISSUE TITLE
Explicitly create Threads instead of implicitly?

### ISSUE THREAD

**Issue by pevdh** [eternnoir/pyTelegramBotAPI#23]
Threading is a complicated subject and it can lead to difficult to track bugs.
By default TeleBot creates a new Thread for each registered listener and each registered message handler. Now, if two message handlers or two listeners try to access the same (not thread-safe) resource, the programmer has got a problem. So unless the programmer is aware that this library creates Threads (and knows how to handle them (locks, semaphores, queues)), Threads can be a threat ( :) ) to the stability of bots.
My proposal: 
Create an optional ```create_threads``` parameter for the TeleBot constructor, which defaults to ```False```.
Check for this parameter when calling listeners or message handlers:
```python
if self.create_threads:
    t = threading.Thread(target=message_handler, args=message)
    t.start()
else:
    message_handler(message)
```

The drawback of this is of course program speed. The bot will block until a listener or message handler has returned. Until then the bot cannot receive new messages. But my estimation is that this drawback is less important than the overhead (for the, especially novice, programmer) of creating Threads. With an optional argument, the programmer can decide for himself whether he wants to go down the dangerous road of multithreading.
Is my reasoning correct?

**Comment by eternnoir** [comment]
Yes, you are right.In the beginning, TeleBot create a thread for every handler is avoid listener crash TeleBot. 
Your suggestion do really make sense. Let user choice which way they want to do. It would be a appropriate way to improve.

**Comment by pevdh** [comment]
Another issue concerning threads: should we consider using a thread pool instead of firing short-running threads? There might be a performance benefit there and it is more scalable. I'll run some tests later on to get some solid measurements.

**Comment by eternnoir** [comment]
In our case 'short-running threads' means notify new message to handler?

**Comment by pevdh** [comment]
Yea thats what I meant

**Comment by eternnoir** [comment]
I think it is a good idea. I'll do some test too. Do you want to use official `multiprocessing.pool` package to implement? or other package.

**Comment by pevdh** [comment]
I took this script:
```python
import time
import multiprocessing
import threading

def dummy_handler(message):
    time.sleep(1)

pool = multiprocessing.Pool()

def test_pool(x):
    for _ in range(x):
        pool.apply_async(dummy_handler, args='x')

def test_thread(x):
    for _ in range(x):
        threading.Thread(target=dummy_handler, args='x').start()

def timef(func, arg):
    start = time.time()
    func(arg)
    print "{0} took {1} seconds ({2} iterations)".format(func.__name__, time.time() - start, arg)


timef(test_pool, 1)
timef(test_thread, 1)

timef(test_pool, 10)
timef(test_thread, 10)

timef(test_pool, 1000)
timef(test_thread, 1000)

timef(test_pool, 100000)
timef(test_thread, 100000)
```
Output:
```
test_pool took 7.39097595215e-05 seconds (1 iterations)
test_thread took 0.000190019607544 seconds (1 iterations)
test_pool took 0.000684976577759 seconds (10 iterations)
test_thread took 0.00121212005615 seconds (10 iterations)
test_pool took 0.018317937851 seconds (1000 iterations)
test_thread took 0.14023399353 seconds (1000 iterations)
test_pool took 1.14335203171 seconds (100000 iterations)
test_thread took 31.8522610664 seconds (100000 iterations)
```
This makes multiprocessing.Pool a clear victor. I have yet to see any disadvantages of using a Process pool. So far it seems that implementing this makes a bot very scalable.

**Comment by pevdh** [comment]
First drawback: Process does not share the same memory space as main Process. So you get a whole bunch of errors like this:
```
Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
    return recv()
AttributeError: 'module' object has no attribute 'send_welcome'
```

**Comment by pevdh** [comment]
I wasn't able to find any implementation of a ThreadPool, except for multiprocessing.pool.ThreadPool, which didn't seem to work for me, so I wrote my own implementation:
```python
class ThreadPool:

    class WorkerThread(threading.Thread):
        count = 0

        def __init__(self, queue):
            threading.Thread.__init__(self, name="WorkerThread{0}".format(self.__class__.count + 1))
            self.__class__.count += 1
            self.queue = queue
            self.daemon = True

            self._running = True
            self.start()

        def run(self):
            while self._running:
                try:
                    task, args, kwargs = self.queue.get(False)
                    task(*args, **kwargs)
                except Queue.Empty:
                    time.sleep(0)
                    pass

        def stop(self):
            self._running = False

    def __init__(self, num_threads=4):
        self.tasks = Queue.Queue()
        self.workers = [self.WorkerThread(self.tasks) for _ in range(num_threads)]

        self.num_threads = num_threads

    def put(self, func, *args, **kwargs):
        self.tasks.put((func, args, kwargs))

    def close(self):
        for worker in self.workers:
            worker.stop()
        for worker in self.workers:
            worker.join()
```
Modified the above script a bit:
```python
import telebot
import threading
import time

def dummy_handler(): # takes roughly .05 seconds on my system.
    x = 0
    for _ in range(1000000):
       x += 1

pool = telebot.ThreadPool()

def test_thread_pool(x):
    for _ in range(x):
        pool.put(dummy_handler)


def test_thread(x):
    for _ in range(x):
        threading.Thread(target=dummy_handler).start()


def timef(func, *args, **kwargs):
    start = time.time()
    func(*args, **kwargs)
    return time.time() - start

for x in [1, 10, 100]:
    print "ThreadPool: {0} tasks, {1} seconds.".format(x, timef(test_thread_pool, x))
    print "Single Threads: {0} tasks, {1} seconds".format(x, timef(test_thread, x))

pool.close()
```
Result:
```
ThreadPool: 1 tasks, 1.21593475342e-05 seconds.
Single Threads: 1 tasks, 0.014475107193 seconds
ThreadPool: 10 tasks, 0.0460138320923 seconds.
Single Threads: 10 tasks, 0.237497091293 seconds
ThreadPool: 100 tasks, 0.00351095199585 seconds.
Single Threads: 100 tasks, 2.13462495804 seconds
```

Though I am not entirely satisfied (can't figure out why 10 tasks takes more time for ThreadPool than 100 tasks), the ThreadPool class shows a big advantage over fire-and-forget Thread creation.

**Comment by eternnoir** [comment]
I guess the reason of '10 tasks takes more time for ThreadPool than 100 tasks' is four thread is too often try  get element from empty queue then raise exception. This action let Thread pool hard to find chance to put new job.

I do some test. I add sleep between each test to wait all thread done. And set different number of worker to test.

```python
import telebot
import threading
import time

def dummy_handler(): # takes roughly .05 seconds on my system.
    x = 0
    for _ in range(1000000):
       x += 1

pool = telebot.ThreadPool(1)

def test_thread_pool(x):
    for _ in range(x):
        pool.put(dummy_handler)


def test_thread(x):
    for _ in range(x):
        threading.Thread(target=dummy_handler).start()


def timef(func, *args, **kwargs):
    start = time.time()
    func(*args, **kwargs)
    return time.time() - start

for x in [1, 10, 100]:
    print "ThreadPool: {0} tasks, {1} seconds.".format(x, timef(test_thread_pool, x))
    #print "Single Threads: {0} tasks, {1} seconds".format(x, timef(test_thread, x))
    time.sleep(10)   # wait all thread done

pool.close()
```

* 1 worker

```
ThreadPool: 1 tasks, 1.4066696167e-05 seconds.
ThreadPool: 10 tasks, 0.000229835510254 seconds.
ThreadPool: 100 tasks, 0.0106010437012 seconds.
```

* 2 worker

```
ThreadPool: 1 tasks, 3.00407409668e-05 seconds.
ThreadPool: 10 tasks, 0.0239241123199 seconds.
ThreadPool: 100 tasks, 0.0252780914307 seconds.
```

* 4 worker

```
ThreadPool: 1 tasks, 4.60147857666e-05 seconds.
ThreadPool: 10 tasks, 0.066645860672 seconds.
ThreadPool: 100 tasks, 0.0446400642395 seconds.
```

* 8 worker

```
ThreadPool: 1 tasks, 7.29560852051e-05 seconds.
ThreadPool: 10 tasks, 0.112873077393 seconds.
ThreadPool: 100 tasks, 0.0997569561005 seconds.
```

Maybe we can let worker sleep a small time if catch queue empty exception to improve thread pool put new tasks  performance.
Is my guess correctly?

**Comment by pevdh** [comment]
Haven't got the time to test it, but would this work better?
```python
def run(self):
    while self._running:
        try:
            task, args, kwargs = self.queue.get(timeout=1)
            task(*args, **kwargs)
        except Queue.Empty:
            pass
```
Only downside to this is that it takes at least 1 second to close() a ThreadPool (that's why I chose for the block=False approach.

**Comment by eternnoir** [comment]
It seems no significant difference. I think just use block=False.

**Comment by pevdh** [comment]
Alright, do you want to have a go at implementing aforementioned issues?

**Comment by eternnoir** [comment]
Okay,but I'm available after 8hours. If in hurry you could start to implement first. I'll check your branch before I started.

**Comment by pevdh** [comment]
Pushed the ThreadPool class and some other commits I can't remember.. it's late here.. time for bed, lol.

**Comment by eternnoir** [comment]
Thanks a lot. I create branch thread_improve and merge ThreadPool commit. 
https://github.com/eternnoir/pyTelegramBotAPI/tree/thread_improve
I still add create_thread flag support. But I am not sure is it still necessary after thread pool supported.

After my commit reviewed. I will merge this branch to develop branch.

**Comment by pevdh** [comment]
Looks good! One addition, though: check for create_threads before creating the ThreadPool? Otherwise, unnecessary Threads will be created when create_threads equals False. And perhaps create_threads should default to False? What do you think?

**Comment by eternnoir** [comment]
Ok, I check create_thread flag in contractor. I think let create_threads default is True is better, because we do that in previous versions.

**Comment by eternnoir** [comment]
Merged. On develop branch now.

**Comment by eternnoir** [comment]
@pevdh I found cpu usage almost full when use thread pool. Is it busy get element from queue cause?

**Comment by pevdh** [comment]
Is this fixed with commit f6a0037f?

**Comment by eternnoir** [comment]
yep, Is it correct solution?

**Comment by vsile** [comment]
pevdh, I found in your script about multiprocessing.Pool to start multiprocessing with command

> multiprocessing.Pool().apply_async(dummy_handler, args='x')

will give another result than with command

> multiprocessing.Process(target=dummy_handler, args='x').start()
Can you explain it?
