### ISSUE TITLE
LinkPreviewOptions - show_above_text doesn't work as expected

### ISSUE THREAD

**Issue by aqasemi** [eternnoir/pyTelegramBotAPI#2300]
When `show_above_text` is set to true, it should put the link preview media above the text. However, it does not.

I'm using the latest version (4.19). 
Steps to reproduce:
```
inline_content= types.InputTextMessageContent(
    content,
    parse_mode="HTML",
    link_preview_options=types.LinkPreviewOptions(url=url, show_above_text=True, prefer_large_media=True)
)
bot.answer_inline_query(query.id, inline_content)
```

Reference: https://core.telegram.org/bots/api#linkpreviewoptions

**Comment by coder2020official** [comment]
I'll take a look tonight. Didn't see any issues on first quick inspection.

**Comment by Badiboy** [comment]
I checked the library - it's fine. Looks like TG fault.

PS. Should be
`bot.answer_inline_query(query.id, [inline_content])`
No?
