### ISSUE TITLE
How can I get voice messages in AsyncTeleBot?

### ISSUE THREAD

**Issue by prp-e** [eternnoir/pyTelegramBotAPI#2304]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

4.19.0

2. What OS are you using?

Ubuntu 22.04

3. What version of python are you using?
3.12 

This is my code: 

```python
@bot.message_handler(content_types=['voice'])
async def voice_processing(message):
    file_info = bot.get_file(message.voice.file_id)
    file_info.wait()
    downloaded_file = bot.download_file(file_info.file_id)
```

and it says there is no method `wait()` for this coroutine. What can I do?

**Comment by coder2020official** [comment]
Learn async await principles
