### ISSUE TITLE
HTTP 429 Too Many Requests

### ISSUE THREAD

**Issue by Tar4s** [eternnoir/pyTelegramBotAPI#231]
Hello! I try to execute your **webhook_cherrypy_echo_bot.py** and a week ago it worked fine. But today under previous settings I see this error message:

> Traceback (most recent call last):
>   File "bot.py", line 74, in <module>
>     certificate=open(WEBHOOK_SSL_CERT, 'r'))
>   File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 79, in set_webhook
>     return apihelper.set_webhook(self.token, url, certificate)
>   File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 127, in set_webhook
>     return _make_request(token, method_url, params=payload, files=files)
>   File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 36, in _make_request
>     return _check_result(method_name, result)['result']
>   File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 55, in _check_result
>     raise ApiException(msg, method_name, result)
> telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 429 Too Many Requests. Response body:
> [b'{"ok":false,"error_code":429,"description":"Too Many Requests: retry after 1","parameters":{"retry_after":1}}']

Given that the code of the example, I have not changed:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This is a simple echo bot using decorators and webhook with CherryPy
# It echoes any incoming text messages and does not use the polling method.

import cherrypy
import telebot
import logging


API_TOKEN = '<api_token>'

WEBHOOK_HOST = '<ip/host where the bot is running>'
WEBHOOK_PORT = 8443  # 443, 80, 88 or 8443 (port need to be 'open')
WEBHOOK_LISTEN = '0.0.0.0'  # In some VPS you may need to put here the IP addr

WEBHOOK_SSL_CERT = './webhook_cert.pem'  # Path to the ssl certificate
WEBHOOK_SSL_PRIV = './webhook_pkey.pem'  # Path to the ssl private key

# Quick'n'dirty SSL certificate generation:
#
# openssl genrsa -out webhook_pkey.pem 2048
# openssl req -new -x509 -days 3650 -key webhook_pkey.pem -out webhook_cert.pem
#
# When asked for "Common Name (e.g. server FQDN or YOUR name)" you should reply
# with the same value in you put in WEBHOOK_HOST

WEBHOOK_URL_BASE = "https://%s:%s" % (WEBHOOK_HOST, WEBHOOK_PORT)
WEBHOOK_URL_PATH = "/%s/" % (API_TOKEN)


logger = telebot.logger
telebot.logger.setLevel(logging.INFO)

bot = telebot.TeleBot(API_TOKEN)


# WebhookServer, process webhook calls
class WebhookServer(object):
    @cherrypy.expose
    def index(self):
        if 'content-length' in cherrypy.request.headers and \
           'content-type' in cherrypy.request.headers and \
           cherrypy.request.headers['content-type'] == 'application/json':
            length = int(cherrypy.request.headers['content-length'])
            json_string = cherrypy.request.body.read(length).decode("utf-8")
            update = telebot.types.Update.de_json(json_string)
            bot.process_new_updates([update])
            return ''
        else:
            raise cherrypy.HTTPError(403)


# Handle '/start' and '/help'
@bot.message_handler(commands=['help', 'start'])
def send_welcome(message):
    bot.reply_to(message,
                 ("Hi there, I am EchoBot.\n"
                  "I am here to echo your kind words back to you."))


# Handle all other messages
@bot.message_handler(func=lambda message: True, content_types=['text'])
def echo_message(message):
    bot.reply_to(message, message.text)


# Remove webhook, it fails sometimes the set if there is a previous webhook
bot.remove_webhook()

# Set webhook
bot.set_webhook(url=WEBHOOK_URL_BASE+WEBHOOK_URL_PATH,
                certificate=open(WEBHOOK_SSL_CERT, 'r'))

# Start cherrypy server
cherrypy.config.update({
    'server.socket_host': WEBHOOK_LISTEN,
    'server.socket_port': WEBHOOK_PORT,
    'server.ssl_module': 'builtin',
    'server.ssl_certificate': WEBHOOK_SSL_CERT,
    'server.ssl_private_key': WEBHOOK_SSL_PRIV
})

cherrypy.quickstart(WebhookServer(), WEBHOOK_URL_PATH, {'/': {}})
```

**Comment by kypsibir** [comment]
You should try to remove line
`bot.remove_webhook()`
or make pause between removing and setting webhook.

**Comment by Tar4s** [comment]
All right. This solved the problem. I wonder why this happened? More than a month everything worked great

**Comment by Kondra007** [comment]
@Tar4s I've spoken to BotSupport, they said they've changed some things in Bot API "under the hood", so this is new "feature".
And since you've solved your problem, don't forget to close the issue.

**Comment by Tar4s** [comment]
@Kondra007 Thanx
It's done
