### ISSUE TITLE
Failed working with visible_file_name in async

### ISSUE THREAD

**Issue by Badiboy** [eternnoir/pyTelegramBotAPI#2320]
https://github.com/eternnoir/pyTelegramBotAPI/discussions/2319#discussioncomment-9850643

Looks like some kind of bug. @coder2020official , could you please check?

**Comment by coder2020official** [comment]
Sure, will check it later

**Comment by coder2020official** [comment]
- [ ] Should add a check for presence of both InputFile and visible_file_name and show a warning;
- [ ] file_name should be added as an optional parameter in InputFile
