### ISSUE TITLE
pre_checkout_query_handler - Not handling telegram stars

### ISSUE THREAD

**Issue by mike2505** [eternnoir/pyTelegramBotAPI#2322]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.20.0
2. What OS are you using?
Arch/Ubuntu
3. What version of python are you using?
3.11/3.10

https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/payments_example.py - You can try addapting this for new telegram stars. pre checkout query handler goes on timeout since it can't handle it.

![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/37780087/52948bbe-e5c4-4c26-a3c6-a12a48a88a1b)

**Comment by coder2020official** [comment]
try turning on debug and see if you get the update; play with allowed_updates too

**Comment by mike2505** [comment]
Will try allowed_updates, but with debug - It generates invoice without any issues, but nothing happens on pay button. 
In telegram it's spinning but nothing happens.

![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/37780087/6819a46a-fcfb-4748-be9e-edd56f581eb3)

**Comment by mike2505** [comment]
Seems like issue is with telegram, manually checked getUpdates endpoint while pressing on Pay button. No updates are stored on a server.
