### ISSUE TITLE
I have an issue 

### ISSUE THREAD

**Issue by ABIRHOSSAIN10** [eternnoir/pyTelegramBotAPI#2330]
packages/telebot/async_telebot.py", line 1906, in get_m
e
    result = await asyncio_helper.get_me(self.token)
  File "/home/mai/.local/lib/python3.10/site-
packages/telebot/asyncio_helper.py", line 154, in get_m
e
    return await _process_request(token, method_url)
  File "/home/mai/.local/lib/python3.10/site-
packages/telebot/asyncio_helper.py", line 105, in _proc
ess_request
    raise RequestTimeout("Request timeout. Request: met
hod={0} url={1} params={2} files={3} request_timeout={4
}".format(method, url, params, files, request_timeout, 
current_try))
telebot.asyncio_helper.RequestTimeout: Request timeout.
 Request: method=get url=getMe params=<aiohttp.formdata
.FormData object at 0x7f6e5a472560> files=None request_
timeout=300
>>>

**Comment by coder2020official** [comment]
bad internet, use non_stop=True in your polling function

**Comment by All-The-Foxes** [comment]
It's not bad internet. Almost all of the time the issue is with Telegram's servers. I run my bots off of a server with 10 gigabit enterprise networking and this happens to me from time to time. The issue is that Async Telebot logs it as an unhandled exception.

**Comment by ABIRHOSSAIN10** [comment]
> bad internet, use non_stop=True in your polling function




2024-07-02 06:40:35,530 (asyncio_helper.py:101 MainThre
ad) ERROR - TeleBot: "Aiohttp ClientError: ClientConnectorError"
Traceback (most recent call last):
  File "/home/mai10/tg-bot-v2.py", line 888, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/mai10/tg-bot-v2.py", line 874, in main
    await bot.delete_my_commands(scope=None, language_code=None)
  File "/home/mai10/.local/lib/python3.10/site-packages/telebot/async_telebot.py", line 4547, in delete_my_commands
    return await asyncio_helper.delete_my_commands(self
.token, scope, language_code)
  File "/home/mai10/.local/lib/python3.10/site-
packages/telebot/asyncio_helper.py", line 1264, in dele
te_my_commands
    return await _process_request(token, method_url, pa
rams=payload, method='post')
  File "/home/mai10/.local/lib/python3.10/site-
packages/telebot/asyncio_helper.py", line 105, in _proc
ess_request
    raise RequestTimeout("Request timeout. Request: met
hod={0} url={1} params={2} files={3} request_timeout={4
}".format(method, url, params, files, request_timeout, 
current_try))
telebot.asyncio_helper.RequestTimeout: Request timeout.
 Request: method=post url=deleteMyCommands params=<aioh
ttp.formdata.FormData object at 0x7fc626d22350> files=N
one request_timeout=300
>>> 
>>> 




Same error still it not running. I am trying to host ny bot in pythonanywhere.

When i Don't use AsyncTeleBot it works fine but. When i use this it show me this.even i Try the examples of this github. And still give me the error maybe this module have a problem

**Comment by Badiboy** [comment]
It show you this error ALWAYS or SOMETIME?

**Comment by coder2020official** [comment]
Probably asynctelebot won't work on pythonanywhere. I should try it out, but I already had such reports. Not only with this library

**Comment by ABIRHOSSAIN10** [comment]
> It show you this error ALWAYS or SOMETIME?

Always when i run the bot

**Comment by ABIRHOSSAIN10** [comment]
> Probably asynctelebot won't work on pythonanywhere. I should try it out, but I already had such reports. Not only with this library

But pyrogram Works on pythonanywhere

Maybe AsyncTeleBot have some problem in there  library. I love the module but. After seeing this maybe i have to shift to pyrogram. Because i need to work with asynchronous.

 it's took 10 days  to build the bot.now i am frustrated. I have to change my full code.

**Comment by coder2020official** [comment]
I will investigate it at some point

**Comment by ABIRHOSSAIN10** [comment]
> I will investigate it at some point

Plz notifie me when you fix it. I will love to use this module

**Comment by ABIRHOSSAIN10** [comment]
> I will investigate it at some point

import telebot
from telebot.types import ChatMemberUpdated
import logging
import config

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

bot = telebot.TeleBot('')

@bot.chat_member_handler()
def handle_chat_member_update(chat_member_update: ChatMemberUpdated):
    print(chat_member_update)
    print(ChatMemberUpdated)
    try:
        if chat_member_update.new_chat_member.status == 'member':
            bot.send_message(chat_member_update.chat.id, f"Welcome, {chat_member_update.new_chat_member.user.first_name}!")
        elif chat_member_update.new_chat_member.status in ['left', 'kicked']:
            bot.send_message(chat_member_update.chat.id, f"Goodbye, {chat_member_update.new_chat_member.user.first_name}!")
    except Exception as e:
        logging.error(f"Error handling chat member update: {e}")

bot.polling()



Found another problem  it dosent trigger the handler. My bot is an admin. But still not doing anything seconde i tryed 
This
@bot.message_handler(content_types=['new_chat_members'])

Its only work for Small groupa

**Comment by Badiboy** [comment]
> But still not doing anything

https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/chat_member_example.py
Check examle paying attention on 

> allowed_updates=util.update_types

**Comment by coder2020official** [comment]
I don't think we will support pythonanywhere for async. Seems like it blocks some aiohttp requests.
