### ISSUE TITLE
Need this feature

### ISSUE THREAD

**Issue by ranjitsingha** [eternnoir/pyTelegramBotAPI#2347]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Latest

2. What OS are you using? Ubuntu

3. What version of python are you using? Latest

Need this feature to open the profile of user
![Screenshot_20240717-092454_1](https://github.com/user-attachments/assets/625935c3-71c4-48f0-b23c-59f13cd5f9f4)

**Comment by coder2020official** [comment]
This is not Bot API.

**Comment by coder2020official** [comment]
instead, use user id links:
tg://user?id=...
