### ISSUE TITLE
Check chat type super group isn't working

### ISSUE THREAD

**Issue by ranjitsingha** [eternnoir/pyTelegramBotAPI#2348]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Latest

2. What OS are you using? Ubuntu 

3. What version of python are you using? Latest 

```
message.chat.type == "supergroup"
```
This isn't working after changing the group to supergroup

**Comment by Badiboy** [comment]
And what message.chat.type it has in fact?

**Comment by ranjitsingha** [comment]
Sorry there was a mistake in my code
