### ISSUE TITLE
Inline mode's InlineKeyboardButton callback_data not works.

### ISSUE THREAD

**Issue by WebShark025** [eternnoir/pyTelegramBotAPI#235]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Latest version. (2.1.5)

2. What OS are you using?
Unix 16.04.1

3. What version of python are you using?
Python 2.7

So, when you try to add callback_data in InlineKeyboardButton in inline mode, It wont submit the callback_data so, when a user clicks on the button, the callback_data will be empty.

I would be glad if you can fix this ASAP :)

**Comment by Kondra007** [comment]
Works fine for me with pyTelegramBotAPI v2.1.7 and Python 3.5.  
Please update pyTelegramBotAPI to 2.1.7 and check it again.

**Comment by WebShark025** [comment]
@Kondra007 Still not works. updated to v2.1.7.
Not me, also one of my friends have this problem using another code (not even close to my code :D)

**Comment by Kondra007** [comment]
@WebShark025 that's really strange. Here's the code I've used:

```pyrhon
@bot.inline_handler(func=lambda query: True)
def inline(query):
    keyboard = types.InlineKeyboardMarkup()
    btn = types.InlineKeyboardButton(text="Button text", callback_data="inline")
    keyboard.add(btn)
    r = types.InlineQueryResultArticle(
        id="1",
        title="Title",
        input_message_content=types.InputTextMessageContent(message_text="Test"),
        reply_markup=keyboard
    )
    bot.answer_inline_query(query.id, [r], cache_time=10)
```
And when I print `call` object from here:
```python
@bot.callback_query_handler(func=lambda call: True)
def callbacks(call):
    if call.data == "inline":
        print(call)
```
I see "Inline" in `call.data`

**Comment by WebShark025** [comment]
@Kondra007 OK Got it. There is no 'call.message', but there is 'call.data' :D
Thanks for your help.

**Comment by Kondra007** [comment]
Please read [documentation](https://core.telegram.org/bots/api#callbackquery) next time.
And, maybe, close this issue?

**Comment by WebShark025** [comment]
I just used the example they made, thats why.
