### ISSUE TITLE
Error when working with the “message.html_text” property if the content type is “sticker”

### ISSUE THREAD

**Issue by rustequal** [eternnoir/pyTelegramBotAPI#2355]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
  4.21.0
2. What OS are you using?
  linux
3. What version of python are you using?
  3.8.18

How to reproduce. Run this code:
```
import asyncio
from telebot.async_telebot import AsyncTeleBot

TOKEN = '<BOT_TOKEN>'
bot = AsyncTeleBot(TOKEN, parse_mode='HTML')

@bot.message_handler(content_types=['sticker'])
def handle_sticker(message):
  print(message.html_text)

asyncio.run(bot.infinity_polling(allowed_updates=['message']))
```
Send any sticker in private chat with the bot.

As of version 4.18.0, [this commit](https://github.com/eternnoir/pyTelegramBotAPI/commit/5fd60380db0de83049d35c66ce1794b988ed6471) has been added, which causes the error:
`ERROR - TeleBot: ‘’NoneType‘ object has no attribute ’replace'”`
if the property value is of type NoneType. Version 4.17.0 works without errors.

**Comment by Badiboy** [comment]
Sticker has no text. Trying to assess text is nonsence.

**Comment by Badiboy** [comment]
> if the property value is of type NoneType. Version 4.17.0 works without errors.

Only this stopped me from closing the issue...

**Comment by rustequal** [comment]
I'm well aware that the sticker doesn't have text in this property. But the library should not crash with an error when trying to access this property.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/2356
