### ISSUE TITLE
telebot has no atribute called TeleBot 

### ISSUE THREAD

**Issue by Bibou1494** [eternnoir/pyTelegramBotAPI#2358]
``Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
lastest
2. What OS are you using?
Windows 10 family 22h2 32 bits(i gonna upgrade)
3. What version of python are you using?
python 3.12.4 32 bits``

My problem is that i just try to make a bot and i did
`pip install pyTelegramBotAPI` command to install
then i did this code
```
import telebot

bot = telebot.TeleBot("{token}", parse_mode=None)
```
but here is the result when i execute the code
```
D:\tleebot>python telebot.py
Traceback (most recent call last):
  File "D:\tleebot\telebot.py", line 1, in <module>
    import telebot
  File "D:\tleebot\telebot.py", line 3, in <module>
    bot = telebot.TeleBot("7214918475:AAF1Dod3D7Cm36CSQ3FRFeGQXSBWdXvEY40", parse_mode=None)
          ^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'telebot' has no attribute 'TeleBot' (most likely due to a circular import). Did you mean: 'telebot'?
```
can you please help me?? or do i just retry with replit?? if it doesn't work then no problem. just thank you even if you dont respond.

**Comment by Badiboy** [comment]
You named your program "telebot" and try to import "Telebot" from "telebot". Change your file name.

**Comment by Bibou1494** [comment]
I'm just dumb(no I just didn't know that)
