### ISSUE TITLE
Create a changes file for the library

### ISSUE THREAD

**Issue by coder2020official** [eternnoir/pyTelegramBotAPI#2365]
By creating a file and recording all changes(Breaking, new features, etc), it will be easier to keep track of all changes and can be used for release notes.

**Comment by Olimovich28** [comment]
import telebot

# Replace 6750611114:AAF-zzIOpMnDik7nNA3YE_a4D8uIMWFoMB0 with your bot's API key
bot = telebot.TeleBot(6750611114:AAF-zzIOpMnDik7nNA3YE_a4D8uIMWFoMB0)

# This handler responds to any text message
@bot.message_handler(func=lambda message: True)
def auto_reply(message):
    bot.reply_to(message, "Thank you for your message! We'll get back to you soon.")

# Keep the bot running
bot.polling()

**Comment by Olimovich28** [comment]
import telebot

# Replace '6750611114:AAF-zzIOpMnDik7nNA3YE_a4D8uIMWFoMB0' with your bot's API key
bot = telebot.TeleBot('6750611114:AAF-zzIOpMnDik7nNA3YE_a4D8uIMWFoMB0')

# This handler responds to any text message
@bot.message_handler(func=lambda message: True)
def auto_reply(message):
    bot.reply_to(message, "Thank you for your message! We'll get back to you soon.")

# Keep the bot running
bot.polling(6750611114:AAF-zzIOpMnDik7nNA3YE_a4D8uIMWFoMB0)

**Comment by Olimovich28** [comment]
from telegram import Update
from telegram.ext import Updater, CommandHandler, CallbackContext

# Command handlers
def start(update: Update, context: CallbackContext) -> None:
    update.message.reply_text('🚀 Loyihada ishtirok etish uchun quyidagilarga kanallarga azo boʼling. Keyin "✅ А'zo boʼldim" tugmasini bosing')

def help(update: Update, context: CallbackContext) -> None:
    update.message.reply_text('Here are the commands you can use:\n/start - Start the bot\n/help - Get help')

def custom_command(update: Update, context: CallbackContext) -> None:
    update.message.reply_text('Tabriklaymiz siz endi bizning yopiq kanalimizga linkni qo'lga kiritdingiz')

# Main function to run the bot
def main():
    # Add your bot's token here
    updater = Updater("7460270316:AAH3a3pi8qK3JXt7YWzFLNNvaZ7MAwd9j2g")

    # Register the command handlers
    dispatcher = updater.dispatcher
    dispatcher.add_handler(CommandHandler("start", start))
    dispatcher.add_handler(CommandHandler("help", help))
    dispatcher.add_handler(CommandHandler("custom", custom_command))

    # Start the bot
    updater.start_polling()
    updater.idle()

if name == 'main':
    main()
