### ISSUE TITLE
Error timeout not working as expected on async

### ISSUE THREAD

**Issue by coder2020official** [eternnoir/pyTelegramBotAPI#2368]
There have been reports saying that error timeout is not working as expected in async during 429 issues.

**Comment by All-The-Foxes** [comment]
This is true. Any exception is ignored in infinity polling. If a token is revoked while running, e.g. it becomes compromised and Telegram revokes it, the 401 error is also ignored and polling keeps retrying despite spamming that it's unauthorized in the logs.

Here is an example of 429 being ignored.
![IMG_20240815_152956_314](https://github.com/user-attachments/assets/86556dd3-4e63-4140-9235-d776a85555bf)

**Comment by Badiboy** [comment]
Is it still actual?

**Comment by coder2020official** [comment]
couldn't reproduce.
