### ISSUE TITLE
Bot API 7.9

### ISSUE THREAD

**Issue by coder2020official** [eternnoir/pyTelegramBotAPI#2374]
..is out!
Will start working on this from tomorrow evening

**Comment by coder2020official** [comment]
@Badiboy the middleware fix might have affected some users. Do you think it is very urgent to release the update RIGHT NOW or wait for bot API update too?

**Comment by Badiboy** [comment]
I cannot release for next 5 days, so If you have plans to go with new BotAPI - you have time for that. :)

PS. I can TRY to release 7.8.1, but most probably I will not.

**Comment by coder2020official** [comment]
What is 7.8.1

**Comment by coder2020official** [comment]
Got it

**Comment by Badiboy** [comment]
Sorry, 4.22.1 ))))

Try it?

**Comment by coder2020official** [comment]
It also contains states tho 
Could you not only release fix for middlewares?

**Comment by Badiboy** [comment]
I propose to release everything. Because nearly nobody will run git version and you will get no feedback.

When released, we will have time for feedbacks while bot API are in progress.

**Comment by coder2020official** [comment]
Well, if you think so, ok
I didn't need feedback rn, I wanted to release it in a little bigger release
But if you insist - ok

**Comment by Badiboy** [comment]
I failed to push release. So no way to release earlier then 5 days later.

**Comment by Badiboy** [comment]
I just succeed in pushing version update. Sending release to pypi...

OMG, I see. I don't know what is on pypi. I failed sending packet there... 
Could you please try to install pypi version? It may be broken.
