### ISSUE TITLE
Enforce users joining channels

### ISSUE THREAD

**Issue by rsoorajs** [eternnoir/pyTelegramBotAPI#2375]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.14.1
2. What OS are you using?
 linux

4. What version of python are you using?
3.11

Is there any method provides in pyTelegramBotApi, to enforce users to join a channel to use our bot ?

**Comment by Badiboy** [comment]
No. You need to make some work yourself.

**Comment by coder2020official** [comment]
Use getchatmember
Also ask this in the chat

**Comment by rsoorajs** [comment]
> Use getchatmember Also ask this in the chat

Thank you
