### ISSUE TITLE
Proposal: any_text, any_entities

### ISSUE THREAD

**Issue by Badiboy** [eternnoir/pyTelegramBotAPI#2382]
@coder2020official 

Processing user messages often requires checking answer for some text like commands or button names or something else. However answer may contain media, so now we need to check caption if media or text if not.

I got an idea to add properties "any_text" and "any_entities" (not sure second one is really needed) to Message class.

```
    @property
    def any_text(self):
        return self.caption if (self.caption is not None) else self.text

    @property
    def any_entities(self):
        return self.caption_entities if (self.caption_entities is not None) else self.entities
```

Your oppinion?

**Comment by coder2020official** [comment]
Yes, ofc this is a good thing. Both are useful.

We need more properties like this, and I had one such in mind also:

- Adding a property to return message.contact.user_id == message.from_user.id, not sure about the name though;
