### ISSUE TITLE
Download voice message as mp3

### ISSUE THREAD

**Issue by ranjitsingha** [eternnoir/pyTelegramBotAPI#2388]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Latest

2. What OS are you using? Ubuntu

3. What version of python are you using? Lastest 

How to directly download the voice messages which are in ogg format to mp3 so that we don't need to convert using pydub or ffmpeg

**Comment by Badiboy** [comment]
Telegram provides ogg. You need to convert it to MP3 yourself. Not the subject of the library.
