### ISSUE TITLE
InlineKeyboard callback doesnt work

### ISSUE THREAD

**Issue by ThisIsLastFly** [eternnoir/pyTelegramBotAPI#2408]
I’m developing a Telegram bot in Python and have implemented inline buttons with callback data. The bot’s setup is straightforward, and the button structure and callback functions are correctly configured. However, the bot doesn’t process or respond to any callback data when buttons are pressed, despite no apparent issues in the code itself. The callback function seems to remain inactive regardless of adjustments I’ve tried.

Here’s what I’ve attempted so far:

    Changing Python versions from 3.12.6 to 3.11.0.
    Changing the pyTelegramBotAPI library from 4.23.0 to 4.22.0 version
    Running the bot on various devices, including a mobile phone (pydroid), to eliminate possible device-specific issues.

Code:
```python
import telebot
from telebot import types

TOKEN = 'hidden'
bot = telebot.TeleBot(TOKEN)


@bot.message_handler(commands=['start'])
def main(message):
    markup = types.InlineKeyboardMarkup()
    buy_btn = types.InlineKeyboardButton("Buy",
                                             callback_data="buy")
    purchases_btn = types.InlineKeyboardButton("Purchases",
                                               callback_data="show_purchases")

    markup.row(buy_btn, purchases_btn)

    settings_btn = types.InlineKeyboardButton("Settings",
                                              callback_data="show_settings")
    markup.row(settings_btn)

    bot.reply_to(message, "Choose one:", reply_markup=markup)


@bot.callback_query_handler(func=lambda callback: callback.data)
def callbacks(callback):
    print(f"Callback data received: {callback.data}")
    if callback.data == "buy":
        bot.send_message(callback.message.chat.id, "Buy")


if __name__ == '__main__':
    bot.polling(none_stop=True)
```

LIB: pyTelegramBotAPI 4.23.0, 4.22.0
OS: Manjaro Linux, Android (PyDroid app)
PY: 3.12.6, 3.11.0

Solution:
Type /revoke to bot father and replace token.

**Comment by Badiboy** [comment]
Try setting _allowed_updates_ to [“message”, “callback_query”]?

**Comment by ThisIsLastFly** [comment]
> Try setting _allowed_updates_ to [“message”, “callback_query”] in polling?

Just tried it change to `bot.polling(none_stop=True, allowed_updates=["message", "callback_query"])`
Didn't help. The problem remains

**Comment by ThisIsLastFly** [comment]
> Try setting _allowed_updates_ to [“message”, “callback_query”] in polling?

I figured out what the problem was. The buttons were not working because, apparently, another bot was supposedly connected to the token, even though it wasn't. I discovered this purely by accident when I decided to change the button type from InlineKeyboard to ReplyKeyboardMarkup. After making these changes, I finally saw the error  `A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running` ,  that had been causing me so much trouble. Please implement an error message for InlineKeyboard as well, as this issue can be very confusing.
