### ISSUE TITLE
Deprecation warning when calling get_chat

### ISSUE THREAD

**Issue by coder2020official** [eternnoir/pyTelegramBotAPI#2412]
calling bot.get_chat throws this warning:

The parameter "can_send_media_messages" is deprecated. Use individual parameters like "can_send_audios", "can_send_documents" etc.

@Badiboy can you please investigate it? I looked at the origin and for some reason we are checking for presence of de_json in kwargs and for can_send_media_messages, which I don't remember. Since you have implemented it and probably remember how it works, please take a look...

**Comment by Badiboy** [comment]
Works fine for me. 

Looks like it may be raised by old library version. Deprecation warning from get_chat was suppressed by de_json=True parameter of ChatPermissions constructor.
