### ISSUE TITLE
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message text is empty

### ISSUE THREAD

**Issue by Tusenka** [eternnoir/pyTelegramBotAPI#2414]
Message:
`<telebot.types.Message object at 0x7b3885a80d90>
message text: 0
 ` 
1. What version of pyTelegramBotAPI are you using?
latest

3. What OS are you using?
`Linux cas12 6.8.0-47-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

5. What version of python are you using?
3.10

**Comment by coder2020official** [comment]
Read the error message once more

**Comment by Tusenka** [comment]
> Read the error message once more

thank you!
