### ISSUE TITLE
edit_message_media() does not preserve original text neither markup of original message

### ISSUE THREAD

**Issue by Archangelll** [eternnoir/pyTelegramBotAPI#2422]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.24.0

2. What OS are you using? Windows 10 Home

3. What version of python are you using? 3.13.0

my bot sends a photo to the user with caption and reply_markup and when i try to replace this photo with edit_message_media() the original text and reply_markup() are deleted

**Comment by Badiboy** [comment]
edit_message_media passes parameters correctly.

https://core.telegram.org/bots/api#editmessagemedia

It looks like that you should pass both aption (in Media) and reply_markup (in function)... Looks like nonsence, but...
