### ISSUE TITLE
mlink with escape=False

### ISSUE THREAD

**Issue by samvova** [eternnoir/pyTelegramBotAPI#2425]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.12
2. What OS are you using?
Windows
3. What version of python are you using?
3.10

Please check code formatting.py
```python
def mlink(content: str, url: str, escape: Optional[bool]=True) -> str:
    return '[{}]({})'.format(escape_markdown(content), escape_markdown(url) if escape else content)
```
its mistake in case of escape=False - url will be changed to content

should be `return '[{}]({})'.format(escape_markdown(content), escape_markdown(url) if escape else url)`

**Comment by Badiboy** [comment]
Looks reasonable. Please, push PR.

**Comment by samvova** [comment]
> Looks reasonable. Please, push PR.

this is my first PR for a project of such scale as telebot. i was nervous to be honest. 
Thanks you all, Great team!

**Comment by Badiboy** [comment]
> this is my first PR for a project of such scale as telebot

🤜🤛
