### ISSUE TITLE
bot.infinity_polling() is not working, without errors

### ISSUE THREAD

**Issue by webcartel-https** [eternnoir/pyTelegramBotAPI#2439]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? - 4.24.0

2. What OS are you using? - Win

3. What version of python are you using? - 3.12.4

I wrote a simple telegram bot that will give information when entering a certain command. In my script I used bot.infinity_polling(), but at some point it just stopped working.
The script starts, 
All code work fine
 and ... script closes, on bot.infinity_poling() line

Initially the script looked like this
``` Python
# .... some shit code
try:
 bot.infinity_polling()
finally:
# ... more shit code
```

Then:
 I tried this:
 ``` Python
 bot.infinity_polling()
```

Then i tried this:
``` Python
bot.polling(non_stop=True)
```
Also a tried this:
``` Python
th = threading.Thread(target=bot.infinity_polling).start()
```
I use python debugger, script stop working on bot.infinity_polling() line. The code below is not executed, the program simply terminates

**Comment by Badiboy** [comment]
If the program terminates in spte of "finally" - the problem is somewhere in your code. Nothing about infinity_polling here: it does not terminate program anyway.

**Comment by webcartel-https** [comment]
> If the program terminates in spte of "finally" - the problem is somewhere in your code. Nothing about infinity_polling here: it does not terminate program anyway.

You are right. I rewrite the whole code in different way and everything works fine. Thank you!
