### ISSUE TITLE
Regex dosen`t work.

### ISSUE THREAD

**Issue by zelds** [eternnoir/pyTelegramBotAPI#247]
Have some trouble with start use regexp in my bot. When i send to bot simple 'qwe-12-12' it says nothing.

```
@bot.message_handler(regex='\w{0,4}-\d{0,2}-\d{0,2}')
def parese_group(message): # Название функции не играет никакой роли, в принципе
    bot.send_message(message.chat.id, message.text)
    config.log(message)
```
1. pip show says 0.0.3 but i install latest from zip by `setup.py install`
2. Elementary OS
3. 3.5

**Comment by Kondra007** [comment]
> pip show says 0.0.3

Looks like that's the problem, You installed lib as `pip install telebot`? Then you're wrong. Use `pip install pytelegrambotapi`

**Comment by Kondra007** [comment]
Regarding your regex: use wrote "regex=" instead of "regexp=".

This code works fine: PyTelegramBotAPI v2.2.2, Python 3.5.2.

```python
@bot.message_handler(regexp=r"\w{0,4}-\d{0,2}-\d{0,2}")
def msg_regex(message):
    bot.send_message(message.chat.id, "Hi there!")
```

**Comment by zelds** [comment]
Thx.For answer. Sorry for dummy question.

**Comment by Kondra007** [comment]
Please close the issue if your problem is solved
