### ISSUE TITLE
Why you skip field 'chat_instance' in CallbackQuery? (pyTelegramBotAPI-2.2.3)

### ISSUE THREAD

**Issue by odinsnik** [eternnoir/pyTelegramBotAPI#250]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2.2.3

2. What OS are you using?
Windows, CentOS

3. What version of python are you using?
3.5.2

like it is in here https://core.telegram.org/bots/api/#callbackquery

**Comment by Kondra007** [comment]
What do you mean by "skip". As far as I see in `types.py` file, `chat_instance` field is present and bots can see it.

**Comment by odinsnik** [comment]
Sorry, I confused
