### ISSUE TITLE
Api timeout causing bot crash

### ISSUE THREAD

**Issue by SergiX44** [eternnoir/pyTelegramBotAPI#251]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Latest
2. What OS are you using?
Debian Jessie
3. What version of python are you using?
Tested on python 2.7.10 and pypy

```
Traceback (most recent call last):
  File "bot.py", line 350, in <module>
    bot.polling(none_stop=True)
  File "/opt/pypy/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/opt/pypy/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/opt/pypy/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/opt/pypy/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/opt/pypy/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/opt/pypy/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/opt/pypy/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/opt/pypy/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/opt/pypy/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/pypy/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/pypy/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/opt/pypy/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
```

Sometimes my telegram bot is crashing with this stacktrace (timeout from the telegram api). I've set the bot polling to `bot.polling(none_stop=True)` and according to method docs `:param none_stop: Do not stop polling when an ApiException occurs.` this shouldn't happen. Is this a bug? How can I avoid this problem?

**Comment by denisergashbaev** [comment]
try this maybe?:

`    
while True:
        try:
            bot.polling(none_stop=True)
        # ConnectionError and ReadTimeout because of possible timout of the requests library
        # TypeError for moviepy errors
        # maybe there are others, therefore Exception
        except Exception as e:
            logger.error(e)
            time.sleep(15)
`

**Comment by MasterGroosha** [comment]
So... is there any _working_ solution to this?

**Comment by maddness** [comment]
Firstly, thanks eternnoir for an amazing library!

But also wondering about this issue, keep getting those errors several times a day.
Wrapping in infinite while doesn't seems a perfect solution?

Could this be resolved using webhooks approach?

**Comment by eternnoir** [comment]
Use @denisergashbaev 's approach is fine. The `ApiException` means telebot's exception like `your request telegram bot api server not accept, api key error ..etc.` not network exception. If network exception occurs you still need handle this.

```python
while True:

    try:

        bot.polling(none_stop=True)

    # ConnectionError and ReadTimeout because of possible timout of the requests library

    # TypeError for moviepy errors

    # maybe there are others, therefore Exception

    except Exception as e:

        logger.error(e)

        time.sleep(15)
```

**Comment by sduisenbay** [comment]
@eternnoir - Hi! A *great library*! Thanks a lot for it, doing a couple of bots using it.
 I have a small problem, I although I wrote the part that catches exceptions, it still stops in a few days. What might the problem?

Thanks!

**Comment by sviat9440** [comment]
@sduisenbay `bot.infinity_polling(True)`

**Comment by memeToasty** [comment]
I still have that Problem, even using the try / except Method with the polling

**Comment by mroctavious** [comment]
> @sduisenbay `bot.infinity_polling(True)`

This one worked great for me. 

Thanks!

**Comment by palandovalex** [comment]
To not break keyboard interrupt pulling stop

```
run_bot = True
while run_bot:

    try:

        bot.polling(none_stop=True)
        run_bot = False
    # ConnectionError and ReadTimeout because of possible timout of the requests library

    # TypeError for moviepy errors

    # maybe there are others, therefore Exception

    except Exception as e:

        logger.error(e)

        time.sleep(15)
```
