### ISSUE TITLE
Which way should I take to get the user's timezone?

### ISSUE THREAD

**Issue by hovikk** [eternnoir/pyTelegramBotAPI#256]
I have a database with some football matches. So, I have entered **_separately_** the values of hours, minutes, days, months and years in **UTC**. Well, how should I catch the user's timezone to convert the **UTC** time into the user's local time. And probably I did a mistake by entering the values of date and time separately, so could you also please advice me the best way to change the columns. **Any** help is appreciated! Thank you!

**Comment by DmytryiStriletskyi** [comment]
If you have question about database, but not about pyTelegramBotAPI — search some topic on the internet. Example, how to change column`s datatype in PostgreSQL— https://www.postgresql.org/docs/current/static/sql-altertable.html

**Comment by DmytryiStriletskyi** [comment]
If you want to know user`s timezone, you can ask their about location directly — https://core.telegram.org/bots/api/#location
And then calculate UTC with another services.
