### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by legard** [eternnoir/pyTelegramBotAPI#259]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2.2.3

2. What OS are you using?

Windows 7 64bit

3. What version of python are you using?

Python 3.5.2.

I try run simple application:

```
import telebot

bot = telebot.TeleBot("<token>")

@bot.message_handler(commands=['start'])
def start(message):
    sent = bot.send_message(message.chat.id, 'Who are you?')
    bot.register_next_step_handler(sent, hello)

def hello(message):
    bot.send_message(message.chat.id, 'Hello, {name}. Nice to meet you.'.format(name=message.text))

bot.polling()
```

> And have this Traceback :
> 
> C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\python.exe "D:/OneDrive/OneDrive - Nokia/project/5620/bots/tgbot.py"
> Traceback (most recent call last):
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
>     chunked=chunked)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
>     self._validate_conn(conn)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
>     conn.connect()
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connection.py", line 323, in connect
>     ssl_context=context)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 324, in ssl_wrap_socket
>     return context.wrap_socket(sock, server_hostname=server_hostname)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 377, in wrap_socket
>     _context=self)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 752, in __init__
>     self.do_handshake()
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 988, in do_handshake
>     self._sslobj.do_handshake()
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 633, in do_handshake
>     self._sslobj.do_handshake()
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 423, in send
>     timeout=timeout
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 643, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\util\retry.py", line 334, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
>     chunked=chunked)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
>     self._validate_conn(conn)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
>     conn.connect()
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\connection.py", line 323, in connect
>     ssl_context=context)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 324, in ssl_wrap_socket
>     return context.wrap_socket(sock, server_hostname=server_hostname)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 377, in wrap_socket
>     _context=self)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 752, in __init__
>     self.do_handshake()
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 988, in do_handshake
>     self._sslobj.do_handshake()
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\ssl.py", line 633, in do_handshake
>     self._sslobj.do_handshake()
> requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:/OneDrive/OneDrive - Nokia/project/5620/bots/tgbot.py", line 14, in <module>
>     bot.polling()
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\telebot\__init__.py", line 196, in polling
>     self.__threaded_polling(none_stop, interval, timeout)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\telebot\__init__.py", line 219, in __threaded_polling
>     polling_thread.raise_exceptions()
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\telebot\util.py", line 73, in raise_exceptions
>     six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\six.py", line 686, in reraise
>     raise value
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\telebot\util.py", line 54, in run
>     task(*args, **kwargs)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\telebot\__init__.py", line 126, in __retrieve_updates
>     updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\telebot\__init__.py", line 96, in get_updates
>     json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\telebot\apihelper.py", line 145, in get_updates
>     return _make_request(token, method_url, params=payload)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\telebot\apihelper.py", line 34, in _make_request
>     result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\api.py", line 56, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 488, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 609, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Users\tabolin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 473, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
> 

On ubuntu this code work very well. 
I reinstall python on windows, but dont work. what's the matter?

**Comment by caztillo** [comment]
I have the same problem on Windows 10

**Comment by pvburkov** [comment]
The same problem at Windows Server 2012. WTF is going on?

**Comment by helloong** [comment]
I got the same problem on WIndows Server 2016.
Anyone solved this?

**Comment by freealeks80** [comment]
Any solution?

**Comment by virusAl7rbi** [comment]
same problem

**Comment by Badiboy** [comment]
Just make exception handling around polling. 
Or use infinity_polling instead of polling.

**Comment by rrvermaa** [comment]
It's solved by using open Wi-Fi means connect your system with Wi-Fi which don't have password.
