### ISSUE TITLE
Make clients able to register for message replies

### ISSUE THREAD

**Issue by pevdh** [eternnoir/pyTelegramBotAPI#26]
It would be useful to not only be able to subscribe to certain commands, but also subscribe to message replies.
For example:
Bot sends: "How many apples do you want?", person replies "3". How does the bot know that the person is replying to his question?
This can be solved by adding a `register_for_reply` function or something similar.

This is how that would look:
```python
def process_reply(message):
    bot.reply_to(message, "Good choice!")

sent_message = bot.send_message(chat_id, "How many apples do you want?", reply_markup=types.ForceReply())
bot.register_for_reply_to(sent_message, process_reply)
```
`register_for_reply_to` would store the sent_message.message_id and process_reply in a dictionary.
When the bot receives a message with `message.reply_to_message.message_id == sent_message.message_id` he notifies `process_reply` and passes the `message` to the function.

I would have implemented this myself, but I will be away for the coming few weeks, so I thought I would just make an issue about this idea :) I hope you get the idea, if not, feel free to ask for clarification.

**Comment by GabrielRF** [comment]
I've done something like this on a bot already. I save the user last message and wait for the next one.
It's working nicely.
The bot: https://www.telegram.me/safe_bot
The bot's code: https://github.com/GabrielRF/Telegram-Safe-Bot

**Comment by pevdh** [comment]
I used to implement a bot the same way you did, but I wanted to get rid of the if-else statements, I think this would be a great help in avoiding many if-else statements and thus contribute to easier to read code.

**Comment by YBinnenweg** [comment]
I would personally prefer @pevdh's idea. I've had a quick look at @GabrielRF's code, I'm by no means a Python expert, but that way seems to break the whole idea of using decorators for commands.

+1

**Comment by GabrielRF** [comment]
@YBinnenweg I'm not even close a good developer. I do it on my spare time. I'm pretty sure it was not the best way to do it, but it was the way I knew by the time.
I'm studying a whole new solution using decorators. :)

**Comment by YBinnenweg** [comment]
@GabrielRF I'm intrigued to see what you can come up with! I've been looking at it for a while, and I couldn't really find a way to do it within the decorator 'limits'. (ie. not using a listener) That, of course, doesn't mean it's not possible!

Good luck! :)

**Comment by pevdh** [comment]
A ```wait_for_reply``` function could be created, but that would stall a whole thread,  and that reply might not even come.

**Comment by Kondra007** [comment]
@pevdh, I'm having some arrays for this.
If user sent /apples, add him to waiters array.
On his next message, if he's in that array, bot replies to him and deletes from that array.
Arrays stay in memory and are dumped to Shelve on keyboard interrupt.

**Comment by pevdh** [comment]
Yea it all comes down to some kind of state machine. What I normally do is create a ChatContext object for each chat, and store chat id, state and chat history in it.

**Comment by Kondra007** [comment]
Maybe we could use some kind of [stack](http://interactivepython.org/runestone/static/pythonds/BasicDS/stacks.html)
