### ISSUE TITLE
Error importing module

### ISSUE THREAD

**Issue by vovawed** [eternnoir/pyTelegramBotAPI#260]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2.2.3

2. What OS are you using?
Fedora 25

3. What version of python are you using?
Python 3.5.2

When I import pyTelegramBotAPI I have:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/telebot/__init__.py", line 23, in <module>
    from telebot import apihelper, types, util
  File "/usr/lib/python3.5/site-packages/telebot/apihelper.py", line 3, in <module>
    import requests
  File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python3.5/site-packages/requests/utils.py", line 26, in <module>
    from .compat import (
ImportError: cannot import name 'integer_types'`

**Comment by Ritmxoid** [comment]
The same issue

**Comment by eternnoir** [comment]
What version of `requests` package ?

**Comment by Ritmxoid** [comment]
I can successfully install requests-2.12.3 via pip but it doesn't work. When I tried to install via dnf I failed: "Error unpacking rpm package python3-requests-2.10.0-4.fc25.noarch"

**Comment by MonsterDeveloper** [comment]
Try to do "sudo pip3 install --upgrade requests" or "sudo pip install --upgrade requests"

**Comment by Intervencion** [comment]
Not sure if will work but you can try
`sudo apt-get remove python-requests*
sudo easy_install pip
sudo pip install -U requests`

**Comment by MonsterDeveloper** [comment]
If you are using python3, use package "python3-requests"

**Comment by mayaracsferreira** [comment]
When I got this error this helped me https://github.com/eternnoir/pyTelegramBotAPI/issues/323
