### ISSUE TITLE
Add support for channel_post and edited_channel_post

### ISSUE THREAD

**Issue by kypsibir** [eternnoir/pyTelegramBotAPI#262]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2.2.3
2. What OS are you using?
Windows 7
3. What version of python are you using?
3.5.2

**Comment by Kondra007** [comment]
Done. See #c168fee

**Comment by kypsibir** [comment]
Thanks a lot!
