### ISSUE TITLE
The bot catches commands not directed to it

### ISSUE THREAD

**Issue by TPXP** [eternnoir/pyTelegramBotAPI#263]
Hey there !

Thank you for this awesome telegram bot API, it works like a charm ! I just have a little remark about the way the bot handles commands : it has a terrible trend to handle commands not directed to it. This is a bug that you can easily notice if you put in a group multiple bots using your API and try to send `/start` to a specific bot : in order to achieve this, you will have to resort to `/start@BotName`. However, you will notice that every bot using this API will reply, including the ones this command is not directed to according to the @mention . This creates uneeded spam in a chat, especially when the command is a command that produces a certain amount output, like `/help`.

Coud this be avoided ? That would be great ! If you don't have time, just tell me and I will gladly submit a pull request in a few weeks ! 😄

---------------------------------------------------------------------------------------------------
1. What version of pyTelegramBotAPI are you using?
2.2.3 (latest)

2. What OS are you using?
Archlinux on Raspberry PI (armv7h)

3. What version of python are you using?
3.5.2

**Comment by eternnoir** [comment]
Maybe need add group mode to telebot. If message from group must check command contain bot name.

I'll try to add this feature in next version update.
