### ISSUE TITLE
Bot freeze when got many callback_query requests from channel's inline button

### ISSUE THREAD

**Issue by kostyakoz** [eternnoir/pyTelegramBotAPI#269]
I'm using webhooks, with `max_connections=100`. When I get many requests, this is what I see:

![screen shot 2016-12-12 at 21 58 18](https://cloud.githubusercontent.com/assets/1935229/21112331/768b05da-c0b6-11e6-95d4-b9804deea66c.png)

I see HTTP requests but bot doesn't handle it. The server is not experiencing heavy load.
Some time later bot handles all requests. Why do I have this delay?

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
**2.3.0**
2. What OS are you using?
**Ubuntu 16.10**
3. What version of python are you using?
**3.5.2**

**Comment by eternnoir** [comment]
Is thread blocked by your handler? Request process by telebot's thread pool. If your handler block all threads in pool, telebot won't process new request.
