### ISSUE TITLE
Full system load with these bots

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#27]
Hello again.
In you README in "echo-bot" example you write:
```python
while True: # Don't let the main Thread end.
    pass
```
previously there was `time.sleep(20)` string.
I've tried your new variant and I'm having 95-100% load on CPU (with `pass` only)  
I've changed to
 ```python
while True:
    time.sleep(20)
``` 
 and now it's fine (1-3% load)

Could you please explain this? Is it API problem or anything else?

**Comment by eternnoir** [comment]
Because no sleep in infinite loop the main thread will always do looping. Add sleep to release cpu time.
It is not api problem.

**Comment by pevdh** [comment]
I only wrote `pass` for simplicity's sake, `pass` should never be used
