### ISSUE TITLE
QUERY_ID_INVALID problem in inline mode

### ISSUE THREAD

**Issue by jls21** [eternnoir/pyTelegramBotAPI#270]
I wanna show inline list of suggestion, but server returns Bad Request: QUERY_ID_INVALID.
I read that query_id will expire in 10 seconds, I send request at 22:34:15,242 and get answer at 22:34:25,503. 
Why api couldn't process it in 10 seconds? Whats wrong ?

> 2016-12-12 22:34:15,242 (apihelper.py:28 WorkerThread2) DEBUG - TeleBot: "Request: method=post url=https://api.telegram.org/bot136496371:AAGwE7_QGVUGfrGMRGET8k75N0aMkSRSRcE/answerInlineQuery params={'inline_query_id': u'775712257326708075', 'results': '[{"input_message_content": {"message_text": "None"}, "type": "article", "id": "-1", "title": "\\u041d\\u0435 \\u043d\\u0430\\u0439\\u0434\\u0435\\u043d\\u043e"}]'} files=None"
> 2016-12-12 22:34:25,503 (apihelper.py:35 WorkerThread2) DEBUG - TeleBot: "The server returned: '{"ok":false,"error_code":400,"description":"Bad Request: QUERY_ID_INVALID"}'"
> A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
> [{"ok":false,"error_code":400,"description":"Bad Request: QUERY_ID_INVALID"}]
> 2016-12-12 22:34:25,503 (util.py:55 WorkerThread2) DEBUG - TeleBot: "Task complete"

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2.3.3
2. What OS are you using?
MacOS El Capitan
3. What version of python are you using?
Python 2.7

**Comment by MasterGroosha** [comment]
> I read that query_id will expire in 10 seconds
Where did you read that? Sound like a fake. `query_id` must be unique within one Inline reply (this is important if you use offsets to load more data on scroll).
