### ISSUE TITLE
'module' object has no attribute 'ReplyKeyboardHide'

### ISSUE THREAD

**Issue by Feduch** [eternnoir/pyTelegramBotAPI#271]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI (2.3.0)
2. What OS are you using?
Linux Gentoo
3. What version of python are you using?
Python 3.4.3

```
try:
              markup = types.ReplyKeyboardHide()
              bot.send_message(message.chat.id, '1', reply_markup=markup)
except Exception as e:
              print("%s" % e)
```

in log 'module' object has no attribute 'ReplyKeyboardHide' and don`t send messege to chat

**Comment by eternnoir** [comment]
You need use `ReplyKeyboardRemove` in 2.3.0. Check official bot api removed ReplyKeyboardHide.

**Comment by Feduch** [comment]
Thank you!
