### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TeleBot'

### ISSUE THREAD

**Issue by martinetoledo** [eternnoir/pyTelegramBotAPI#274]
I'm using Python 2.7 and just copied and pasted the sample code in the Docs so as to try see if it works. It just raises that Traceback. The code is the following:

`import telebot

bot = telebot.TeleBot("TOKEN")

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "Howdy, how are you doing?")

@bot.message_handler(func=lambda message: True)
def echo_all(message):
    bot.reply_to(message, message.text)

bot.polling()`

**Comment by iliakonnov** [comment]
All working for me. But only if i'm using real token.
Files used in test: https://gist.github.com/iliakonnov/05e1bf2e36b77baa317604528f0fc983
```
user@computer:~$ pip2.7 freeze | grep pyTelegramBotAPI
pyTelegramBotAPI==2.3.0
user@computer:~$ python2.7 -V
Python 2.7.12
user@computer:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
user@computer:~$ python2.7 pyTelegramBotAPI_issue274_notoken.py 
2016-12-28 16:25:38,109 (__init__.py:220 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 404 Not Found. Response body:
[{"ok":false,"error_code":404,"description":"Not Found"}]"
user@computer:~$ python2.7 pyTelegramBotAPI_issue274_token.py 
^Cuser@computer:~$
```

**Comment by MasterGroosha** [comment]
@martinetoledo Is your problem solved?

**Comment by martinetoledo** [comment]
Sorry I've been away from home for some weeks. I'll try this ASAP. Thanks for your time.

________________________________

**Comment by martinetoledo** [comment]
I used iliakonnov recommendation and now works fine. Thank you.
