### ISSUE TITLE
Timeout value connect was (3.5, 9999), but it must be an int or float.

### ISSUE THREAD

**Issue by icduicdu** [eternnoir/pyTelegramBotAPI#276]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Latest

2. What OS are you using?
Ubuntu 14.04

3. What version of python are you using?
2.7.6

Code raised exception:
```
bot = telebot.TeleBot(BOT_TELEGRAM_CREDENTIALS)
bot.send_message(recipient, message)

```

**Comment by MasterGroosha** [comment]
Have you tried updating requests library?

**Comment by icduicdu** [comment]
Yeap, requests latest version installed.
