### ISSUE TITLE
AttributeError: 'TeleBot' object has no attribute 'message_handler'

### ISSUE THREAD

**Issue by logs777** [eternnoir/pyTelegramBotAPI#278]
Hello!
1. I'm using  pyTelegramBotAPI 2.3.0 and telebot==0.0.3
2. What OS are you using? My Telegram bot worked on Heroku.
3. In file runtime.txt  (which describe for Heroku version of python) - python-3.5.2.

Few days ago I started getting error 
`AttributeError: 'TeleBot' object has no attribute 'message_handler'`
And I absolutely can't understand, where is error in my code, everything seems to be ok.
I had the same error, when I launched my bot on VPS (Digital Ocean) with the same versions of modules on Ubuntu 16.10x64, python 3.5.

**Comment by logs777** [comment]
I changed my requirements.txt file from 
`PyTelegramBotAPI`
to 
`PyTelegramBotAPI==2.2.3`
and after that bot working again.

**Comment by wMw9** [comment]
I did
`pip3 uninstall telebot` then
`pip3 uninstall PyTelegramBotAPI` and then
`pip3 install PyTelegramBotAPI` and it works now!

**Comment by maheshmnj** [comment]
` import telebot
  File "C:\Users\mahesh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telebot\__init__.py", line 816
    @util.async()
`
I am getting this error I dont get it

**Comment by imnotadeveloper** [comment]
This helps me now :

> pip uninstall telebot then
> pip uninstall PyTelegramBotAPI 
> pip install PyTelegramBotAPI

**Comment by nextalgon** [comment]
вчера у меня работал код, а сегодня нет! переустановил pycharm python 3.9, переустановил pycharm, переустановил PyTelegramBotAPI на 2.2.3, но все таки не работает

**Comment by asd-21** [comment]
> вчера у меня работал код, а сегодня нет! переустановил pycharm python 3.9, переустановил pycharm, переустановил PyTelegramBotAPI на 2.2.3, но все таки не работает

У меня такая же беда. Решили проблему?

**Comment by dasshit** [comment]
А кусок кода с импортами и объявлением бота можете сюда скинуть?

**Comment by Rozhin81** [comment]
I follow these steps but it didn't work for me :
pip uninstall telebot
pip uninstall pyTelegramBotAPI
pip install pyTelegramBotAPI==2.2.3
what sould I do ,now?

**Comment by iZhitin** [comment]
Удалил через cmd:
pip uninstall telebot
pip uninstall pytelegrambotapi

Затем в pycharm в пакетах через интерфейс программы удалил telebot и установил pytelegrambotapi

Проблема решилась

**Comment by Nik0Bellic** [comment]
> Удалил через cmd: pip uninstall telebot pip uninstall pytelegrambotapi
> 
> Затем в pycharm в пакетах через интерфейс программы удалил telebot и установил pytelegrambotapi
> 
> Проблема решилась

Твое помогло, ничего до этого не помогало. Спасибо!!!

**Comment by cpljoshrayperson** [comment]
Столкнулся с той же проблемой, все вышеуказанное не помогает решить.

**Comment by coder2020official** [comment]
@cpljoshrayperson proceed to https://t.me/pytelegrambotapi_talks_ru

**Comment by James-Baxter-The-Horse** [comment]
> This helps me now :
> 
> > pip uninstall telebot then
> > pip uninstall PyTelegramBotAPI
> > pip install PyTelegramBotAPI

This did it for me, thanks!
