### ISSUE TITLE
Bot stops reacting after a few hours

### ISSUE THREAD

**Issue by julianschritt** [eternnoir/pyTelegramBotAPI#279]
1. What version of pyTelegramBotAPI are you using?
**2.3.0**
2. What OS are you using?
**Raspbian Jessie**
3. What version of python are you using?
**Python 2.7.9**

I have a simple bot that reacts to commands and I use polling like this:

```
if __name__ == "__main__":
    while True:
        try:
            log.info("start polling")
            bot.polling(none_stop=True)
        except requests.exceptions.ReadTimeout as e:
    	    log.error('ReadTimeout')
            print >> sys.stderr, str(e)
            sleep(10)
        except requests.exceptions.ConnectionError as e:
    	    log.error('ConnectionError')
            print >> sys.stderr, str(e)
            sleep(10)
        except Exception as e:
            log.error('unexpected Exception')
            print >> sys.stderr, str(e)
            sleep(10)
```

This problem occurs everytime, for example a few days ago:
I started the bot at 9 in the morning and everything worked fine. 
At 1 PM I checked again and the bot still reacted. 
At 3 PM I tried again but the bot was down.
I then took a look at the logs and saw that there were a few exceptions:

```
2017-01-18 10:57:40,646 - ERROR: ReadTimeout
2017-01-18 10:58:25,722 - ERROR: ConnectionError
2017-01-18 10:59:10,798 - ERROR: ConnectionError
2017-01-18 10:59:36,575 - ERROR: ConnectionError
```

And after that the usual

```
2017-01-18 16:50:26,230 - DEBUG: https://api.telegram.org:443 "GET /MY_BOT_ID/getUpdates?timeout=20&offset=107698299 HTTP/1.1" 200 23
2017-01-18 16:50:26,323 - DEBUG: Starting new HTTPS connection (1): api.telegram.org
```

every 20 seconds.

Obviously there are some exceptions but the bot should keep polling and it does, but then a few hours after the ReadTimeout and ConnectionsErrors it doesn’t react anymore.

I also tried none_stop=False because I thought that it might get stuck at this point and doesn't start polling again but it didn't help.

Today there were no errors at all but suddenly the bot stopped responding and I still can see the "Starting new HTTPS connection" messages.

The only thing that helps is restarting the script. Do you have any idea what I could do about that?

**Comment by MasterGroosha** [comment]
#251 ?
