### ISSUE TITLE
Request for Secret Chat

### ISSUE THREAD

**Issue by GabrielRF** [eternnoir/pyTelegramBotAPI#28]
Do you have any plan on adding secret chats support?
I had an idea that I would like to use it. Reading your API, the one I like the most, I could not find anything about it. 
If possible, please add this functionality! :D

**Comment by rougeth** [comment]
+1!

**Comment by pevdh** [comment]
Could you explain what you mean with "secret chat support"?

**Comment by GabrielRF** [comment]
I would like to use secret chats on a bot. Is it already possible?
https://core.telegram.org/method/messages.requestEncryption

**Comment by Kondra007** [comment]
@GabrielRF I think secret chats are not available in BotAPI: https://core.telegram.org/bots/api
Btw, why do you need this?

**Comment by GabrielRF** [comment]
I would like to transmit passwords. Having the encrypted chat and message timer would be kind of fun. :)

**Comment by rougeth** [comment]
@GabrielRF why did you close it?

**Comment by GabrielRF** [comment]
@rougeth It cannot be done.
