### ISSUE TITLE
Get user data from bot

### ISSUE THREAD

**Issue by MarcSky** [eternnoir/pyTelegramBotAPI#281]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 2.3.0

2. What OS are you using? macos

3. What version of python are you using? 3.5

I have a inline buttons, pressing on them I want to receive information from the user, such as age or height. How to do it? Where can I read the text data from the user? How to determine which inline button refers answer?

**Comment by MonsterDeveloper** [comment]
For usual message it is easy - just use register_next_step_handler. But for callback buttons... It's more tricky. Tomorrow I will try to write example code for you.

**Comment by MonsterDeveloper** [comment]
Do you need to check this data? If its not, you can just write data in MongoDB of txt file

**Comment by MonsterDeveloper** [comment]
You can use force reply. Send it, check reply message text when user answers and write data
