### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by rafa93m** [eternnoir/pyTelegramBotAPI#289]
Hi, I'm making a small application and it already has its own log. 
Is there any way that the telebot does not write in the same log?

**Comment by MonsterDeveloper** [comment]
Telebot log? Never heard about that... Can you share you code?

**Comment by rafa93m** [comment]
The code is simple, whenever I get something register two test lines.

This is the code and as you see in the following image it is also recorded what I receive and what I send.

```
import telebot
import logging

LOG_FILENAME = 'prueba.log'
LOG_FORMAT = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(filename=LOG_FILENAME, level=logging.DEBUG, format=LOG_FORMAT)


API_TOKEN = 'xxxxxxxxxxxxxxxxxxxxxxxxxx'

bot = telebot.TeleBot(API_TOKEN)

# Handle all other messages with content_type 'text' (content_types defaults to ['text'])
@bot.message_handler(func=lambda message: True)
def echo_message(message):
    bot.reply_to(message, message.text)


    logging.info("Esto es un log de informacion")
    logging.error("Esto es un log de error")

bot.polling()
```

![log](https://cloud.githubusercontent.com/assets/12030658/22667904/02c28a30-ecbf-11e6-852e-c155576a9bb3.png)


I would like to only register what I want.

**Comment by eternnoir** [comment]
That is requests lib's log. You can use `logging.getLogger("requests").setLevel(logging.WARNING)` to set higher logging level to requests package.

**Comment by rafa93m** [comment]
Thank you very much! Now it works as I want.
