### ISSUE TITLE
CPU 100% after commit #e3025f4

### ISSUE THREAD

**Issue by GabrielRF** [eternnoir/pyTelegramBotAPI#29]
On commit #e3025f4 is suggested the change:
```
while True:
    time.sleep(20)
```
to:
```
while True: # Don't let the main Thread end.
    pass
```
But i've noticed that using this last method makes CPU goes to 100% all the time. I believe the time.sleep() is better.

**Comment by eternnoir** [comment]
Same issue here #27

**Comment by GabrielRF** [comment]
Sorry
