### ISSUE TITLE
Bot handle commands for other bots in group chats

### ISSUE THREAD

**Issue by DjKrip** [eternnoir/pyTelegramBotAPI#292]
![image](https://cloud.githubusercontent.com/assets/21053141/22701341/38633d22-ed7f-11e6-9c51-1585ca5211e7.png)

1. What version of pyTelegramBotAPI are you using?
2.3.0 from pip

2. What OS are you using?
heroku hosting

3. What version of python are you using?
3.6.0

My `/help` command handler code
```python
@bot.message_handler(commands=['start', 'help'], func=in_whitelist)
def start(msg):
	bot.send_message(msg.chat.id, r"""Привет!
Это кошерный самописный бот.
Не ругайтесь на него.""")
```

Privacy mode (https://core.telegram.org/bots#privacy-mode) is disabled

**Comment by eternnoir** [comment]
When privacy mode disabled bot will receive all message. So these two message are apply commands rule. A workaround is check text contain bot name.
