### ISSUE TITLE
New method to handle photos uploaded to Telegram

### ISSUE THREAD

**Issue by alexroche** [eternnoir/pyTelegramBotAPI#295]
First of all thankyou for this API, which I find very useful and very easy to use.

I want to REQUEST a NEW FETURE, since according to my understanding, this is something that can be done through telegram API, but not possible through this API:

**When a user uploads a photo to my bot (actually to telegram servers) I want my bot to get the handle or reference that allows it to access the photo and do something with it**

How can I do this ? Does pyTelegramBotAPI require a new method to be able to do it ?

Thanks a lot,
Alex

----

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Don't remember but I updated it last month.

2. What OS are you using? raspbian on raspberri pi

3. What version of python are you using? 2.7

**Comment by MasterGroosha** [comment]
```python
@bot.message_handler(content_types=["photo"]
def parse_all_photos(message):
    # Here you do something with incoming photos, for example:
    print(message.photo[-1].file_id)
```

**Comment by alexroche** [comment]
Thankyou very much!
I have tried your solution and it works.
Sorry for asking an obvious question. Now I realize that I was not understanding that for anything received, the related information can always be located in the differen elements of the message. 
The issue that I submitted can be closed.
