### ISSUE TITLE
Error "HTTP 413" when i sending file with russian symbols

### ISSUE THREAD

**Issue by ghost** [eternnoir/pyTelegramBotAPI#296]
1. "What version of pyTelegramBotAPI are you using?" - the last version

2. "What OS are you using?" - Windows 10 (x64)

3. "What version of python are you using?" - Python 3.4

I tried to send the audio file (or document) with Russian symbols:

_file = open('Файл.mp3','rb')
bot.send_audio(message.chat.id,file,None)_

And then i got this error: 

_(__init__.py:250 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 413 Request Entity Too Large. Response body: 
[b'']"_

( . _.)

**Comment by MonsterDeveloper** [comment]
Very strange (Правда странно). I think its `requests` or `telebot` error. Not Telegram's

**Comment by MasterGroosha** [comment]
Due to `A request to the Telegram API was unsuccessful. The server returned HTTP 413` response it's likely Telegram's refusing such files.  
In early 2016 it wasn't possible to send files with non-Latin symbols in name, so I think it hasn't changed.
