### ISSUE TITLE
module 'telebot' has no attribute 'types'

### ISSUE THREAD

**Issue by Corrandoo** [eternnoir/pyTelegramBotAPI#299]
Hello! I have updated pyTelegramBotAPI to 2.3.0 version and when I'm trying to launch my bot I have such error: module 'telebot' has no attribute 'types' I haven't meet this error before the update.
I am using MacOS Sierra with Python 3.5

**Comment by Intervencion** [comment]
Have you imported telebot first? Paste the import section please.

**Comment by Corrandoo** [comment]
import telebot, server_manager, config, image_decoder, datetime, time
from threading import Thread

types = telebot.types #
bot = telebot.TeleBot(config.token)

I had "from telebot import types" before on the third line but it hasn't worked too

**Comment by Intervencion** [comment]
Try

```
import telebot, server_manager, config, image_decoder, datetime, time
from threading import Thread
config.token = ''random:numbers"
types = telebot.types #
bot = telebot.TeleBot(config.token)
```

**Comment by Corrandoo** [comment]
Unfortunately, it is not woking too. I have never had such problem before the update.

**Comment by Intervencion** [comment]
Have you double checked that PyTelegramBotAPI is installed on the python you're using?

**Comment by Corrandoo** [comment]
Yes.
As I can see, I have problems only with the types. Not with whole telebot

**Comment by eternnoir** [comment]
```python
import telebot, server_manager, config, image_decoder, datetime, time
from threading import Thread

from telebot import types
bot = telebot.TeleBot(config.token)
```

If you have `from telebot import types` just use `types`. You do not need `types = telebot.types`.

**Comment by Corrandoo** [comment]
I wrote that this variant had not worked too. Everything stopped working after the update, do you understand?

**Comment by JMAgundezG** [comment]
In python 3.5 doesn't works `from telebot import types`, 
The Traceback is ` Traceback (most recent call last):
  File "calendar_api.py", line 4, in <module>
    from telebot import types
ImportError: cannot import name 'types' `

**Comment by mayaracsferreira** [comment]
Check it out, maybe this simple issue would help you like it did to me  https://github.com/eternnoir/pyTelegramBotAPI/issues/323

**Comment by ttresslar** [comment]
I am having the same issue. It was actually working not that long ago, but now I'm having an import issue

**Comment by gmsajeed** [comment]
pip uninstall telebot
pip install pytelegrambotapi
