### ISSUE TITLE
Detailed Example Bot

### ISSUE THREAD

**Issue by LeoDJ** [eternnoir/pyTelegramBotAPI#30]
Hey eternnoir,

I'm just getting started with this awesome API.

After some trouble, I got the listener and the custom keyboards working perfectly fine.
But now I'm wondering... If I register a handler on the command '/start'. Do I have to do additional filtering manually in the handler?

Because you have non-linked examples, it's quite hard to understand everything easily.
It would be REALLY helpful, if you could include an example in the Readme, that includes every feature of your really useful library in one example (listener on normal messages, custom keyboards, command handlers, chat actions and maybe even multimedia handling (sending/receiving).

Because I want to use all that in a project, but can't seem to get every component to work together...

Thank you very much in advance,
LeoDJ

**Comment by GabrielRF** [comment]
Sorry, but what kind of explanation do you need?
The Echo example was not clear for you? Any part in specific?

**Comment by LeoDJ** [comment]
Well, a more or less simple example using all capabilities of this API would be ideal... 

But what I don't quite understand right now is e.g: 
If I have a command handler registered onto the "/start" command, the listener also gets the "/start" message... So do I have to filter stuff like the commands and the "@BotName" out manually?

**Comment by GabrielRF** [comment]
On the @BotFather you will set your bot's privacy. It can be able to read everything on a group or only messages that mentions the bot.
You can use, for example:
```
if '/start' in text:
    action
```
or
```
if '/start' in text and '@botname' in text:
    action
```

**Comment by LeoDJ** [comment]
So, I have to filter manually, okay... 
And I guess, I'll also have to do parsing of command parameters manually, right? (/a asdf 1234)

I think I got it now... I just won't use the command handlers at all :P

**Comment by eternnoir** [comment]
I suggest you use message_handler to help filter commands. In official telegram bot api, command is a text message. The message handler just help you filter command type(like `/help`, `/start`). When the command match, telebot will send that message object to your handler. In handler you still have to get text from message object(if you need to know the command message), then parse them.

in your case, the message_handler could be:

```python
# Only message text start with '/a' will trigger this function.
@bot.message_handler(commands=['a'])
def command_a(message):
    try:
        text = message.text
        texts = text.split(' ')  
        # texts[0] -> /a
        # texts[1] -> asdf
        # texts[2] -> 1234
        # do something you want to do.
    except Exception as e:
        logger.error(e.message)
```

**Comment by pevdh** [comment]
I recommend you to use the message handler as well - don't reinvent the wheel if you do not need to. Arguably, the listener mechanism gives you more flexibility, but the message handler takes the burden of filtering your messages from you.

**Comment by LeoDJ** [comment]
Yeah, that's what I thought too.

So if I also want to receive "normal" messages in the listener (not a
command), I would still have to filter the commands out (e.g. "if first
letter != '/' do something) in addition to using the command handlers. I
guess.
Am 11.07.2015 09:53 schrieb "Pieter" <notifications@github.com>:

**Comment by LeoDJ** [comment]
After an afternoons worth of fiddeling, I now created a detailed example (https://github.com/eternnoir/pyTelegramBotAPI/pull/31)

**Comment by pevdh** [comment]
The message handler is capable of not only processing commands, but also regular expressions and lambda's.

E.g.:
@bot.message_handler(func=lambda message: message.text == "Hi")

Listeners and message handlers should not be mixed, because one can replace the other and mixing them compromises readability, but that's just my opinion.

**Comment by LeoDJ** [comment]
Okay, I forgot to include the message handlers with regex and lambda.

I know the multi-stage messaging is not quite readable, if it's split up
But how would you process a user reply to a question the bot asked?
```python
@bot.message_handler(func=lambda message: userStep[message.chat.id] == 1)
def msg_imageSelect:
  <stuff from handler>
```
Would that work like this?

**Comment by LeoDJ** [comment]
Okay, I tried it now, and it works like a charm! Will create a pull request shortly...

But I can't get the given examples of the regex and the document message handler to work...
```python
# Handles all messages which text matches the regex regexp.
# See https://en.wikipedia.org/wiki/Regular_expression
# This regex matches all sent url's.
@bot.message_handler(regexp='((https?):((//)|(\\\\))+([\w\d:#@%/;$()~_?\+-=\\\.&](#!)?)*)')
def command_url(message):
    bot.reply_to(message, "I shouldn't open that url, should I?")


# Handle all sent documents of type 'text/plain'.
@bot.message_handler(func=lambda message: message.document.mime_type == 'text/plain', content_types=['document'])
def command_handle_document(message):
    bot.reply_to(message, "Document received, sir!")
```

It always calls my default message handler
```python
#default handler for every other text	
@bot.message_handler(func=lambda message: True, content_types=['text'])
def command_default(m):
	bot.send_message(m.chat.id, "I don't understand \""+m.text+"\"\nMaybe try the help page at /help") #this is the standard reply to a normal message
```

All other of my message handlers seem to work fine
