### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by MonsterDeveloper** [eternnoir/pyTelegramBotAPI#300]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Latest

2. What OS are you using? Ubuntu 16.04

3. What version of python are you using? Python 3.5
I have this error:

![screenshot_2017-03-03-08-30-45-154_com sonelli juicessh](https://cloud.githubusercontent.com/assets/16190582/23543323/b9746716-0002-11e7-98a4-815fbd44f37c.png)

It happens like HTTPSConnectionPool. Bot working OK but suddenly this happens just like httpsconnectionpool.

**Comment by MonsterDeveloper** [comment]
Error was in another library. Sorry.

**Comment by SergeiMinaev** [comment]
> Error was in another library. Sorry.
In which one? I got same error
