### ISSUE TITLE
50mb limit?

### ISSUE THREAD

**Issue by hannibal1986** [eternnoir/pyTelegramBotAPI#302]
Some way to send / download files of more than 50mb? Thank you

**Comment by MonsterDeveloper** [comment]
I think there is no way to do this😢 Telegram won't allow you. Or you can upload files to Google Drive or Dropbox and send links to users.

**Comment by hannibal1986** [comment]
Ok thnks, this api --> pwrtelegram.xyz up to 1,5gb

**Comment by MonsterDeveloper** [comment]
maybe:)
