### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by MonsterDeveloper** [eternnoir/pyTelegramBotAPI#304]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Latest

2. What OS are you using? Ubuntu 16.04, Google Compute Engine

3. What version of python are you using? Python 3.5.2

This error sometimes happens when I edit message's text
 http://pastebin.com/0AbCxYZ1

**Comment by mhvuze** [comment]
This same error occurs for sendMessage on my end (Raspian on Raspberry Pi). Not always but regularly.

**Comment by s3c** [comment]
Any chance this is because of a rate limit?
