### ISSUE TITLE
no get updates

### ISSUE THREAD

**Issue by hannibal1986** [eternnoir/pyTelegramBotAPI#307]
A few days ago with this function I read the updates correctly, now only shows me this without making any changes:
{"Ok": true, "result": []}

Python:
url = "https://api.telegram.org/botTOKEN/getUpdates"
f = urllib2.urlopen(url)
myfile = f.read()
bot.send_message(m.chat.id, myfile)

any idea? thnks

*With the link in the browser sometimes shows result and sometimes not

**Comment by MonsterDeveloper** [comment]
If it is in browser, its definitely Telegram issue. Write to Telegram Support.
