### ISSUE TITLE
AttributeError: Message instance has no attribute 'update_id'

### ISSUE THREAD

**Issue by amk5** [eternnoir/pyTelegramBotAPI#310]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2.3.1

2. What OS are you using?

Windows

3. What version of python are you using?

Python 3.4.3

Hi,

I deployed my "Hi" bot on Heroku and I'm getting this error message : 

`2017-03-15T16:30:11.448526+00:00 app[web.1]:   File "/app/hi.py", line 22, in getMessage

2017-03-15T16:30:11.448526+00:00 app[web.1]:     [telebot.types.Update.de_json(request.stream.read().decode("utf-8")).message])

2017-03-15T16:30:11.448527+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/telebot/__init__.py", line 148, in process_new_updates

2017-03-15T16:30:11.448528+00:00 app[web.1]:     if update.update_id > self.last_update_id:

2017-03-15T16:30:11.448528+00:00 app[web.1]: AttributeError: Message instance has no attribute 'update_id'`

Here's my full code : 

`from flask import Flask, request
import telebot
import os
from socket import *

app = Flask(__name__)
TOKEN = ''
bot = telebot.TeleBot(TOKEN)
port = int(os.environ.get("PORT", 5000))

@bot.message_handler(content_types=['start'])
def start(message):
    bot.send_message(message.chat.id, 'Hi')

@bot.message_handler(func=lambda message: True, content_types=['text'])
def echo_message(message):
    bot.reply_to(message, message.text)

@app.route("/bot", methods=['POST'])
def getMessage():
    bot.process_new_updates([telebot.types.Update.de_json(request.stream.read().decode("utf-8")).message])
    return "!", 200

@app.route('/')
def webhook():
    bot.remove_webhook()
    bot.set_webhook(url="https://.herokuapp.com/bot")
    return "!", 200

sock = socket()
sock.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=port, debug=True)
`
Can someone point me the way please.

Cheers.

**Comment by MonsterDeveloper** [comment]
Try to use [this](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/webhook_examples/webhook_flask_echo_bot.py) example.

**Comment by amk5** [comment]
Do I have to setup a SLL certificate with Heroku ?

**Comment by MonsterDeveloper** [comment]
You have Heroku hosting?
