### ISSUE TITLE
send a picture with command line argument

### ISSUE THREAD

**Issue by strike19** [eternnoir/pyTelegramBotAPI#311]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2.3.1
2. What OS are you using?
Raspbian Jessy
3. What version of python are you using?
2.7

Overall I have a more complicated project which will consist of a interface to a telegram bot to control my raspberry pi zero. (system status; Shutdown; reboot; take a picture with cam and send to the bot) (This part is presently quite stable)

Right now I am working on one simple part. I would like to run motion for my surveillance cam. On event the python script shall be called (with the pic as system argument) and the new picture shall be send.
****************
import telebot

TOKEN = 'YourOwnToken'

tb = telebot.TeleBot(TOKEN)	#create a new Telegram Bot object
chat_id = XXXXXXXX #specific ID of the user the foto shall be sent

foto = open('/home/pi/last.jpg', 'rb')
tb.send_photo(chat_id, foto)
******
Sending of the jpg works fine. BUT:
The script can be terminated after sending the file. (exit() / quit did not the job. 
btw: if you can give me a hint to send a picture via sysarg...you are more than welcome!

The following error occurs:
Exception in thread WorkerThread2 (most likely raised during interpreter shutdown):Exception in thread WorkerThread1 (most likely raised during interpreter shutdown):

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner

  File "/usr/local/lib/python2.7/dist-packages/telebot/util.py", line 57, in run  File "/usr/local/lib/python2.7/dist-packages/telebot/util.py", line 57, in run

<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

**Comment by eternnoir** [comment]
How about use try/expect to make sure the problem is from send_photo?

```
try:
   foto = open('/home/pi/last.jpg', 'rb')
   tb.send_photo(chat_id, foto)
except Exception as e:
   print(e)
```

**Comment by strike19** [comment]
OK. That means that python is not usable for this part of the project. Thanks for help.
