### ISSUE TITLE
get webhook info exception

### ISSUE THREAD

**Issue by globax89** [eternnoir/pyTelegramBotAPI#314]
Please answer these questions before submitting your issue. Thanks!

    What version of pyTelegramBotAPI are you using?

pyTelegramBotAPI==2.3.1

    What OS are you using?

Linux 3.10.0-514.6.1.el7.x86_64 x86_64 GNU/Linux

    What version of python are you using?

Python 3.5.2

Good time, want to use the method get_webhook_info(), but to get the exception:

  File "/usr/local/lib/python3.5/site-packages/telebot/types.py", line 151, in de_json
    return cls(url, has_custom_certificate, pending_update_count, last_error_date, last_error_message, max_connections, allowed_updates)
UnboundLocalError: local variable 'allowed_updates' referenced before assignment

As far as I understand, the problem is that allowed_updates and max_connection variables not initialized with a value of None.

**Comment by kostyakoz** [comment]
Same bug when updated to 2.3.1

**Comment by Deathik** [comment]
pyTelegramBotAPI 3.0.0
Windows 10
Python 3.5.2
Bug is still alive
