### ISSUE TITLE
register_next_step_handler question

### ISSUE THREAD

**Issue by MonsterDeveloper** [eternnoir/pyTelegramBotAPI#315]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Latest

2. What OS are you using? Ubuntu 16.04

3. What version of python are you using? Python 3.5
Hello. There is an error in `register_next_step_handler`: when new message comes, callback function is called. Its okey. But it processes like regular message, too. Look: I have handler for text and then check if message.text == "/start" and etc. An if it doesn't match any command it send unknown command message. So when user sends message after register_next_step_handler, it send message from callback function and FROM HANDLER! I want to just call callback function and not to go on message handler.

**Comment by mhb8898** [comment]
same problem for me!
is there any solution?
i have to use a lot of if and condition to handle this problem and i think there should be a better implementation.

**Comment by 7633** [comment]
Guys, have you find any solution?

**Comment by 0xVK** [comment]
mhb8898, which conditions do you use?
