### ISSUE TITLE
logging 2 bots into 2 different files is not working

### ISSUE THREAD

**Issue by Yolley** [eternnoir/pyTelegramBotAPI#316]
I have two bots, which are working via webhooks with router on flask, so my structure is:

- app.py - router
- bot1.py
- bot2.py

Router imports bot1 and bot2 and then run the needed bot.

In both bots i configured logging like this:
```
handler = RotatingFileHandler('BOT_NAME.log', maxBytes=18000, backupCount=7) # instead of "BOT_NAME" i write the name of the bot
logging.getLogger("TeleBot").setLevel(logging.DEBUG)
logging.getLogger("TeleBot").addHandler(handler)
```

The problem is, that all debug messages from bots goes to both log files, but i need every bot to write debug messages to its own log file. I tried to configure logging with something like this:
```

logging.getLogger("TeleBot.BOT_NAME").setLevel(logging.DEBUG)
logging.getLogger("TeleBot.BOT_NAME").addHandler(handler)
```

But with this code bots don't write debug messages at all.

Is this a bug? Is there a way to configure separated logs for bots?

**Comment by pevdh** [comment]
I see your problem. At the moment this is not possible, since the logger is shared across the library by different files, and configuring a logger per bot instance would complicate matters.

I see your issue, however, at the moment there is no viable solution.
