### ISSUE TITLE
Using pyTelegramBotAPI with Django

### ISSUE THREAD

**Issue by furang** [eternnoir/pyTelegramBotAPI#320]
1.  pyTelegramBotAPI 2.3.1
2. Raspbian
3. python 2.7.9

Hello! Thanks for your great job. That's really awesome. I'd like to know is it possible to use your lib with Django (as a webhook server)? Could you please provide an example?

**Comment by eternnoir** [comment]
Yes, you can. 
Check flask's example. Django should be like this.

https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/webhook_examples/webhook_flask_echo_bot.py#L48
