### ISSUE TITLE
AsyncTeleBot vs NextStepHandler

### ISSUE THREAD

**Issue by Olegt0rr** [eternnoir/pyTelegramBotAPI#322]
NextStepHandler doesn't working with AsyncTeleBot

`  File "/telebot/__init__.py", line 685, in register_next_step_handler
chat_id = message.chat.id
AttributeError: 'AsyncTask' object has no attribute 'chat'`

1. What version of pyTelegramBotAPI are you using?
2.3.1

2. What OS are you using?
MacOS

3. What version of python are you using?
3.6

**Comment by Olegt0rr** [comment]
@pevdh can you help?

**Comment by eternnoir** [comment]
Can you paste some example?

**Comment by Istreb** [comment]
@Olegt0rr, are you using AsyncTeleBot?
`bot = telebot.AsyncTeleBot(...`
mb switching to simple Telebot would help

**Comment by almazkayum** [comment]
same question. listening.
why no answers and unresolved issue?
