### ISSUE TITLE
types and util are unresolved references 

### ISSUE THREAD

**Issue by rudskoy** [eternnoir/pyTelegramBotAPI#323]
Hi. I've installed it from pip recently (pip install telebot).

When I use: 

`import telebot`
`from telebot import types`
`from telebot import util`

types and util are marked as 'Unresolved reference', I don't know what I'm doing wrong. Could you help me? 

Result from python console: `ImportError: No module named types`
Python 2.7
The latest telebot from api 
macOS

**Comment by Olegt0rr** [comment]
@rudskoy, 
```
pip uninstall telebot
pip install pytelegrambotapi
```

**Comment by rudskoy** [comment]
Thank you

...dammit

**Comment by axtrace** [comment]
I done this on Ubuntu

> pip uninstall telebot
> pip install pytelegrambotapi

get: AttributeError: module 'telebot' has no attribute 'TeleBot'
