### ISSUE TITLE
i use the last version of pyTelegramBotAPI, Windows 10 and my python is 3.6 version. How can I make a bold font? 

### ISSUE THREAD

**Issue by tokelau** [eternnoir/pyTelegramBotAPI#327]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2. What OS are you using?

3. What version of python are you using?

**Comment by Kylmakalle** [comment]
Just use `parse_mode` parameter with the correct [text formatting](https://core.telegram.org/bots/api#formatting-options)

For example:
`bot.send_message(chat.id, '*bold text* _italic text_, parse_mode='Markdown')`
And you will get a message: 
**bold text** _italic text_

**Comment by tokelau** [comment]
Thanks)

**Comment by Kjuyf** [comment]
Thanks it helped me...
