### ISSUE TITLE
undocumented 'deleteMessage' method

### ISSUE THREAD

**Issue by ticoti** [eternnoir/pyTelegramBotAPI#330]
Could this be implemented?
It is not documented but it works
https://api.telegram.org/botTOKEN/deletemessage?chat_id=CID&message_id=MID

**Comment by Kylmakalle** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/325
No comments from @eternnoir for now

**Comment by eternnoir** [comment]
Official document not release this feature now. But I'll accept #325 for now. You can use delete method after #325 merged.
