### ISSUE TITLE
Loop block all

### ISSUE THREAD

**Issue by seby2000** [eternnoir/pyTelegramBotAPI#334]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 2.3.0

2. What OS are you using? windows

3. What version of python are you using? 2.7

```
@bot.message_handler(commands=['start'])
def handle_start_help(message):
	while condition:
               pass
@bot.message_handler(commands=['help'])
def handle_start_help(message):
        chat_id = message.from_user.id
	bot.send_message(chat_id, "ciao")
```

When I click /start starts a loop and until it finishes, all the other commands are unusable both from one chat_id or another. How can i solve it?

**Comment by seby2000** [comment]
any help?

**Comment by eternnoir** [comment]
Because thread block by your loop. Try to create another thread to process your loop.

**Comment by seby2000** [comment]
thank you, added thread and now is working correctly
