### ISSUE TITLE
Telegram api were updateddd

### ISSUE THREAD

**Issue by seby2000** [eternnoir/pyTelegramBotAPI#335]
Telegram api were updated but they are not documented, add support for payments pls

**Comment by Kylmakalle** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/issues/330#issuecomment-301718500

Also payments are disabled for some bots `Bad Request: BOT_PAYMENTS_DISABLED` and should be implemented later.

**Comment by seby2000** [comment]
Il 18/Mag/2017 16:53, "Sergey" <notifications@github.com> ha scritto:

**Comment by seby2000** [comment]
https://core.telegram.org/bots/payments

Il 18/Mag/2017 21:50, "Sebastiano Pignato" <pignato.sebastiano@gmail.com>
ha scritto:

**Comment by Kylmakalle** [comment]
@seby2000 It was released just 30 mins ago

**Comment by seby2000** [comment]
I know i know, could u help me with #334 issue?

Il 18/Mag/2017 22:49, "Sergey" <notifications@github.com> ha scritto:
