### ISSUE TITLE
My bot is suddenly stoping

### ISSUE THREAD

**Issue by GabrielRF** [eternnoir/pyTelegramBotAPI#34]
I'm getting this several times a day:
```
TeleBot: Exception occurred. Stopping.
getUpdates failed. Returned result: <Response [502]>
TeleBot: Stopped polling.
```
Knowing that '*The 502 Bad Gateway error is an HTTP status code that means that one server received an invalid response from another server*', I believe it is an error on Telegram's server, not on the API. 

So I would be happy if someone could give me an suggestion on how to treat this and make my bot automatically begin to work again.

**Comment by Kondra007** [comment]
I think that's because of DDoS on Telegram Servers.
Suffering from this problem for 48 hours now.

**Comment by GabrielRF** [comment]
@Kondra007 I agree to that. The time it began to happen is the same as the DDoS. 
So I'm looking for a way to make my bot come back to life automatically.
For now, I'm reseting everything, one by one, and starting them back again.

**Comment by Kondra007** [comment]
If you can get SSL Certificate, you can start using webhooks instead of getUpdates(). Maybe this can solve the problem.
Or you can try writing some Python or Shell script, which finds PIDs of scripts, kills them and starts again every 2 hours.

**Comment by GabrielRF** [comment]
I'll try to make a script to reset everything..

I guess I have a solution for #33. Take a look. :)

**Comment by Kondra007** [comment]
@GabrielRF that solution worked, thank you!

**Comment by eternnoir** [comment]
@GabrielRF 
In this DDOS attack , I also found this problem. In this commit 4a3e989 , I try to add a flag let telebot do not stop when Exception occurs.

**Comment by GabrielRF** [comment]
@eternnoir 
Very good! Any idea when it will be available on master branch?

**Comment by eternnoir** [comment]
@GabrielRF It's available on master branch and pip now.

**Comment by GabrielRF** [comment]
Thanks!

**Comment by GabrielRF** [comment]
Is it working for you all? My bot is still stopping.

**Comment by eternnoir** [comment]
It works fine for me.Don't forget add True param.
```python
tb = telebot.TeleBot(TOKEN)
tb.set_update_listener(listener) #register listener
tb.polling(True)
```

**Comment by GabrielRF** [comment]
Well observed. I'll check that.

**Comment by Kondra007** [comment]
@GabrielRF How do you start your bots? Via `nohup`? 
I'm on VDS now and starting bots from non-root leads to their stopping.

To find out whether it's Telegram problem or it's bug in your code, could you start your bots in separate virtual terminals? (using `screen` utility):
1. `sudo apt-get install screen` (in Ubuntu)
2. `screen -S mybot` (create virtual terminal with 555.mybot ID, where 555 is given Process ID (autogenerated))
3. `./bot.py` or `python3.4 bot.py` (starts the bot)
4. Ctrl+A, then Ctrl+D (detaches from that terminal, you should see previous command prompt, hovewer, your bot is still working in foreground)

When you stop recieving messages from your bot, do the following:
1. `screen -list` will show you created virtual terminals.
2. Find the one that has `mybot` in its name (f.ex. `32200.mybot`)
3. Type `screen -r 32200.mybot` to switch to that terminal.
There you should see any exceptions or errors occured and find out the reason.

P.S. Of course, one can just do `nohup ./mybot.py &` and then look through `nohup.out` file for errors, but `screen` variant somehow works better for me (placebo?)

**Comment by GabrielRF** [comment]
It depends. When I want to leave it running, I simply type ```/python bot.py &```
I have set on my bots an option to log everything, so I have and output to read what is happening.

Whenever I want to catch the outputs, I use byobu. It's similar to screen, but I prefer it.
That's how I found that the error was on the Telegram servers and not on the API.
Thanks for the tip anyway.

**Comment by GabrielRF** [comment]
@Kondra007 
I have left my bots running overnight on BYOBU.
It keeps getting the same errors etc, but the difference is that they didn't stop! Even though I caught a lot of ```getUpdates failed. Returned result: <Response [502]>```
I can't tell the difference of letting them running on BYOBU and let them simply running on the background using a ```python bot.py &```.
The thing is that it seems to the more stable this way. Maybe your *placebo effect* is working on me too.

**Comment by pyed** [comment]
I got the same exception multiple times

I leave it running for a day or two and I will get this exception eventually, I'm running it via `tmux`

```
TeleBot: Exception occurred. Stopping.
getUpdates failed. Returned result: <Response [502]>
TeleBot: Stopped polling.
```

then I have to run it again, my bot is very simple so it's not a bug with my code, it gotta be something else

**Comment by Kondra007** [comment]
Even with 'none_stop=true' it sometimes stops

**Comment by GabrielRF** [comment]
My bots are running for three days without any interrupting (using Byobu), though the error ```getUpdates failed. Returned result: <Response [502]>``` is still happening.

Only one of them stops sometimes, when the user whose id is ```-29786609``` sends a lot of messages in less then a minute. I've just implemented a simple filter for him. I'll keep checking to see if it's enough.

**Comment by Kondra007** [comment]
-xxx means group chat, btw

**Comment by Kondra007** [comment]
And yes, two of three bots are running fine, except one that is stopping for any reason. But this can also be my fault

**Comment by GabrielRF** [comment]
I didn't know -xxx means group, what makes it weirder as the bot is not allowed on groups.

**Comment by analca3** [comment]
My two bots are stopped since yesterday although they don't have received any messages... I'll try screen placebo method.

**Comment by eternnoir** [comment]
@analca3 also use python3? maybe it can be fixed in 0.2.7 60a7595b723

**Comment by analca3** [comment]
Yes, I'm using python3 :)

**Comment by analca3** [comment]
It's fixed! Now it can get exception but not stop polling :)
