### ISSUE TITLE
Python3   "module 'telebot' has no attribute 'TeleBot'"

### ISSUE THREAD

**Issue by Witalika** [eternnoir/pyTelegramBotAPI#341]
1. version of pyTelegramBotAPI is 2.3.2
2. OS is Ubuntu 16.04 LTS 64
3. Python version 3.5.2 
 Hi, i got the problem, trying to launch the first example. My code is:
> import telebot
> TOKEN="3156... etc"
> bot = telebot.TeleBot(TOKEN)
> @bot.message_handler(commands=['start', 'help'])
> def send_welcome(message):
>     bot.reply_to(message, "Howdy, how are you doing?")
> @bot.message_handler(func=lambda message: True)
> def echo_all(message):
>     bot.reply_to(message, message.text)
> bot.polling()

the terminal :
> > bot = telebot.TeleBot(TOKEN)	
> > AttributeError: module 'telebot' has no attribute 'TeleBot'

**Comment by Witalika** [comment]
Also I saw the issue here:
https://github.com/eternnoir/pyTelegramBotAPI/issues/274
It didn`t help

**Comment by MasterGroosha** [comment]
How did you install the module?

**Comment by Witalika** [comment]
I installed it, using the pip command, as in the guide... 
saw your comment and decided to reinstall it the other way, by "git clone" . it is still not working. 
interesting, but when there was no library installed at all, console showed the same result. consequently the problem should be somewhere with python or linux. So i upgraded python with "sudo apt-get upgrade python3"... in vain. maybe I should read something?

**Comment by MasterGroosha** [comment]
1. Install `pip` (if you don't have it): `wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py`
2. `pip3 install pytelegrambotapi`

After that you should be fine.

**Comment by Witalika** [comment]
pip was installed before with
sudo apt install python-pip
and removed with
python -m pip uninstall pip setuptools
Made all steps, but nothing.  
Should mention, that it worked only with "sudo" and "wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py" had to be separate in "wget https://bootstrap.pypa.io/get-pip.py " and "python3 get-pip.py" . perhaps it has some impact

**Comment by trevorgentry** [comment]
I am having the same issue. Running Python 3.6.4 (64-bit) on Windows 7.

**Comment by Retul15** [comment]
I have been trying to use this API for a year but still there is no solution to fix this error. I think it is a spam repository.

**Comment by Equecevi** [comment]
Im also having this issue in ubuntu 18.04 lts

**Comment by Equecevi** [comment]
> Im also having this issue in ubuntu 18.04 lts

Hi people, the problem I had was about the virtual enviroments, so look that good because it can possibly be a problem of the package installation

**Comment by abdullah20401** [comment]
I have Windows 7 32 bit and I have the same problem.
`    @bot.message_handler(commands=['start', 'help'])
AttributeError: 'TeleBot' object has no attribute 'message_handler'`

**Comment by Guatama** [comment]
The same problem on Windows 10. Python 3.7.1

**Comment by HooZz** [comment]
Hi! I had the issue and in my case there was a name conflict - I named the test file as telebot.py So, "import telebot" statement was importing the file itself and not the module I needed. After the filename change code started to work.

**Comment by Guatama** [comment]
OMG! I was so blind... "has no attribute 'Tele**b**ot'... but has 'Tele**B**ot'

**Comment by AlexPetul** [comment]
> OMG! I was so blind... "has no attribute 'Tele**b**ot'... but has 'Tele**B**ot'

Same problem omg

**Comment by Falcon-Peregrine** [comment]
I fixed this with 'TeleBot' instead of Telebot

**Comment by rOOtsystem2010** [comment]
The same problem on Windows 10. Python 3.7.1

**Comment by Badiboy** [comment]
I suppos you installed telebot

> pip install telebot

instead of pyTelegramBotAPI

> pip install pyTelegramBotAPI

**Comment by kolbak** [comment]
I fixed this problem by reinstall package pyTelegramBotAPI in my project

**Comment by pvgdevelop** [comment]
I had the similar issue, except it was  ```AttributeError: module 'telebot' has no attribute 'AsyncTeleBot'```
And this was happening in `Debian 10`
On my local machine `Mac OS 11.4` everything worked fine right away.


pip suggests you use ```python -m pip install --user <package>```
it also give the link on issue wth better explanation [5599](https://github.com/pypa/pip/issues/5599)

This helped helped me
```python -m pip install --user -U pyTelegramBotAPI```

**Note**, that running the same, but with `-r requirements` did NOT work.

Hope this will be useful to  someone.

**Comment by n3b0** [comment]
> I fixed this with 'TeleBot' instead of Telebot

Same!

**Comment by coder2020official** [comment]
be careful with names

**Comment by allanfernds** [comment]
pip3 uninstall telebot
sudo pip3 install pyTelegramBotAPI

**Comment by Lil-Homer** [comment]
> 1. Install `pip` (if you don't have it): `wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py`
> 
>     2. `pip3 install pytelegrambotapi`
> 
> 
> After that you should be fine.

In Debian it worked perfectly. Thank you very much!! 😄

**Comment by CoopCodes** [comment]
> I had the similar issue, except it was `AttributeError: module 'telebot' has no attribute 'AsyncTeleBot'` And this was happening in `Debian 10` On my local machine `Mac OS 11.4` everything worked fine right away.
> 
> pip suggests you use `python -m pip install --user <package>` it also give the link on issue wth better explanation [5599](https://github.com/pypa/pip/issues/5599)
> 
> This helped helped me `python -m pip install --user -U pyTelegramBotAPI`
> 
> **Note**, that running the same, but with `-r requirements` did NOT work.
> 
> Hope this will be useful to someone.

Thanks so much! this helped
