### ISSUE TITLE
Bot is not receiving audio messages

### ISSUE THREAD

**Issue by ticoti** [eternnoir/pyTelegramBotAPI#344]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
version='2.3.2'
2. What OS are you using?
ubuntu
3. What version of python are you using?
python 2.7

Bot is not receiving audio messages, it receives documents, stickers and all types but not audios

**Comment by amirmaaref** [comment]
I Have this problem so with python 3.7
Please Help me!

**Comment by Badiboy** [comment]
"voice" and "audio" are different message types. Voice messages are "voice", music files are "audio" (may be).
