### ISSUE TITLE
Example of payments

### ISSUE THREAD

**Issue by alfilesnet** [eternnoir/pyTelegramBotAPI#345]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
2.3.2
2. What OS are you using?
Ubuntu 16.0.4 LTE
3. What version of python are you using?
3.5.2

Could you give a complete example of a payment?
Thanks

**Comment by Kylmakalle** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/346
