### ISSUE TITLE
Is it possible to send files via ID, not via files itself with your API?

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#35]
Hello! 
How can I use your API to send files using their file_ids, without uploading them every time? 
This is VERY convenient when using bot as storage

For now I'm using custom function, but it would be more convenient to use your awesome API.

**Comment by eternnoir** [comment]
Done. check master branch.

**Comment by Kondra007** [comment]
Thank you! I'll check it later.
