### ISSUE TITLE
Example to create a message to telegra.ph

### ISSUE THREAD

**Issue by alfilesnet** [eternnoir/pyTelegramBotAPI#353]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.0.1
2. What OS are you using?
Ubuntu 16.0.4 LTE
3. What version of python are you using?
3.5.2

Could you make an example to create a message to telegra.ph and edit its content?
Thank you.

**Comment by Kylmakalle** [comment]
It's **really not** a telebot issue, if you will google a bit, you will find:
- https://github.com/mercuree/html-telegraph-poster
- https://github.com/python273/telegraph
- https://github.com/Kylmakalle/TelegraPyBot

**Comment by alfilesnet** [comment]
Thanks
