### ISSUE TITLE
aiohttp example - telebot is using blocking module (requests)

### ISSUE THREAD

**Issue by intra-au** [eternnoir/pyTelegramBotAPI#354]
asyncio compatibility / aiohttp issue
Telebot is using requests module which blocks entire script during requests calls.
To resolve this telebot would need to use asynchronous aiohttp ClientSession module instead of requests.
short example:

async with aiohttp.ClientSession() as session:
    async with session.get('https://api.github.com/events') as resp:
      print(resp.status)
        print(await resp.text())

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
latest
2. What OS are you using?
ubuntu
3. What version of python are you using?
3.5

**Comment by intra-au** [comment]
another comment is usage of threads defeat the purpose of async framework and running aiohttp as a low level server can allow to use ``loop.ensure_future(bot.process_new_updates([update]))`` to run function as a "thread" in terms of asyncio framework...

I'm not sure what is the best the way to approach resolution, but I guess it may require completely new async version where each function is declared as async and called with await + replace requests module with aiohttp.ClientSession get/post functions...

**Comment by intra-au** [comment]
I've modified current version to be compliant with asyncio so I can use it in my project, it works awesome with python3.5, sanic as a server, aiohttp client instead of requests and it's working in webhook mode.
Of course it's completely broken for everything else including polling mode (which I didn't modify) and not compliant with Python 2.
Please let me know If anyone can benefit from my version and I'm happy share it.

**Comment by eternnoir** [comment]
Hi @intra-au,
I am very interested in let this project compliant  with aiohttp. If you want to share your result it will be 
very helpful.

**Comment by intra-au** [comment]
Hi @eternnoir please check your gmail!
Please let me know if this project will implement any of my modifications.

**Comment by desprit** [comment]
Any news guys? Would love to see Telebot working inside my aiohttp environment.
