### ISSUE TITLE
WebHook AWS Lambda

### ISSUE THREAD

**Issue by Mirio** [eternnoir/pyTelegramBotAPI#356]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.0.1

2. What OS are you using? No OS, Lambda on AWS

3. What version of python are you using? 2.7

Code:
```
import os
import sys
import json
import logging
from config import tgram_token
from time import sleep

# Fix lambda dep
sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)),
                             "./lib"))

import telebot

logger = telebot.logger
bot = telebot.TeleBot(tgram_token, threaded=False)
telebot.logger.setLevel(logging.DEBUG)

def lambda_handler(event, context):
    ''' Lambda Handler (webhook via api gateway) '''
    update = telebot.types.Update.de_json(event)
    bot.process_new_updates([update])
    return ""

@bot.message_handler(commands=['help', 'start'])
def start_helper(message):
    ''' Helper for first command '''
    bot.reply_to(message,("Test Start"))
```
Telegram ---[Webhook]---> Aws Api Gateway --> Aws Lambda

Issue: The message are processed but not deleted, every run of lambda the message are resend.

How i can fix that?

**Comment by Mirio** [comment]
Ok is not an issue, the problem is the config of api gateway, it need to be return status code => 200 to the telegram server for clean the queue.

**Comment by Amar1729** [comment]
Sorry to comment on a dead issue -

As of (at least) today, the `event` passed down by AWS has many fields that seem to be AWS-specific, and one `body` field where the content given by the Telegram API resides as a string. So instead of

```python
update = telebot.types.Update.de_json(event)
```

you'll want to do:
```python
update = telebot.types.Update.de_json(event["body"])
```

Had me debugging for a while today.
