### ISSUE TITLE
webHooks using webapp2?

### ISSUE THREAD

**Issue by desmonduz** [eternnoir/pyTelegramBotAPI#36]
I am using pyTelegramBotAPI wrapper and I really like the way how it handles commands and messages through decorator mechanism. I like it so much so I don't want to switch to any other wrapper. However its infinite polling loop sometimes causing network related problems. I have made my own local customisations to retry the polling attempt in case of failure, but it would be awesome if we could extend this wrapper for webHooks as well. We could use webapp2 as a framework for endpoints.
In this way, instead of infinitely polling for updates, the web application would respond to callbacks immediately. Any ideas?

**Comment by Kondra007** [comment]
Could I ask one question? Where're you going to buy/get SSL certificate? (needed for using webhooks)

**Comment by YBinnenweg** [comment]
@Kondra007 You could use a self-signed certificate. A service called [Let's Encrypt](https://letsencrypt.org/) is also coming reasonably soon, which aims to provide free SSL certificates, that are officially signed, to everyone, for free.

**Comment by Kondra007** [comment]
But API page (https://core.telegram.org/bots/api#setwebhook)
says that they do not support self-signed certificates...

**Comment by YBinnenweg** [comment]
@Kondra007 Ah, whoops! I wasn't aware of that! :)

**Comment by desmonduz** [comment]
If you host on cloud, for ex, Google App engine, the SSL certificate is already provided. But SSL certificate of your own is not very expensive, and an easy procedure of application. You can have one in GoDaddy for example: https://uk.godaddy.com/ssl/ssl-certificates.aspx

**Comment by eternnoir** [comment]
@desmonduz At this stage telebot not design message receiver for webhook, I'll plan to design some method let webhook can easy passing new message to telebot without modify existing message_handling and listener. 

For now, you can use type.message.de_json(json) method to transform json string to message object list, when webhook receive json. Then you can call telebot obj's private method `__notify_update(new_messages)` and `_notify_command_handlers(new_messages)` let listener and message_handler process your new messages.

Of course this is not a good way. Maybe can create a public method named `process_new_message(new_messages)` let webhook can passing message objects.

**Comment by desmonduz** [comment]
@eternnoir It seems an absolutely perfect solution to me to handle my webhook callbacks. Thanks.

**Comment by eternnoir** [comment]
Done. check master branch.
