### ISSUE TITLE
bot.skip_pending=True in WebHook?

### ISSUE THREAD

**Issue by alfilesnet** [eternnoir/pyTelegramBotAPI#363]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.0.1
2. What OS are you using?
Ubuntu 16.0.4 LTE
3. What version of python are you using?
3.5.2

I have been using polling until now, although today I have decided to use webhook (aiohttp), but I see that when I put some command on the bot and then run .py, the commands written before the bot is started.

How can I have the same result as 'bot.skip_pending = True' in webhook?

Thank you

**Comment by MasterGroosha** [comment]
You don't need this while using webhooks.
