### ISSUE TITLE
Support for botapi 3.1

### ISSUE THREAD

**Issue by StrangePers** [eternnoir/pyTelegramBotAPI#366]
Do you plan to update code to support 3.1?

**Comment by MasterGroosha** [comment]
Please, check [this branch](https://github.com/MasterGroosha/pyTelegramBotAPI/tree/botapi_v3.1), I think it has all 3.1 features.

**Comment by alfilesnet** [comment]
When will we upgrade our pyTelegramBot using pip?
Thanks

**Comment by MasterGroosha** [comment]
I think this issue can be closed. 3.1 is implemented.
