### ISSUE TITLE
Support for Bot API v3.2

### ISSUE THREAD

**Issue by MasterGroosha** [eternnoir/pyTelegramBotAPI#375]
Bot API got 3.2 update with new methods for stickers/masks: https://core.telegram.org/bots/api#setstickerpositioninset

**Comment by eternnoir** [comment]
[ ] sendSticker
[ ] getStickerSet
[ ] uploadStickerFile
[ ] createNewStickerSet
[ ] addStickerToSet
[ ] setStickerPositionInSet
[ ] deleteStickerFromSet
