### ISSUE TITLE
How to add a string to file name when sending file?

### ISSUE THREAD

**Issue by AliBahaari** [eternnoir/pyTelegramBotAPI#378]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.10 - I think, Because Installed By PIP

2. What OS are you using? GNU/Linux - Ubuntu 16.04

3. What version of python are you using? 3

Hello, First thanks for your implementation ... I have a question, Is it possible to add a string to file name we send to user ? For example my file name is "Biology.pdf", So I want to add a channel name like " - @Test" to the end of it to be "Biology.pdf - @Test". I know I can add caption but I need this too.

**Comment by Kylmakalle** [comment]
It's not TeleBot issue
https://docs.python.org/3/library/os.html#os.rename

**Comment by AliBahaari** [comment]
I know it is not, But It is very good if TeleBot that has many advantages have this ability too, Because some frameworks like TeleBot has this ability to not to use os.rename ...

**Comment by Kylmakalle** [comment]
Adding text to the end of file will mess up file extention

Are you sure that you'r talking not about [Caption](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/__init__.py#L509)?

**Comment by alfilesnet** [comment]
you can use:

filename='Biology.pdf'
extension=filename[-4:]
string=' - @mychannel'
filename=filename[0:-4]+string+extension

-> Biology - @mychannel.pdf

**Comment by AliBahaari** [comment]
@Kylmakalle I'm sure, Please check python-telegram-bot ...

**Comment by AliBahaari** [comment]
@alfilesnet Thanks, I will check it ...

**Comment by Ratgor** [comment]
I think the problem is in hardcoded filename 'document' 
see commit 151880f, line 688 in
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/__init__.py
