### ISSUE TITLE
Set user specified timeout for polling?

### ISSUE THREAD

**Issue by nasfarley88** [eternnoir/pyTelegramBotAPI#38]
With `bot.polling()`, currently the bot polls as many times as it likes. Since I don't need an instant response it would be good to be able to optionally limit the loop to only cycle every `x` seconds (e.g. `bot.polling(1)`).

**Comment by eternnoir** [comment]
Do you mean Interval? Polling will sleep a small time before next request?

**Comment by nasfarley88** [comment]
Yes, that's right.

**Comment by eternnoir** [comment]
Done, check master branch.

**Comment by pevdh** [comment]
TeleBot performs long-polling (with a timeout of 20 secs) by default, so there is no need for a customised interval.

--- Oorspronkelijk bericht ---

Van: "nasfarley88" <notifications@github.com>
Verzonden: 15 juli 2015 03:30
Aan: "eternnoir/pyTelegramBotAPI" <pyTelegramBotAPI@noreply.github.com>
Onderwerp: Re: [pyTelegramBotAPI] Set user specified timeout for polling? (#38)

Yes, that's right.

---
