### ISSUE TITLE
Can't set the audio file title 

### ISSUE THREAD

**Issue by Theodorex** [eternnoir/pyTelegramBotAPI#380]
pyTelegramBotAPI: 3.1.0
OS: Ubuntu 17.10
python version: 2.7.13

I can't set the title of the audio file sent by the bot. Using the example you provided only changes the file description - this little text where is says 'test' (actually I think that's just a separate message, not related to the file):

![image](https://i.imgur.com/Xx6haGB.png)

I tried both using a local file and an external one, but nothing changes.

**Comment by Kylmakalle** [comment]
You are editing caption, but want
https://docs.python.org/2/library/os.html#os.rename

**Comment by Theodorex** [comment]
no, the file name doesn't influence what appears in Telegram. If you look at the file's properties in Linux, in the '_Audio_' tab, it says "_Title: rodrigo22k_". Even though the mp3 itself is named something else.
![image](https://i.imgur.com/PbhGWNL.png)

In the documentation for sending audio files it's written "_## sendAudio with duration, performer and title._". I thought that's the purpose - to edit the name that appears in Telegram when you send the file, isn't it?

**Comment by Kylmakalle** [comment]
`send_audio(chat_id, audio, performer='That cool guy', title='Awesome guitar solo')`

**Comment by Theodorex** [comment]
It doesn't work:
`bot.send_audio("XXXXXX", "external_link", title="Pronunciation", performer="Someone")`

![image](https://i.imgur.com/wJdzQTO.png)

**Comment by Trabel** [comment]
You can't set title and performer when you are sending audio by url, but there would be no problem if you will do the same with  local file
