### ISSUE TITLE
Invalid documentation: new_chat_member vs new_chat_members

### ISSUE THREAD

**Issue by lorien** [eternnoir/pyTelegramBotAPI#393]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.2.0

2. What OS are you using?
Linux Debian

3. What version of python are you using?
Python 3.5

README contains "new_chat_member" in the list of possible event types. It does not work. Only "new_chat_members" (with trailing S) works:
```
    @bot.message_handler(content_types=['new_chat_members'])
    def handle_new_chat_member(msg):
         # todo
```

I think README should be updated.

**Comment by MasterGroosha** [comment]
I guess this issue can be closed since it's fixed in 4a11bb60b457c391658e913922b5615169770604
