### ISSUE TITLE
register_next_step empty message text

### ISSUE THREAD

**Issue by Gooman-rus** [eternnoir/pyTelegramBotAPI#395]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
The latest
2. What OS are you using?
Ubuntu
3. What version of python are you using?
Python 2.7

Hello!
I use register_next_step like this:
```python
bot.register_next_step_handler(msg, lambda m: process_request(m, var1, var2))
```

```python
def process_request(message, var1, var2):
    foo(bot, message, message.text)
```

And sometimes in the function foo() the value of `message.text` turns out to be `None`.
I just see the message in my log file:

`[10.09.2017 20:55:26] bot-utils.py:123 ERROR - ERROR. foo(): message.text is None`

Example of foo function:
```python
def foo(bot, message, text):
    if text is not None
        logging.error("ERROR. foo(): message.text is None")
    #...
```

I really don't know what is it. I can't repeat this, but it appears in log file several times (1-4) per day. Maybe you can help me? Can it be connected with using `lambda m`?
Or perhaps someone wants to break my bot? What do you think?

**Comment by eternnoir** [comment]
Is the next message in that chat room text message? If the message in that chat room which you register is not text message `message.text` will be None.

**Comment by Gooman-rus** [comment]
Indeed. If I send a sticker or file instead of a text message, the `message.text` becomes `None`. So now I can repeat this error. Thank you!
