### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by Malomalsky** [eternnoir/pyTelegramBotAPI#397]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Latest
2. What OS are you using?
Windows 7
3. What version of python are you using?
3.6.2
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot404636181:***************************************/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02E1BDF0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

**Comment by Malomalsky** [comment]
(util.py:64 PollingThread) ERROR - TeleBot: "ConnectionError occurred, args=(MaxRetryError("HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot450819306:********************************/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x02DFCB30>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))",),)
Traceback (most recent call last):

**Comment by alfilesnet** [comment]
I think you're trying to send more than 30 messages per second, then telegram bans you for a few minutes.

you must send less messages per second or sleep them a little.

**Comment by tonys111** [comment]
i also meet this problem.
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot439585328:****************/getMe (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa73fc39850>: Failed to establish a new connection: [Errno 110] Connection timed out',))

i dont know what had happend?

**Comment by Malomalsky** [comment]
It's something like "soft ban". You need to wait sometimes and this problem 
the problem will be solved

**Comment by kovalexis15** [comment]
> It's something like "soft ban". You need to wait sometimes and this problem
> will be solved

I've waited for three years, but it still doesnt't working. I'm already fifteen, and my life is a garbage now, my mates are bullying me. So sad.
