### ISSUE TITLE
Disable keyboard/ wait until new message

### ISSUE THREAD

**Issue by Andermutu** [eternnoir/pyTelegramBotAPI#398]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 2017 September

2. What OS are you using? Ubuntu 16.04

3. What version of python are you using? 2.7.9

Dear Community;

I have a Telegram Python program with this API that simply transforms a Telegram Message into a gmail message.  The problem is that if I send two Telegram message simultaneously the Gmail library cant handle that and it disconnects. So I want to disable the keyboard until the email message is sent or not receive more Telegram messages until the email is sent. If anyone has and idea to solve this I would be very grateful. Thanks in advance!

**Comment by vlad-shev** [comment]
Hello @Andermutu,
I don't know how to disable the keyboard, but maybe it's a good idea to create a queue of your Telegram messages and handle it one by one. As soon email is sent you can take the first message from the queue and handle it by Gmail. I think, this will eliminates the simultaneous  library calls.
