### ISSUE TITLE
Error sending big files

### ISSUE THREAD

**Issue by victor141516** [eternnoir/pyTelegramBotAPI#4]
I'm trying to send big files (20MB is enough) and after some time sending the file, it reaches the point where this error is shown:
>ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botTOKEN/sendDocument?chat_id=8214509 (Caused by <class 'socket.error'>: [Errno 10054] An existing connection was forcibly closed by the remote host.)

**Comment by eternnoir** [comment]
I try upload over 10mb file, telegram api will return 

```
'<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.9.1</center>
</body>
</html>
'
```

**Comment by victor141516** [comment]
But Telegram supports files up to 1,5GB so where is the problem?

**Comment by eternnoir** [comment]
Same problem here https://twitter.com/telegram/status/614836085160587264

Telegram bot api document has updated.
> Bots can send files of any type of up to 50 MB in size.
