### ISSUE TITLE
Send files via file_id fail (0.2.4)

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#40]
```python
file_id = 'My_ID_here'
tb.send_audio(m.chat.id, file_id)
```
fails with the following error (API v0.2.4)
```
    tb.send_audio(m.chat.id, file_id)
  File "/usr/local/lib/python3.4/dist-packages/telebot/__init__.py", line 231, in send_audio
    apihelper.send_data(self.token, chat_id, data, 'audio', reply_to_message_id, reply_markup))
  File "/usr/local/lib/python3.4/dist-packages/telebot/apihelper.py", line 124, in send_data
    if isinstance(data, file):
NameError: name 'file' is not defined
```

**Comment by eternnoir** [comment]
Which python version you use?

**Comment by Kondra007** [comment]
@eternnoir 3.4

**Comment by eternnoir** [comment]
OK, the problem is `isinstance(data, file)` to check object is file. this not work in python3. I will try some other way to fix it.

**Comment by Kondra007** [comment]
@eternnoir I tried opening .docx and .zip files in binary and normal formats. Looks like there're two types for this:
```
<class '_io.BufferedReader'>
<class '_io.TextIOWrapper'>
```
Maybe this could help

**Comment by Kondra007** [comment]
Why don't reverse check if it's a string?

**Comment by eternnoir** [comment]
Check string python2 use `isinstance(s, basestring)` , python3 use `isinstance(s, str)`. It's different too.

**Comment by eternnoir** [comment]
Please try  latest master branch.

**Comment by Kondra007** [comment]
Works fine for me, thank you!
