### ISSUE TITLE
cant download photo or voice

### ISSUE THREAD

**Issue by vocoun** [eternnoir/pyTelegramBotAPI#400]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?    
    Version: 3.2.1    

2. What OS are you using?
    openSUSE Leap 42.3

3. What version of python are you using?
    python3.4

Cant download file. Get an error

> 2017-10-17 00:57:15,704 (util.py:64 WorkerThread2) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 404 Not Found. Response body:\n[<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.9.10</center>\r\n</body>\r\n</html>\r\n]',)
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-packages/telebot/util.py", line 58, in run
>     task(*args, **kwargs)
>   File "main_goz.py", line 217, in handle_input_voice
>     bot.download_file(nf)
>   File "/usr/lib/python3.4/site-packages/telebot/__init__.py", line 355, in download_file
>     return apihelper.download_file(self.token, file_path)
>   File "/usr/lib/python3.4/site-packages/telebot/apihelper.py", line 107, in download_file
>     raise ApiException(msg, 'Download file', result)
> telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 404 Not Found. Response body:
> [<html>
> <head><title>404 Not Found</title></head>
> <body bgcolor="white">
> <center><h1>404 Not Found</h1></center>
> <hr><center>nginx/1.9.10</center>
> </body>
> </html>
> ]
> "
> 2017-10-17 00:57:15,704 (__init__.py:292 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 404 Not Found. Response body:
> [<html>
> <head><title>404 Not Found</title></head>
> <body bgcolor="white">
> <center><h1>404 Not Found</h1></center>
> <hr><center>nginx/1.9.10</center>
> </body>
> </html>
> ]"

and the code (example for voice) is follow:
```
    vc = message.voice                                                              
        if (vc != None):                                                                
            file_id = vc.file_id                                                    
            newFile = bot.get_file(file_id)                                         
            path = some_path
            ds = os.path.exists(path)                                               
            if (ds == False):                                                       
                        os.makedirs(path)                                               
            nf = path + str(message.from_user.username) + '_voice.ogg'                  
            bot.download_file(nf)   
```

**Comment by eternnoir** [comment]
Check this example: https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/download_file_example.py

bot.download_file need file_info's path not server file system path.
