### ISSUE TITLE
handling reopost messages from channels by telegram bot

### ISSUE THREAD

**Issue by justxor** [eternnoir/pyTelegramBotAPI#408]
tell me how to properly handle the repost, which was send to bot from the channel. I'm using telebot for python 3.6 I tried to do something like this:

@bot.message_handler(content_types=['channel_post'])
def handle_docs_photo(channel_post):

    print(channel_post) 

but its not worked

**Comment by MasterGroosha** [comment]
From channel to bot:
```python
@bot.message_handler(func=lambda message: message.forward_from_chat)
def posts_from_channels(message):
    print(message.text)
```
From the [Bot API docs](https://core.telegram.org/bots/api#message), `forward_from_chat` field has information about channel from which the message was forwarded. If the message is not a forward, this handler will not be called.

Please, note, that this handler will only work for **text** messages. To get more types, specify `content_types` array in handler, for example:
`@bot.message_handler(func=lambda message: message.forward_from_chat, content_types=["text", "photo", "video"]`

**Comment by justxor** [comment]
Thanks a lot

**Comment by MasterGroosha** [comment]
If your problem is solved, please suggest closing your issue.

**Comment by ukinti** [comment]
doesn't work :/

**Comment by MasterGroosha** [comment]
More details please?

**Comment by ukinti** [comment]
sure.
I put your code but bot doesn't trigger for any post in my channel(he's
admin there) and doesn't show output.

**Comment by MasterGroosha** [comment]
Of course, since the original question is about **reposts** (forwards) from channels, not channel posts itself.

For posts in channels, please use `@bot.channel_post_handler`

**Comment by ukinti** [comment]
ty then

**Comment by brebiv** [comment]
> From channel to bot:
> 
> ```python
> @bot.message_handler(func=lambda message: message.forward_from_chat)
> def posts_from_channels(message):
>     print(message.text)
> ```
> 
> From the [Bot API docs](https://core.telegram.org/bots/api#message), `forward_from_chat` field has information about channel from which the message was forwarded. If the message is not a forward, this handler will not be called.
> 
> Please, note, that this handler will only work for **text** messages. To get more types, specify `content_types` array in handler, for example:
> `@bot.message_handler(func=lambda message: message.forward_from_chat, content_types=["text", "photo", "video"]`

Thank you.
