### ISSUE TITLE
shipping_query_handler don't work

### ISSUE THREAD

**Issue by emilagam** [eternnoir/pyTelegramBotAPI#415]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.4.1
2. What OS are you using?
Windows 10
3. What version of python are you using?
3.6.1

shipping_query_handler don't work, it dont catch an event

on version 3.2.1 it worked

**Comment by surik00** [comment]
Fixed this in 3.4.2 [in this commit](https://github.com/eternnoir/pyTelegramBotAPI/commit/7ac246b8016efd7e5b616754dc26ff81d9df321b)
Please update the lib and check again

**Comment by emilagam** [comment]
thanks!
