### ISSUE TITLE
GAE support

### ISSUE THREAD

**Issue by apstygo** [eternnoir/pyTelegramBotAPI#421]
My project has been based on Telebot from day one and now, when I ported its storage onto Google Cloud Datastore, I can't go back to a different cloud platform. From what I understand, requests library doesn't work with GAE. My guess is that redefining _make_request method in apihelper.py and using webhook instead of polling may help. What are the possible workarounds?

**Comment by eternnoir** [comment]
Is there more information about this problem? eg. error message.
