### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by orangemio** [eternnoir/pyTelegramBotAPI#422]
0|15       |   File "/data/telegram/test/15.py", line 206, in <module>
0|15       |     bot.polling(none_stop=True)
0|15       |   File "/usr/lib/python2.6/site-packages/telebot/__init__.py", line 264, in polling
0|15       |     self.__threaded_polling(none_stop, interval, timeout)
0|15       |   File "/usr/lib/python2.6/site-packages/telebot/__init__.py", line 288, in __threaded_polling
0|15       |     self.worker_pool.raise_exceptions()
0|15       |   File "/usr/lib/python2.6/site-packages/telebot/util.py", line 107, in raise_exceptions
0|15       |     six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
0|15       |   File "/usr/lib/python2.6/site-packages/telebot/util.py", line 58, in run
0|15       |     task(*args, **kwargs)
0|15       |   File "/data/telegram/test/15.py", line 95, in echo
0|15       |     if (len(dict1[message.chat.id])<3):
0|15       | KeyError: 310365654

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
master
2. What OS are you using?
centos
3. What version of python are you using?
2.7

**Comment by CoconutWaffle** [comment]
There is error in your program, not in this lib (I think), `dict1 ` hasn't key `310365654`.
