### ISSUE TITLE
Bot API 3.5 update with albums feature

### ISSUE THREAD

**Issue by kostyakoz** [eternnoir/pyTelegramBotAPI#424]
Hello! At November 17 Telegram Bot API was updated with support of the albums feature. 

From Telegram Bot API web page:

> November 17, 2017
> Bot API 3.5.
>
> Added the new method sendMediaGroup and two kinds of InputMedia objects to support the new albums feature.
 > Added support for pinning messages in channels. pinChatMessage and unpinChatMessage accept channels.
> Added the new field provider_data to sendInvoice for sharing information about the invoice with the payment provider.

When this update will be available for `pyTelegramBotAPI`?

**Comment by eternnoir** [comment]
Updated on latest release.
