### ISSUE TITLE
[Not a bug][Question] How to get file_id of sent file?

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#43]
Hello! I'm doing my best to optimize bot's traffic and speed.
One of my bots downloads pictures and sends then to multiple recipients. For now, he [bot] sends them as file every time.

I wonder, if it's possible somehow to send file once, find out its file_id so that other people will get this image via file_id?

**Comment by eternnoir** [comment]
send_photo method if success it will return Message object which you sended. You can get photo array in message object.

**Comment by Kondra007** [comment]
Done. Thank you.
