### ISSUE TITLE
message_handler and register_next_step_handler  issue

### ISSUE THREAD

**Issue by manzabvil** [eternnoir/pyTelegramBotAPI#431]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
It works good in 3.2.1, the  problem is in newer versions
2. What OS are you using?
ubuntu 16.04 64-bit
3. What version of python are you using?
2.7

I have this at the beginning

@bot.message_handler(commands=['cancel'])

so that I can go to start step in any moment but if I am in a register_next_step_handler and I hit /cancel it doesnt work, it only works when I hit /cancel again, this happens in 3.4.1 or newer, but works good in 3.2.1

**Comment by 0xVK** [comment]
This behavior has changed. It can help you:
https://github.com/eternnoir/pyTelegramBotAPI/pull/410
https://github.com/eternnoir/pyTelegramBotAPI/issues/405
https://github.com/eternnoir/pyTelegramBotAPI/issues/315
