### ISSUE TITLE
handle photo from forward_message

### ISSUE THREAD

**Issue by justxor** [eternnoir/pyTelegramBotAPI#434]
i am trying to parse message which was sent from channel to bot . My goal is to get photo id from forward message and send photo and text as message(not forward message) to myself. code :

@bot.message_handler(func=lambda message: message.forward_from_chat, content_types=['gif','channel', 'forward_from', 'post', 'sticker', 'forward_from_chat', 'audio', 'photo''])
def posts_from_channels1(message):

    print(message.text)
    print(message.photo)

result -None
[<telebot.types.PhotoSize object at 0x7f1dd81b4cc0>, <telebot.types.PhotoSize object at 0x7f1dd81b4c18>, <telebot.types.PhotoSize object 
at 0x7f1dd81b4b00>, <telebot.types.PhotoSize object at 0x7f1dd81b4550>]

post contains photo and text .i don't see any of this  how to handle this ?

**Comment by eternnoir** [comment]
Try use `message.caption`.
