### ISSUE TITLE
Question. Bot exception handling

### ISSUE THREAD

**Issue by reflash** [eternnoir/pyTelegramBotAPI#436]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.5.1
2. What OS are you using?
macOS 10.13 High Sierra
3. What version of python are you using?
3.6

Is there any way to handle all exceptions occurring during bot request processing?

**Comment by 0xVK** [comment]
Did you try it?
`    try:
        log(m='Bot running..')
        bot.polling(none_stop=True, interval=2)

    except Exception as ex:
        log(m='Error - {}'.format(str(ex)))

        log(m='Restarting..')
        bot.stop_polling()

        time.sleep(15)

        log(m='Running again!')
        bot.polling(none_stop=True, interval=2)`

**Comment by reflash** [comment]
@0xVK This will not work for production environment, I am using polling only for dev

**Comment by eternnoir** [comment]
If use webhook, you can add try expect to your web request handler.
