### ISSUE TITLE
problem in setting webhook on server

### ISSUE THREAD

**Issue by justxor** [eternnoir/pyTelegramBotAPI#438]
i am trying to run telegram bot via webhook. My python and flask version are 3.5. telebot library server -https://www.pythonanywhere.com
my code is :

    from flask import Flask
    import flask
    import telebot
    
    import requests
    import time

    app = Flask(__name__)
    
    API_TOKEN = '***'
    
    bot = telebot.TeleBot(API_TOKEN)

this is for  get my ip :

    res=requests.get('http://ipinfo.io/ip')
    s=str(res.text)
    s=s.split('\n')[0]
    
    WEBHOOK_SSL_CERT = '/home/w/webhook_cert.pem'
    WEBHOOK_SSL_PRIV = '/home/w//webhook_pkey.pem'

    bot.set_webhook(url="https://myacc.pythonanywhere.com", certificate=open('/home/adr/webhook_pkey.pem'))

    WEBHOOK_HOST =s
    #WEBHOOK_HOST = 'https://myacc.pythonanywhere.com/'
    WEBHOOK_PORT = 443
    WEBHOOK_LISTEN = '0.0.0.0'

    WEBHOOK_URL_BASE = "https://{}:{}".format(WEBHOOK_HOST, WEBHOOK_PORT)
    WEBHOOK_URL_PATH = "/%s/" % (API_TOKEN)
    #updates = bot.get_updates()

Process webhook calls

    @app.route(WEBHOOK_URL_PATH, methods=['POST'])
    def webhook():
        if flask.request.headers.get('content-type') == 'application/json':
            json_string = flask.request.get_data().decode('utf-8')
            update = telebot.types.Update.de_json(json_string)
            bot.process_new_updates([update])
            return 'Hello bot'
        else:
            flask.abort(403)

it's not worked and i got no error in log. is there any problem with libary and server or something else ?

**Comment by 0xVK** [comment]
What server does you use?

**Comment by justxor** [comment]
@0xVK https://www.pythonanywhere.com

**Comment by 0xVK** [comment]
I had a similar problem, and solved it in this way:
`bot = telebot.TeleBot(<BOT_TOKEN>, threaded=False)`
Pythonanywhere allows running only one thread, and param threaded=False help to solve it.

**Comment by 0xVK** [comment]
If you use Pythonanywhere, you don't have to create certificates. Becouse host gets you it own certificates.
You can look at my code https://github.com/0xVK/SmartySBot, whick I host at pythonanywhere. and it uses webhooks.

**Comment by justxor** [comment]
@0xVK hi, thanks for help, so what should i use instead certificates wich i create . Where can i get pythonanywhere certificates ?

**Comment by justxor** [comment]
and what is WEBHOOK_PATH ?

**Comment by 0xVK** [comment]
@justxor, you need to write in your code this:
`bot.set_webhook('https://mydomain.pythonanywhere.com/some_secret_url/')`
This url says telegram where to send queries, what people send to your bot.

**Comment by justxor** [comment]
@0xVK i still missing something ,  this is my code  :

```
bot.set_webhook('https://myaccount.pythonanywhere.com/12341',max_connections=1)
   @app.route('/')
def index():
    return 'Main page.'

@app.route('/12341', methods=['POST'] )
def webhook():
    json_string = request.get_data().decode('utf-8')
    update = telebot.types.Update.de_json(json_string)
    bot.process_new_updates([update])

    return "!", 200

```
if i paste this : `bot.send_message(my_id, '111') `
bot sends me message , but it does  not response to my actions /start or any others .
what am i missing ? help me please

**Comment by 0xVK** [comment]
Did you check server error logs?  ("web" tab on pythonahywhere)
And did you debug "update" object? If message exists in it.

**Comment by justxor** [comment]
no errors at all . how could i debug update object ?

**Comment by 0xVK** [comment]
@justxor 
```
@app.route('/12341', methods=['POST'] )
def webhook():
    json_string = request.get_data().decode('utf-8')
    update = telebot.types.Update.de_json(json_string)
    print(update)
    bot.process_new_updates([update])
```
