### ISSUE TITLE
How to get a text from message, if i know him message_id

### ISSUE THREAD

**Issue by Cenzor** [eternnoir/pyTelegramBotAPI#441]
1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI-3.2.1.egg-info

2. What OS are you using?
debian 8.9

3. What version of python are you using?
python3.4

Hello.
1) How can i to get a text from message, if i know him message_id?
2) How can i to know is this  message from user or from bot?

Thank's

**Comment by mostm** [comment]
Hi @Cenzor 
1. There is no way to get message by message_id. Read [Telegram Bot API documentation](https://core.telegram.org/bots/api) first.
2. If you have full `Message` instance, you can get `Message.from_user.is_bot` to check that.

**Comment by WellBenH** [comment]
1) That is wrong... but you can create a special dump channel,  add bot here and forward the message with message_id here, get text from forward and delete the f. msg
