### ISSUE TITLE
How to listen all the incoming messages without running the script every time?

### ISSUE THREAD

**Issue by sumit6192** [eternnoir/pyTelegramBotAPI#446]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2. What OS are you using?

3. What version of python are you using?

**Comment by sumit6192** [comment]
Hi 

1. using  pytelegrambotapi-3.5.1
2. OS- windows 10
3.python 3.6


I think you have made an awesome package.. is there any way to write or store all the incoming messages to the Bot and reply them later..
i am a newbee in Python so please guide me through.


Regards,
Sumit

**Comment by eternnoir** [comment]
Hi,

You need implement message storage (eg. database) to save incoming message. Then get message from storage to reply them.
