### ISSUE TITLE
AttributeError: module 'telebot' has no attribute 'types'

### ISSUE THREAD

**Issue by axtrace** [eternnoir/pyTelegramBotAPI#449]
```
import telebot
tb = telebot.TeleBot(token)
remove_markup = telebot.types.ReplyKeyboardRemove(True)
```

Get:

> Traceback (most recent call last):
>     remove_markup = telebot.types.ReplyKeyboardRemove(True)
> AttributeError: module 'telebot' has no attribute 'types'

Tried to uninstall telebot and install pyTelegramBotAPI (as it was in [323](https://github.com/eternnoir/pyTelegramBotAPI/issues/323)). It did not help. 
What should I do to start correctly?

pyTelegramBotAPI 3.5.1
Ubuntu 16.04
Python 3.5.2

**Comment by heyyyoyy** [comment]
try to create virtualenv and import again

**Comment by axtrace** [comment]
Hm. I'd uninstalled both telebot and pyTelegramBotApi and installed telebot first and pyTelegramBotApi then. And it works well now

` sudo -H pip3 uninstall pytelegrambotapi
sudo -H pip3 uninstall telebot`

`sudo -H pip3 install telebot
sudo -H pip3 install pytelegrambotapi`

**Comment by axtrace** [comment]
oh Mata Hari
It's repeated on my Win 10 computer
