### ISSUE TITLE
one_time_keyboard not working (?)

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#45]
Hello! I've tried both `markup = types.ReplyKeyboardMarkup(one_time_keyboard=True)` and
```
markup = types.ReplyKeyboardMarkup()
markup.one_time_keyboard=True
```
Custom keyboard stays visible forever. The only way now to hide it is to send another message with `ReplyKeyboardHide`

**Comment by eternnoir** [comment]
`Custom keyboard stays visible forever. ` It means custom keyboard's icon?

**Comment by Kondra007** [comment]
Telegram's custom keyboard with custom answers

**Comment by pevdh** [comment]
Is it resolved? What did you do to make it work?

**Comment by Kondra007** [comment]
@pevdh I misunderstood their API documentation.
When one_time_keyboard=True and bot shows you custom keyboard, pressing on any button will hide keyboard, but leave custom keyboard active (square with 4 squares inside)
When one_time_keyboard=False and bot shows you custom keyboard, pressing on any button won't hide keyboard (Think of it as multiple choice)

It you want to completely hide custom keyboard and show "/" button with list of available commands, you have to send any message with ReplyKeyboardHide object.
