### ISSUE TITLE
[document/example request] reply message handling and uploaded file handling

### ISSUE THREAD

**Issue by kmahyyg** [eternnoir/pyTelegramBotAPI#459]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

Latest Version as I opened this issue.

2. What OS are you using?

Unrelated to this problem.

3. What version of python are you using?

3.6

---------------------------------------------

1. I want user to upload a file after some command reply.  (1) If user didn't need to upload files, How should I know whether user upload a file?  (2) If user did upload a file, How should I get it?

just like this:

>  $  /sendmsg
``` this is msg1. please send some text. ```
$ HAHA
(bot got 'HAHA' , then reply)
``` I got some text you just send, send me another text or upload a file.```
$ BLAHBLAH / A FILE
(how should i determine whether user send a file or text? If it was a file, how should I get it?)
(finished)

**Comment by BennyThink** [comment]
`@bot.message_handler(content_types=['text', 'voice'])`
this parameter `content_types` would do that for you.
