### ISSUE TITLE
[Feature Request] Split large messages onto smaller before sending

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#46]
Some bots are intended to send large piles of data (news articles, for example). When sending large texts, you may encounter [HTTP Error 414](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) ("Request URI Too Long")

In this case, I've started using the following function (found on [StackOverflow](http://stackoverflow.com/a/9475354/2032848)):
```python
def string_splitter(line, chars_in_each_line):
    return [line[i:i + chars_in_each_line] for i in range(0, len(line), chars_in_each_line)]
```
It returns an array of chunks, `chars_in_each_line` long each. 
I can't say which number is max supported, but `2000` seems fine.
So, maybe you could add a parameter to `send_message`? (f.ex. `single_message_length`)

**Comment by pevdh** [comment]
Would making a POST instead of a GET request help?

**Comment by Kondra007** [comment]
Probably will, but for large texts could be not enough.

**Comment by pevdh** [comment]
Can you try whether using POST solves this issue? Change in `apihelper.py`, line 59 (in function send_message) from 
`return _make_request(token, method_url, params=payload)`
to
`return _make_request(token, method_url, params=payload, method='post')`

**Comment by Kondra007** [comment]
I can try via requests library myself.
I don't know how to recompile this API after changes and where to edit in system

**Comment by pevdh** [comment]
Can you supply me with a piece of text which fails to be sent?

**Comment by Kondra007** [comment]
I'm at work right now, I'll write to you in an hour or two, ok?

**Comment by Kondra007** [comment]
@pevdh About 6k Cyrillic symbols (normal news article) fail via Eternoir's API
8-9k POST via requests library is OK

**Comment by Sadik** [comment]
having same issue here. What's the status?

**Comment by Kondra007** [comment]
@Sadik you can use function in first post or read commit here - https://github.com/eternnoir/pyTelegramBotAPI/commit/20e3f731f7f3d3ebb2d6cd6fcf1eee5946e8817c
