### ISSUE TITLE
Passing context to register_next_step_handler

### ISSUE THREAD

**Issue by Senpos** [eternnoir/pyTelegramBotAPI#461]
**pyTelegramBotAPI version:** 3.5.2
**OS:** Ubuntu 16.04 (_KDE neon user edition_)
**Python version:** 3.6.3

I am using `register_next_step_handler` as described in this [example](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/step_example.py).

It is a nice feature, but is there any way to pass context from one handler to another? 
I store all received data in the database and to do this i have to get object in each handler, which is ridiculously inefficient. And it seems like i can't simply pass desired argument to handler.

`The function must accept at most one argument, which will be the message that the function must handle.`

**Comment by Senpos** [comment]
Hey, i am trying nested functions for that purpose now. 

I retrieve data from database in main handler and declare & use new functions inside that main handler.

Pseudo-code:
```Python
def main_handler():
    def sub_1_handler():
        # using data from main_handler scope
        register_next_step_handler(..., sub_2_handler)
    def sub_1_handler():
        # using data from main_handler scope
    
    data = some expensive call to database
    register_next_step_handler(..., sub_1_handler)
```

**Comment by gmm96** [comment]
It is supposed you can pass *args and **kwargs to the function, at least looking at the [code](https://github.com/eternnoir/pyTelegramBotAPI/blob/e62eeb7ff2a6c23f2a30dff38b19d76d62e45eb3/telebot/__init__.py), but it's not working in practice.
I have been trying to pass them and it always said there's too many arguments. 
Any soltuion? @eternnoir

**Comment by gmm96** [comment]
`Oct 28 04:20:21 UbuntuServer python[32426]: TypeError: register_next_step_handler() takes exactly 3 arguments (4 given)`

`bot.register_next_step_handler(m, add_audio_file, filepath="something)`

**Comment by MastAKK** [comment]
> `Oct 28 04:20:21 UbuntuServer python[32426]: TypeError: register_next_step_handler() takes exactly 3 arguments (4 given)`
> 
> `kwargs = {"filepath": "value"}`
> `bot.register_next_step_handler(m, add_audio_file, **kwargs)`

You shouldn't create a kwargs variable yourself, just pass variables as usual:
`bot.register_next_step_handler(m, add_audio_file, filepath="value")`
Should work

**Comment by gmm96** [comment]
> > `Oct 28 04:20:21 UbuntuServer python[32426]: TypeError: register_next_step_handler() takes exactly 3 arguments (4 given)`
> > `kwargs = {"filepath": "value"}`
> > `bot.register_next_step_handler(m, add_audio_file, **kwargs)`
> 
> You shouldn't create a kwargs variable yourself, just pass variables as usual:
> 
> `bot.register_next_step_handler(m, add_audio_file, filepath="value")`
> 
> Should work

I have also checked it before, doesn't work but code error is different.

`Oct 28 04:02:21 UbuntuServer python[31923]: TypeError: register_next_step_handler() got an unexpected keyword argument 'filepath'`

**Comment by gmm96** [comment]
Nothing else?

**Comment by ReadMost** [comment]
bot.register_next_step_handler(msg, lambda m: callback(m, args*))
Try this one

**Comment by Iqrar99** [comment]
This is example how you can pass an object into the next handler:

```python
def my_function(message):
   my_object = Something()
   msg = bot.reply_to(message, "TEST")
   bot.register_next_step_handler(msg, process_next_function, my_object)

def process_next_function(message, my_object):
   # Now you can access `my_object` in this function since it already passed in *args
```

**Comment by serebrich** [comment]
пт, 4 сент. 2020 г., 5:10 Iqrar Agalosi Nureyza <notifications@github.com>:

**Comment by sumarokov-vp** [comment]
`
def first_poll(cu)
    msg = bot.send_message(cu.cid, get_lang_phrase('how_much', cu.language))
    bot.register_next_step_handler(msg, process_get_money, cu)

def process_get_money(message, cu)
    m = message.text
    if m.isdigit():
        amount = float(m)
        msg = bot.send_message(cu.cid, get_lang_phrase('how_long', cu.language))
        bot.register_next_step_handler(msg, process_get_term, cu, amount)

def process_get_term(message, cu, amount)
    m = message.text
    if m.isdigit():
        term = int(float(m))
        ra = calculate_return_amount(amount, term)
        send_calculated_results(cu, ra)
`

**Comment by or-yarok** [comment]
My idea is to parametrize a function using `partial` from `functools`.
Example:
```
from functools import partial
@bot.message_handler(commands=['start'])
def greet(message):
	msg = "... your message...."
	bot.send_message(message.chat.id, msg)
	parametrized_handler2 = partial(handler2, param="you value")
	bot.register_next_step_handler(message, parametrized_handler2)

def handler2(message, param):
	_do something with `message` and `param`_

```
