### ISSUE TITLE
channel_post_handler(content_types=['new_chat_members'] Not working

### ISSUE THREAD

**Issue by lacoil** [eternnoir/pyTelegramBotAPI#464]
**pyTelegramBotAPI** version: 3.5.2
**OS**: Windows10
**Python version**: 3.6.4

I'm trying to handle new_chat_members service message from channel to get information about all users being added to the channel.  
The problem is I handle new_chat_title, but not new_chat_members.
My guess is that new_chat_members does not work in pyTelegramBotAPI
```
bot = telebot.TeleBot(TOKEN, threaded=False)
bot.get_updates(allowed_updates=["channel_post","message"])

#NEVER HIT
@bot.channel_post_handler(content_types=['new_chat_members'])
def channelhandler_NewUser(m):
    print ('new_chat_members')

#WORKS GOOD
@bot.channel_post_handler(content_types=['new_chat_title'])    
def channelhandler_TextToConsole2(m):
   # Userlist = m.new_chat_members
    print('new_chat_title')
```

**Comment by vb64** [comment]
this is a restriction from Telegram, not TelegramBotAPI

new_chat_members event doesn't appear in channels. it's for group/supergroup only.

**Comment by yourash** [comment]
So is any solution how to handle new channel participants?
