### ISSUE TITLE
Can't pass 'parse_mode' param to the 'send_photo' method.

### ISSUE THREAD

**Issue by MrNobodyCh** [eternnoir/pyTelegramBotAPI#467]
Please answer these questions before submitting your issue. Thanks!

1. 3.5.2

2. OS X

3. 2.7

__init__.py of your lib:

    def send_photo(self, chat_id, photo, caption=None, reply_to_message_id=None, reply_markup=None,
                   disable_notification=None):
        """
        Use this method to send photos.
        :param disable_notification:
        :param chat_id:
        :param photo:
        :param caption:
        :param reply_to_message_id:
        :param reply_markup:
        :return: API reply.
        """
        return types.Message.de_json(
            apihelper.send_photo(self.token, chat_id, photo, caption, reply_to_message_id, reply_markup,
                                 disable_notification))

**Comment by kostyakoz** [comment]
I think this need library to be updated to version of **Bot API 3.6** (released on February 13, 2018).

**Comment by MrNobodyCh** [comment]
So, waiting for the update...

**Comment by eternnoir** [comment]
Please check 3.6.0 tag. Or update by pip.
