### ISSUE TITLE
how to save 'msg.text' in a variable

### ISSUE THREAD

**Issue by homfarnam** [eternnoir/pyTelegramBotAPI#468]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.5.2

2. What OS are you using? ubuntu 16.04 lts

3. What version of python are you using? Python 3.5.2

   `     if msg.text=='.....:
        gmailaddress = bot.send_message(chat_id=chat_id, text='..... :')
        bot.register_next_step_handler(gmailaddress,msg)
        return gmailaddress

    org_email = "@gmail.com"
    if org_email in msg.text:
      gmailpassword = bot.send_message(chat_id=chat_id, text='.... :')
      return gmailpassword

    mailServer = smtplib.SMTP('smtp.gmail.com', 587)
    mailServer.starttls()
    mailServer.login(gmailaddress, gmailpassword)
`

hi
this is my code and i want to save 'msg.text' in a variable for use that in the mailserver section but i don't know how to do that
please help me
thanks

**Comment by MrNobodyCh** [comment]
some_variable=msg.text ?
