### ISSUE TITLE
parse_mode = "markdown" or "HTML" not working when using it in 'send_photo' method

### ISSUE THREAD

**Issue by MrNobodyCh** [eternnoir/pyTelegramBotAPI#469]
Please answer these questions before submitting your issue. Thanks!

1. 3.6.0

2. OSX

3. 2.7

**Code**
`bot.send_photo(message.chat.id, photo="AgADAgADwKgxG6sLuUispQ8IR_UOZKIBnA4ABMX49YVw5ClNTPkBAAEC",
                   caption="*%s*\n\n_%s_" % ("Bold", "Italic"),
                   parse_mode="Markdown")`

**Actual Result:**
<img width="404" alt="screen shot 2018-03-02 at 3 09 57 pm" src="https://user-images.githubusercontent.com/31210815/36898538-5143f8a2-1e2c-11e8-8255-d152fd163c23.png">

**Comment by vb64** [comment]
1. 3.6.0
2. Android 6.0
3. 2.7

![1](https://user-images.githubusercontent.com/8738387/36902985-be642704-1e45-11e8-9d86-ec99fff69369.jpg)

Final rendering makes TG client app. 
It's not a problem of this library
