### ISSUE TITLE
How to register next step handler if it must be  callback query?

### ISSUE THREAD

**Issue by ghost** [eternnoir/pyTelegramBotAPI#470]
Hellow!
**register_next_step_handler** expects **message**. How i can transfer to next step **callback_query**?

**Comment by ipique** [comment]
the same question. listening.

**Comment by sviat9440** [comment]
You can create a custom method that will register everything you need in the database of the json, sql, sqlite (and others of your choice).

**Comment by chandan22140** [comment]
> You can create a custom method that will register everything you need in the database, like json, sql, sqlite (and others of your choice). Personally, I've never used the default method.

I'm using PyTelegrambotApi to create a bot.

Requesting and receiving data appears to work; however, when I'm using the inline keyboard and create callback_query_handler to handle the user's choice the callback does not appear to fire.

Once the user has made a choice, the user should be asked for a price, but as it stands I have to send a message to the bot to trigger it. The bot will stay frozen until I send a random message - for example "Hey?" - and only then the bot starts the next step.

@bot.callback_query_handler(func=lambda call: True)
def user_answer(call):
    user[call.message.chat.id].city_id = call.data #creates dict from received data
    bot.register_next_step_handler(call.message, get_price) # <-- stuck at this point
The next step is:

def get_price(message):
    bot.send_message(message.chat.id, 'What's the price?')
    bot.register_next_step_handler(message, save_price)

**Comment by coder2020official** [comment]
Use states instead
