### ISSUE TITLE
webhook with Flask and Heroku

### ISSUE THREAD

**Issue by zahrafitrianti** [eternnoir/pyTelegramBotAPI#471]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? pyTelegramBotAPI-3.6.0

2. What OS are you using? macOS High Sierra 10.13.3

3. What version of python are you using? Python3.6

I tried out your code for `webhook_flask_heroku_echo.py`, but for the following method
```
@server.route('/' + TOKEN, methods=['POST'])
def getMessage():
    bot.process_new_updates([telebot.types.Update.de_json(request.stream.read().decode("utf-8"))])
    return "!", 200
```

I got a 500 response status. The error is
``` 
return json.loads(json_type)
ValueError: Expected object or value
```

I used the following code snippet is used to get updates from webhook
```
@server.route('/' + TOKEN, methods=['POST'])
def getMessage():
    json_string = request.get_data().decode('utf-8')
    update = telebot.types.Update.de_json(json_string)
    bot.process_new_updates([update])
    return "!", 200
```

But it seems to give errors at this particular line
```
update = telebot.types.Update.de_json(json_string)
```

Can you help me fix this?

**Comment by hariprasetya** [comment]
mbak @zahrafitrianti sudah coba ganti dari:
_`json_string = request.get_data().decode('utf-8')`_
menjadi:
_`json_string = request.stream.read().decode('utf-8')`_
