### ISSUE TITLE
Bot is suddenly crashing

### ISSUE THREAD

**Issue by CyberWenger** [eternnoir/pyTelegramBotAPI#473]
1. What version of pyTelegramBotAPI are you using?
_- Latest_

2. What OS are you using?
_- Ubuntu_

3. What version of python are you using?
_- 3.4_

Hi, Dear Community
Just want to say that I'm a novice and do not know very well both in programming and in the etiquette you have, so please forgive me in advance

I have a small bot with simple functions. It works well, but sometimes it crashed. After starting it always works for a while (always in different ways, it can work 40 hours or 2 hours) and then stops responding. I've been trying to solve this problem for more than a week, I've tried so many ways that I forgot even what I used

Remember I was getting this error
` File "/lebot/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/lebot/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/lebot/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/lebot/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/lebot/telebot/apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)`

Then I tried this solution #401
And then I stopped getting error reports in screen -list, only got this message:
`There is no screen to be resumed matching 31786.mybot.`

I also tried other solutions, but bot crushed sooner or later anyway

If necessary, I can give the bot code that I uploaded to the hosting

**Comment by IgorBeschastnov** [comment]
I'm having the same issue, had not figured it out yet.

**Comment by EnforcerZhukov** [comment]
That's a common issue, I suppose is something related with Telegram servers? You can somehow """fix""" the problem putting the polling inside a while True loop, so when it fails, it'll restart automatically. Here I uploaded some examples: https://gist.github.com/EnforcerZhukov/37e0ae02cd7fb1cd01085b2de553dde4

**Comment by sviat9440** [comment]
bot.pooling(none_stop=True)

**Comment by EnforcerZhukov** [comment]
none_stop=True usually does nothing about the timeout errors and other errors, at least in all my bots

**Comment by sviat9440** [comment]
@EnforcerZhukov ok, soon I will try to fix this problem.

**Comment by sviat9440** [comment]
@CyberWenger, @IgorBeschastnov, @EnforcerZhukov, try fix #484

**Comment by sviat9440** [comment]
Это намного сложнее, чем я думал. Вернемся к `while True` :)

**Comment by sviat9440** [comment]
Try bot.infinity_polling()
Works three days without crash, with unstable Internet
