### ISSUE TITLE
How to delete unused telebot.TeleBot and it's thread?

### ISSUE THREAD

**Issue by kostyakoz** [eternnoir/pyTelegramBotAPI#475]
1. **pyTelegramBotAPI v3.6.1**
2. **Ubuntu 17.10**
3. **Python 3.6.3**

I have a big `for` loop which create many `telebot.TeleBot()` bots from dict with tokens and sends messages to its users.

```
for user in users:
    bot = telebot.TeleBot(user['token']) # with users tokens
    ... # send messages from bot etc.
```

Everything looks fine, but I see that `telebot.TeleBot()` every time create new `thread`. 
Then I got error `RuntimeError: can't start new thread` because of server & Python limitations.

How can I delete unused bot & bot's thread? (it's create `thread` in `util.py`: `self.worker_pool = util.ThreadPool(num_threads=num_threads)`). 

`del bot` inside my loop delete only variable I think, but do nothing with `thread`.

Thanks.

**Comment by tiagonapoli** [comment]
I found some errors and made some experiments on this matter [issue481](https://github.com/eternnoir/pyTelegramBotAPI/issues/481)

**Comment by kostyakoz** [comment]
I think my problem in `threaded` argument in `telebot.TeleBot()` instance.
I've resolved my problem by just adding `threaded=False` argument when I create bot. 

I find it only in source code, its would be nice if it will be described in docs 😉
