### ISSUE TITLE
'AsyncTask' object has no attribute 'username'

### ISSUE THREAD

**Issue by arudmin** [eternnoir/pyTelegramBotAPI#476]
1. What version of pyTelegramBotAPI are you using?
Latest
3. What OS are you using?
MacOS
5. What version of python are you using?
3.6

bot = telebot.AsyncTeleBot(os.environ['TELEGRAM_TOKEN'])
bot.get_me().username

AttributeError: 'AsyncTask' object has no attribute 'username'

**Comment by eternnoir** [comment]
You need use wait function. `bot.get_me().wait().username`
