### ISSUE TITLE
new_chat_participant deprecated? 

### ISSUE THREAD

**Issue by Astrantia** [eternnoir/pyTelegramBotAPI#477]
1. What version of pyTelegramBotAPI are you using?
Latest
2. What OS are you using?
Windows 10
3. What version of python are you using?
3.6

https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/telebot_bot/telebot_bot.py 
Tried to use this example, but as soon as new member joins a group, the bot throws an error because message.new_chat_participant is not recognized. I took a look and the message it prints begins with new_chat_members, then I went and checked https://core.telegram.org/bots/api#user and I couldn't find new_chat_participants, but I found new_chat_members. Is there a bug in the example?

**Comment by sviat9440** [comment]
Not all examples are relevant at this time. For a complete list of available methods and parameters, see source code (types.py, apihelper.py).

**Comment by sudousercom** [comment]
Hi! same issue, none found in apihelper or types, maybe this function does not implemented for now?

**Comment by coder2020official** [comment]
Use message.new_chat_member(s)

**Comment by Badiboy** [comment]
https://core.telegram.org/bots/api

Try to find it here? Let us know if any.

**Comment by sudousercom** [comment]
> Use message.new_chat_member(s)

so, figured it out
for new chat members work this - message.new_chat_members[0].username
for leave chat members work message.left_chat_member.username
