### ISSUE TITLE
callback_query_handler issue

### ISSUE THREAD

**Issue by MrNobodyCh** [eternnoir/pyTelegramBotAPI#479]
1. 3.6.0

2. macOS High Sierra version 10.13.3

3. 2.7

I have some function which handling callback_data from the InlineKeyboardMarkup button:
> @bot.callback_query_handler(func=lambda call: call.data == "some_call")
> def test_function(call):
>        do_something

After repeatedly pressing the InlineKeyboardMarkup button, this function is permanently performed and returned the result.

**Comment by arudmin** [comment]
and what's the problem?

**Comment by MrNobodyCh** [comment]
Function is **permanently** performed and returned the result. 

E.g.: push the button 3 times, function is performed more than 3 times until the application stops.
