### ISSUE TITLE
Many (maybe)unactive threads and huge memory usage

### ISSUE THREAD

**Issue by tiagonapoli** [eternnoir/pyTelegramBotAPI#481]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.6.1

2. What OS are you using? Ubuntu 16.04

3. What version of python are you using? 3.5

``` 
    def __threaded_polling(self, none_stop=False, interval=0, timeout=3):
        logger.info('Started polling.')
        self.__stop_polling.clear()
        error_interval = .25

        polling_thread = util.WorkerThread(name="PollingThread")
        or_event = util.OrEvent(
            polling_thread.done_event,
            polling_thread.exception_event,
            self.worker_pool.exception_event
        )

        while not self.__stop_polling.wait(interval):
            or_event.clear()
            try:
                polling_thread.put(self.__retrieve_updates, timeout)

                or_event.wait()  # wait for polling thread finish, polling thread error or thread pool error

                polling_thread.raise_exceptions()
                self.worker_pool.raise_exceptions()

                error_interval = .25
            except apihelper.ApiException as e:
                logger.error(e)
                if not none_stop:
                    self.__stop_polling.set()
                    logger.info("Exception occurred. Stopping.")
                else:
                    polling_thread.clear_exceptions()
                    self.worker_pool.clear_exceptions()
                    logger.info("Waiting for {0} seconds until retry".format(error_interval))
                    time.sleep(error_interval)
                    error_interval *= 2
            except KeyboardInterrupt:
                logger.info("KeyboardInterrupt received.")
                self.__stop_polling.set()
                polling_thread.stop()
                break

        logger.info('Stopped polling.')`
```
I was observing the api's polling code and noted that polling_thread isn't stopped when you explicitly call the bot to stop polling (using bot.stop_polling(), this only can be done when you have an auxiliary thread to call it). I did a test and stopped polling many times and started polling again with the same telebot instance. The code I used to do the test is at the very end of the post. After each cycle, the number of active threads increased, without decreasing anytime. I had a problem that, after running the bot for one day, because each thread used some memory, the memory usage became super high.

![f1](https://user-images.githubusercontent.com/26463288/37688527-5d051b7e-2c7f-11e8-8119-ecf968d9d39d.png)
![f2](https://user-images.githubusercontent.com/26463288/37688529-5f732eaa-2c7f-11e8-8a99-6be78cc94b15.png)
![f3](https://user-images.githubusercontent.com/26463288/37688532-620219e2-2c7f-11e8-950f-0ab43fdfe370.png)

Note on the images that the memory usage is slowly increasing, in only 8 minutes (the first print was made at 19:02, the last at 19:10).

I tried to modify the api code in my pc, and i'm testing it now. Apparently with a simple modification the threads are closed after polling, but i don't know if it may create bugs on other parts of the api.

``` 
def __threaded_polling(self, none_stop=False, interval=0, timeout=3):
        logger.info('Started polling.')
        self.__stop_polling.clear()
        error_interval = .25

        polling_thread = util.WorkerThread(name="PollingThread")
        or_event = util.OrEvent(
            polling_thread.done_event,
            polling_thread.exception_event,
            self.worker_pool.exception_event
        )

        #######HERE#############
        stopped_polling_thread = False
       #######################
       while not self.__stop_polling.wait(interval):
            or_event.clear()
            try:
                polling_thread.put(self.__retrieve_updates, timeout)

                or_event.wait()  # wait for polling thread finish, polling thread error or thread pool error

                polling_thread.raise_exceptions()
                self.worker_pool.raise_exceptions()

                error_interval = .25
            except apihelper.ApiException as e:
                logger.error(e)
                if not none_stop:
                    self.__stop_polling.set()
                    logger.info("Exception occurred. Stopping.")
                else:
                    polling_thread.clear_exceptions()
                    self.worker_pool.clear_exceptions()
                    logger.info("Waiting for {0} seconds until retry".format(error_interval))
                    time.sleep(error_interval)
                    error_interval *= 2
            except KeyboardInterrupt:
                logger.info("KeyboardInterrupt received.")
                self.__stop_polling.set()
                polling_thread.stop()
                 #######HERE#############
                stopped_polling_thread = True
               ########################
                break

         #######HERE#############
        if stopped_polling_thread == False:
            polling_thread.stop()
       #############################

        logger.info('Stopped polling.')
```

The code I used to test:

```
import time
from threading import Thread
import gc
import telebot

def handle_message_not_understood(bot):
	@bot.message_handler(func = lambda msg: True)
	def msg_not_undestood(msg):
		user_id = msg.chat.id
		bot.send_message(user_id, "#message_not_understood")

def handle_cancel(bot):
	@bot.message_handler(func = lambda msg: True, commands = ['cancel'])
	def cancel(msg):
		user_id = msg.chat.id
		bot.send_message(user_id, "#cancel")


def handle_help(bot):
	@bot.message_handler(func = lambda msg: True, commands = ['help'])
	def help(msg):
		user_id = msg.chat.id
		bot.send_message(user_id, "#help_msg")


class MessageHandler():

	def __init__(self):
		self.last_restart = time.time()
		self.bot = telebot.TeleBot('INSERT TOKEN HERE')
		self.continue_flag = False
		self.first = True


	def idle_time(self):
		return time.time() - self.last_restart


	def restart_bot(self):
		if self.bot != None:
			self.bot.stop_polling()


	def stop(self):
		self.continue_flag = False
		if self.bot != None:
			self.bot.stop_polling()

	def setup_bot(self):
		if self.first:
			print("MESSAGE HANDLERS ADD")
			handle_cancel(self.bot)
			handle_help(self.bot)
			handle_message_not_understood(self.bot)

		self.first = False

	def run(self):
		self.continue_flag = True
		print("message handler on")
		self.setup_bot()
		cycles = 0
		while self.continue_flag:
			#try:
				# if cycles % 2 == 0:
				# 	self.logger.warning("Collect garbage")
				# 	gc.collect()
			self.last_restart = time.time()
			cycles += 1
			print("Start again! Cycles: " + str(cycles))
			self.bot.polling()

	

class MessageHandlerThread(Thread):

	def __init__(self, message_handler):
		Thread.__init__(self)
		self.message_handler = message_handler

	def stop(self):
		self.message_handler.stop()

	def run(self):
		self.message_handler.run()

	def restart_bot(self):
		self.message_handler.restart_bot()

	def idle_time(self):
		return self.message_handler.idle_time()


if __name__ == '__main__':
	message_handler = MessageHandler()
	message_handler_thread = MessageHandlerThread(message_handler)
	message_handler_thread.start()

	while True:
		aux = message_handler_thread.idle_time()
		print(aux)
		if message_handler_thread.idle_time() > 2:
			message_handler_thread.restart_bot()
		time.sleep(2)
```

**Comment by tiagonapoli** [comment]
When creating new instances, the old ones stay with unfinished threads too:


(piece of code in telebot class)
```
def __init__(self, token, threaded=True, skip_pending=False, num_threads=2):
        """
        :param token: bot API token
        :return: Telebot object.
        """
        self.token = token
        self.update_listener = []
        self.skip_pending = skip_pending

        self.__stop_polling = threading.Event()
        self.last_update_id = 0
        self.exc_info = None

        self.message_subscribers_messages = []
        self.message_subscribers_callbacks = []
        self.message_subscribers_lock = threading.Lock()

        # key: chat_id, value: handler list
        self.message_subscribers_next_step = {}
        self.pre_message_subscribers_next_step = {}

        self.message_handlers = []
        self.edited_message_handlers = []
        self.channel_post_handlers = []
        self.edited_channel_post_handlers = []
        self.inline_handlers = []
        self.chosen_inline_handlers = []
        self.callback_query_handlers = []
        self.shipping_query_handlers = []
        self.pre_checkout_query_handlers = []

        self.threaded = threaded
        if self.threaded:
            self.worker_pool = util.ThreadPool(num_threads=num_threads)
```

The self.worker_pool sometimes stays with unfinished threads (i think). Maybe would be nice to have a function to stop the bot instance, and call self.worker_poll.close().

(i think) This problem relates to the [issue#475](https://github.com/eternnoir/pyTelegramBotAPI/issues/475)

**Comment by eternnoir** [comment]
TODO:
* Fix polling thread not stop in some case
* Add stop method for TeleBot Class let developer can release polling_thread and work_pool.

**Comment by tiagonapoli** [comment]
There's another detail I noticed. Sometimes while polling, urllib3 raises ReadTimeOut exception and then aborts the _threaded_polling function. In these cases the polling_thread never stops too, just continues. Maybe if the while catches all exceptions, do polling_thread.stop(), and then re-raises the exception.

**Comment by Mityuha** [comment]
This bug is not fixed yet. As @tiagonapoli noticed 
```
There's another detail I noticed. Sometimes while polling, urllib3 raises ReadTimeOut exception and then aborts the _threaded_polling function. In these cases the polling_thread never stops too, just continues, it seems
```
As I understand, if there were any exceptions in polling thread different from apihelper.ApiException and KeyboardInterrupt:
1. Polling thread processes exception (https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/util.py#L65)
2. Main thread causes polling thread reraise exception catched (https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/__init__.py#L414)
3. If there was apihelper.ApiException or KeyboardInterrupt exception instance -- it's OK. But! If there was any other exception type (requests.exceptions.ReadTimeout, urllib3.exceptions.ReadTimeoutError etc.) polling function, i.e. __threaded_polling (https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/__init__.py#L395) aborts
  

Strictly speaking, there are two problems:
1. There are no chances anymore to stop and join polling thread, because it was assigned to local variable, that is no longer reachable. Moreover, if polling is called over infinity_polling(...) function, the number of process (polling) threads will increase until memory runs out or "can't start new thread" RuntimeError exception occurs;
2. These "suspended" threads will consume cpu and memory resources, since run(...) function implementation (https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/util.py#L49) has infinite loop with every 0.5 seconds Queue.Empty exception processing.

Possible fixes:
1. Make polling thread local variable class instance member variable and process polling thread (stop&join old, run new) every time __threaded_polling(...) function called
2. Process Exception class instance exceptions along with apihelper.ApiException and KeyboardInterrupt exceptions

As for me, I need threaded user request processing and I can't restart bot process every time any exception occurs in polling thread, because bot works inside docker container in k8s. I can probably  take infinite timeout parameter value, but when network appears after some system works it would be better to start connection again.

So as a temporary workaround I'm using 
```python
    bot = telebot.TeleBot(token, threaded=True, num_threads=5)
    while True:
        try:
            bot._TeleBot__non_threaded_polling(none_stop=False)
        except BaseException:
            logger.exception("")
            time.sleep(5)
        else:
            break
```
Though I would prefer clear way of using that good library. Thank you.
