### ISSUE TITLE
Echo bot with webhook and flask. Get 200, but don't get any answer from bot.

### ISSUE THREAD

**Issue by OlegBrony** [eternnoir/pyTelegramBotAPI#488]
I took this code (https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/webhook_examples/webhook_flask_echo_bot.py) and a little chenged it. I set webhook on ngrok, and it's working fine. here is my code 
https://hastebin.com/itoxoluyiv.py
I commended the part, where bot set webhook, because it already done. when I go to the site - I get 200 code, just like if I write something to bot. and get no answer. 
I also tryed use pythonanywhere, but I don't know its host. 
1. 3.6.2
2. Windows
3. 3.6

**Comment by eternnoir** [comment]
You commend set_webhook part. So you need set web hook by youself.

Check: https://core.telegram.org/bots/api#setwebhook
