### ISSUE TITLE
[Question] Can I mark message as viewed when I want?

### ISSUE THREAD

**Issue by analca3** [eternnoir/pyTelegramBotAPI#49]
Hi! I'm asking that If I can mark a message as viewed only when my bots finish their work. 

For example, when bot fails because of an API update or simply my fault, these messages are lost. Is there any way to hold this messages until I manage them properly?

**Comment by pevdh** [comment]
You could design a listener which saves all received messages to some storage facility (e.g. a file).
Pseudo code:
```python
def on_messages(messages):
    for message in messages:
        save_message(message)

bot.set_update_listener(on_messages)
```
How you handle the saved messages depends on what you want to do with them.

--- Oorspronkelijk bericht ---

Van: "Antonio Álvarez Caballero" <notifications@github.com>
Verzonden: 22 juli 2015 13:12
Aan: "eternnoir/pyTelegramBotAPI" <pyTelegramBotAPI@noreply.github.com>
Onderwerp: [pyTelegramBotAPI] [Question] Can I mark message as viewed when I want? (#49)

Hi! I'm asking that If I can mark a message as viewed only when my bots finish their work.

For example, when bot fails because of an API update or simply my fault, these messages are lost. Is there any way to hold this messages until I manage them properly?

---
Reply to this email directly or view it on GitHub:
https://github.com/eternnoir/pyTelegramBotAPI/issues/49

**Comment by analca3** [comment]
This is a good idea, but I think it's not perfect: when bot stops randomly https://github.com/eternnoir/pyTelegramBotAPI/issues/34 I don't know if your solution will keeping saving messages (it is good) or will discard the messages (it is bad)... In my case my bots discard the messages when they hang, so I think bot will discard messages. What do you think?

**Comment by pevdh** [comment]
You keep all messages that you succesfully write to a file. When the bot stops, messages will pile up at the Telegram servers (up to a hundred, I believe) until you start the bot again. So unless some exception is raised between (succesful) retrieval and the point at which messages are saved (and this should be rare), you will keep all received messages.

--- Oorspronkelijk bericht ---

Van: "Antonio Álvarez Caballero" <notifications@github.com>
Verzonden: 22 juli 2015 19:39
Aan: "eternnoir/pyTelegramBotAPI" <pyTelegramBotAPI@noreply.github.com>
CC: "Pieter" <pevdh@live.nl>
Onderwerp: Re: [pyTelegramBotAPI] [Question] Can I mark message as viewed when I want? (#49)

This is a good idea, but I think it's not perfect: when bot stops randomly https://github.com/eternnoir/pyTelegramBotAPI/issues/34 I don't know if your solution will keeping saving messages (it is good) or will discard the messages (it is bad)... In my case my bots discard the messages when they hang, so I think bot will discard messages. What do you think?

---

**Comment by Kondra007** [comment]
Store messages in memory and dumv via Shelve or SQLite to file on Exception

**Comment by analca3** [comment]
Ok, after a test I confirm I was wrong: my bot don't discard messages, but fails sending the response. Damm 502 error :(

```
pi@raspbmc:~/Git/LaTeX2IMGbot$ ./bot.py
/latex \phi    <------------------------ This is the received message
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/telebot/__init__.py", line 153, in __polling
    self.get_update()
  File "/usr/local/lib/python3.2/dist-packages/telebot/__init__.py", line 108, in get_update
    updates = apihelper.get_updates(self.token, offset=(self.last_update_id + 1), timeout=20)
  File "/usr/local/lib/python3.2/dist-packages/telebot/apihelper.py", line 71, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.2/dist-packages/telebot/apihelper.py", line 25, in _make_request
    raise ApiException(method_name, result)
telebot.apihelper.ApiException: getUpdates failed. Returned result: <Response [502]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.2/dist-packages/telebot/__init__.py", line 158, in __polling
    logger.error(e.message)
AttributeError: 'ApiException' object has no attribute 'message'

Exception in thread WorkerThread1:
Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.2/dist-packages/telebot/__init__.py", line 41, in run
    task(*args, **kwargs)
  File "./bot.py", line 36, in listener
    tb.send_sticker(chatid, equation)
  File "/usr/local/lib/python3.2/dist-packages/telebot/__init__.py", line 256, in send_sticker
    apihelper.send_data(self.token, chat_id, data, 'sticker', reply_to_message_id, reply_markup))
  File "/usr/local/lib/python3.2/dist-packages/telebot/apihelper.py", line 135, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
  File "/usr/local/lib/python3.2/dist-packages/telebot/apihelper.py", line 25, in _make_request
    raise ApiException(method_name, result)
telebot.apihelper.ApiException: sendSticker failed. Returned result: <Response [502]>
```

This error is so strange, sometimes I get it with getUpdates but now it's with sendSticker. Last time I get this error I only have to reboot the server (in another case was my laptop, now is my Raspberry Pi), but it has no sense for me. none_stop flag is not perfect, d'oh :(.

So, I'm not used to manage JSON, can anyone give me a clue for saving message as a file and how to recover it? Thanks!

PD: @Kondra007 what is dumv? I'm sorry, I'm spanish, I don't understood that :).

**Comment by Kondra007** [comment]
@analca3 "dumv" was a typo. I meant `dump` (Save from memory to disk)
502 error is "Bad Gateway", so I think it's not your fault but Telegram's.
Anyway, maybe you're sending a lot of requests in short amount of time, think about it.

**Comment by analca3** [comment]
Oh, ok, dump :).

Request? xD, it has only 1 request in this moment (the mine), anyone is using it at the moment... The strange is that last time I get this error I fix it rebooting server...

**Comment by Kondra007** [comment]
I think it was coincidence

**Comment by analca3** [comment]
What the... I launch the bot in my laptop and there is the same error. Are your bots running properly?

**Comment by Kondra007** [comment]
Recently I got `AttributeError: 'ApiException' object has no attribute 'message'`
I repeat, it's Telegram's problem. They're under DDoS now [news](https://telegram.org/blog/ddos)

**Comment by analca3** [comment]
Ok, thank you so much :), I'll read for dump messages to disk for backup :).

**Comment by eternnoir** [comment]
@analca3 @Kondra007 `AttributeError: 'ApiException' object has no attribute 'message'` This maybe only occur in python3. Because python3 removed message attribute in Exception. I'll fix next version.
