### ISSUE TITLE
file_id 

### ISSUE THREAD

**Issue by spikelo** [eternnoir/pyTelegramBotAPI#491]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2. What OS are you using?

3. What version of python are you using?

**Comment by spikelo** [comment]
1 . pyTelegramBotAPI==3.5.2
2 . Lubuntu : Lubuntu 16.04
3 . Python3
Can anyone explain where can i find file_id to my upload files . I have tried to search all attributes of message but nothing

**Comment by sviat9440** [comment]
sent_msg = bot.send_document(...)
    print(sent_msg.document.file_id)

**Comment by spikelo** [comment]
Let me explain , user send photo to bot my purpose is download it from bot.

**Comment by sviat9440** [comment]
`message.photo[0].file_id`

**Comment by spikelo** [comment]
Yes , thanks you . I have deleted previous  message  because i found answer. I did not see that attributes are in the list

**Comment by sviat9440** [comment]
If problem is solved, please close the issue
