### ISSUE TITLE
How to disable using HTTPS?

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#5]
Hello, how to disable InsecurePlatformWarnings? 
I'm running bot on my ODroid with no private SSL keys.

I see "API_URL" string in `__init__.py` file. Changed https to http -> still have warnings. Do I have to rebuild this lib somehow? (installed via git clone and `setup.py`)

**Comment by Kondra007** [comment]
Sorry, my bad. Now I see that only HTTPS is supported.

**Comment by eternnoir** [comment]
Hi, the warning message is from requests package. 
http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent

maybe it can help you.
