### ISSUE TITLE
No handlers could be found for logger "Telebot"

### ISSUE THREAD

**Issue by i32ropie** [eternnoir/pyTelegramBotAPI#50]
Hi, sometimes after my script is running, I get this message in the console and the script stops so I have to finish it and run it again. Do you know what could be? I leave you the code, it's very simple.

import telebot
from telebot import types
import time
TOKEN = '<my token>'
def listener(messages):
	"""
	When new messages arrive TeleBot will call this function.
	"""
	for m in messages:
		cid = m.chat.id
		if m.content_type == 'text':
			#print the sent message to the console
			#print str(m.chat.first_name) + " [" + str(m.chat.id) + "]: " + m.text
			print " [" + str(m.chat.id) + "]: " + m.text

bot = telebot.TeleBot(TOKEN)
bot.set_update_listener(listener) #register listener
try:
	bot.polling()
except Exception:
	pass
#Funcion de repetir mensajes.
@bot.message_handler(commands=['repite'])
def echo_message(message):
    repetir = message.text[7:]
    bot.reply_to(message, repetir)
    print "Edurolp_bot [" + str(message.chat.id) + "]: " + repetir

#Funcion flood
@bot.message_handler(commands=['flood'])
def flood_command(message):
    repetir = message.text[6:]
	#print "Edurolp_bot [" + str(message.chat.id) + "]: " + repetir + "(x10)"
    contador = 0
    while contador < 10:
        bot.send_message(message.chat.id , repetir)
        contador = contador + 1
	#print "Edurolp_bot [" + str(message.chat.id) + "]: " + repetir + "(x10)"

while True:
    time.sleep(0)

**Comment by eternnoir** [comment]
```python
logger = telebot.logger
formatter = logging.Formatter('[%(asctime)s] %(thread)d {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s',
                                  '%m-%d %H:%M:%S')
ch = logging.StreamHandler(sys.stdout)
logger.addHandler(ch)
logger.setLevel(logging.DEBUG)  # or use logging.INFO
ch.setFormatter(formatter)
```
