### ISSUE TITLE
if offset -> if offset it not None

### ISSUE THREAD

**Issue by bryzgaloff** [eternnoir/pyTelegramBotAPI#504]
https://github.com/eternnoir/pyTelegramBotAPI/blob/91f213ff3498eb78efa29db03fe775382fb82113/telebot/apihelper.py#L172

For example, when using `get_updates` with `offset=0` the resulting request url will be missing `offset` parameter.

**Comment by Badiboy** [comment]
> **offset | Integer | Optional**
> By default, updates starting with the earliest unconfirmed update are returned.
https://core.telegram.org/bots/api#getupdates

Offset is optional, so no need to send zero offset, it will work with "default" behaviour.
