### ISSUE TITLE
 TeleBot: "ConnectTimeout occurred"; Max retries exceeded with url...

### ISSUE THREAD

**Issue by artemmarkaryan** [eternnoir/pyTelegramBotAPI#505]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.2

2. What OS are you using?
MacOS HighSierra

3. What version of python are you using?
3.6

While my bot was down some user (me) has sent too much '/start' messages.
Now when the bot is up it tries to process all these messages and raises and exception.

Is there a way to tell my bot to ignore those messages, or process them one-by-one?

**Comment by artemmarkaryan** [comment]
Solved the problem by replacing the token. Nevertheless the problem could be somewhere in the connection.

**Comment by azikazimov** [comment]
What did you mean? Where did you passed your token?
