### ISSUE TITLE
Opening user photo gallery on 'Send Image' click and uploading image to the app

### ISSUE THREAD

**Issue by marekjuana** [eternnoir/pyTelegramBotAPI#507]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 2.2.3

2. What OS are you using? Windows10

3. What version of python are you using? 3.6
![capture](https://user-images.githubusercontent.com/38796139/39966603-78587896-56b7-11e8-95e9-1d88cae5bcb8.PNG)

hi do somebody know (have a script) that open user photo gallery on 'Send Image' click  that works like a crip click and and allows the user to select a photo and upload it to the app

**Comment by Badiboy** [comment]
Telegram bot API is not allowed to interact with a telegram client. It can only send messages (may be with menus) and receive messages and callbacks.
