### ISSUE TITLE
html_text does not parse text_links correctly

### ISSUE THREAD

**Issue by Badiboy** [eternnoir/pyTelegramBotAPI#508]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
**3.6.3**

2. What OS are you using?
**Windows 10**

3. What version of python are you using?
**3.4.3**

**Example:**
Forward any post from RBC channel, for example: https://t.me/rbc_ru/38221
![image](https://user-images.githubusercontent.com/5613421/39988248-8a15321e-576f-11e8-8ceb-821f42cfaa44.png)
**Entities seen in the message:**
```
Entity 1
{'type': 'bold', 'offset': 0, 'length': 67, 'url': None, 'user': None}
```

```
Entity 2
{'type': 'text_link', 'offset': 268, 'length': 16, 'url': 'http://www.rbc.ru/business/14/05/2018/5af8e8a89a7947876db3443c?fromtg=1', 'user': None}
```

**Result:**
```
<b>«Коммерсантъ» сообщил о проблемах СП Eni и «Роснефти» из-за санкций</b>
Источники «Коммерсанта» в нефтяной отрасли сообщили о де-факто остановке работы совместных предприятий «Роснефти» и итальянской Eni из-за американских санкций. О проблемах говорится и в отчетности СП
Подробнее на РБК
```

**_PS. Could you please do the same property for captions?_**

**Comment by sviat9440** [comment]
@Badiboy It's my fault. I have not tested links.

**Comment by sviat9440** [comment]
@Badiboy, okay, I'll do it in a few days.

**Comment by Badiboy** [comment]
@sviat9440 I did it myself, may be it'll be faster for you to take a look then to implement. :)
https://github.com/eternnoir/pyTelegramBotAPI/pull/509

**Comment by sviat9440** [comment]
@Badiboy great, tnx)
