### ISSUE TITLE
reply markup is too long

### ISSUE THREAD

**Issue by mojipkfr77** [eternnoir/pyTelegramBotAPI#511]
i really need help

**Comment by mojipkfr77** [comment]
im using the latest version of pyTelegramBotAPI
os : windows 10
python version = 3.6.5

i wanted to create a inline reply markup with 50 buttons 
and i got this error:
[b'{"ok":false,"error_code":400,"description":"Bad Request: reply markup is too long"}']"
what's wrong?

why is this happening?

**Comment by springjools** [comment]
The limit is 100 buttons
