### ISSUE TITLE
ReadTimeout at bot with webhooks

### ISSUE THREAD

**Issue by Timurizer** [eternnoir/pyTelegramBotAPI#518]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.3
2. What OS are you using?
Ubuntu 17.10
3. What version of python are you using?
3.6.3

I'm currently running my bot at webhooks using cherrypy.

```
class WebhookServer(object):
    @cherrypy.expose
    def index(self):
        if 'content-length' in cherrypy.request.headers and \
                        'content-type' in cherrypy.request.headers and \
                        cherrypy.request.headers['content-type'] == 'application/json':
            length = int(cherrypy.request.headers['content-length'])
            json_string = cherrypy.request.body.read(length).decode("utf-8")
            update = telebot.types.Update.de_json(json_string)
            # Эта функция обеспечивает проверку входящего сообщения
            bot.process_new_updates([update])
            return ''
        else:
            raise cherrypy.HTTPError(403)
```

It works for some time (5 minutes to several hours) and then I get
```
python3.6[25297]: [29/May/2018:17:58:18] HTTP
python3.6[25297]: Traceback (most recent call last):
python3.6[25297]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
python3.6[25297]:     six.raise_from(e, None)
python3.6[25297]:   File "<string>", line 3, in raise_from
python3.6[25297]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
python3.6[25297]:     httplib_response = conn.getresponse()
python3.6[25297]:   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
python3.6[25297]:     response.begin()
python3.6[25297]:   File "/usr/lib/python3.6/http/client.py", line 297, in begin
python3.6[25297]:     version, status, reason = self._read_status()
python3.6[25297]:   File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
python3.6[25297]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
python3.6[25297]:   File "/usr/lib/python3.6/socket.py", line 586, in readinto
python3.6[25297]:     return self._sock.recv_into(b)
python3.6[25297]:   File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
python3.6[25297]:     return self.read(nbytes, buffer)
python3.6[25297]:   File "/usr/lib/python3.6/ssl.py", line 871, in read
python3.6[25297]:     return self._sslobj.read(len, buffer)
python3.6[25297]:   File "/usr/lib/python3.6/ssl.py", line 631, in read
python3.6[25297]:     v = self._sslobj.read(len, buffer)
python3.6[25297]: TimeoutError: [Errno 110] Connection timed out
python3.6[25297]: During handling of the above exception, another exception occurred:
python3.6[25297]: Traceback (most recent call last):
python3.6[25297]:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
python3.6[25297]:     timeout=timeout
python3.6[25297]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 649, in urlopen
python3.6[25297]:     _stacktrace=sys.exc_info()[2])
python3.6[25297]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 357, in increment
python3.6[25297]:     raise six.reraise(type(error), error, _stacktrace)
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
python3.6[25297]:     raise value
python3.6[25297]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
python3.6[25297]:     chunked=chunked)
python3.6[25297]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 388, in _make_request
python3.6[25297]:     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
python3.6[25297]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 319, in _raise_timeout
python3.6[25297]:     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
python3.6[25297]: urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeou
python3.6[25297]: During handling of the above exception, another exception occurred:
python3.6[25297]: Traceback (most recent call last):
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 631, in respond
python3.6[25297]:     self._do_respond(path_info)
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 690, in _do_respond
python3.6[25297]:     response.body = self.handler()
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/cherrypy/lib/encoding.py", line 221, in __call__
python3.6[25297]:     self.body = self.oldhandler(*args, **kwargs)
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
python3.6[25297]:     return self.callable(*self.args, **self.kwargs)
python3.6[25297]:   File "/home/brandbot/sberbrandbot/aws/scripts/bot_hook.py", line 27, in index
python3.6[25297]:     bot.process_new_updates([update])
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/telebot/__init__.py", line 196, in process_new_updates
python3.6[25297]:     self.process_new_messages(new_messages)
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/telebot/__init__.py", line 218, in process_new_messages
python3.6[25297]:     self._notify_command_handlers(self.message_handlers, new_messages)
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/telebot/__init__.py", line 1345, in _notify_command_handlers
python3.6[25297]:     self._exec_task(message_handler['function'], message)
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/telebot/__init__.py", line 346, in _exec_task
python3.6[25297]:     task(*args, **kwargs)
python3.6[25297]:   File "/home/brandbot/sberbrandbot/aws/scripts/bot.py", line 100, in greet_user
python3.6[25297]:     bot.send_message(message.chat.id, texts.GREETING, parse_mode='Markdown')
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/telebot/__init__.py", line 480, in send_message
python3.6[25297]:     reply_markup, parse_mode, disable_notification))
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/telebot/apihelper.py", line 140, in send_message
python3.6[25297]:     return _make_request(token, method_url, params=payload, method='post')
python3.6[25297]:   File "/usr/local/lib/python3.6/dist-packages/telebot/apihelper.py", line 54, in _make_request
python3.6[25297]:     timeout=(connect_timeout, read_timeout), proxies=proxy)
python3.6[25297]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 502, in request
python3.6[25297]:     resp = self.send(prep, **send_kwargs)
python3.6[25297]: requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=9999)

python3.6[25297]:   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 612, in send
python3.6[25297]:     r = adapter.send(request, **kwargs)
python3.6[25297]:   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
python3.6[25297]:     raise ReadTimeout(e, request=request)
```

**Comment by Badiboy** [comment]
>  File "/home/brandbot/sberbrandbot/aws/scripts/bot.py", line 100, in greet_user
> python3.6[25297]:     bot.send_message(message.chat.id, texts.GREETING, parse_mode='Markdown')
It seems that timeout was reached when your bot tries to send the message to user. Webhooks are out of business here...

**Comment by Timurizer** [comment]
And what is the reason of this timeout? Bot works great for some time at all cases. Such crashes appear only after some time  (5 minutes to several hours as I wrote before). Restarting the bot fixes the problem, but only for some time, so it's not the solution. 

Here's the code btw. But it doesn't matter at all, it fails to send everything, not only in this case.
```
@bot.message_handler(commands=['start', 'help'])
def greet_user(message):
    bot.send_message(message.chat.id, texts.GREETING, parse_mode='Markdown')
```

**Comment by Badiboy** [comment]
> And what is the reason of this timeout?

The reason is that shit sometime happens. :) The connection problem occurs between your server and telegram server. Next try will (may) be successfull.

What is the problem with the bot after this crash? Why do you need to restart it? All other send_messages starts to fail?

**Comment by Timurizer** [comment]
> What is the problem with the bot after this crash? Why do you need to restart it? All other send_messages starts to fail?

Yes, after the crash bot fails to answer almost everything. But sometimes it answers like couple of times a day. After restart bot answers normally.

**Comment by Badiboy** [comment]
Ah, I got my old logs and see the same problem.
But I got this in "polling" mode when bot tried to get updates.

> 2018-05-13 00:44:19,077 (util.py:64 PollingThread) ERROR - TeleBot: "ReadTimeout occurred, args=(ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)",),)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 2, in raise_from
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
>     response.begin()
>   File "/usr/lib/python3.5/http/client.py", line 297, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.5/socket.py", line 575, in readinto
>     return self._sock.recv_into(b)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/contrib/pyopenssl.py", line 294, in recv_into
>     raise timeout('The read operation timed out')
> socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 357, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 686, in reraise
>     raise value
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 389, in _make_request
>     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
>     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
> urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 58, in run
>     task(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 159, in __retrieve_updates
>     updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
>   File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 129, in get_updates
>     json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
>   File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 175, in get_updates
>     return _make_request(token, method_url, params=payload)
>   File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 54, in _make_request
>     timeout=(connect_timeout, read_timeout), proxies=proxy)
>   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 521, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)

I had the same exception and bot stops polling until restart. AFAIK there was made additional poll mode "infinite_polling" (https://github.com/eternnoir/pyTelegramBotAPI/issues/474), but I now works with webhooks and did not tried it yet.

But I did not (yet?) face this issue with webhooks... May be you whould try to make manual exception handling at least for "bot.process_new_updates([update])" or even for "send_message"?
