### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tsuelectro** [eternnoir/pyTelegramBotAPI#519]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 
v3.6.3
2. What OS are you using?
windows 10 
3. What version of python are you using?
python 3.7

Traceback (most recent call last):
  File "echo_bot.py", line 1, in <module>
    import telebot
  File "C:\Program Files\Python37\lib\site-packages\telebot\__init__.py", line 1353
    @util.async()
              ^
SyntaxError: invalid syntax

***Repl Closed***

regards; I get this message syntax error as if the variable did not exist and look in the files and there are both:_init_.py  util.py  telebot.py.
thank you for help me...

**Comment by tsuelectro** [comment]
regards; I get this message syntax error as if the variable did not exist and look in the files and there are both:init.py util.py telebot.py.
thank you for help me...

**Comment by MasterGroosha** [comment]
Unfortunately, there are compability issues with Python 3.7 right now. I hope @eternnoir will take care of them, since 3.7 release is not far away.

**Comment by vovnit-phie** [comment]
got that problem too

**Comment by eternnoir** [comment]
After commit c8b2b1415 . You need use `@util.async_dec`.  It for python 3.7.
