### ISSUE TITLE
can't use reply_to_message_id

### ISSUE THREAD

**Issue by Mokhzzz** [eternnoir/pyTelegramBotAPI#520]
hi

i need to get id of a user who **i replied his message** in the group chat but i can't use the reply_to_message_id is there any other command that i can get the user id of this person?

**Comment by Badiboy** [comment]
Your question is **very** unclear. If I catch it well: AFAIK you should use "reply_to_message" field in the Message object returned by send_xxx function. See [Telegram docs](https://core.telegram.org/bots/api#message) for details.
