### ISSUE TITLE
High number of Thread in log

### ISSUE THREAD

**Issue by Badiboy** [eternnoir/pyTelegramBotAPI#522]
_1. What version of pyTelegramBotAPI are you using?_
3.6.3 + last commits
_2. What OS are you using?_
Ubuntu 16.04.4
_3. What version of python are you using?_
3.5.2

I looked at the log file after a week of bot online and see:

> 2018-06-13 21:18:19,294 (__init__.py:194 Thread-672) DEBUG - TeleBot: "Received 1 new updates"
> 2018-06-13 22:01:19,229 (__init__.py:194 Thread-673) DEBUG - TeleBot: "Received 1 new updates"
> 2018-06-13 22:01:21,239 (__init__.py:194 Thread-674) DEBUG - TeleBot: "Received 1 new updates"
 
The number of thread is increased every time the bot receive an update.
Workers numbers are fine:

> 2018-06-13 13:23:02,194 (__init__.py:194 Thread-560) DEBUG - TeleBot: "Received 1 new updates"
> 2018-06-13 13:23:02,195 (util.py:56 WorkerThread1) DEBUG - TeleBot: "Received task"

I'm confused of thread numbers: do the bot really had 674 active threads?
Or such a thread is created and then killed and this is just the counter increase?

**PS.** Code inspection of logger module shows that it uses Thread.name:
```
        if logThreads and threading:
            self.thread = threading.get_ident()
            self.threadName = threading.current_thread().name
```
Pyhton docs say:

> name is the thread name. By default, a unique name is constructed of the form “Thread-N” where N is a small decimal number.

But all this still gives me no answer to my question. :(

**Comment by MasterGroosha** [comment]
I think there is a problem with threads in this module, I'm constantly running into system error "Can't start new thread", which can be fixed by stopping some bots and restarting them.
