### ISSUE TITLE
Broken on Python 3.7

### ISSUE THREAD

**Issue by xvitaly** [eternnoir/pyTelegramBotAPI#524]
pyTelegramBotAPI version: 3.6.3
OS: Fedora 29 (rawhide).
Python version: 3.7.

```python
File "/usr/lib/python3.7/site-packages/telebot/util.py", line 146
    def async():
            ^
SyntaxError: invalid syntax
  File "/usr/lib/python3.7/site-packages/telebot/__init__.py", line 1353
    @util.async()
              ^
SyntaxError: invalid syntax
```

**Comment by xvitaly** [comment]
https://www.python.org/dev/peps/pep-0492/

**Comment by xvitaly** [comment]
@eternnoir Async is a registered keyword now. You need to rename your method from utils class.

**Comment by Badiboy** [comment]
Why "async_dec"? What's the reason for this name?

**Comment by eternnoir** [comment]
Maybe means decorator.

**Comment by arjenbrandenburgh** [comment]
Any chance on a new release to fix this?
