### ISSUE TITLE
Bug with multi-threading

### ISSUE THREAD

**Issue by ArtemCid** [eternnoir/pyTelegramBotAPI#533]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
    pyTelegramBotAPI==3.6.3
    telebot==0.0.3

2. What OS are you using?
   Ms Windows (Azure) or Linux (PythonAnywhere)

3. What version of python are you using?
   3.6.4

I use webhooks and multi-threaded TeleBot.
`bot = telebot.TeleBot(constants.token)`

The problem is that my command handlers not called when I call process_new_updates.
My issue is the same like for example https://github.com/eternnoir/pyTelegramBotAPI/issues/340

My impression is that the pyTelegramBotAPI  module "goes to sleep" if the bot doesn't get any commands for 4-5 minutes. To "awake it" user should post 10-15 commands after each other.
When I turn off multi-threading
`bot = telebot.TeleBot(constants.token, threaded=False)`
the problem cured a little: now user should post only 1-2 commands to awake a bot.

On local machine I can't reproduce the bug.
It's reproduced on two hostings: Microsoft Azure (Windows server) and PythonAnywhere (Linux).

Does anybody founded a solution?

**Comment by n3tr4k** [comment]
> My impression is that the pyTelegramBotAPI module "goes to sleep" if the bot doesn't get any commands for 4-5 minutes.

The same issue I have too, just submitted it #535 . And I also used threaded=True and polling instead, but threaded=False seems work fine...

**Comment by Badiboy** [comment]
"telebot==0.0.3" - who is that?

**Comment by Badiboy** [comment]
I use the bot and it may sleep for half a day and it still respond and send messages when needed.

I see that all issues are faced by ones who use Python 3.6.x. I have Python 3.5.2 (Linux) and bot run with webhooks. May there be any issue relative to Python 3.6?

**Comment by GerardHenninger** [comment]
Have the same problem; with threading the message handlers don't work. Without threading they work but the bot goes to "sleep" after a while and sometimes takes minutes to respond (and sometimes doesn't restart at all".

Is there still no fix for this?

Running the bot in a docker container, tried multiple Python versions. Tried in flask webserver, tried it with uWSGI and Gunicorn. Nothing seems to help.

**Comment by rganeyev** [comment]
why did you close this bug? it still happens for me as well.

Db connection does not close when using the `threading=True` option for webhooks.
