### ISSUE TITLE
how to make a telegram bot wait for answer?

### ISSUE THREAD

**Issue by BLucky-gh** [eternnoir/pyTelegramBotAPI#538]
1. I use the last version of the API (updated it yesterday)

2. I'm on Mac Os X High Sierra

3. I'm on python 3.6.2

so, I have a post-to-channel bot that has to ask a question in response to a command and wait for the answer and save the answer to a variable, but i do not know how to make the bot wait for the answer.

here's my code:  https://pastebin.com/ffsecq4y

**Comment by Badiboy** [comment]
See examples/echo_bot.py
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/echo_bot.py

**Comment by BLucky-gh** [comment]
Sorry, but my matter is a bit more complicated than echoing the same message, my bot has to wait for reply, then store the reply, and answer the same thing whatever the answer was, so I cannot use the text handle decorator,

**Comment by BLucky-gh** [comment]
Very much like @contorllerbot

**Comment by Badiboy** [comment]
The author gave you an example how to work with pyTelegramBotAPI and I gave you the link to this example. Do you really think that somebody here will write the program for you?

**Comment by BLucky-gh** [comment]
no, just explain which command should I use. anyways I have already figured it out using nested decorators

**Comment by mbnai** [comment]
Damn! I have same problem...

**Comment by Shaffle1** [comment]
> no, just explain which command should I use. anyways I have already figured it out using nested decorators

Can you please explain how you did it, please? I have the same exact problem. Thanks a lot!

**Comment by dx4321** [comment]
> Черт! У меня такая же проблема ...

+

**Comment by SaiMun92** [comment]
ok, my question will be how NOT to wait for an answer?

**Comment by kurkurzz** [comment]
I think the solution is to use bot.register_next_step_handler(msg, func) 
sample code is [here](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/step_example.py)

**Comment by BLucky-gh** [comment]
Yeah i found it out 2 years ago @kurkurzz

**Comment by TopAndrey** [comment]
> The author gave you an example how to work with pyTelegramBotAPI and I gave you the link to this example. Do you really think that somebody here will write the program for you?

ChatGPT may write code for him XD
