### ISSUE TITLE
kick_chat_member dosen't return types.Message

### ISSUE THREAD

**Issue by P-Alban** [eternnoir/pyTelegramBotAPI#540]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.3
2. What OS are you using?
win 10 x64
3. What version of python are you using?
3.6.5

In method description says: 
```
    def kick_chat_member(self, chat_id, user_id, until_date=None):
        """
        Use this method to kick a user from a group or a supergroup.
        :param chat_id: Int or string : Unique identifier for the target group or username of the target supergroup
        :param user_id: Int : Unique identifier of the target user
        :param until_date: Date when the user will be unbanned, unix time. If user is banned for more than 366 days or
               less than 30 seconds from the current time they are considered to be banned forever
        :return: types.Message
        """
```
It must return ` types.Message`, bot it's returning a boolean

**Comment by Badiboy** [comment]
Incorrect method description.

According to API it returns BOOLEAN: https://core.telegram.org/bots/api#kickchatmember

**Comment by Badiboy** [comment]
Fix description https://github.com/eternnoir/pyTelegramBotAPI/pull/539/commits/8634e652497065178dd5f538327fddd04a53f963
