### ISSUE TITLE
Error 409 Conflict

### ISSUE THREAD

**Issue by memeToasty** [eternnoir/pyTelegramBotAPI#543]
1. What version of pyTelegramBotAPI are you using?
- 3.6.3
2. What OS are you using?
- Windows
3. What version of python are you using?
- 3.6.6
My problem is that after some time the Bot crashes with given Error Message... I didnt found any solutions for this, but im only running a single instance of the Bot, so i am very confused about the error message.
Source Code:

https://pastebin.com/QwJdvdF4

Error Message :

\__init__.py", line 128, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Users\Petra\AppData\Local\Programs\Python\Python36\lib\site-packages\telebot\apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Petra\AppData\Local\Programs\Python\Python36\lib\site-packages\telebot\apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "C:\Users\Petra\AppData\Local\Programs\Python\Python36\lib\site-packages\telebot\apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']

**Comment by Yodams** [comment]
did you solve it ?
