### ISSUE TITLE
how to get chat_id and message_id in telebot(pytelegramBotAPI) to update last sent messaeg in telegram bot(Python)

### ISSUE THREAD

**Issue by ijahongirmirzo** [eternnoir/pyTelegramBotAPI#546]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? latest

2. What OS are you using? Ubuntu

3. What version of python are you using? 3.6

Good day!
here is my piece of code
` bot.edit_message_text(chat_id = CHAT_ID, message_id = MESSAGE_ID, text = "message has been updated", reply_markup=inline_keyboard)`
thanks in advance

**Comment by Badiboy** [comment]
```
msg = bot.send_message(xxxxx)
bot.edit_message_text(chat_id = msg.chat.id, message_id = msg.message_id...
```

**Comment by 0susboy0** [comment]
### dick

**Comment by marsuh228** [comment]
Merzbow.
