### ISSUE TITLE
Webhook on flask with proxy, silent bot. 

### ISSUE THREAD

**Issue by daniyal18374** [eternnoir/pyTelegramBotAPI#552]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.5

2. What OS are you using?
Ubuntu 18.04

3. What version of python are you using?
3.6.5

Hello! I used your example (https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/webhook_examples/webhook_flask_echo_bot.py). I added proxy to my bot:
`apihelper.proxy = {'https': 'socks5://login:password@ip:port'}`

When i try to go to https://0.0.0.0:8443/, i get 200 message.
When i try to go to https://my_ip:8443/my_token/, i get 405 message.
And i see nothing in my telegram bot, although i send messages.

My 8443 port is open:

![port_8443_isopen](https://user-images.githubusercontent.com/39619485/43687995-90e342c8-98e9-11e8-8db3-39a15375583a.png)

And my webhook info:
{'url': 'https://my_ip:8443/token/', 'has_custom_certificate': True, 'pending_update_count': 3, 'last_error_date': None, 'last_error_message': None, 'max_connections': 40, 'allowed_updates': None}

Please help me to understand what is wrong!

Thank you for you help!

**Comment by Badiboy** [comment]
Proxy is not the reason. To use subdirectories (like .../my_token/...) you need the web server who will route your requests to the flask app. For me I use nginx.

See the similar topic here: https://github.com/eternnoir/pyTelegramBotAPI/issues/541
