### ISSUE TITLE
How we should set callback query handler for inline buttons?

### ISSUE THREAD

**Issue by kingofnull** [eternnoir/pyTelegramBotAPI#563]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Version: 3.6.5
2. What OS are you using?
Windows 10 April 2018
3. What version of python are you using?
Python 2.7.14

this show the inline buttons:

```
msg = bot.reply_to(m, "Send me your url:")
markup = types.InlineKeyboardMarkup()
itembtna = types.InlineKeyboardButton('a', callback_data="ds")
itembtnv = types.InlineKeyboardButton('v', callback_data="sds")
itembtnc = types.InlineKeyboardButton('c', callback_data="sdss")
markup.row(itembtna)
markup.row(itembtnv, itembtnc)
```

but how we should set callback query handler for inline buttons?

**Comment by Badiboy** [comment]
Just look at examples! 
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/inline_example.py

**Comment by Badiboy** [comment]
Read the doc here:
https://github.com/eternnoir/pyTelegramBotAPI#callback-query-handler

**Comment by kingofnull** [comment]
Thanks but how to update the message?

**Comment by Badiboy** [comment]
`bot.edit_message_text(chat_id, message_id, new_text, ...)`
or any other edit_message_xxx.

See details here: https://core.telegram.org/bots/api#updating-messages

**Comment by kingofnull** [comment]
I know but where are chat id and message id in query ?

**Comment by Badiboy** [comment]
Bro, spend 10 minutes to read the docs! Bot API doc is really small and well structured.

https://core.telegram.org/bots/api#callbackquery

query.message.chat.id
query.message.message_id

**Comment by kingofnull** [comment]
Thanks I done it before but in another way, I found chat_id in `json` property of message not directly in message property. I think documentation of pyTelegramBotAPI is not complete and should cover this. Also there are other function in telegram bot API which didn't mention in pyTelegramBotAPI's documentation and I don't know how to use them.

**Comment by SL-Hydra** [comment]
> `bot.edit_message_text(chat_id, message_id, new_text, ...)` or any other edit_message_xxx.
> 
> See details here: https://core.telegram.org/bots/api#updating-messages

bro how to delete a message?

**Comment by GodHand226** [comment]
Thanks to this thread.
