### ISSUE TITLE
I use 3.6.5 version of pyTelegramBotAPI

### ISSUE THREAD

**Issue by nurland777** [eternnoir/pyTelegramBotAPI#564]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2. What OS are you using?

3. What version of python are you using?

**Comment by fozema67** [comment]
1. 3.6.5
2. Windows 7 x64
3. 3.6.1

**Comment by jamescash120** [comment]
pyTelegramBotAPI v3.6.6
Win 7
Python v3 7.4

import telebot
Writes: no module named telebot

pip list
pyTelegramBotAPI v3.6.6

pip install
already satisfied

Tried pip and pip3 to install
Tried add path
Tried python 32 and 64
