### ISSUE TITLE
Run 1 bot, more than 1 PC

### ISSUE THREAD

**Issue by rollly00** [eternnoir/pyTelegramBotAPI#568]
Hello, can I run one bot on 5 different computers, and switch between them in one chat?
For example:
/to 1-PC
/to 2-PC
etc.

**Comment by Badiboy** [comment]
Nope.

**Comment by khode-mohsen** [comment]
> Hello, can I run one bot on 5 different computers, and switch between them in one chat?
> For example:
> /to 1-PC
> /to 2-PC
> etc.

you have to use a server to save this data and when you need call that to send data for your devices , bye
