### ISSUE TITLE
The light does not turn off after sending photos

### ISSUE THREAD

**Issue by rollly00** [eternnoir/pyTelegramBotAPI#570]
When I run this code without a bot, the bulb is turned off, for its shutdown, it answers cap.release(), but I run this code through the bot, the bulb does not turn off.

```
		cap = cv2.VideoCapture(0)
		ret, frame = cap.read()
		cv2.imwrite('1.jpg',frame)
		doc = open('1.jpg','rb')
		bot.send_document(message.chat.id,doc)
		cap.release(1)
```

**Comment by Badiboy** [comment]
_Lol, what bulb you are talking about? On your webcam? :)_

https://askubuntu.com/a/701536/453929
_As we can learn from ..., the Python interpreter closes the file in the following cases:
...
the file object's last reference got removed and therefore the object gets processed by the Garbage Collector. **This is not a language feature, but a special feature of the CPython implementation only, so for portability don't rely on this!**
..._
Close your file by calling **doc.close()** explicitly or put the code in **with open(...):** block...
