### ISSUE TITLE
Bad Request: field \\"parse_mode\\" must be of type String"

### ISSUE THREAD

**Issue by MasterGroosha** [eternnoir/pyTelegramBotAPI#571]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.5
2. What OS are you using?
Ubuntu 16.10
3. What version of python are you using?
3.5

Latest pyTelegramBotAPI is **bugged**. Whenevery you run answer_inline_query you crash with `{"ok":false,"error_code":400,"description":"Bad Request: field \\"parse_mode\\" must be of type String"}` error

**Comment by Badiboy** [comment]
Any example of your "answer code"?

**Comment by MasterGroosha** [comment]
@Badiboy 

```python
@bot.inline_handler(func=lambda query: True)
def inline(query):
    android = telebot.types.InlineQueryResultCachedDocument(
        id="android",
        title="Telegram Android Localizaton",
        description="android",
        document_file_id="BQADAgADlAEAAgZsSUhcA2wI",
        caption="android",
    )

    desktop = telebot.types.InlineQueryResultCachedDocument(
        id="desktop",
        title="Telegram Desktop Localizaton",
        description="Desktop",
        document_file_id="BQADAgADlAEAAgZsSUh",
        caption="desktop"
    )
    android_x = telebot.types.InlineQueryResultCachedDocument(
        id="android_x",
        title="Telegram X Localizaton",
        description="x",
        document_file_id="BQADAgADlAEAAgZsSUhcA",
        caption="X"
    )
    bot.answer_inline_query(query.id, [android, desktop, android_x], cache_time=300)
```

**Comment by Badiboy** [comment]
I had a look, but I see the only problem: InlineQueryResultCachedDocument() constructor does not  have the parse_mode parameter to request at all (while Bot API has such parameter). This is the problem for one who want to use it, but it's not your case.

As far as I see, for this case nothing is passed to the request to server regarding the parse_mode. Can you set the logger level to "DEBUG" and see the exact request details? If there is anything regarding the parse_mode?

**Comment by Badiboy** [comment]
Yep, exactly. So I wonder if anything for parse_mode is sending to server. If nothing - the problem is on server side. If anything - we should dig deeper in sources.

**Comment by MasterGroosha** [comment]
@Badiboy Hmm... I got into [answer_inline_query](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/apihelper.py#L884) method in apihelper.py and did `print(payload)`. Besides other arguments it shows me `"parse_mode":null` string which is very strange.

**Comment by Badiboy** [comment]
Mmm, sorry. I looked at outdated sources. [Here](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/types.py#L1686) everything is passed.

```
class InlineQueryResultCachedDocument(BaseInlineQueryResultCached):
    def __init__(self, id, document_file_id, title, description=None, caption=None, parse_mode=None, reply_markup=None, input_message_content=None):
...
        self.payload_dic['parse_mode'] = parse_mode
```
I should investigate what happens once again...

**Comment by MasterGroosha** [comment]
Most likely [this commit](https://github.com/eternnoir/pyTelegramBotAPI/commit/5035e0ce80e86e24b489c99cd78a02fff280b717) broke inline mode

**Comment by Badiboy** [comment]
In the latest code I see it's fixed from
`        self.parse_mode = parse_mode

to
`        self.payload_dic['parse_mode'] = parse_mode

I think we need new release...

**Comment by Badiboy** [comment]
3.6.6 released. 
@MasterGroosha , can you check if the problem is solved?

**Comment by MasterGroosha** [comment]
@Badiboy as far as I see, no.

**Comment by rmed** [comment]
Encountered the same issue today while working with `InlineQueryResultCachedPhoto`. Seems like the Telegram API does not like the `null` value, so as a workaround I'd suggest adding `parse_mode=''` as an argument, which should be ignored by the API.

After checking the commit @MasterGroosha mentioned I think the problem lies in how the cached version of the inline query results are managed. The non-cached classes (such as `InlineQueryResultPhoto`) do not send the `parse_mode` when the argument is empty ([See example](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/types.py#L1236)).

This is not the case for `BaseInlineQueryResultCached`, which sends the JSON "as is" without checking those special arguments ([See here](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/types.py#L1610))
