### ISSUE TITLE
get_file_url AttributeError

### ISSUE THREAD

**Issue by P-Alban** [eternnoir/pyTelegramBotAPI#578]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.6
2. What OS are you using?
win 10
3. What version of python are you using?
3.6.5

AttributeError when you trying to use get_file_url, because there is a dict, replace it: 
Before:
`FILE_URL.format(token, get_file(token, file_id).file_path)`
After:
`FILE_URL.format(token, get_file(token, file_id)['file_path'])`

https://github.com/eternnoir/pyTelegramBotAPI/blob/07b82dc9b0af773d472b10d83ad4c55acceca997/telebot/apihelper.py#L103

**Comment by qwqmeow** [comment]
I guess,  from the perspective of the project author, maybe he forgot to `de_json` the result of `get_file`,so he call `file_path` as attribute.

in telebot/apihelper.py（In my humble opinion
```py
def get_file(token, file_id):
    method_url = r'getFile'
    return types.File.de_json(_make_request(token, method_url, params={'file_id': file_id})
```
then you can call `get_file(token, file_id).file_path` without AttributeError
