### ISSUE TITLE
Creating Calculator but How?

### ISSUE THREAD

**Issue by daemonbtw** [eternnoir/pyTelegramBotAPI#579]
Please answer these questions before submitting your issue. Thanks!

Hello I created a Bot that grabs data from an API. I want that users can enter this command for example: /calc 10. Bot should calculate Number with Input (in this case 10) How can I do it?

1. What version of pyTelegramBotAPI are you using?
Latest
2. What OS are you using?
Pythonanywhere Bash Console
3. What version of python are you using?
3.6

**Comment by Badiboy** [comment]
You should:
1. Write bot
2. Run bot
3. Profit!
