### ISSUE TITLE
 __polling [ERROR] Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by mahrens917** [eternnoir/pyTelegramBotAPI#58]
Received this error today.  One way to resolve is to add json exception handling in _make_request in apihelper.py.

For now will resolve with none_stop=True in call to polling.

**Comment by pevdh** [comment]
Can you provide the full stack trace please?

**Comment by mahrens917** [comment]
Unfortunately, I do not have the stack trace for this - some logging was turned off.   Next bug report, I will provide.  

Thanks for a great product.

**Comment by pevdh** [comment]
Make sure to use the latest version, it provides more information as to where an Exception comes from.
