### ISSUE TITLE
Handle just channel updates 

### ISSUE THREAD

**Issue by aguro90** [eternnoir/pyTelegramBotAPI#580]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Last

2. What OS are you using?
Win10

3. What version of python are you using?
3.6

**Comment by aguro90** [comment]
How the hell can I just handle channel update where my bot is admin? 

I have no problems managing single chats but I just need to listen a channel.

**Comment by Badiboy** [comment]
Messages from channels are handled by ordinal handlers:
```
@bot.message_handler(content_types=['text', 'audio', 'document', 'photo', 'video'])
def process_message_other(message):
   print("Got the message")
```

What do you mean under "channel update"?

**Comment by Badiboy** [comment]
Additionally, try to send something to any chat (the bot is added to, your channel for example) just to be sure that the bot is connected and interaction works well.

**Comment by aguro90** [comment]
Okey,  thanks for quick responses. I gave up for today but will try that in the morning. Many many thanks man.

**Comment by aguro90** [comment]
It didnt work. I receive the update in the http api like that
<code>
{"ok":true,"result":[{"update_id":639341210,
"message":{"message_id":4,"from":{"id":438098035,"is_bot":false,"first_name":"Alfonso","last_name":"De la mata","language_code":"es"},"chat":{"id":438098035,"first_name":"Alfonso","last_name":"De la mata","type":"private"},"date":1538303907,"text":"Hola"}},{"update_id":639341211,
"channel_post":{"message_id":2,"chat":{"id":-1001189121756,"title":"Testing","username":"tietar","type":"channel"},"date":1538303921,"text":"Yeye"}}]}
</code> 

and Im not receiving the message from the channel in python.

**Comment by aguro90** [comment]
[In this issue]((https://github.com/eternnoir/pyTelegramBotAPI/issues/413#issuecomment-343714394))

is related a different handler wich is supposed to manage channel posts but this is my code(dont know how to put prettier)

<code>
import telebot
bot = telebot.TeleBot("694978643:AAEPN1nB9xhoBVd_0bi5487DmHPmCrRmvp0")
@bot.message_handler(content_types=['text', 'audio', 'document', 'photo', 'video','channel_post'])
def process_message_other(message):
   print("Got the message")
@bot.channel_post_handler(func=lambda message: True, content_types=["text", "photo", "video"])
def echo_message(message):
    print(message.text)
bot.polling()
</code>

and this is my output:

> @bot.channel_post_handler(func=lambda message: True, content_types=["text", "photo", "video"])
>AttributeError: 'TeleBot' object has no attribute 'channel_post_handler'

**Comment by Badiboy** [comment]
Damn, sorry, I use 3 telegram python APIs in parallel and they are messed up in my head.

Of course, you should use _channel_post_handler_ decorator to handle channel posts.

TeleBot definitely have the channel_post_handler attribute:
![image](https://user-images.githubusercontent.com/5613421/46258236-b04e5c80-c4cf-11e8-8248-a42ab95d30ea.png)

and this simple code definitely work for me:
![image](https://user-images.githubusercontent.com/5613421/46258271-34084900-c4d0-11e8-93a3-c08c43af8042.png)

**Comment by aguro90** [comment]
Your comment made me to find deeper in the code  and i had some packet wrong installed or something due I tried some APIS.  Clean modules and reinstall and everything **worked nice.** 

Hope this could help anyone reading this.

Again thanks a lot for your quick responses

**Comment by EyasuTew** [comment]
How to send, edit and delete message from bot to channel.
