### ISSUE TITLE
Method download_file()

### ISSUE THREAD

**Issue by CraftedCat** [eternnoir/pyTelegramBotAPI#581]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI  3.6.6
2. What OS are you using?
Ubuntu Server 
3. What version of python are you using?
3.6.5/3.6.6

After pyTelegramBotAPI update, Method download_file() not working
`
oct 05 10:59:16 test.com OfdBot[16113]: 2018-10-05 10:59:16,863 (util.py:65 WorkerThread2) ERROR - TeleBot: "ApiException occurred, args=('A request to the Tel
oct 05 10:59:16 test.com OfdBot[16113]: Traceback (most recent call last):
oct 05 10:59:16 test.com OfdBot[16113]: File "/usr/lib64/python3.6/site-packages/telebot/util.py", line 59, in run
oct 05 10:59:16 test.com OfdBot[16113]: task(*args, **kwargs)
oct 05 10:59:16 test.com OfdBot[16113]: File "/home/test/my_env/ofdcheckbot/ofdbot.py", line 83, in ofd_check_qr
oct 05 10:59:16 test.com OfdBot[16113]: downloaded_file = bot.download_file(file_info.file_path)
oct 05 10:59:16 test.com OfdBot[16113]: File "/usr/lib64/python3.6/site-packages/telebot/__init__.py", line 488, in download_file
oct 05 10:59:16 test.com OfdBot[16113]: return apihelper.download_file(self.token, file_path)
oct 05 10:59:16 test.com OfdBot[16113]: File "/usr/lib64/python3.6/site-packages/telebot/apihelper.py", line 112, in download_file
oct 05 10:59:16 test.com OfdBot[16113]: raise ApiException(msg, 'Download file', result)
oct 05 10:59:16 test.com OfdBot[16113]: telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden.
oct 05 10:59:16 test.com OfdBot[16113]: [<html>
oct 05 10:59:16 test.com OfdBot[16113]: <head><title>403 Forbidden</title></head>
oct 05 10:59:16 test.com OfdBot[16113]: <body bgcolor="white">
oct 05 10:59:16 test.com OfdBot[16113]: <center><h1>403 Forbidden</h1></center>
oct 05 10:59:16 test.com OfdBot[16113]: <hr><center>nginx/1.12.2</center>
oct 05 10:59:16 test.com OfdBot[16113]: </body>
oct 05 10:59:16 test.com OfdBot[16113]: </html>
oct 05 10:59:16 test.com OfdBot[16113]: ]
oct 05 10:59:16 test.com OfdBot[16113]: "
`

**Comment by PKEv** [comment]
nead add file path to it, like this:
bot.download_file(photos.file_path)

**Comment by CraftedCat** [comment]
Nope. Look, i had this parameter
sended_photo_from_array = bot.get_file(message.photo[len(message.photo)-1].file_id)


        #sended_photo_from_array = bot.get_file(message.photo[0].file_id)
        print (message.photo)
        print (sended_photo_from_array)
        print (sended_photo_from_array.file_path)

        downloaded_file = bot.download_file(sended_photo_from_array.file_path)

**Comment by CraftedCat** [comment]
Nope. Look, i had this var
``
sended_photo_from_array = bot.get_file(message.photo[len(message.photo)-1].file_id)


        #sended_photo_from_array = bot.get_file(message.photo[0].file_id)
        print (message.photo)
        print (sended_photo_from_array)
        print (sended_photo_from_array.file_path)

        downloaded_file = bot.download_file(sended_photo_from_array.file_path)

**Comment by CraftedCat** [comment]
Only revoke TOKEN reslove my problem
