### ISSUE TITLE
reply on private message

### ISSUE THREAD

**Issue by beryindo** [eternnoir/pyTelegramBotAPI#582]
How to if type on group but bot reply on private message ?

**Comment by Badiboy** [comment]
if (message.chat.type == "private"): ...

_Type of chat, can be either “private”, “group”, “supergroup” or “channel”_
(See [API](https://core.telegram.org/bots/api#chat))

**Comment by beryindo** [comment]
how to add to here ?
`@bot.message_handler(commands=['help', 'start'])
def command_start(m):
   bot.send_message(m.chat.id,"test")`

**Comment by Badiboy** [comment]
```
@bot.message_handler(commands=['help', 'start'])
def command_start(m):
   if (m.chat.type == "private"):
      bot.send_message(m.chat.id,"test")
```
