### ISSUE TITLE
 CURRENCY total amount Invalid

### ISSUE THREAD

**Issue by vmazurenko** [eternnoir/pyTelegramBotAPI#595]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI==3.6.6 

2. What OS are you using?
Ubuntu 16.04

3. What version of python are you using?
3.5.2

### 
I just tried to call invoice using example in pyTelegramBotAPI library and got this error : "Bad Request: CURRENCY_TOTAL_AMOUNT_INVALID, did not search any answer about this error message in google ....

**Comment by vmazurenko** [comment]
if someone has problem like me just see minimum amount - https://core.telegram.org/bots/payments#supported-currencies, solved !

**Comment by vladkomudrich** [comment]
I faced this problem in aiogram. I knew about the minimum amount, and kept this rule but still got **Currency_total_amount_invalid**. 

**How did I solve this?** For example if you want to **set amount** - 100 RUB, you must write **10000** and at the output you will **receive 100,00** RUB ;)

**Comment by honsour72** [comment]
> I faced this problem in aiogram. I knew about the minimum amount, and kept this rule but still got **Currency_total_amount_invalid**.
> 
> **How did I solve this?** For example if you want to **set amount** - 100 RUB, you must write **10000** and at the output you will **receive 100,00** RUB ;)

So, what should i do if i want to set amount 50 rub?

predicting the future:
"""
aiogram.utils.exceptions.CurrencyTotalAmountInvalid: Currency_total_amount_invalid
"""
