### ISSUE TITLE
Sending photos together

### ISSUE THREAD

**Issue by mast22** [eternnoir/pyTelegramBotAPI#596]
Hello, i was wondering if there is a way of sending pictures together. Something like a mobile app allows user to attach 2+ files into the same message. Sending them separately takes up too much space on a display. `send_photo(chat_id, ['FileID','FileID'])`

**Comment by Badiboy** [comment]
See 
`send_media_group`
https://core.telegram.org/bots/api#sendmediagroup

**Comment by SasukeSagara** [comment]
Hi, did you manage to solve this problem?
can you tell me what this code should look like?
I could not understand in what form to submit this parameter
Can you help me, please?)

**Comment by mast22** [comment]
I walk through my bots and couldn't find the solution, and cannot recall how i did it. But, you can try doing it without pyTelegramBotAPI and make a raw request. I need to say that i usually pre-load static images into bot and then retrieve them by their id. I believe something like this might work `https://api.telegram.org/bot123456:123456/sendMediaGroup?chat_id=<chat_id>&media=<pictureid1>&media=<pictureid2>`
