### ISSUE TITLE
How to retrieve all users who using a bot?

### ISSUE THREAD

**Issue by markolofsen** [eternnoir/pyTelegramBotAPI#597]
How to retrieve all users who using a bot?

**Comment by homfarnam** [comment]
So how we can save them to the database?

**Comment by art1415926535** [comment]
> So how we can save them to the database?

```python
@bot.message_handler(commands=['start'])
def send_welcome(message):
    conn = psycopg2.connect(connection)
    cursor = conn.cursor()
    cursor.execute(insert_user_sql, (message.chat.id,))
    conn.commit()

    bot.reply_to(message, "Howdy, how are you doing?")

```

**Comment by AndreiJirohHaliliDev2006** [comment]
> > So how we can save them to the database?
> 
> ```python
> @bot.message_handler(commands=['start'])
> def send_welcome(message):
>     conn = psycopg2.connect(connection)
>     cursor = conn.cursor()
>     cursor.execute(insert_user_sql, (message.chat.id,))
>     conn.commit()
> 
>     bot.reply_to(message, "Howdy, how are you doing?")
> ```

Can I use Firebase for this?

**Comment by alexshavelev44** [comment]
> > > So how we can save them to the database?
> > 
> > 
> > ```python
> > @bot.message_handler(commands=['start'])
> > def send_welcome(message):
> >     conn = psycopg2.connect(connection)
> >     cursor = conn.cursor()
> >     cursor.execute(insert_user_sql, (message.chat.id,))
> >     conn.commit()
> > 
> >     bot.reply_to(message, "Howdy, how are you doing?")
> > ```
> 
> Can I use Firebase for database storage? Is there are any other options?

you can use any storage you want. even a txt file

**Comment by AndreiJirohHaliliDev2006** [comment]
So, if this supports Firebase, how I can configure it?
