### ISSUE TITLE
Custom Keyboard

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#6]
Could you please provide example for custom keyboard layouts?
I'm making an array of buttons:
```python
newsTitles = 10 * ['MyButton']
news_keyboard = {'keyboard': newsTitles, 'one_time_keyboard': 'true'}
```
and then try to send message:
`tb.send_message(chatid, 'Choose news:', None, None, news_keyboard)`

but no custom keyboards are seen

**Comment by eternnoir** [comment]
This is my mistake. Because the reply_markup need a JSON-serialized object for a custom reply keyboard. So you should serialized the news_keyboard. I will let reply_markup support python dict at next update. 

And ReplyKeyboardMarkup keyboard field must be "Array of Array of String".


Example:
```python
import json
r1 = ['a','b','c']
r2 = ['d','e','f']
keyboard = [r1,r2]
news_keyboard = {'keyboard': keyboard, 'one_time_keyboard':True}
tb.send_message(chat_id, 'message', None, None, json.dumps(news_keyboard))
```

**Comment by Kondra007** [comment]
Still doesn't work for me :(
Used your answer as an example.

**Comment by eternnoir** [comment]
hmmm try to remove one_time_keyboard.

```python
import json
r1 = ['a','b','c']
r2 = ['d','e','f']
keyboard = [r1,r2]
news_keyboard = {'keyboard': keyboard}
tb.send_message(chat_id, 'message', None, None, json.dumps(news_keyboard))
```

**Comment by Kondra007** [comment]
Yep, that worked. Thanks!

**Comment by igoose1** [comment]
> I will let reply_markup support python dict at next update.

Not yet.
without `json.dumps` is `Bad Request: can\'t parse reply keyboard markup JSON object`
