### ISSUE TITLE
register_next_step_handler && two modules

### ISSUE THREAD

**Issue by Sanchoyzer** [eternnoir/pyTelegramBotAPI#602]
> Please answer these questions before submitting your issue. Thanks!
> 
> 1. What version of pyTelegramBotAPI are you using?
> pyTelegramBotAPI==3.6.6
> 
> 2. What OS are you using?
> Win7
> 
> 3. What version of python are you using?
> 3.7.1

There are 2 files:
**main.py**
```
import telebot as tb
import os
import controller


bot = tb.TeleBot(os.environ.get('TELEGRAM_TOKEN', None))


def step_get_name(message):
    controller.get_name_step(bot, message)


def step_get_age(message):
    controller.get_age_step(bot, message)


@bot.message_handler(commands=['start'])
def input_command_start(message):
    controller.command_start_handler(bot, message)


@bot.message_handler(content_types=["text"])
def input_text(message):
    controller.text_handler(bot, message)


@bot.callback_query_handler(func=lambda call: True)
def callback_query(callback):
    controller.callback_query_handler(bot, callback)


def main():
    bot.polling(none_stop=True)


if __name__ == '__main__':
    main()
```
and **controller.py**
```
import telebot as tb
import main


def command_start_handler(bot, message):
    markup = tb.types.InlineKeyboardMarkup(row_width=1)
    markup.add(tb.types.InlineKeyboardButton("caption1", callback_data="action1"))
    bot.send_message(message.chat.id, "Select", reply_markup=markup)


def text_handler(bot, message):
    bot.send_message(message.chat.id, message.text)


def get_name_step(bot, message):
    name = message.text
    msg = bot.send_message(message.chat.id, "what is you age?")
    bot.register_next_step_handler(msg, main.step_get_age)


def get_age_step(bot, message):
    age = message.text
    bot.send_message(message.chat.id, "ok")


def callback_query_handler(bot, callback):
    if callback.message is None:
        return
    if callback.data == "action1":
        msg = bot.send_message(callback.message.chat.id, "what is you name?")
        bot.register_next_step_handler(msg, main.step_get_name)
```
and the code

> bot.register_next_step_handler(msg, main.step_get_age)

works incorrect, because text_handler works instead step_get_age

test:
```
user:
/start

bot:
Select
[caption1]

user click

bot:
what is you name?

user:
a

bot:
what is you age?

user:
16

bot:
16
// but it should be "ok"
```

Why this handler isn't registering?

**Comment by plasticruler** [comment]
In case someone else needs this answer.

But in your `main` method just before you start `polling`, add the following equivalent code.

``
bot.enable_save_next_step_handlers(delay=1,filename='/home/pingu/uploaded_faces/step.save')`
bot.load_next_step_handlers(delay=1,filename='/home/pingu/uploaded_faces/reply.save')
``

**Comment by Sanchoyzer** [comment]
> In case someone else needs this answer.
> 
> But in your `main` method just before you start `polling`, add the following equivalent code.
> 
> `` bot.enable_save_next_step_handlers(delay=1,filename='/home/pingu/uploaded_faces/step.save')` bot.load_next_step_handlers(delay=1,filename='/home/pingu/uploaded_faces/reply.save') ``

Thanks, I'll try it later
