### ISSUE TITLE
Cannot send_video with url.

### ISSUE THREAD

**Issue by dyseo** [eternnoir/pyTelegramBotAPI#605]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.6
2. What OS are you using?
Linux localhost 3.18.*
3. What version of python are you using?
3.7.1

Why cannot send video with URL?
Url e.g https://www.youtube.com/embed/j2hiC9BmJlQ?enablejsapi=1&wmode=opaque&autoplay=1

With following code
`bot.send_video(msg.chat.id,url,caption='*Captions*',parse_mode='Markdown')`

**Comment by art1415926535** [comment]
You can just send message:
```python
bot.send_message(msg.chat.id, 'https://www.youtube.com/embed/j2hiC9BmJlQ?enablejsapi=1&wmode=opaque&autoplay=1')
```
Telegram will load the preview automatically.

`bot.send_video` used for local video files.
