### ISSUE TITLE
The write operation timed out

### ISSUE THREAD

**Issue by billydotexe** [eternnoir/pyTelegramBotAPI#607]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.6.6

2. What OS are you using? win10 & debian 9.5

3. What version of python are you using? 3.7.0

When I try to use the send_video or send_document methods it crash istantly giving Connection `aborted.', timeout('The write operation timed out')` as error, I tried with other methods like send_photo and it works fine.
I also tried the same code on my raspberry pi3 with raspbian and it worked with no problem

**Comment by art1415926535** [comment]
There is another way: to send url.

Example:
```python
bot.send_audio(CHAT_ID, 'https://my.server/c12e2ddd-48de-4c97-a2b0-729686509a6a.mp3')
```

**Comment by n1ckgorbachev** [comment]
Try timeout.

`bot.send_audio(chat_id, "audio.mp3", timeout=60)`

**Comment by MuhammadS05** [comment]
> Try timeout.
> 
> `bot.send_audio(chat_id, "audio.mp3", timeout=60)`

I tried this, but anyway gives the same error. 
Is any other solve exists for this situation?
