### ISSUE TITLE
can it be simplified?

### ISSUE THREAD

**Issue by goga1978** [eternnoir/pyTelegramBotAPI#611]
Please answer these questions before submitting your issue. Thanks!

1. pyTelegramBotAPI 3.6.6

2. Win 10

3. python 3.6

![555](https://user-images.githubusercontent.com/31812770/49604947-d1489780-f9c1-11e8-8815-149d451b494a.jpg)

![666](https://user-images.githubusercontent.com/31812770/49605017-01903600-f9c2-11e8-918d-0d66be12d287.jpg)

call message instead of msg
can it be simplified?

type(message ) = <class 'telebot.types.Message'>
type(msg) = <class 'telebot.types.Message'>
why write msg?

**Comment by goga1978** [comment]
type(message ) = <class 'telebot.types.Message'>
type(msg) = <class 'telebot.types.Message'>
why write msg?

**Comment by Badiboy** [comment]
These variants are equal. You can use any of them.

"Message" in register_xxx is used to get chat/user parametera.

**Comment by Badiboy** [comment]
These variants are equal. You can use any of them.

"Message" in register_xxx is used to get chat/user parametera.

**Comment by goga1978** [comment]
thank you!!! )
