### ISSUE TITLE
edit_message_text always returns True

### ISSUE THREAD

**Issue by kor0p** [eternnoir/pyTelegramBotAPI#613]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.6
2. What OS are you using?
Kubuntu 18.04 (plasma 5.12.7)
3. What version of python are you using?
python3.6.7, pypy3 (PyPy 5.8.0-beta0) (both have the same problem)

I set msg to result of bot.edit_message_text(...) and recieve:
`AttributeError: 'bool' object has no attribute 'text'` when trying get msg.text,
`<class 'bool'>` when getting type(msg)

From [documentation](https://core.telegram.org/bots/api#editmessagetext) :

> **editMessageText**
Use this method to edit text and game messages sent by the bot or via the bot (for inline bots). On success, if edited message is sent by the bot, the edited Message is returned, otherwise True is returned.

So, as I understand, bot must return "Message" (types.Message in telebot) on success, but bot returns True every time, even message was edited.
Please, fix this :disappointed:

**Comment by kor0p** [comment]
I tried get Message directly from url, but it also returns True instead Message entity. Anybody knows what to do?

**Comment by Badiboy** [comment]
I checked the library: it returns exactly what telegram returns. 
So if Telegram returns "True" instead if "Message"... Se la vie...

**Comment by kor0p** [comment]
I'm not working on bots for a while, but as I read from [documantation](https://core.telegram.org/bots/api#editmessagetext) Message entity must be returned
> **editMessageText**
Use this method to edit text and game messages sent by the bot or via the bot (for inline bots). On success, if edited message is sent by the bot, the edited Message is returned, otherwise True is returned.
