### ISSUE TITLE
Security issue: pickle is used to store data on disk

### ISSUE THREAD

**Issue by Tishka17** [eternnoir/pyTelegramBotAPI#614]
Pickle module is not secure and should not be used to save data to unsecure location. Data storage on disk is one of such locations.

However, pickle is used in to save "next_step_handlers" in Saver class (telebot/__init__.py)

Some info about pickle security issues: https://intoli.com/blog/dangerous-pickles/

**Comment by Badiboy** [comment]
Data storage on the local server disk is not less secure then to store bot code on this disk and other configs.

**Comment by Tishka17** [comment]
Code of bot is nornally lcoated on readonly storage, or accessible only by admin. On the other side data  and configs are written by user. Is this case, accessing to a storage by limited user can affect bot code (e.g. injecting backdoors) if it uses vulnerable file types. It is not dangerous with configs as they use json/yaml/ini/etc safe format, but is it for data stored as pickle
