### ISSUE TITLE
Replies with inline mode

### ISSUE THREAD

**Issue by artyemk** [eternnoir/pyTelegramBotAPI#626]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.6

2. What OS are you using?
Ubuntu 16.04

3. What version of python are you using?
3.5.2

Hello! Is it possible to answer to a reply message in inline mode? 

Example:
![photo_2019-02-27_23-43-02](https://user-images.githubusercontent.com/32482126/53514387-766a9c00-3ae9-11e9-84ea-c5739ab5ccb6.jpg)

I need to get a message text ("Test" in example above) and process it. Any ideas?

**Comment by kor0p** [comment]
Yes, it can be real. You need to edit_message_text and you **must** get your message, where **must** be reply_to, which be a Message with that text ("Test"). **But**, telegram actually don't return Message entity, as is wroten in Telegram API, so I create issue #613 to this, but it don't help :c
