### ISSUE TITLE
Send message without chat_Id

### ISSUE THREAD

**Issue by Arrmlet** [eternnoir/pyTelegramBotAPI#633]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Newest
2. What OS are you using?
Ubuntu
3. What version of python are you using?
3.6.2

I have created a telegram bot which send a messages, but it send the message only to one telegram account. How I can do this for all users which connected to my bot on telegram??

**Comment by Badiboy** [comment]
```
for chat_id in user_storage:
   bot.send_message(chat_id, message)
```
No other way.
PS. Yes, you need to collect and store all users wh visited your bot.

**Comment by Arrmlet** [comment]
@Badiboy Thanks for fast response, how I can collect all users which visited my bot( is there exist some api method for this?)

**Comment by Badiboy** [comment]
@Arrmlet Process /start command in bot (anyway you need to do this) and store all ids of users who called that command.

**Comment by Arrmlet** [comment]
@Badiboy Thank you
