### ISSUE TITLE
How to send a self-destruction message?

### ISSUE THREAD

**Issue by Spixmaster** [eternnoir/pyTelegramBotAPI#634]
How is it possible that a bot sends a message which will only be visible for ~30 seconds?

**Comment by Badiboy** [comment]
msg = bot.send_message(chat_id, message)
sleep(30)
bot.delete_message(...do not remember parameters...)

**Comment by Spixmaster** [comment]
@Badiboy but the bot needs to be responsible during that.
Could it be possible to get the message id of the sent message in order to delete it?
i already tried that but it did not work.
i work with the cpp api but listener onAnyMessage does not recognize sent messages of the bot

**Comment by Badiboy** [comment]
@Spixmaster "send_message" method returns the full Message object of the sent message. With its message_id and all other credetials.

**Comment by Spixmaster** [comment]
@Badiboy ooh. Thanks man. I thought it was a void function...
