### ISSUE TITLE
Group or channel message history

### ISSUE THREAD

**Issue by lebanonsky** [eternnoir/pyTelegramBotAPI#639]
Please answer these questions before submitting your issue. Thanks!

1. latest
2.Ubuntu 16.4
3. Python 3.6.5

Is it possible to access channel or group message history with pyTelegramBotAPI? There is such a command in Telegram API https://core.telegram.org/method/messages.getHistory  but can not seem to access it from Bot.

**Comment by goldenrump** [comment]
The link that you specified leads to api for applications. Here is a link to bots api: https://core.telegram.org/bots/api

**Comment by MasterGroosha** [comment]
Not supported in Bot API.

**Comment by plasticruler** [comment]
It is possible but the bot needs to have admin access to the group. Else the bot will only see messages that are commands.
