### ISSUE TITLE
get_updates() return a object inside a list, how to acess this objects?

### ISSUE THREAD

**Issue by EricGPTI** [eternnoir/pyTelegramBotAPI#642]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Answer: The latest.

2. What OS are you using?
Answer: Win 7

3. What version of python are you using?
Answer: Python 3.6.8

When I use the method get_update() I get return content as a list. Inside the list has some information of the type dict. Some values these keys are an object of the type telebot.

When I try access the parameter 'chat', for exemple,  I can't because it is an object telebot.

How I can get access to these?
![telebot](https://user-images.githubusercontent.com/17994386/55043151-8eafd700-5013-11e9-9b6c-617033c53262.PNG)

**Comment by Badiboy** [comment]
updates = **bot.**get_update()
... empty check skipped...
updates[0].message.chat.xxx

**Comment by EricGPTI** [comment]
Thanks Badiboy, it was a long time ago... I solve this question. More one time, thanks.
