### ISSUE TITLE
one user at a time

### ISSUE THREAD

**Issue by mehranj73** [eternnoir/pyTelegramBotAPI#648]
Windows 10, 3.6.6. Python 3.6
Hey, My bot changes captions for posts. When one user sends a bunch of posts at the same time to my bot, My bots will stop working for others until the bot finishes its job for the first user.
How can I fix this?
Thanks

**Comment by plasticruler** [comment]
Are you using polling or webhooks?

**Comment by mehranj73** [comment]
Polling. I used threads to solve my problem. Any other solutions?

**Comment by Badiboy** [comment]
> Polling. I used threads to solve my problem. Any other solutions?

No, this is the only solution. Because if you have ONE thread how you can do something in parallel? :)
