### ISSUE TITLE
Better documentation for Asynchronous Implementation

### ISSUE THREAD

**Issue by IRRN** [eternnoir/pyTelegramBotAPI#65]
I have trouble with current API documentation. I'm looking for a more clear example about asynchronous implementation or a better documentation.

appreciate that

**Comment by pevdh** [comment]
Can you be a bit more clear about what you are having trouble with, please? `AsyncTeleBot`? If that is the case, the documentation shows all there is to asynchronously sending API requests. There really is no difference between `TeleBot` and `AsyncTeleBot`, except that the first returns the request result directly while the latter returns an `AsyncTask` object. By using `AsyncTeleBot` you are already sending requests asynchronously, there is nothing more to be done on your side :)

**Comment by IRRN** [comment]
thanks, it work :D 
I think it's different ;)
but I can't understand these:
task = tb.get_me()
result = task.wait()

how can I use them? or what's the usage?

**Comment by pevdh** [comment]
This allows you to fire a request (`task = tb.get_me()`) and retrieve the result at another time in code (`result = task.wait()`)
