### ISSUE TITLE
Error while running bot: handle_messages is not defined

### ISSUE THREAD

**Issue by MIMAXUZ** [eternnoir/pyTelegramBotAPI#651]
The following error occurred while running the bot.
`C:\project>python main.py
Traceback (most recent call last):
  File "main.py", line 458, in <module>
    bot.set_update_listener(handle_messages)
NameError: name 'handle_messages' is not defined
`
And I have the following code.
`if __name__ == "__main__":
    bot.set_update_listener(handle_messages)
    bot.polling(none_stop=True)
`
Now I am using Windows 10, python version: 3.6.8 and latest version of telebot 3.3.6...
I am searching this problem from google, but I couldn't found anything...
How can I solve this problem?
I tested it with some of telebot versions but no solution.
Thanks!

**Comment by LuckyDenis** [comment]
Hello, judging by the error: `NameError: name 'handle_messages' is not defined`, you do not have the variable `handle_messages` in the global namespace. It also seems that the api is used is not quite correct, not entirely sure, but it seems that you are trying to call not a function but a function decorator directly.
