### ISSUE TITLE
How to add multiple buttons from a list?

### ISSUE THREAD

**Issue by glebgrig0** [eternnoir/pyTelegramBotAPI#652]
Hi, am doing a porject but I don't know how to to add multiple buttons from a list.
I have a list with button names but don't know how to use it, pls help.

**Comment by gingick** [comment]
this way how i add an inline buttons
list-names - list with button names

def func (list-names):
    inl_markup = types.InlineKeyboardMarkup()
    row_btns=[]
    for i in range(len(list-names)):
            row_btns.append(types.InlineKeyboardButton(text=list-names[i], callback_data="%s" %list-names[i]))
            inl_markup.add(row_btns[i])
    return inl_markup

**Comment by endemic-ru** [comment]
`
        data = [{'text':'Button text1','callback':'button_callback1'},
                   {'text': 'Button text2', 'callback': 'button_callback2'},
                   {'text': 'Button text3', 'callback': 'button_callback3'},
                   {'text': 'Button text4', 'callback': 'button_callback4'}]

        buttons=[]

        for button in data:
            #buttons.append(types.InlineKeyboardButton(text='💼 Groups stat', callback_data="groups_stat"))
            buttons.append(types.InlineKeyboardButton(text=button['text'], callback_data=button['callback']))

        markup.add(*buttons)
`
The main part is "*" at markup.add(*****buttons)
