### ISSUE TITLE
problem in register_next_step_handler function

### ISSUE THREAD

**Issue by IRRN** [eternnoir/pyTelegramBotAPI#66]
if I have a code something like this:
```python
@bot.message_handler(commands=['config'])
def set_config(message):
    bot.reply_to(message, 'enter password')
    bot.register_next_step_handler(message, check_password)

def check_password(message):
    if message.text == password:
        bot.reply_to(message, 'OK')
        bot.register_next_step_handler(message, next_step_func)
    else:
        bot.reply_to(message, 'Invalid password')
        bot.register_next_step_handler(message, check_password)
```
If a person send for my bot `/config` and when I ask them to type password maybe he/she send me `/config` again. so `set_config()` and `check_password()` called together.
how can I solve this problem? :)

**Comment by eternnoir** [comment]
In your case user reply ```/config``` again, You want only trigger set_config method?  

By design, it will trigger two handler is correct. next_step_handle will get next new message by this user. command handler will get message when message accord command.
