### ISSUE TITLE
How to send InlineKeyboardButton with URL from callback_query_handler?

### ISSUE THREAD

**Issue by ghost** [eternnoir/pyTelegramBotAPI#660]
```python
@bot.callback_query_handler(func=lambda call: True)
def callback_worker(call):
    tv_data = id_query(call.data)
    msg_body = tv_data['title'] + '\nRating: ' + tv_data['rating'] + '\nDate: ' + \
               tv_data['start_date'] + '\nStatus: ' + \
               tv_data['end_date'] + '\nDescription:\n' + tv_data['description']
    keyboard = types.InlineKeyboardMarkup()
    keyboard.add(types.InlineKeyboardButton(text='Watch', url=msg_body['iframe_src']))
    bot.send_photo(call.from_user.id, photo=tv_data['poster'], caption=msg_body, reply_markup=keyboard)
```

When i try to run this i have a error:
> 2019-06-10 00:18:15,322 (util.py:65 WorkerThread1) ERROR - TeleBot: "TypeError occurred, args=('string indices must be integers',)
> Traceback (most recent call last):
>   File "C:\Python37\lib\site-packages\telebot\util.py", line 59, in run
>     task(*args, **kwargs)
>   File "D:/Develop/tvsmotr_bot/main.py", line 17, in callback_worker
>     keyboard.add(types.InlineKeyboardButton(text='Watch', url=msg_body['iframe_src']))
> TypeError: string indices must be integers
How i can send InlineKeyboardButton with URL?

**Comment by Badiboy** [comment]
The error occurs because msg_body is STRING and you are tryin gto access it via TEXT index:
_msg_body['iframe_src']_

I think you mean _tv_data['iframe_src']_ here:
_url=msg_body['iframe_src']_
