### ISSUE TITLE
Problem with symblos "<" in text

### ISSUE THREAD

**Issue by HappyFX** [eternnoir/pyTelegramBotAPI#661]
`bot.send_message(message.chat.id, "<how>", parse_mode='HTML')`

> Bad Request: can\\\\\\'t parse entities: Unsupported start tag \\\\\\\\\"how\\\\\\\\\

**Comment by Badiboy** [comment]
It's not a problem. It's defined behaviour of the Telegram html parcer.

Use "&lt;" and "&gt;" instead of "<" and ">".

**Comment by HappyFX** [comment]
I think it's mistake what to use - they are equal...
