### ISSUE TITLE
AttributeError: 'AsyncTask' object has no attribute 'file_path'

### ISSUE THREAD

**Issue by adyckman** [eternnoir/pyTelegramBotAPI#665]
When a photo is placed in a chat, I am able to retrieve the File ID but I'm unable to call download_file() and I get the following error:

> 2019-06-17 11:33:58,386 (util.py:65 WorkerThread1) ERROR - TeleBot: "AttributeError occurred, args=("'AsyncTask' object has no attribute 'file_path'",)

My codeblock that invokes the downloading:

`@tb.message_handler(content_types=['photo'])`
`def echo_photo(message):`
`    fileID = message.photo[-1].file_id`
`    file_info = tb.get_file(fileID)`
`    downloaded_file = tb.download_file(file_info.file_path)`

Am I missing something?

1. What version of pyTelegramBotAPI are you using?
**pyTelegramBotAPI==3.6.6**
2. What OS are you using?
**Ubuntu 18.06**
3. What version of python are you using?
**3.6.7**

**Comment by chttrjeankr** [comment]
The problem here is 'AsyncTask' object doesn't have a file_path. Neither is it subscriptable. I tried this too. So to make it work, we have to use `file_info = file_info.wait()` after executing `file_info = tb.get_file(fileID)` before executing `downloaded_file = tb.download_file(file_info.file_path)`.

This is because `AsyncTeleBot` object is different than `TeleBot` object and it needs to use `.wait()` to fetch results.

**Comment by Badiboy** [comment]
@chttrjeankr Could you clear, what is wrong in wait() there?

**Comment by chttrjeankr** [comment]
> When a photo is placed in a chat, I am able to retrieve the File ID but I'm unable to call download_file()

I just proposed a working alternative to [this](https://github.com/eternnoir/pyTelegramBotAPI/issues/665#issue-457033442) problem by @adyckman. There is no issue with `.wait()` here. There's a need to use `.wait()` to be able to fetch and download files from `AsyncTeleBot`

**Comment by Badiboy** [comment]
@chttrjeankr OK, thanks. Seems that author is not here anymore.

**Comment by adyckman** [comment]
Thanks for checking into this; I found some other workaround that I can't even remember anymore.

**Comment by saniar-mf** [comment]
i had same problem,for solving that write like this:

fileID = message.photo[-1].file_id
file_info = tb.get_file(fileID)/
file_info = file_info.wait()
your_file = bt.download_file(file_info.file_path)
str_image = your_file.wait()   #it gives you string of image bytes
