### ISSUE TITLE
What is chat id and how do I find it?

### ISSUE THREAD

**Issue by jpcst** [eternnoir/pyTelegramBotAPI#669]
I want to use this code:
```
tb.send_message(chat_id, text)
```
But I don't know what I should put in chat_id.

**Comment by Blink128net** [comment]
Try it 
      bot.send_message(message.chat.id, text= "#text".format(cht, usr))

**Comment by Blink128net** [comment]
@bot.message_handler(commands=['start']) #--------Start Bot
def kalau(message): 
      usr = message.from_user.username
      cht = message.chat.id

**Comment by derf974** [comment]
Find @userinfobot on telegram and just start a conversation with him.
