### ISSUE TITLE
How can I schedule a message?

### ISSUE THREAD

**Issue by cosme12** [eternnoir/pyTelegramBotAPI#670]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? **3.6.6**
2. What OS are you using? **Windows 10**
3. What version of python are you using? **3.6.8**

Sorry for the silly question: 
I'm trying to send a message at a certain time, but unfortunatly, `bot.polling()` is an infinite loop. On the other hand `message_handler()` only works when there is an actual message being sent. Any idea of how I could accomplish this?

Thanks.

**Comment by cosme12** [comment]
Well, I could accomplish this by creating another thread and schedule the message there, while the main loop is working as normal. Not sure if this is the right way to do it, but it worked. If anybody knows the "proper" way to do, just leave a comment.
Thanks.

**Comment by Andrebcd4** [comment]
```
Well, I managed accomplish this by creating another thread and schedule the message there, while the main loop is working as normal. ```
Can you please help me figure out how to do that?

**Comment by wessells** [comment]
Hey, could you explain to me how you implemented multiple threads? I'm struggling with the same problem and can't find a solution anywhere.
