### ISSUE TITLE
Animation not supported?

### ISSUE THREAD

**Issue by TahaPY** [eternnoir/pyTelegramBotAPI#672]
1. What version of pyTelegramBotAPI are you using?
3.6.6
2. What OS are you using?
Ubuntu 18.4
3. What version of python are you using?
python3.7

Hello I need to get gifs in my bot but animation type is not added to the Message type
and I cant send animation with pytelegrambotapi

**Comment by chttrjeankr** [comment]
Bots can send animation through send_document() for the time being. But I noticed it gets converted to mp4 format. Say the bot wanted to send `example.gif`, the bot sends `example.gif.mp4` and the mime_type is as `video/mp4`

- version of pyTelegramBotAPI : 
- OS : Ubuntu 18.04.2
- python version : Python 3.7.3

Part of logs attached:

`{.....'animation': {'file_name': 'example.gif.mp4', 'mime_type': 'video/mp4', 'duration': 4, 'width': 246, 'height': 120, 'thumb': {'file_id': '-----------', 'file_size': 6321, 'width': 245, 'height': 120}, 'file_id': '------------------', 'file_size': 72441}, 'document': {'file_name': 'example.gif.mp4', 'mime_type': 'video/mp4', 'thumb': {'file_id': '----------------------', 'file_size': 6321, 'width': 245, 'height': 120}, 'file_id': '---------------', 'file_size': 72441}}}`

**Comment by Badiboy** [comment]
send_animation added in the latest commits.
