### ISSUE TITLE
How can I save photos, sent to bot?

### ISSUE THREAD

**Issue by gashish1n** [eternnoir/pyTelegramBotAPI#675]
Hey. Recently (2 hours ago) I started developing a bot that will help me in everyday life. There was a problem with the photos. Some messengers do not support sending photos. In such cases, use Imgur, but no, it is better to do something of your own. I need from the bot:

1. Got a photo
2. Upload it to a specific directory (network)
3. I changed the name of the photo and sent back the link.

I have already [found a page](https://github.com/php-telegram-bot/core/issues/386) on how to do this in PHP, but I am new to programming and do not know it. Can someone help?

**Comment by MalteToenjes** [comment]
this should help you:
```
@bot.message_handler(func=lambda m: True, content_types=['photo'])
def get_broadcast_picture(message):
	file_path = bot.get_file(message.photo[0].file_id).file_path
	file = bot.download_file(file_path)
	with open("python1.png", "wb") as code:
		code.write(file)
```

**Comment by gashish1n** [comment]
I brought this script to the point that I wanted. [Here it is](https://github.com/gashish1n/telegram-share-bot). Thank!

**Comment by gashish1n** [comment]
The fact is that I don’t see the point of creating a separate repository for this, so I will leave an answer to everyone who has such a question here. The link in the past message is not valid.

This is an example presented above. Using this method, you can save photos.
```python
@bot.message_handler(content_types=["photo"])
def photo(message):
    file_info = bot.get_file(message.photo[len(message.photo)-1].file_id)
    downloaded_file = bot.download_file(file_info.file_path)
    src = "/var/www/share" + file_info.file_path
    with open(src, "wb") as new_file:
        new_file.write(downloaded_file)
    bot.reply_to(message, "https:/site.com/" + src.strip("/var/www/share"))
```
Now about the music, videos and documents. All three types are identical. Instead of `message.audio`, can be replaced by ` message.video` or `message.document`. And don't forget about `content_types`.
```python
def other_type(message):
    file_info = bot.get_file(message.audio.file_id)
    downloaded_file = bot.download_file(file_info.file_path)
    src = "/var/www/share" + file_info.file_path
    with open(src, "wb") as new_file:
        new_file.write(downloaded_file)
    bot.reply_to(message, "https:/site.com/" + src.strip("/var/www/share"))
```
Telegram automatically names the file: `file_0.jpg`,` file_1.mp3`, `file_2.mp4`. Thanks!

**Comment by javadnematollahi** [comment]
> this should help you:
> 
> ```
> @bot.message_handler(func=lambda m: True, content_types=['photo'])
> def get_broadcast_picture(message):
> 	file_path = bot.get_file(message.photo[0].file_id).file_path
> 	file = bot.download_file(file_path)
> 	with open("python1.png", "wb") as code:
> 		code.write(file)
> ```

thank you for this good answer. I looked all net for this example code for getting photo from telegram bot.

**Comment by javadnematollahi** [comment]
> The fact is that I don’t see the point of creating a separate repository for this, so I will leave an answer to everyone who has such a question here. The link in the past message is not valid.
> 
> This is an example presented above. Using this method, you can save photos.
> 
> ```python
> @bot.message_handler(content_types = ["photo"])
> def photo(message):
>     file_info = bot.get_file(message.photo[len(message.photo)-1].file_id)
>     downloaded_file = bot.download_file(file_info.file_path)
>     src = "/var/www/share" + file_info.file_path
>     with open(src, "wb") as new_file:
>         new_file.write(downloaded_file)
>     bot.reply_to(message, "https:/site.com/" + src.strip("/var/www/share"))
> ```
> 
> Now about the music, videos and documents. All three types are identical. Instead of `message.audio`, can be replaced by ` message.video` or `message.document`. And don't forget about `content_types`.
> 
> ```python
> def other_type(message):
>     file_info = bot.get_file(message.audio.file_id)
>     downloaded_file = bot.download_file(file_info.file_path)
>     src = "/var/www/share" + file_info.file_path
>     with open(src, "wb") as new_file:
>         new_file.write(downloaded_file)
>     bot.reply_to(message, "https:/site.com/" + src.strip("/var/www/share"))
> ```
> 
> Telegram automatically names the file: `file_0.jpg`,` file_1.mp3`, `file_2.mp4`. Thanks!

thank you for your complete answer, because I used your code and I can save image.
