### ISSUE TITLE
Two OS, basically the same code, one works and the other does not.

### ISSUE THREAD

**Issue by jpcst** [eternnoir/pyTelegramBotAPI#679]
1. What version of pyTelegramBotAPI are you using?
Both 3.6.6 I believe
2. What OS are you using?
Windows 10 and Ubuntu 18
3. What version of python are you using?
3.6.0 on Windows and 3.6.8 for Ubuntu

Here's the code that's running on Windows:
```
import telebot

dirBot = 'C:/Users/jp/Desktop/scrape/bot.txt'
with open(dirBot, 'r') as f:
    api = f.read()

tb = telebot.TeleBot(api)
print(tb.get_me())
```
The output is, as expected:
```
{'id': 870812039, 'is_bot': True, 'first_name': 'SCPR', 'username': 'oScpr_bot', 'last_name': None, 'language_code': None}
```

The code on Ubuntu is:
```
import telebot

dirBot = '/home/jpcst/scrape-valores/bot.txt'
with open(dirBot, 'r') as f:
    api = f.read()

tb = telebot.TeleBot(api)
print(tb.get_me())
```

But the output is this:
```
{'ok': False, 'error': 'Got unexpected response. (404) - {"ok":false,"error_code":404,"description":"Not Found"}'}
```
Therefore I can't control the bot on Linux.

**Comment by goldenrump** [comment]
Check what you get from dirBot through printing(dirBot). Maybe they have wrong/unnecessary characters

**Comment by jpcst** [comment]
> 
> 
> Check what you get from dirBot through printing(dirBot). Maybe they have wrong/unnecessary characters

The same problem happens even if I use the api code directly into the argument, the exact same code runs fine on Windows. I really have no idea what's causing it.

**Comment by mackhossain** [comment]
in ubuntu just add this simple line


import telebot

dirBot = '/home/jpcst/scrape-valores/bot.txt'
with open(dirBot, 'r') as f:
    api = f.read()

tb = telebot.TeleBot(api)
tb.config['api_key']=api     # Just add this line  :) 
print(tb.get_me())
