### ISSUE TITLE
Post to channel & add button in the post

### ISSUE THREAD

**Issue by DrMartiner** [eternnoir/pyTelegramBotAPI#681]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.6

2. What OS are you using?
Ubuntu

3. What version of python are you using?
3.6.6

Hi there,

- How can I send a message to channel?
- May I add a button in a post on a channel?

Best regards

**Comment by wd** [comment]
I have found the way. 

Fist you need to find you channel's id , [ref](https://stackoverflow.com/questions/33858927/how-to-obtain-the-chat-id-of-a-private-telegram-channel)

A channel id is something like '-1001252390347', use `bot.send_message('-1001252390347', 'test')` to send the message.

I think you also need to add the bot to your channel, haven't test it.
