### ISSUE TITLE
problem with forward_message - infinity wait

### ISSUE THREAD

**Issue by vikingUnet** [eternnoir/pyTelegramBotAPI#689]
pyTelegramBotAPI 3.6.6
OS Ubuntu 16
python 3.6.7

Sometimes i have problem with call forward_message: i am waiting for response infinity time, then i get responce usually with some error (like MESSAGE_ID_INVALID). Can i set timeout limit on this function call? I can run this functuin in new thread, but there is threads limit in os and i dislike this solution. Anyone help me? Thanks!

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/848

(I know that 1 year had passed. :) )
