### ISSUE TITLE
Next_Step_Handler doesnt work in channels

### ISSUE THREAD

**Issue by DonPepeSun** [eternnoir/pyTelegramBotAPI#692]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
 3.6.6
2. What OS are you using?
Windows 10
3. What version of python are you using?
3.7.4
_____________________________________________________

When i use "next_step_handler" in a group, it works. But it doesnt happend when i do this in a channel. This is my code:

`import telebot`
`import time`
`import os`

`bot_token = 'TOKEN'`
`bot = telebot.TeleBot(token=bot_token)`

`persona=[]`

`@bot.channel_post_handler(func=lambda m:True)` ''' with @bot.message.handler(...) work all in a group'''
`def proceso_codigo(message):`
`    mci=message.chat.id`
`    CodTrans=message.text`
`    persona.insert(0,f'{CodTrans}')`
`    Completo=bot.send_message(mci,'Ahora envie su nombre:')`
`    bot.register_next_step_handler(Completo,proceso_nombre)`

`def proceso_nombre(message):`
`    mci=message.chat.id`
`    CodNomb=message.text`
`    persona.insert(1,f'{CodNomb}')`

`    print(f'Codigo es {persona[0]} y la persona es {persona[1]}')`
    
    
`while True:`
`    try:`
`        bot.polling()`
`    except Exception:`
`        time.sleep(15)`

In a channel, "@bot.channel_post_handler" works getting the first message but "next_step_handler" not

**Comment by Badiboy** [comment]
next_step_handler is bind to chat id. It seem to be a bad practice using it n groups / channels...
