### ISSUE TITLE
confilect 

### ISSUE THREAD

**Issue by A4E45** [eternnoir/pyTelegramBotAPI#695]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.6
2. What OS are you using?
linux
3. What version of python are you using?
3.7.4
hi i have go and conflict error :

 (__init__.py:417 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']"

**Comment by keshamin** [comment]
@A4E45 Usually I faced this error when indeed there were a few bots running and polling the API at the same time. Check this first, maybe some is running in the background.

If not, then maybe your Bot Token is leaked and is used by somebody else. Request a new one from BotFather.
