### ISSUE TITLE
ReplyKeyboardMarkup doesn't allow for loops?

### ISSUE THREAD

**Issue by wessells** [eternnoir/pyTelegramBotAPI#697]
1. pyTelegramBotAPI-3.6.6-py3.7.egg-info
2. Windows 10
3. Python 3.7

So I noticed that when I used a loop for ReplyKeyBoardMarkup and a specific row_width, I would just get back a list of buttons that were below one another.

```
length_of_task = types.ReplyKeyboardMarkup(row_width = 3)
for i in [5, 15, 20, 30, 40, 60]:
    item = types.KeyboardButton(str(i))
    length_of_task.add(item)
``` 

But when I added each individually, it worked as I thought it would.

I was just wondering why this is the case.

**Comment by keshamin** [comment]
This is how `add()` method works. Every time you can it it adds a new row.
To reach your goal here you need to pass multiple buttons to `add()`, like this:
```
length_of_task = tb.types.ReplyKeyboardMarkup(row_width = 3)
length_of_task.add(*[KeyboardButton(str(i)) for i in (5, 15, 20, 30, 40, 60)])
```

You can simplify it, if the code seems overloaded:
```
length_of_task = tb.types.ReplyKeyboardMarkup(row_width = 3)
options = (5, 15, 20, 30, 40, 60)
buttons = [KeyboardButton(str(i)) for i in options]
length_of_task.add(*buttons)
```
