### ISSUE TITLE
How I can make underline and strikeout text?

### ISSUE THREAD

**Issue by walkman99** [eternnoir/pyTelegramBotAPI#699]
Python 3.6
I try to use 
`bot.send_message('-' + tg_channel, '<u>Text</u>', parse_mode='HTML')`
and got exception:
_"[b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Unsupported start tag \\"u\\" at byte offset 0"}']"_
I read telegram API here: https://core.telegram.org/api/entities

**Comment by keshamin** [comment]
Telegram Bot API doesn't support underline or strikeout formatting. All supported formatting with examples is here:
https://core.telegram.org/bots/api#formatting-options
