### ISSUE TITLE
Message without username

### ISSUE THREAD

**Issue by GabrielRF** [eternnoir/pyTelegramBotAPI#7]
First of all, thank you for the API! It's really useful!

I've noticed that the bot won't send messages (photos/files etc) to people that doesn't have an username.
As far as I read, it's a limitation from the Telegram API. Can you confirm that, please?

**Comment by pevdh** [comment]
I just tested it myself, and it seems to work for me. Where did you find this information claiming that you can't send messages to people without usernames? Can you provide some source code?

**Comment by GabrielRF** [comment]
I guess ```git pull``` solved the problem
