### ISSUE TITLE
problem with threads

### ISSUE THREAD

**Issue by CalevGrad** [eternnoir/pyTelegramBotAPI#700]
Python 3.6.8
PyTelegramBotAPI 3.6.6
If you write a message to the bot when it is turned off and then turn it on, it responds to every message that is written. Also, this problem occurs if you manage to write several messages to the bot while it is processing one of them. I think the problem is that the bot starts processing for each message, and not, for example, the last.
[The first image where I wrote to the bot when it was turned off](https://yadi.sk/i/kTpAWW_P9fIrKw)
[The second image, where I managed to write several messages to the bot at once](https://yadi.sk/i/lSaP9BuwH16RVQ)

**Comment by keshamin** [comment]
@CalevGrad What exactly seems incorrect to you? Why would bot ignore some messages sent to it?
