### ISSUE TITLE
Allowing register_next_step_handler to run only once

### ISSUE THREAD

**Issue by ronka** [eternnoir/pyTelegramBotAPI#702]
pyTelegramBotAPI version: 3.6.6
OS: Windows 10
Python version: 3.7.4

I am using `register_next_step_handler` as described in [this example](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/step_example.py),  
The function  `register_next_step_handler` is connected to a button, it works great but the problem is if the button is pressed multiple times it register the next step multiple times.  
I tried to add a simple boolean flag but it didnt help.

What can I do inorder to process the step only once?

**Comment by keshamin** [comment]
@ronka Did you use the keyboard button or inline button?
Can you show the example of the code and the example of undesired behavior?

**Comment by Badiboy** [comment]
You can use
clear_step_handler(message)
before 
register_next_step_handler(message)
To ensure it will be the only one.
