### ISSUE TITLE
telebot handler that is up and running

### ISSUE THREAD

**Issue by HappyFX** [eternnoir/pyTelegramBotAPI#704]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
latest
2. What OS are you using?
centos 7
3. What version of python are you using?
python 3.6.8

Any way to add decorator function so I can set up in etcd flag, that bot is still up and running?
something like:

```
@bot.get_updates()
def keepalive():
    print('ALIVE')
```

**Comment by HappyFX** [comment]
why closed?

**Comment by Badiboy** [comment]
No positive answer on your question. No such decorators.
