### ISSUE TITLE
DELETE message

### ISSUE THREAD

**Issue by danielpetrato** [eternnoir/pyTelegramBotAPI#706]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI-3.6.6-py3.7.egg-info
2. What OS are you using?
Windows 10
3. What version of python are you using?
Python 3.7

Is there any function to delete the last message sent by the bot?

**Comment by keshamin** [comment]
@danielpetrato yes, `TeleBot` has the following method to delete messages:
`def delete_message(self, chat_id, message_id):`

if you need to delete the last message you sent, just remember the IDs somewhere and use the method:
```
# it's just a dirty example for a demo:
msg = bot.send_message(<CHAT_ID>, 'Message goes here')
bot.last_message_sent = msg.chat.id, msg.message_id

# when you need to delete that last message, just call:
bot.delete_message(*bot.last_message_sent)
```
The above example stores the last message over all users. If you need to store the last message sent to each particular user, you need to store IDS per user:
```
bot.last_message_sent = {}
msg = bot.send_message(<CHAT_ID>, 'Message goes here')
bot.last_message_sent[msg.chat.id] = msg.message_id
```
