### ISSUE TITLE
Changing API_URL does not work

### ISSUE THREAD

**Issue by svetlyak40wt** [eternnoir/pyTelegramBotAPI#707]
Change introduced in commit https://github.com/eternnoir/pyTelegramBotAPI/commit/6fb9e1838541c88400c02a1cda46571d3fe08018 does not work.

This does not works for me because python catches a variable's value in a closure when it reads a function definition. And it is impossible to change default value by settings API_URL after the apihelper.py was loaded.

Here is a short example:

```python
In [11]: API_URL = None

In [12]: def do(url=API_URL):
    ...:     return url
    ...:

In [13]: do()

In [14]: # it returned None

In [15]: API_URL = 'foo'

In [16]: do()

In [17]: # again, it returned none, because it was remembered
```

To make it work, it is better to make api_url a bot's attribute and to pass it to each function which calls `_make_request`.

**Comment by svetlyak40wt** [comment]
But probably, the much simpler solution would be replacing:

```python
API_URL = None
```

with:

```python
API_URL = os.environ.get('API_URL')
```

**Comment by svetlyak40wt** [comment]
@xxsokolov what do you think?

**Comment by Badiboy** [comment]
There was an error in API_URL processing: it was overriden in any case. In the latest commits it should work as planned. If no - please, reopen the issue or create new one.
