### ISSUE TITLE
Problem with send_media_group()

### ISSUE THREAD

**Issue by walkman99** [eternnoir/pyTelegramBotAPI#714]
If I sending video and photos as album from desktop client, I sent one message. But if I sending with send_media_group(), I got two instead one: video and photos in separate messages.
Please, fix it to "natural" method.

**Comment by BLUE-DEVIL1134** [comment]
its because too many things cant be sent at once in a group

**Comment by Badiboy** [comment]
Fuction test_send_media_group_local_files from library tests works fine for me.

```
    def test_send_media_group_local_files(self):
        photo = open('../examples/detailed_example/kitten.jpg', 'rb')
        video = open('./test_data/test_video.mp4', 'rb')
        tb = telebot.TeleBot(TOKEN)
        medias = [types.InputMediaPhoto(photo, "View"),
                  types.InputMediaVideo(video)]
        result = tb.send_media_group(CHAT_ID, medias)

```

![image](https://user-images.githubusercontent.com/5613421/104051431-28507480-51f9-11eb-86d8-f7bf7b3d1f51.png)

_PS. I know that this issue had been posted loooong ago._
