### ISSUE TITLE
How to find the message id from the last message my bot sent?

### ISSUE THREAD

**Issue by jpcst** [eternnoir/pyTelegramBotAPI#716]
I'm trying to use the function to pin a message that my bot sent, but one of the arguments must be the id of this message, how can I find it? Here's a part of the code:

```
tb = telebot.TeleBot(api_bot)
tb.send_message(group_id, 'Test!')
tb.pin_chat_message(group_id, <MESSAGE ID HERE>)
```

This id will also change over time, because the bot will send multiples texts over the day and always pin the last one.

Also, how can I unpin it afterwords?
Thanks.

**Comment by keshamin** [comment]
@jpcst `send_message()` method returns a an instance of `Message` class. 
All you need is:
```
tb = telebot.TeleBot(api_bot)
message = tb.send_message(group_id, 'Test!')
tb.pin_chat_message(group_id, message.message_id)
```
