### ISSUE TITLE
remove InlineKeyboardButton from InlineKeyboardMarkup

### ISSUE THREAD

**Issue by eliran1314** [eternnoir/pyTelegramBotAPI#717]
Hi,
there is any way to remove InlineKeyboardButton from InlineKeyboardMarkup?
I am adding dynamically buttons and i want to remove and add while running, it is possible?

Thanks

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using - pyTelegramBotAPI 3.6.6

2. What OS are you using - Windows 10

3. What version of python are you using - 3.8.0

**Comment by Badiboy** [comment]
Inline keyboard buttons are storead as TUPLEs. Tuples cannot be modified, so you only can create new tuple instead of old tuple without unneeded button.

**Comment by eliran1314** [comment]
Hi,
Thanks for the answer.
this is the part of the code:
keyboard = types.InlineKeyboardMarkup()
keyboard.add(types.InlineKeyboardButton("1", callback_data="1"))

I want for example that the next time I will call the keyboard it will one option with different parameters

how can I create new TUPLE and insert it to the keyboard without the previous TUPLE ?

thanks a lot

**Comment by Badiboy** [comment]
https://www.google.com/search?q=python+work+with+tuples&oq=python+work+with+tup&aqs=chrome.1.69i64j0l2j69i57j0.5290j0j1&sourceid=chrome&ie=UTF-8
