### ISSUE TITLE
not able to get respond as json

### ISSUE THREAD

**Issue by noideaw** [eternnoir/pyTelegramBotAPI#719]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.6.6

2. What OS are you using? ubuntu 16.04

3. What version of python are you using? 3.5.2

I want to get the respond of telegram server for any action I do by the library e.g sending message, kick users, etc.
how is it possible?
I need it to use in the way below(for example variable j is the respond of server):
```
j = bot.kick_chat_member(message.chat.id, user_id)
if j.ok == True:
     do something
else:
     do another thing
```

**Comment by Badiboy** [comment]
Try

```
j = bot.kick_chat_member(message.chat.id, user_id)
if j['ok']:
     do something
else:
     do another thing
```

Cannot check right now, but should be like this.
