### ISSUE TITLE
Maybe these ones were forgotten and should be replaced for example by ‘mickey’, ‘mouse’ :-)

### ISSUE THREAD

**Issue by pantunes** [eternnoir/pyTelegramBotAPI#721]
https://github.com/eternnoir/pyTelegramBotAPI/blob/e62eeb7ff2a6c23f2a30dff38b19d76d62e45eb3/examples/detailed_example/detailed_example.py#L23

**Comment by Badiboy** [comment]
Thanks. 

https://github.com/eternnoir/pyTelegramBotAPI/pull/726
