### ISSUE TITLE
No ability to use replay_markup with send_media_group

### ISSUE THREAD

**Issue by VladGavriuk** [eternnoir/pyTelegramBotAPI#729]
I am programming a bot that grabs some photos from Internet and sends to channel. When I am trying to add Like/Dislike buttons via `InlineKeyboardMarkup` but I discovered that it cannot be done with `bot.send_media_group(chat_id, img_urls, reply_markup=gen_markup())`. It raises `TypeError: send_media_group() got an unexpected keyword argument 'reply_markup'`. Is it 
a disadvantage of whole Telegram official API or just this library? If it can be done, please provide a code example.

1. pyTelegramBotAPI version: `3.6.6`
2. OS: `Linux Ubuntu 18.04.3` LTS; kernel version - 5.0.0-37-generic;
3. Python version: `3.6.9`

**Comment by Badiboy** [comment]
Is it really easier to open an issue and write the question, then to open a Telegram Bot API and read yourself?

https://core.telegram.org/bots/api#sendmediagroup

**Comment by VladGavriuk** [comment]
Sorry for dumb qu
