### ISSUE TITLE
telegram bot don't answer

### ISSUE THREAD

**Issue by cruim** [eternnoir/pyTelegramBotAPI#730]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Last version, install with pip.

2. What OS are you using?
Ubuntu 18.04

3. What version of python are you using?
Python 3.6.7

I add ssl certificates from certbot. And try to use [this example](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/webhook_examples/webhook_flask_echo_bot.py) with my token, port, url and others. I run script and then check state with this link `https://api.telegram.org/bot827929874:AAELa-Dl6pYFM_test_test/getWebhookInfo` and get this answer `{"ok":true,"result":{"url":"https://my_site.com:88/827929874:AAELa-Dl6pYFM_test_test/","has_custom_certificate":true,"pending_update_count":32,"max_connections":40}}`. I see that now 32 messages is in a queue waiting. Why bot didn't response?

**Comment by Badiboy** [comment]
You need to set
WEBHOOK_LISTEN = WEBHOOK_HOST
if you have no web-servers on your host.

Or to set up your web-server (apache / nginx / etc) to forward calls from
"your site port 88" to localhost.

**Comment by cruim** [comment]
this is my nginx config (/etc/nginx/sites-available/mysite.com)
`server {
        listen 88 default ssl;
        server_name mysite.com www.mysite.com;
        ssl_certificate /etc/letsencrypt/live/mysite.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mysite.com/privkey.pem;
        access_log /var/log/nginx_access.log;
        error_log /var/log/ngingx_error.log;
        if ($scheme = http) {
            return 301 https://$server_name$request_uri;
        }
    location / {
        include uwsgi_params;
    }
}`
What else I have to add in config?

**Comment by Badiboy** [comment]
> forward calls from "your site port 88" to localhost.

AFAIK you configure nginx to LISTEN your port, so nginx answers to Telegram, not your bot. But I'm not sure. )

**Comment by cruim** [comment]
> > forward calls from "your site port 88" to localhost.

Could add some example?

**Comment by Badiboy** [comment]
https://www.google.com/search?q=nginx+port+forwarding+localhost

**Comment by cruim** [comment]
I rewrite config to
```
server {
        listen 80;
        listen 88 ssl;

        server_name site.com www.site.com;
        ssl_certificate /etc/letsencrypt/live/site.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/site.com/privkey.pem;
        access_log /var/log/nginx_access.log;
        error_log /var/log/ngingx_error.log;
    location / {
    proxy_redirect     off;
    proxy_set_header   Host $http_host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Host $server_name;
    proxy_pass http://localhost:8001/;
    }
}
```

**Comment by cruim** [comment]
Удалил созданный мною конфиг. Оставил тот , который был автоматически сгенерирован certbot'ом.
```
server{
        location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
}



    listen 80; # managed by Certbot

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/site.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/site.comprivkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
```
В скрипте также поменял порт на 443. Пока та же ошибка `Connection timed out`  Если отправить запрос на `https://api.telegram.org/bot<Token>`

**Comment by Badiboy** [comment]
> Change port to 443 in python script.

> proxy_pass http://127.0.0.1:443;

?

**Comment by cruim** [comment]
Вместо `WEBHOOK_SSL_CERT = "/etc/letsencrypt/live/YOUR.DOMAIN/cert.pem"` указал `/etc/letsencrypt/live/YOUR.DOMAIN/fullchain.pem`. Бот стал отвечать
