### ISSUE TITLE
two instances of bot running at the same time

### ISSUE THREAD

**Issue by ronaldylf** [eternnoir/pyTelegramBotAPI#733]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
the last version
2. What OS are you using?
ubuntu
3. What version of python are you using?
3.6.8 64bit

there is some way to run 2 bots at the same time ?
i really have to make that

**Comment by Badiboy** [comment]
Only one instance can receive updates: if you try to poll from two instances, Telegram will return error. If one bot is "write only" - it's possible.
