### ISSUE TITLE
New release in PyPi

### ISSUE THREAD

**Issue by keshamin** [eternnoir/pyTelegramBotAPI#734]
Hello!
I've been using this library for years now. I've even made a little contribution to it. I'm interested if it's planned to release new versions to PyPi? The last release was back in September 2018 and there've been a lot of good pull requests merged into master since then.
If currently nobody can be responsible for that, I can help and participate.

**Comment by Badiboy** [comment]
Hi.
I think we can make a v3.6.7 release soon.
Frankly speaking, there are no significant updates in all theese commits: just some minor updates and pull history clearing.
I'd set up the current version on my production server and it works fine.

**Comment by keshamin** [comment]
@Badiboy In my case I cannot use the release version because of the bug I fixed by my small pull request. Some attachment-related method (don't remember which one right now) just fails with AttributeError. I can find the PR and give you a link of needed.

This only is a reason to release a fix in my opinion, because it makes a part of functionality completely unavailable.

**Comment by Badiboy** [comment]
Voila: https://github.com/eternnoir/pyTelegramBotAPI/releases/tag/3.6.7
Thanks to @eternnoir :)

**Comment by Badiboy** [comment]
Voila: https://pypi.org/project/pyTelegramBotAPI/3.6.7/

Thanks to @eternnoir .
