### ISSUE TITLE
TeleBot:A request to the Telegram API was unsuccessful

### ISSUE THREAD

**Issue by balzer82** [eternnoir/pyTelegramBotAPI#737]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI==3.6.7

2. What OS are you using?
Ubuntu 18.04.

3. What version of python are you using?
3.7

After some hours of running the Bot in `.polling()` mode, there is some issue with the Telegram API but then the Bot stops working with

```
(util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 500 Internal Server Error. Response body:\n[b\'{"ok":false,"error_code":500,"description":"Internal server error: restart"}\']',)
```

Is there a way to catch this exception so the bot doesn't stop polling?

**Comment by Rayanfer32** [comment]
Using supervisor is bad ... i used try except loop but still it will raise many exceptions ... and bot terminates

**Comment by paritosh3006** [comment]
I got this error:
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The Server returned HTTP 409 conflict.

**Comment by paritosh3006** [comment]
> > I got this error:
> > telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The Server returned HTTP 409 conflict.
> 
> the whole message is :
> 
> ```
> {
> 
>     "ok": false,
>     "error_code": 409,
>     "description": "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
> 
> }
> ```
> 
> it because you run one more instance request to 'getUpdates'

Please tell me how to solve this issue.
Thanks in advance

**Comment by paritosh3006** [comment]
> > > > I got this error:
> > > > telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The Server returned HTTP 409 conflict.
> > > 
> > > 
> > > the whole message is :
> > > ```
> > > {
> > > 
> > >     "ok": false,
> > >     "error_code": 409,
> > >     "description": "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
> > > 
> > > }
> > > ```
> > > 
> > > 
> > > it because you run one more instance request to 'getUpdates'
> > 
> > 
> > Please tell me how to solve this issue.
> > Thanks in advance
> 
> 1. you run one more program instance at the same time, check the process on the server, kill one of them.
> 2. maybe someone stole the token of your bot, chat with botfather, revoke the token, then run another instance using the new token.
I use this link to try to access to my bot: https://api.telegram.org/botToken/getUpdates:
then I got this one : 
{"ok":true,"result":{"id":1032572032,"is_bot":true,"first_name":"Rest_Bot","username":"rest_chatbot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":true}}

**Comment by paritosh3006** [comment]
> > > > > > I got this error:
> > > > > > telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The Server returned HTTP 409 conflict.
> > > > > 
> > > > > 
> > > > > the whole message is :
> > > > > ```
> > > > > {
> > > > > 
> > > > >     "ok": false,
> > > > >     "error_code": 409,
> > > > >     "description": "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
> > > > > 
> > > > > }
> > > > > ```
> > > > > 
> > > > > 
> > > > > it because you run one more instance request to 'getUpdates'
> > > > 
> > > > 
> > > > Please tell me how to solve this issue.
> > > > Thanks in advance
> > > 
> > > 
> > > 
> > > 1. you run one more program instance at the same time, check the process on the server, kill one of them.
> > > 2. maybe someone stole the token of your bot, chat with botfather, revoke the token, then run another instance using the new token.
> > >    I use this link to try to access to my bot: https://api.telegram.org/botToken/getUpdates:
> > >    then I got this one :
> > >    {"ok":true,"result":{"id":1032572032,"is_bot":true,"first_name":"Rest_Bot","username":"rest_chatbot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":true}}
> 
> the message, looks like it works fine.

Yeah, but still getting same error..

**Comment by paritosh3006** [comment]
> > > > > > > > I got this error:
> > > > > > > > telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The Server returned HTTP 409 conflict.
> > > > > > > 
> > > > > > > 
> > > > > > > the whole message is :
> > > > > > > ```
> > > > > > > {
> > > > > > > 
> > > > > > >     "ok": false,
> > > > > > >     "error_code": 409,
> > > > > > >     "description": "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"
> > > > > > > 
> > > > > > > }
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > it because you run one more instance request to 'getUpdates'
> > > > > > 
> > > > > > 
> > > > > > Please tell me how to solve this issue.
> > > > > > Thanks in advance
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. you run one more program instance at the same time, check the process on the server, kill one of them.
> > > > > 2. maybe someone stole the token of your bot, chat with botfather, revoke the token, then run another instance using the new token.
> > > > >    I use this link to try to access to my bot: https://api.telegram.org/botToken/getUpdates:
> > > > >    then I got this one :
> > > > >    {"ok":true,"result":{"id":1032572032,"is_bot":true,"first_name":"Rest_Bot","username":"rest_chatbot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":true}}
> > > 
> > > 
> > > the message, looks like it works fine.
> > 
> > 
> > Yeah, but still getting same error..
> 
> That's weird.
> Are you sure you are request to 'getUpdates' but not 'getMe', 'getMe' won't result to '409 Conflict'.

Ohh. Actually getMe gives:
{"ok":true,"result":{"id":1032572032,"is_bot":true,"first_name":"Rest_Bot","username":"rest_chatbot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":true}}

and getUpdates gives:
{"ok":true,"result":[]}
