### ISSUE TITLE
MTProto

### ISSUE THREAD

**Issue by nabbat** [eternnoir/pyTelegramBotAPI#742]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.7

2. What OS are you using?
Windows server

3. What version of python are you using?
3.6

Please add MTProto support to apihelper.

**Comment by brightening-eyes** [comment]
hi,
PyTelegramBotAPI uses the HTTP version of the telegram which is made for bots.
if you want to use mtproto, consider using something like telethon
