### ISSUE TITLE
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The Server returned HTTP 409 conflict

### ISSUE THREAD

**Issue by paritosh3006** [eternnoir/pyTelegramBotAPI#745]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 
3.6.7

2. What OS are you using?
Windows 10
3. What version of python are you using?
3.5

**Comment by paritosh3006** [comment]
telebot.apihelper.ApiException A request to the Telegram API was 
 unsuccessful. The Server returned HTTP 409 conflict
 Telegram API was unsuccessful. The server returned HTTP 409 Conflict. 
 Response body:
 [b'{"ok":false,"error_code":409,"description":"Conflict:  
 terminated by other getUpdates request; make sure that only one bot 
 instance is running"}']

 ERROR - TeleBot: "A request to the Telegram API was unsuccessful. 
 The server returned HTTP 409 Conflict.           
 Response body:
 [b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates 
 request; make sure that only one bot instance is running"}']"
 (util.py:65 Polling Thread) ERROR - TeleBot: "ApiException occurred, 
 args=('A request   to the Telegram API was unsuccessful. The server returned    
 HTTP 409 Conflict. 
 Response body:
 \n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates 
  request; make sure that only one bot instance is running"}\']',)

**Comment by Badiboy** [comment]
Where is the question?

Before asking - what code are you runnung?
