### ISSUE TITLE
How to read message text with message id?

### ISSUE THREAD

**Issue by Yek0** [eternnoir/pyTelegramBotAPI#746]
Can i read message text with message id? Sample : 
Link : https://t.me/group/54 (message id : 54)
This link message text is : "Message text"
If we can this please help me. 
**********
msg = bot.get_message(chat.id, message_id)
print('msg.text')
*********
😆 Like this 😆
pyTelegramBotAPI : 3.6.7
OS : Windows 10
Python version : 3.8.1

**Comment by Badiboy** [comment]
Impossible for bots. Bots cannot "request" messages. They got only what Telegram **send** them.

**Comment by Yek0** [comment]
> Botlar için imkansız. Botlar mesaj "talep edemez". Sadece Telegram'ın onlara **gönderdiklerini** aldılar .

Thanks
