### ISSUE TITLE
Members list

### ISSUE THREAD

**Issue by Yek0** [eternnoir/pyTelegramBotAPI#748]
How to get group members id list? I know we can but how? Sample t.me/tag_man_bot

pyTelegramBotAPI : 3.6.7
OS : Windows 10
Python version : 3.8.1

**Comment by Badiboy** [comment]
Bot cannot get mebers list. Bot can:
1. [Get members count](https://core.telegram.org/bots/api#getchatmemberscount)
2. [Get member by ID](https://core.telegram.org/bots/api#getchatmember)

To have the list bot should stay in group and save every joining user.
