### ISSUE TITLE
restrictChatMember

### ISSUE THREAD

**Issue by wmchina** [eternnoir/pyTelegramBotAPI#749]
Excuse me, how can I call restrictchatmember? I didn't find it in the method. Can I give you a call example?

**Comment by Badiboy** [comment]
`
bot.restrict_chat_member(chat_id, user_id, can_send_messages = False, can_send_media_messages = False, can_send_other_messages = False)
`

**Comment by wmchina** [comment]
Thank you very much. There is another problem, bot. Polling (interval = 3), which is to update the message every 3 seconds. I added a timer under this document. Why does the new timer not work.


def sleeptime(hour,min,sec):
 return hour*3600 + min*60 + sec;
 

second = sleeptime(0,0,2);

while 1==1:

 time.sleep(second);

 
 print ('go go go')
 
How do I operate if I need to add a new timer?

**Comment by Badiboy** [comment]
This is not the pyTelegramBotAPI issue.
