### ISSUE TITLE
Connection exceptions

### ISSUE THREAD

**Issue by rmed** [eternnoir/pyTelegramBotAPI#75]
The `__polling()` method takes into account API exceptions when polling for updates. While the `none_stop` argument prevents the thread from stopping in case these exceptions occur, it will stop if it encounters a connection exception (such as those from the *requests* module).

Would it be possible to also *skip* and/or log these exceptions when using the `none_stop` argument so that it is not necessary to manually restart the bot?

**Comment by eternnoir** [comment]
Hi, you can use telebot's log to logging message. See logging section https://github.com/eternnoir/pyTelegramBotAPI#logging .

Example 

```python
    ch = logging.StreamHandler(sys.stdout)
    formatter = logging.Formatter('[%(asctime)s] %(thread)d {%(pathname)s:%(lineno)d} %(levelname)s - %(message)s',
                                  '%m-%d %H:%M:%S')
    ch.setFormatter(formatter)
    telebot.logger.addHandler(ch)
    telebot.logger.setLevel(logging.DEBUG)
```

**Comment by pevdh** [comment]
Just to be clear, what kind of exceptions are we talking about? To my knowledge, most exceptions from the requests module are non-recoverable.

**Comment by rmed** [comment]
I was thinking about `requests.exceptions.ConnectionError` and such (maybe the host lost connection temporarily?), but as you say, I'm not sure if that is recoverable.

**Comment by pevdh** [comment]
See #78 for further discussion.
