### ISSUE TITLE
def sleeptime(hour,min,sec)

### ISSUE THREAD

**Issue by wmchina** [eternnoir/pyTelegramBotAPI#750]
import telebot
import time

def sleeptime(hour,min,sec):
 return hour*3600 + min*60 + sec;
 

second = sleeptime(0,0,2);

while 1==1:
 #
 time.sleep(second);
 
 
 print ('go go go')
 
     
        

             
TOKEN = config.TOKEN
def listener(messages):
   
    #When new messages arrive TeleBot will call this function.

    for m in messages:
        chatid = m.chat.id
        if m.content_type =='new_chat_members':
            tb.delete_message(chatid,message_id)
        

tb = telebot.TeleBot(TOKEN)
tb.set_update_listener(listener) #register listener
tb.polling()
#Use none_stop flag let polling will not stop when get new message occur error.
tb.polling(none_stop=True)
# Interval setup. Sleep 3 secs between request new message.
tb.polling(interval=3)

while True: # Don't let the main Thread end.
    pass

In this case, I added def sleeptime(hour,min,sec): Why the newly added def sleep time (hour, min, SEC): doesn't work

**Comment by Nitroteam** [comment]
Here is the problem :+1:
```
while True:
    pass

```
when you run the bot, script just stuck on this loop and don't pay attention to tb.polling()
