### ISSUE TITLE
get_file() does not return file_unique_id

### ISSUE THREAD

**Issue by xon-dev** [eternnoir/pyTelegramBotAPI#751]
Version: pyTelegramBotAPI==3.6.7
OS: Manjaro linux 19.0.0
Python: Python 3.8.1
`https://api.telegram.org/bot<token>/getFile?file_id=<file_id>` returns four fields: `file_id,` `file_unique_id,` `file_size` and `file_path,` but using `bot.get_file(file_id)` it returns only 3: `file_id,` `file_size` and `file_path`

**Comment by Badiboy** [comment]
Please, update your issue with adequate details.
