### ISSUE TITLE
Wia

### ISSUE THREAD

**Issue by ahvahsky2008** [eternnoir/pyTelegramBotAPI#753]
1. 3.6.7

2. Windows 10

3. 3.7.4

How wait untill all photos upload? I want upload 10 images and save it to folder. How wait untill all photos being uploaded? Example, i upload 10 images - in photo_make_photo_step i receive only 2 because others not yet uploaded. Why wait untill all photos uploaded?
```
  msg = bot.send_message(message.chat.id, 'Сделайте фотографии. Как завершите - нажмите Далее⏭️', reply_markup = ok_cancel_menu)
        bot.register_next_step_handler(msg, photo_make_photo_step)

def photo_make_photo_step(message):
   
    if message.content_type=='photo':
        fileID = message.photo[-1].file_id
        file_info = bot.get_file(fileID)
        downloaded_file = bot.download_file(file_info.file_path)

        with open(fileID+".jpg", 'wb') as new_file:
            new_file.write(downloaded_file)
        user.photos.append(fileID+".jpg")
        msg = bot.send_message(message.chat.id, 'Добавьте ещё фото или нажмите Далее если закончили выбор')
        bot.register_next_step_handler(msg, photo_bind_photo_step)
        return
    msg = bot.send_message(message.chat.id, 'Введите номер объекта', reply_markup = cancel_menu)
    bot.register_next_step_handler(msg, vvedi_nomer_objecta_step)
```
ps. Хочу принять n-фоток из сообщения и сохранить их под текущим именем. Все гут, но пока работает с 1-й фоткой. Гружу 10-фоток, и оно ассинхронно получает их. Я загрузил 10 фоток - и в методе photo_make_photo_step я вижу только 2штуки, так как другие не успели подгрузиться. Как обойти это?

**Comment by awarebayes** [comment]
Жиза

**Comment by Badiboy** [comment]
Две это еще странно. Одну должны видеть вроде...

Примерный ответ: "по простому - никак". Фотки будут приходить по мере загруки и прохождения через сервер. Никто не знает, сколько фоток отправил юзер, поэтому совершенно неизвестно, сколько и как ждать. Предполагаю, что городить какую-то магию с тредами и таймаутами.
