### ISSUE TITLE
photo

### ISSUE THREAD

**Issue by wmchina** [eternnoir/pyTelegramBotAPI#757]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 3.6.7
2. What OS are you using?
ubuntu18
3. What version of python are you using?
python3.8

Hello, the following code, when I send expression and text, it will print, when I send pictures, it will not print content. How to solve it

bot = telebot.TeleBot(TOKEN)
@bot.message_handler(func=lambda message: True)
def redictMessage(message):
    print (message)

@bot.callback_query_handler(func=lambda call: True)
def callback_handle(call):
    print(call)

while True:
    try:
        bot.polling(none_stop=True)
    except Exception:
        time.sleep(10)

**Comment by wmchina** [comment]
This ECHO robot, when inputting pictures (jpg), does not answer. How can I solve it


import telebot

bot = telebot.TeleBot("TOKEN")

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
	bot.reply_to(message, "Howdy, how are you doing?")

@bot.message_handler(func=lambda message: True)
def echo_all(message):
	bot.reply_to(message, message.text)

bot.polling()

**Comment by Badiboy** [comment]
Default content_type for message_handler is "text". 

![image](https://user-images.githubusercontent.com/5613421/75631336-fcd92280-5c02-11ea-9e56-e66b32470718.png)

Define content_type "photo" for the handler.

**Comment by wmchina** [comment]
Can you give me an example? I haven't realized it here.

**Comment by Badiboy** [comment]
```
@bot.message_handler(func=lambda message: True, content_types=['text', 'photo'])
def test_all(message):
print("ololo")
```
