### ISSUE TITLE
CPU overload after update

### ISSUE THREAD

**Issue by analca3** [eternnoir/pyTelegramBotAPI#76]
Hi! After last update (or an older one) I have my Raspberry Pi CPU overloaded. I saw the new block parameter and other things but I don't know my problem. What do I have missed?

**Comment by carlosgarciamou** [comment]
Yeah... I has the same issue. I solved it by adding a delay in the while true: pass

**Comment by analca3** [comment]
I have the sleep too...

**Comment by pevdh** [comment]
What version of the API are you running? The latest? Check with sudo pip install pytelegrambotapi --upgrade. I'll look into this on my Pi. What did you use to measure CPU usage?

**Comment by analca3** [comment]
Yes, I have the latest one. I'm using top. Before the update the cpu usage was minimal. Now it is so high... These python3 processes are my bots.

https://www.dropbox.com/s/ftkd230bfh6kq5v/Screenshot_2015-09-30-00-27-56.png?dl=0

Sorry for the non attached image, I'm using my phone.

Thank you :).

**Comment by pevdh** [comment]
I cannot replicate this with Python 2.7 on my Pi.. can you post your exact source code if you don't mind?

**Comment by analca3** [comment]
Sure.

https://github.com/analca3/LaTeX2IMGbot

https://github.com/analca3/Sympybot

Thank you so much!

**Comment by eternnoir** [comment]
Problem like #27. What version number before you update?

**Comment by analca3** [comment]
I don't understand the problem, the main thread is sleeping... changing to 20 seconds is the same :(.

I think I was on 0.3.x, one or two versions before block parameter in polling().

Thanks.

**Comment by pevdh** [comment]
Can you update to the latest version and tell us whether the problem persists? This is not an easy fix, I think.

**Comment by analca3** [comment]
It's better with 0.3.8!

![image](https://cloud.githubusercontent.com/assets/3939991/10322062/4dae8f90-6c7c-11e5-8af0-ddb38a8ac2b8.png)

It's not as good as before (python3 wasn't at top of top XD) but it's a normal usage :). What's the problem exactly?
