### ISSUE TITLE
problem with regexp

### ISSUE THREAD

**Issue by hamidko** [eternnoir/pyTelegramBotAPI#768]
hi, I write this for example:
@bot.message_handler(regexp = "london")
def London_city(message):
       blabla
but when a user send to bot: "london streets" , the above function react!
how I get function reaction on just "london" phrase?!

**Comment by Badiboy** [comment]
This is the way regexp works.
![image](https://user-images.githubusercontent.com/5613421/79330859-e5d86080-7f22-11ea-8ca8-a0faa8c590ce.png)

Use lambda instead.
bot.message_handler(func=lambda mess: mess.text == "london")
