### ISSUE TITLE
Add to doc

### ISSUE THREAD

**Issue by frandibar** [eternnoir/pyTelegramBotAPI#77]
I think it's worth mentioning in the docs that the `message_handler` decorators can be stacked to produce an OR filter, i.e.:

```python
@bot.message_handler(commands=[CMD])
@bot.message_handler(func=lambda msg: msg.text.encode("utf-8") == SOME_FANCY_EMOJI)
def send_something(message):
    pass
```

**Comment by pevdh** [comment]
Thats really smart and really useful! This should indeed definitely be added to the docs, thanks!

**Comment by pevdh** [comment]
941b8ac5d0a399961da
