### ISSUE TITLE
problem in running specific function with schedule in telebot

### ISSUE THREAD

**Issue by alim7676** [eternnoir/pyTelegramBotAPI#770]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? v 3.7.6

2. What OS are you using? Ubuntu

3. What version of python are you using?3.6
`schedule.every(10).minutes.do(get_price)
schedule.every(1).days.at("00:00").do(update)
schedule.every(1).days.at("00:20").do(update_stock)

print("LOG:  ready to use...!")

bot = telebot.TeleBot("664511011:AAHRe-WE2Udg6iwjcUJFIbhZi3gRBgLzUi0")

@bot.message_handler(commands=['help', 'start'])
def send_welcome(message):
    chat_id = message.chat.id

@bot.message_handler(regexp = '...')
def echo_message(message):
.....................

while True:
    try:
        schedule.every(10).minutes.do(get_price)
        schedule.every(1).days.at("00:00").do(update)
        schedule.every(1).days.at("00:20").do(update_stock)
        bot.polling(none_stop=True, interval=0, timeout=0)
    except:
        time.sleep(10)
`

hey this is part of my code and im trynig to run a function every 10 min but it doesnt work . i dont know how handle this . help me and thank u

**Comment by Badiboy** [comment]
1. https://github.com/eternnoir/pyTelegramBotAPI/issues/759
2. You do not know how schedule work, read there docs.
