### ISSUE TITLE
When I call inlinekeyboard again, it does not work

### ISSUE THREAD

**Issue by Stele1024** [eternnoir/pyTelegramBotAPI#771]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

	3.6.7

2. What OS are you using?

	Mac OS 10.14.6

3. What version of python are you using?

	Python 3.8 

	

I want to use `inlinekeyboard` to get the information of each item, for example, `tcp`, `stcp`. But I choose `tcp`, click `online`, `offline`,` all`, I can get the information of `tcp` accurately, but then get `stcp`, click `online`, `offline`, `all`, the output is the previous item `tcp` .

This image shows the output of `tcp` clicking `inlinekeyboard`  `all`

![tcp](https://ftp.bmp.ovh/imgs/2020/03/298a9fedc97b0269.png)

The red circled image of this image is the output of `stcp`  , which does not match the information sent by the telegram bot. Bot sent the information about `tcp`, no is `stcp`

![stcp](https://ftp.bmp.ovh/imgs/2020/03/c1bd13c8f2c90678.png)

My code :

```python
import telebot
from telebot import types
import pprint

bot1 = telebot.TeleBot('TOKEN')


class InlineMarkup:
    def __init__(self):
        self.row_width = 2
        self.frp_status_tag = ['online', 'offline', 'all']
        self.frp_api_tag = ['Server info', 'Tcp', 'Udp', 'Https', 'Http', 'Stcp']

    def frp_inline_markup(self):
        markup = types.InlineKeyboardMarkup(row_width=self.row_width)
        bl = []
        for i in self.frp_status_tag:
            bl.append(types.InlineKeyboardButton(i, callback_data=i.lower()))
        markup.add(bl[0], bl[1], bl[2])
        return markup


class FRP:
    def serverinfo(self):
        pass

    def tcp(self):
        pass

    def stcp(self):
        pass


ii = InlineMarkup()
frp = FRP()


@bot1.message_handler(content_types=['text'])
def tt(message):
    uci = message.chat.id
    if message.text == 'Server info':
        bot1.send_message(chat_id=uci, text=frp.serverinfo())
    elif message.text in ii.frp_api_tag:
        bot1.send_message(chat_id=uci, text='哎哟，三个不同选项呢！你快快选一个❤️',
                          reply_markup=ii.frp_inline_markup())
        handle_three_status_frp(tag=message.text)


def handle_three_status_frp(tag):
    command = 'result = FRP().' + tag.lower() + "()"
    exec(command)
    data = locals()["result"]
    pprint.pprint(data[2])

    @bot1.callback_query_handler(func=lambda call: True)
    def handle_call(call, data=data):
        if call.data == 'online':
            bot1.answer_callback_query(call.id, "Success")
            bot1.send_message(chat_id=call.message.chat.id, text=data[0])
        elif call.data == 'offline':
            bot1.answer_callback_query(call.id, "Success")
            bot1.send_message(chat_id=call.message.chat.id, text=data[1])
        elif call.data == 'all':
            bot1.answer_callback_query(call.id, "Success")
            bot1.send_message(chat_id=call.message.chat.id, text=data[2])


bot1.polling()

```

Thank!

**Comment by Badiboy** [comment]
```
  elif message.text in ii.frp_api_tag:
        bot1.send_message(chat_id=uci, text='哎哟，三个不同选项呢！你快快选一个❤️',
                          reply_markup=ii.frp_inline_markup())
```

You always create the same markup, you always have the same callback result...

**Comment by Stele1024** [comment]
> ```
>   elif message.text in ii.frp_api_tag:
>         bot1.send_message(chat_id=uci, text='哎哟，三个不同选项呢！你快快选一个❤️',
>                           reply_markup=ii.frp_inline_markup())
> ```
> 
> You always create the same markup, you always have the same callback result...

emmm，Does that mean I need to add an elif clause for each tag (e.g. tcp, stcp) to send a markup and change their callback?

**Comment by Stele1024** [comment]
> same

thank ,
