### ISSUE TITLE
examples/step_example.py

### ISSUE THREAD

**Issue by simpsss** [eternnoir/pyTelegramBotAPI#772]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
latest
2. What OS are you using?
Ubuntu 18.04.4 LTS
3. What version of python are you using?
Python 3.6.9

Hi,

The examples/step_example.py dont works in group?

register_next_step_handler dont works in group?

Regards.

**Comment by vollmann-ariel** [comment]
You should check the group privacy setting of your bot with Botfather, since it's enabled by default when you create a new bot.
And since you're doing that check also the "Allow Groups" setting.
Good luck!
