### ISSUE TITLE
updating telegram bot api

### ISSUE THREAD

**Issue by brightening-eyes** [eternnoir/pyTelegramBotAPI#773]
hi,
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
latest from GitHub
2. What OS are you using?
no matter, but mine is windows 10 64 bit
3. What version of python are you using?
3.6 and 3.7
the telegram api like fields and functions are out of date and needs refactoring
things like polls, (including PollOption and PollAnswer, KeyboardButtonPoll), markdown v2 which has been added in jan 23th 2020, SetChatPermission, setChatStickerSet, deleteChatStickerSet, and other methods and fields which has been added
this makes it possible to make more responsive bots easily with pytelegrambotapi

**Comment by Badiboy** [comment]
Polls, Perissions, Stickers and some other news are added. Others will be added... when they will be added. Look for updates. :)
