### ISSUE TITLE
Getting previous send message

### ISSUE THREAD

**Issue by zerefdarkmage** [eternnoir/pyTelegramBotAPI#777]
Please answer these questions before submitting your issue. Thanks!

1. the newest

2. pythonanywhere (flask)

3. 3.6 

How can i get the content(message.text) from a message send before the triggering message?

How it should look:

user send a name like: felix

then presses a button "add"

and the output should looks like"felix added"

i thought i could be done with something like this

bot.send_message(message.chat.id, text.from.previous.message +'added')

any ideas how it culd be done ?

**Comment by MasterGroosha** [comment]
Implement a [finite state machine](https://en.wikipedia.org/wiki/Finite-state_machine) in your bot

**Comment by Abdvkh** [comment]
Actually, i think you can use
`bot.register_next_step_handler(message, your_next_function)`
Your function will be like:
`your_next_function(message):
   bot.send_message(message.chat.id, message.text + " added")`

**Comment by underskys** [comment]
You can simply:
last_text = message.text()
bot.register_next_step_handler(message, your_next_function, last_text)

def your_next_function(message, last_text=''):
 text = f'{last_text} {message.text)'

**Comment by Abdvkh** [comment]
@underskys Does it work at all? I tried to pass arguments via lambda then have read that it breaks next step handler
