### ISSUE TITLE
'TeleBot' object has no attribute 'messege_handler'

### ISSUE THREAD

**Issue by Pokrishka** [eternnoir/pyTelegramBotAPI#778]
It's my code:
*********************************************************************************************************
import telebot

TOKEN = '1149023850:AAEBIhHlm4wslxkqcm6Aklwqjfs92zyGCyo'

bot = telebot.TeleBot(TOKEN)

@bot.messege_handler(commands-['start'])
def start(messege):
    send_mess = f'<b>Привет {messege.from_user.first_name}!</b>\nВведите страну'
    bot.send_messege(messege.chat.id,send_mess,parse_mode='html')

bot.polling(none_stop=True)

*********************************************************************************************************
I wanted to make a Telegram bot with Python. But I but I got such an error:
[AttributeError: 'TeleBot' object has no attribute 'messege_handler']
I'm using Python 3.8. And pytelegrambotapi the last version
Please help me!

**Comment by Badiboy** [comment]
pip uninstall telebot
pip install pyTelegramBotAPI

**Comment by MasterGroosha** [comment]
@Badiboy that's just a typo
@Pokrishka should be "mess**a**ge_handler", not "mess**e**ge_handler"

**Comment by Badiboy** [comment]
@MasterGroosha Oh lol, thanks :)
