### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by dkuznetsov21** [eternnoir/pyTelegramBotAPI#779]
1. latest

2. Ubuntu 18.04

3.Python 3.8.2

![image](https://user-images.githubusercontent.com/42741535/78554043-0e6da580-7813-11ea-8b8f-daf508377098.png)

console:
![image](https://user-images.githubusercontent.com/42741535/78554064-1decee80-7813-11ea-8ce2-4f56a47db89d.png)

Why I have this error?

**Comment by Badiboy** [comment]
If bot is / is not None after line 4?

**Comment by bedilbek** [comment]
> 1. latest
> 2. Ubuntu 18.04
> 
> 3.Python 3.8.2
> 
> ![image](https://user-images.githubusercontent.com/42741535/78554043-0e6da580-7813-11ea-8b8f-daf508377098.png)
> 
> console:
> ![image](https://user-images.githubusercontent.com/42741535/78554064-1decee80-7813-11ea-8ce2-4f56a47db89d.png)
> 
> Why I have this error?

@dkuznetsov21 Can you please share more of a traceback, so we can where actually error is raised?

**Comment by MasterGroosha** [comment]
Sorry for necroposting, but...
@dkuznetsov21 Did you solve your problem? Was it caused by `telebot` library installed along with `pyTelegramBotAPI`?
