### ISSUE TITLE
telegram bot telebot

### ISSUE THREAD

**Issue by correligionist** [eternnoir/pyTelegramBotAPI#788]
I am use telebot.
How can I pass the value of a variable inside a block to display text?
i = ('text')
```
``import telebot
import config
import random
 
from telebot import types
 
bot = telebot.TeleBot(config.TOKEN)
i = ('text')
x = ('text')
z = ('text')
y = ('text')
@bot.message_handler(commands=['start'])
def welcome(message):
    sti = open('avatar1459.jpg', 'rb')
    bot.send_sticker(message.chat.id, sti)

    # keyboard
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    item1 = types.KeyboardButton(text='i')
    item2 = types.KeyboardButton(text='x')
    item3 = types.KeyboardButton(text='z')
    item4 = types.KeyboardButton(text='y')

  
    markup.add(items1, items2, items3, items4)
 
    bot.send_message(message.chat.id, "Добро пожаловать, {0.first_name}!\nЯ - <b>{1.first_name}</b>, бот созданный чтобы быть подопытным кроликом.".format(message.from_user, bot.get_me()),
        parse_mode='html', reply_markup=markup)
@bot.message_handler(func=lambda message: True)
            ``
```
How can I pass the value of a variable inside a block to display text?

**Comment by bedilbek** [comment]
@correligionist, please if you want someone to help you, learn how to organize the code and question and only give the context of the code you want to ask.

Also, if you do not have something to announce about the issue or enhancement, you'd better ask on [stackoverflow](http://stackoverflow.com/) so you will find the answer faster. I hope you won't get it as an offense, that's just a solid advice to help you found out your problem faster!
