### ISSUE TITLE
ERROR - TeleBot: "A request to the Telegram API was unsuccessful

### ISSUE THREAD

**Issue by isxoq** [eternnoir/pyTelegramBotAPI#790]
When I run code
**************************************
import botParser
import telebot

bot = telebot.TeleBot("my token")

@bot.message_handler(commands=['help', 'start'])
def send_welcome(message):
    bot.reply_to(message, """\
Hi there, I am EchoBot.
I am here to echo your kind words back to you. Just say anything nice and I'll say the exact same thing to you!\
""")

@bot.message_handler(func=lambda message: True)
def echo_message(message):
    bot.reply_to(message, message.text)

bot.polling()

*************************************************************************Answer:

2020-04-14 10:30:11,871 (__init__.py:420 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned an invalid JSON response. Response body:

[b'{"ok":true,"result":[{"update_id":66120358,\n"message":{"message_id":2,"from":{"id":733285621,"is_bot":false,"first_name":"Isxoqjon","last_name":"| Uyda qoling!","username":"isxoqjon","language_code":"ru"},"chat":{"id":733285621,"first_name":"Isxoqjon","last_name":"| Uyda qoling!","username":"isxoqjon","type":"private"},"date":1586841888,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}},{"update_id":66120359,\n"message":{"message_id":3,"from":{"id":733285621,"is_bot":false,"first_name":"Isxoqjon","last_name":"| Uyda qoling!","username":"isxoqjon","language_code":"ru"},"chat":{"id":733285621,"first_name":"Isxoqjon","last_name":"| Uyda qoling!","username":"isxoqjon","type":"private"},"date":1586841936,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}},{"update_id":66120360,\n"message":{"message_id":4,"from":{"id":733285621,"is_bot":false,"first_name":"Isxoqjon","last_name":"| Uyda qoling!","username":"isxoqjon","language_code":"ru"},"chat":{"id":733285621,"first_name":"Isxoqjon","last_name":"| Uyda qoling!","username":"isxoqjon","type":"private"},"date":1586841982,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}}]}']"

**Comment by Badiboy** [comment]
Your json is really incorrect.
¯\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/5613421/79330405-22f02300-7f22-11ea-8a49-a7dd0d323613.png)

**Comment by isxoq** [comment]
> Your json is really incorrect.
> ¯_(ツ)_/¯
> 
> ![image](https://user-images.githubusercontent.com/5613421/79330405-22f02300-7f22-11ea-8a49-a7dd0d323613.png)

Thanks
