### ISSUE TITLE
How to delete a user named deleted account in a group?

### ISSUE THREAD

**Issue by wmchina** [eternnoir/pyTelegramBotAPI#791]
Please answer these questions before submitting your issue. Thanks!

  1  What version of pyTelegramBotAPI are you using?
    pyTelegramBotAPI 3.6.7
  2  What OS are you using?
    Ubuntu 18 (64 бит)
  3  What version of python are you using?
    python3.8

How to delete a user named deleted account in a group?

**Comment by Badiboy** [comment]
Not possible. Bot cannot get list of group users.
