### ISSUE TITLE
update message methods?

### ISSUE THREAD

**Issue by hamidko** [eternnoir/pyTelegramBotAPI#793]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2. What OS are you using?

3. What version of python are you using?
3.7

hi, how can I delete or update the messages that bot sent it to user?!

there are in telegram api this methods: **editMessageText** and 
**editMessageMedia** etc. 
can I do them by pyTelegramBotAPI?!
thanks.

**Comment by Badiboy** [comment]
edit_message_text
edit_message_media
etc.

**Comment by hamidko** [comment]
> edit_message_text
> edit_message_media
> etc.

thank you!!
