### ISSUE TITLE
How to filter username use bot

### ISSUE THREAD

**Issue by KevinKien** [eternnoir/pyTelegramBotAPI#795]
Hello,

I want one username use bot and I want filter for that user. I do not know how to do. You can help me. 

Thank you!!!

**Comment by ThePokerFaCcCe** [comment]
i think it helps you
<pre>
`admins_list=[11845686, 3564678]`
`@bot.message_handler()`
`def name(pm):`
   ` if pm.text == "show users":`
        `if pm.chat.id in admins_list:`
             `#Show List...`
        `else:`
             `pass`
</pre>

**Comment by KevinKien** [comment]
thank you @ThePokerFaCcCe
