### ISSUE TITLE
'TeleBot' object has no attribute 'middleware_handler'

### ISSUE THREAD

**Issue by go1dbless** [eternnoir/pyTelegramBotAPI#796]
Hello, i'm using middlware example from docs and have problem

`'TeleBot' object has no attribute 'middleware_handler'`

I'm using this clean [example ](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/middleware/i18n.py) and this not works for me.
Other bot functions works normaly

Version of package: 3.6.7
Python: 3.8

**Comment by bedilbek** [comment]
Hi @go1dbless,

The reason why you see this maybe that you are installing `pyTelegramBotApi` from pypi and not from source. This `middleware_handler` is a new feature and has been added recently. So, it only exists in `master` branch and no new version is released after this feature has been added. You can install  `pyTelegramBotApi` from source (github master branch) for that reason:

```shell script
pip install -e git+https://github.com/bedilbek/pyTelegramBotAPI.git@master#egg=pyTelegramBotAPI
```

**Comment by go1dbless** [comment]
> Hi @go1dbless,
> 
> The reason why you see this maybe that you are installing `pyTelegramBotApi` from pypi and not from source. This `middleware_handler` is a new feature and has been added recently. So, it only exists in `master` branch and no new version is released after this feature has been added. You can install `pyTelegramBotApi` from source (github master branch) for that reason:
> 
> ```shell
> pip install -e git+https://github.com/eternnoir/pyTelegramBotAPI.git@master#egg=pyTelegramBotAPI
> ```

**Comment by go1dbless** [comment]
> Hi @go1dbless,
> 
> The reason why you see this maybe that you are installing `pyTelegramBotApi` from pypi and not from source. This `middleware_handler` is a new feature and has been added recently. So, it only exists in `master` branch and no new version is released after this feature has been added. You can install `pyTelegramBotApi` from source (github master branch) for that reason:
> 
> ```shell
> pip install -e git+https://github.com/eternnoir/pyTelegramBotAPI.git@master#egg=pyTelegramBotAPI
> ```

Большое спасибо Вам за быстрый ответ. Да действительно проблема была в этом. Сделал так как Вы сказали и все сработало. Отлично!
Ещё раз благодарю!
