### ISSUE TITLE
How to use send_poll. What is poll parameter here

### ISSUE THREAD

**Issue by aayushchowhan** [eternnoir/pyTelegramBotAPI#802]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

3.6.7

2. What OS are you using?

Android

3. What version of python are you using?

3.7.2

**Comment by Badiboy** [comment]
1. Use the recently published version 3.7.0

2.
`def send_poll(self, chat_id, poll, explanation_parse_mode=None, disable_notifications=False, reply_to_message=None, reply_markup=None):`

3. poll is an instance of class Poll
