### ISSUE TITLE
Deprecation warning due to invalid escape sequences.

### ISSUE THREAD

**Issue by tirkarthi** [eternnoir/pyTelegramBotAPI#805]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? master branch

2. What OS are you using? Ubuntu

3. What version of python are you using? 3.8

Deprecation warning due to invalid escape sequences. Using raw strings or escaping them again helps in resolving this. Check https://github.com/asottile/pyupgrade/ for automatic fix of this.

```
find . -iname '*.py' | grep -Ev 'setup|rdf4|tool' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./tests/test_telebot.py:51: DeprecationWarning: invalid escape sequence \w
  @bot.message_handler(regexp='((https?):((//)|(\\\\))+([\w\d:#@%/;$()~_?\+-=\\\.&](#!)?)*)')
./tests/test_telebot.py:87: DeprecationWarning: invalid escape sequence \w
  @bot.message_handler(regexp='((https?):((//)|(\\\\))+([\w\d:#@%/;$()~_?\+-=\\\.&](#!)?)*)')
./telebot/util.py:247: DeprecationWarning: invalid escape sequence \w
  regexp = re.compile("/\w*(@\w*)*\s*([\s\S]*)",re.IGNORECASE)
```

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/80213180-74df2a00-8641-11ea-87c6-ec546a57336c.png)
I do not see any problems with '\w' in the link you gave.

**Comment by tirkarthi** [comment]
`\d` is given as an example. `\w` should also give similar warning.

**Comment by Badiboy** [comment]
@tirkarthi 

> Anyway, please, note what exactly should be fixed and in what way.

**Comment by tirkarthi** [comment]
The fix is to ensure the deprecation warnings are not raised that in future might become syntax warnings. As noted in pyupgrade, using raw strings for the regex or escaping the \w with \\w will fix this. Using pyupgrade will do this automatically.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/819

Fixed.

**Comment by tirkarthi** [comment]
Thanks :)
