### ISSUE TITLE
How can I get id of the last message sent from my bot?

### ISSUE THREAD

**Issue by derevyanko** [eternnoir/pyTelegramBotAPI#809]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.7

2. What OS are you using?
Linux Ubuntu 16.04

3. What version of python are you using?
3.6

I need to change the last message  sent from my bot when user sends concrete command, how I can do it?
Thanks for your attention and answers.

**Comment by Badiboy** [comment]
```
msg = bot.send_message(...)
last_message_id = msg.message_id
```
