### ISSUE TITLE
Use real Long polling by default.

### ISSUE THREAD

**Issue by rockneurotiko** [eternnoir/pyTelegramBotAPI#81]
In Line 87 of `__init__.py` (please, refactor the code, `__init__.py` shouldn't be used to have code) you set the timeout to 3 seconds. And this is the method used in polling. Please, change the timeout to the maximum that Telegram servers handles: 20 seconds. It will help in the performance of the bots when they don't have many requests.

**Comment by eternnoir** [comment]
commit  1c53955d5ab

**Comment by eternnoir** [comment]
Version 0.3.7 supported.
