### ISSUE TITLE
The server returned HTTP 404 Not Found

### ISSUE THREAD

**Issue by Ricftrw** [eternnoir/pyTelegramBotAPI#817]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.7
2. What OS are you using?
Raspberry Pi
3. What version of python are you using?
3.7

i get error like this : 2020-04-29 20:39:25,093 (__init__.py:443 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 404 Not Found. Response body:
[b'{"ok":false,"error_code":404,"description":"Not Found"}']"

**Comment by Badiboy** [comment]
May be your provider/uplink/country blocks Telegram?

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/80640298-dfda9780-8a6b-11ea-945f-d534f8f7a9d1.png)
Or you did not pass the correct token.

**Comment by Ricftrw** [comment]
> ![image](https://user-images.githubusercontent.com/5613421/80640298-dfda9780-8a6b-11ea-945f-d534f8f7a9d1.png)
> Or you did not pass the correct token.

Yes my token is incorrect
