### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by maheshthedev** [eternnoir/pyTelegramBotAPI#818]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
1.1
2. What OS are you using?
Windows
3. What version of python are you using?
3.7

My issue, how can we create Hyperlinks using pytelegramapi?

**Comment by Badiboy** [comment]
Use html-style: https://core.telegram.org/bots/api#html-style

**Comment by maheshthedev** [comment]
Thank you.
