### ISSUE TITLE
Help me with send_poll what a hell?

### ISSUE THREAD

**Issue by Seruios** [eternnoir/pyTelegramBotAPI#820]
1. What version of pyTelegramBotAPI are you using?  Newest one

2. What OS are you using? Windows10

3. What version of python are you using? 3.8.2

`answers = ["Python", "PHP", "Java"]
bot.send_poll(message.chat.id, "How it works", answers)`

AttributeError: 'str' object has no attribute 'question'

but it must be right - https://core.telegram.org/bots/api#sendpoll

It's works only with 
`poll = telebot.types.Poll(question= "How it works")
poll.add("Python")
poll.add("PHP")
poll.add("Java")
bot.send_poll(chat_id= message.chat.id, poll = poll)`

Why doesn't 1st way work?

**Comment by Badiboy** [comment]
1st way doesn't work because first parameter should be Poll.
Construct the Poll instance and pass it to send_poll, like you did.

**Comment by Seruios** [comment]
ok thx, but I still don't understood anything. All others commands work fine with core telegram com bot api. and I cant find this way in telegram api..

**Comment by Badiboy** [comment]
May be you are right and whis was step away from API. I'll revise the poll sending mechanism.

**Comment by Badiboy** [comment]
Revised, thank you for your pointing to the problem.
https://github.com/eternnoir/pyTelegramBotAPI/pull/821

Before updated version is published on pypi, you can use
`pip install -U git+https://github.com/eternnoir/pyTelegramBotAPI.git`

**Comment by Seruios** [comment]
Thank you very much, now it works fine!
