### ISSUE TITLE
How to use setMyCommands in the code?

### ISSUE THREAD

**Issue by Seruios** [eternnoir/pyTelegramBotAPI#822]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Newest one

2. What OS are you using? Windows 10

3. What version of python are you using? 3.8.2

how to use this command and how to create object BotCommand and create json-serialized array of BotCommand?

**Comment by Badiboy** [comment]
The last Bot API updates are not implemented yet.

**Comment by Seruios** [comment]
Okay.
