### ISSUE TITLE
How to change slow mode in group by bot? is it possible?

### ISSUE THREAD

**Issue by Seruios** [eternnoir/pyTelegramBotAPI#824]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Newest one

2. What OS are you using? Windows 10

3. What version of python are you using? 3 8 2

https://core.telegram.org/bots/api#chatpermissions - I checked this, and I can't find any slow_mode, is it possible?

**Comment by Seruios** [comment]
I found slow_mode_delay in Chat object, but how to edit this?..

**Comment by Badiboy** [comment]
Manually in group settings.

**Comment by Seruios** [comment]
and with bot?

**Comment by Seruios** [comment]
ok thx
