### ISSUE TITLE
Message can't be edited after bot_edit_message_reply_markup

### ISSUE THREAD

**Issue by NikitaNeganov** [eternnoir/pyTelegramBotAPI#828]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
 pyTelegramBotAPI==3.7.1
2. What OS are you using?
MacOS Catalina 10.15, + whatever Heroku runs in
3. What version of python are you using?
python==3.7.5

I'm running into the following error while trying to edit message after editing reply_markup for this message
```
Traceback (most recent call last):
  File "usd.py", line 90, in repeat_all_messages
    bot.edit_message_text(chat_id=sent.chat.id, message_id=sent.message_id, text=value, reply_markup=keyboard)
  File "/Users/nikita/Documents/projects/tg/lib/python3.7/site-packages/telebot/__init__.py", line 1090, in edit_message_text
    disable_web_page_preview, reply_markup)
  File "/Users/nikita/Documents/projects/tg/lib/python3.7/site-packages/telebot/apihelper.py", line 682, in edit_message_text
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/nikita/Documents/projects/tg/lib/python3.7/site-packages/telebot/apihelper.py", line 65, in _make_request
    return _check_result(method_name, result)['result']
  File "/Users/nikita/Documents/projects/tg/lib/python3.7/site-packages/telebot/apihelper.py", line 84, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: message can\'t be edited"}']
```

The case is the following: on user message I first send 'Loading...' message, then scrape the data I need and then edit the message effectively replacing 'Loading' with the data.

But after that, I realized that I needed to change reply_markup based on some criteria received from the message.

Assuming I basically want to check against user_id, then I'll try to do this:
```
@bot.message_handler(content_types=["text"])
def repeat_all_messages(message):
  ....
  sent = bot.send_message(message.chat.id, 'Loading...')
  if (message.chat.id == 'xxx'):
    bot.edit_message_reply_markup(message.chat.id, reply_markup=new_markup)
  # make async call here
  data = ...
  # then receive some data and edit message
  bot.edit_message_text(chat_id=sent.chat.id, message_id=sent.message_id, text=data)
```

And then I run into the aforementioned `Traceback`. The thing is now there is only 2 options - to edit `reply_markup` and be unable to edit the message or to edit the message without editing `reply_markup`.

I'm not sure whether it is indeed a bug or an expected behavior, but in the latter case is there another option to edit both markup and the message?

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/104052195-65693680-51fa-11eb-90ea-3221afe8e2a3.png)
You did not specify message_id in edit_message_reply_markup
