### ISSUE TITLE
Pdf file Cyrillic name encoding error

### ISSUE THREAD

**Issue by kkukushkin** [eternnoir/pyTelegramBotAPI#833]
pyTelegramBotAPI==3.6.7
macOS Catalina, version 10.15.4
python 3.7

Hi!

My bot app is deployed via Pythonanywhere server. 
Also I have there pdf file named in Cyrillic, for example: '2018_0730_Глоссарий CML.pdf'. 
My bot gets request from user and sends him this file (code works correctly)
But.
The name of the file, user finally gets, changes.
The new name: '2018_0730_Глоссарии_CML.pdf'.    
So one letter was changed and one new underscore appeared. 
I do not face this problem with other *.pptx files but with pdf files I get similar error. 
What is a potential solution for this problem? Thank you in advance.

My code:

`definitions(message):`
`chat_id = message.chat.id `
`bot.send_message(chat_id, 'Вот Ваш файл. Для повторного вызова меню нажмите /start') `
`glos = bot.send_document(chat_id, open('....../bot/2018_0730_Глоссарий CML.pdf', 'rb')) `
`return chat_id`
`bot.register_next_step_handler(glos, send_welcome)`

**Comment by rabx2i** [comment]
Isn't it easier to convert names to transliteration?

**Comment by basskuz** [comment]
yes, this could be a solution, unfortunately I need Cyrillic names of files
I found that names of *.pptx and other files are also changing

**Comment by ShelMX** [comment]
hi
i also have some trouble with sendinп file too ...
bot send without extension and without correct name, always just 'document'
how send file with name and extension?
In my case i haven't file_id

**Comment by rabx2i** [comment]
So what's the problem? Just indicate the file name along with the extension. Maybe [this](https://ru.stackoverflow.com/questions/969515/Как-отправить-torrent-файл-в-pytelegrambotapi-методом-senddocument) will help you.

**Comment by ShelMX** [comment]
you make my day, bro)))
BIIIIIIIG THNX

**Comment by rabx2i** [comment]
Regarding the error with the name. And if you save the file to an archive? A file in the archive can be of any name, and the archive itself, for example, will be called "archive.zip".

**Comment by kkukushkin** [comment]
Thank you for the suggestion. Some colleagues use MacBooks and have no idea how to open archives. That is why I chose to send unpacked files via bot. Anyway I tried to send these files using Telegram to my colleagues and sometimes get the same mistake with 'Й' and with '_'. But I did not find any logic in these errors. So, probably, it can be Telegram itself.
