### ISSUE TITLE
AttributeError: partially initialized module 'telebot' has no attribute 'TeleBot' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Sokrat08** [eternnoir/pyTelegramBotAPI#835]
Всем добра! Помогите! При созданий телеграмм бота выдает такую ошибку при запуске с командной строки! Вот код:

import telebot

bot = telebot.telebot("1280340746:AAFSdU-HR7OmVx3pKvKuwFoeHjMdP5TK98s")

@bot.message_handler(content_types=['text'])
def send_echo(message):
	bot.reply_to(message, message.text)

bot.polling( none_stop = True)

pyTelegramBotAPI==3.7.1
Windows 10 Pro
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32

**Comment by tohabyuraev** [comment]
> Всем добра! Помогите! При созданий телеграмм бота выдает такую ошибку при запуске с командной строки! Вот код:
> 
> import telebot
> 
> bot = telebot.telebot("1280340746:AAFSdU-HR7OmVx3pKvKuwFoeHjMdP5TK98s")
> 
> @bot.message_handler(content_types=['text'])
> def send_echo(message):
> 	bot.reply_to(message, message.text)
> 
> bot.polling( none_stop = True)
> 
> 
> 
> pyTelegramBotAPI==3.7.1
> Windows 10 Pro
> Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
> 

You need telebot.Telebot(TOKEN), not telebot.telebot(TOKEN). You have also another errors in code.

**Comment by Sokrat08** [comment]
> > Всем добра! Помогите! При созданий телеграмм бота выдает такую ошибку при запуске с командной строки! Вот код:
> > import telebot
> > bot = telebot.telebot("1280340746:AAFSdU-HR7OmVx3pKvKuwFoeHjMdP5TK98s")
> > @bot.message_handler(content_types=['text'])
> > def send_echo(message):
> > bot.reply_to(message, message.text)
> > bot.polling( none_stop = True)
> > pyTelegramBotAPI==3.7.1
> > Windows 10 Pro
> > Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
> 
> You need telebot.TeleBot(TOKEN), not telebot.telebot(TOKEN). You have also another errors in code.

F:\Python>python import.py
Traceback (most recent call last):
  File "import.py", line 1, in <module>
    import telebot
  File "F:\Python\telebot.py", line 3, in <module>
    bot = telebot.TeleBot("1280340746:AAFSdU-HR7OmVx3pKvKuwFoeHjMdP5TK98s")
AttributeError: partially initialized module 'telebot' has no attribute 'TeleBot' (most likely due to a circular import)

**Comment by tohabyuraev** [comment]
How did you install the library? And what is the telebot.py file in your folder?

**Comment by Sokrat08** [comment]
This is a file with that name. Thank you for paying attention to this. The telebot itself conflicted with the name of the file, which was identical with itself. Renamed the file earned. thank

> How did you install the library? And what is the telebot.py file in your folder?

This is a file with that name. Thank you for paying attention to this. The telebot itself conflicted with the name of the file, which was identical with itself. Renamed the file earned. thank
