### ISSUE TITLE
Set_chat_permissions doesn't work or not exist/

### ISSUE THREAD

**Issue by Seruios** [eternnoir/pyTelegramBotAPI#838]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Newest one

2. What OS are you using? Windows 10

3. What version of python are you using? 3.8.2

Why Set_chat_permissions doesn't work? Does it even exist?

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/834
Added here.
