### ISSUE TITLE
No timeout option in send_media_group method

### ISSUE THREAD

**Issue by VladislavKudrin** [eternnoir/pyTelegramBotAPI#845]
Hi, i've noticed that send_medoa_group method has no timeout option. It is in Telegram Api though.

**Comment by tohabyuraev** [comment]
In my opinion, the sendMediaGroup method does not have a timeout field in the official Telegram Bot API. Maybe you can add this field if it necessary.

**Comment by Badiboy** [comment]
@VladislavKudrin Yep, some send functions are miss timeout parameters. Should be added...

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/848

Added
