### ISSUE TITLE
How to restart bot?

### ISSUE THREAD

**Issue by ARN00L** [eternnoir/pyTelegramBotAPI#850]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 3.6.7

2. What OS are you using?
ubuntu

3. What version of python are you using?
python 3.6

Hello, I am writing a bot on pyTelegramBotAPI. I would like to reboot the bot when an error is caught.

Code:
except OverridingEx: # I catch an error
           bot.send_message (message.chat.id, 'Error, please contact the creator (@moodguy) to reboot the bot.') # you need to reboot here

**Comment by ComanderKai77** [comment]
Maybe this can help you:
https://github.com/eternnoir/pyTelegramBotAPI/issues/832#issuecomment-628226891
