### ISSUE TITLE
How to get a list of voted users?

### ISSUE THREAD

**Issue by YunSergey** [eternnoir/pyTelegramBotAPI#851]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.1

2. What OS are you using?
Windows 10

3. What version of python are you using?
3.8

Hi! 
Created a poll (not anonymous), created a handler that captures the fact of the user's response.
How to see which user chose which answer?

I did not find **PollAnswer**.

**Comment by Covalent5** [comment]
Hello, Telegram Bot API 4.2 which is the one with polls, is not supported. Its been 3 years since a new API is tested...

**Comment by drforse** [comment]
Show the code, please.

**Comment by YunSergey** [comment]
`@bot.message_handler(commands=['test'])
def run_pool(msg):
    question = 'poll #1'
    options = ['yes', 'no']
    test = bot.send_poll(msg.chat.id, question=question, options=options, is_anonymous=False)
    print('poll: ', test)

@bot.poll_handler(func=lambda msg:True)
def test_poll(msg):
    print('@bot.poll_handler(func=lambda msg:True)')
    print(msg)`

I can see how many users voted.
But I can’t get the result of the vote or get which user chose which answer option.

**Comment by drforse** [comment]
PollAnswer is available in telebot, you should use poll_answer_handler

**Comment by YunSergey** [comment]
> poll_answer_handler

Tell me where?

![image](https://user-images.githubusercontent.com/43809688/82398811-8287a400-9a75-11ea-8bbe-bf9e7c4516c6.png)

**Comment by ronmount** [comment]
1) `pip3 uninstall pytelegrambotapi`
2) Идем на главную страницу и там 
```
git clone https://github.com/eternnoir/pyTelegramBotAPI.git
cd pyTelegramBotAPI
python setup.py install
```
Ну либо вручную отредактируй библиотеки. В последнем коммите наблютаю poll_answer_handler
![Screenshot 2020-05-20 at 11 11 55](https://user-images.githubusercontent.com/22373231/82400931-0c8e3780-9a8b-11ea-9d1e-476a6d79b211.png)

**Comment by YunSergey** [comment]
> ```
> python setup.py install
> ```

Спасибо, с вашим вариантом получилось.

Хотя стояла эта же версия 3.7.1 и PyCharm сейчас указывает именно её, но у меня почему-то отсутствовал poll_answer_handler (специально искал его до этих манипуляций в __init__.py).

**Comment by Badiboy** [comment]
@YunSergey Версия с poll_answer_handler еще не опубликована в pypi. Указанный выше способ установки берет master branch с github. Поэтому и сработало. :)

**Comment by YunSergey** [comment]
> @YunSergey Версия с poll_answer_handler еще не опубликована в pypi. Указанный выше способ установки берет master branch с github. Поэтому и сработало. :)

Спасибо за помощь и поддержку библиотеки!
