### ISSUE TITLE
Reading all messages in a channel/group

### ISSUE THREAD

**Issue by dducted** [eternnoir/pyTelegramBotAPI#857]
Hi there,

How can the bot read all messages (can be admin as well) in a group/channel and print them to the console? 

Thanks for your help!

**Comment by dasshit** [comment]
Hi,

You can use bot.message_handler to look at the chat type or its ID (message.chat.id) if it is known in advance. Messages that match the conditions are output via print (message.text).

**Comment by dducted** [comment]
Hi,

Thanks for your reply and help. I tried putting something together, do you mind taking a look:

```
import telebot

API_TOKEN = '<API TOKEN>'

bot = telebot.TeleBot(API_TOKEN)

@bot.message_handler()
print(message.text)

bot.polling()
```

I do know the ID in advance but also unsure how to include it in the example above.

Thanks again!

**Comment by luisfmontes** [comment]
Try this out.
To get the GROUP_ID  use bot.send_message(message.chat.id, message.chat.id)

import telebot

API_TOKEN = '<API TOKEN>'
GROUP_ID = ''

bot = telebot.TeleBot(API_TOKEN)


@bot.message_handler(func=lambda message: True)
def echo_all(message):
    if message.chat.id is not GROUP_ID:
        bot.send_chat_action(message.chat.id, 'typing')
        bot.send_message(message.chat.id, 'Sorry private bot !!')
        return

    print('{} said: {}'.format(message.from_user.first_name, message.text))
    bot.send_chat_action(message.chat.id, 'typing')
    bot.send_message(message.chat.id, 'message received')


bot.polling()

**Comment by dducted** [comment]
Hi,

Thanks for your help! I've tried out your code and simplified it a lot but it appears that the bot is not printing any message (Channel) in the terminal. Used:
```
import telebot

API_TOKEN = ''
GROUP_ID = ''

bot = telebot.TeleBot(API_TOKEN)

@bot.message_handler(func=lambda message: True)
def echo_all(message):
    if message.chat.id is GROUP_ID:
        print('{}'.format(message.text))

bot.polling()
```
The bot is admin and I do use the correct channel id.

**Comment by luisfmontes** [comment]
I forgot to say that chat.id is integer
https://core.telegram.org/bots/api#chat

**Comment by dducted** [comment]
> I forgot to say that chat.id is integer
> https://core.telegram.org/bots/api#chat

Yes, I am actually using it as an INT but sadly that does not fix the issue. I am still not able to read any messages by the bot posted in the channel....

**Comment by luisfmontes** [comment]
We are looking at the wrong handler. 
Try this out, worked here.

@bot.channel_post_handler(func=lambda message: True)
def echo_all(message):
    print('Chanel {} message received: {}'.format(message.chat.title, message.text))
    bot.send_chat_action(message.chat.id, 'typing')
    bot.send_message(message.chat.id, 'message received')

**Comment by dducted** [comment]
Yes, that did the trick. Thanks a lot!!!
