### ISSUE TITLE
using next_offset in inline handler

### ISSUE THREAD

**Issue by amirarj** [eternnoir/pyTelegramBotAPI#858]
I have a list of entries that has more than 50 items. how can I answer_inline it with next_offset when user scrolling down? 

```
@bot.inline_handler(func=lambda query: True)
def query_text(query):
    entries = ['t1','t2','t3','t4','t5','t6','t7','t8','t9','t10'] # MORE THAN 50 ENTRIES
    results = []
    id = 0
    for i in entries:
        results.append(types.InlineQueryResultArticle(str(id), title=i, input_message_content=types.InputTextMessageContent(message_text=i)))
        id += 1                           
    bot.answer_inline_query(query.id, results, next_offset='5')
```
got this error when running above code:
```[b'{"ok":false,"error_code":400,"description":"Bad Request: RESULTS_TOO_MUCH"}']"```

**Comment by Badiboy** [comment]
https://core.telegram.org/bots/api#answerinlinequery

> answerInlineQuery
> Use this method to send answers to an inline query. On success, True is returned.
> No more than 50 results per query are allowed.

Use less results.
