### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by wmchina** [eternnoir/pyTelegramBotAPI#859]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 3.7.1

2. What OS are you using?
Ubuntu 18 (64 бит)
3. What version of python are you using?
python3

from telebot import apihelper
apihelper.proxy = {'https':'socks5://userproxy:password@proxy_address:port'}

Excuse me, is there any specific example of this agent? I write to the source code, still can't connect.
I'm like this
from telebot import apihelper
apihelper.proxy = {'https':'socks5://userproxy:password@proxy_address:port'}

 def listener(messages):
    
    
        for m in messages:

**Comment by Badiboy** [comment]
apihelper.proxy = {'https':'socks5**h**://userproxy:password@proxy_address:port'}

**Comment by wmchina** [comment]
apihelper.proxy = {'https':'socks5h://userproxy:password@proxy_address:port'}

{'https':'socks5h:  no {'https':'socks5:  ?
