### ISSUE TITLE
Don't initialize a default value to a mutable data structure, and compare with is None

### ISSUE THREAD

**Issue by rockneurotiko** [eternnoir/pyTelegramBotAPI#86]
In [telebot/util.py#L21](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/util.py#L21) you are using `Queue.Queue()' as default value to `queue`, but this is a mutable data structure, and you shouldn't do this. Try this in your interpreter (python3, change queue to Queue for python2):

```python
import queue

def test(q=queue.Queue()):
    q.put(1)
    print(q.qsize())

test()
test()
test()
```

To avoid this really bad behaviour, you need to initialize by default to `None` and check if it's `None` with `variable is not None` (or `is None`).

You are checking if a variable is `None` with `if not variable`, for example in line [telebot/util.py#L22](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/util.py#L22)

**Comment by eternnoir** [comment]
Thank you for the suggestion . :)
