### ISSUE TITLE
Is there a way to control image width/ height in Telegram Chat?

### ISSUE THREAD

**Issue by i-bond** [eternnoir/pyTelegramBotAPI#861]
Hello! I have a question about image sizing with the telebot library. Let's say, we have two images with different resolution, one is 1920x1080 and another 1280x720. Despite the difference they will be displayed like the same in Telegram Chat. Is there a way to control it with the send_photo method and change the default displaying?

**Comment by Badiboy** [comment]
Bot cannot control the Client behaviour.
