### ISSUE TITLE
Someone can help me with getUserProfilePhotos?

### ISSUE THREAD

**Issue by Seventty** [eternnoir/pyTelegramBotAPI#862]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
The newest version
2. What OS are you using?
Windows/Linux (both)
3. What version of python are you using?
3.8

Good morning, guys. How y'all been? 
I've been trying to get the user img using getUserProfilePhotos and i get this dict for e.g:

{'total_count': 2, 'photos': [[<telebot.types.PhotoSize object at 0x039785F8>, <telebot.types.PhotoSize object at 0x039787A8>, <telebot.types.PhotoSize object at 0x039785E0>]]}

I thought immediately get the info as we get the info of a dict, but i got this one:

count = data['total_count']
TypeError: 'UserProfilePhotos' object is not subscriptable

Someone can help me?

Here the piece of code: 

@bot.message_handler(commands=['pic'])
def pic(message):
    uId = message.from_user.id
    chatId = message.chat.id
    data = bot.get_user_profile_photos(uId,1,1)
    count = data['total_count']
    print(data)

Best wishes, guys.

**Comment by luisfmontes** [comment]
The return of bot.get_user_profile_photos(uId,1,1) it's not dict 
it's a UserProfilePhotos class object.
Try this out

@bot.message_handler(commands=['pic'])
def pic(message):
    uId = message.from_user.id
    chatId = message.chat.id
    data = bot.get_user_profile_photos(uId, 1, 1)
    count = data.total_count
    print(count)

**Comment by Seventty** [comment]
Thanks to that little help I was able to do a command on my own to show the user photo, thank you very much.
