### ISSUE TITLE
AttributeError: module 'telebot' has no attribute 'types'

### ISSUE THREAD

**Issue by kryakrya110** [eternnoir/pyTelegramBotAPI#863]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? pyTelegramBotAPI 3.7.1

2. What OS are you using? Ubuntu Ubuntu 18.04.4 LTS

3. What version of python are you using? Python 3.6.9

I can’t start any telebot script. I reinstalled libraries in different sequences. I run the python script.py command in PyCharm and throws an error
`keyboard1 = telebot.types.ReplyKeyboardMarkup(True)
AttributeError: module 'telebot' has no attribute 'types'
`

On Windows the same script and everything starts. Help please, why doesn’t it work on ubunt?

**Comment by Badiboy** [comment]
pip uninstall telebot
pip uninstall PyTelegramBotAPI
pip install PyTelegramBotAPI

**Comment by kryakrya110** [comment]
> pip uninstall telebot
> pip uninstall PyTelegramBotAPI
> pip install PyTelegramBotAPI

Traceback (most recent call last):
  File "ifinbot.py", line 4, in <module>
    bot = telebot.telebot('tokken')
AttributeError: module 'telebot' has no attribute 'telebot'
(venv) 1@1-MS-7721:~/1/bot$ pip list
Package          Version
---------------- ----------
certifi          2020.4.5.1
chardet          3.0.4
idna             2.9
pip              20.1.1
pkg-resources    0.0.0
pyTelegramBotAPI 3.7.1
requests         2.7.0
setuptools       46.4.0
six              1.15.0
urllib3          1.25.9
(venv) 1@1-MS-7721:~/1/bot$ python ifinbot.py
Traceback (most recent call last):
  File "ifinbot.py", line 4, in <module>
    bot = telebot.telebot('tokken')
AttributeError: module 'telebot' has no attribute 'telebot'

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/83019618-ed198080-a02f-11ea-9bb3-c03cf40a4c78.png)

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/83019684-07ebf500-a030-11ea-885e-d09699bcf7d1.png)
Find the difference.

**Comment by kryakrya110** [comment]
Now so, for half a day of the library there I delete the court I put keyboard1 = telebot.types.ReplyKeyboardMarkup (True)
AttributeError: 'function' object has no attribute 'ReplyKeyboardMarkup'

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/83021031-0ae7e500-a032-11ea-83e1-60346e94e5a1.png)
Everything works fine.

**Comment by kryakrya110** [comment]
> ![image](https://user-images.githubusercontent.com/5613421/83021031-0ae7e500-a032-11ea-83e1-60346e94e5a1.png)
> Everything works fine.


I still run it on Windows myself, it also works for me. On ubuntu writes errors. I do everything the same way.
