### ISSUE TITLE
Button problem

### ISSUE THREAD

**Issue by wmchina** [eternnoir/pyTelegramBotAPI#864]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 3.7.1
2. What OS are you using?

3. What version of python are you using?

python3

markup = types.ReplyKeyboardMarkup()
itembtna = types.KeyboardButton('a')
itembtnv = types.KeyboardButton('v')
itembtnc = types.KeyboardButton('c')
itembtnd = types.KeyboardButton('d')
itembtne = types.KeyboardButton('e')
markup.row(itembtna, itembtnv)
markup.row(itembtnc, itembtnd, itembtne)
tb.send_message(chat_id, "Choose one letter:", reply_markup=markup)

This is for work
How do the following work?

reply_markup={"inline_keyboard":[[{"text":"btn1","url":"https://github.com/"},{"text":"btn1","url":"https://github.com/"}],[{"text":"btn1","url":"https://github.com/"},{"text":"btn1","url":"https://github.com/"}]]}

**Comment by wmchina** [comment]
tb.send_message(chatid, "Choose one letter:", reply_markup=markup, resize_keyboard='true')
Why resize_ Keyboard is not working

**Comment by goldenrump** [comment]
_Optional_. Requests clients to resize the keyboard vertically for optimal fit (e.g., make the keyboard smaller if there are just two rows of buttons). Defaults to false, in which case the custom keyboard is always of the same height as the app's standard keyboard

source: [ReplyKeyboardMarkup at Telegram/bots/api](https://core.telegram.org/bots/api#replykeyboardmarkup)
