### ISSUE TITLE
How to add a member to the group?

### ISSUE THREAD

**Issue by Agha-Shadi** [eternnoir/pyTelegramBotAPI#869]
OS: win 10 - Python: 3.7.2 - TeleBot: 27.04.2020 release

wonder if there's a way of adding a member to a group. sounds like there isn't

**Comment by goldenrump** [comment]
bots can’t invite.

**Comment by Agha-Shadi** [comment]
thanks. so is there a way to control a real user with my bot using this python module? so that then the real user can add a member to the group
