### ISSUE TITLE
Embedded image in html parse mode issue

### ISSUE THREAD

**Issue by trikunai** [eternnoir/pyTelegramBotAPI#871]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.0
2. What OS are you using?
Manjaro archlinux
3. What version of python are you using?
python3

hi guys,

in am trying this package and build a bot that post messages in html_mode parse. And i embeeded a image like this https://stackoverflow.com/questions/38685619/how-to-send-an-embedded-image-along-with-text-in-a-message-via-telegram-bot-api . Also tried with disable_web_page_preview=False but it keeps happening

but not all messages are diplaying the embedded image always. The bot post a message each 5 seconds, and not all messages have the image (but all the html string has the image inside) so i dont know what this can be..

it looks like that the bot after so many messages sometines doesnt take care the <ahref> image "trick"... 
any help please?

**Comment by Badiboy** [comment]
The URLs preview is managed by the Telegram or Telegram client. You can ask them to preview by 
setting disable_web_page_preview=False, so it's further their work to make a preview for your HTML. May be if you send messages too fast, Telegram temporary ban this activity and stops previews.
