### ISSUE TITLE
Checkbox - how to get multiple options from keyboard?

### ISSUE THREAD

**Issue by GraphGrailAi** [eternnoir/pyTelegramBotAPI#874]
How to get multiple options from keyboard?
If i have `InlineKeyboardMarkup` and several buttons 
```
    itembtna = types.InlineKeyboardButton('a', switch_inline_query="")
    itembtnv = types.InlineKeyboardButton('v', switch_inline_query="")
    itembtnc = types.InlineKeyboardButton('c', switch_inline_query="")
```
How to allow user choose several options at once, maybe long pressing to button ?  - checkbox like behavior 

1. What version of pyTelegramBotAPI are you using?
3.5
2. What OS are you using?
Ubuntu
3. What version of python are you using?
3.6.8

**Comment by Badiboy** [comment]
It's not possible in Telegram.
