### ISSUE TITLE
Send_audio() doesn't work

### ISSUE THREAD

**Issue by S4RX** [eternnoir/pyTelegramBotAPI#877]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? - the last

2. What OS are you using? - the last

3. What version of python are you using? - the last

Hello dear developers.  please tell me why the send_audio () method does not work?  The bot then sends audio recordings, or simply refuses to do it.  To check the problem, I wrote a simple code that sends the same track to the same chat_id () and nothing happens.

**Comment by Badiboy** [comment]
> To check the problem, I wrote a simple code that sends the same track to the same chat_id () and nothing happens.

Where is it?

**Comment by S4RX** [comment]
#Sorry, i think i pin code
import telebot
import misc #file with APIToken 
import json
import aiohttp
import asyncio
from time import time
import requests
from bs4 import BeautifulSoup
from unicodedata import normalize
TOKEN = misc.token
bot = telebot.AsyncTeleBot(TOKEN)
URL = 'https://api.telegram.org/bot' + TOKEN + '/'
ADMIN = #in original here is chat_id of account, which i send audio 

async def send_audio():

	pyt = r'C:\pybot\Songs\@chat_id\Ленинград — Рыба _ Leningrad — Fish.mp3'

	with open(pyt, 'rb') as audio:
		#print()
		bot.send_audio(ADMIN, audio)
		
		#print( +" " + ' send to ' + " " + str(chat_id))
async def main():
	await send_audio()

if __name__ == '__main__':

	asyncio.run(main())

**Comment by Badiboy** [comment]
> What version of pyTelegramBotAPI are you using? - the last
> What OS are you using? - the last
> What version of python are you using? - the last

Make request properly.

**Comment by Badiboy** [comment]
```
res = bot.send_audio(ADMIN, audio)
print(str(res))
```
What will be there?

**Comment by S4RX** [comment]
<telebot.util.AsyncTask object at 0x03F18150>

**Comment by Badiboy** [comment]
Ah, it's async, sorry. Try to change your example to syncronous to make it more observable, I did not work with asnyc version.

**Comment by S4RX** [comment]
I changed to syncronus and it`s work. But i need more speed, how i can take it?

**Comment by Badiboy** [comment]
YOU may want lot of things, but TELEGRAM do not want you to do something. I think you meet limitations from Telegram.

**Comment by S4RX** [comment]
ok, thank you
