### ISSUE TITLE
No way to set offset, How to listen only to last message when bot were off ?

### ISSUE THREAD

**Issue by Nitroteam** [eternnoir/pyTelegramBotAPI#878]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Latest (3.7.1)
2. What OS are you using?
Mint Cinnamon 19.3
3. What version of python are you using?
python 3.8

I didn't find anything related to this on docs . Someone help me please !

**Comment by rabx2i** [comment]
Describe your question in more detail.
