### ISSUE TITLE
Add the bot to asyncio event loop

### ISSUE THREAD

**Issue by Danialzz** [eternnoir/pyTelegramBotAPI#881]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.1
2. What OS are you using?
macOS
3. What version of python are you using?
3.7.7

Hi
I wanted to know how to add the telegram bot to asyncio event loop.
I've tried this:
```
bot = telebot.AsyncTeleBot('API TOKEN')
loop = asyncio.get_event_loop()
bot_task = loop.create_task(bot.polling())
another_task = loop.create_task(foo())
loop.run_until_complete(asyncio.wait([bot_task, another_task]))
loop.close()
```
But since bot.polling() is not asynchronous, it is executed without switching to the other task.

**Comment by fgallaire** [comment]
Use Webhooks ?

**Comment by Badiboy** [comment]
> Asynchronous delivery of messages
> There exists an implementation of TeleBot which executes all send_xyz and the get_me functions asynchronously.

bot_polling is not asyncroized.
