### ISSUE TITLE
Is statistics needed?

### ISSUE THREAD

**Issue by dtalkachou** [eternnoir/pyTelegramBotAPI#882]
There was an idea to create statistics collection similar to all actions (in more detail by categories), unique users.  It is also possible to automatically create a database with users, which subsequently will create a simple method for mass mailing.

Interested in your opinion, does this framework need this and what statistics would be useful to collect?

**Comment by tohabyuraev** [comment]
Good idea. But there are several statistics services like Chatbase, Dashbot, etc.
How do you want to collect, store ans show statistics?

**Comment by dtalkachou** [comment]
> How do you want to collect, store ans show statistics?
I wanna to collect stats in the database.
