### ISSUE TITLE
Inline mode cycle

### ISSUE THREAD

**Issue by 1JeimiP1** [eternnoir/pyTelegramBotAPI#883]
1. pyTelegramBotAPI    3.7.1

2. Windows 10

3. Python 3.8.3 

How can I make the output of buttons in inline mode using a cycle, and not one button at a time?
```
r = types.InlineQueryResultVoice('id', 'link',  'title')
        bot.answer_inline_query(inline_query.id, [r], cache_time=1) 
```
In this code I must add buttons only one by one, but how I can do this in cycle?

Ty for help)

**Comment by 1JeimiP1** [comment]
help me someone pls(

**Comment by sadpenguinn** [comment]
`
replies = []
for list_elem in some_list:
    replies.append(types.InlineQueryResultVoice('id', 'link',  'title'))
bot.answer_inline_query(inline_query.id, replies, cache_time=1) 
`
If I understood the problem correctly :)

**Comment by 1JeimiP1** [comment]
> `
> 
> replies = []
> 
> 
> 
> for list_elem in some_list:
> 
>     replies.append(types.InlineQueryResultVoice('id', 'link',  'title'))
> 
> bot.answer_inline_query(inline_query.id, replies, cache_time=1) 
> 
> `
> 
> 
> 
> If I understood the problem correctly :)

Thanks a lot, I’ll try that)

**Comment by 1JeimiP1** [comment]
> replies = []
> 
> for list_elem in some_list:
> 
>     replies.append(types.InlineQueryResultVoice('id', 'link',  'title'))
> 
> bot.answer_inline_query(inline_query.id, replies, cache_time=1) 
> 
> 
> 
> If I understood the problem correctly :)

That’s really works, ty man <3
