### ISSUE TITLE
Welcome bot (yourself) in group

### ISSUE THREAD

**Issue by dducted** [eternnoir/pyTelegramBotAPI#884]
I was wondering how the bot can welcome himself? I started with code like:

```
@bot.message_handler(func=lambda m: True, content_types=['new_chat_members'])
def on_user_joins(message):

    if message.new_chat_members.id == bot.id:
        bot.reply_to(message, 'hi')
```

However `message.new_chat_members.id` and `bot.id` seems to be wrong here...

Thanks for your help!

**Comment by 1JeimiP1** [comment]
Try this:
```
@bot.message_handler(content_types=["new_chat_members"])
def handler_new_member(message):
    new_user_name = message.new_chat_member.first_name
    #bot.send_message(message.chat.id, "Welcome, {0}!".format(new_user_name))
```

And I would be grateful if you could help me with my problem described in the previous issue!

**Comment by dducted** [comment]
I tried that snippet however it didn't work. By the look of it, it doesn't look like it exclusively greets the bot itself after adding it.

**Comment by 1JeimiP1** [comment]
> I tried that snippet however it didn't work. By the look of it, it doesn't look like it exclusively greets the bot itself after adding it.

Oh, wait a sec, I’ll try to write a new one

**Comment by 1JeimiP1** [comment]
I always have that error:
_AttributeError: 'Message' object has no attribute 'new_chat_participant'_

**Comment by Badiboy** [comment]
https://core.telegram.org/bots/api#message

![image](https://user-images.githubusercontent.com/5613421/85200509-a7836700-b300-11ea-92e9-090020eded04.png)

**Comment by 1JeimiP1** [comment]
> https://core.telegram.org/bots/api#message
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5613421/85200509-a7836700-b300-11ea-92e9-090020eded04.png)
> 
> 

Yes, I saw this, but probably there is some problems with library PyTelegramBotAPI.

**Comment by Badiboy** [comment]
Probably there is some problems with somewhere else:

![image](https://user-images.githubusercontent.com/5613421/85200595-73f50c80-b301-11ea-9f70-8d79c3ad38d3.png)

**Comment by 1JeimiP1** [comment]
> Probably there is some problems with someone else:
> 
> ![image](https://user-images.githubusercontent.com/5613421/85200595-73f50c80-b301-11ea-9f70-8d79c3ad38d3.png)

check this:

```
name = message.new_chat_members.username
AttributeError: 'list' object has no attribute 'username'
```

**Comment by dducted** [comment]
```       
 new_members = message.new_chat_members
   for new_mem in new_members:
      if new_mem.id == bot.id:
```
Did the trick for me
