### ISSUE TITLE
Why bot doesn't support inline results for voice_note type

### ISSUE THREAD

**Issue by sadpenguinn** [eternnoir/pyTelegramBotAPI#885]
Hello everyone! Why _Telebot_ doesn't support inline results for `video_note` type? I did not find class like `InlineQueryResultCachedVideo` for video notes.

**Comment by 1JeimiP1** [comment]
> Hello everyone! Why _Telebot_ doesn't support inline results for `voice_note` type? I did not find class like `InlineQueryResultCachedVideo` for voice notes.

`InlineQueryCachedAudio`

**Comment by 1JeimiP1** [comment]
> Hello everyone! Why _Telebot_ doesn't support inline results for `voice_note` type? I did not find class like `InlineQueryResultCachedVideo` for voice notes.

Maybe `InlineQueryResultCachedAudio` will help you?

P.S. help me with my issue pls

**Comment by 1JeimiP1** [comment]
> > Hello everyone! Why _Telebot_ doesn't support inline results for `voice_note` type? I did not find class like `InlineQueryResultCachedVideo` for voice notes.
> 
> Maybe `InlineQueryResultCachedAudio` will help you?
> 
> P.S. help me with my issue pls https://github.com/eternnoir/pyTelegramBotAPI/issues/883

**Comment by goldenrump** [comment]
> Hello everyone! Why _Telebot_ doesn't support inline results for `video_note` type? I did not find class like `InlineQueryResultCachedVideo` for video notes.

[Video_note (executing code from telebot)](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/types.py#L1881) 

[inlinequeryresultcachedvideo in Telegtam/bot/api](https://core.telegram.org/bots/api#inlinequeryresultcachedvideo)
