### ISSUE TITLE
Parsing techniques

### ISSUE THREAD

**Issue by Jzarecta** [eternnoir/pyTelegramBotAPI#89]
I wrote an IRC bot and instead of parsing I use find(). However I wonder if there are some regular REGEXP examples in order to parse the user inputs. 
```python
def commands(nick,channel,message):
   if message.find(botnick+b': shellium')!=-1:
      ircsock.send(b'PRIVMSG %s :%s: Shellium is awesome!\r\n' % (channel,nick))
   elif message.find(botnick+b': help')!=-1:
      ircsock.send(b'PRIVMSG %s :%s: My other command is shellium.\r\n' % (channel,nick))
```
So doing:
```
    MyBot help
    > Dave: My other command is shellium.
```

**Comment by pevdh** [comment]
I have to be honest, I simply have no clue what you are talking about :)
Can you try to elaborate?

**Comment by Jzarecta** [comment]
I am just looking for the code of a bot that handles more complex comands and arguments like a weight convertion bot for example. To convert from kg to lbs I would use something like:
```
/c 32kg
70.5479
```
In the telegram bot, I saw the decorator parse delcare commands like 'start' and 'help' which obviously will parse the message and get the command '/c' 

I want to know how to about parsing the argument like **32kg**, which in itself would need to enable a second parser of '32' and 'kg' in order to know if it should divide or multiply for to the other unit.

I could do some python REGEX for this, but if the code already recognize commands from arguments would rather use that.

**Comment by pevdh** [comment]
You'll have to write your own implementation for that. There might be some conversion Python libs out there though.
