### ISSUE TITLE
cannot get bold text

### ISSUE THREAD

**Issue by PasaOpasen** [eternnoir/pyTelegramBotAPI#891]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? **3.7.1**

2. What OS are you using? **Windows 10**

3. What version of python are you using? **3.8**

cannot message bold text by telebot:

```python
bot.send_message(message.chat.id, "**text**", parse_mode="Markdown") 
# text

bot.send_message(message.chat.id, "*text*", parse_mode="Markdown") 
# text

bot.send_message(message.chat.id, "**text**") 
# **text**

bot.send_message(message.chat.id, "*text*") 
# *text*
```

**Comment by dducted** [comment]
Use:

`bot.reply_to(message, "*BOLD TEXT*", parse_mode='Markdown')`

**Comment by PasaOpasen** [comment]
Sorry, it was my mistake. It works with send_message and reply_to both
