### ISSUE TITLE
Looking for self destruction of issued commands / bot replies

### ISSUE THREAD

**Issue by dducted** [eternnoir/pyTelegramBotAPI#893]
I was wondering if there is an easy way to self destruct messages after X amount of time without using `time.sleep` which halts the hole code?

I do have the snippets to remove issued messages:
```
bot.delete_message(message.chat.id, msg.message_id)
bot.delete_message(message.chat.id, message.message_id)
```

However I am not happy with `time.sleep` as mentioned above. Async might be a solution however I was hoping for sth easier, since my code is not async written.

**Comment by dducted** [comment]
Ok, `bot.answer_callback_query` was the answer.

**Comment by goldenrump** [comment]
`bot.delete_message(message.chat.id, message.message_id,timeout=sometime)` try it

**Comment by dducted** [comment]
Hi @goldenrump,

Thanks for your reply. I tired the snipped you mentioned above however I am getting:

`TypeError: delete_message() got an unexpected keyword argument 'timeout'`

**Comment by Badiboy** [comment]
No "timout" parameter in delete_message.
Should be added...
