### ISSUE TITLE
Stop poll - "Poll can't be stopped" Why?

### ISSUE THREAD

**Issue by Seruios** [eternnoir/pyTelegramBotAPI#896]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? newest one

2. What OS are you using? Win 10

3. What version of python are you using? 3 8 2

ApiException('A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: poll can't be stopped"}']') 

Why can't be stopped? Any reason?

**Comment by Badiboy** [comment]
May be poll is stopped, or wrong ID, or there is some restriction on poll stops...

**Comment by qadirsuh** [comment]
can anybody answer this please. not this repo question but its from nodeJS npm module
`node-telegram-bot-api`
https://stackoverflow.com/questions/64062772/etelegram-400-bad-request-poll-cant-be-stopped
