### ISSUE TITLE
Determine which button with `request_location` is clicked

### ISSUE THREAD

**Issue by birdy90** [eternnoir/pyTelegramBotAPI#897]
Please answer these questions before submitting your issue. Thanks!
1. What version of pyTelegramBotAPI are you using? 3.6.6
2. What OS are you using? Hm.. windows with docker..
3. What version of python are you using? Some 3.5+

Hello! I have some issues handling buttons. There are two buttons on one keyboard markup with `request_location=True`:

```python
keyboard = telebot.types.ReplyKeyboardMarkup()
keyboard.row(telebot.types.KeyboardButton('First location', request_location=True))
keyboard.row(telebot.types.KeyboardButton('Second location', request_location=True))
self.bot.send_message(message.chat.id, 'Choose one?', reply_markup=keyboard)
```

And I can push either of them and get my location. It works. But location is sent as an answer to `Choose one?` message, so I can't determine which one of these buttons I clicked. Because when it is sent as reply, I don't get the text of a clicked button. 

How can I handle this?

**Comment by Badiboy** [comment]
You cannot see what user clicks except you are using inline buttons with unique "data".

**Comment by birdy90** [comment]
thank you!
