### ISSUE TITLE
How to get message in group which is sent from another bot 

### ISSUE THREAD

**Issue by HYaroslav** [eternnoir/pyTelegramBotAPI#898]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.1
2. What OS are you using?
Windows 10 Home
3. What version of python are you using?
3.7.4

I have a group with 2 bots. When a new message is sent by me - the first bot handle that message by message_handler. But when a new message is sent by second bot - the first bot does not handle it. 
How can I handle message which is sent by bot?

**Comment by Badiboy** [comment]
Totally impossible. Telegram bot cannot see messages send by another bot.
