### ISSUE TITLE
How to get user id from a message sent on group?

### ISSUE THREAD

**Issue by mshah21202** [eternnoir/pyTelegramBotAPI#899]
title says it all, I'm trying to get the user id of a message sent on my group, then I'll use that user id to send a message using my bot. I would really love help with that, I'm open to suggestions on betters ways to privately reply to certain commands that are typed in group chat

@bot.message_handler(commands=['list'])
def send_list(message):
    links = "\n".join(map(str, linkList))
    resultLinks = links.replace("(", "").replace(")", "").replace("'", "").replace(",", "")
    resultLinks_text = "Here are the links for the accounts you must follow before posting your account:\n{}".format(
        resultLinks)
    bot.send_message(userid, resultLinks_text)

**Comment by goldenrump** [comment]
`bot.send_message(message.chat.id, resultLinks_text)`

If you need reply to user, use: `bot.reply_to(message, text)`

**Comment by mshah21202** [comment]
> `bot.send_message(message.chat.id, resultLinks_text)`
> 
> If you need reply to user, use: `bot.reply_to(message, text)`

I'm afraid that does not fulfill my question, let me explain again. When the bot detects a message sent on the group, I want the bot to privately send a message to the user who just sent the message. From what I know, user ID and chat ID are the same for the same user. So if I am able to achieve the user ID of the person who sent the message, I can privately message them

**Comment by Badiboy** [comment]
1. Use "from": https://core.telegram.org/bots/api#message

2. You cannot if user did not start your bot yet. Bot cannot initiate conversations.

**Comment by goldenrump** [comment]
> > `bot.send_message(message.chat.id, resultLinks_text)`
> > If you need reply to user, use: `bot.reply_to(message, text)`
> 
> I'm afraid that does not fulfill my question, let me explain again. When the bot detects a message sent on the group, I want the bot to privately send a message to the user who just sent the message. From what I know, user ID and chat ID are the same for the same user. So if I am able to achieve the user ID of the person who sent the message, I can privately message them

`message.from_user.id` as far as I remember it gives user id.

**Comment by mshah21202** [comment]
> > > `bot.send_message(message.chat.id, resultLinks_text)`
> > > If you need reply to user, use: `bot.reply_to(message, text)`
> > 
> > 
> > I'm afraid that does not fulfill my question, let me explain again. When the bot detects a message sent on the group, I want the bot to privately send a message to the user who just sent the message. From what I know, user ID and chat ID are the same for the same user. So if I am able to achieve the user ID of the person who sent the message, I can privately message them
> 
> `message.from_user.id` as far as I remember it gives user id.

Thank you very much, idk why when I tried using this before it wouldn't work. It works now as intended

**Comment by MarsDiplomatToEarth** [comment]
how can i get myself message
