### ISSUE TITLE
Command handlers

### ISSUE THREAD

**Issue by Jzarecta** [eternnoir/pyTelegramBotAPI#90]
So on your example demo script you have something like this:
```python
@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
         bot.reply_to(message, 'Howdy, how are you doing?')
```

However I am not sure if this is a /start AND /help that execute the message, or can I filter a function for either of the commands, so something like this:
```python
@bot.message_handler(commands=['start', 'help', 'convert'])
def send_welcome(message):
         bot.reply_to(message, 'Howdy, how are you doing?')
def send_convert(message)
          bot.reply_to(message, 'This is my convert function')
```
Or do I have to do for each command a handler, like:
```python
@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
         bot.reply_to(message, 'Howdy, how are you doing?')

@bot.message_handler(commands=['convert'])
def send_convert(message)
          bot.reply_to(message, 'This is my convert function')
```

Regards.

**Comment by pevdh** [comment]
The latter is indeed the correct approach. Decorators only influence the function they decorate.

**Comment by Jzarecta** [comment]
What about if I want to get an argument beside the comand, let say:
/convert 32
Do I need to use a python regular argv module or does the fw have a method to differntiate command from argument. Or do I have to leave it to REGEX?

**Comment by Jzarecta** [comment]
How to avoid getting quoted when the bot reply?

**Comment by Marzal** [comment]
To avoid getting quoted you have to use the send_message method
tb.send_message(chatid, text)

Example:
```python
@bot.message_handler(commands=['help'])
    def command_help(m):
    bot.send_message(m.chat.id, "hola")
```

I would recommend to read the Docu and the [examples ](https://github.com/eternnoir/pyTelegramBotAPI/tree/master/examples), they are very illustrative.

**Comment by Jzarecta** [comment]
I looked at the examples where they use the **m.chat.id** but get several errors:
```
AttributeError: 'int' object has no attribute 'chat'
```

**Comment by Marzal** [comment]
There should be an error in your code

This is a very basic example:
```python
import telebot

TOKEN = '<token_string>'
bot = telebot.TeleBot(TOKEN)

@bot.message_handler(commands=['start'])
def command_start(m):
    bot.send_message(m.chat.id, "Text of message")

bot.polling()
```

**Comment by Jzarecta** [comment]
yeah kept getting the same error, I even changed the original def foo(message) with def foo(m). I wonder if I can ouput the content of the message object to see why is it treating it like int. Is this maybe a python3 issue?
Here is my code:
```python
@bot.message_handler(commands=['d','dolares'])
def send_convert_pesos(m):
    cid = m.chat.id
    #peso = float(message.split()[1])
    with urllib.request.urlopen("http://api.coindesk.com/v1/bpi/currentprice.json") as coindesk:
        data = coindesk.read()
        jobject = json.loads(data.decode('utf-8'))
        val=jobject['bpi']['USD']['rate']
        usd=float(val)
        dolar= "USD : $"+'{:,.2f}'.format(usd,'.2f')
        bot.reply_to(m.chat.id, dolar)
```

**Comment by Marzal** [comment]
I'm not an expert but I think that you have to use the objetc "message" (in your case "m") with bot.reply not "cid". Or you should use the attrib chat.id (cid) with the method "send_message"
```python
bot.send_message(m.chat.id, dolar)
#OR
bot.send_message(cid, dolar)
```
if you don want the text to be quoted.

**Comment by Jzarecta** [comment]
Thanks changing the method from reply_to to send_message worked.
