### ISSUE TITLE
Photo define as 'NoneType'

### ISSUE THREAD

**Issue by Sapf3ar** [eternnoir/pyTelegramBotAPI#900]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.7.1

2. What OS are you using? Windows

3. What version of python are you using? 3.6

Script :
 file_info = bot.get_file(message.document.file_id)
        downloaded_file = bot.download_file(file_info.file_path.m)
        src = 'C:/Users/minio/PycharmProjects/untitled/Images' + message.document.file_name
        print(str(file_info))
        with open(src, 'wb') as new_file:
            new_file.write(downloaded_file)

So, photo define as 'NoneType'

**Comment by Badiboy** [comment]
https://core.telegram.org/bots/api#document

> **Document**
> This object represents a general file (as opposed to photos, voice messages and audio files).

Use 
`message.photo[0].file_id`
