### ISSUE TITLE
Add parse_mode in TeleBot class

### ISSUE THREAD

**Issue by daveusa31** [eternnoir/pyTelegramBotAPI#905]
Good afternoon. I think we should add the parse_mode parameter to the TeleBot class.
To avoid being specified every time a function is called

I want to:

```python
bot = telebot. TeleBot("token", parse_mode="HTML")
bot.send_message(chat_id, text)
bot.send_message(chat_id, text)
bot.send_message(chat_id, text)
```

And now:

```python
bot = telebot. TeleBot("token")
bot.send_message(chat_id, text, parse_mode="HTML")
bot.send_message(chat_id, text, parse_mode="HTML")
bot.send_message(chat_id, text)
```

**Comment by daveusa31** [comment]
If I implement this myself and make a pull request, will the repository owner miss it?
Suddenly, the owner has already had such thoughts, but he decided to refuse?

**Comment by Badiboy** [comment]
For me it's not usefull, I use most of messages without parse_mode and just some with "HTML".

But changing the "default" behaviour may be usefull for cases like yours. 

If you implement it accurately and make a proper pull request - we'll check if it can be merged.

**Comment by daveusa31** [comment]
It's done
https://github.com/eternnoir/pyTelegramBotAPI/pull/906

**Comment by Badiboy** [comment]
+
