### ISSUE TITLE
I can not handler message with animation 

### ISSUE THREAD

**Issue by mbrantov** [eternnoir/pyTelegramBotAPI#907]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI-3.7.1.dist-info

2. What OS are you using?
Mac OS 10.15.5

3. What version of python are you using?
3.8

For example you can send emoji text = 🏀 and try to catch it
@bot.message_handler(content_types=['text']) don't work in this case

**Comment by daveusa31** [comment]
Use
`python
@bot.message_handler(content_types=["dice"]
)`
