### ISSUE TITLE
Can't send attachments without reading from an actual file

### ISSUE THREAD

**Issue by DamianX** [eternnoir/pyTelegramBotAPI#91]
I can't send photos (and I assume other file types) using TeleBot.send_photo() if the second argument is a BytesIO "file". I think we need a way to manually specify/automatically figure out the file extension, without looking at the file's actual name.

I made this little test to demonstrate the issue: [Click me!](https://gist.github.com/DamianX/f04d79e814f5522699d1)

Following is the error that gets printed:
```
2015-10-25 13:54:46,814 (__init__.py:159 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Error: Photo has unsupported extension. Use one of .jpg, .jpeg, .gif, .png, .tif or .bmp"}']"
```
Following is the logged python-requests' request:
```
/bot1234567890:ThisIsIndeedNotMyRealToken/sendPhoto?chat_id=13631709 HTTP/1.1
Host: api.telegram.org
Accept-Encoding: gzip, deflate
User-Agent: python-requests/2.8.1
Content-Length: 473973
Content-Type: multipart/form-data; boundary=415fae3fe054411f8d6752e865040ed1
Accept: */*
Connection: keep-alive

'
send: b'--415fae3fe054411f8d6752e865040ed1
Content-Disposition: form-data; name="photo"; filename="photo"

\x89PNG[...]
reply: 'HTTP/1.1 400 Bad Request
'
header: Server header: Date header: Content-Type header: Content-Length header: Connection 
```

I can see parameters in there that could be of interest: name and filename.

**Comment by maximko** [comment]
Hi.
Just add attribute __name__ to your _io.BytesIO_ object, e.g.:
```
thing = io.BytesIO(image_data)
thing.name = 'Lenna.png'
```

**Comment by Kondra007** [comment]
Why not using this?
```python
with open('image.png', 'rb') as file:
    bot.send_photo(1234567, file)
```

Or have I got you wrong?

**Comment by DamianX** [comment]
@maximko 
That's...so *python*. Awesome, thanks!
@Kondra007 
I wish to avoid saving to file, since in my bot I fetch the image from the internet. Thank you anyway!
