### ISSUE TITLE
"service" content_type

### ISSUE THREAD

**Issue by fgallaire** [eternnoir/pyTelegramBotAPI#910]
`new_chat_members, left_chat_member, new_chat_title, new_chat_photo, delete_chat_photo, group_chat_created, supergroup_chat_created, channel_chat_created, migrate_to_chat_id, migrate_from_chat_id, pinned_message` are not `content_type` but service message flavors.
So trigger all service messages is a pain. At least, keeping the same design, we should have a `service` content type equivalent to the 11 service message flavors.

**Comment by Badiboy** [comment]
`bot.message_handler(content_types=['left_chat_member', 'new_chat_title', 'new_chat_photo', 'delete_chat_photo', 'pinned_message'...])`

No pain. Just 1 line of code.

**Comment by fgallaire** [comment]
hello @Badiboy, 
Thanks a lot for your work on this really great software, hope you can be open to other views.

> `bot.message_handler(content_types=['left_chat_member', 'new_chat_title', 'new_chat_photo', 'delete_chat_photo', 'pinned_message'...])`
> 
> No pain. Just 1 line of code.

Just an horrible bug-prone enumeration isn't it ??

**Comment by Badiboy** [comment]
I don't know, I do not have any problems with creating a bug-free list of 11 elements.

**Comment by fgallaire** [comment]
> I don't know, I do not have any problems with creating a bug-free list of 11 elements.

It's bug free if it's created one time in the lib code, not each time in the user code.

**Comment by Badiboy** [comment]
> bot.message_handler(content_types=['service'])
> Great API = great code isn't it ?

content_type corresponds 1 to 1 to the content of the Message:
https://core.telegram.org/bots/api#message

Content types that are not presented there will be confusing.

**Comment by fgallaire** [comment]
It's a great design improvement for close to 0 work in the the lib....

**Comment by fgallaire** [comment]
> content_type corresponds 1 to 1 to the content of the Message:
> https://core.telegram.org/bots/api#message

I know, but 

> Content types that are not presented there will be confusing.

Pyrogram (a MTProto python lib), is doing this sort of API improvement (supply a `service` message type) and it's really the way to go.

**Comment by Badiboy** [comment]
Finally seems that I found the neutral solution. :)

![image](https://user-images.githubusercontent.com/5613421/98004240-bcb8e800-1e00-11eb-8897-e4dd5f88325a.png)

```
bot.message_handler(content_types=utils.content_type_service):
    ...
```

Suits your needs?

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/commit/7a3fd30f6ac7c06e39673665f9ec2817ad64294c
