### ISSUE TITLE
Can someone help me with something? User input

### ISSUE THREAD

**Issue by Seventty** [eternnoir/pyTelegramBotAPI#912]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
The newest, sir.

2. What OS are you using?
Windows 10 & android(termux)

3. What version of python are you using?
3.8

Morning, afternoon or night, beautiful creatures. I've been working for a while with the eternnoir api and i've been lost trying to do something... I was trying to do a command with a user response, example:

Someone type: /dice
bot says: type some number
User type: 3
and the bot reply some another number like 6 or smth.

how can I make it wait for an user answer?

Really thx for read, best wishes.

**Comment by Seventty** [comment]
I focused in the poll function and i need an user answer (to add the options by loop) obviously without the [/] prefix.

**Comment by Badiboy** [comment]
Avoid such a crap in Subject and text.

**Comment by Seventty** [comment]
Interesting answer.
