### ISSUE TITLE
Bot stops responding with no errors

### ISSUE THREAD

**Issue by mshah21202** [eternnoir/pyTelegramBotAPI#914]
For some reason, my bot will stop responding to commands and any kind of messages after some time. No errors or exceptions popup in the console. I have no idea what could cause this

This is my polling set up
 ```
while True:
     try:
         bot.polling()
     except:
         sleep(5)
```

**Comment by mshah21202** [comment]
I'm currently testing #251
I'll reopen if it happens again

**Comment by mshah21202** [comment]
I'm still experiencing the same unresponsive issue.

**Comment by goldenrump** [comment]
```
import sys

while True:
    try:
        bot.polling()
    except Exception as e:
        tb = sys.exc_info()[2]
        print(e,
              '\nat line {}'.format(tb.tb_lineno))
```
