### ISSUE TITLE
how can i delete service message

### ISSUE THREAD

**Issue by MarsDiplomatToEarth** [eternnoir/pyTelegramBotAPI#920]
how can i delete service message

Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
the newest one 
2. What OS are you using?
windows
3. What version of python are you using?
2

**Comment by MarsDiplomatToEarth** [comment]
@bot.message_handler(func=lambda m: True, content_types=['new_chat_participant','new_chat_participant','left_chat_member', 'new_chat_title', 'new_chat_photo', 'delete_chat_photo'])
def on_user(message):
    print(message)
    bot.delete_message(message.chat.id, message.message_id)



not work

**Comment by Badiboy** [comment]
Does bot have enough rights to delete messages there?

**Comment by MarsDiplomatToEarth** [comment]
> 
> 
> Does bot have enough rights to delete messages there?
yes but service message someone joined the group and someone left the group is still existing

**Comment by Badiboy** [comment]
Show the screen with bot permissions?
