### ISSUE TITLE
how can i get myself message id and chat id from the message my bot send

### ISSUE THREAD

**Issue by MarsDiplomatToEarth** [eternnoir/pyTelegramBotAPI#921]
how can i get myself message id and chat id from the message my bot send

**Comment by MarsDiplomatToEarth** [comment]
bot.send_message()

**Comment by mrpes** [comment]
Check [Telegram bot documentation](https://core.telegram.org/bots/api), I guess all methods work same and return same things
```python
message = bot.send_message(0123456789, text='Hello')
message_id = message.message_id
chat_id = message.chat.id
```
