### ISSUE TITLE
How to Forward all income messages?

### ISSUE THREAD

**Issue by 4omp** [eternnoir/pyTelegramBotAPI#922]
Hi!
1) I try to make telegram bot that's forward all messages, photos, videos, link that it recieve to me. I found this code, But it only forward text, no attachments. I try to add "content_types=["text", "photo", "video"]", and use message.photo & etc, it doesn't work too

```
> @bot.message_handler(func=lambda m: True)
> def messages(message):
> 	print(message)
> 	if int(message.chat.id) == int('****'):
> 		try:
> 			bot.send_message(message.chat.id, message.text)
> 		except:
> 			pass
> 	else:
> 		bot.send_message(message.chat.id, message.text)
> 		bot.send_message(message.chat.id, '%s, wait please 👍'%message.chat.username)
```

2) And how to forward messages, that was forwarded to bot without any annotation. (for example user forward post from chanel with photo & text, and doesn't make any annotation to it)

**Comment by mrpes** [comment]
If you wanna make echo-bot, you need to handle all content types.
Or, you can just [forward messages](https://core.telegram.org/bots/api#forwardmessage)

```python
@bot.message_handler(func=lambda m: True)
def on_message(message):
    if int(message.chat.id) == int('****'):
        bot.forward_message(
            chat_id=message.chat.id, 
            from_chat_id=message.chat.id, 
            message_id=message.message_id)
```
