### ISSUE TITLE
'text' as content_types default

### ISSUE THREAD

**Issue by fgallaire** [eternnoir/pyTelegramBotAPI#925]
`'text'` is the default value of the `content_types` handlers parameter but:

1) It's not consistent: all other parameters default to `None`
2) The expected behaviour for most people is probably a "catch-all"
3) I don't understand the recent implementation change with the `None` default value manually changed to `'text'`

**Comment by mrpes** [comment]
This will cause a backward compatibility issue... I guess? For sure it's a bad practice not to specify content type if your program is sensitive to it, but if someone did it, yeah, it will cause a backward compatibility issue

**Comment by fgallaire** [comment]
In fact it's a question: why is `text` the `content_types` default, I don't understand this choice

**Comment by fgallaire** [comment]
@Badiboy I still not understand why ? and the recent implementation change with the None default value manually changed to 'text' ?

**Comment by Badiboy** [comment]
It exists "as is" for a long time. All who used it already deal with it.
Definitely I see no reasons to change it now.

**Comment by fgallaire** [comment]
@Badiboy agree not to change, my question about the implementation, why not use keyword argument anymore ?

**Comment by Badiboy** [comment]
Let's better go to https://github.com/eternnoir/pyTelegramBotAPI/issues/910#issuecomment-721192803
