### ISSUE TITLE
Connection error handler

### ISSUE THREAD

**Issue by Jzarecta** [eternnoir/pyTelegramBotAPI#93]
My bot gets dc frequently, any error handler to avoid it from crashing and just getting some kind of idling connectivity process?
```
2015-10-29 10:55:19,095 (__init__.py:159 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 504 Gateway Time-out. Response body: [b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.6.2</center>\r\n</body>\r\n</html>\r\n']"
```

**Comment by Nesffer** [comment]
+1 Me too.

**Comment by el3ctron** [comment]
+1 me too

**Comment by Jzarecta** [comment]
I think we need a Network error handler to avoid crashing the script when
the datapoint becomes unresponsive. Looking at the init file should be
somewhere around telebot/init.py line 100

On Fri, Oct 30, 2015 at 6:35 PM, el3ctron <notifications@github.com> wrote:

> +1 me too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eternnoir/pyTelegramBotAPI/issues/93#issuecomment-152680075>
> .
>



-- 
Alexandro Colorado
Apache OpenOffice Contributor
9060 55AB FFD2 2F02 0E1A  3409 599C 14FC 9450 D3CF

**Comment by eternnoir** [comment]
Do you try let none_stop flag be true at polling method?

```
bot.polling(none_stop=True)
```

**Comment by Kondra007** [comment]
Same problem even with `none_stop=True`
Using webhooks, however, solved this problem

**Comment by davboc** [comment]
Same problem for me.

Thanks for everything guys

**Comment by Maksadbek** [comment]
The same issue with on by bot

**Comment by davboc** [comment]
No problem since I used "bot.polling(none_stop=True)"...

**Comment by GooDeeJaY** [comment]
Even there is `none_stop` is `True`,
Sometimes I'm getting `ConnectionError`
`('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))`

How to handle that?
