### ISSUE TITLE
new_chat_members - first_name

### ISSUE THREAD

**Issue by dducted** [eternnoir/pyTelegramBotAPI#932]
I have been trying to get the `first_name` from `new_chat_members` but without success.

I already tried `message.new_chat_members.first_name`, `message.new_chat_member.first_name`, `message.new_chat_participant.first_name`.

Extracted the `message` json feed:
![img](https://i.imgur.com/i9z3vnt.png)

Any idea what I am doing wrong? Thanks!

**Comment by Badiboy** [comment]
message.new_chat_members[0].first_name

**Comment by dducted** [comment]
Awesome, thank you!
