### ISSUE TITLE
 rate-limiting feature

### ISSUE THREAD

**Issue by bitog** [eternnoir/pyTelegramBotAPI#933]
Hi there,

I was wondering if telebot comes with a ` rate-limiting feature` to properly handle `429` errors? I am sending bulb messages and was simply wondering if I will get hit by the `30 messages per seconds`  limitation fromTelegram. More [here](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this).

**Comment by mrpes** [comment]
As far as I know, telebot does not come with rate-limiting. But you can write it yourself. Handle `ApiTelegramException` (will come in next update, or just install library from github) and get its `result_json` parameter. This is just json telegram returned. I never handled telegram errors but I guess it will look like this:
```python
sended=False
while not sended:
    try:
        # bot.send_message(....), or something
    except ApiTelegramException as err:
        if err.result_json['error_code']==429:
            time.sleep(0.5) # wait for 0.5 seconds
        else:
            raise # reraise exception if error_code is not 429
    else:
        sended = True
```

**Comment by dducted** [comment]
Awesome, thank you so much @mrpes! In case I am getting hit by the 429 error the remaining messages will be sent after the `0.5` sleep time?
