### ISSUE TITLE
Sending a thumb

### ISSUE THREAD

**Issue by dominon12** [eternnoir/pyTelegramBotAPI#943]
Hi,

I tried to send an audio file with a thumb, but got an error: "TypeError: send_audio() got an unexpected keyword argument 'thumb'". I checked send_audio method and found that it doesn't have this arg. 

1. pyTelegramBotAPI == 3.7.2
2. MacOS
3. Python 3.8

**Comment by mrpes** [comment]
Try to install latest version from github. Clone repo and run `pip install -r requirements.txt`
![img](https://user-images.githubusercontent.com/68982655/90007704-a9d8c080-dcb4-11ea-9305-8624756815c7.png)

**Comment by dominon12** [comment]
> Try to install latest version from github. Clone repo and run `pip install -r requirements.txt` and `python setup.py install`
> ![img](https://user-images.githubusercontent.com/68982655/90007704-a9d8c080-dcb4-11ea-9305-8624756815c7.png)

Thank you, it helped 👍

**Comment by fgallaire** [comment]
Hello, `thumb` is missing in `send_document` !!
