### ISSUE TITLE
how to display "pyTelegramBotAPI" version

### ISSUE THREAD

**Issue by ramonetnet** [eternnoir/pyTelegramBotAPI#951]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

2. What OS are you using?

3. What version of python are you using?

1.- last one, but not sure - how can I know ?

2.- raspbian

3.- cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"

? how can I display (run time if possible) the version of "pyTelegramBotAPI" ?

I can see "static" :
`sebas@pi0alby:~/python/bot $ pip3 show pyTelegramBotAPI | grep Version
Version: 3.7.2
`

**Comment by sebastianet** [comment]
Sorry to say, but your code does not work (for me) :

`nicolau@mars:~/sebas/python/bot$ pip3 install telebot
Collecting telebot
  Downloading https://files.pythonhosted.org/packages/65/e0/2494a32a7857638215d2368fce0c6ae342157d3a74c1dcd8b2305f5da372/telebot-0.0.3.tar.gz
Collecting requests==2.7.0 (from telebot)
  Downloading https://files.pythonhosted.org/packages/26/ff/c71b3943bebdd9f7ceb9e137296370587eb0b33fe2eb3732ae168bc45204/requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 872kB/s 
Building wheels for collected packages: telebot
  Running setup.py bdist_wheel for telebot ... done
  Stored in directory: /home/nicolau/.cache/pip/wheels/ba/db/fd/615d8209580a23b26a7de1a154bfcc9a900481f4775fa63539
Successfully built telebot
Installing collected packages: requests, telebot
Successfully installed requests-2.7.0 telebot-0.0.3

nicolau@mars:~/sebas/python/bot$ python ./veure_versio.py
Python version 3.6.9
Traceback (most recent call last):
  File "./veure_versio.py", line 6, in <module>
    from telebot import version
ImportError: cannot import name 'version'
`

and my code to display telebot version is

`nicolau@mars:~/sebas/python/bot$ cat veure_versio.py 
#!/usr/bin/env python

import platform           
print( "Python version", platform.python_version() )

from telebot import version
print( "telbot version", version.__version__)
`

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/954#issuecomment-678310388

**Comment by Badiboy** [comment]
Works fine for me.
![image](https://user-images.githubusercontent.com/5613421/91102115-31d5a780-e671-11ea-9cda-944dd8572636.png)
Double underscores.

**Comment by sebastianet** [comment]
well, this is the reason I am opening this "issue" - it works OK for you, but nor for me, so I have a problem in my installation
My op system:
`sebas@pi0alby:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
The static version:
`sebas@pi0alby:~ $ pip3 show pyTelegramBotAPI | grep Version
Version: 3.7.2
`
Run time versions:
`sebas@pi0alby:~ $ python
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> print( "python version", platform.python_version() )
python version 3.7.3
>>> import telebot
>>> from telebot import version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'version' from 'telebot' (/usr/local/lib/python3.7/dist-packages/telebot/__init__.py)`

Any ideas ?

**Comment by sebastianet** [comment]
How did I install it ? Herte is the command :
`sudo pip3 install pyTelegramBotAPI`

I dont mind re-installing. 
Can you provide a "clean" and "complete" set of instructions to erase+reinstall ?
Thanks.

**Comment by Badiboy** [comment]
> sudo pip3 uninstall pyTelegramBotAPI
> sudo pip3 install -U pyTelegramBotAPI
>

**Comment by sebastianet** [comment]
Done.. 
Now it works :
`>>> from telebot import version
>>> print( version.__version__ )
3.7.3`

What is the meaning of the "-U" flag ?

**Comment by sebastianet** [comment]
guess it is "upgrade" 
`-U, --upgrade
              Upgrade all packages to the newest available version.  This process is  recursive  regardless  of  whether  a               dependency is already satisfied.
`
It does not provide a clue, but my problemn is solved.

*** THANKS A LOT ***
