### ISSUE TITLE
JSON error when sending msg to channel

### ISSUE THREAD

**Issue by TTimoNN** [eternnoir/pyTelegramBotAPI#96]
error:
"""
Exception in thread WorkerThread3:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/telebot/util.py", line 30, in run
    task(*args, **kwargs)
  File "tg3.py", line 25, in listener
    tb.send_message('@timontest', "chicken")
  File "/usr/local/lib/python2.7/site-packages/telebot/__init__.py", line 204, in send_message
    reply_markup, parse_mode))
  File "/usr/local/lib/python2.7/site-packages/telebot/types.py", line 132, in de_json
    from_user = User.de_json(obj['from'])
KeyError: 'from'
"""
code: https://gist.github.com/anonymous/692ecda96dcc9d5557f7

**Comment by eternnoir** [comment]
Hi @TTimoNN 

What pyTelegramBotAPI version your bot use?

**Comment by TTimoNN** [comment]
using version 0.3.6 on python 2.7.6

**Comment by TTimoNN** [comment]
Downloaded the latest release 1.4.0 but that directly turns into an error (max recursion depth exceeded)

**Comment by eternnoir** [comment]
@TTimoNN 

In your example code. bt.polling() just need call once.

try this, it works fine on v1.4.0.

```python
import telebot

TOKEN = 'token'

def listener(messages):
    for m in messages:
        chatid = m.chat.id
        if m.content_type == 'text':
            text = m.text

            if text.startswith('!channel'):
                tb.send_message('@timontest', "chicken")

            else:
                pass

tb = telebot.TeleBot(TOKEN)
tb.set_update_listener(listener)
tb.polling(none_stop=True)

while True:
    pass
```

**Comment by TTimoNN** [comment]
Seems like the wrong polling method caused the 1.4.0 to crash. sending a message to a channel works now without an error.
Sidenote, it also send the message to the channel on version 0.3.6 but it gave an json error.
Thanks!

**Comment by eternnoir** [comment]
> Sidenote, it also send the message to the channel on version 0.3.6 but it gave an json error.

Yes, when in 0.3.6 Telegram official api message's from must have value. So in 0.3.6 pyTelegramBotAPI didn't check from is exist or not in json. But when channel supported, from attribute could be empty in message json.
