### ISSUE TITLE
Problems with 3.7.3

### ISSUE THREAD

**Issue by txolo99** [eternnoir/pyTelegramBotAPI#961]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.3

2. What OS are you using?
Linux 4.1.20-1.9

3. What version of python are you using?
2.7.16

When I start my application it throws this error:

```
import telebot
  File "/usr/lib/python2.7/site-packages/telebot/__init__.py", line 23, in <module>
    from telebot import apihelper, types, util
  File "/usr/lib/python2.7/site-packages/telebot/apihelper.py", line 18, in <module>
    from telebot import types
  File "/usr/lib/python2.7/site-packages/telebot/types.py", line 829
    def add(self, *args, row_width=None):
                                 ^
SyntaxError: invalid syntax
```

**Comment by Badiboy** [comment]
Python2 is not supported any more due to end-of-life.

**Comment by txolo99** [comment]
> Python2 is not supported any more due to end-of-life.

Your text in the readme:

Getting started.
This API is tested with **Python 2.6, Python 2.7**, Python 3.4, Pypy and Pypy 3. There are two ways to install the library:

Installation using pip (a Python package manager)*:

Please change this for other people

**Comment by Badiboy** [comment]
Sorry, I miss that this is presented in the Readme. I'll update it ASAP.
