### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by evdmux** [eternnoir/pyTelegramBotAPI#962]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.3
2. What OS are you using?
Mac OS Catalina 10.15.6
3. What version of python are you using?
3.7

Good afternoon. I would like to make a bot that will forward messages from certain Viber groups to Telegram. Can someone help to understand this topic and help make this very bot? Thank you in advance.

**Comment by BLUE-DEVIL1134** [comment]
you will need multiple bots
one from viber to localserver then one from localserver to tg

**Comment by Badiboy** [comment]
This topic is outside of the pyTelegramBotAPI.
