### ISSUE TITLE
thumb not working in send_document()

### ISSUE THREAD

**Issue by fgallaire** [eternnoir/pyTelegramBotAPI#964]
Hello,

The newly added thumb argument works fine in send_document() when the document is send as an InputFile but not when the document is sent as String (file_id or url)

**Comment by Badiboy** [comment]
https://core.telegram.org/bots/api#senddocument

![image](https://user-images.githubusercontent.com/5613421/91346241-3329e000-e7e9-11ea-8823-5bae21ce72dd.png)

So:
1. No file_id.
2. I suppose that URLs are also not working.
3. String there is only 

I think we should update all send_xxx methods to accept only Files as thumb...

**Comment by fgallaire** [comment]
hello @Badiboy I don't speak of the thumb but of document itself.
When I send the document by String and thumb as Fils at doesn't work but it should

**Comment by Badiboy** [comment]
@fgallaire sorry, I was not attentive. I'll check what's up.

**Comment by fgallaire** [comment]
@Badiboy about the String choice, de theoricaly have to support it as it's part of the API.
What I understand is that thé String is not the file_id or URL string, but a String of the form “attach://<file_attach_name>” with <file_attach_name> an user choosed name not conflicting with others parameters, not possible actualy as add an unknown parameter throws an exception with pyTelegramBotAPI

**Comment by fgallaire** [comment]
@Badiboy maybe you're right and it's not possible, not sure of the mining of Telegram specs, but other libs seems to have the same limitation.

**Comment by fgallaire** [comment]
@Badiboy maybe you're right and it's not possible, not sure of the mining of Telegram specs, but other libs seems to have the same limitation.

**Comment by fgallaire** [comment]
"Ignored if the file is not uploaded using multipart/form-data", I understand now, so not possible you were right @Badiboy

**Comment by Badiboy** [comment]
Let it stays open. I don't think (yet) that this problem is fundamential, I should pay some attention on code. :)
