### ISSUE TITLE
TypeError: edit_message_text() got multiple values for argument 'text'

### ISSUE THREAD

**Issue by Essay97** [eternnoir/pyTelegramBotAPI#965]
I'm using pyTelegramBotAPI version 3.7.3 running with Python 3.5.9

If I try to run this code snippet

`a = bot.send_message(message.chat.id, "Example")`
`bot.edit_message_text(message.chat.id, a.message_id, text="Changed")`

I get this error
`TypeError: edit_message_text() got multiple values for argument 'text'`

Am I doing something wrong?

**Comment by Badiboy** [comment]
>     def edit_message_text(self, text, chat_id=None, message_id=None, inline_message_id=None, parse_mode=None,
>                           disable_web_page_preview=None, reply_markup=None):
>
