### ISSUE TITLE
HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=9999)

### ISSUE THREAD

**Issue by mlino** [eternnoir/pyTelegramBotAPI#966]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

pyTelegramBotAPI    3.7.3

2. What OS are you using?

Raspbian GNU/Linux 10 (buster)

3. What version of python are you using?

Python 3.7.3

Hi There!

I'm using a simple script to send a message to the Telegram group and getting the error mentioned on the title. 

```
while True:
        with open('/run/data.json') as data_file:
            data = json.load(data_file)
            try:
                processList(data["aircraft"], icaolist, flightlist, squawklist, processed)
            except Exception as e:
                print(e)
            time.sleep(30)
```

So, every 30 seconds, the script reads the JSON file and compares the values found with the values existing on the processed parameter.  If there is a new value the send a message to the group using the following code.

```
TOKEN = '111111111111111111111111111111111111111'
tb = telebot.TeleBot(TOKEN, parse_mode=None)

```
And them in the processList function I call:

`tb.send_message(chat_id, msg_content)`

In the same function, I also send a message as a twitter bot like this:

`api.update_status(msg_content)`

I have no problem at all send to twitter, but I'm getting the above error when sending it to the Telegram.

I appreciate any input on this issue. Thanks!

**Comment by SteveImmanuel** [comment]
What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 3.7.3

What OS are you using?
Ubuntu 18.04 LTS

What version of python are you using?
Python 3.8 running on Docker

Same thing happens to me. My code in a nutshell is:
```
import telebot

@bot.message_handler(commands=['help'])
def send_help(message):

@bot.message_handler(commands=['start'])
def send_welcome(message):

@bot.message_handler(commands=['subscribe'])
def register_user(message):

@bot.message_handler(commands=['unsubscribe'])
def unregister_user(message):

def push_message(chat_id, message):
    bot.send_message(chat_id, message)


if __name__ == "__main__":
    bot.polling()
```

In addition, I also run one more thread to handle the push message which will poll every 60 seconds. When looking on the Docker logs, I got:
```
ERROR - TeleBot: "ReadTimeout occurred, args=(ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=9999)"),)
```
Then, the bot no longer responsive (cannot send back response), however the push message that I set up (with the other thread) still works and can send me a message.

Any help is greatly appreciated, thanks!

**Comment by Badiboy** [comment]
```
while(True):
    try:
        bot.infinity_polling()
    except:
        pass

```

**Comment by khumoyun2008** [comment]
The exception is from requests package. Perhaps need to replace requests package.
There is a network problem between your server and telegram's api.

and:
Can you try adding this line before polling()?

apihelper.RETRY_ON_ERROR = True
bot.polling()

if u r on ubuntu vps, use service files

**Comment by SteveImmanuel** [comment]
Thx, I ended up using the web hook instead of the infinite polling to reduce the possibility of a timeout. So far it works like a charm.
