### ISSUE TITLE
Threading issue

### ISSUE THREAD

**Issue by XazkerBoy** [eternnoir/pyTelegramBotAPI#968]
Hello! I have a problem with both (threaded and not threaded) versions of TeleBot. 

1. pyTelegramBotAPI==3.7.3

2. Windows 10, Windows Server 2012, Ubuntu 18.04...

3. Python 3.6.7

I have a function that recieves a message, starts a new Thread and passes the message into the function.
```python
Thread(target=threaded_func, args=(message.chat.id, some_var, int(some_var1))).start()

def threaded_func(chat_id, some_var, some_var1):
    ...
    return
```

The function in the thread should do some operations (+edit the message) and end, closing the Thread. The problem is that after starting it creates many threads (1 that executes my function and 1 unnecessary)
[Before starting](https://i.imgur.com/THJnggq.png)
[After](https://i.imgur.com/jtu6ob1.png)
(This is the unthreaded version of TeleBot [threaded=False]. The threaded one creates the double amount of unnecessary Threads. I suppose Dummy-64 belongs to Telebot, because Dummy-6 belongs to it)
The problem is that after my function ends, it disappears from the Thread list, but the TeleBot Thread (Dummy-64) remains there. And so, after a couple of function starts, the memory is full of Dummy-Like Threads

I hope I explained well, if any other details needed, I'll add them. Thanks in advice!

**Comment by Badiboy** [comment]
Dummy is not the pyTelegramBotAPI threads.
Library creates:
1. WorkerThread(s)
2. PollingThread(s)
if it works in Threading mode. And no threads in non-threading mode. So you should find in the code who creates Dummy-threads...

**Comment by XazkerBoy** [comment]
After some debug I got interesting results:
[Before **send()** method](https://imgur.com/a/g4P39Rx)
[After](https://imgur.com/a/R4i7wIy)

**Comment by XazkerBoy** [comment]
After some debug I got interesting results:
[Before **send()** method](https://imgur.com/a/g4P39Rx)
[After](https://imgur.com/a/R4i7wIy)

**Comment by XazkerBoy** [comment]
After some debug I got interesting results:
[Before **send()** method](https://imgur.com/a/g4P39Rx)
[After](https://imgur.com/a/R4i7wIy)

**Comment by Badiboy** [comment]
I tried again, but I cannot reproduce appearing of DummyThreads. 

AFAIK, DummyThreads are replacement of normal threads (https://docs.python.org/2/library/dummy_threading.html) when threads are not available, so it seems that some other libraries in your library stack creates them. But I'm not sure about it.
