### ISSUE TITLE
Not getting command from other bots

### ISSUE THREAD

**Issue by Noah-Rod** [eternnoir/pyTelegramBotAPI#971]
Hello I am making two Bots which should execute command from each other (no doubles, all different).
I made a python project which Handle all of that.

The issue is, that the bot is never receiving a command from the other bot.
I tired it with direct cmds: /cmd@bot
If I send the command as a normal user I get a response.

The privacy mode is disabled.

1. What version of pyTelegramBotAPI are you using?
3.73

2. What OS are you using?
Windows 10

3. What version of python are you using?
3.8

I hope I explained well. Thank you in advice.

**Comment by Badiboy** [comment]
In Telegram bots do not see other bots. System restriction.
