### ISSUE TITLE
How to run some task periodically ?

### ISSUE THREAD

**Issue by kaushik-rishi** [eternnoir/pyTelegramBotAPI#974]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.3
2. What OS are you using?
Windows 10
3. What version of python are you using?
3.8.3

**Issue** : easy
**Aim** : I want to run a request periodically and give the user updates
**Problem** : I am not able to figure out how to do that
**Progress** : All i'm able to do is send replies to user messages

I could'nt find some function on how to run a task periodically. It would be of great help if someone throwed some light on my issue

**Comment by Badiboy** [comment]
https://pypi.org/project/schedule/
