### ISSUE TITLE
Problems with ssl.PROTOCOL_TLSv1_2

### ISSUE THREAD

**Issue by MaximScherbatov** [eternnoir/pyTelegramBotAPI#976]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? -pyTelegramBotAPI 3.7.3

2. What OS are you using? -ubuntu-minimal-2004-focal-v20200907

3. What version of python are you using? -Python 3.8.2

Greetings!
Please help me understand the code in the "webhook_aiohttp_echo_bot.py" example:
`# Remove webhook, it fails sometimes the set if there is a previous webhook
bot.remove_webhook()

# Set webhook
bot.set_webhook(url=WEBHOOK_URL_BASE + WEBHOOK_URL_PATH,
                certificate=open(WEBHOOK_SSL_CERT, 'r'))

# Build ssl context
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
context.load_cert_chain(WEBHOOK_SSL_CERT, WEBHOOK_SSL_PRIV)

# Start aiohttp server
web.run_app(
    app,
    host=WEBHOOK_LISTEN,
    port=WEBHOOK_PORT,
    ssl_context=context,
)`
why does this error occur:
![Снимок](https://user-images.githubusercontent.com/70111181/93386076-d497d500-f86f-11ea-9fcf-6614fb8491ca.JPG)

**Comment by Badiboy** [comment]
Seems that it's outside of pyTelegrabTopAPI library. Look like that something wrong with asyhcio or ssl libraries.
