### ISSUE TITLE
ConnectionError: ('Connection aborted.', OSError(24, 'Too many open files'))

### ISSUE THREAD

**Issue by psded** [eternnoir/pyTelegramBotAPI#979]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI==3.7.3

2. What OS are you using?
ubuntu-18

3. What version of python are you using?
Python 3.6.9

https://sentry.io/share/issue/c2c839504ba649bdb82c2b8676ff6dd6/ - полная инфа об ошибке

Если что, сервак очень много работает с сокетами.

**Comment by Badiboy** [comment]
Ну, ошибка ОС, слишком много открыто файлов (сетевые соединения тоже файлы). При чем тут бот? :) Если так много надо - в линукс есть настройка с этим количеством, можно увеличить..
