### ISSUE TITLE
How i get reply_markup with force_reply and custom keyboard?

### ISSUE THREAD

**Issue by Tiabaldu1990** [eternnoir/pyTelegramBotAPI#980]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
**The last one**
2. What OS are you using?
**Windows 10**
3. What version of python are you using?
**3.8**

Hi, friend. Can you help me with my problem? How can I get a **reply_markup** with my **keyboard** and **force_reply**? Can you help with that? I can't find an answer in this documentation.

**Comment by Tiabaldu1990** [comment]
Does anyone help?

**Comment by dtalkachou** [comment]
If you want to pin keyboard (`types.ReplyKeyboardMarkup`) to `force_reply` for quick user answer, that is not posible.

**Comment by MasterGroosha** [comment]
You cannot use custom keyboard with force reply at the same time.
https://core.telegram.org/bots/api#sendmessage
