### ISSUE TITLE
Sending photo doesn't work on the latest version

### ISSUE THREAD

**Issue by asolovyov03** [eternnoir/pyTelegramBotAPI#988]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.3
2. What OS are you using?
Windows
3. What version of python are you using?
3.8.5

I was trying to send photo using telebot, but it caused an error "AttributeError: module 'PIL' has no attribute 'Image'". When I changed pyTelegramBotAPI version to 3.7.2 without editing code, this problem was solved. It seems like there is some kind of problem with packages. Thank you in any case!

**Comment by dtalkachou** [comment]
Please, see this issue https://github.com/eternnoir/pyTelegramBotAPI/issues/986

**Comment by Badiboy** [comment]
The issue is fixed but the fixed version is not published yet.
Use GIT version instead:
```
pip uninstall pyTelegramBotAPI
pip install -U git+https://github.com/eternnoir/pyTelegramBotAPI.git

```
