### ISSUE TITLE
Another repo looks like a copy of pyTelegramBotAPI

### ISSUE THREAD

**Issue by MasterGroosha** [eternnoir/pyTelegramBotAPI#992]
As noted in https://github.com/MA24th/tgbotapi/issues/2 (_edit: they deleted my issue, lol_), their "framework" looks too similar to pyTelegramBotAPI, the documentation is almost identical and many code parts differ only in variables naming.

How to deal with it is completely up to you though.
Notifying @eternnoir

**Comment by Badiboy** [comment]
He want to promote his personal service with this library copy.

I think we should let him be happy. :)

**Comment by MasterGroosha** [comment]
@Badiboy it's up to you of course, feel free to close this repo if you're OK with such behaviour

**Comment by Badiboy** [comment]
But what can be done? Writing complains to GPL vioulation? :)

**Comment by MasterGroosha** [comment]
I don't know honestly ¯\_(ツ)_/¯
Though blatantly copying work of other people without any attribution is not a good thing either. Especially if it's not MIT

**Comment by MasterGroosha** [comment]
I think I will close this issue because that person added a reference to pyTelegramBotAPI: https://github.com/MA24th/tgbotapi/commit/98e82a57efbce03ee6a90d54b0ead6838510b405
