### ISSUE TITLE
animation and document content_type confilict

### ISSUE THREAD

**Issue by TahaPY** [eternnoir/pyTelegramBotAPI#993]
1. What version of pyTelegramBotAPI are you using?  3.7.3

2. What OS are you using? windows and ubuntu

3. What version of python are you using? 3.8

when you send gif telegram gives you animation and document at same time in update and when you parse that first if is animation and second is document because of this the content_type set document not animation

for fix this you can change order of if statement or check if animation is available with document just parse animation or set content_type to animation
[image of update from telegram](https://imgur.com/a/fZTaJe0)

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1005
