### ISSUE TITLE
Change params for send_chat_action method

### ISSUE THREAD

**Issue by makisukurisu** [eternnoir/pyTelegramBotAPI#994]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

3.7.3

2. What OS are you using?

Does not matter

3. What version of python are you using?

3.8 (but still does not matter)

In [TeleBotAPI](https://core.telegram.org/bots/api#sendchataction), there is no such a parameter as timeout, but in this module, there is.

I was confused by the fact that timeout is not working as I wanted to. (I need to show that bot is texting for a little (1-2 s, not 5), while changing message)

**Comment by Badiboy** [comment]
If something is confusing you - it does not mean that this something should be immediately changed.
